project:
  type: book
  output-dir: docs

  
crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")
    
book:
  title: "Bio Data Science"
  author: "Prof. Dr. Jochen Kruppa"
  link-citations: yes
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - preface.qmd
    - literature.qmd
    - part: example-preface.qmd
      chapters:
      - example-fleas-dogs.qmd
      - example-fleas-dogs-cats.qmd
      - example-outro.qmd
    - part: programing-preface.qmd
      chapters:
      - programing-letters-numbers.qmd
      - programing-import.qmd
      - programing-outro.qmd
    - part: eda-preface.qmd
      chapters:
      - formula.qmd
      - eda-descriptive.qmd
      - eda-ggplot.qmd
    - part: stat-tests-preface.qmd
      chapters:
      - stat-tests-ttest.qmd
    - part: distributions-preface.qmd
      chapters: 
      - distributions-normal.qmd
      - distributions-poisson.qmd
    
    
bibliography: references.bib
lang: de 
reference-location: margin

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
    html-math-method: webtex

