project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")
    
book:
  title: "Bio Data Science"
  author: "Prof. Dr. Jochen Kruppa"
  date: "25. August 2022"
  link-citations: yes
  cover-image: images/cover.png
  search: true
  # repo-url: https://github.com/jjallaire/hopr/
  # repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-footer: 
    left: "Copyright 2022, Jochen Kruppa" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
  chapters:
    - index.qmd
    - organisation.qmd
    - literature.qmd
    - preface.qmd
    - part: example-preface.qmd
      chapters:
      - example-fleas-dogs.qmd
      - example-fleas-dogs-cats.qmd
      - example-fleas-dogs-cats-foxes.qmd
      - example-fleas-dogs-cats-foxes-site.qmd
      - example-fleas-dogs-cats-length-weight.qmd
    - part: programing-preface.qmd
      chapters:
      - programing-letters-numbers.qmd
      - programing-basics.qmd
      - programing-import.qmd
      - programing-dplyr.qmd
    - part: eda-preface.qmd
      chapters:
      - eda-descriptive.qmd
      - eda-ggplot.qmd
    - part: stat-tests-preface.qmd
      chapters:
      - stat-tests-ttest.qmd
      - stat-tests-anova.qmd
      - stat-tests-utest.qmd
      - stat-tests-kruskal.qmd      
      - stat-tests-chi-test.qmd
      - stat-diagnostisches-testen.qmd
      - stat-tests-posthoc.qmd
    - part: distributions-preface.qmd
      chapters: 
      - distributions-normal.qmd
      - distributions-poisson.qmd
    - part: stat-modeling-reg-preface.qmd
      chapters: 
      - stat-modeling-gaussian.qmd
      - stat-modeling-mixed.qmd
  appendices:
    - app-example-analysis.qmd
    - app-r-tutorial.qmd
    - app-how-to-write.qmd
    
bibliography: references.bib
lang: de 
reference-location: margin

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true
  pdf:
    documentclass: scrreport

