project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")
    
book:
  title: "Skript Bio Data Science"
  author: "Prof. Dr. Jochen Kruppa"
  date: "14. November 2022"
  link-citations: yes
  cover-image: images/cover.png
  # search: true
  # repo-url: https://github.com/jjallaire/hopr/
  # repo-actions: [edit]
  # downloads: [pdf, epub]
  # downloads: [pdf]
  # sharing: [twitter, facebook]
  # page-footer: 
  #  left: "Version von 2022 | Jochen Kruppa" 
  #  right: 
  #    - icon: github
  #      href: https://github.com/jkruppa
  #    - icon: youtube 
  #      href: https://www.youtube.com/c/JochenKruppa
  chapters:
    - index.qmd
    - organisation.qmd
    - literature.qmd
    - preface.qmd
    - part: example-preface.qmd
      chapters:
      - example-fleas-dogs.qmd
      - example-fleas-dogs-cats.qmd
      - example-fleas-dogs-cats-foxes.qmd
      - example-fleas-dogs-cats-foxes-site.qmd
      - example-fleas-dogs-cats-length-weight.qmd
      - example-gummi-bears.qmd
      - example-complex.qmd
    - part: programing-preface.qmd
      chapters:
      - programing-letters-numbers.qmd
      - programing-basics.qmd
      - programing-import.qmd
      - programing-dplyr.qmd
    - part: eda-preface.qmd
      chapters:
      - eda-descriptive.qmd
      - eda-ggplot.qmd
      - eda-transform.qmd
      - eda-distribution.qmd
    - part: stat-tests-preface.qmd
      chapters:
      - stat-tests-basic.qmd
      - stat-tests-theorie.qmd
      - stat-tests-effect.qmd
      - stat-tests-ttest.qmd
      - stat-tests-anova.qmd
      - stat-tests-ancova.qmd
      - stat-tests-utest.qmd
      - stat-tests-kruskal.qmd    
      - stat-tests-friedman.qmd  
      - stat-tests-chi-test.qmd
      - stat-tests-diagnostic.qmd
      - stat-tests-pretest.qmd
      - stat-tests-posthoc.qmd
    - part: stat-linear-reg-preface.qmd      
      chapters: 
      - stat-linear-reg-basic.qmd
      - stat-linear-reg-quality.qmd
      - stat-linear-reg-corr.qmd
    - part: stat-modeling-preface.qmd
      chapters: 
      - stat-modeling-basic.qmd
      - stat-modeling-variable-selection.qmd
      - stat-modeling-outlier.qmd
      - stat-modeling-missing.qmd
      - stat-modeling-sensitivity.qmd
      - stat-modeling-gaussian.qmd
      - stat-modeling-poisson.qmd
      - stat-modeling-multinom.qmd      
      - stat-modeling-logistic.qmd
      - stat-modeling-mixed.qmd
      - stat-modeling-gee.qmd
      - stat-modeling-non-linear.qmd
    - part: experimental-design-preface.qmd
      chapters: 
      - experimental-design-basic.qmd
      - experimental-design-samplesize.qmd
    - part: classification-preface.qmd
      chapters: 
      - classification-basic.qmd
      - classification-knn.qmd
      - classification-randomforest.qmd
      - classification-svm.qmd
      - classification-neural-networks.qmd
      - classification-deep-learning.qmd
      - classification-model-compare.qmd
 #   - part: bayes-preface.qmd
  #    chapters: 
  #    - bayes-basic.qmd
  appendices:
    - app-example-analysis.qmd
    - app-r-tutorial.qmd
    - app-how-to-write.qmd
    - app-bewertungsbogen.qmd
    - module.qmd
    
bibliography: references.bib
lang: de 

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true
#  pdf:
#    documentclass: scrreport
#scrreport
#  epub:
#    cover-image: cover.png
