project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —    
    
book:
  title: "Bio Data Science"
  subtitle: "Der endgültige Leitfaden"
  author: "<a href='https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/'>Prof. Dr. habil. Jochen Kruppa-Scheetz</a>"
  date: "09. December 2024"
  favicon: cover2024_favi.png
  description: "*Ein Kochbuch mit Rezepten aus der Bio Data Science, Biostatistik, Biometrie und Statistik zum selber nachkochen!*"
  keyword: programmieren, data science, biostatistik, statistik, biometrie, maschinelles lernen, statistisches modellieren, landwirtschaftliche Daten
  url: https://jkruppa.github.io/
  repo-url: https://github.com/jkruppa/jkruppa.github.io/
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  open-graph:
    image: https://github.com/jkruppa/jkruppa.github.io/raw/master/cover2024.png
    description: Ein Kochbuch mit Rezepten der Bio Data Science, Biostatistik, Biometrie und Statistik
  search: true
  page-footer:
    left: |
      Bio Data Science wurde von <a href="https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/">Jochen Kruppa-Scheetz</a> geschrieben. 
    right: |
      Dieses Openbook wurde mit <a href="https://quarto.org/">Quarto</a> erstellt.
  chapters:
    - index.qmd
    - organisation.qmd
    - literature.qmd
    - forschungsprozess.qmd
    - abschlussarbeit.qmd
    - part: example-preface.qmd
      chapters:
      - example-fleas-dogs-cats.qmd
      - example-gummi-bears.qmd
      - example-complex.qmd
      - example-database.qmd
    - part: programing-preface.qmd
      chapters:
      - programing-letters-numbers.qmd
      - programing-basics.qmd
      - programing-import.qmd
      - programing-dplyr.qmd
      - programing-strings.qmd
      - programing-purrr-furrr.qmd
      - programing-quarto-shiny.qmd
    - part: eda-preface.qmd
      chapters:
      - eda-descriptive.qmd
      - eda-ggplot.qmd
      - eda-distribution.qmd
      - eda-transform.qmd
    - part: stat-tests-preface-theory.qmd
      chapters:
      - stat-tests-basic.qmd
      - stat-tests-theorie.qmd
      - stat-tests-effect.qmd
      - stat-tests-pretest.qmd
    - part: experimental-design-preface.qmd
      chapters: 
      - experimental-design-r.qmd
      - experimental-design-basic.qmd
      - experimental-design-advanced.qmd
      - experimental-design-samplesize.qmd
    - part: stat-tests-preface-app.qmd 
      chapters:
      - stat-tests-R.qmd
      - stat-tests-ttest.qmd
      - stat-tests-anova.qmd
      - stat-tests-ancova.qmd
      - stat-tests-utest.qmd
      - stat-tests-kruskal.qmd    
      - stat-tests-friedman.qmd  
      - stat-tests-chi-test.qmd
      - stat-tests-anteil-test.qmd
      - stat-tests-diagnostic.qmd
      - stat-tests-trendtest.qmd  
      - stat-tests-permutationstest.qmd
      - stat-tests-posthoc.qmd
    - part: stat-linear-reg-preface.qmd      
      chapters: 
      - stat-linear-reg-basic.qmd
      - stat-modeling-basic.qmd
      - stat-linear-reg-quality.qmd
      - stat-linear-reg-corr.qmd
      - stat-modeling-outlier.qmd
      - stat-modeling-variable-selection.qmd
      - stat-modeling-missing.qmd
      - stat-modeling-sensitivity.qmd
    - part: stat-modeling-preface.qmd
      chapters: 
      - stat-modeling-R.qmd
      - stat-modeling-gaussian.qmd
      - stat-modeling-poisson.qmd
      - stat-modeling-beta.qmd
      - stat-modeling-multinom.qmd      
      - stat-modeling-logistic.qmd
      - stat-modeling-prob-model.qmd
      - stat-modeling-mixed.qmd
      - stat-modeling-gee.qmd
      - stat-modeling-non-linear.qmd
      - stat-modeling-robust-quantile.qmd
      - stat-modeling-survival.qmd
      - stat-modeling-noninferiority.qmd
      - stat-modeling-meta.qmd
      - stat-modeling-cluster.qmd
      - stat-modeling-pca.qmd
      - stat-modeling-survey.qmd
    - part: time-space-preface.qmd
      chapters: 
      - time-space-pseudo-time-series.qmd
      - time-space-time-series.qmd
      - time-space-spatial-data.qmd
    - part: classification-preface.qmd
      chapters: 
      - classification-basic.qmd
      - classification-data.qmd   
      - classification-pre-processing.qmd   
      - classification-model-compare.qmd
      - classification-knn.qmd
      - classification-randomforest.qmd
      - classification-svm.qmd
      - classification-neural-networks.qmd
#   - part: bayes-preface.qmd
#     chapters: 
#     - bayes-basic.qmd
    - part: abspann.qmd
      chapters:
      - app-spielecke.qmd

bibliography: references.bib
csl: bioscience.csl
lang: de 

format:
  html: 
    theme:
      - journal
      - bioscience.scss
    cover-image: cover2025.png
    code-annotations: hover
    lightbox: true
    toc-expand: 2
    code-fold: show
    highlight-style: tango
    code-block-border-left: true
    code-summary: "R Code [zeigen / verbergen]"
    code-tools: true
    mermaid:
      theme: neutral
      htmlLabels: true
