project:
  type: book
  output-dir: docs

  
crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")
    
book:
  title: "Bio Data Science"
  author: "Prof. Dr. Jochen Kruppa"
  date: "17. August 2022"
  link-citations: yes
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - organisation.qmd
    - literature.qmd
    - preface.qmd
    - part: example-preface.qmd
      chapters:
      - example-fleas-dogs.qmd
      - example-fleas-dogs-cats.qmd
      - example-fleas-dogs-cats-foxes.qmd
      - example-fleas-dogs-cats-foxes-site.qmd
      - example-outro.qmd
    - part: programing-preface.qmd
      chapters:
      - programing-letters-numbers.qmd
      - programing-basics.qmd
      - programing-import.qmd
      - programing-dplyr.qmd
      - programing-outro.qmd
    - part: eda-preface.qmd
      chapters:
      - eda-descriptive.qmd
      - eda-ggplot.qmd
    - part: stat-tests-preface.qmd
      chapters:
      - stat-tests-ttest.qmd
      - stat-tests-anova.qmd
      - stat-tests-utest.qmd
      - stat-tests-kruskal.qmd      
      - stat-tests-chi-test.qmd
      - stat-tests-posthoc.qmd
    - part: distributions-preface.qmd
      chapters: 
      - distributions-normal.qmd
      - distributions-poisson.qmd
  appendices:
    - app-example-analysis.qmd
    - app-r-tutorial.qmd
    - app-how-to-write.qmd
    
bibliography: references.bib
lang: de 
reference-location: margin

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true


