project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —    
    
book:
  title: "Skript Bio Data Science"
  author: "Prof. Dr. Jochen Kruppa"
  date: "02. January 2022"
  link-citations: yes
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - organisation.qmd
    - literature.qmd
    - preface.qmd
    - part: example-preface.qmd
      chapters:
      - example-fleas-dogs-cats.qmd
      - example-fleas-dogs-cats-foxes.qmd
      - example-fleas-dogs-cats-length-weight.qmd
      - example-gummi-bears.qmd
      - example-complex.qmd
    - part: programing-preface.qmd
      chapters:
      - programing-letters-numbers.qmd
      - programing-basics.qmd
      - programing-import.qmd
      - programing-dplyr.qmd
      - programing-strings.qmd
      - programing-purrr-furrr.qmd
    - part: eda-preface.qmd
      chapters:
      - eda-descriptive.qmd
      - eda-ggplot.qmd
      - eda-transform.qmd
      - eda-distribution.qmd
    - part: stat-tests-preface.qmd
      chapters:
      - stat-tests-basic.qmd
      - stat-tests-theorie.qmd
      - stat-tests-effect.qmd
      - stat-tests-ttest.qmd
      - stat-tests-anova.qmd
      - stat-tests-ancova.qmd
      - stat-tests-utest.qmd
      - stat-tests-kruskal.qmd    
      - stat-tests-friedman.qmd  
      - stat-tests-chi-test.qmd
      - stat-tests-diagnostic.qmd
      - stat-tests-pretest.qmd
      - stat-tests-posthoc.qmd
    - part: stat-linear-reg-preface.qmd      
      chapters: 
      - stat-linear-reg-basic.qmd
      - stat-linear-reg-quality.qmd
      - stat-linear-reg-corr.qmd
    - part: stat-modeling-preface.qmd
      chapters: 
      - stat-modeling-basic.qmd
      - stat-modeling-variable-selection.qmd
      - stat-modeling-outlier.qmd
      - stat-modeling-missing.qmd
      - stat-modeling-sensitivity.qmd
      - stat-modeling-gaussian.qmd
      - stat-modeling-poisson.qmd
      - stat-modeling-multinom.qmd      
      - stat-modeling-logistic.qmd
      - stat-modeling-mixed.qmd
      - stat-modeling-gee.qmd
      - stat-modeling-non-linear.qmd
    - part: experimental-design-preface.qmd
      chapters: 
      - experimental-design-basic.qmd
      - experimental-design-samplesize.qmd
    - part: classification-preface.qmd
      chapters: 
      - classification-basic.qmd
      - classification-data.qmd   
      - classification-pre-processing.qmd   
      - classification-model-compare.qmd
      - classification-knn.qmd
      - classification-randomforest.qmd
      - classification-svm.qmd
      - classification-neural-networks.qmd
 #   - part: bayes-preface.qmd
  #    chapters: 
  #    - bayes-basic.qmd
  appendices:
    - app-example-analysis.qmd
    - app-r-tutorial.qmd
    - app-how-to-write.qmd
    - app-bewertungsbogen.qmd
    - module.qmd
    
bibliography: references.bib
lang: de 

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true
