```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Writing principles {#sec-writing}

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

> *"Dicke Bücher sind deswegen dick, weil der Autor nicht die Zeit hatte, sich kurz zu fassen." ----- Walter Moers*

Schreiben ist nicht einfach. *Aber es folgt einem Schema.* Schreiben ist anstrengend und dauert seine Zeit. Ein guter Text wird mehrfach revidiert, umgeschrieben und gelöscht, bis er zu einem guten Text geworden ist. Häufig vergehen mehrere Tage bis man eine Idee so auf das Blatt Papier gebracht hat, dass auch ein Dritter den Text lesen und verstehen kann.

::: callout-note
## Zentraler Gedanke

Der erste Entwurf ist für einen selber, ab dem zweiten geht es um den Leser.
:::

Es geht also am Anfang erstmal darum, Text auf das weiße Blatt zu kriegen.

::: callout-note
## Otto Kruse -- Keine Angst vor dem leeren Blatt

Viele wissenschaftliche Themen kann man erst dann lösen, wenn man alle Aspekte explizit formuliert hat. Das Denken ist dafür insofern nicht genügend vorbereitet, als es immer nur kleine Ausschnitte fokussieren kann. Systematisch denken kann man nur, wenn man schreibt, also die Ergebnisse seines Denkens festhält und mit weiteren Aspekten in Beziehung setzt.
:::

Das ist die Idee vom Schreiben. Andere merken, wie weit du mit deinen Gedanken gekommen bist. Wir bringen komplexe Gedankengänge in die lineare Form des Textes.

## Der Schreibprozess

Der Schreibprozess läuft nach Beginn in den nächsten Wochen und Monaten in mehreren Phasen ab. In jeder Phase ist es wichtig, sich ein gutes Umfeld für konzentriertes Arbeiten zu schaffen, gleichzeitig aber die Kommunikation mit den Betreuenden und anderen Mitschaffenden nicht abreißen zu lassen.

## Zeitplan

Hier ist es wichtig was geschrieben werden soll. Eine Bachelor- und Masterarbeit hat einen klaren Zeitplan, der vorab feststehen muss. Bis wann müssen wie viele Wörter geschrieben sein, damit die Arbeit fertig werden kann. Beide Abschlussformen haben ja unterschiedliche Zeitrahmen. Und das ist wirklich wichtig! Wann sollte man fertig sein mit Programmieren, wie lange soll man sich Zeit für Vortragsvorbereitung nehmen, etc. Auch eine wissenschaftliche Veröffentlichung hat einen Zeitplan! Leider -- das ist der Primat der Forschung -- kann sich der Zeitplan immer wieder ändern, wenn Methoden nicht klappen oder neue Erkenntnisse gewonnen werden. Dennoch muss klar sein, dass in endlicher Zeit -- meist ein Jahr -- ein Paper eingereicht werden kann. Auf dieses Ziel sollten sich alle Einschwören. Sonst ist eine Promotion in endlicher Zeit nicht machbar.

## Ideen entwickeln

Man sammelt Ideen zunächst in der Breite und fokussiert dann, was davon man aufschreiben will. Man liest andere wissenschaftliche Paper, lernt vielleicht noch Grundlagen und Methoden, und macht sich Notizen, was interessant sein könnte, und wo es steht. Natürlich kann man sich bei den Betreuern und Mitschaffenden Hilfe und Anregungen holen, wo man Input herbekommt. Holen heißt aber nicht, dass man gebracht bekommt.

::: callout-note
## OCAR Prinzip

Frage dich, was ist das **O**pening (der Hintergrund der Arbeit), die **C**hallenge (was ist das Problem, was gelöst werden soll?), die **A**ction (was wirst du tun um dieses Problem zu lösen?) und die **R**esults (Was kam dabei raus oder soll rauskommen?)
:::

## Strukturieren

Das grobe Gerüst ist ja vorgegeben. Eine wissenschaftliche Arbeit folgt dem **IMRaD** Schema. Erst die Einleitung (**I**ntroduction), dann die Methoden (**M**ethods), gefolgt von den Ergebnissen (**R**esults) und der Diskussion (**D**iscussion). Am Ende der Einleitung wird nochmal die Fragestellung benannt. Welche Frage soll in der Arbeit beantwortet werden? Dann fehlt noch die Zusammenfassung am Anfang (abstract) und der Schluss bzw. das Fazit (conclusion). So ist das vorgegebene Schema für die Arbeit, das soll mit Inhalt gefüllt werden. Klingt erstmal einfach und ist es auch. Mit Zwischenüberschriften in den einzelnen Abschnitten kann man sich eine grobe Ordnung vorgeben, was in welcher Reihenfolge aufgeschrieben werden soll. Die Struktur innerhalb von Methodenteilen ist zum Beispiel oft gleich, Beschreibung der Studie, Beschreibung der interessierenden Variablen und ihrer Erhebung, Beschreibung der Auswertungsmethodik. Das kommt aber aufs Thema an. Und unterhalb dieser kann man sich wieder Unter-zwischen-unterüberschriften machen. Es wird sowieso noch alles überarbeitet.

::: callout-note
## Grobe Strukturierung nach IMRaD

-   Zusammenfassung

1.  Einleitung
    -   Forschungsfrage
2.  Material und Methoden
3.  Ergebnisse
4.  Diskussion

-   Literatur
:::

Wenn es einen Flowchart gibt, so gibt dieser auch die Struktur vor. Ein Flowchart ist nicht final und ändert sich mit der Zeit! Mach den Flowchart am besten auf einem Blatt Papier. Da kannst du schneller was ergänzen.

::: callout-note
Zeichne einen Flowchart, der aufzeigt was in der Arbeit passiert!
:::

## Rohtexten

Das kann wirklich sloppy sein, in Stichpunkten oder hingerotzt, aber hier soll man sich auch nicht an Details aufhalten, sondern dem Arbeits- und Denkfluss folgen. Gerne auch Denglisch. Lieber erst Text schreiben und dann korrigieren. Wenn das Englische Wort nicht einfällt, das deutsche Hinschreiben. Den Schreibprozess nicht durch im Internet suchen und dann mal was Anderes gucken unterbrechen. Gerade wenn die Arbeit selbst noch im Entstehen ist, schreibt man erst einmal auf, was man tut, was man gemacht, gelernt, oder gelesen hat. Diese Frage stellt sich meist nach den ersten paar Sätzen in einer wissenschaftlichen Arbeit. Worum geht es hier eigentlich? Es könnte alles so einfach sein. Das ist normal. Durch das Aufschreiben werden einem meist die Dinge klarer und uns wird bewusst, wo wir nochmal genauer einhaken müssen.

## Reflektieren

Die Grundideen sind jetzt schon mal auf dem Papier, jetzt muss man sich überlegen, wie daraus ein Text wird. Gut ist es, sich schon an dieser Stelle Feedback von Betreuern oder Kommilitonen zu holen. Das hilft auch, die eigene Perspektive auf den Text zu ändern und ihn aus mehreren Richtungen zu betrachten -- was ist wichtig, was soll viel Platz einnehmen, was fehlt vielleicht noch?

::: callout-note
Was könnte die zentrale Abbildung in den Ergebnissen sein?
:::

Ein guter Ansatz um einen Fokus zu haben!

## Jetzt schreiben wir! Wie geht es am besten?

Dafür geht gut die Hälfte der Schreibzeit drauf. Am wichtigsten sind Inhalt und Struktur, Korrektheit und Verständlichkeit dürfen aber auch nicht unterschätzt werden: Wir nutzen einfache englische Sprache. Das geschriebene Wort muss nicht schlau klingen, sondern der Inhalt muss schlau sein. Keine umständlichen, gekünstelten Verben verwenden, wenn es ein einfaches Verb auch tut. Wir machen es dem Leser einfach. Später wirst du in einem wissenschaftlichen Paper „we" schreiben, da man selten ein Paper alleine schreibt. Um das jetzt hier gleich am Anfang zu üben, schreibst du keine verschachtelten Passivkonstruktionen, sondern „I do/did something". Das fühlt sich erst seltsam an, aber wir als Leser danken dir!

::: callout-important
## Schlecht

After the raw methylation data has been preprocessed, a student t test was used for the differential analysis.
:::

::: callout-tip
## Gut

I used the student t test for the differential analysis after the preprocessing of the raw methylation data.
:::

Wir nutzen auch keine Pronomen, wo man nicht weiß, was diese Pronomen aussagen sollen. Was ist „it" oder „they"?

::: callout-important
## Schlecht

The dog and the cat walk into a house. It eats all the cookies.
:::

::: callout-tip
## Gut

The dog and the cat walk into a house. The cat eats all the cookies.
:::

Wir führen alle Begriffe vorher ein, daher erklären wir diese Begriffe, bevor wir die Begriffe verwenden. Ja, mache Begriffe sind klar, aber welche das sind, ergibt sich manchmal erst auf Nachfrage bei uns und ist für einen Neuling in einem Fachbereich gar nicht zu wissen.

::: callout-important
## Schlecht

I analyzed the NGS data with an ANOVA after checking the residuals with a QQ-plot.
:::

::: callout-tip
## Gut

I analyzed the next generation sequencing data (NGS) with an analysis of variance (ANOVA) after plotting the residuals of the model in a quantile-quantile plot (QQ-plot).
:::

Ist dir der Begriff nicht klar, erkläre ihn. Später können wir immer noch kürzen. Erkenntnisgewinn durch schreiben ist das Ziel.

## Wer macht was? Die Frage des Lesers an jeden einzelnen Satz!

Komme in den **ersten sieben Wörtern** zum Punkt, wer was macht. Subjekt und Prädikat sollen nah beieinander sein und möglichst früh im Satz kommen. Wir schreiben kurze Sätze und vermeiden komplizierte Schachtelsätze.

::: callout-important
## Schlecht

The differential analysis of whole genome genetic data - like methylation pattern or expression analysis - has a long history of different invented methods and I used different analysis methods to find the best method for the analysis of methylation data with repeated measurements.
:::

::: callout-tip
## Gut

\[1\] A long history of different analysis methods like methylation pattern or expression analysis exists. \[2\] Hence, many scientist have invented different analysis methods of whole genome.
:::

## Löschen von Text

Text löschen macht keine Freude. Es ist immer nervig Teile des Textes, den man so mühsam in die Maschine getippt hat, zu löschen. Lege dir eine neue Datei an, in der du alles was du löschen willst reinkopierst. Bei mir heißt die Datei dump.docx oder dump.R oder auch anders. Auf jeden Fall löschst du so keinen Text, sondern bewahrst ihn erstmal auf. Denk immer daran, es geht nicht darum nur viel Text zu produzieren!

## Zum Schluss kommen

Wie Anne und Jochen[^app-how-to-write-1] jetzt in diesem Augenblick musst du zum Schluss kommen. Kein Text ist perfekt, kein Gedankengang so klar niedergeschrieben, wie er sein könnte. Aber irgendwann muss gut sein. Lass das Perfekte nicht der Feind des Guten sein. Dieser Leitfaden ist *good enough* und somit muss es reichen. Viel Erfolg!

[^app-how-to-write-1]: Die beide zusammen die erste Version von diesem Text mal 2019 geschrieben haben. Tja, wie so die Zeit vergeht.

::: callout-note
## Erfahrungsbericht von ehemaligen Bachelorstudierenden

-   keine neuen (wichtigen) Begriffe verwenden, wenn sie nicht vorher eingeführt wurden
-   wenn man einen Begriff nicht richtig versteht oder nicht richtig erklären kann, sollte man ihn nicht verwenden. Daher ist es sehr hilfreich sich gründlich in den Hintergrund des Themas einzulesen.
-   man sollte mehr wissen über das Thema, als man eigentlich im Text erklärt (um auf Fragen vorbereitet zu sein)
-   Achtgeben auf die Zeitformen
-   "it", "they" und weitere Pronomen vermeiden, d.h. immer klar machen worauf man sich bezieht
-   wenn etwas komplizierter scheint, sollte man Beispiele benutzen oder es eventuell graphisch darstellen. **Aber:** ein Bild nicht verwenden, wenn es keinen inhaltlichen Wert hat! Bringt dieses Bild etwas zum Verständnis des Lesers bei?
-   in der Diskussion kein neues "Fass aufmachen"
-   die Limitationen in der Diskussion im Fließtext "verstecken"
-   die eigene Arbeit nicht schlecht reden; "schlechte" Resultate sind auch Resultate
-   keine zu langen Sätze
-   es sollte ein roter Faden in jedem Kapitel zu erkennen sein: Was ist das Ziel? Wie erreiche ich das? Was bringt mir diese Methode? Was sagen mir die Resultate (in Bezug auf mein Ziel)?
-   und für die eigene Motivation: Es werden oft Schreibblockaden kommen, es wird oft frustrierend sein, weil vielleicht etwas umgeschmissen wird und man von vorne anfangen muss, etc., aber davon soll man sich nicht entmutigen lassen
-   Der Text muss nicht gleich beim ersten Hinschreiben perfekt sein, sondern es hilft erstmal etwas drauflos zu schreiben um die Gedanken besser ordnen zu können
-   ähnlich beim Programmieren: hier hat es mir auch geholfen einfach erstmal anzufangen und Ideen aufzuschreiben, aus welchen sich kann das Programm aufbauen kann
-   Man sollte nicht zögern so etwas wie deepl ([deepl.com](www.deepl.com)) zu benutzen, wenn man mal mit einer englischen Formulierung nicht weiterkommt
-   Man kann vor Beginn eines Tages ein realistisches Tagesziel (oder alternativ ein Wochenziel) festlegen, dann hat man ein Zwischenziel vor Augen und ist zufrieden mit sich, wenn dieses erreicht ist
:::
