```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra)
```

# Bewertungsbogen {#sec-bewertung}

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

## Allgemeine Anmerkungen

Die Arbeit wird im Bereich (Bio) Data Science geschrieben. Im Zentrum steht die *Methodik und die Auseinandersetzung der Methoden* mit einem potenziellen biologischen Datensatz oder Fragestellung. Der biologischen Kontext ist kurz aber prägnant. Der methodische Teil dagegen ist ausführlich. Hier kann es natürlich je nach Thema noch Anpassungen geben.

## Formalia (10 Punkte)

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
|                                                                                                                                                                                                                        | Maximale Punkte | Erhaltene Punkte |
+========================================================================================================================================================================================================================+:===============:+:================:+
| **IMRAD eingehalten**                                                                                                                                                                                                  | 1               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Kohärenz** (0 - unzusammenhängend, 1 - Mängel, mehrere Brüche, aber nicht völlig daneben, 2 - weitgehend klarer Zusammenhang, kleinere Brüche, 3 - guter Bezug der Teile aufeinander; 0 - k.o. Kriterium: Rückgabe)  | 3               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Rechtschreibung & Grammatik** (0 - nicht vorhanden oder schwere Mängel, 1 - teilweise schwerwiegende Mängel, aber nicht durchgehend, 2 - leichte Mängel, 3 - weitgehend korrekt; 0 - k.o. Kriterium: Rückgabe)       | 3               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Programmcode & Literaturdatenbank** (0 - nicht vorhanden oder schwere Mängel, 1 - teilweise schwerwiegende Mängel, aber nicht durchgehend, 2 - leichte Mängel, 3 - weitgehend korrekt; 0 - k.o. Kriterium: Rückgabe) | 3               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Erreichte Punkte**                                                                                                                                                                                                   | **10**          |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+

## Einleitung (10 Punkte)

Die Einleitung ist im Bezug zur Biologie kurz und prägnant geschrieben. Es ist ein klarer Fokus gesetzt. Allgemeinheiten, wie die Struktur der DNA sind bekannt. Wert wird auf die Methodik und deren Referenzen gelegt.

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
|                                                                                                                                                                                    | Maximale Punkte | Erhaltene Punkte |
+====================================================================================================================================================================================+:===============:+:================:+
| **Vorstellung des Themas und der Fragestellung.** Der Problemhintergrund wird aufgezeigt                                                                                           | 2               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Bedeutung und Relevanz** Die methodische Relevanz wird betont, die biologische Relevanz erwähnt.                                                                                 | 2               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Bezugnahme auf Praxis und Theorie** Der Fokus liegt auf den Methoden und deren Limitierungen sowie die Auseinandersetzung mit der Anwendung auf das aktuelle, praktische Problem | 5               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Ausblick auf Gliederung des Berichts.** *Sehr kurzer* Überblick über die weitere Arbeit.                                                                                         | 1               |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Erreichte Punkte**                                                                                                                                                               | **10**          |                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+

## Material & Methoden (14 Punkte)

Das Zentrum der Arbeit. Die Methodiken werden vorgestellt und der Bezug zur Fragestellung aufgezeigt. Die Beschreibung der Methoden ist nachvollziehbar und im Zweifel auch ein wenig zu detailliert.

+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
|                                                                                                                                           | Maximale Punkte | Erhaltene Punkte |
+===========================================================================================================================================+:===============:+:================:+
| **Design und Datenerhebung** nachvollziehbare und vollständige Beschreibung der Daten zusammen mit Unsicherheiten der Fremderhebung.      | 4               |                  |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Geeignet und begründete Literatur. Warum wenden wir die Methoden an? Was sind die Unterschiede zwischen den Methoden?                     | 2               |                  |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Auswertungsmethoden nachvollziehbar, korrekt, mit aktueller Literatur. Detaillierte Beschreibung der Methodik im Bezug zur Fragestellung. | 6               |                  |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Literatur enthält aktuelle wissenschaftliche Veröffentlichungen                                                                           | 2               |                  |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Erreichte Punkte**                                                                                                                      | **14**          |                  |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+

## Ergebnisse (10 Punkte)

Welche Ergebnisse liefern die Methoden? Wird ein Fokus gesetzt, wenn viele Ergebnisse produziert wurden? Sind die Abbildungen in einer hohen Qualität, sodass Dritte die Abbildungen verstehen? Sind die Abbildungen angemessen und ausführlich beschriftet?

+---------------------------------------------------------------------------------------------------------------+-----------------+------------------+
|                                                                                                               | Maximale Punkte | Erhaltene Punkte |
+===============================================================================================================+:===============:+:================:+
| **Klare und vollständige Darstellung der Ergebnisse** Es ist ein Fokus auf bedeutende Ergebnisse zu erkennen. | 4               |                  |
+---------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Qualität der Abbildungen und Tabellen** Abbildungen sind, wenn möglich und sinnvoll mit ggplot2 erstellt.   | 3               |                  |
+---------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Abbildungen und Tabellen sind klar beschriftet und formatiert.                                                | 2               |                  |
+---------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Die Auswahl der Ergebnisse ist sinnvoll und ausgewählt passend zur Fragestellung.                             | 1               |                  |
+---------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Erreichte Punkte**                                                                                          | **10**          |                  |
+---------------------------------------------------------------------------------------------------------------+-----------------+------------------+

## Diskussion (16 Punkte)

Diskussion der Ergebnisse im Kontext der Methoden. Was hätte man anders machen können? Was wären die Effekte gewesen? Warum hat man sich für diese Methoden entschieden? Kritische Auseinandersetzung mit den getroffenen Entscheidungen.

+-----------------------------------------------------------------------------------------------------------------+-----------------+------------------+
|                                                                                                                 | Maximale Punkte | Erhaltene Punkte |
+=================================================================================================================+:===============:+:================:+
| Nachvollziehbare und angemessene Interpretation der Ergebnisse, Diskussion von alternativen Interpretationen    | 6               |                  |
+-----------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Bezug zur Fragestellung / Hypothese; Einordnung in theoretischen Hintergrund                                    | 4               |                  |
+-----------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Schlussfolgerungen; Implikationen für Praxis oder Forschung; Grenzen der Studie; Zielerreichung (ja/nein/warum) | 4               |                  |
+-----------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| Ausblick - Was habe ich gelernt und was kommt jetzt?                                                            | 2               |                  |
+-----------------------------------------------------------------------------------------------------------------+-----------------+------------------+
| **Erreichte Punkte**                                                                                            | **16**          |                  |
+-----------------------------------------------------------------------------------------------------------------+-----------------+------------------+

## Benotung

### Notenschlüssel

| Punkte | Note | Erreicht |
|:------:|:----:|:--------:|
|   30   | 4.0  |          |
|   31   | 4.0  |          |
|   32   | 3.7  |          |
|   33   | 3.7  |          |
|   34   | 3.7  |          |
|   35   | 3.7  |          |
|   36   | 3.7  |          |
|   37   | 3.7  |          |
|   38   | 3.7  |          |
|   39   | 3.0  |          |
|   40   | 3.0  |          |
|   41   | 3.0  |          |
|   42   | 2.7  |          |
|   43   | 2.7  |          |
|   44   | 2.7  |          |
|   45   | 2.3  |          |
|   46   | 2.3  |          |
|   47   | 2.3  |          |
|   48   | 2.3  |          |
|   49   | 2.0  |          |
|   50   | 2.0  |          |
|   51   | 2.0  |          |
|   52   | 1.7  |          |
|   53   | 1.7  |          |
|   54   | 1.7  |          |
|   55   | 1.3  |          |
|   56   | 1.3  |          |
|   57   | 1.3  |          |
|   58   | 1.3  |          |
|   59   | 1.0  |          |
|   60   | 1.0  |          |

### Endnote

|      Zahl       | In Worten |
|:---------------:|:---------:|
| $\phantom{1.7}$ |           |

*Stempel / Datum / Unterschrift*
