```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, openxlsx)
```

# Tutorium in R

## Genutzte R Pakete für das Kapitel

Wir wollen folgende R Pakete in diesem Kapitel nutzen.

```{r echo = TRUE}
pacman::p_load(tidyverse, magrittr, readxl, broom, multcomp, emmeans)
```

Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.

## Keimung

```{r}
germ_tbl <- read_excel("data/germination_data.xlsx")


```

## Schweine

```{r}
pig_tbl <- read_excel("data/pig_feed_data.xlsx")


```

## Kohlenstoff/Nitrat

```{r}
carbon_tbl <- read_excel("data/carbon_data.xlsx") %>% 
  mutate(c2n = c_o/n,
         c_m2c_o = c_m/c_o)


```

## Lichtintensität

```{r}
intensity_tbl <- read_excel("data/light_intensity_data.xlsx") %>% 
  mutate(rack = as_factor(rack),
         layer = as_factor(layer),
         light_intensity = factor(light_intensity, 
                                  labels = c("low", "mid", "high")))
```

```{r}
#| echo: false

intensity_tbl %>% 
  kable(align = "c", "pipe")

```

```{r}

fit_1 <- lm(growth ~ light_intensity + rack + layer, data = intensity_tbl)

fit_1 %>% anova %>% tidy

```

```{r}

fit_1 %>% glht(linfct = mcp(light_intensity = "Tukey")) %>% tidy

```

```{r}

marginal <- emmeans(fit_1, "light_intensity")
tidy(marginal) %>% 
  mutate_if(is.numeric, round, 2)

```

```{r}
marginal %>% contrast(method = "pairwise") %>% tidy %>% 
  mutate_if(is.numeric, round, 2)
```

## Auswirkung von N/P/Fe auf Weizen

```{r}
#| message: false

plant_tbl <- read_csv2("data/corn_plant_height.csv") %>% 
  gather(key = "day", value = "height", "1...3":"9...47") %>% 
  mutate(day = str_replace(day, "...\\d+", ""),
         day = as_factor(day),
         treatment = as_factor(treatment),
         block = factor(block, labels = c("I", "II", "III", "IV")))

```

```{r}
#| column: screen

ggplot(plant_tbl, aes(x = treatment, y = height, fill = day)) +
  geom_boxplot() +
  facet_wrap(~ block) +
  labs(x = "Behandlung", y = "Weizenhöhe [cm]", fill = "Messtag") +
  theme_bw()
```

```{r}
#| message: false

chlorophyl_tbl <- read_csv2("data/corn_chlorophyl.csv") %>% 
  gather(key = "day", value = "chlorophyl", "1...3":"3...62") %>% 
  mutate(day = str_replace(day, "...\\d+", ""),
         day = as_factor(day),
         treatment = as_factor(treatment),
         block = factor(block, labels = c("I", "II", "III", "IV"))) %>% 
  filter(chlorophyl >= 20 & chlorophyl <= 100)

```

```{r}
#| column: screen

ggplot(chlorophyl_tbl, aes(x = treatment, y = chlorophyl, fill = day)) +
  geom_boxplot() +
  facet_wrap(~ block) +
  labs(x = "Behandlung", y = "Chlorophyllgehalt", fill = "Messtag") +
  theme_bw()
```

```{r}
#| message: false

burn_tbl <- read_csv2("data/corn_burning.csv") %>% 
  gather(key = "day_outcome", value = "drymatter", "1_FM":"3_TMperc") %>%
  separate(day_outcome, c("day", "outcome")) %>% 
  mutate(day = as_factor(day),
         treatment = as_factor(treatment),
         block = factor(block, labels = c("I", "II", "III", "IV")),
         outcome = as_factor(outcome)) 

```

```{r}
burn_tbl %>% 
  filter(outcome == "FM") %>% 
  ggplot(aes(x = treatment, y = drymatter, color = day)) +
  geom_point() +
  ##facet_wrap(~ block, scales = "free_y") +
  labs(x = "Behandlung", y = "Gewicht", fill = "Messtag") +
  theme_bw()
```
