```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Klassifikation oder maschinelles Lernen

*Letzte Änderung am `r format(fs::file_info("classification-preface.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

> *"Prognosen sind schwierig, vor allem, wenn sie die Zukunft betreffen" --- Mark Twain*

In diesem Abschnitt und den folgenden Kapiteln wollen wir uns mit der Klassifikation beschäftigen. Was heißt Klassifikation? Wir wollen eine Vorhersage rechnen. Wir haben eine Spalte $y$ vorliegen in der wir Klassen stehen haben. Mit Klassen meine ich gesunde oder kranke Patienten. Oder aber eben gesunde oder kranke Ferkel. Meistens wollen wir also einen $0/1$ Wert vorhersagen. Wir brauchen dafür keine $0/1$ Einträge in unserer $y$ Spalte, schon aber einen binären Eintrag. Also zum Beispiel nur Männer und Frauen. Oder aber der Befall mit Blattläusen oder kein Befall mit Blattläusen. Theoretisch gehen auch mehr als zwei Klassen (eng. *multiclass*) aber das ist eher die Ausnahme als die Regel.

## Ausgewählte Algorithmen

Nachdem wir also wissen, dass wir Werte in einer Spalte vorhersagen wollen, können wir uns verschiedene Algorithmen einmal anschauen. Ich kann @mueller2021machine als einen Einstieg ins maschinelle Lernen empfehlen.

-   In dem @sec-knn schauen wir uns den $k$-NN Algorithmus einmal an. In diesem Algorithmus werden neue Beoabchtungen anhand der nächstliegenden Nachbarn klassifiziert.
-   In dem @sec-class-tree betrachten wir Entscheidungsbäume. Wir lassen also immer einen Entscheidungsbaum mit zwei Zweigen wachsen und nutzen diese Entscheidungsbäume für die Vorhersage.
-   In dem @sec-svm werden wir uns mit der Support Vector Machine beschäftigen. Wir werden hier aber nur auf die Anwendung eingehen und ein sehr anschauliches Beispiel für die Funktionsweise nutzen.
-   In dem @sec-neural betrachten wir dann neuronale Netzwerke. Damit ist dann auch Deep learning gemeint und somit der letzte Stand des maschinellen Lernens.

Was fehlt noch? Sicherlich fehlen noch andere Algorithmen. Aber das ist auch nicht der Sinn dieses Abschnitts eine umfassende Übersicht über alle Algorithmen des maschinellen Lernens zu geben. Wir wollen uns aber hier auf die großen und meist angewandten Algorithmen beschränken. Vielleicht ergänze ich dann nochmal ein Kapitel, wenn ich einen spannenden Algorithmus entdecke.

## Referenzen {.unnumbered}
