# Die Poissonverteilung {#sec-poisson}

```{r}
#| warning: false
#| echo: false

pacman::p_load(tidyverse, readxl, knitr, kableExtra)

```

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-align: center
#| fig-height: 3
#| fig-width: 5
#| fig-cap: "An 39 Hunden wurde die Anzahl an Flöhen gezählt."

set.seed(20220789)
pois_tbl <- tibble(lambda1 = rpois(1000, 6),
              lambda2 = rpois(1000, 10),
              lambda3 = rpois(1000, 1)) %>% 
  gather()

ggplot(data = pois_tbl, aes(x = value, fill = key)) +
  theme_bw() +
  geom_histogram(binwidth = 1, position = position_dodge(0.95)) +
  labs(x = "", y = "Anzahl") +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = 0:25, limits = c(0,NA)) +
  annotate("text", 3, 250, label = expression(paste("Pois(", lambda, " = 1)")),
           color = "blue") +
  annotate("text", 6, 180, label = expression(paste("Pois(", lambda, " = 6)")),
           color = "red") +
  annotate("text", 10, 150, label = expression(paste("Pois(", lambda, " = 10)")),
           color = "darkgreen") 
```
