# Die Normalverteilung {#sec-normal}

```{r}
#| warning: false
#| echo: false

pacman::p_load(tidyverse, readxl, knitr, kableExtra)

```

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-align: center
#| fig-height: 3
#| fig-width: 5
#| label: fig-normal-same-sd
#| fig-cap: "An 39 Hunden wurde die Anzahl an Flöhen gezählt."

set.seed(20220789)
norm_tbl <- tibble(n1 = rnorm(10000, 10, 2),
                   n2 = rnorm(10000, 20, 2),
                   n3 = rnorm(10000, 0, 2)) %>% 
  gather()

ggplot(data = norm_tbl, aes(x = value, fill = key)) +
  theme_bw() +
  geom_histogram(position = position_identity(), alpha = 0.75) +
  labs(x = "", y = "Anzahl") +
  xlim(-15, 30) +
  theme(legend.position = "none") +
  annotate("text", 0, 3200, label = expression(paste("N(0,2)")),
           color = "blue") +
  annotate("text", 10, 3200, label = expression(paste("N(10,2)")),
           color = "red") +
  annotate("text", 20, 3200, label = expression(paste("N(20,2)")),
           color = "darkgreen") 
```

@fig-normal-same-sd

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-align: center
#| fig-height: 3
#| fig-width: 5
#| label: fig-normal-mu-sd-different
#| fig-cap: "An 39 Hunden wurde die Anzahl an Flöhen gezählt."

set.seed(20220789)
norm_tbl <- tibble(n1 = rnorm(10000, 10, 1),
                   n2 = rnorm(10000, 20, 3),
                   n3 = rnorm(10000, 0, 6)) %>% 
  gather()

ggplot(data = norm_tbl, aes(x = value, fill = key)) +
  theme_bw() +
  geom_histogram(binwidth = 1, position = position_identity(), alpha = 0.75) +
  labs(x = "", y = "Anzahl") +
  xlim(-15, 30) +
  theme(legend.position = "none") +
  annotate("text", 0, 900, label = expression(paste("N(0,6)")),
           color = "blue") +
  annotate("text", 10, 4100, label = expression(paste("N(10,1)")),
           color = "red") +
  annotate("text", 20, 1500, label = expression(paste("N(20,3)")),
           color = "darkgreen") 
```

@fig-normal-mu-sd-different
