```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Explorative Datenanalyse {#sec-eda-preface}

*Letzte Änderung am `r format(fs::file_info("eda-preface.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

> *"Richtiges Auffassen einer Sache und Missverstehen der gleichen Sache schließen einander nicht vollständig aus." --- Franz Kafka, Vor dem Gesetz*

In dem vorherigen Kapiteln haben wir uns mit dem Programmieren in R beschäftigt. Wir haben gelernt mit einem Computer durch eine Programmiersprache zu kommunizieren. Jetzt haben wir die Daten in R Eingelesen und im Zweifel noch angepasst. Nun wollen wir uns die Daten einmal angucken. Nicht in dem Sinne, dass wir nur auf die Daten*tabelle* schauen. Sondern wir wollen die Daten visualisieren und damit Zusammenhänge aufdecken. Wir erstellen Abbildungen von den Daten und versuchen so mehr über die Daten zu erfahren. In dem Zusammenhang können wir auch Tabellen erstellen, die uns die Daten zusammenfassen. Das führt uns dann schon näher an die eigentlichen Forschungsfragen, als es die puren Daten tun. Sehen wir Zusammenhänge zwischen verschiedenen Variablen bzw. Spalten? Dazu führen wir eine explorative Datenanalyse durch (abk. *EDA*). Über die explorative Datenanalyse wollen wir uns nun in den folgenden Kapitel einmal Gedanken machen.
