```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, openxlsx)
```

# Von Flöhen auf Tieren in Habitaten {#sec-example-4}

```{r }
#| message: false
#| echo: false
#| fig-align: center
#| fig-height: 4
#| fig-width: 6
#| fig-cap: Boxplot der Sprungweiten [cm] von Hunden und Katzen.
#| label: fig-example-4

set.seed(20220812)
data_tbl <- expand_grid(animal = 1:3, site = 1:4, rep = 1:10) %>% 
  mutate(jump_length = round(8 + 5 * animal + 2.5 * site - 1.5 * animal * site + rnorm(n(), 0, 2), 2),
         animal = factor(animal, labels = c("cat", "dog", "fox")),
         site = factor(site, labels = c("city", "smalltown", "village", "field")))

ggplot(data_tbl, aes(animal, jump_length, fill = site)) + 
  geom_boxplot() +
  labs(x = "Tierart", y = "Sprungweite [cm]") +
  theme_bw() 

write.csv2(data_tbl, "data/flea_dog_cat_foxes_site.csv", row.names = FALSE)
write.xlsx(data_tbl, "data/flea_dog_cat_foxes_site.xlsx", rowNames = FALSE)


```

Wir schauen uns Flöhe auf drei Tierarten an sowie in verschiedenen Habitaten. Dabei messen wir als Endpunkt die Sprungweite in cm.

::: callout-tip
## Datei für von Flöhen auf Tieren in Habitaten

Du findest die Datei `flea_dog_cat_foxes_site.xlsx` auf GitHub [jkruppa.github.io/data/](https://github.com/jkruppa/jkruppa.github.io/tree/master/data) als Excel oder auch als CSV.
:::
