```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, openxlsx)
```

# Von Flöhen auf Tieren {#sec-example-3}

```{r }
#| echo: false
#| message: false

data_tbl <- read_csv2("data/flea_dog_cat.csv")
```

Wir wollen jetzt das Beispiel von den Hunde- und Katzenflöhen um eine *weitere* Spezies erweitern. Wir nehmen noch die Füchse mit dazu und fragen uns, wie sieht es mit der Sprungfähigkeit von Hunde-, Katzen- und Fuchsflöhen aus?

```{r echo = FALSE}
#| label: tbl-dog-cat-fox
#| tbl-cap: Sprunglängen [cm] für Hunde-, Katzen- und Fuchsflöhe. 

y_jump_fox <- c(12.1, 13.2, 14.1, 9.7, 10.6, 11.5, 10.8)
y_grade_fox <- c(5, 4, 7, 5, 4, 4, 1)
y_count_fox <- c(21, 25, 31, 12, 28, 18, 19)
y_infected_fox <- c(1, 1, 1, 1, 0, 1, 0)

data_tbl <- rbind(data_tbl,  
                  tibble(fox = y_jump_fox) %>%
                    gather(animal, jump_length) %>%
                    mutate(flea_count = c(y_count_fox),
                           grade = c(y_count_fox),
                           infected = c(y_count_fox)))

write.csv2(data_tbl, "data/flea_dog_cat_foxes.csv", row.names = FALSE)
write.xlsx(data_tbl, "data/flea_dog_cat_foxes.xlsx", rowNames = FALSE)


data_tbl %>%
  kable(align = "c", "pipe")


```
