```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, openxlsx)
```

# Datenbeispiele

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

> *"It is possible to commit no mistakes and still lose. That is not a weakness. That is life." --- Jean-Luc Picard, Star Trek: The Next Generation, Peak Performance*

Wir brauchen am Anfang erstmal ein simples Beispiel. Konkrete Zahlen mit denen wir arbeiten können und Grundlagen aufbauen können. Was liegt da näher als sich einmal am Kopf zu kratzen und zu fragen, was juckt den da? Genau! Flöhe. Wir schauen uns einmal Flöhe auf Hunden und Katzen an. Daran können wir viel über Zahlen und Buchstaben in der Statistik und dann im Programmieren lernen.

::: callout-note
## Zahlen, Buchstaben und Wörter

Mir ist bewusst, dass du die Unterschiede kennst. Nur leider ist eine Zahl nicht nur eine Zahl und ein Wort nicht immer ein Wort. Das hat mit der eingeschränkten Kommunikationsfähigkeit von Computerprogrammen zu tun. R braucht da deine Mithilfe und dein *neues* Verständnis von Buchstaben und Zahlen. Eben wie ein Computer denkt.
:::

## Von Flöhen und Hunden

In unserem ersten Beispiel in @sec-example-1 geht es darum einmal ein Gefühl für Daten zu kriegen. Also was sind diese Zahlen und Buchstaben eigentlich? Wie sind Daten aufgebaut und wie musst du Daten bauen, so dass wir auch mit den Daten arbeiten können? Wir schauen uns dafür einmal Flöhe auf Hunden an und fragen uns welche Typen von Zahlen können wir erheben?

## Von Flöhen, Hunden und Katzen

In unserem zweiten Beispiel in @sec-example-2 erweitern wir unserer erstes Beispiel um die Katzen. Das heist, dass eigentlich alles gleich bleibt. Wir schauen usn *zusätlich* noch als zweite Gruppe die Katzen an. Nun können wir die Frage stellen, unterscheiden sich Flöhe auf Hunden und Katzen gegeben von gemessenen Eigenschaften?

## Von Flöhen auf Tieren

In unserem dritten Beispiel in @sec-example-3 erweitern wir das Beispiel um den Fuchs mit einem weiteren Tier. Dadurch haben wir nicht mehr einen Faktor mit zwei Leveln vorliegen sondern einen mit drei Leveln. Die Fragestrellung erweitert sich jetzt auf einen *multiplen* Gruppenvergleich. Wir vergleichen nicht mehr nur noch zwei Gruppen miteinander sondern drei.

## Von Flöhen auf Tieren in Habitaten

In unserem vierten Beispiel in @sec-example-4 schauen wir uns zusätzlich zu dem dritten Beispiel noch verschiedene Habitate (eng. *site*) an. Wir haben nämlich die Hunde-, Katzen-, und Fuchsflöhe nicht nur an einem Ort sondern an verschiedenen Orten gesammelt und gemessen. Wir haben einen zweiten Faktor vorliegen.

## Von vielen Flöhen auf Hunden und Katzen

Im fünften Beispiel in @sec-example-5 schauen wir uns wiederum nur noch zwei Tierarten an: Hunde und Katzen. Dafür aber eine große Anzahl an Tieren. Wir schauen uns hier die Daten von 400 Tiere an. Auf diesen Tierarten messen wir mehrere Variablen unn wollen uns diese Daten später in der Regression anschauen.

## Gummibärchen

Im Beispiel mit den Gummibärchen in @sec-example-gummibears geht es um die Darstellung verschiedener Verteilungen. Wir brauchen den Datensatz um zu verstehen, wie Daten verteilt sind. Sonst können wir den Datensatz auch gut nutzen um einmal in R zu filtern und zu selektieren. Auch für die Erstellung von Abbilungen eignet sich der Datensatz sehr gut.
