```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Experimentelle Designs

*Letzte Änderung am `r format(fs::file_info("experimental-design-preface.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

> *"Kein noch so bedeutsamer Einzelversuch kann für den experimentellen Nachweis eines Naturphänomens ausreichen; denn der"eine Zufall unter Millionen" wird zweifellos auftreten, und zwar nicht weniger und nicht mehr als mit der entsprechenden Häufigkeit, wie überrascht wir auch sein mögen, dass er uns auffällt." --- Roland Fisher*

Was ist ein experimentelles Design? Wir unterscheiden zuerst nach dem Organismus, den wir uns anschauen. Wenn wir über Tiere und Pflanzen sprechen, dann haben wir meist ein feststehendes experimentelles Design. Wir haben ein Feldexperiment vorliegen, dass natürlich mit Tieren auch in einem Stall stattfinden kann. Wenn wir uns Menschen betrachten, dann haben wir eine klinische Studie vorliegen. Wir werden uns in den folgenden Kapiteln erstmal nur mit dem experimentellen Design für Pflanzen und Tiere beschäftigen. Der große Unterschied ist zum einen ethischer Natur und rein praktisch, dass sich Menschen frei bewegen können und Pflanzen sowie Tiere in einem Experiment nicht. Ja, es gibt natürlich noch weitreichende moralische und ethische Unterschiede. Deshalb jetzt erstmal das klassische Feldexperiement in den Agrarwissenschaften. Was können wir hier an Literatur lesen? Dazu habe ich dann nochmal in den folgenden Kasten einige Literatur zusammengesucht.

::: callout-tip
## Weitere Literatur zum experimentellen Design

-   Es findet sich auch eine kurze Veröffentlichung über [Versuchsergebnisse interpretieren](https://www.dlg.org/de/landwirtschaft/themen/pflanzenbau/pflanzenernaehrung/dlg-kompakt-3-2021) der DLG e.V. - Deutsche Landwirtschafts-Gesellschaft.
-   @casler2015fundamentals zeigt in seiner wissenschaftlichen Veröffentlichung [Fundamentals of Experimental Design: Guidelines for Designing Successful Experiments](https://acsess.onlinelibrary.wiley.com/doi/10.2134/agronj2013.0114) nochmal auf, welche Ideen und Konzepte wichtig sind für ein erfolgreiches Experiment.
-   @piepho2022one gehen nochmal auf die Fallzahlplanung in ihrer wissenschaftlichen Veröffentlichung [One, two, three: portable sample size in agricultural research](https://www.cambridge.org/core/journals/journal-of-agricultural-science/article/one-two-three-portable-sample-size-in-agricultural-research/0CDCF73CA7B2AB585E00D460D482C2FD) ein.
-   Ein tolles Beispiel für die Fallzahlplanung liefert @benz2023einfluss in der wissenschaftlichen Veröffentlichung [Einfluss des Stichprobendesigns und der Messdauer von Liegezeiten bei Milchkühen auf den Stichprobenumfang](http://landtechnik-online.eu/landtechnik/article/view/3301).
-   Und natürlich darf @hurlbert1984pseudoreplication mit seiner grundlegenden wissenschaftlichen Veröffentlichung [Pseudoreplication and the Design of Ecological Field Experiments](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.2307/1942661) nicht fehlen.
:::

## Übersicht der experimentellen Designs

Zuerst empfehle ich dir das folgende Kapitel in dem ich nochmal auf die Erstellung von Versuchsplänen in R eingehe. Ich stelle dort R Pakete vor und zeige auch wie du dir selber dein Design erstellen kannst.

-   In dem ersten Kapitel zur [Versuchsplanung in R](#sec-experimental-design-r) zeige ich einmal auf, wie du Experimente in R planen kannst.

Wir schauen uns in den folgenden Kapiteln einmal eine Auswahl an experimentellen Designs an. Im Laufe der Zeit werden sicherlich noch andere Designs ergänzt werden. Soweit erstmal diese Auswahl hier.

-   [Complete randomized design (CRD)](#sec-crd). Das *complete randomized design* ist der Klassiker unter den experimentellen Designs und wird häufig verwendet.
-   [Randomized complete block design (RCBD)](#sec-rcbd). Das *randomized vomplete block design* ist entweder eine Erweiterung des *romplete randomized design* und bringt noch eine neuen Faktor für die Wiederholung mit in das Experiment mit ein.
-   [Latin square design (LSD)](#sec-lsd) Das *latin square design* liefert eine gleichmäßige Aufteilung der experimentellen Einheiten über ein Feld oder ein Stall.

Als Spezialfälle dann noch folgende Designs, die ich selten in der Beratung habe, aber dennoch nochmal vorstellen möchte.

-   [Alpha design](#sec-alpha). Hier handelt es sich um ein *incomplete block design*. Das heißt wir haben nicht jede Behandlung in jedem Block vorliegen. Da wir hier dann natürlich Fläche einsparen können wir dann mehr Behandlungen oder Sorten testen. Dafür bezahlen wir auch einen preis, das Alpha design hat eine nicht so hohe Aussagekraft.
-   [Augmented design](#sec-augment). Wir nutzen dieses Design, wenn wir in unserem *incomplete block design* noch Behandlungen haben, die nicht unvollständig sein sollen. Das heißt, wir haben hier den Hybriden aus dem RCBD und eben dem Alpha design. Wir nehmen also immer in jeden unvollständigen Block noch Behandlungen mit auf, die dann eben vollständig randomisiert sind.

In dem weiteren Kapitel wollen wir uns mit der Erstellung von komplexeren experimentellen Designs beschäftigen.

-   [Randomized complete block design (RCBD, 3-faktoriell)](#sec-rcbd-3fac)
-   [Split plot design (3-faktoriell) oder Spaltanlage](#sec-split)
-   [Subsampling](#sec-subsampling)
-   [Incomplete block design (3-faktoriell und 2-faktoriell)](#sec-incomplete)
-   [Strip plot design (3-faktoriell) oder Streifenanlage](#sec-strip-plot)

Die Liste ist nicht vollständig und kann von mir auch je nach Bedarf erweitert werden. Wir belassen es aber bis auf Weiteres bei diesen sehr häufig genutzten Varianten.

## Grundlagen eines statistischen Versuchs

Wie funktioniert ein *statistischer* Versuch? Ich könnte auch wissenschaftliches Experiment schreiben, aber ein wissenschaftliches Experiment ist sehr abstrakt. Wir wollen ja einen Versuch durchführen und danach - ja was eigentlich? Was wollen wir nach dem Versuch haben? Meistens eine neue Erkenntnis. Um diese Erkenntnis zu validieren oder aber abzusichern nutzen wir Statistik. Dazu musst du noch wissen, dass wir eine spezielle Form der Statistik nutzen: die *frequentistische Statistik*.

Die *frequentistische Statistik* basiert - wie der Name andeutet - auf Wiederholungen in einem Versuch. Daher der Name frequentistisch. Also eine Frequenz von Beobachtungen. Ist ein wenig gewollt, aber daran gewöhnen wir uns schon mal. Konkret, ein Experiment welches wir frequentistisch Auswerten wollen besteht immer aus biologischen Wiederholungen. Wir müssen also ein Experiment planen in dem wir wiederholt ein Outcome an vielen Tieren, Pflanzen oder Menschen messen. Eine *biologische Wiederholung* beinhaltet ein neues Tier, Pflanze oder Mensch. Eine *technische* Wiederholung ist die gleiche Messung an dem gleichen Tier, Pflanze oder Mensch.

::: callout-note
## Wie gehen wir nun vor, wenn wir ein Experiment durchführen wollen?

1)  Wir müssen auf jeden Fall wiederholt ein Outcome an verschiedenen Tieren, Pflanzen oder Menschen messen.
2)  Wir überlegen uns aus welcher Verteilungsfamilie unser Outcome stammt, damit wir dann die entsprechende Verfahren zur Analyse nehmen können.
:::

## Tipps & Tricks

Hier einmal eine Sammlung an Tipps & Tricks für deinen versuch, der sich in der letzten Zeit so ansammelt. Ich ergänze hier immer fortlaufend, wenn ich was passenden finde oder höre.

-   Wir berechnen meist den Mittelwert von $n$ Pflanzen in einer Parzelle. Wenn wir das nicht tun, könnte es sein, dass du gerade ein [Subsampling](#sec-subsampling) Experiment durchführst.
-   Markiere dir die Pflanze, die du wiederholt messen willst, zu Beginn des Experiments mit einem farbigen Stock. Du kannst im Gewächshaus die Blumentöpfe mit Sprühfarben markieren.
-   Nehme dir einen Zollstock mit, wenn du photographierst, sonst hast du keinen passenden Maßstab.
-   Nehme dir die Zeit für die Fotos, später lassen sich viele Fotos nicht wiederholen. Lege dir einen einfarbigen Untergrund unter die Pflanze. Je nach Art der Pflanze oder des Organs, mag die Farbe der Unterlage entscheident sein.
-   Sind deine Zettel wasserfest und dein Stift auch? Wenn du im Freiland unterwegs bist, kann es regnen.

In @tbl-experimental-hurlbert sehen wir einmal mögliche Quellen für die Verwirrung und die Möglichkeiten des experimentellen Design etwas gegen diese Quellen der Verwirrung zu unternehmen. Wir können hier Quelle der Verwirrung auch als Quelle der Varianz deuten. Eine detaillierte Diskussion findet sich in @dormann2013parametrische und @hurlbert1984pseudoreplication. Wichtig ist hier mitzunehmen, dass wir häufig eine Kontrolle brauchen um überhaupt die Stärke des Effektes messen zu können. Sonst können wir die Frage, ob die Behandlung besser ist nicht quantifizieren.

|     | Quelle der Verwirrung                                                     | Merkmal des experimentellen Designs um die Verwirrung zu reduziert oder aufzulösen                                                                |
|-----|---------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| 1\. | Zeitliche Veränderung                                                     | Kontrollgruppe                                                                                                                                    |
| 2\. | Artefakte in der Behandlung                                               | Kontrollgruppe                                                                                                                                    |
| 3\. | Voreingenommenheit des Forschenden (Bias)                                 | Randomisierte Zuordnung der Versuchseinheiten zu den Behandlungen; generelle Randomisierung bei allen möglichen Prozessen; Verblindete Prozeduren |
| 4\. | Vom Forschenden induzierte Variabilität (zufälliger Fehler)               | Wiederholungen der Behandlungen (und Kontrolle)                                                                                                   |
| 5\. | Anfängliche oder beinhaltende Variabilität zwischen den Versuchseinheiten | Wiederholungen der Behandlungen (und Kontrolle); Durchmischen der Behandlungen; Begleitbeobachtungen (Positive Kontrolle)                         |
| 6\. | Nicht-dämonische Einflüsse                                                | Wiederholung und Durchmischung der Behandlungen (und Kontrolle)                                                                                   |
| 7\. | Dämonische Eingriffe                                                      | Ewige Wachsamkeit - siehe dazu auch @feynman1998cargo; Geisteraustreibung; Menschenopfer                                                          |

: In @dormann2013parametrische und @hurlbert1984pseudoreplication finden wir eine Zusammenfassung von Quellen der Verwirrung also eigentlich der Varianz und deren mögliche Lösung um die Varianz zu beherrschen. {#tbl-experimental-hurlbert}

## Referenzen {.unnumbered}
