```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Bibliothek {#sec-literatur}

*Letzte Änderung am `r format(fs::file_info("literature.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

> *"Stealing from one author is plagiarism; from many authors, research." --- Walter Moers, The City of Dreaming Books*

Was ist gute Literatur? Ich würde sagen, gute Literatur ist Literatur, die einem hilft. Im Folgenden stelle ich einige etwas eskalierte Quellensammlung vor, die mittlerweile eher einer Bibliothek gleicht. Es ist (noch) nicht ganz so schlimm wie die Schwarze Bibliothek im Netz der Tausend Tore, aber mir kommt es fasst so vor. Du musst dann schauen, was passt und siehe es eher als ein Angebot. Deshalb hier eine Auswahl Literatur, die dir helfen mag und die ich sehr spannend finde. Zum einen ist jede Literatur anders geschrieben und zum anderen sind dort andere Inhalte enthalten, die ich hier einfach nicht in der Tiefe abdecken kann. Leider ist es etwas chaotisch in der Sortierung. Ich kann dir also nicht sagen, was du in welcher Reihenfolge lesen sollst. Das kommt ja wirklich auf dich und deine Fragen an. Aber manchmal finde ich in den Quellen Antworten bevor ich die Frage wusste. Beginnen wir jetzt aber einmal uns die verschiedenen Bücher & Blogs anzuschauen, die ich empfehlen kann, wenn du noch mehr zum Thema Bio Data Science lesen möchtest. Ich versuche also wie die Schwarze Bibliothek dann Struktur ins Chaos zu bringen.

::: {.callout-caution collapse="true"}
## Die Stadt der Träumenden Bücher

Oder Quellen, die ich noch lesen will... und dann nicht dazu komme, aber ich wichtig genug finde, dass ich diese Quellen nicht vergesse. Wenn dann die Quelle hier verschwindet, dann habe ich die Literatur dann sinnvoll im Buch ergänzt.

-   [What did Bateson mean when he wrote "information" is "a difference that makes a difference"?](https://www.cs.bham.ac.uk/research/projects/cogaff/misc/information-difference.html)
-   [How did we get back here, again?](https://metalogue.co.uk/2023/01/23/how-did-we-get-back-here-again/)
-   [Mathematical Tables Project](https://en.wikipedia.org/wiki/Mathematical_Tables_Project)
-   [10 Oldest Computers in The World](https://www.oldest.org/technology/computers/)
-   [The 2,500-Year-Old History of Adults Blaming the Younger Generation](https://historyhustle.com/2500-years-of-people-complaining-about-the-younger-generation/)
-   [Women And Children First: Technology And Moral Panic](https://www.wsj.com/articles/BL-TEB-2814)
-   [Biasarten](https://www.iqwig.de/sonstiges/glossar/biasarten.html)
-   [Analyzing reactor water level measurements in the Fukushima Daiichi 1 accident](https://www.sciencedirect.com/science/article/pii/S0149197023001427)
-   [Äther](https://de.wikipedia.org/wiki/%C3%84ther_(Physik))
-   [Women in Statistics through History](https://womeninstatshistory.blog/)
-   [Trailblazing women in statistics](https://news.uga.edu/groundbreaking-women-in-statistics/)
-   [Famous women statisticians](https://andifugard.info/famous-women-statisticians/)
-   [Nature Reviews Methods Primers](https://www.nature.com/nrmp/articles?type=primer)
-   [Current Biology Primers](https://www.cell.com/current-biology/libraries/primers)
:::

## Bloggern, denen ich folge... {.unnumbered}

Und was lese ich so? Ich folge einigen Bloggern in der unteren Liste. Da schaue ich immer mal was die so machen, damit meine Fähigkeiten nicht einrosten. Schöne Sachen machen die dort! Auch lerne ich dort immer mal wieder neue R Tricks, die dann hier im Buch erscheinen.

-   [Econometrics and Free Software by Bruno Rodrigues](https://www.brodrigues.co/)
-   [The 20% Statistician by Daniel Lakens](https://daniellakens.blogspot.com/)
-   [Blog by Andrew Heiss](https://www.andrewheiss.com/)
-   [Data Visualization & Information Design by Cédric Scherer](https://www.cedricscherer.com/)
-   [Statistics, Data, Science by Michael Clark](https://m-clark.github.io/index.html)
-   [Chris Brown’s blog on ocean science, quantitative ecology and R programming](https://www.seascapemodels.org/bluecology_blog.html)
-   [The broken bridge between biologists and statisticians](https://www.statforbiology.com/)
-   [Coding Club: a positive peer-learning community](https://ourcodingclub.github.io/tutorials.html)
-   [Dave Tang's Blog \| Computational Biology and Genomics](https://davetang.org/muse/)
-   [Nicola Rennie's Blog](https://nrennie.rbind.io/blog/)
-   [Layton R blog \| Data Stories](https://graphdr.github.io/data-stories/)

Das ist auch irgendwie so meine Linksammlung geworden. Im Weiteren dann vollständige Bücher, die du dir gerne anschauen kannst.

## Parametrische Statistik {.unnumbered}

Dormann [-@dormann2013parametrische] liefert ein tolles deutsches Buch für die Vertiefung in die Statistik. Insbesondere wenn du wissenschaftlich Arbeiten willst weit über die Bachelorarbeit hinaus. Dormann baut in seinem Buch eine hervorragende Grundlage auf. Das Buch ist an der Hochschule Osnabrück kostenlos [über den Link](https://link.springer.com/book/10.1007/978-3-662-54684-0) zu erhalten. Oder aber das Buch [Angewandte Statistik für die biologischen Wissenschaften](https://www.biometrie.uni-freiburg.de/mitarbeiter/dormann/deutschstatswork.pdf) was ebenfalls von @dormann2009angewandte geschrieben wurde. Beide Bücher überschneiden sich etwas, aber das ist eigentlich nicht so das Problem.

## Experimental methods in agriculture {.unnumbered}

Onofri und Sacco (2021) haben das Buch [Experimental methods in agriculture](https://www.statforbiology.com/_statbookeng/) geschrieben. Wir werden auf dieses englische Buch ab und zu mal verweisen. Insbesondere der Einleitungstext zur Wissenschaft und dem Design von Experiementen ist immer wieder lesenswert. Spätere Teile des Buches sind etwas mathematischer und nicht für den Einstieg unbedingt geeignet. Aber schaue es dir selber an.

## R for Data Science {.unnumbered}

Wickham [-@wickham2016r] ist die Grundlage für die R Programmierung. Das Material von Wickahm findet sich kostenlos online unter <https://r4ds.hadley.nz/> und <https://www.tidyverse.org/>. Wir werden uns hauptsächlich mit R wie es Wickham lehrt beschäftigen. Somit ist Wickham unsere Grundlage für R.

## Moderne Datenanalyse mit R {.unnumbered}

Mit dem Buch [Moderne Datenanalyse mit R -- Daten einlesen, aufbereiten, visualisieren, modellieren und kommunizieren](https://link.springer.com/book/10.1007/978-3-658-21587-3) von @sauer2019moderne steht noch eine freies, deutsches Buch zu Verfügung. Frei ist es dann über das Hochschulnetzwerk Osnabrück. Das Buch ist eine Alternative, wenn es eben dann noch Deutsch als Literatur sein soll.

## Data Science for Agriculture in R {.unnumbered}

Schmidt liefert auf der Webseite <https://schmidtpaul.github.io/DSFAIR/index.html> eine tolle Sammlung an experimentellen Designs bzw. Versuchsanlagen samt der Auswertung in R. Ohne Vorkenntnisse schwer zu verstehen. Sollte aber nach dem Besuch eines meiner Module dann möglich sein. Gerne hier auch mich fragen, dann können wir gemeinsam das passende Design raussuchen und besprechen.

## Big Book of R {.unnumbered}

Das [Big Book of R](https://www.bigbookofr.com/) beinhaltet über 300 (!) frei verfügbare Bücher, die sich mit R und entsprechenden Themen beschäftigen. Wie der Autor oder Sammler des Buches so schön schreibt, du brauchst nur noch diesen Link, du findest hier alles.

## Practical Statistics for Data Scientists {.unnumbered}

Bruce [-@bruce2020practical] schreibt ein Buch für den Anwender. Ohne Vorkenntnisse ist das Buch vermutlich etwas schwer zu lesen. Dafür bietet das Buch aber *nach* einem Statistikkurs sehr gute Anknüpfungspunkte Richtung maschinelles Lernen und somit der Klassifikation. Das Buch ist auch hier in der [englischen Version](https://ebookcentral.proquest.com/lib/hs-osnabrueck/detail.action?docID=6173908) und hier in der [deutschen Version](http://www.content-select.com/index.php?id=bib_view&ean=9783960104674) zu erhalten. *Beide Links benötigen den Zugang über die Hochschule Osnabrück*.

## Statistics for Terrified Biologists {.unnumbered}

Das Buch [Statistics for Terrified Biologists](https://s3-us-west-2.amazonaws.com/mtvernon.wsu.edu/uploads/2016/12/Statistics_for_Terrified_Biologists.pdf) von @van2019statistics liefert auch nochmal einen anderen Blick auf die Statistik. Auch hier bekommst du nochmal verschiedene Experimente und Versuche dargestellt. Ich mag das Buch, da es nochmal einen etwas anderen Blick auf die Statistik wirft. Hier schreibt ein sehr erfahrener Statistiker in einfacherer Sprache über sein Fachgebiet. Ich habe es gerne gelesen und schaue auch immer mal wieder rein.

## Educational papers from Nature Biotechnology and PLoS Computational Biology {.unnumbered}

Die Sammling [Educational papers from Nature Biotechnology and PLoS Computational Biology](https://liacs.leidenuniv.nl/~hoogeboomhj/mcb/nature_primer.html) liefert eine Übersicht an spannenden und gut zu lesenden wissenschaftlichen Veröffentlichungen, die komplexe Zusammenhänge einfach zu erklären versuchen. Auch kannst du hier schön Paper lesen üben. Schau einfach mal rein, ob da was passendes für dich dabei ist.

## Ten Simple Rules {.unnumbered}

Die Sammlung von [Ten Simple Rules](https://collections.plos.org/collection/ten-simple-rules/) bieten einen schnellen, konzentrierten Leitfaden für die Bewältigung einiger der beruflichen Herausforderungen, mit denen Forscher in ihrer Karriere konfrontiert sind. Ich fine die Sammlung fantastisch und finde immer wieder inspirierende Ideen. Nicht alles ist sinnvoll, aber vieles interessant und lohnt sich zum drüber nachdenken.

## A biologist's guide to statistical thinking and analysis {.unnumbered}

Das Buch [A biologist's guide to statistical thinking and analysis](http://www.wormbook.org/chapters/www_statisticalanalysis/statisticalanalysis.html) liefert eine wunderbare Übersicht von statistischen Ideen und Konzepten aus der Sicht von Biologen. Es dreht sich zar alles um Würmer, aber die Analysen und biologischen Schlussfolgerungen machen dennoch Sinn. Ich lese da immer mal wieder gerne quer. Besonders der Abschnitt [A quick guide to interpreting different indicators of variation](http://www.wormbook.org/chapters/www_statisticalanalysis/statisticalanalysis.html#sec1-6) und [Comparisons of more than two means](http://www.wormbook.org/chapters/www_statisticalanalysis/statisticalanalysis.html#sec3) zu multiplen Vergleichen fand ich sehr gut zu lesen.

## Advanced Data Analysis from an Elementary Point of View {.unnumbered}

Das sehr lange Skript [Advanced Data Analysis from an Elementary Point of View](https://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/) von Cosma Rohilla Shalizi gibt nochmal mehr Einblicke in die Welt der Statistik. Wie auch bei mir ist bei [Cosma Shalizi](https://www.stat.cmu.edu/~cshalizi/) alles immer größer geworden und mehr angewachsen. Wenn du mehr über Statistik lesen willst, ist es eine Goldgrube an Skripten und Ideen.

## Odds & Ends {.unnumbered}

Am Ende dann noch eine Mathebuch von Weisberg zu finden unter <https://jonathanweisberg.org/vip/>. Eigentlich eher ein Buch über Wahrscheinlichkeiten und wenn ein Buch am Ende stehen muss, dann ist es dieses Buch. Ich finde es sehr spannend zu lesen, aber das ist dann vermutlich *special intrest*.

## Referenzen {.unnumbered}
