```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Modulbeschreibung {#sec-module-entwurf}

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

> *"Wer etwas Großes will, der muß sich, wie Goethe sagt, zu beschränken wissen. Wer dagegen alles will, der will in der Tat nichts und bringt es zu nichts. Es gibt eine Menge interessante Dinge in der Welt; spanische Poesie, Chemie, Politik, Musik, d. ist alles sehr interessant, und man kann es keinem übel nehmen, der sich dafür interessiert; um aber als ein Individuum in einer bestimmten Lage etwas zustande zu bringen, muß man sich an etwas Bestimmtes halten und seine Kraft nicht nach vielen Seite hin zersplittern." --- Georg Wilhelm Friedrich Hegel, deutscher Philosoph*

Hier finden sich die *work in progress* Modulbeschreibungen. Diese werden teilweise von den offiziellen Modulbeschreibungen abweichen. Es handelt sich hierbei um Entwürfe von Modulbeschreibungen deren langfristiges Ziel es ist in den offiziellen Modulbeschreibungen aufzugehen. Dabei werden sicherlich nicht alle Inhalte hier übernommen. In der folgenden Tabelle findest du eine Übersicht der aktuell von mir angebotenen Module nach Lernstufe. Die ersten drei Lernstufen bilden hierbei den Bachelor ab. Die Lernstufe vier ist das Masterniveau mit anderen inhaltlichen Schwerpunkten neben der reinen Wissensvermittelung von statistischen Lerninhalten.

::: column-page
| Stufe | **Landwirtschaft; Angewandte Pflanzenbiologie -- Gartenbau, Pflanzentechnologie**      | **Wirtschafts- ingenieurwesen Agrar / Lebensmittel**      | **Bioverfahrenstechnik in Agrar- und Lebensmittelwirtschaft**                                 | **Angewandte Nutztier- und Pflanzenwissenschaften**          |
|:------|:---------------------------------------------------------------------------------------|:----------------------------------------------------------|:----------------------------------------------------------------------------------------------|--------------------------------------------------------------|
| **1** | [Mathematik und Statistik](https://www.hs-osnabrueck.de/module/44b0266/)               | [Statistik](https://www.hs-osnabrueck.de/module/44b0568/) | [Angewandte Statistik für Bioverfahrenstechnik](https://www.hs-osnabrueck.de/module/44b0567/) |                                                              |
| **2** | [Angewandte Statistik und Versuchswesen](https://www.hs-osnabrueck.de/module/44b0400/) |                                                           |                                                                                               |                                                              |
| **3** | [Spezielle Statistik und Versuchswesen](https://www.hs-osnabrueck.de/module/44b0390/)  |                                                           | [Statistische Bioinformatik -- *work in progess*](#sec-module-bioinformatik)                  |                                                              |
| **4** |                                                                                        |                                                           |                                                                                               | [Biostatistik](https://www.hs-osnabrueck.de/module/44m0161/) |

: Angebotene Statistik Module an der Fakultät Agrarwissenschaften und Landschaftsarchitektur (AuL). Die Stufe gibt das Lernniveau an. Dabei ist zu unterschieden, dass die ersten drei Lernstufen den Bachelor abbilden und die Lernstufe vier, das Masterniveau.
:::

{{< include module/module-bioinformatik.qmd >}}

{{< include module/module-mathematik-und-statistik.qmd >}}

{{< include module/module-angewandte-statistik-und-versuchswesen.qmd >}}

{{< include module/module-spezielle-statistik-und-versuchswesen.qmd >}}

{{< include module/module-statistik.qmd >}}

{{< include module/module-angewandte-statistik-bioverfahrenstechnik.qmd >}}

{{< include module/module-biostatistik.qmd >}}
