# Organisation

Den Teil kannst du hier überspringen, wenn es dich nicht so richtig interessiert, was ich alles an Vorlesungen anbiete. Wenn es dir um *statistische* Inhalte geht, dann gehe einfach weiter in das nächste Kapitel.

## Vorlesungen an der Hochschule Osnabrück {#sec-vorlesungen-hs}

Von mir angebotene Vorlesungen werden an der Hochschule Osnabrück an der Fakultät Agrarwissenschaften und Landschaftsarchitektur (AuL) in ILIAS verwaltet. Alle notwendigen Informationen und Materialien sind auf ILIAS unter <https://lms.hs-osnabrueck.de/> zu finden. Wenn du in dem Kurs nicht angemeldet bist, dann kontaktiere mich bitte [per Mail](#sec-contact-mail). Auch die Kommunikation erfolgt von meiner Seite aus über ILIAS.

[Auf ILIAS findest du alle aktuellen Kursinformationen und erhälst auch die Mails, wenn Änderungen im Kursablauf stattfinden.]{.aside}

Wenn du nicht in der Fakultät Agrarwissenschaften und Landschaftsarchitektur (AuL) studierst oder aber in einem Studiengang, der meine Module nicht anbietet, steht es dir natürlich frei, sich in meine Vorlesungen zu setzten. Du findest in @tbl-angebot eine Übersicht der angebotenen Module und auch die inhaltliche Ordnung nach Lernstufe. Bitte informiere dich in deinem Studierendensekretariat über die Modalitäten zur Prüfungsteilnahme.

| Stufe | **Landwirtschaft; Angewandte Pflanzenbiologie -- Gartenbau, Pflanzentechnologie**      | **Wirtschafts- ingenieurwesen Agrar / Lebensmittel**                                   | **Bioverfahrenstechnik in Agrar- und Lebensmittelwirtschaft**                                 |
|:------|:---------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------|
| **1** | [Mathematik und Statistik](https://www.hs-osnabrueck.de/module/44b0266/)               | [Statistik](https://www.hs-osnabrueck.de/module/44b0568/)                              | [Angewandte Statistik für Bioverfahrenstechnik](https://www.hs-osnabrueck.de/module/44b0567/) |
| **2** | [Angewandte Statistik und Versuchswesen](https://www.hs-osnabrueck.de/module/44b0400/) | [Angewandte Statistik und Versuchswesen](https://www.hs-osnabrueck.de/module/44b0400/) |                                                                                               |
| **3** | [Spezielle Statistik und Versuchswesen](https://www.hs-osnabrueck.de/module/44b0390/)  |                                                                                        |                                                                                               |

: Angebotene Statistik Module an der Fakultät Agrarwissenschaften und Landschaftsarchitektur (AuL). Die Stufe gibt das Lernniveau an. {#tbl-angebot}

Eine inhaltliche Übersicht findet sich auf dem [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1WCTnJnofz5OrGZth6LKyPGQvQUUw31t7OfnAE6yz-ww/edit?usp=sharing). Die Planung ist aktuell (Stand Sommer 2022) noch nicht abgeschlossen. Im Zweifel einfach bei mir einmal [per Mail](#sec-contact-mail) anfragen.

## R Tutorium {#sec-r-tutorium}

Im Rahmen der statistischen Beratung bieten wir auch ein R Tutorium für alle Mitglieder:innen der Fakultät Agrarwissenschaften und Landschaftsarchitektur (AuL) an. Die aktuellen Termine findest du in @tbl-r-tutorium.

Im R Tutorium besprechen wir aktuelle Themen der Teilnehmer:innen. Meist sind dies aktuelle Fragen zu den BAchelorarbeiten. Auch wenn du kein dringendes Problem hats, kannst du gerne kommen und dir die Fragestellungen anhören. Bitte beachte folgende Hinweise zu den Terminen.

::: callout-note
## Hinweise zu dem R Tutorium

Das R Tutorium findet **nicht** im Prüfungszeitraum der Fakultät Agrarwissenschaften und Landschaftsarchitektur (AuL) statt.

Das R Tutorium findet **nicht** im *Februar* und *März* statt.

Das R Tutorium findet **nicht** im *August* und *September* statt.
:::

| Termin    | Uhrzeit   | Raum | Anmerkung      |
|:----------|:----------|:-----|----------------|
| *nächste* | *Termine* | *ab* | *Oktober 2022* |

: Aktuelle Termine des R Tutoriums im Semester {#tbl-r-tutorium}

## Statistische Beratung

Ich biete auch Termine für die statistische Beratung von Abschlussarbeiten sowie Projekten an. Dafür musst du mir einfach nur eine [E-Mail schreiben](#sec-contact-mail) und dann erhälst du einen Termin innerhalb der nächsten zwei Wochen.

Die Beratung ist grundsätzlich anonym und vertraulich. Wenn du willst kannst du gerne noch dein:e Betreuer:in mitbringen. Das ist aber keine Voraussetzung oder Notwendigkeit.
