# Programmieren in R

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

::: callout-tip
## Einführung in R per Video

Du findest auf YouTube [Grundlagen in R](https://www.youtube.com/playlist?list=PLe51bCp9JvEFUnFqaJG5aRmON9i1ZbOYC) als Video Reihe. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.
:::

[Um eien Sprache zu lernen brauchst du Vokabeln und Grammatik. Beides lernt sich alleine immer recht sinnlos. Aber zusammen bringen kann man beides erst, wenn man beides gelernt hat.]{.aside}

Was solltest du nun zuerst Lesen um Programmieren in R zu verstehen und zu lernen? Es ist sehr schwierig die Programmierung exakt so zu schreiben, dass das Programmieren *linear* verständlich ist. Du brauchst im Prinzip das Wissen aus @sec-basics *Operatoren, Funktionen und Pakete* um die Grundlagen von Operatoren und Funktionen in R zu verstehen.

Auf der anderen Seite fehlt dir vielleicht noch das Verständnis von Buchstaben und Zahlen in R. Diesen Zusammenhang zwischen Buchstaben und Zahlen erkläre ich als erstes im folgenden @sec-letter-number *Von Buchstaben und Zahlen*. Vielleicht musst du beide Kapitel jeweils nochmal lesen. Oder aber in der Anwendung sehen. Stell dir vor es ist wie eine Sprache zu lernen. Ohne Vokabeln keine Sätze aber ohne Grammatik kein Sinn.

Bevor wir uns weiter mit statistischen Kennzahlen beschäftigen, wollen wir uns einmal die Realisierung einer Datentabelle mit den Hunde- und Katzenflöhen in R anschauen. Dabei wollen wir auch Eigenschaften von Zahlen und Buchstaben lernen, die notwendig sind um mit einem Programm wie R kommunizieren zu können. Wir wollen später R nutzen um die explorative Datenanalyse anzuwenden.

Fangen wir also an die Grammatik und die Vokabeln in R zu verstehen um dann mit dem Rechner kommunizieren zu können.
