```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Die ANOVA {#sec-anova}

## Einfaktorielle ANOVA

```{r}
#| echo: false
#| message: false
#| tbl-cap: test caption
#| label: tbl-data-anova-1

fac1_tbl <- read_csv2("data/flea_dog_cat_foxes.csv") 

fac1_tbl %>% kable(align = "c", "pipe")
```

Beispieldaten sind in @tbl-data-anova-1 abgebildet.

```{r}
#| message: false
#| echo: false
#| fig-align: center
#| fig-height: 4
#| fig-width: 4
#| fig-cap: Boxplot der Sprungweiten [cm] von Hunden und Katzen.
#| label: fig-boxplot-anova-1

ggplot(fac1_tbl, aes(x = animal, y = jump_length, 
                     fill = animal)) +
  geom_boxplot() +
  labs(x = "Tierart", y = "Sprungweite [cm]") +
  theme_bw() +
  theme(legend.position = "none") 

```

## Zweifaktorielle ANOVA

```{r}
#| echo: false
#| message: false
#| tbl-cap: test caption
#| label: tbl-data-anova-2

fac2_tbl <- read_csv2("data/flea_dog_cat_foxes_site.csv") %>% 
  mutate(animal = as_factor(animal),
         site = as_factor(site))

```

Beispieldaten sind in @fig-data-anova-2 abgebildet.

```{r}
#| message: false
#| echo: false
#| fig-align: center
#| fig-height: 4
#| fig-width: 6
#| fig-cap: Boxplot der Sprungweiten [cm] von Hunden und Katzen.
#| label: fig-boxplot-anova-2

ggplot(fac2_tbl, aes(x = animal, y = jump_length, 
                     fill = site)) +
  geom_boxplot() +
  labs(x = "Tierart", y = "Sprungweite [cm]") +
  theme_bw() 
```
