```{r echo = FALSE}
#| message: false
#| warning: false
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc, see, latex2exp,
               multcomp, emmeans, ggpubr, multcompView, nlme, quantreg, janitor,
               parameters, effectsize, patchwork, conflicted)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", 
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
## ggplot template
gg_template <- ggplot() +
  theme_minimal() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        # axis.text.y = element_text(color = "#CC79A7", face = "bold", size = 14),
        axis.text.y = element_text(),
        axis.ticks.y = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(size = 14, face = "bold"),
        plot.caption = element_text(face = "italic"),
        legend.position = "none") +
  scale_color_okabeito() +
  scale_fill_okabeito() 

```

# Der Post-hoc-Test {#sec-posthoc}

*Letzte Änderung am `r format(fs::file_info("stat-tests-posthoc.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

> *"Comparison is the thief of joy." --- Theodore Roosevelt*

```{r}
#| echo: false
#| eval: true
#| message: false
#| warning: false
#| label: fig-posthoc-temp
#| fig-align: center
#| fig-height: 5
#| fig-width: 5
#| fig-cap: "Visueller Zusammenhang eines gemittelten Outcomes ($y$) aus einer Normalverteilung im Verhältnis zu der Einflussvariable ($x$) mit zwei oder mehr Kategorien anhand von Barplots. Hauptsächlich unterscheiden sich die Barplots durch die unterschiedlichen Einheiten auf der $y$-Achse. Die Fehlerbalken stellen den Standardfehler (*SE*) dar. *[Zum Vergrößern anklicken]*"

gg_template %+%
  tibble(x_fct = c("A", "B", "C"),  
         mean_normal = c(1.5, 2.5, 5),
         sd_normal = c(0.5, 0.5, 0.5)) +
  aes(x_fct, mean_normal, fill = x_fct) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean_normal-(sd_normal), 
                    ymax = mean_normal+(sd_normal)),
                width = 0.2) +
  labs(x = "Kategoriell (>2 Level)", y = "Mittlerer Ertrag [t/ha]",
       title = "Gaussian",
       subtitle = "ANOVA, Paarweiser Vergleich und\ncompact letter display") +
  annotate("text", x = 1.5, y = 6, hjust = "right", color = "black", size = 4, 
           label = TeX(r"($ANOVA < 0.05$)")) +
  annotate("text", x = c(1, 2, 3), y = c(1.6, 3, 5.4),
           label = c("a", "ab", "b"), size = 5, fontface = 2) 
```

## Daten

## Modell

$$
y \sim f_1 + f_2
$$

### Varianzhomogenität & Varianzheterogenität

## ANOVA Pfad

Tukey HSD

## `{emmeans}`

## Weitere Methoden

### Paarweise Tests

### `{nparcomp}`

### `{multcomp}`

### Games Howell Test

### 

## Referenzen {.unnumbered}
