```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra)
```

# Grundlagen der linearen Regression {#sec-modeling-simple-stat}

*Letzte Änderung am `r format(fs::file_info("stat-linear-reg-preface.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

In diesem Kapitel wollen wir uns mit den Grundlagen der simplen linearen Regression beschäftigen. Das heißt, wir haben ein Outcome $y$, was normalverteilt ist, sowie eine Einflussvariable $x_1$, die eine kontinuierliche Variable ist. Wir wollen jetzt herausfinden, welchen Einfluss oder Effekt das $x_1$ auf das $y$ hat. Sehr simple Gesprochen legen wir eine Gerade durch eine Punktewolke.

::: column-margin
Ein simples lineares Modell hat ein $x$:

$$
y \sim x_1
$$

Ein multiples lineares Modell hat mehrere $x$:

$$
y \sim x_1 + x_2 + ... + x_p
$$
:::

Viele der Konzepte hier brauchen wir in dem Kapitel zum statistischen Modellieren. Wir lernen hier also eher die Aufwärmübungen und Konzepte um dann multiple lineare Regressionen rechnen zu können. In den seltensten Fällen reichen simple lineare Modell aus, um die Realität abzubilden.

Fangen wir also mit den Grundlagen an und bauen dann systematisch die Konzepte der simplen linearen Regression auf.

## Simple lineare Regression

Im @sec-modeling-simple-stat wollen wir einmal die Grundlagen der linearen Regression an der simplen linearen Regression erarbeiten. Wir benötigen die Formeln und die Worte für das weitere Modellieren multipler lineare Modelle.

### Kausales Modell

Schon gleich hier vorweg, es gibt einen Unterschied zwischen einem kausalen und einem prädiktiven Modell. In diesem kurzen @sec-simple-kausal schauen wir uns das kausale Modell einmal an. Wenn wir eine *klassische* Regression rechnen, rechnen wir meist ein kausales Modell.

### Prädiktives Modell

Die Vorhersage oder Prädiktion ist ein eigenes Kapitel wert. Im Bereich des maschinellen Lernens wird die Prädiktion auch Klassifikation genannt. Wir schauen uns in diesem @sec-simple-pred nur die Grundlage einmal an. Später nutzen wir auch maschinelle Lernverfahren für die Klassifikation.

## Maßzahlen der Modelgüte

Nachdem wir ein Modell mathematisch gerechnet haben, müssen wir herausfinden, ob das Modell auch gut funktioniert hat. In @sec-lin-reg-quality schauen wir uns verschiedene Maßzahlen an um zu sehen, ob die Wahl des mathematischen Algorithmus auch zu unseren Daten passt. Rechnen können wir alles, aber ob die Rechnung Sinn ergibt müssen wir erst herausfinden.

## Korrelation

Die simple lineare Regression und Korrelation sind eng miteinander verwandt. In @sec-lin-reg-corr schauen wir uns einmal die beiden Korrelationskoeffizienten nach Pearson und Spearman einmal an.
