## Mathematik und Statistik {#sec-module-mathematik}

### Inhalte und Qualifikationsziele des Moduls

#### Kurzbeschreibung

In den Pflanzenwissenschaften sowie in der Landwirtschaft werden vielen Prozesse und Phänomene durch mathematische und statistische Modelle beschrieben. In dem Modul "Mathematik und Statistik" lernen Studierende drei Schwerpunkte für das spätere wissenschaftliche und angewandte Arbeiten. Im ersten Teil des Moduls werden mathematische Grundkenntnisse wiederholt und im Verlauf des Moduls vertieft. Die mathematischen Formeln werden aus ihrer theoretischen, formalistischen Anwendung herausgelöst und in praktische Herausforderungen übertragen. Dabei werden Bereiche der Physik, Chemie sowie Biologie in den Kontext der Mathematik gesetzt. Im zweiten Teil des Moduls werden statistische Grundkenntnisse vermitteln. Der Fokus liegt hier auf der Darstellung, Erfahrung und ersten statistischen Auswertungen von Daten. Wissenschaftliche Forschung und Erkenntnisgewinn wird hierbei in den Kontext der Erhebung von Daten gesetzt. Die für Landwirtschaft und Gartenbau relevanten mathematischen und statistischen Verfahren werden dargestellt und diskutiert. Im dritten Teil des Moduls werden die erworbenen theoretischen, mathematischen und statistischen Kenntnisse durch die Einführung in die Programmierung in R für die Studierenden umsetzbar und erfahrbar gemacht. In dem Modul "Mathematik und Statistik" werden somit die ersten Grundkenntnisse für die praktische Anwendung der Bio Data Science erworben.

#### Lehr-Lerninhalte

Mathematischer Anteil

-   Maßzahlen, Flächen und Volumen beinhaltend Berechnungen mit Maßeinheiten von sehr kleinen sowie sehr großen Zahlen. Berechnungen mit Flächen- sowie Volumenmaßen einschließlich Winkel- und Streckenbestimmung.
-   Berechnungen mit Vektoren und Matrizen.
-   Mathematische Funktionen und Anwendung der Differential- und Integralrechnung einschließlich logarithmischer sowie exponentieller Funktionen. Lösung von quadratischer Gleichungen sowie Extremwertproblemen.
-   Wahrscheinlichkeiten mit Baumdiagramm und Pfadregeln sowie stochastische Prozesse. Wahrscheinlichkeitsverteilungen am Beispiel der Normalverteilung.
-   Logische Operatoren sowie Mengenlehre.

Statistischer Anteil

-   Einführung in die explorative Datenanalyse mit Fokus auf dem Boxplot und dem Barplot und deren statistischen Maßzahlen.
-   Einführung in das statistische Testen sowie der Testtheorie mit dem Prüfen von statistischen Hypothesen beinhaltend p-Wert und die 95% Konfidenzintervalle.
-   Berechnung des Student-, Welch- und gepaarten t-Test. Einführung in die Varianzanalyse.
-   Einführung in das multiple Testen von mehreren Mittelwerten und die Darstellung im compact letter display.

Informatorischer Anteil

-   Einführung in die Programmierung in R anhand von Skalenarten sowie der Darstellung von Daten in R.
-   Konzept von Objekten, Funktionen sowie Pipen und der Vorstellung des tidyverse in R.
-   Einlesen von Daten und deren Bearbeitung sowie Visualisierung in R

### Kompetenzorientierte Lernergebnisse

#### Wissen und Verstehen

##### Wissensverbreiterung

Mathematischer Anteil

-   Die Studierenden sind in der Lage mathematische Formeln in der Literatur zu finden.
-   Die Studierenden können ein Baumdiagramm für die Berechnung von Wahrscheinlichkeiten erstellen.

Statistischer Anteil

-   Die Studierenden sind in der Lage verschiedene Daten und Datenstrukturen zu erkennen.
-   Die Studierenden können einfache explorative Abbildungen erstellen und interpretieren.
-   Die Studierenden können verschiedene statistische Tests händisch durchführen.

Informatorischer Anteil

-   Die Studierenden können die Anforderungen an einen Datensatz zur Verwendung in R benennen.
-   Die Studierenden können in R Objekte, Funktionen und Zahlenvektoren unterscheiden und kennen die gängigen Operatoren in R.
-   Die Studierenden können den Ablauf für die Erstellung einer explorativen Datenanalyse in R beschreiben.

##### Wissensvertiefung

Mathematischer Anteil

-   Die Studierenden sind in der Lage mathematische Formeln in einem anwendungsorientierten Kontext anzuwenden.
-   Die Studierenden können sinnvolle Abschätzungen von linearen und exponentiellen Wachstum vornehmen.

Statistischer Anteil

-   Die Studierenden können das Ergebnis eines statistischen Test im Kontext der wissenschaftlichen Fragestellung interpretieren.
-   Die Studierenden sind in der Lage anhand eines statistisches Tests eine Entscheidung zu treffen.

Informatorischer Anteil

-   Die Studierenden sind in der Lage die Ausgabe eines statistischen Test in R zu interpretieren.

##### Wissensverständnis

Mathematischer Anteil

-   Die Studierenden können praktische Fragestellungen in einen formalisierten, mathematischen Kontext übersetzen.
-   Die Studierenden sind in der Lage die Wahrscheinlichkeit für das Eintreten eines Ereignisses abzuschätzen.

Statistischer Anteil

-   Die Studierenden können einen einfachen statistischen Test mit einer explorativen Datenanalyse in einen Kontext setzen.

#### Einsatz, Anwendung und Erzeugung von Wissen

##### Nutzung und Transfer

Die Studierenden sind in der Lage einfache lineare und exponentielle Kosten- und Nutzenabschätzungen anhand von mathematischen Modellen durchzuführen. Diese einfachen Abschätzungen umfassen die Planung von technischen und biologischen Prozesses in den Pflanzenwissenschaften sowie in der Landwirtschaft. Die Studierenden können dabei externe Literaturquellen und deren statistischen Maßzahlen in den Kontext des eigenen Berufsfeld setzen und aus verschiedenen, wissenschaftlichen Quellen erste informierte Vorentscheidungen treffen.

##### Wissenschaftliche Innovation

Die Studierende können statistische Maßzahlen aus wissenschaftlichen Publikationen in andere wissenschaftliche Kontexte einordnen. Die Studierenden kennen die Grundlagen des wissenschaftlichen Arbeitens anhand von Fallbeispielen. Die Studierenden können eine Reihe von explorativen Abbildungen aus Veröffentlichungen verstehen und erste informierte Forschungsideen entwickeln. Die Studierenden sind in der Lage bei der Erstellung von Daten aus Experimenten die Verwertbarkeit in R zu berücksichtigen.

#### Kommunikation und Kooperation

Die Studierenden sind in der Lage durch das Konzept von "tidy data" erhobene Daten mit anderen Forschenden zu teilen. Ebenfalls sind die Studierenden in der Lage gängige statistische Maßzahlen zu erkennen und zu berichten. Die Studierenden können einfachen R Code lesen und demonstrieren.

#### Wissenschaftliches Selbstverständnis / Professionalität

Keine. Es handelt sich um ein Grundlagenmodul.

### Literatur

-   Das Skript des Mathematikteils des Moduls unter https://jkruppa.github.io/math/
-   Das Skript des Statistik- und Programmierteil des Moduls unter https://jkruppa.github.io/
-   Teile des Skripts als Video unter https://www.youtube.com/c/JochenKruppa
-   Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013.
-   Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. \[https://r4ds.had.co.nz/\]

### Voraussetzungen für die Teilnahme

Keine. Es handelt sich um ein Grundlagenmodul.

### Empfohlene Vorkenntnisse

Keine. Es handelt sich um ein Grundlagenmodul.

### Zusammenhang mit anderen Modulen

Das Modul "Mathematik und Statistik" bereitet zudem auf weiterführende Module aus verschiedenen Themenbereichen vor. Zu diesen Themenbereichen gehören insbesondere

-   Angewandte Statistik und Versuchswesen (44B0400)
-   Chemie und Biochemie (44B0532)
-   Physikalische Grundlagen der Natur und Agrartechnik (44B0534)

Welche nachfolgenden Module konkret in Frage kommen, hängt von den einzelnen Studiengängen ab. Nähere Informationen hierzu bietet der Studienverlaufsplan in der jeweils gültigen Studienordnung.

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten

#### Benotete Prüfungsleistung

Klausur
