## Angewandte Mathematik und Statistik für Bioverfahrenstechnik {#sec-module-mathe-bioverfahren .unnumbered}

### Inhalte und Qualifikationsziele des Moduls {.unnumbered}

#### Kurzbeschreibung {.unnumbered}

In der Agrarwirtschaft und Ingenieurwissenschaften werden vielen Prozesse und Phänomene durch statistische Modelle beschrieben. Verfahrenstechnik, Qualitätssicherung und Marketing sind wesentlich getragen durch eine statistische Analyse von Daten. In dem Teil des Moduls “Angewandte Statistik für Bioverfahrenstechnik” lernen Studierende die Grundlagen für das spätere wissenschaftliche und angewandte Arbeiten. Das Modul vermittelt die dafür notwendigen statistischen Grundkenntnisse. Der Fokus liegt hier auf der Darstellung, Erfahrung und ersten statistischen Auswertungen von Daten. Wissenschaftliche Forschung und Erkenntnisgewinn wird hierbei in den Kontext der Erhebung von Daten gesetzt. Eine auf Daten gestützte Risikoabschätzung von Entscheidungen wird eingeübt. In dem Modul “Angewandte Statistik für Bioverfahrenstechnik” werden somit die ersten Grundkenntnisse für die praktische Anwendung der Bio Data Science erworben. Der Teil “Angewandte Mathematik für Bioverfahrenstechnik” des Moduls ist die Vertiefung und Erweiterung des Moduls “Mathematik für Bioverfahrenstechnik”. Schwerpunkt soll auf der Auswahl und Anwendung wichtiger mathematischer Werkzeuge liegen. Während im Modul “Mathematik für Bioverfahrenstechnik” Wert auf grundlegende Rechentechniken gelegt wird, ist in diesem Modul die Unterstützung durch die Software MATLAB zentrales Merkmal. Die grundlegende Funktionsweise der Software soll in diesem Rahmen vermittelt werden. Mittels der integrierten Funktionen der Software sollen die Studierenden lernen mathematische Berechnungen und numerische Analysen durchzuführen und zu visualisieren.

#### Lehr-Lerninhalte {.unnumbered}

Statistischer Anteil

-   Einführung in die explorative Datenanalyse und deren statistischen Maßzahlen.
-   Einführung in das statistische Testen sowie der Testtheorie mit dem Prüfen von statistischen Hypothesen beinhaltend p-Wert und die 95% Konfidenzintervalle.
-   Berechnung des Student-, Welch- und gepaarten t-Test.
-   Einführung in die Varianzanalyse beinhaltend die einfaktorielle ANOVA.
-   Grundlagen der simplen linearen Regression und deren statistischen Maßzahlen der Modellgüte am Beispiel eines normalverteilten Endpunkts.
-   Einführung in das multiple Testen von mehreren Mittelwerten und die Darstellung im compact letter display.

Mathematischer Anteil

-   Vertiefung der Anwendung mathematischer Lösungsansätze und Methoden
-   Grundlegende Einführung in die Software MATLAB
-   Anwendung der Software MATLAB
-   Näherungen und Näherungsmethoden
-   Systeme von Differentialgleichungen
-   Visualisierung von Daten

### Kompetenzorientierte Lernergebnisse {.unnumbered}

#### Wissen und Verstehen {.unnumbered}

##### Wissensverbreiterung {.unnumbered}

Statistischer Anteil

-   Die Studierenden sind in der Lage verschiedene Daten und Datenstrukturen zu erkennen und zu benennen.
-   Die Studierenden können explorative Abbildungen erkennen und benennen.
-   Die Studierenden können verschiedene statistische Tests händisch durchführen.

Mathematischer Anteil

-   Die Studierenden sind in der Lage Lösungsverfahren auszuwählen, anzuwenden um Problemlösungen korrekt zu erarbeiten.
-   Die Studierenden können Näherungsmethoden auswählen und anwenden.
-   Die Studierenden sind in der Lage Daten zu visualisieren.

##### Wissensvertiefung {.unnumbered}

Statistischer Anteil

-   Die Studierenden können explorative Abbildungen erstellen und interpretieren.
-   Die Studierenden können aus explorative Abbildungen die entsprechende Datenstruktur zur Erstellung der Abbildungen wiedergeben.
-   Die Studierenden sind in der Lage anhand eines statistisches Tests eine Entscheidung zu treffen.
-   Die Studierenden können das Ergebnis eines statistischen Test im Kontext der wissenschaftlichen Fragestellung interpretieren.

Mathematischer Anteil

-   Die Studierenden können mathematische Problemstellungen unter Zuhilfenahme der Software MATLAB lösen.
-   Die Studierenden sind in der Lage Näherungen mittels geeigneter Näherungsmethoden sinnvoll durchzuführen.
-   Die Studierenden können Systeme von linearen Differentialgleichungen lösen.
-   Die Studierenden können Ergebnisse zwei- und dreidimensional graphisch darstellen.

##### Wissensverständnis {.unnumbered}

Statistischer Anteil

-   Die Studierenden können einen statistischen Test mit einer explorativen Datenanalyse in einen Kontext bringen.

Mathematischer Anteil

-   Die Studierenden können Aufgabenstellungen interpretieren, Lösungsverfahren zuordnen und unter Zuhilfenahme von Software korrekt anwenden.

#### Einsatz, Anwendung und Erzeugung von Wissen {.unnumbered}

##### Nutzung und Transfer {.unnumbered}

Die Studierenden sind in der Lage einfache lineare Kosten- und Nutzenabschätzungen anhand von statistischen Modellen durchzuführen. Diese einfachen Abschätzungen umfassen die Planung von marktwirtschaftlichen, technischen und biologischen Prozesses in der Agrarwirtschaft und Ingenieurwissenschaften. Die Studierenden können dabei externe Literaturquellen und deren statistischen Maßzahlen in den Kontext des eigenen Berufsfeld setzen und aus verschiedenen, wissenschaftlichen Quellen erste informierte Vorentscheidungen treffen. Die Studierenden sind in der Lage die grundlegenden Konzepte der Programmierung in R in anderen Programmiersprachen zuerkennen.

##### Wissenschaftliche Innovation {.unnumbered}

Die Studierende können statistische Maßzahlen aus wissenschaftlichen Publikationen in andere wissenschaftliche Kontexte einordnen. Die Studierenden kennen die Grundlagen des wissenschaftlichen Arbeitens anhand von Fallbeispielen. Die Studierenden können explorative Abbildungen aus Veröffentlichungen verstehen und erste informierte Forschungsideen entwickeln. Die Studierenden sind in der Lage bei der Erstellung von Daten aus Experimenten die Verwertbarkeit in R zu berücksichtigen.

#### Kommunikation und Kooperation {.unnumbered}

Die Studierenden sind in der Lage durch das Konzept von "tidy data" erhobene Daten mit anderen Forschenden zu teilen. Ebenfalls sind die Studierenden in der Lage gängige statistische Maßzahlen zu erkennen und zu berichten.

#### Wissenschaftliches Selbstverständnis / Professionalität {.unnumbered}

Keine. Es handelt sich um ein Grundlagenmodul.

### Literatur {.unnumbered}

-   Das Skript des Statistik- und Programmierteil des Moduls unter https://jkruppa.github.io/
-   Teile des Skripts als Video unter https://www.youtube.com/c/JochenKruppa
-   Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013.
-   Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. https://r4ds.had.co.nz

### Voraussetzungen für die Teilnahme {.unnumbered}

Inhalte des Moduls Mathematik für Bioverfahrenstechnik (44B0609)

### Empfohlene Vorkenntnisse {.unnumbered}

Keine. Es handelt sich um ein Grundlagenmodul.

### Zusammenhang mit anderen Modulen {.unnumbered}

Das Modul "Angewandte Statistik für Bioverfahrenstechnik" bereitet zudem auf weiterführende Module aus verschiedenen Themenbereichen vor. Zu diesen Themenbereichen gehören insbesondere

-   [Produktionssystem Pflanze (44B0261)](https://www.hs-osnabrueck.de/module/44B0261/)
-   [Einführung in die Pflanzenzüchtung (44B0112)](https://www.hs-osnabrueck.de/module/44B0112/)
-   [Messen, Regeln und Auswerten in der Biosystemtechnik (44B0549)](https://www.hs-osnabrueck.de/module/44B0112/)

Welche nachfolgenden Module konkret in Frage kommen, hängt von den einzelnen Studiengängen ab. Nähere Informationen hierzu bietet der Studienverlaufsplan in der jeweils gültigen Studienordnung.

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten {.unnumbered}

#### Benotete Prüfungsleistung {.unnumbered}

Klausur
