## Biostatistik {#sec-module-biostatistik}

### Inhalte und Qualifikationsziele des Moduls

#### Kurzbeschreibung

Aus den Daten, die sich aus Prozessen und Experimenten ergeben, sollen zuverlässig und objektiv Entscheidungen herbeigeführt werden. Grundvoraussetzung hierzu sind aber vertiefte und umfangreiche Kenntnisse über angewandte statistische Methoden. Deshalb werden die notwendigen wissenschaftlichen und angewandten statistischen Methoden und ihre Prinzipien ausführlich dargestellt und diskutiert. An Fallbeispielen werden die Methoden eingeübt.

Wissenschaftliches Arbeiten, Strategien in der Forschung und ihre Beziehungen zu angewandten statistischen Methoden

Mit dem Fortschreiten der Digitalisierung können in den Pflanzenwissenschaften und der Landwirtschaft komplexere Experimente durchgeführt werden. Die Digitalisierung erlaubt die automatisierte Erfassung und Speicherung großer Datenmengen, die über entsprechende statistische Algorithmen aggregiert und ausgewertet werden müssen. Diese Daten können zur Steuerung der Produktion oder zur Erkennung von unerwünschten Ereignissen genutzt werden. Dadurch kann eine bessere Qualitätssicherung und Entwicklung gewährleistet werden. In dem Modul "Spezielle Statistik und Versuchswesen" lernen Studierende die fortgeschrittenen Algorithmen für das spätere wissenschaftliche und angewandte Arbeiten mit großen Datenmengen. Das Modul vermittelt die dafür notwendigen statistischen und algorithmischen praktischen Kenntnisse. Verschiedene statistische Verfahren werden vorgestellt und die statistischen Maßzahlen für die Modellselektion eingeübt. Im Weiteren werden maschinelle Lernverfahren präsentiert und auf Fallbeispiele angewendet. Der Fokus des Moduls liegt auf der praktischen Anwendung und Diskussion der Ergebnisse der statistischen Modellierungen. Die vorhandenen Programmierkenntnisse in R werden weiter vertieft und automatisierte Berichtserstellung mit Quarto und RMarkdown eingeübt. Das Arbeiten mit großen Datenmengen wird so für die Studierenden umsetzbar und erfahrbar gemacht. Das Modul "Spezielle Statistik und Versuchswesen" befähigt Studierende in dem Bereich der Bio Data Science in verschiedenen Anwendungsfeldern praktisch tätig zu sein.

#### Lehr-Lerninhalte

Allgemeine Statistik

-   Einführung in die gängigen multiplen linearen Regressionen und deren Verteilungsfamilien beinhaltend die Gaussian, Poisson, Multinominal/Ordinal und Binomial.
-   Grundlagen der statistischen Maßzahlen der Modellgüte einer multiplen linearen Regression sowie deren Effektschätzer.
-   Grundlagen der Variablenselektion und Imputation von fehlenden Werten sowie Ausreißerdetektion.
-   Einführung in die linearen gemischten Modelle und die Berücksichtigung von Messwiederholungen.
-   Vertiefte Auseinandersetzung mit multiplen Gruppenvergleichen und deren Möglichkeiten der Visualisierung von Gruppenunterschieden.
-   Einführung in die Äquivalenz oder Nichtunterlegenheit in der praktischen Anwendung.
-   Einführung in die klassischen experimentellen Designs in den Agrarwissenschaften und der Versuchsplanung.
-   Durchführung aller theoretisch erarbeiteten Inhalte in R.
-   Interpretation und Bewertung von statistischen Modellierungen in R.

Nutztierwissenschaften und Pflanzenwissenschaften

-   Spezifische Strategien und statistische Methoden in der Forschung und ihre Beziehungen zu angewandten statistischen Methoden in der jeweiligen Fachrichtung.

### Kompetenzorientierte Lernergebnisse

#### Wissen und Verstehen

##### Wissensverbreiterung

-   Die Studierenden kennen die gängigen experimentellen Designs in den Agrarwissenschaften.
-   Die Studierenden kennen die entsprechenden Repräsentationen der experimentellen Designs als Datensatz.
-   Die Studierenden können die gängigen statistischen Modellierungen benennen und unterscheiden.
-   Die Studierenden sind in der Lage zwischen einem kausalen und einem prädiktiven Modell zu unterscheiden.

##### Wissensvertiefung

Statistischer Anteil

-   Die Studierenden können explorative Abbildungen erstellen und interpretieren.

-   Die Studierenden können aus explorative Abbildungen die entsprechende Datenstruktur zur Erstellung der Abbildungen wiedergeben.

-   Die Studierenden sind in der Lage anhand eines statistisches Tests eine Entscheidung zu treffen.

-   Die Studierenden können das Ergebnis eines statistischen Test im Kontext der wissenschaftlichen Fragestellung interpretieren.

-   Die Studierenden sind in der Lage anhand einer wissenschaftlichen Fragestellung eine statistische Auswertung zu gliedern und zu planen.

-   Die Studierenden können wissenschaftliche Veröffentlichungen lesen und in den statistischen Kontext richtig einordnen.

-   Die Studierenden können eine multiple lineare Regression entsprechend des Endpunktes modellieren und interpretieren.

-   Die Studierenden können einen multiplen Gruppenvergleich für verschiedene Endpunkte rechnen und die p-Werte entsprechend adjustieren.

-   Die Studierenden können verschiedene technische Messparameter miteinander vergleichen und eine Aussage über die Nichtunterlegenheit treffen.

##### Wissensverständnis

-   Die Studierenden sind die der Lage eine wissenschaftliche Fragestellung mit einem experimentellen Design und einer statistischen Modellierung zu verbinden.
-   Die Studierenden können eine statistische Modellierung in einer Präsentation darstellen und vorstellen.
-   Die Studierenden können eine wissenschaftliche Veröffentlichung anhand der verwendeten Statistik bewerten.

#### Einsatz, Anwendung und Erzeugung von Wissen

##### Nutzung und Transfer

Die Studierenden sind in der Lage einfache lineare Kosten- und Nutzenabschätzungen anhand von statistischen Modellen durchzuführen. Diese einfachen Abschätzungen umfassen die Planung von marktwirtschaftlichen, technischen und biologischen Prozesses in den Agrarwirtschaften, Lebensmittelwissenschaften und Gartenbau. Die Studierenden können dabei externe Literaturquellen und deren statistischen Maßzahlen in den Kontext des eigenen Berufsfeld setzen und aus verschiedenen, wissenschaftlichen Quellen erste informierte Vorentscheidungen treffen. Die Studierenden sind in der Lage die grundlegenden Konzepte der Programmierung in R in anderen Programmiersprachen zuerkennen.

##### Wissenschaftliche Innovation

Die Studierende können statistische Maßzahlen aus wissenschaftlichen Publikationen in andere wissenschaftliche Kontexte einordnen. Die Studierenden kennen die Grundlagen des wissenschaftlichen Arbeitens anhand von Fallbeispielen. Die Studierenden können explorative Abbildungen aus Veröffentlichungen verstehen und erste informierte Forschungsideen entwickeln. Die Studierenden sind in der Lage bei der Erstellung von Daten aus Experimenten die Verwertbarkeit in R zu berücksichtigen.

#### Kommunikation und Kooperation

Die Studierenden sind dadurch in der Lage in multidiziplinären, wissenschaftlichen Teams mitzuwirken. Die Studierenden können eine gemeinsam geplante Forschungsskizze in R umsetzen. Die Studierenden sind in der Lage die Ergebnisse einer statistischen Analyse auch Fachfremden zu erläutern.

#### Wissenschaftliches Selbstverständnis / Professionalität

Die Studierenden können wissenschaftliche Publikationen und deren statistischen Maßzahlen in den Kontext des eigenen Berufsfeldes setzen und somit informierte Entscheidungen treffen. Die Studierende sind sich der inhärenten Unsicherheit der wissenschaftlichen Forschung bewusst und können die eigenen Forschungsergebnisse kritisch hinterfragen. Die Studierenden können die Ergebnisse der eigenen Forschung diskutieren und in den allgemeinen wissenschaftlichen Kontext ihres Forschungsfeldes einordnen.

### Literatur

-   Das Skript des Statistik- und Programmierteil des Moduls unter https://jkruppa.github.io/
-   Teile des Skripts als Video unter https://www.youtube.com/c/JochenKruppa
-   Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013.
-   Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. \[https://r4ds.had.co.nz/\]

### Voraussetzungen für die Teilnahme

Keine. Es handelt sich um ein Grundlagenmodul.

### Empfohlene Vorkenntnisse

In dem Modul werden vertiefte Kenntnisse der deskriptiven Statistik sowie Grundkenntnisse der Statistik vorausgesetzt, wie sie in Modulen "Mathematik und Statistik (44B0266)" und "Angewandte Statistik und Versuchswesen (44B0400)" erworben werden.

Studierenden, die ihre Kenntnisse und Fertigkeiten vor Beginn des Moduls auffrischen möchten, wird folgende Grundlagenliteratur mit dem "Skript Bio Data Science" unter https://jkruppa.github.io/ empfohlen.

In dem Modul wird mit der Software R gearbeitet. Um sich im Vorfeld mit den Basisfunktionen vertraut zu machen, eignen sich beispielsweise die folgenden Video-Tutorials unter https://www.youtube.com/c/JochenKruppa.

### Zusammenhang mit anderen Modulen

Das Modul "Biostatistik" bereitet zudem auf weiterführende Module aus verschiedenen Themenbereichen vor. Zu diesen Themenbereichen gehören insbesondere

-   Wissenschaftliches Arbeiten (44M0159)
-   Wissenschaftliche Publikation und Fachtagungen (44M0125)
-   Forschungs- und Entwicklungsprojekt (44M0043)
-   Masterarbeit (44M0267)

Welche nachfolgenden Module konkret in Frage kommen, hängt von den einzelnen Studiengängen ab. Nähere Informationen hierzu bietet der Studienverlaufsplan in der jeweils gültigen Studienordnung.

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten

#### Benotete Prüfungsleistung

Klausur
