## Statistische Bioinformatik {#sec-module-bioinformatik .unnumbered}

### Inhalte und Qualifikationsziele des Moduls {.unnumbered}

#### Kurzbeschreibung {.unnumbered}

Die statistische Bioinformatik spielt eine bedeutende Rolle in verschiedenen wissenschaftlichen Bereichen der Omics-Forschung. Sie wird nicht nur klassisch genutzt, um genetische Marker für Krankheiten oder genetische Veranlagungen in der Humangenetik zu identifizieren, sondern auch zur Entschlüsselung der genetischen Vererbung bei der Züchtung von Tieren und Pflanzen. Die algorithmische Auswertung von genetischen Daten ist sowohl biologisch umfassend als auch methodisch anspruchsvoll. Das Modul "Statistische Bioinformatik" folgt dem zentralen Dogma der Molekularbiologie, das besagt, dass Informationen von Genen zu Proteinen übertragen werden. Es beinhaltet die statistische Analyse von genetischen Markern auf DNA-Ebene sowie die Untersuchung der Genexpression über mRNA und die daraus resultierende Proteinexpression bis hin zur Phänomik. Auch regulatorische Elemente der DNA-Expression, wie die Methylierung, werden im Modul berücksichtigt. Das Modul "Statistische Bioinformatik" bietet zuerst eine Einführung in die klassische mendelsche Genetik sowie Grundlagen in der quantitativen Genetik. Den Großteil den Inhalts machen aktuelle algorithmische Verfahren zu Assoziationsstudien und Sequenzanalysen aus. Studierende erlernen somit die grundlegenden Fähigkeiten für zukünftige wissenschaftliche und angewandte Arbeiten im Bereich der Omics-Forschung. Der Schwerpunkt des Moduls liegt auf der Darstellung, Verarbeitung und statistischen Auswertung von hochdimensionalen genetischen Daten. Fallstudien aus den Bereichen der Agrarwissenschaften und Humanbiologie dienen als praktische Anwendungen. Gleichzeitig werden die erworbenen theoretischen Kenntnisse durch die Auswertung von Daten in R/Bioconductor in die Praxis umgesetzt. Das Modul "Statistische Bioinformatik" legt somit den Grundstein für die methodische Auswertung von Omics-Daten.

#### Lehr-Lerninhalte {.unnumbered}

-   Grundlagen der klassischen, mendelschen Vererbung beinhaltend das Hardy-Weinberg-Gleichgewicht
-   Grundlagen der Quantitativen Genetik mit Kopplungskarten und Linkage disequilibrium
-   Genetische Distanz und polygenetische Bäume zur Darstellung evolutionärer Beziehungen
-   Markergestützte Selektion und indirekte Selektion
-   Statistische Herausforderungen von hochdimensionalen Daten
-   Data Preprocessing und Qualitätskontrolle auf der Ebene der Marker und Individuen
-   Gängige Assoziationstests unter anderem Chi-Quadrat-Test und logistische Regression
-   Auswertung von Genomeweite Assoziationsstudien, Microarraydaten, High throughput genotyping, Next generation sequencing, Whole genome sequencing und RNA-seq an Fallbeispielen
-   Visualisierungen der Ergebnisse durch Manhattanplot, Vucanoplot und Regional Association Plot und weiteren.
-   Grundlagen Multiomics und Pathway Analysen sowie deren Datenbanken
-   Grundlegende Methoden zum Sequenzaligment
-   Anwendung der Algorithmen an ausgewählten Fallbeispielen in R/Bioconductor

### Kompetenzorientierte Lernergebnisse {.unnumbered}

#### Wissen und Verstehen {.unnumbered}

##### Wissensverbreiterung {.unnumbered}

-   Die Studierenden sind in der Lage verschiedene Daten und Datenstrukturen zu den jeweiligen Omics-Verfahren zu erkennen und zu benennen.
-   Die Studierenden können das zentrale Dogma der Molekularbiologie erklären und visualisieren.
-   Die Studierenden sind in der Lage den Unterschied zwischen der quantitativen und qualitativen Genetik zu erklären.
-   Die Studierenden können Omics-Abbildungen erkennen und benennen.
-   Die Studierenden können externe Programme aus R heraus starten und Ergebnisse einlesen.

##### Wissensvertiefung {.unnumbered}

-   Die Studierenden können explorative Abbildungen in ausgewählten Omics-Analysen erstellen und interpretieren.
-   Die Studierenden sind in der Lage anhand einer Omics-Analyse eine Entscheidung zu treffen.
-   Die Studierenden können das Ergebnis einer Omics-Analyse im Kontext der wissenschaftlichen Fragestellung interpretieren.
-   Die Studierenden sind in der Lage aus englischen Tutorien eine Lösung für ein Omics-Verfahren einzugrenzen.
-   Die Studierenden können einfache Auswahl- und Filterregeln auf Datensätze in R anwenden.
-   Die Studierenden können erste einfache R Code Blöcke miteinander in einen Kontext setzen.

##### Wissensverständnis {.unnumbered}

-   Die Studierenden können verschiedene Ebenen der Omics-Analysen in einen wissenschaftlichen Kontext bringen und miteinander vergleichen.
-   Die Studierenden sind in der Lage eine genetische Auswertung mit den notwendigen Funktionen und Paketen in R zu skizzieren und zu erklären.
-   Die Studierenden können die einzelnen Schritte einer genetischen Analyse benennen und bei der Planung eines eigenen Experiments berücksichtigen. Sie identifizieren dabei die Probleme der jeweiligen biologischen Proben.

#### Einsatz, Anwendung und Erzeugung von Wissen {.unnumbered}

##### Nutzung und Transfer {.unnumbered}

Die Studierenden sind in der Lage einfache Kosten- und Nutzenabschätzungen anhand von genetischen Analysen durchzuführen. Diese einfachen Abschätzungen umfassen die Planung von marktwirtschaftlichen, technischen und biologischen Prozesses in der Agrarwirtschaft und den Lebenswissenschaften. Sie können dabei die verschiedenen Ebenen der Omics-Foschung in den Kontext der Anwendung und der Phänomik setzen. Die Studierenden können dabei externe Literaturquellen und deren genetischen Analysen in den Kontext des eigenen Berufsfeld setzen und aus verschiedenen, wissenschaftlichen Quellen erste informierte Vorentscheidungen für die eigenen Analysen treffen.

##### Wissenschaftliche Innovation {.unnumbered}

Die Studierende können genetische Maßzahlen aus wissenschaftlichen Publikationen in andere wissenschaftliche Kontexte einordnen. Die Studierenden kennen die Grundlagen des wissenschaftlichen Arbeitens anhand von Fallbeispielen in der Genetik. Die Studierenden können genetische Visualisierungen aus Veröffentlichungen verstehen und erste informierte Forschungsideen entwickeln. Die Studierenden sind in der Lage bei der Erstellung von Daten aus Experimenten die Verwertbarkeit in R zu berücksichtigen.

#### Kommunikation und Kooperation {.unnumbered}

Die Studierenden sind in der Lage genetische Daten und Analysen mit anderen Forschenden zu teilen. Sie können die einzelnen Schritte der Analyse erklären und die Ergebnisse allgemein verständlich erklären. Ebenfalls sind die Studierenden in der Lage gängige genetische Maßzahlen zu erkennen und zu berichten. Die Studierenden können R Code lesen, erstellen und demonstrieren.

#### Wissenschaftliches Selbstverständnis / Professionalität {.unnumbered}

Die Studierenden können wissenschaftliche Publikationen und deren genetischen Maßzahlen sowie Ergebnisse in den Kontext des eigenen Berufsfeldes setzen und somit informierte Entscheidungen treffen. Diese informierten Entscheiden betreffen sowohl die praktische Anwendung wie auch die Bewertung von Forschungsideen in der wissenschaftlichen Grundlagenforschung. Die Studierende sind sich der inhärenten Unsicherheit der wissenschaftlichen, genetischen Forschung bewusst und können die eigenen Forschungsergebnisse diesbezüglich kritisch hinterfragen.

### Literatur {.unnumbered}

-   Das Skript des Statistik- und Programmierteil des Moduls unter https://jkruppa.github.io/
-   Das Skript zum Bioinformatikteil unter https://jkruppa.github.io/bioinformatic/
-   Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013.
-   Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. https://r4ds.had.co.nz

### Voraussetzungen für die Teilnahme {.unnumbered}

Keine.

### Empfohlene Vorkenntnisse {.unnumbered}

Für dieses Modul sind Kenntnisse der deskriptiven Statistik sowie Grundkenntnisse der Statistik hilfreich aber nicht notwendig, wie sie unter anderem in den Modulen "Mathematik und Statistik (44B0266)" oder "Angewandte Statistik und Versuchswesen (44B0400)" vermittelt werden.

Studierenden, die ihre Kenntnisse und Fertigkeiten vor Beginn des Moduls auffrischen oder erweitern möchten, wird folgende Grundlagenliteratur mit dem "Skript Bio Data Science" unter https://jkruppa.github.io/ empfohlen.

In dem Modul wird mit der Software R gearbeitet. Um sich im Vorfeld mit den Basisfunktionen vertraut zu machen, eignen sich beispielsweise die folgenden Video-Tutorials unter https://www.youtube.com/c/JochenKruppa.

### Zusammenhang mit anderen Modulen {.unnumbered}

Das Modul "Statistische Bioinformatik" bereitet zudem auf weiterführende Module aus verschiedenen Themenbereichen vor. Zu diesen Themenbereichen gehören insbesondere

-   [Einführung in die Pflanzenzüchtung (44B0112)](https://www.hs-osnabrueck.de/module/44B0112/)

Welche nachfolgenden Module konkret in Frage kommen, hängt von den einzelnen Studiengängen ab. Nähere Informationen hierzu bietet der Studienverlaufsplan in der jeweils gültigen Studienordnung.

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten {.unnumbered}

#### Benotete Prüfungsleistung {.unnumbered}

Hausarbeit und Präsentation
