## Angewandte Statistik für Bioverfahrenstechnik {#sec-module-bioverfahren}

### Inhalte und Qualifikationsziele des Moduls

#### Kurzbeschreibung

Der wissenschaftliche Fortschritt ist wesentlich getragen durch eine intensive Versuchstätigkeit. Um erfolgreich in diesem Bereich tätig zu sein, sind neben statistischen Kenntnissen auch solche über Versuchsplanung erforderlich. Messdaten und Beobachtungen aus Erhebungen und Versuchen werden mit Hilfe von statistischen Methoden ausgewertet, dargestellt und interpretiert. Eine auf Daten gestützte Risikoabschätzung von Entscheidungen wird eingeübt.

#### Lehr-Lerninhalte

-   Hypothesenformulierung - Wahl geeigneter Merkmale - Skalenniveaus - Stichprobentheorie - Darstellung und Zusammenfassung der Ergebnisse (beschreibende Statistik) - Überprüfung von Hypothesen (Grundlagen der schließenden Statistik) - statistische Prozesskontrolle - Versuchsplanung

### Kompetenzorientierte Lernergebnisse

#### Wissen und Verstehen

##### Wissensverbreiterung

Studierende kennen die im biologischen Bereich allgemein üblichen statistischen Methoden, sie haben einen Überblick über die standardmäßig verwendeten Versuchsanlagen und kennen die Grundsätze der Versuchsplanung

##### Wissensvertiefung

Sie können Versuchsfragen in adäquate Versuchspläne und Strategien umwandeln und sie identifizieren die korrekte statistische Methode zur Auswertung der Messdaten,

##### Wissensverständnis

Altdaten aus MoPPS2. Bitte diese Daten auf die Felder Wissensverständnis, Nutzung und Transfer, Wissenschaftliche Innovation, Kommunikation und Kooperation, Wissenschaftliches Selbstverständnis aufteilen und ggf. erweitern/abändern!

Können - instrumentale Kompetenz Sie setzen die Standardmethoden zur Darstellung und Auswertung von Daten ein Können - kommunikative Kompetenz Sie erkennen in ihren Ergebnissen die Sachzusammenhänge und sind in der Lage, diese zu präsentieren Können - systemische Kompetenz Sie können das Risiko von auf Daten gestützten Entscheidungen verdeutlichen und abschätzen

#### Einsatz, Anwendung und Erzeugung von Wissen

##### Nutzung und Transfer

##### Wissenschaftliche Innovation

#### Kommunikation und Kooperation

##### Kommunikation und Kooperation

#### Wissenschaftliches Selbstverständnis / Professionalität

##### Wissenschaftliches Selbstverständnis / Professionalität

#### Literatur

Skript als Video unter https://www.youtube.com/c/JochenKruppa Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013. Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. \[https://r4ds.had.co.nz/\] Köhler, Wolfgang, Gabriel Schachtel, and Peter Voleske. Biostatistik: Einführung in die Biometrie für Biologen und Agrarwissenschaftler. Springer-Verlag, 2013.

### Voraussetzungen für die Teilnahme

#### Empfohlene Vorkenntnisse

### Verwendbarkeit des Moduls

#### Zusammenhang mit anderen Modulen

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten

#### Benotete Prüfungsleistung

Klausur

mündliche Prüfung

Referat (mit schriftlicher Ausarbeitung)
