## Angewandte Statistik und Versuchswesen {#sec-module-angewandte .unnumbered}

### Inhalte und Qualifikationsziele des Moduls {.unnumbered}

#### Kurzbeschreibung {.unnumbered}

Der wissenschaftliche Fortschritt in den Agrarwissenschaften ist wesentlich getragen durch eine intensive experimentelle Versuchstätigkeit. Um erfolgreich in diesem Bereich tätig zu sein sind neben statistischen Kenntnissen auch solche über die Techniken zur Versuchsdurchführung erforderlich. Für die Versuchsdurchführung müssen Messdaten und Beobachtungen aus Erhebungen sowie aus experimentellen Versuchen in einem Datensatz aufgearbeitet werden. In dem Modul "Angewandte Statistik und Versuchswesen" lernen Studierende die grundlegenden Algorithmen der Statistik für das spätere wissenschaftliche und angewandte Arbeiten kennen. Das Modul vermittelt die dafür notwendigen statistischen und algorithmischen praktischen Kenntnisse. Verschiedene statistische Verfahren zur Auswertung von experimentellen Daten werden vorgestellt und die statistischen Maßzahlen für das lineare Modellieren eingeübt. Einfache experimentelle Designs werden vorgestellt und Anwendungsmöglichkeiten diskutiert. Die vorhandenen Programmierkenntnisse in R werden weiter vertieft. Verschiedene einfache Fallbeispiele dienen als Einstieg für die Diskussion und der Reflexion der eigenen Versuchstätigkeit. Das Modul "Angewandte Statistik und Versuchswesen" schließt den Erwerb der Grundlagen in der Bio Data Science ab und ermöglicht den Studierenden somit einfache Experimente in den Agrarwissenschaften selbstständig zu planen und auszuwerten.

#### Lehr-Lerninhalte {.unnumbered}

Statistischer Anteil

-   Die explorative Datenanalyse und deren statistischen Maßzahlen.
-   Einführung in statistische Verteilungen anhand der Poisson- und Normalverteilung.
-   Die Varianzanalyse beinhaltend die einfaktorielle sowie zweifaktorielle ANOVA.
-   Grundlagen des nicht-parametrischen Tests beinhaltend Wilcoxon-Mann-Whitney-Test sowie Kruskal-Wallis-Test.
-   Grundlagen der simplen linearen Regression und der multiplen linearen Regression sowie deren statistischen Maßzahlen der Modellgüte am Beispiel eines normalverteilten Endpunkts.
-   Diagnostischen Testen und deren statistischen Maßzahlen.
-   Chi-Quadrat-Test für eine Vierfeldertafel.
-   Das multiple Testen von mehreren Mittelwerten und deren Visualisierungen.
-   Einführung in die klassischen experimentellen Designs in den Agrarwissenschaften sowie die einfache Versuchsplanung.

Informatorischer Anteil

-   Durchführung aller theoretisch erarbeiteten Inhalte in R.
-   Interpretation und Bewertung von einfachen statistischen Modellierungen in R.
-   Einfache Transformationen von Daten für die explorative Datenanalyse.
-   Demonstration der automatisierten Erstellung von Berichten in Rmarkdown sowie in R Quatro.

### Kompetenzorientierte Lernergebnisse {.unnumbered}

#### Wissen und Verstehen {.unnumbered}

##### Wissensverbreiterung {.unnumbered}

Statistischer Anteil

-   Die Studierenden kennen einfache experimentelle Designs in den Agrarwissenschaften.
-   Die Studierenden kennen einfache Repräsentationen der experimentellen Designs als Datensatz.
-   Die Studierenden können verschiedene statistische Tests händisch durchführen.
-   Die Studierenden sind in der Lage zwischen einen parametrischen und einem nicht-parametrischen Test zu unterscheiden.

Informatorischer Anteil

-   Die Studierenden kennen die gängigen Funktionen für die Datenaufbereitung in R.
-   Die Studierenden können den Ablauf für die Erstellung einer einfachen Datenanalyse in R beschreiben.
-   Die Studierenden sind in der Lage aus englischen Internetquellen eine Lösung für ein R Problem einzugrenzen.

##### Wissensvertiefung {.unnumbered}

Statistischer Anteil

-   Die Studierenden können eine simple lineare Regression für eine Normalverteilung modellieren.
-   Die Studierenden können eine Aussage über die Güte eines simplen linearen Modells abgeben.
-   Die Studierenden können eine Korrelation berechnen und interpretieren.
-   Die Studierenden können einen multiplen Gruppenvergleich für einen normalverteilten Endpunkt rechnen und die p-Werte entsprechend adjustieren.
-   Die Studierenden sind in der Lage eine einfache explorative Datenanalyse mit einem multiplen Gruppenvergleich zu verbinden.

Informatorischer Anteil

-   Die Studierenden können Datensätze in R bearbeiten.
-   Die Studierenden können einfache experimentelle Designs in R visualisieren.
-   Die Studierenden können verschiedene Ausgaben von statistischen Tests in R visualisieren.

##### Wissensverständnis {.unnumbered}

Statistischer Anteil

-   Die Studierenden sind die der Lage eine wissenschaftliche Fragestellung mit einem einfachen experimentellen Design zu verbinden.
-   Die Studierenden können einfache linearen Modellierungen bewerten und interpretieren.

Informatorischer Anteil

-   Die Studierenden können verschiedene statistische Tests und eine lineare Modellierung mit einer explorativen Datenanalye in einen Kontext setzen.

#### Einsatz, Anwendung und Erzeugung von Wissen {.unnumbered}

##### Nutzung und Transfer {.unnumbered}

Die Studierenden sind in der Lage einfache Kosten- und Nutzenabschätzungen anhand von statistischen linearen Modellen durchzuführen. Diese Abschätzungen umfassen im Besonderen die Planung von einfachen experimentellen Designs in den Agrarwissenschaften. Die Studierenden können statistische Unterschiede aus multiplen Gruppenvergleichen berechnen und eine Risikoabschätzung treffen. Die Studierenden sind in der Lage selbständig einfache statistische Analysen auf Datensätzen in R durchzuführen. Die Studierenden können einfache experimentelle Designs für verschiedene Berufsfelder und Anwendungen abwägen und diskutieren.

##### Wissenschaftliche Innovation {.unnumbered}

Die Studierende können statistische Maßzahlen aus wissenschaftlichen Publikationen in andere wissenschaftliche Kontexte einordnen. Die Studierenden können selbständig eigene wissenschaftliche Fragestellungen mit Fallbeispielen abgleichen und entsprechend der eigenen Anforderungen modifizieren. Die Studierenden können explorative Abbildungen aus Veröffentlichungen verstehen und erste informierte Forschungsideen entwickeln. Die Studierenden sind in der Lage bei der Erstellung von Daten aus Experimenten die wissenschaftliche Verwertbarkeit in R zu gewährleisten. Die Studierenden kennen die Möglichkeit über automatisierte Berichte die Reproduzierbarkeit der eigenen Forschungsergebnisse zu gewährleisten.

#### Kommunikation und Kooperation {.unnumbered}

Die Studierenden sind in der Lage die Daten der durchgeführten Experimente und entsprechende R Skripte der statistische Auswertungen mit anderen Forschenden zu teilen. Die Studierenden können die statistischen Analyseergebnisse vorstellen und Änderungswünsche entsprechend durchführen.

#### Wissenschaftliches Selbstverständnis / Professionalität {.unnumbered}

Keine. Es handelt sich um ein Grundlagenmodul.

### Literatur {.unnumbered}

-   Das Skript des Statistik- und Programmierteil des Moduls unter https://jkruppa.github.io/
-   Teile des Skripts als Video unter https://www.youtube.com/c/JochenKruppa
-   Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013.
-   Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. \[https://r4ds.had.co.nz/\]
-   Data Science for Agriculture in R unter https://schmidtpaul.github.io/DSFAIR/

### Voraussetzungen für die Teilnahme {.unnumbered}

Keine.

### Empfohlene Vorkenntnisse {.unnumbered}

Für dieses Modul werden Kenntnisse der deskriptiven Statistik sowie Grundkenntnisse der Statistik vorausgesetzt, wie sie in dem Modul "Mathematik und Statistik (44B0266)" vermittelt werden.

Studierenden, die ihre Kenntnisse und Fertigkeiten vor Beginn des Moduls auffrischen möchten, wird folgende Grundlagenliteratur mit dem "Skript Bio Data Science" unter https://jkruppa.github.io/ empfohlen.

In dem Modul wird mit der Software R gearbeitet. Um sich im Vorfeld mit den Basisfunktionen vertraut zu machen, eignen sich beispielsweise die folgenden Video-Tutorials unter https://www.youtube.com/c/JochenKruppa.

### Zusammenhang mit anderen Modulen {.unnumbered}

Das Modul "Angewandte Statistik und Versuchswesen" bereitet zudem auf weiterführende Module aus verschiedenen Themenbereichen vor. Zu diesen Themenbereichen gehören insbesondere

-   [Steuerung der vegetativen Entwicklung krautiger Pflanzen (44B0608)](https://www.hs-osnabrueck.de/module/44b0608/)
-   [Projektplanung und -management (44B0654)](https://www.hs-osnabrueck.de/module/44B0654/)
-   [Berufspraktisches Projekt (BAP) (44B0595)](https://www.hs-osnabrueck.de/module/44B0595/)

Welche nachfolgenden Module konkret in Frage kommen, hängt von den einzelnen Studiengängen ab. Nähere Informationen hierzu bietet der Studienverlaufsplan in der jeweils gültigen Studienordnung.

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten {.unnumbered}

#### Benotete Prüfungsleistung {.unnumbered}

Klausur
