## Modellierung landwirtschaftlicher Daten {#sec-module-modellierung-landwirtschaft .unnumbered}

### Inhalte und Qualifikationsziele des Moduls {.unnumbered}

#### Kurzbeschreibung {.unnumbered}

Die Modellierung landwirtschaftlicher Daten spielt eine zentrale Rolle in verschiedenen wissenschaftlichen Disziplinen der Agrarwissenschaften. Die Modellierung von komplexen Daten ermöglicht nicht nur das Gewinnen von Erkenntnissen über biologische Prozesse, sondern auch die Vorhersage zukünftiger Ereignisse weit über die gängigen Gruppenvergleiche aus Feldexperimenten hinaus. Oftmals sind diese biologischen Abhängigkeiten nicht linear, sondern folgen nicht-linearen Trends. Die Modellierung solcher nicht-linearen Abhängigkeiten erfordert spezielle Kompetenzen in der statistischen Analyse, insbesondere bei Zeitreihen, räumlichen Daten (eng. "spatial data") oder genetischen Daten vor. In dem Modul "Modellierung landwirtschaftlicher Daten" werden die gängigen statistische Verfahren zur Auswertung dieser und weiterer Daten vorgestellt. Im Weiteren spielt die Vorhersage von Ereignissen eine entscheidende Rolle in den Agrarwissenschaften, sei es für die Früherkennung von Risiken oder die Steuerung landwirtschaftlicher Prozesse. Im Modul werden die Grundlagen des maschinellen Lernens präsentiert und anhand von Fallbeispielen erläutert. Das Modul "Modellierung landwirtschaftlicher Daten" vermittelt den Studierenden somit fortgeschrittene Kenntnisse und Fähigkeiten im Bereich der Datenmodellierung und -analyse im Kontext der Landwirtschaft. Studierende erwerben dabei grundlegende Fähigkeiten für zukünftige wissenschaftliche und praktische Arbeiten im Bereich der Modellierung landwirtschaftlicher Daten. Der Fokus liegt dabei auf der Darstellung, Verarbeitung und statistischer Modellierung komplexer landwirtschaftlicher Daten. Fallstudien aus verschiedenen Bereichen der Agrarwissenschaften werden verwendet, um die erworbenen theoretischen Kenntnisse in die Praxis umzusetzen. Dabei wird R/Bioconductor für die Datenanalyse genutzt. Das Modul "Modellierung landwirtschaftlicher Daten" erweitert die bisherigen Kenntnisse der Studierenden in der Auswertung agrarwissenschaftlicher Daten und bereitet auf anspruchsvolle Aufgaben in diesem Bereich vor.

#### Lehr-Lerninhalte {.unnumbered}

-   Einführung in die statistischen Modellierung sowie deren Interpretation und Bewertung am Beispiel der multiplen linearen Regression.
-   Besonderheiten der statistischen Modellierung der Varianzstrukturen von Zeitreihen und räumlichen Daten ("spatial data").
-   Die explorative Datenanalyse und deren statistischen Maßzahlen sowie die Visualisierung von räumlichen und zeitlichen Daten.
-   Multivariate statistische Analysen zur Erkennung von Gruppenzugehörigkeiten anhand von Clusteranalysen.
-   Einführung in die klassischen experimentellen Designs in den Agrarwissenschaften.
-   Grundlagen der Analyse von genetischen Daten anhand ausgewählter, beispielhafter Omics-Ebenen.
-   Genetische Distanzen und polygenetische Bäume zur Darstellung evolutionärer Beziehungen.
-   Grundlagen des maschinellen Lernens und der Klassifikation von Ereignissen sowie Maßzahlen der Bewertung eines maschinellen Lernalgorithmus.
-   Anwendung der grundlegenden maschinellen Lernverfahren beispielhaft durch k-NN, Random Forest und Neuronale Netze.
-   Automatisierte Erstellung von Berichten in R Quatro.
-   Einführung in die Erstellung von interaktiven R Shiny Apps.

### Kompetenzorientierte Lernergebnisse {.unnumbered}

#### Wissen und Verstehen {.unnumbered}

##### Wissensverbreiterung {.unnumbered}

-   Die Studierenden kennen die gängigen experimentellen Designs in den Agrarwissenschaften.
-   Die Studierenden kennen die entsprechenden Repräsentationen der experimentellen Designs als Datensatz.
-   Die Studierenden sind in der Lage verschiedene Daten und Datenstrukturen in der Genetik zu erkennen und zu benennen.
-   Die Studierenden kennen die gängigen Datenformate für räumliche und zeitliche Daten.
-   Die Studierenden können die gängigen, vorgestellten statistischen Modellierungen benennen und unterscheiden.
-   Die Studierenden kennen die gängigen Funktionen für die Modellierungen und Datenaufbereitung in R.

##### Wissensvertiefung {.unnumbered}

-   Die Studierenden können explorative Abbildungen erstellen und interpretieren.
-   Die Studierenden können räumliche und zeitliche Daten visualisieren.
-   Die Studierenden können das Ergebnis eines statistischen Modells im Kontext der wissenschaftlichen Fragestellung interpretieren.
-   Die Studierenden sind in der Lage anhand eines statistisches Modells eine Entscheidung zu treffen.
-   Die Studierenden können verschiedene statistisches Modelle anhand statistischer Maßzahlen miteinander vergleichen und eine informierte Modellauswahl treffen.
-   Die Studierenden sind in der Lage die Ausgabe eines statistischen Modells in R zu interpretieren.
-   Die Studierenden können einen automatischen Bericht in R Quatro erstellen.

##### Wissensverständnis {.unnumbered}

-   Die Studierenden können ein statistisches Modell mit einer explorativen Datenanalyse oder Visualisierung in einen Kontext bringen.
-   Die Studierenden sind in der Lage Modellierungen mit den notwendigen Funktionen und Paketen in R durchzuführen.

#### Einsatz, Anwendung und Erzeugung von Wissen {.unnumbered}

##### Nutzung und Transfer {.unnumbered}

Räumliche Daten in landwirtschaftlichen Kontexten zu sammeln, zu organisieren und zu analysieren.

Modelle für landwirtschaftliche Prozesse unter Verwendung von räumlichen Daten zu entwickeln und zu validieren.

Genetische Daten in landwirtschaftlichen Untersuchungen zu integrieren und die Auswirkungen von Genotypen auf Erträge und Qualität zu bewerten.

Fortgeschrittene statistische und mathematische Methoden für die Analyse von landwirtschaftlichen Daten anzuwenden.

Die Ergebnisse der Datenanalyse klar und verständlich zu kommunizieren, sowohl schriftlich als auch mündlich.

Die Studierenden sind in der Lage einfache lineare Kosten- und Nutzenabschätzungen anhand von statistischen Modellen durchzuführen. Diese einfachen Abschätzungen umfassen die Planung von marktwirtschaftlichen, technischen und biologischen Prozesses in der Agrarwirtschaft und Ingenieurwissenschaften. Die Studierenden können dabei externe Literaturquellen und deren statistischen Maßzahlen in den Kontext des eigenen Berufsfeld setzen und aus verschiedenen, wissenschaftlichen Quellen erste informierte Vorentscheidungen treffen. Die Studierenden sind in der Lage die grundlegenden Konzepte der Programmierung in R in anderen Programmiersprachen zuerkennen.

##### Wissenschaftliche Innovation {.unnumbered}

Die Studierende können statistische Maßzahlen aus wissenschaftlichen Publikationen in andere wissenschaftliche Kontexte einordnen. Die Studierenden kennen die Grundlagen des wissenschaftlichen Arbeitens anhand von Fallbeispielen. Die Studierenden können explorative Abbildungen aus Veröffentlichungen verstehen und erste informierte Forschungsideen entwickeln. Die Studierenden sind in der Lage bei der Erstellung von Daten aus Experimenten die Verwertbarkeit in R zu berücksichtigen.

#### Kommunikation und Kooperation {.unnumbered}

Die Studierenden sind in der Lage durch das Konzept von "tidy data" erhobene Daten mit anderen Forschenden zu teilen. Ebenfalls sind die Studierenden in der Lage gängige statistische Maßzahlen zu erkennen und zu berichten. Die Studierenden können R Code lesen, erstellen und demonstrieren.

#### Wissenschaftliches Selbstverständnis / Professionalität {.unnumbered}

Keine. Es handelt sich um ein Grundlagenmodul.

### Literatur {.unnumbered}

-   Das Skript des Statistik- und Programmierteil des Moduls unter https://jkruppa.github.io/
-   Dormann, Carsten F. Parametrische Statistik. Springer Berlin Heidelberg, 2013.
-   Wickham, Hadley, and Garrett Grolemund. R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc., 2016. https://r4ds.had.co.nz

### Voraussetzungen für die Teilnahme {.unnumbered}

Keine. Bitte aber die empfohlenen Vorkenntnisse beachten.

### Empfohlene Vorkenntnisse {.unnumbered}

Für dieses Modul werden vertiefte Kenntnisse der deskriptiven Statistik sowie Grundkenntnisse der Statistik vorausgesetzt, wie sie unter anderem in den Modulen "Mathematik und Statistik (44B0266)" und "Angewandte Statistik und Versuchswesen (44B0400)" oder "Angewandte Statistik für Bioverfahrenstechnik (44B0567)" vermittelt werden.

Studierenden, die ihre Kenntnisse und Fertigkeiten vor Beginn des Moduls auffrischen möchten, wird folgende Grundlagenliteratur mit dem "Skript Bio Data Science" unter https://jkruppa.github.io/ empfohlen.

In dem Modul wird mit der Software R gearbeitet. Um sich im Vorfeld mit den Basisfunktionen vertraut zu machen, eignen sich beispielsweise die folgenden Video-Tutorials unter https://www.youtube.com/c/JochenKruppa.

### Zusammenhang mit anderen Modulen {.unnumbered}

Das Modul "Statistische Bioinformatik" bereitet zudem auf weiterführende Module aus verschiedenen Themenbereichen vor. Zu diesen Themenbereichen gehören insbesondere

-   [Einführung in die Pflanzenzüchtung (44B0112)](https://www.hs-osnabrueck.de/module/44B0112/)

Welche nachfolgenden Module konkret in Frage kommen, hängt von den einzelnen Studiengängen ab. Nähere Informationen hierzu bietet der Studienverlaufsplan in der jeweils gültigen Studienordnung.

### Voraussetzungen für die Vergabe von ECTS-Leistungspunkten {.unnumbered}

#### Benotete Prüfungsleistung {.unnumbered}

Hausarbeit und Präsentation
