Der Scatterplot wird auch xy-Plot genannt. Wir stellen in einem Scatterplot zwei kontenuierliche Variablen dar. Dann wollen wir eine Linie durch die Punkte legen. Im Prinzip fragen wir uns, wie hänge die Werte auf der y-Achse von den Werten auf der x-Achse ab? Wenn sich also die Werte auf der x-Achse erhöhen, wie verhalten sich dann die Werte auf der y-Achse?

```{r }
#| echo: true
#| message: false
#| label: fig-scatter-flea-0
#| fig-align: center
#| fig-height: 4
#| fig-width: 6
#| fig-cap: "Zusammenhang zwischen der Sprungweite in [cm] und Gewicht der Flöhe. Jeder Punkt stellt eine Beobachtung dar."

ggplot(data = flea_dog_cat_tbl, aes(x = weight, y = jump_length, 
                                    color = animal)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(x = "Gewicht der Flöhe [mg]", y = "Sprungweite in [cm]",
       color = "Tierart") 

```

Die @fig-scatter-flea-0 zeigt den Scatterplot für die Spalte `weight` auf der x-Achse und `jump_length` auf der y-Achse. Mit der Funktion `geom_point()` können wir die Punktepaare für jede Beobachtung zeichnen. In unserem Fall zeichnen wir mit der Funktion `stat_smooth()` noch die entsprechende Grade durch die Punkte. Es handelt sich hierbei um eine Regression, da wir eine Gerade durch die Punktewolke zeichnen.

::: {.callout-note collapse="true"}
## Zerforschen: Simple lineare Regression

{{< include zerforschen/zerforschen-simple-regression.qmd >}}
:::
