<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 49&nbsp; Grundlagen der Klassifikation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./classification-data.html" rel="next">
<link href="./classification-preface.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen und Hunden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen, Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes-site.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren in Habitaten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Von Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Friedman Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">Klassifikation oder maschinelles Lernen</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Data splitting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Data preprocessing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Random Forest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Support vector machines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Neural networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-deep-learning.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Deep learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-bewertungsbogen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Bewertungsbogen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Modulbeschreibung</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link active" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"> <span class="header-section-number">49.1</span> Genutzte R Pakete für das Kapitel</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"> <span class="header-section-number">49.2</span> Daten</a></li>
  <li><a href="#what-he-says" id="toc-what-he-says" class="nav-link" data-scroll-target="#what-he-says"> <span class="header-section-number">49.3</span> What he say’s?</a></li>
  <li><a href="#klassifikation-vs.-regression" id="toc-klassifikation-vs.-regression" class="nav-link" data-scroll-target="#klassifikation-vs.-regression"> <span class="header-section-number">49.4</span> Klassifikation vs.&nbsp;Regression</a></li>
  <li><a href="#supervised-vs.-unsupervised" id="toc-supervised-vs.-unsupervised" class="nav-link" data-scroll-target="#supervised-vs.-unsupervised"> <span class="header-section-number">49.5</span> Supervised vs.&nbsp;unsupervised</a></li>
  <li><a href="#bias-vs.-varianz" id="toc-bias-vs.-varianz" class="nav-link" data-scroll-target="#bias-vs.-varianz"> <span class="header-section-number">49.6</span> Bias vs.&nbsp;Varianz</a></li>
  <li><a href="#problem-der-fehlenden-werte" id="toc-problem-der-fehlenden-werte" class="nav-link" data-scroll-target="#problem-der-fehlenden-werte"> <span class="header-section-number">49.7</span> Problem der fehlenden Werte</a></li>
  <li><a href="#normalisierung" id="toc-normalisierung" class="nav-link" data-scroll-target="#normalisierung"> <span class="header-section-number">49.8</span> Normalisierung</a></li>
  <li><a href="#das-rezept-mit-recipe" id="toc-das-rezept-mit-recipe" class="nav-link" data-scroll-target="#das-rezept-mit-recipe"> <span class="header-section-number">49.9</span> Das Rezept mit <code>recipe()</code></a></li>
  <li><a href="#bagging" id="toc-bagging" class="nav-link" data-scroll-target="#bagging"> <span class="header-section-number">49.10</span> Bagging</a></li>
  <li><a href="#boosting" id="toc-boosting" class="nav-link" data-scroll-target="#boosting"> <span class="header-section-number">49.11</span> Boosting</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-class-basic" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell">

</div>
<p><em>Version vom November 21, 2022 um 21:59:32</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/caution.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Dieses Kapitel dient als Einführung in die <em>Klassifikation</em> mit maschinellen Lernmethoden. Leider müssen wir wieder einiges an Worten lernen, damit wir überhaupt mit den Methoden anfangen können. Vieles dreht sich um die Aufbereitung der Daten, damit wir dann auch mit den Modellen anfangen können zu <em>arbeiten</em>. Ja ich meine wirklich Arbeiten, denn wir werden eher einen Prozess durchführen. Selten rechnet man einmal ein Modell und ist zufrieden. Meistens müssen wir noch die Modelle <em>tunen</em> um mehr aus den Modellen rauszuholen. Wir wollen bessere Vorhersagen mit einem kleineren Fehler erreichen. Das ganze können wir dann aber nicht in einem Schritt machen, sondern brauchen viele Schritte nacheinander. Damit müssen wir auch mir R umgehen können sonst ist der Prozess nicht mehr abzubilden.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Mit <em>Tuning</em> bezeichnen wir den Prozess, ein Modell wiederholt zu verändern und dabei zu verbessern. Was wir verändern können, hängt vom gewählten Algorithums ab.</span></div></div>
<section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="49.1"><h2 data-number="49.1" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">49.1</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">tidymodels</span>, <span class="va">magrittr</span>, <span class="va">conflicted</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"mutate"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"extract"</span>, <span class="st">"magrittr"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2" data-number="49.2"><h2 data-number="49.2" class="anchored" data-anchor-id="daten">
<span class="header-section-number">49.2</span> Daten</h2>
<p>In dieser Einführung nehmen wir die infizierten Ferkel als Beispiel um einmal die verschiedenen Verfahren zu demonstrieren. Ich füge hier noch die ID mit ein, die nichts anderes ist, als die Zeilennummer. Dann habe ich noch die ID an den Anfang gestellt. Wir wählen auch nur ein kleines Subset aus den Daten aus, da wir in diesem Kapitel nur Funktion demonstrieren und nicht die Ergebnisse interpretieren.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pig_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/infected_pigs.xlsx"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>pig_id <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>         infected <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">infected</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">pig_id</span>, <span class="va">infected</span>, <span class="va">age</span><span class="op">:</span><span class="va">crp</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">pig_id</span>, <span class="va">infected</span>, <span class="fu">everything</span><span class="op">(</span><span class="op">)</span><span class="op">)</span>  </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <a href="classification-knn.html#tbl-ml-basic-pig">Tabelle&nbsp;<span>52.1</span></a> siehst du nochmal einen Auschnitt aus den Daten. Wir haben noch die ID mit eingefügt, damit wir einzelne Beobachtungen nachvollziehen können.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ml-basic-pig" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 49.1— Auszug aus dem Daten zu den kranken Ferkeln.</caption>
<thead><tr class="header">
<th style="text-align: center;">pig_id</th>
<th style="text-align: center;">infected</th>
<th style="text-align: center;">age</th>
<th style="text-align: center;">sex</th>
<th style="text-align: center;">location</th>
<th style="text-align: center;">activity</th>
<th style="text-align: center;">crp</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">61</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">15.31</td>
<td style="text-align: center;">22.38</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">13.01</td>
<td style="text-align: center;">18.64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">66</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">11.31</td>
<td style="text-align: center;">18.76</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">13.33</td>
<td style="text-align: center;">19.37</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">14.71</td>
<td style="text-align: center;">21.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">15.81</td>
<td style="text-align: center;">21.45</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">407</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">11.82</td>
<td style="text-align: center;">21.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">408</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">west</td>
<td style="text-align: center;">13.91</td>
<td style="text-align: center;">20.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">409</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">12.49</td>
<td style="text-align: center;">21.95</td>
</tr>
<tr class="odd">
<td style="text-align: center;">410</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">61</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">15.26</td>
<td style="text-align: center;">23.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">411</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">13.13</td>
<td style="text-align: center;">20.23</td>
</tr>
<tr class="odd">
<td style="text-align: center;">412</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">10.01</td>
<td style="text-align: center;">19.89</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Gehen wir jetzt mal die Wörter und Begrifflichkeiten, die wir für das maschinelle Lernen später brauchen einmal durch.</p>
</section><section id="what-he-says" class="level2 page-columns page-full" data-number="49.3"><h2 data-number="49.3" class="anchored" data-anchor-id="what-he-says">
<span class="header-section-number">49.3</span> What he say’s?</h2>
<p>In diesem Teil des Skriptes werden wir wieder mit einer Menge neuer Begriffe konfrontiert. Deshalb steht hier auch eine Menge an neuen Worten drin. Leider ist es aber auch so, dass wir <em>bekanntes</em> neu bezeichnen. Wir tauchen jetzt ab in die Community der Klassifizierer und die haben dann eben die ein oder andere Sache neu benannt.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Kurze Referenz zu <a href="https://youtu.be/RAidDYQLIK4">What he says?</a></p>
</div></div><p>Die gute nachticht zuerst, wir haben ein relativ festes Vokabular. Das heißt, wir springen nicht so sehr zwischen den Begrifflichkeiten wie wir es in den anderen Teilen des Skriptes gemacht haben. Du kennst die Modellbezeichnungen wie folgt.</p>
<p><span class="math display">\[
y \sim x
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(y\)</span>, als Outcome oder Endpunkt.</li>
<li>
<span class="math inline">\(x\)</span>, als Covariate oder Einflussvariable.</li>
</ul>
<p>Das bauen wir jetzt um. Wir nennen in dem Bereich des maschinellen Lernen jetzt das <span class="math inline">\(y\)</span> und das <span class="math inline">\(x\)</span> wie folgt.</p>
<ul>
<li>
<span class="math inline">\(y\)</span> ist unser <em>label</em>, dafür gibt es kein deutsches Wort.</li>
<li>
<span class="math inline">\(x\)</span> sind unsere <em>features</em> und mehrere Features bilden den <em>feature space</em>, dafür gibt es jeweils auch kein deutsches Wort.</li>
</ul>
<p>Im folgenden Text werde ich also immer vom Label schreiben und dann damit das <span class="math inline">\(y\)</span> links von dem <code>~</code> in der Modellgleichung meinen. Wenn ich dann von den Features schreibe, meine ich alle <span class="math inline">\(x\)</span>-Variablen rechts von dem <code>~</code> in der Modellgleichung. Ja, daran muss du dich dann gewöhnen. Es ist wieder ein anderer sprachlicher Akzent in einem anderen Gebiet der Statistik.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside"><em>Label</em> meint also das <span class="math inline">\(y\)</span> oder Outcome. <em>Feature</em> beschreibt das <span class="math inline">\(x\)</span> oder die Einflussvariablen.</span></div></div>
</section><section id="klassifikation-vs.-regression" class="level2" data-number="49.4"><h2 data-number="49.4" class="anchored" data-anchor-id="klassifikation-vs.-regression">
<span class="header-section-number">49.4</span> Klassifikation vs.&nbsp;Regression</h2>
<p>Wenn mich etwas aus der Bahn geworfen hat, dann waren es die Terme <em>classification</em> und <em>regression</em> im Kontext des maschinellen Lernens. Wenn ich von <em>classification</em> schreibe, dann wollen wir ein kategoriales Label vorhersagen. Das bedeutet wir haben ein <span class="math inline">\(y\)</span> vorliegen, was nur aus Klassen bzw. Kategorien besteht. Im Zweifel haben wir dann ein Label mit <span class="math inline">\(0/1\)</span> einträgen. Wenn mehr Klassen vorliegen, wird auch gerne von <em>multiclass</em> Klassifikation gesprochen.</p>
<p>Dazu steht im Kontrast der Term <em>regression</em>. In dem Kontext vom maschinellen Lernen meint <em>regression</em> die Vorhersage eines numerischen Labels. Das heißt, wir wollen die Körpergröße der Studierenden vorhersagen und nutzen dazu einen <em>regression</em> Klassifikator. Das ist am Anfang immer etwas verwirrend. Wir unterschieden hier nur die Typen der Label, sonst nichts. Wir fassen also wie folgt zusammen.</p>
<ul>
<li>
<em>classification</em>, wir haben ein Label bzw. <span class="math inline">\(y\)</span> mit Kategorien. Nehmen wir einmal unser Ferkelbeispiel. In unserer Spalte <code>infected</code> sind die Ferkel infiziert <span class="math inline">\((1)\)</span> oder nicht-infiziert daher gesund <span class="math inline">\((0)\)</span>.</li>
<li>
<em>regression</em>, wir haben ein Label bzw. <span class="math inline">\(y\)</span> mit kontinuierlichen Werten. Unsere Ferkel haben ein Gewicht in <span class="math inline">\(kg\)</span> und daher nehmen wir die Spalte <code>weight</code>.</li>
</ul>
<p>Wir brauchen die Begriffe, da wir später in den Algorithmen spezifizieren müssen, welcher Typ die Klassifikation sein soll.</p>
</section><section id="supervised-vs.-unsupervised" class="level2 page-columns page-full" data-number="49.5"><h2 data-number="49.5" class="anchored" data-anchor-id="supervised-vs.-unsupervised">
<span class="header-section-number">49.5</span> Supervised vs.&nbsp;unsupervised</h2>
<p>Der Unterschied zwischen einer <em>suprvised</em> Lernmethode oder Algorithmus ist, dass das Label bekannt ist. Das heißt, dass wir in unseren Daten eine <span class="math inline">\(y\)</span> Spalte haben an der wir unser Modell dann trainieren können. Das Modell weiß also an was es sich optimieren soll. In <a href="#tbl-class-supervised">Tabelle&nbsp;<span>49.2</span></a> sehen wir einen kleinen Datensatz in einem <em>supervised</em> Setting. Wir haben ein <span class="math inline">\(y\)</span> in den Daten und können an diesem Label unser Modell optimieren. Oft sagen wir auch, dass wir gelabelte Daten vorliegen haben. Daher haben wir eine Spalte, die unser LAbel mit <span class="math inline">\(0/1\)</span> enthält.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside"><em>Supervised</em> heißt, dass die Daten ein Label haben und damit eine <span class="math inline">\(y\)</span> Spalte haben. Wir sagen, dass die Daten gelabelt sind. <em>Unsupervised</em> heißt, dass wir ungelabelte Daten vorliegen haben. In dem Fall von <em>semi-supervised</em> Daten, haben wir Beobachtungen mit Label und ohne Label</span></div></div>
<div id="tbl-class-supervised" class="anchored">
<table class="table">
<caption>Tabelle 49.2— Beispieldatensatz für <em>supervised learning</em>. Unsere Daten haben eine Spalte <span class="math inline">\(y\)</span>, die wir als Label in unserem Modell nutzen können. Wir haben gelabelte Daten vorliegen.</caption>
<thead><tr class="header">
<th><span class="math inline">\(y\)</span></th>
<th><span class="math inline">\(x_1\)</span></th>
<th><span class="math inline">\(x_2\)</span></th>
<th><span class="math inline">\(x_3\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.2</td>
<td>1.3</td>
<td>1.2</td>
</tr>
<tr class="even">
<td>0</td>
<td>0.1</td>
<td>0.8</td>
<td>0.6</td>
</tr>
<tr class="odd">
<td>1</td>
<td>0.3</td>
<td>2.3</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.2</td>
<td>9.1</td>
<td>1.1</td>
</tr>
</tbody>
</table>
</div>
<p>In der <a href="#tbl-class-unsupervised">Tabelle&nbsp;<span>49.3</span></a> sehen wir als Beispiel einen Datensatz ohne eine Spalte, die wir als Label nutzen können. Nazürlich haben wir in echt dann keine freie Spalte. Ich habe das einmal so gebaut, damit du den Unterschied besser erkennen kannst. Beim <em>unsuoervised</em> Lernen muss der Algorithmus sich das Label selber bauen. Wir müssen meist vorgeben, wie viele Gruppen wir im Label erwarten würden. Dann können wir den Algorithmus starten.</p>
<div id="tbl-class-unsupervised" class="anchored">
<table class="table">
<caption>Tabelle 49.3— Beispieldatensatz für <em>unsupervised learning</em>. Unsere Daten haben keine Spalte <span class="math inline">\(y\)</span>, die wir als Label in unserem Modell nutzen können. Wir haben ungelabelte Daten vorliegen.</caption>
<thead><tr class="header">
<th></th>
<th><span class="math inline">\(x_1\)</span></th>
<th><span class="math inline">\(x_2\)</span></th>
<th><span class="math inline">\(x_3\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\phantom{0}\)</span></td>
<td>0.2</td>
<td>1.3</td>
<td>1.2</td>
</tr>
<tr class="even">
<td></td>
<td>0.1</td>
<td>0.8</td>
<td>0.6</td>
</tr>
<tr class="odd">
<td></td>
<td>0.3</td>
<td>2.3</td>
<td>0.9</td>
</tr>
<tr class="even">
<td></td>
<td>0.2</td>
<td>9.1</td>
<td>1.1</td>
</tr>
</tbody>
</table>
</div>
<p>Dann gibt es natürlich auch den Fall, dass wir ein paar Beobachtungen mit einem Eintrag haben und wiederum andere Beobachtungen ohne eine Eintragung. Dann sprechen wir von einem <em>semi-supervised learning</em>. Im Prinzip ist es ein Mischmasch aus <em>supervised learning</em> und dem <em>unsupervised learning</em>. Es gibt hier aber keine genaue Grenze wie viele gelabelete Beobachtungen zu ungelabelten Beobachtungen da sein müssen.</p>
<p>Wir haben sehr oft eine <em>superised</em> Setting in unseren Daten vorliegen. Aber wie immer, du wirst vielleicht auch Cluster bilden wollen und dann ist das <em>unsupervised</em> Lernen eine Methode, die du gut nutzen kannst. Am Ende müssen jeder Beobachtung ein Label zugeordnet werden. Wer das dann macht, ist wiederum die Frage.</p>
</section><section id="bias-vs.-varianz" class="level2 page-columns page-full" data-number="49.6"><h2 data-number="49.6" class="anchored" data-anchor-id="bias-vs.-varianz">
<span class="header-section-number">49.6</span> Bias vs.&nbsp;Varianz</h2>
<p>Im Bereich des maschinellen Lernens sprechen wir oft von einem Bias/Varianz Trade-off. Das heißt, wir haben zum einen eine Verzerrung (eng. <em>Bias</em>) in unserem Auswahlprozess des anzuwendenden Algorithmus. Zum anderen ist unser Algorithmus nur bedingt genau, das heißt wir haben auch eine Varianz die durch den Algorithmus hervorgerufen wird. Hierbei musst du dich etwas von dem Begriff <em>Varianz</em> im Sinne der deskriptiven Statistik lösen. Die Varianz beschreibt hier die Variabilität in der Vorhersage. Wir meinen hier schon eine Art Abweichung, aber das Wort Varianz mag hier etwas verwirrend sein. In <a href="#fig-class-bias-overview">Abbildung&nbsp;<span>49.1</span></a> sehen wir nochmal den Zusammenhang zwischen dem Bias und der Varianz.</p>
<div id="fig-class-bias-overview" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-bias-overview.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 49.1— Der Bias ist eine menschliche Komponente des Modells. Wir wählen das Modell aus und bringen damit eine <em>mögliche</em> Verzerrung in die Auswertung. Die Varianz wird vom Modell selber verursacht und beschreibt den Zusammenhang zwischen dem Traings- und Testdaten.</figcaption><p></p>
</figure>
</div>
<p>Wir können daher wie folgt den Bias und die Varianz beschreiben. Wichtig ist hier nochmal, dass wir uns hier die Worte etwas anders benutzen, als wir es in der klassischen Statistik tun würden.</p>
<ul>
<li>
<strong>Bias</strong>: Der Bias (deu. <em>Verzerrung</em>) unseres Modells hat mit den Annahmen zu tun, die wir über die Daten machen. Und damit auch wie gut das Modell zu den Daten passt, auf denen das Modell trainiert wird. Ein Modell mit einem hohen Bias passt nicht gut zu den Trainingsdaten, hat eine begrenzte Flexibilität oder ist extrem einfach für die vorliegenden Daten. Wenn ein Modell zu simpel ist, führt es häufig zu einem hohen Trainingsfehler. Das Label der Traingsdaten wird daher nicht gut wiedergegeben.</li>
<li>
<strong>Varianz</strong>: Die Varianz unseres Modells sagt aus, wie das Modell seine Vorhersageergebnisse in Abhängigkeit von den Traingsdaten variiert. Ein Modell mit hoher Varianz kann sich gut an die Trainingsdaten anpassen und hat daher Probleme bei der Verallgemeinerung auf die ungesehene Testdaten, was zu einem hohen Testfehler führt.</li>
</ul>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Der Bias zeigt uns, wie gut unser Modell der Realität entspricht. Die Varianz sagt uns, wie gut unser Modell auf die Trainingsdaten abgestimmt ist.</span></div></div>
<p>In <a href="#fig-class-bias-var-overview">Abbildung&nbsp;<span>49.2</span></a> shen wir den Zusammenhang zwischen Bias und Varianz an einer Dartscheibe dargestellt. Wenn wir eine hohe Varianz und einen hohen Bias haben, dann treffen wir großflächig daneben. Wenn sich der Bias verringert, dann treffen wir mit einer großen Streuung in die Mitte. Eine geringe Varianz und ein hoher Bias lässt uns präsize in daneben treffen. Erst mit einem niedrigen Bias und einer niedrigen Varianz treffen wir in die Mitte der Dartscheibe.</p>
<div id="fig-class-bias-var-overview" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-bias-variance-overview.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 49.2— Abstrakte Darstellung des Bias vs.&nbsp;Varianz Trade-off anhand einer Dartscheibe.</figcaption><p></p>
</figure>
</div>
<p>Der gesamte Fehler unseres Modells setzt sich dann wie folgt aus dem Bias und der Varianz zusammen. Wir können den Bias kontrollieren in dem wir verschiedene Algorithmen auf unsere Daten testen und überlegen, welcher Algorithmus am besten passt. Die Varianz können wir dadurch verringern, dass wir unsere Modelle tunen und daher mit verschiedenen Parametern laufen lassen. Am Ende haben wir aber immer einen Restfehler <span class="math inline">\(\epsilon\)</span>, den wir nicht reduzieren können. Unser Modell wird niemals perfekt zu generalisieren sein. Wenn <span class="math inline">\(\epsilon\)</span> gegen Null laufen sollte, spricht es eher für ein Auswendiglernen des Modells als für eine gute Generalisierung.</p>
<p><span class="math display">\[
error = variance + bias + \epsilon
\]</span></p>
<p>In der <a href="#fig-class-trade-off">Abbildung&nbsp;<span>49.3</span></a> sehen wir den Zusammenhang zwischen Bias und Varianz nochmal in einer Abbildung im Zusammenhang mit der Modellkomplxität gezeigt. Je größer die Modellkomplexität wird, desto geringer wird der Bias. Dafür wird das Modell aber überangepasst und die Varianz des Modells steigt. Daher gibt es ein Optimum des <em>total errors</em> bei dem der Bias und Varianz jeweils Minimal sind.</p>
<div id="fig-class-trade-off" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-trade-off.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 49.3— Zusammenhang zwischen der Modellkomplexität, dem Bias und der Varainz. Es gibt ein Optimum des <em>total errors</em>.</figcaption><p></p>
</figure>
</div>
<p>Jetzt wollen wir uns den Zusammenhang zwischen Bias und Varianz nochmal an der Bilderkennung veranschaulichen. Wir nutzen dafür die Bilderkennung um Meerschweinchen und Schafe auf Bildern zu erkennen. In der <a href="#fig-class-bias-03">Abbildung&nbsp;<span>49.4</span></a> sehen wir mich in einem Krokodilkostüm. Unser erstes Modell 1 klassifiziert mich als Meerschweinchen. Wir haben also ein sehr hohes Bias vorliegen. Ich bin kein Meerschweinchen.</p>
<div id="fig-class-bias-03" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-bias-03.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 49.4— Unser erstes Modell hat ein hohes Bias. Daher klassifiziert mich das Modell 1 als ein Meerschweinchen, obwohl ich ein Krokodil bin.</figcaption><p></p>
</figure>
</div>
<p>In der <a href="#fig-class-bias-01">Abbildung&nbsp;<span>49.5 (a)</span></a> sehen wir ein durch Model 2 korrekt klassifiziertes Meerschweinchen. Nun hat dieses Modell 2 aber eine zu hohe Varianz. Die hohe Varianz in dem Modell 2 sehen wir in der <a href="#fig-class-bias-02">Abbildung&nbsp;<span>49.5 (b)</span></a>. Das Meerschweinchen wird nicht als Meerschweinchen von Modell 2 erkannt, da es keine krausen Haare und eine andere Fellfarbe hat. Wir sind also auch mit diesem Modell 2 nicht zufrieden. Nur exakt die gleichen Meerschweinchen zu klassifizieren ist uns nicht genug.</p>
<div id="fig-class-bias-0102" class="quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-center">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 44.4%;justify-content: center;">
<div id="fig-class-bias-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-bias-01.png" class="img-fluid figure-img" data-ref-parent="fig-class-bias-0102"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) In unserem Trainingsdatensatz hat unser Modell 2 eine hohe Varianz. Das Modell 2 findet zwar das Meerschweinchen im Bild, aber hat Probleme auf dem folgenden Testdaten.</figcaption><p></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 55.6%;justify-content: center;">
<div id="fig-class-bias-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-bias-02.jpg" class="img-fluid figure-img" data-ref-parent="fig-class-bias-0102"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) In unseren Testdaten zu dem trainierten Modell 2 kann das Meerschweinchen im Bild nicht erkannt werden. Das Modell 2 hat eine zu hohe Varianz.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 49.5— Unser zweites Modell hat eine hohe Varianz. Es erkennt zwar <em>perfekt</em> eine Meerschweinchenart, muss aber bei einer anderen Art passen.</figcaption><p></p>
</figure>
</div>
<p>In der <a href="#fig-class-bias-02">Abbildung&nbsp;<span>49.5 (b)</span></a> sehen wir nun unser Modell 3 mit einem niedrigen Bias und einer niedrigen Varianz. Das Modell 3 kann Schafe in einer Herde als Schafe klassifizieren. Aber auch hier sehen wir gewisse Grenzen. Das Schaf welches den Kopf senkt, wird nicht von dem Modell 3 als ein Schaf erkannt. Das kann vorkommen, wenn in dem Traingsdaten so ein Schaf nicht als Bild vorlag. Häufig brauchen wir sehr viele gute Daten. Mit guten Daten, meine ich nicht immer die gleichen Beobachtungen oder Bilder sondern eine gute Bandbreite aller möglichen Gegebenheiten.</p>
<div id="fig-class-bias-04" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/class-bias-04.png" class="img-fluid figure-img" style="width:70.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 49.6— Unser letztes Modell 3 hat eine niedrige Varianz und ist in der Lage die Schafe auch als Schafe zu entdecken. Ein Schaf senkt den Kopf und schon kann unser Modell 3 das Schaf nicht mehr finden.</figcaption><p></p>
</figure>
</div>
<p>Wir sehen also, das Thema Bias und Varianz beschäftigt uns bei der Auswahl des richtigen Modells und bei der Festlegung der Modellkomplexität. Du kannst dir merken, dass ein komplexeres Modell auf den Trainingsdaten meistens bessere Ergebnisse liefert und dann auf den Testdaten schlechtere. Ein komplexes Modell ist meist überangepasst (eng. <em>overfitted</em>).</p>
</section><section id="problem-der-fehlenden-werte" class="level2" data-number="49.7"><h2 data-number="49.7" class="anchored" data-anchor-id="problem-der-fehlenden-werte">
<span class="header-section-number">49.7</span> Problem der fehlenden Werte</h2>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Mehr zu fehlenden Werten
</div>
</div>
<div class="callout-body-container callout-body">
<p>In dem <a href="classification-pre-processing.html"><span>Kapitel&nbsp;51</span></a> erfährst du, wie du mit den fehlenden Werten im maschinellen Lernen umgehst. Wir werden dort aber nicht alle Details wiederholen. In dem <a href="stat-modeling-missing.html"><span>Kapitel&nbsp;38</span></a> erfährst du dann mehr über die Hintergründe und die Verfahren zum Imputieren von fehlenden Werten.</p>
</div>
</div>
<p>Ein wichtiger Punkt ist bei der Nutzung von maschinellen Lernen, dass wir <em>keine</em> fehlenden Beobachtungen in den Daten haben dürfen. Es darf kein einzelner Wert fehlen. Dann funktionieren die Algorithmen nicht und wir erhalten eine Fehlermeldung. Deshalb ist es die erste Statistikerpflicht darauf zu achten, dass wir nicht so viele fehlenden Werte in den Daten haben. Das ist natürlich nur begrenzt möglich. Wenn wir auf die Gummibärchendaten schauen, dann wurden die Daten ja von mir mit Erhoben. Dennoch haben wir viele fehlende Daten mit drin, da natürlich Studierende immer was eingetragen haben. Wenn du wissen willst, wie du mit fehlenden Werten umgehst, dann schaue einmal dazu das <a href="stat-modeling-missing.html"><span>Kapitel&nbsp;38</span></a> an. Wir gehen hier nicht nochmal auf alle Verfahren ein, werden aber die Verfahren zur Imputation von fehlenden Werten dann am Beispiel der Gummibärchendaten anwenden. Müssen wir ja auch, sonst könnten wir auch die Daten nicht für maschinelle Lernverfahren nutzen.</p>
</section><section id="normalisierung" class="level2" data-number="49.8"><h2 data-number="49.8" class="anchored" data-anchor-id="normalisierung">
<span class="header-section-number">49.8</span> Normalisierung</h2>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Mehr zur Normalisierung
</div>
</div>
<div class="callout-body-container callout-body">
<p>In dem <a href="classification-pre-processing.html"><span>Kapitel&nbsp;51</span></a> erfährst du, wie du die Normalisierung von Daten im maschinellen Lernen anwendest. In dem <a href="eda-transform.html"><span>Kapitel&nbsp;17</span></a> kannst du dann mehr über die Hintergründe und die Verfahren zur Normalisierung nachlesen. Wir wenden in hier nur die Verfahren an, gehen aber nicht auf die Details weiter ein.</p>
</div>
</div>
<p>Unter Normalisierung der Daten fassen wir eigentlich ein <em>preprocessing</em> der Daten zusammen. Wir haben ja unsere Daten in einer ursprünglichen Form vorliegen. Häufig ist diese Form nicht geeignet um einen maschinellen Lernalgorithmus auf diese ursprüngliche Form der Daten anzuwenden. Deshalb müssen wir die Daten vorher einmal anpassen und in eine geleiche Form über alle Variablen bringen. Was meine ich so kryptisch damit? Schauen wir uns einmal in der <a href="#tbl-class-normal">Tabelle&nbsp;<span>49.4</span></a> ein Beispiel für zu normalisierende Daten an.</p>
<div id="tbl-class-normal" class="anchored">
<table class="table">
<caption>Tabelle 49.4— Beispieldatensatz für einen Datensatz der nomiert werden muss. Die einzelenen Spalten haben sehr unterschiedliche Wertebereiche eingetragen.</caption>
<thead><tr class="header">
<th><span class="math inline">\(y\)</span></th>
<th><span class="math inline">\(x_1\)</span></th>
<th><span class="math inline">\(x_2\)</span></th>
<th><span class="math inline">\(x_3\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.2</td>
<td>1430</td>
<td>23.54</td>
</tr>
<tr class="even">
<td>0</td>
<td>0.1</td>
<td>1096</td>
<td>18.78</td>
</tr>
<tr class="odd">
<td>1</td>
<td>0.4</td>
<td>2903</td>
<td>16.89</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.2</td>
<td>7861</td>
<td>12.98</td>
</tr>
</tbody>
</table>
</div>
<p>Warum müssen diese Daten normalisiert werden? Wir haben mit <span class="math inline">\(x_1\)</span> eine Variable vorliegen, die im Iterval <span class="math inline">\([0;1]\)</span> liegt. Die Variable <span class="math inline">\(x_2\)</span> liegt in einem zehntausendfach größeren Wertebereich. Die Werte der Variable <span class="math inline">\(x_3\)</span> ist auch im Vergleich immer noch hundertfach im Wertebereich unterschiedlich. Dieser großen Unterschiede im Wertebereich führen zu fehlern bei Modellieren. Wir können hierzu das <a href="eda-transform.html"><span>Kapitel&nbsp;17</span></a> betrachten. Dort werden gängige Transformationen einmal erklärt. Wir gehen hier nicht nochmal auf alle Verfahren ein, sondern konzentrieren uns auf die häufigsten Anwendungen.</p>
</section><section id="das-rezept-mit-recipe" class="level2 page-columns page-full" data-number="49.9"><h2 data-number="49.9" class="anchored" data-anchor-id="das-rezept-mit-recipe">
<span class="header-section-number">49.9</span> Das Rezept mit <code>recipe()</code>
</h2>
<p>Wenn wir jetzt in den folgenden Kapiteln mit den maschinellen Lernverfahren arbeiten werden, nutzen wir das R Paket <code>recipes</code> um uns mit der Funktion <code>recipe()</code> ein Rezept der Klassifikation zu erstellen. Warum brauchen wir das? Wir werden sehen, dass wir auf verschiedene Datensätze immer wieder die gleichen Algorithmen anwenden. Auch wollen wir eine Reihe von Vorverarbeitungsschritten (eng. <em>preprocessing steps</em>) auf unsere Daten anwenden. Dann ist es einfacher, wenn wir alles an einem Ort abgelegt haben. Am Ende haben wir auch verschiedene Spalten in unseren Daten. Meistens eine Spalte mit dem Label und dann sehr viele Spalten für unsere Features oder Prediktoren. Vielleiht noch eine Spalte für die ID der Beobachtungen. Das macht alles sehr unübersichtlich. Deshalb nutzen wir <code>recipes</code> um mehr Ordnung in unsere Klassifikation zu bekommen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Du findest hier die <a href="https://recipes.tidymodels.org/">Introduction to recipes</a> und dann eine Idee wie <code>recipes</code> funktionieren mit <a href="https://www.tidymodels.org/start/recipes/">Preprocess your data with recipes</a>.</p>
</div></div><p>Wir gehen nun folgende vier Schritte einmal durch. Am Ende haben wir dann unsere Klassifikation durchgeführt. Vorher haben wir aber unseren Algorithmus und damit unser Modell definiert und auch festgelegt, was in den Daten noch angepasst und transformiert werden soll. Alles zusammen bringen wir dann in ein <code>workflow</code> Objekt in dem alles gespeichert ist.</p>
<ol type="1">
<li>Erstellen des Modells (<code>logreg_mod</code>),</li>
<li>ein Vorverarbeitungsrezept (eng. <em>preprocessing</em>) für unseren Datensatz <code>pig_tbl</code> erstellen (<code>pig_rec</code>),</li>
<li>das Modell und das Rezept in einem Wokflow bündeln (<code>pig_wflow</code>), und</li>
<li>unseren Workflow mit einem einzigen Aufruf von <code>fit()</code> trainieren.</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">logreg_mod</span> <span class="op">&lt;-</span> <span class="fu">logistic_reg</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">set_engine</span><span class="op">(</span><span class="st">"glm"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pig_rec</span> <span class="op">&lt;-</span> <span class="fu">recipe</span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">pig_tbl</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">update_role</span><span class="op">(</span><span class="va">pig_id</span>, new_role <span class="op">=</span> <span class="st">"ID"</span><span class="op">)</span>  <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_nominal_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pig_rec</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  variable type    role      source  
  &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;   
1 pig_id   numeric ID        original
2 age      numeric predictor original
3 sex      nominal predictor original
4 location nominal predictor original
5 activity numeric predictor original
6 crp      numeric predictor original
7 infected nominal outcome   original</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pig_wflow</span> <span class="op">&lt;-</span> <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">add_model</span><span class="op">(</span><span class="va">logreg_mod</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">add_recipe</span><span class="op">(</span><span class="va">pig_rec</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pig_wflow</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow ════════════════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: logistic_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
2 Recipe Steps

• step_dummy()
• step_zv()

── Model ───────────────────────────────────────────────────────────────────────
Logistic Regression Model Specification (classification)

Computational engine: glm </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pig_fit</span> <span class="op">&lt;-</span> <span class="va">pig_wflow</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">fit</span><span class="op">(</span>data <span class="op">=</span> <span class="va">pig_tbl</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pig_fit</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: logistic_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
2 Recipe Steps

• step_dummy()
• step_zv()

── Model ───────────────────────────────────────────────────────────────────────

Call:  stats::glm(formula = ..y ~ ., family = stats::binomial, data = data)

Coefficients:
       (Intercept)                 age            activity                 crp  
        -21.256180            0.035596           -0.087440            1.042905  
          sex_male  location_northeast  location_northwest       location_west  
          0.592557           -0.550867           -0.417869           -0.245572  

Degrees of Freedom: 411 Total (i.e. Null);  404 Residual
Null Deviance:      545.64 
Residual Deviance: 410.25   AIC: 426.25</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pig_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">extract_fit_parsnip</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">round</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>         p.value <span class="op">=</span> <span class="fu">pvalue</span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term               estimate std.error statistic p.value
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  
1 (Intercept)          -21.3       3.03     -7.02 &lt;0.001 
2 age                    0.04      0.03      1.32 0.190  
3 activity              -0.09      0.09     -0.94 0.350  
4 crp                    1.04      0.11      9.27 &lt;0.001 
5 sex_male               0.59      0.32      1.88 0.060  
6 location_northeast    -0.55      0.35     -1.57 0.120  
7 location_northwest    -0.42      0.32     -1.3  0.190  
8 location_west         -0.25      0.36     -0.68 0.500  </code></pre>
</div>
</div>
</section><section id="bagging" class="level2" data-number="49.10"><h2 data-number="49.10" class="anchored" data-anchor-id="bagging">
<span class="header-section-number">49.10</span> Bagging</h2>
<p>Das Wort <em>Bagging</em> steht für <em>bootstrap aggregating</em> und ist eine Methode, um Vorhersagen aus verschiedenen Modellen zu kombinieren. Dabei müssen alle Modelle mit dem gleichen Algorithmus laufen, können aber auf verschiedenen Datensätzen oder aber Variablensätzen zugreifen. Häufig haben die Modelle eine hohee Varianz in der Vorhersage und wir nutzen dann Bagging um die Modelle miteinader zu kombinieren und dadurch die Varianz zu verringern. Die Ergebnisse der Modelle werden dann im einfachsten Fall gemittelt. Das Ergebnis jeder Modellvorhersage geht mit gleichem Gewicht in die Vorhersage ein. Wir haben auch noch andere Möglichkeiten, aber du kannst dir Vorstellen wir rechnen verschiedene Modelle <span class="math inline">\(k\)</span>-mal und bilden dann ein finales Modell in dem wir alle <span class="math inline">\(k\)</span>-Modelle zusammenfassen. Wie wir die Zusammenfassung rechnen, ist dann immer wieder von Fall zu Fall unterschiedlich. Wir erhalten am Ende einen <em>Ensemble</em> Klassifizierer, da ja ein Ensemble von Modellen zusammengefasst wird.</p>
</section><section id="boosting" class="level2" data-number="49.11"><h2 data-number="49.11" class="anchored" data-anchor-id="boosting">
<span class="header-section-number">49.11</span> Boosting</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/caution.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>https://medium.com/greyatom/a-quick-guide-to-boosting-in-ml-acf7c1585cb5</p>
<p>https://towardsdatascience.com/boosting-algorithms-explained-d38f56ef3f30</p>
<p>https://howtolearnmachinelearning.com/articles/boosting-in-machine-learning/</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./classification-preface.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Klassifikation oder maschinelles Lernen</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./classification-data.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Data splitting</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>