<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 17&nbsp; Visualisierung von Daten</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./eda-transform.html" rel="next">
<link href="./eda-descriptive.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./eda-preface.html">Explorative Datenanalyse</a></li><li class="breadcrumb-item"><a href="./eda-ggplot.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Fortgeschrittene Versuchsplanung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link active" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">17.1</span> Genutzte R Pakete</a></li>
  <li>
<a href="#grundlagen-in-ggplot" id="toc-grundlagen-in-ggplot" class="nav-link" data-scroll-target="#grundlagen-in-ggplot"><span class="header-section-number">17.2</span> Grundlagen in ggplot()</a>
  <ul class="collapse">
<li><a href="#datenbeispiel" id="toc-datenbeispiel" class="nav-link" data-scroll-target="#datenbeispiel"><span class="header-section-number">17.2.1</span> Datenbeispiel</a></li>
  <li><a href="#erste-abbildung-in-ggplot" id="toc-erste-abbildung-in-ggplot" class="nav-link" data-scroll-target="#erste-abbildung-in-ggplot"><span class="header-section-number">17.2.2</span> Erste Abbildung in ggplot()</a></li>
  <li><a href="#sec-eda-histogramm" id="toc-sec-eda-histogramm" class="nav-link" data-scroll-target="#sec-eda-histogramm"><span class="header-section-number">17.2.3</span> Histogramm</a></li>
  <li><a href="#density-plot" id="toc-density-plot" class="nav-link" data-scroll-target="#density-plot"><span class="header-section-number">17.2.4</span> Density Plot</a></li>
  <li><a href="#sec-eda-boxplot" id="toc-sec-eda-boxplot" class="nav-link" data-scroll-target="#sec-eda-boxplot"><span class="header-section-number">17.2.5</span> Boxplot</a></li>
  <li><a href="#sec-eda-barplot" id="toc-sec-eda-barplot" class="nav-link" data-scroll-target="#sec-eda-barplot"><span class="header-section-number">17.2.6</span> Barplot oder Balkendiagramm</a></li>
  <li><a href="#sec-eda-dotplot" id="toc-sec-eda-dotplot" class="nav-link" data-scroll-target="#sec-eda-dotplot"><span class="header-section-number">17.2.7</span> Dotplot</a></li>
  <li><a href="#sec-eda-scatter" id="toc-sec-eda-scatter" class="nav-link" data-scroll-target="#sec-eda-scatter"><span class="header-section-number">17.2.8</span> Scatterplot</a></li>
  <li><a href="#sec-eda-mosaic" id="toc-sec-eda-mosaic" class="nav-link" data-scroll-target="#sec-eda-mosaic"><span class="header-section-number">17.2.9</span> Mosaic Plot</a></li>
  </ul>
</li>
  <li><a href="#%C3%BCberschriften-achsen-und-legenden" id="toc-überschriften-achsen-und-legenden" class="nav-link" data-scroll-target="#%C3%BCberschriften-achsen-und-legenden"><span class="header-section-number">17.3</span> Überschriften, Achsen und Legenden</a></li>
  <li><a href="#mathematische-ausdr%C3%BCcke-in-den-achsenbeschriftungen" id="toc-mathematische-ausdrücke-in-den-achsenbeschriftungen" class="nav-link" data-scroll-target="#mathematische-ausdr%C3%BCcke-in-den-achsenbeschriftungen"><span class="header-section-number">17.4</span> Mathematische Ausdrücke in den Achsenbeschriftungen</a></li>
  <li><a href="#die-okabe-ito-farbpalette" id="toc-die-okabe-ito-farbpalette" class="nav-link" data-scroll-target="#die-okabe-ito-farbpalette"><span class="header-section-number">17.5</span> Die Okabe-Ito Farbpalette</a></li>
  <li><a href="#abbildungen-nebeneinander" id="toc-abbildungen-nebeneinander" class="nav-link" data-scroll-target="#abbildungen-nebeneinander"><span class="header-section-number">17.6</span> Abbildungen nebeneinander</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-eda-ggplot" class="quarto-section-identifier"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom July 20, 2023 um 15:51:04</em></p>
<blockquote class="blockquote">
<p><em>“Numerical quantities focus on expected values, graphical summaries on unexpected values.” — John Tukey</em></p>
</blockquote>
<p>Ein wichtiger Teil in der Analyse von Daten ist die Visualisierung. Wir glauben keine Auswertung eines mathematischen Algorithmus, wenn wir nicht die Bestätigung in einer Abbildung sehen. Daher ist die Visualisierung die Grundlage für ein fundiertes, wissenschaftliches Arbeiten. In diesem Kapitel stelle ich dir verschiedene Abbildungen vor, die uns helfen werden zu Verstehen ob es einen Zusammenhang zwischen Y und X gibt. Wir haben ein <span class="math inline">\(y\)</span> vorliegen, was wir auf die y-Achse eines Graphen legen und daneben dann mehrere Variablen bzw. Spalten die wir <span class="math inline">\(x\)</span> nennen. Eine der Variablen legen wir auf die x-Achse des Graphen. Nach den anderen <span class="math inline">\(x\)</span> färben wir die Abbildung ein.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Wir nennen eine Abbildung auch häufig Plot. Das ist der englische Begriff und hat nichts in unserem Kontext mit einer Fläche zu tun.</span></div></div>
<p>In diesem Kapitel wollen wir durch die häufigsten und wichtigsten Abbildungen in der explorativen Datenanalyse durchghen. Das wären im folgenden diese Abbildungen:</p>
<ul>
<li>
<strong>Histogramm</strong> in <a href="#sec-eda-histogramm"><span>Kapitel&nbsp;17.2.3</span></a> für mehr als 20 Beobachtungen (pro Gruppe). Wir nutzen ein Histogramm um die Verteilung einer Variable zu visualisieren.</li>
<li>
<strong>Boxplot</strong> in <a href="#sec-eda-boxplot"><span>Kapitel&nbsp;17.2.5</span></a> für 5 bis 20 Beobachtungen (pro Gruppe). Ebenso wie bei einem Histogramm, geht es bei einem Boxplot auch um die Verteilung der einer Variable.</li>
<li>
<strong>Barplot</strong> in <a href="#sec-eda-barplot"><span>Kapitel&nbsp;17.2.6</span></a> für 5 und mehr Beobachtungen (pro Gruppe). Der Barplot oder das <strong>Balkendiagramm</strong> bzw. <strong>Säulendiagramm</strong> stellt den Mittelwert und die Standardabweichung da.</li>
<li>
<strong>Dotplot</strong> in <a href="#sec-eda-dotplot"><span>Kapitel&nbsp;17.2.7</span></a> für 3 bis 5 Beobachtungen (pro Gruppe). Hier geht es weniger um die Verteilung der Variable, sondern darum die wenigen Beobachtungen zu visualisieren.</li>
<li>
<strong>Scatterplot</strong> in <a href="#sec-eda-scatter"><span>Kapitel&nbsp;17.2.8</span></a> für zwei kontinuierliche Variablen. Auch <strong>xy-Plot</strong> genannt. Die Abbildung, die dir bekannt sein müsste. Wir zeichnen hier eine Grade durch eine Punktewolke.</li>
<li>
<strong>Mosaicplot</strong> in <a href="#sec-eda-mosaic"><span>Kapitel&nbsp;17.2.9</span></a> für zwei diskrete Variablen. Eine etwas seltene Abbildung, wenn wir Variablen abbilden wollen, die diskret sind bzw. aus Kategorien bestehen.</li>
</ul>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Konkret ist eine <strong>Variable</strong> gleich einer <strong>Spalte</strong> in einem Datensatz.</span></div></div>
<section id="genutzte-r-pakete" class="level2" data-number="17.1"><h2 data-number="17.1" class="anchored" data-anchor-id="genutzte-r-pakete">
<span class="header-section-number">17.1</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">readxl</span>, <span class="va">ggmosaic</span>, </span>
<span>               <span class="va">janitor</span>, <span class="va">see</span>, <span class="va">patchwork</span>, <span class="va">latex2exp</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="grundlagen-in-ggplot" class="level2 page-columns page-full" data-number="17.2"><h2 data-number="17.2" class="anchored" data-anchor-id="grundlagen-in-ggplot">
<span class="header-section-number">17.2</span> Grundlagen in ggplot()</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Im Gegensatz zu dem Pipe-Operator <code>%&gt;%</code> nutzt ggplot den Operator <code>+</code> um die verschiedenen ggplot Funktionen (<code>geom_</code>) miteinander zu verbinden.</span></div></div>
<p>Wir nutzen in R das R Paket <code>ggplot2</code> um unsere Daten zu visualisieren. Die zentrale Idee von <code>ggplot2</code> ist, dass wir uns eine Abbildung wie ein Sandwich bauen. Zuerst legen wir eine Scheibe Brot hin und legen uns dann Scheibe für Scheibe weitere Schichten übereinander. Oder die Idee eines Bildes, wo wir erst die Leinwand definieren und dann Farbschicht über Farbschicht auftragen. Das Konzept von <code>ggplot2</code>ist schlecht zu be<em>schreiben</em> deshalb habe ich auch noch zwei Videos hierfür gemacht. Um den Prozess von <code>ggplot2</code> zu visualisieren…</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Grundlagen von ggplot() im Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/SGwSVzJ9C-s">Einführung in R - Teil 16.0 - Trockenübung ggplot2 simpel und einfach erklärt</a> als Video.</p>
<p>Sowie auch auf YouTube <a href="https://youtu.be/SRRQQO3DXtc">Einführung in R - Teil 16.1 - Abbildungen mit ggplot in R erstellen. Idee und Konzept von ggplot</a> als Video. Also alles nochmal als Video - vielleicht einfacher nachzuvollziehen als in einem Fließtext.</p>
</div>
</div>
<p>Die Funktion <code>ggplot()</code> ist die zentrale Funktion, die die Leinwand erschafft auf der wir dann verschiedene Schichten aufbringen werden. Diese Schichten heißen <code>geom</code>. Es gibt nicht nur ein <code>geom</code> sondern mehrere. Zum Beispiel das <code>geom_boxplot</code> für die Erstellung von Boxplots, das <code>geom_histogram</code> für die Erstellung von Histogrammen. <a href="https://ggplot2.tidyverse.org/reference/index.html">Die Auswahl ist riesig</a>. Die einzelnen Schichten werden dann über den Operator <code>+</code> miteinander verbunden. Soviel erstmal zur Trockenübung. Schauen wir uns das ganze einmal an einem Beispiel an.</p>
<section id="datenbeispiel" class="level3 page-columns page-full" data-number="17.2.1"><h3 data-number="17.2.1" class="anchored" data-anchor-id="datenbeispiel">
<span class="header-section-number">17.2.1</span> Datenbeispiel</h3>
<p>Wir importieren den Datensatz <code>flea_cat_dog.xlsx</code> und wollen einzelne Variablen visualisieren. Wir kennen den Datensatz schon aus den vorherigen Beispielen. Dennoch nochmal hier der Datensatz in <a href="#tbl-cat-dog-ggplot">Tabelle&nbsp;<span>17.1</span></a> einmal dargestellt.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flea_dog_cat_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/flea_dog_cat.xlsx"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>animal <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">animal</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Spaltennamen sind in <strong>Englisch</strong> und haben <strong>keine Leerzeichen</strong>. Die Funktion <code>clean_names()</code> aus dem R Paket <code>janitor</code> ist hier eine Hilfe.</span></div></div>
<p>Im Folgenden ist es wichtig, dass du dir die Spaltennamen merkst. Wir können nur die exakten, wortwörtlichen Spaltennamen verwenden. Sonst erhalten wir einen Fehler. Deshalb haben wir auch keine Leerzeichen in den Spaltennamen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cat-dog-ggplot" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.1— Beispieldatensatz für Eigenschaften von Flöhen von zwei Tierarten.</caption>
<thead><tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">jump_length</th>
<th style="text-align: center;">flea_count</th>
<th style="text-align: center;">grade</th>
<th style="text-align: center;">infected</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.9</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">11.8</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">9.1</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.6</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">4.1</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section><section id="erste-abbildung-in-ggplot" class="level3 page-columns page-full" data-number="17.2.2"><h3 data-number="17.2.2" class="anchored" data-anchor-id="erste-abbildung-in-ggplot">
<span class="header-section-number">17.2.2</span> Erste Abbildung in ggplot()</h3>
<p>Der folgende R Code erstellt die Leinwand in der <a href="#fig-ggplot-1">Abbildung&nbsp;<span>17.1</span></a> für die folgende, zusätzliches Schichten (<code>geom</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span> , y <span class="op">=</span> <span class="va">jump_length</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir schauen uns einmal den Code im Detail an.</p>
<ul>
<li>
<code>ggplot</code> ruft die Funktion auf. Die Funktion ist dafür da den Plot zu zeichnen.</li>
<li>
<code>data = flea_dog_cat_tbl</code> bennent den Datensatz aus dem der Plot gebaut werden soll.</li>
<li>
<code>aes()</code>ist die Abkürzung für <em>aesthetics</em> und beschreibt, was auf die x-Achse soll, was auf die y-Achse soll sowie ob es noch andere Faktoren in den Daten gibt.
<ul>
<li>
<code>x</code> braucht den Spaltennamen für die Variable auf der x-Achse.</li>
<li>
<code>y</code> braucht den Spaltennamen für die Variable auf der y-Achse.</li>
</ul>
</li>
</ul>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class=""><strong>Faktoren</strong> meint hier andere Gruppenvariablen. Variablen sind ein anderes Wort für Spalten. Also Variablen die wir mit <code>as_factor</code>erschaffen haben.</span></div></div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ggplot-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-ggplot-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.1— Leere ggplot() Leinwand mit den Spalten <code>animal</code> und <code>jump_length</code> aus dem Datensatz <code>flea_dog_cat_tbl</code>.</figcaption></figure>
</div>
</div>
</div>
<p>Wir sehen, dass wir nichts sehen in <a href="#fig-ggplot-1">Abbildung&nbsp;<span>17.1</span></a>. Der Grund ist, dass wir noch kein <code>geom</code> hinzugefügt haben. Das <code>geom</code> beschreibt nun wie die Zahlen in der Datentabelle <code>flea_dog_cat_tbl</code> visualisiert werden sollen.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Histogramm, Boxplot, Scatterplot und Mosaicplot im Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/Zdw6NlLauNw">Einführung in R - Teil 16.2 - Histogramm, Boxplot, Scatterplot und Mosaicplot mit ggplot in R</a> als Video. Weitere Videos werden dann noch folgen und ergänzt.</p>
</div>
</div>
</section><section id="sec-eda-histogramm" class="level3" data-number="17.2.3"><h3 data-number="17.2.3" class="anchored" data-anchor-id="sec-eda-histogramm">
<span class="header-section-number">17.2.3</span> Histogramm</h3>
<p>Wir nutzen für die Erstellung eines Histogramms den Datensatz <code>dog_fleas_hist.csv</code>. Wir brauchen für ein anständiges Histogramm, wo du auch was erkennen kannst, mindestens 20 Beobachtung. Am besten mehr noch mhr Beobachtungen. Deshalb schauen wir uns jetzt einmal 39 Hunde an und zählen wieviele Flöhe die Hunde jeweils haben, dargestellt in der Spalte<code>flea_count</code>. Darüber hinaus bestimmen wir auch noch das mittlere Gewicht der Flöhe auf dem jeweiligen Hund, dargestellt in der Spalte <code>flea_weight</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dog_fleas_hist_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/dog_fleas_hist.csv"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cat-dog-histogram" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.2— Beispieldatensatz für die Anzahl an Flöhen auf 39 Hunden. Gezählt wurde die Anzahl an Flöhen <code>flea_count</code> und das gemittelte Gewicht der Flöhe <code>flea_weight</code>.</caption>
<thead><tr class="header">
<th style="text-align: center;">flea_count</th>
<th style="text-align: center;">flea_weight</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">7.43</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">21.04</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">20.07</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">21.90</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">24.96</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">27.08</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">16.58</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">19.92</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">24.63</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">21.64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">20.97</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">23.15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">14.91</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">19.39</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">17.66</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">19.15</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">25.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">26.38</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">19.33</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">13.29</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">17.81</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">23.56</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">18.64</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">15.64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">19.88</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">18.40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">25.17</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><a href="#tbl-cat-dog-histogram">Tabelle&nbsp;<span>17.2</span></a> zeigt den Datensatz <code>dog_fleas_hist.csv</code>. Wir wollen jetzt die Variable <code>flea_count</code> und <code>flea_weight</code> jeweils abbilden. Wir beginnen mit der diskreten Variable <code>flea_count</code>. Im Gegensatz zu der Variable <code>flea_weight</code> haben wir bei der Anzahl gleiche Zahlen vorliegen, die wir dann zusammen darstellen können. <a href="#fig-dotplot-flea-1">Abbildung&nbsp;<span>17.2</span></a> zeigt die Darstellung der Tabelle. Auf der x-Achse ist die Anzahl an Flöhen dargestellt. Auf der y-Achse die Anzahl der jeweiligen Anzahl an Flöhen. Das klingt jetzt etwas schief, aber schauen wir uns die Abbilung näher an.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-dotplot-flea-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dotplot-flea-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.2— Die Anzahl von Flöhen auf 39 Hunden. Jeder Punkt entspricht einem Hund und der entsprechenden Anzahl an Flöhen auf dem Hund.</figcaption></figure>
</div>
</div>
</div>
<p>Wir sehen in <a href="#fig-dotplot-flea-1">Abbildung&nbsp;<span>17.2</span></a> das acht Hunde keine Flöhe hatten - also eine Anzahl an Flöhen von 0. Auf der anderen Seite hatten zwei Hunde vier Flöhe und ein Hund hatte sogar fünf Flöhe. Wir sehen also die <em>Verteilung</em> der Anzahl an Flöhen über alle unsere 39 Hundebeobachtungen.</p>
<p>Wir schauen uns aber die Verteilung der Anzahl an Flöhen meist nicht in der Form von gestapelten Punkten an, sondern in der Form eines Histogramms also einem Balkendiagramm. <a href="#fig-hist-flea-count">Abbildung&nbsp;<span>17.3</span></a> zeigt das Histogramm für die Anzahl der Flöhe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_fleas_hist_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_count</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">1</span>, fill <span class="op">=</span> <span class="st">"gray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Anzahl Flöhe"</span>, y <span class="op">=</span> <span class="st">"Anzahl"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-hist-flea-count" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-hist-flea-count-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.3— Histogramm der Anzahl von Flöhen auf 39 Hunden.</figcaption></figure>
</div>
</div>
</div>
<p>Was sehen wir in der <a href="#fig-hist-flea-count">Abbildung&nbsp;<span>17.3</span></a>? Anstatt von gestapelten Punkten sehen wir jetzt Balken, die die jeweilige Anzahl an Flöhen zusammenfassen. Der Unterschied ist bei einer diskreten Variable wie der Anzahl (eng. <em>count</em>) relativ gering.</p>
<p>Anders sieht es für kontenuierliche Variablen mit Kommazahlen aus. Schauen wir uns das Gewicht der Flöhe an, so sehen wir, dass es sehr viele Zahlen gibt, die nur einmal vorkomen. <a href="#fig-hist-flea-1">Abbildung&nbsp;<span>17.4</span></a> zeigt das Histogramm für das Geicht der Flöhe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_fleas_hist_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">1</span>, fill <span class="op">=</span> <span class="st">"gray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Gewicht [mg]"</span>, y <span class="op">=</span> <span class="st">"Anzahl"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-hist-flea-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-hist-flea-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.4— Histogramm des Gewichts von Flöhen auf 39 Hunden.</figcaption></figure>
</div>
</div>
</div>
<p>Wie entsteht nun ein Hisotgramm für konetnierliche Zahlen? Schauen wir uns dafür einmal ein kleineres Datenbeispiel an, in dem wir nur Flöhe mit einem Gewicht größer als 11 und kleiner als 19 wäheln. Wir nutzen dazu die Funktion <code>filter(flea_weight &gt; 11 &amp; flea_weight &lt; 19)</code>. Wir erhalten folgende Zahlen und das entsprechende Histogramm.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.29 14.91 15.64 16.58 17.66 17.81 18.40 18.64</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-hist-flea-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-hist-flea-2-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.5— Zusammenhang zwischen den einzelnen Beobachtungen und der Höhe der einzelnen Balken am Beispiel von acht Hunden.</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-hist-flea-2">Abbildung&nbsp;<span>17.5</span></a> zeigt das Histogramm der reduzierten Daten. Die roten vertikalen Linien zeigen die Position der einzelnen Flohgewichte auf der x-Achse. Die blauen Hilfslinien machen nochmal klarer, wie hoch die einzelnen Balken sind sowie welche Beobachtungen auf der x-Achse in den jeweiligen Balken mit eingehen. Wir sehen, dass wir einen Hund mit Flöhen haben, die zwischen 12.5 und 13.5 wiegen - der entsprechende Balken erhält die Anzahl von eins. Auf der anderen Seite sehen wir, dass es drei Hunde mit Flöhen, die zwischen 17.5 und 18.5 wiegen. Daher wächst der Balken auf eine Anzahl von drei.</p>
<p>Wir können mit der Option <code>binwidth</code> in dem <code>geom_histogram()</code> einstellen, wie breit auf der x-Achse die jeweiligen Balken sein sollen. Hier empfiehlt es sich verschiedene Zahlen für <code>binwidth</code>auszuprobieren.</p>
</section><section id="density-plot" class="level3 page-columns page-full" data-number="17.2.4"><h3 data-number="17.2.4" class="anchored" data-anchor-id="density-plot">
<span class="header-section-number">17.2.4</span> Density Plot</h3>
<p>Eine weitere Möglichkeit sich eine Verteilung anzuschauen, ist die Daten nicht als Balkendiagramm sondern als Densityplot - also Dichteverteilung - anzusehen. Im Prinzip verwandeln wir die Balken in eine Kurve. Damit würden wir im Prinzip unterschiedliche Balkenhöhen ausgleichen udn eine “glattere” Darstellung erreichen. Wir wir aber gleich sehen werden, benötigen wir dazu eine Menge an Beoabchtungen und auch dann ist das Ergebnis eventuell nicht gut zu interpretieren.</p>
<div class="page-columns page-full">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_fleas_hist_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_count</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">1</span>, fill <span class="op">=</span> <span class="st">"gray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Anzahl Flöhe"</span>, y <span class="op">=</span> <span class="st">"Anzahl"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_fleas_hist_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_count</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"gray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Anzahl Flöhe"</span>, y <span class="op">=</span> <span class="st">"Häufigkeit"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-dens-flea-1" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-dens-flea-1-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dens-flea-1-1.png" class="img-fluid figure-img" data-ref-parent="fig-dens-flea-1" width="576"></p>
<figcaption class="figure-caption">(a) Histogramm</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-dens-flea-1-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dens-flea-1-2.png" class="img-fluid figure-img" data-ref-parent="fig-dens-flea-1" width="576"></p>
<figcaption class="figure-caption">(b) Densityplot</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;17.6— Zusammenhang von Histogramm und Densityplot an der Anzahl der Flöhe auf 39 Hunden.</figcaption><p></p>
</figure>
</div>
</div>
<p><a href="#fig-dens-flea-1">Abbildung&nbsp;<span>17.6</span></a> zeigt auf der linken Seite erneut die Abbildung des Histogramms als Balkendiagramm für die Anzahl der Flöhe auf den 39 Hunden. Auf der rechten Seite die entsprechenden gleichen Daten als Denistyplot. Klar ist die Wellenbewegung des Densityplots zu erkennen. Hier leigen zu wenige Beobachtungen und Kategorien auf der x-Achse vor, so dass der Densityplot nicht zu empfehlen ist.</p>
<div class="page-columns page-full">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_fleas_hist_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">1</span>, fill <span class="op">=</span> <span class="st">"gray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Gewicht [mg]"</span>, y <span class="op">=</span> <span class="st">"Anzahl"</span><span class="op">)</span> </span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_fleas_hist_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"gray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Gewicht [mg]"</span>, y <span class="op">=</span> <span class="st">"Häufigkeit"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-dens-flea-2" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-dens-flea-2-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dens-flea-2-1.png" class="img-fluid figure-img" data-ref-parent="fig-dens-flea-2" width="576"></p>
<figcaption class="figure-caption">(a) Histogramm</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-dens-flea-2-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dens-flea-2-2.png" class="img-fluid figure-img" data-ref-parent="fig-dens-flea-2" width="576"></p>
<figcaption class="figure-caption">(b) Densityplot</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;17.7— Zusammenhang von Histogramm und Densityplot am Gewicht der Flöhe auf 39 Hunden.</figcaption><p></p>
</figure>
</div>
</div>
<p><a href="#fig-dens-flea-2">Abbildung&nbsp;<span>17.7</span></a> zeigt auf der linken Seite erneut die Abbildung des Histogramms als Balkendiagramm für das Gewicht der Flöhe auf den 39 Hunden. Insbesondere bei dieser Abbildung erkennst du die Nachteile des Densityplot. Dadurch das es einen Peak von acht Hunden mit einem Flohgewicht von 0 gibt, zeigt der Densityplot eine seltsame Wellenform. Es emppfielt sich daher die Daten zuerst als Histogramm zu betrachten.</p>
</section><section id="sec-eda-boxplot" class="level3 page-columns page-full" data-number="17.2.5"><h3 data-number="17.2.5" class="anchored" data-anchor-id="sec-eda-boxplot">
<span class="header-section-number">17.2.5</span> Boxplot</h3>
<p>Mit dem Boxplot können wir den Median und die Quartile visualisieren. In <a href="#fig-boxplot-drawn">Abbildung&nbsp;<span>17.8</span></a> sehen wir einen Boxplot, der den Median und die Quartile visualisiert. Die Box wird aus dem IQR gebildet. Der Median wird als Strich in der Box gezeigt. Die Schnurrhaare (eng. <em>Whiskers</em>) sind das 1.5 fache des IQR. Punkte die außerhalb der Schnurrhaare liegen werden als einzelne Punkte dargestellt. Diese einzelnen Punkte werden auch als Ausreißer (eng. <em>Outlier</em>) bezeichnet.</p>
<div class="column-page">
<div id="fig-boxplot-drawn" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/boxplot-drawn.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.8— Ein Boxplot der die statistischen Maßzahlen Median und Quartile visualisiert. Die Box wird aus dem IQR gebildet. Der Median wird als Strich in der Box gezeigt. Die Schnurrhaare sind das 1.5 fache des IQR. Punkte die außerhalb der Schnurrhaare liegen werden als einzele Punkte dargestellt.</figcaption></figure>
</div>
</div>
<p>In <a href="#fig-boxplot-drawn-distribution">Abbildung&nbsp;<span>17.9</span></a> sehen wir den Zusammenhang zwischen einem Histogramm, Densityplot und dem Boxplot. Der Median <span class="math inline">\(\tilde{y}\)</span> im Boxplot zeigt die höchste Stelle des Densityplots an. Durch einen Boxplot kann die Verteilung der entsprechenden Zahlen abgeschätzt werden.</p>
<div id="fig-boxplot-drawn-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/boxplot-drawn-distribution.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.9— Der Zusammenhang von Histogram, Densityplot und Boxplot.</figcaption></figure>
</div>
<p>Die “liegende” Darstellung des Boxplots dient nur der Veranschaulichung und dem Verständnis des Zusammenhangs von Histogramm und Boxplot. In der <a href="#fig-boxplot-drawn-flipped">Abbildung&nbsp;<span>17.10</span></a> sehen wir drei Boxplots für einen Faktor mit drei Leveln. Jedes Level wird duch einen Boxplot dargestellt. Zum Beispiel eine Düngerbehandlung mit drei Konzentrationen. Auf der x-Achse würden wir die Behandelung finden und auf der y-Achse das Trockengewicht in [kg/ha].</p>
<div id="fig-boxplot-drawn-flipped" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/boxplot-drawn-flipped.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.10— Typische Darstellung von drei Gruppen jeweils dargestellt durch einen Boxplot. Boxplots werden in der Anwendung stehtend dargestellt. Insbesondere wenn die Boxplots mehrere Gruppen repräsentieren.</figcaption></figure>
</div>
<p>Wie erstellen wir nun einen Boxplot in R? Zuerst laden wir die Daten mit der Funktion <code>read_excel()</code> in R, wenn du die Daten als <code>.xlsx</code> Datei vorliegen hast. Im XX kannst du nochmal das Importieren von Daten wiederholen.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flea_dog_cat_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/flea_dog_cat.xlsx"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot-flea-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-boxplot-flea-0-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.11— An 39 Hunden wurde die Anzahl an Flöhen gezählt.</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-boxplot-flea-0">Abbildung&nbsp;<span>17.11</span></a> ist der Boxplot für die Daten aus der Datei <code>flea_dog_cat.xlsx</code> dargestellt. Auf der x-Achse finden wir die Tierart als <code>cat</code> und <code>dog</code>. Auf der y-Achse ist die Sprungweite in [cm] dargestellt.</p>
<p>Wir erkennen auf einen Blick, dass die Sprungweite von den Hundeflöhen weiter ist als die Sprungweite der Katzenflöhe. Im Weiteren können wir abschätzen, dass die Streuung etwa gleich groß ist. Die Boxen sind in etwa gleich groß und die Whiskers in etwa gleich lang.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>                                    fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.25</span>, shape <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Tierart"</span>, y <span class="op">=</span> <span class="st">"Sprungweite [cm]"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-boxplot-freshmatter-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-boxplot-freshmatter-2-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.12— An 39 Hunden wurde die Anzahl an Flöhen gezählt.</figcaption></figure>
</div>
</div>
</div>
<p>Wir neigen dazu die Boxplots über zu interpretieren, wenn die Anzahl der Beobachtungen klein ist. Deshalb können wir mit dem <code>geom_jitter()</code> noch die Beobachtungen zu den Boxplot ergänzen, dargestellt in <a href="#fig-boxplot-freshmatter-2">Abbildung&nbsp;<span>17.12</span></a>. Die Funktion <code>geom_jitter()</code> streut die Punkte zufällig, so dass keine Punkte übereinander liegen. Wir haben hier die Streuweite durch die Option <code>width = 0.25</code> etwas eingeschränkt. Darüber hinaus habe wir das Aussehen der Punkte mit <code>shape = 1</code> geändert, so dass wir die Jitter-Punkte von den potenziellen Ausreißer-Punkten unterscheiden können. Du kannst auch andere Zahlen hinter <code>shape</code> eintragen um verschiedene Punktesymbole durch zuprobieren. Eine Übersicht an <code>shapes</code> findest du auch hier unter <a href="http://www.cookbook-r.com/Graphs/Shapes_and_line_types/">Cookbook for R &gt; Graphs &gt; Shapes and line types</a>.</p>
</section><section id="sec-eda-barplot" class="level3" data-number="17.2.6"><h3 data-number="17.2.6" class="anchored" data-anchor-id="sec-eda-barplot">
<span class="header-section-number">17.2.6</span> Barplot oder Balkendiagramm</h3>
<p>Der Barplot oder das Balkendiagramm auch Säulendiagramm ist eigentlich veraltet. Wir haben mit dem Boxplot eine viel bessere Methode um eine Verteilung und <em>gleichzeitig</em> auch die Gruppenunterschiede zu visualisieren. Warum nutzen wir jetzt so viel den Barplot? Das hat damit zu tun, dass früher - oder besser bis vor kurzem - in Excel kein Boxplot möglich war. Daher nutzte jeder der mit Excel seine Daten auswertet den Barplot. Und was der Bauer nicht kennt… deshalb ist hier auch der Barplot dargestellt. Ich persönlich mag den Barplot eher weniger. Der Barplot ist einfach schlechter als der Boxplot. Wir haben nur die Standardabweichung als Maßzahl für die Streuung. Beim Boxplot haben wir das IQR, was uns mehr über die Streuung aussagt. Aber gut, häufig musst du den Barplot in deiner Abschlussarbeit machen. Also dann hier der Barplot. Wie erstellen wir nun einen Barplot in R? Zuerst laden wir die Daten mit der Funktion <code>read_excel()</code> in R, wenn du die Daten als <code>.xlsx</code> Datei vorliegen hast.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flea_dog_cat_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/flea_dog_cat.xlsx"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir müssen jetzt für <code>ggplot()</code> noch den Mittelwert und die Streuung für die Gruppen berechnen. Du kannst als Streuung die Standardabweichung oder den Standardfehler nehmen. Ich würde die Standardabweichung bei kleinen Fallzahlen kleiner als 20 Beobachtungen nehmen.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stat_tbl</span> <span class="op">&lt;-</span> <span class="va">flea_dog_cat_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">animal</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">summarise</span><span class="op">(</span>mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">jump_length</span><span class="op">)</span>,</span>
<span>            sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">jump_length</span><span class="op">)</span>,</span>
<span>            se <span class="op">=</span> <span class="va">sd</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir nutzen nun das Objekt <code>stat_tbl</code> um den Barplot mit der Funktion <code>ggplot()</code> zu erstellen. Dabei müssen wir zum einen schauen, dass die Balken nicht übereinander angeordnet sind. Nebeneinander angeordnete Balken kriegen wir mit der Option <code>stat = "identity"</code> in dem <code>geom_bar()</code>. Dann müssen wir noch die Fehlerbalken ergänzen mit dem <code>geom_errorbar</code>. Hier kann nochmal mit der Option <code>width =</code> an der Länge der Fehlerenden gedreht werden.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">stat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">mean</span>, fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu">geom_bar</span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_errorbar</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">mean</span><span class="op">-</span><span class="va">sd</span>, ymax <span class="op">=</span> <span class="va">mean</span><span class="op">+</span><span class="va">sd</span><span class="op">)</span>,</span>
<span>                  width <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="eda-ggplot_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Im Zweifel muss du nochmal googlen und schauen welche Form dir am besten zusagt. Es gibt sehr viele Möglichkeiten einen Barplot zu erstellen.</p>
</section><section id="sec-eda-dotplot" class="level3" data-number="17.2.7"><h3 data-number="17.2.7" class="anchored" data-anchor-id="sec-eda-dotplot">
<span class="header-section-number">17.2.7</span> Dotplot</h3>
<p>Wenn wir weniger als fünf Beobachtungen haben, dann ist meist ein Boxplot verzerrend. Wir sehen eine Box und glauben, dass wir viele Datenpunkte vorliegen haben. Bei 3 bis 7 Beobachtungen je Gruppe bietet sich der Dotplot als eine Lösung an. Wir stellen hier alle Beobachtungen als einzelne Punkte dar. Wie erstellen wir nun einen Dotplot in R? Zuerst laden wir die Daten mit der Funktion <code>read_excel()</code> in R, wenn du die Daten als <code>.xlsx</code> Datei vorliegen hast.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flea_dog_cat_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/flea_dog_cat.xlsx"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">grade</span>,</span>
<span>                                    fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_dotplot</span><span class="op">(</span>binaxis <span class="op">=</span> <span class="st">"y"</span>, stackdir <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Tierart"</span>, y <span class="op">=</span> <span class="st">"Boniturnote [1-9]"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-dotplot-flea-eda-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dotplot-flea-eda-0-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.13— Der Dotplot für die Anzahl der Flöhe für die beiden Tierarten Hund und Katze.</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-dotplot-flea-eda-0">Abbildung&nbsp;<span>17.13</span></a> sehen wir den Dotplot aus der Datei <code>flea_dog_cat.xlsx</code>. Auf der x-Achse sind die Level des Faktors <code>animal</code> dargestellt und auf der y-Achse die Notenbewertung <code>grade</code> der einzelnen Hunde und Katzen. Die Funktion <code>geom_dotplot()</code> erschafft das Layer für die Dots bzw. Punkte. Wir müssen in der Funktion noch zwei Dinge angeben, damit der Plot so aussieht, dass wir den Dotplot gut interpretieren können. Zum einen müssen wir die Option <code>binaxis = y</code> wählen, damit die Punkte horizontal geordnet werden. Zum anderen wollen wir auch, dass die Punkte zentriert sind und nutzen dafür die Option <code>stackdir = center</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">grade</span>,</span>
<span>                            fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_dotplot</span><span class="op">(</span>binaxis <span class="op">=</span> <span class="st">"y"</span>, stackdir <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="va">median</span>, fun.min <span class="op">=</span> <span class="va">median</span>, fun.max <span class="op">=</span> <span class="va">median</span>,</span>
<span>               geom <span class="op">=</span> <span class="st">"crossbar"</span>, width <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Tierart"</span>, y <span class="op">=</span> <span class="st">"Boniturnote [1-9]"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-dotplot-flea-eda-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-dotplot-flea-eda-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.14— Der Dotplot für die Anzahl der Flöhe für die beiden Tierarten Hund und Katze. Die schwarze Linie stelt den Median für die beiden Tierarten dar.</figcaption></figure>
</div>
</div>
</div>
<p>Nun macht es wenig Sinn bei sehr wenigen Beobachtungen noch statistische Maßzahlen mit in den Plot zu zeichnen. Sonst hätten wir auch gleich einen Boxplot als Visualisierung der Daten wählen können. In <a href="#fig-dotplot-flea-eda-1">Abbildung&nbsp;<span>17.14</span></a> sehen wir die Ergänzung des Medians. Hier müssen wir etwas mehr angeben, aber immerhin haben wir so eine Idee, wo die “meisten” Beobachtungen wären. Aber auch hier ist Vorsicht geboten. Wir haben sehr wenige Beobachtungen, so dass eine Beobachtung mehr oder weniger große Auswirkungen auf den Median und die Interpretation hat.</p>
</section><section id="sec-eda-scatter" class="level3" data-number="17.2.8"><h3 data-number="17.2.8" class="anchored" data-anchor-id="sec-eda-scatter">
<span class="header-section-number">17.2.8</span> Scatterplot</h3>
<p>Der Scatterplot wird auch xy-Plot genannt. Wir stellen in einem Scatterplot zwei kontenuierliche Variablen dar. Dann wollen wir eine Linie durch die Punkte legen. Im Prinzip fragen wir uns, wie hänge die Werte auf der y-Achse von den Werten auf der x-Achse ab? Wenn sich also die Werte auf der x-Achse erhöhen, wie verhalten sich dann die Werte auf der y-Achse?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_count</span>, y <span class="op">=</span> <span class="va">jump_length</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Anzahl der Flöhe"</span>, y <span class="op">=</span> <span class="st">"Sprungweite in [cm]"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-scatter-flea-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-scatter-flea-0-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.15— Zusammenhang zwischen der Sprungweite in [cm] und der Anzahl an Flöhen auf den 39 Hunden. Jeder Punkt stellt einen Hund dar.</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-scatter-flea-0">Abbildung&nbsp;<span>17.15</span></a> zeigt den Scatterplot für die Spalte <code>flea_count</code> auf der x-Achse und <code>jump_length</code> auf der y-Achse. Mit der Funktion <code>geom_point()</code> können wir die Punktepaare für jede Beobachtung zeichnen. In unserem Fall zeichnen wir mit der Funktion <code>stat_smooth()</code> noch die entsprechende Grade durch die Punkte. Es handelt sich hierbei um eine Regression, da wir eine Gerade durch die Punktewolke zeichnen.</p>
</section><section id="sec-eda-mosaic" class="level3" data-number="17.2.9"><h3 data-number="17.2.9" class="anchored" data-anchor-id="sec-eda-mosaic">
<span class="header-section-number">17.2.9</span> Mosaic Plot</h3>
<p>Wenn wir zwei Spalten visualisieren wollen, die aus zwei Faktoren bestehen mit jeweils zwei Leveln, dann nutzen wir den Mosaic Plot. Wir nutzen den Datensatz <code>flea_dog_cat.xlsx</code> mit vierzehn Beobachtungen. Zuerst drehen wir nochmal die Ordnung der Level in dem Faktor <code>animal</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flea_dog_cat_mosaic_tbl</span> <span class="op">&lt;-</span> <span class="va">flea_dog_cat_tbl</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>animal <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">animal</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dog"</span>, <span class="st">"cat"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Schauen wir uns jetzt einmal die 2x2 Kreuztabelle der beiden Spalten <code>animal</code> and <code>infected</code> an. Um die 2x2 Tabelle in R in der richtigen Orientierung vorliegen zu haben, müssen wir nochmal einen kleinen Klimmzug über <code>mutate()</code> nehmen. Wir wandeln die Variable <code>infected</code> in einen Faktor um und sortieren die Level entsprechend, so dass wir die richtige Ordnung wie später im Mosaic Plot haben. Dieser Umweg hat nur didaktische Gründe, später plotten wir den Mosaic Plot direkt und schauen uns vorher nicht die 2x2 Tabelle in R an. Hier also die 2x2 Kreuztablle aus R.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flea_dog_cat_mosaic_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>infected <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">infected</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tabyl</span><span class="op">(</span><span class="va">infected</span>, <span class="va">animal</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> infected dog cat
        1   3   2
        0   4   5</code></pre>
</div>
</div>
<p>Wir sehen in der Tabelle, dass wir mehr nicht infizierte Tiere (n = 9) als infizierte Tiere haben (n = 5). Die Aufteilung zwischen den beiden Tierarten ist nahezu gleich. Im folgenden wollen wir diese Tabelle durch einen Mosaic Plot einmal visualisieren.</p>
<p>Um jetzt einen Mosaic Plot zeichnen zu können müssen wir die relativen Anteile pro Spalte bzw. für jedes Level von <span class="math inline">\(x\)</span> berechnen. In unserem Fall ist <span class="math inline">\(x\)</span> die Variable <code>animal</code> und die Level sind <code>dog</code> und <code>cat</code>. In der folgenden 2x2 Kreuztablle werden die relativen Anteile für die Hunde- und Katzenflöhe für den Infektionsstatus berechnet.</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Animal</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Dog</em></td>
<td style="text-align: center;"><em>Cat</em></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Infected</strong></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{3}{7} = 0.43\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{2}{7} = 0.29\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{5}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{4}{7} = 0.57\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{5}{7} = 0.71\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{9}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{7}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{7}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = 14\)</span></td>
</tr>
</tbody>
</table>
<p>Wir können jetzt die relativen Anteile in den Mosaic Plot übertragen und erhalten die <a href="#fig-mosaic-flea-0">Abbildung&nbsp;<span>17.16</span></a>. Wir müssen also zuerst die absoluten Anteile bestimmen um dann die relativen Anteile für die Spalten berechnen zu können. Abschließend zeichnen wir dann den Mosaic Plot. Wir nutzen dafür das R Paket <code>ggmosaic</code> mit der Funktion <code>geom_mosaic()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_mosaic_tbl</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_mosaic</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="fu">product</span><span class="op">(</span><span class="va">infected</span>, <span class="va">animal</span><span class="op">)</span>, fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">annotate</span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.75</span>, <span class="fl">0.75</span><span class="op">)</span>, </span>
<span>                   y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.25</span>, <span class="fl">0.75</span>, <span class="fl">0.25</span>, <span class="fl">0.85</span><span class="op">)</span>, </span>
<span>           label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"0.57"</span>, <span class="st">"0.43"</span>, <span class="st">"0.71"</span>, <span class="st">"0.29"</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mosaic-flea-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-mosaic-flea-0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.16— Visualisierung einer 2x2 Tabelle als Mosaic Plot. Die unterschiedlich großen Flächen geben die Verhältnisse per Spalte wieder.</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-mosaic-flea-0">Abbildung&nbsp;<span>17.16</span></a> zeigt den Mosaic Plot für die Variable <code>animal</code> and <code>infected</code>. Die untrschiedlich großen Flächen bilden die Verhältnisse der 2x2 Tabelle ab. So sehen wir, dass es mehr uninfizierte Tiere als infizierte Tiere gibt. Am meisten gibt es uninfizierte Katzen. Am wenigstens treten infizierte Katzen auf.</p>
</section></section><section id="überschriften-achsen-und-legenden" class="level2" data-number="17.3"><h2 data-number="17.3" class="anchored" data-anchor-id="überschriften-achsen-und-legenden">
<span class="header-section-number">17.3</span> Überschriften, Achsen und Legenden</h2>
<p>Wenn du mehr machen willst, also die Überschriften anpassen oder aber die Achsenbeschriftung ändern, dann gibt es hier global Hilfe im <a href="https://ggplot2.tidyverse.org/reference/index.html">ggplot Manual</a>. Die Webseite <a href="https://ggplot2.tidyverse.org/reference/index.html">R Cookbook</a> hat auch spezielle Hilfe für ggplot().</p>
<ul>
<li><a href="http://www.cookbook-r.com/Graphs/Titles_(ggplot2)/">Überschriften von Abbildungen</a></li>
<li><a href="http://www.cookbook-r.com/Graphs/Axes_(ggplot2)/">Achsenbeschriftung</a></li>
<li><a href="http://www.cookbook-r.com/Graphs/Legends_(ggplot2)/">Legende</a></li>
<li><a href="http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/">Farben</a></li>
</ul>
<p>In <a href="#fig-labels-0">Abbildung&nbsp;<span>17.17</span></a> siehst du eine Abbildung mit Titel und veränderten Beschriftungen. Die Möglichkeiten sind nahezu unbegrenzt und sprengen auch hier den Rahmen. Im Zweifel im R Tutorium vorbeischauen oder aber in der Vorlesung fragen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>                                    fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Frischgewicht in Abhängigkeit von der Behandlung"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Behandlung"</span>, y <span class="op">=</span> <span class="st">"Frischgewicht in kg/ha"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_discrete</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Katze"</span>, <span class="st">"Hund"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_discrete</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Behandlung"</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Katze"</span>, <span class="st">"Hund"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-labels-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-labels-0-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.17— Beispielhafte Abbildung mit Titel und geänderter Achsenbeschrittung</figcaption></figure>
</div>
</div>
</div>
</section><section id="mathematische-ausdrücke-in-den-achsenbeschriftungen" class="level2 page-columns page-full" data-number="17.4"><h2 data-number="17.4" class="anchored" data-anchor-id="mathematische-ausdrücke-in-den-achsenbeschriftungen">
<span class="header-section-number">17.4</span> Mathematische Ausdrücke in den Achsenbeschriftungen</h2>
<p>Häufig wollen wir nicht nur einfache Achsenbeschriftungen haben, sondern auch irgendwie komplexere Einheiten wie Eisendüngergehalt im Boden in <span class="math inline">\([kg\, ha]^{-1}\)</span> darstellen. Jetzt soll die Einheit auch in dieser Form mit in die Achsenbeschriftung. Wir können dafür zwei Wege wählen. Einmal über das R Paket <code>latex2exp</code> und die Funktion <code>TeX()</code> oder aber die Funktion <code><a href="https://rdrr.io/r/base/expression.html">expression()</a></code>, wofür wir dann kein eigenes R Paket brauchen. Beide Wege haben Vor- und Nachteile. Wir gehen aber beide mal durch.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Mehr Informationen durch das Tutorium <a href="https://cran.r-project.org/web/packages/latex2exp/vignettes/using-latex2exp.html">Using latex2exp</a> oder aber eben der Klassiker mit <a href="https://stat.ethz.ch/R-manual/R-patched/library/grDevices/html/plotmath.html">Plot math expression</a>.</p>
</div></div><p>Wir können die Funktion <code><a href="https://rdrr.io/r/base/expression.html">expression()</a></code> nutzen um uns mathematische Formeln zu bauen. Leider ist das Ganze etwas frickelig und auch ich brauche immer drei Anläufe, bis die Formel dann passt. Im Folgenden aber einmal zwei Beispiel für mathematische Formeln und Ausdrücke. Beachte, dass du jedes Leerzeichen durch eine Tilde <code>~</code> abbilden musst. Ich nutze die Funktion <code><a href="https://rdrr.io/r/base/expression.html">expression()</a></code> sehr selten und nur wenn die Formel wirklich sehr einfach ist. Da wir aber schon mit eckigen Klammern Probleme kriegen und diese so nervig mit <code>"</code> einklammern müssen, nutze ich dann das Paket <code>latex2exp</code> was ich im Folgenden vorstellen werde.</p>
<p>Hier aber erstmal zwei Beispiele für eine Formel mit der Funktion <code><a href="https://rdrr.io/r/base/expression.html">expression()</a></code>. Wenn du mehr über die Möglichkeiten wissen willst, dann schauen auch einmal auf die Hilfeseite von <a href="https://stat.ethz.ch/R-manual/R-patched/library/grDevices/html/plotmath.html">Plot math</a> oder du googelst dir die Lösung wie ich früher zusammen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">Eisendüngeform</span><span class="op">~</span><span class="va">und</span><span class="op">~</span><span class="op">-</span><span class="va">höhe</span><span class="op">~</span><span class="st">"[kg ha]"</span><span class="op">^</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span>, cex <span class="op">=</span> <span class="fl">1.5</span>, main <span class="op">=</span> <span class="st">""</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">Fe</span><span class="op">-</span><span class="va">Gehalt</span><span class="op">~</span><span class="st">"["</span><span class="op">~</span><span class="va">mg</span><span class="op">%.%</span><span class="op">(</span><span class="va">kg</span><span class="op">~</span><span class="va">TM</span><span class="op">)</span><span class="op">^</span><span class="op">-</span><span class="fl">1</span><span class="op">~</span><span class="st">"]"</span><span class="op">)</span>, cex <span class="op">=</span> <span class="fl">1.5</span>, main <span class="op">=</span> <span class="st">""</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Für mich ausdrücklich einfacher geht es mit dem R Paket <code>latex2exp</code> und der Funktion <code>TeX()</code> sowie die Helferfunktion <code>r"()"</code>. Ja, hier muss man dann noch eine andere Programmiersprache kennen, aber wie immer, du wirst nur schlauer. Die Informationen zur Matheumgebung in <span class="math inline">\(\LaTeX\)</span> kommen dann nochmal extra zwischen zwei Dollarzeichen <code>$</code>. Ja, das ist etwas wirr für einen Anfänger, aber wir nutzen hier auch zwei Programmiersprachen zusammen. Zum einen <span class="math inline">\(\LaTeX\)</span> um die Mathesymbole sauber darzustellen und dann R um die Abbildungen in <code>ggplot()</code> zu bauen. Mehr Informationen zu der Matheumgebung in <span class="math inline">\(\LaTeX\)</span> findest du einmal in der <a href="https://de.wikipedia.org/wiki/Hilfe:TeX">LaTeX Mathehilfe I</a> sowie der <a href="https://en.wikibooks.org/wiki/LaTeX/Mathematics">LaTeX Mathehilfe II</a>.</p>
<p>Wie bauen wir uns also unseren mathematischen Ausdruck? Als erstes brauchen wir die Funktion <code>Tex()</code>, die sagt einfach nur aus, dass jetzt <span class="math inline">\(\LaTeX\)</span>-Code kommt. Dann wollen wir noch einen String brauen in dem der <span class="math inline">\(\LaTeX\)</span>-Code für unseren mathematischen Ausdruck drin steht. Diesen String bauen wir mit <code>r"()"</code>. Achtung, hier ist das Gänsefüßchen oben und unten vor und nach der runden Klammer sehr wichtig. In den Ausdruck können wir dann Text schreiben <code>Eisengehalt</code> oder aber einen mathematischen Ausdruck abgrenzt von zwei Dollarzeichen <code>$</code> wie <code>$[kg\, ha]^{-1}$</code>. <span class="math inline">\(\LaTeX\)</span> kann nämlich nicht nur mathematische Ausdrücke sondern ist eigentlich ein Textverarbeitungsprogramm. Deshalb musst du hier <em>nochmal</em> zwischen Text und mathematischen Ausdruck unterscheiden.</p>
<p>Hier nochmal aufgeschlüsselt wie der Code aussieht. Wir schreiben den Code nachher in einer Zeile, aber zum Verständnis ist es besser, wenn wir den Code einmal aufgeklappt sehen.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">TeX</span><span class="op">(</span></span>
<span>    <span class="st">r"(</span></span>
<span><span class="st">      Eisengehalt $[kg\, ha]^{-1}$</span></span>
<span><span class="st">    )"</span></span>
<span>   <span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir wollen uns das Ergebnis einmal in einem simplen <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> anschauen. Wir nutzen die Funktionalität natürlich später in <code>ggplot</code>, aber hier ist es so einmal einfacher zu sehen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>cex <span class="op">=</span> <span class="fl">2</span>, main <span class="op">=</span> <span class="st">""</span>,</span>
<span>  <span class="fu">TeX</span><span class="op">(</span><span class="st">r"(</span></span>
<span><span class="st">         Eisengehalt $[kg\, ha]^{-1}$</span></span>
<span><span class="st">      )"</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Auch können wir sehr viel komplexere Formeln erstellen. Beachte auch hier, dass wir zwei Matheumgebungen in <span class="math inline">\(\LaTeX\)</span> vorliegen haben.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>cex <span class="op">=</span> <span class="fl">2</span>, main <span class="op">=</span> <span class="st">""</span>,</span>
<span>  <span class="fu">TeX</span><span class="op">(</span><span class="st">r"(</span></span>
<span><span class="st">         A $\LaTeX$ formula: $\frac{2hc^2}{\lambda^5}\frac{1}{e^{\frac{hc}{\lambda k_B T}} - 1}$</span></span>
<span><span class="st">      )"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>In der <a href="#fig-scatter-flea-1">Abbildung&nbsp;<span>17.18</span></a> dann nochmal die Anwendung in einem <code>ggplot</code> in dem wir die Achsen entsprechend beschriften und dann auch noch eine ausgedachte Regressionsgeleichung zu der Abbildung ergänzen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_count</span>, y <span class="op">=</span> <span class="va">jump_length</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="fu">TeX</span><span class="op">(</span><span class="st">r"(Eisengehalt und -höhe $[kg\, ha]^{-1}$)"</span><span class="op">)</span>, </span>
<span>       y <span class="op">=</span> <span class="fu">TeX</span><span class="op">(</span><span class="st">r"(Fe-Gehalt $[mg \cdot (kg TM)^{-1}]$)"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">annotate</span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">10</span>, y <span class="op">=</span> <span class="fl">10</span>,</span>
<span>           label <span class="op">=</span> <span class="fu">TeX</span><span class="op">(</span><span class="st">r"($y = \beta_0 + \beta_1 \cdot x;\; R^2 = 0.24$)"</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-scatter-flea-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-scatter-flea-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.18— Zusammenhang zwischen dem Eisengehalt und -höhe im Boden und dem Eisengehalt in Salat. Zusätzlich ergänzt eine Regressiongleichung und ein ausgedachtes Bestimmtheitsmaß.</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Workaround für <code>Tex()</code> in <code>geom_text()</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Wenn du dann mal die Funktion <code>Tex()</code> in <code>geom_text()</code> verwenden willst, dann musst du einmal etwas anpassen. Dann klappt es aber auch hier. Das hat mich mal echt Nerven und Zeit gekostet, deshalb lagere ich die Information mal hier für mich.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_void</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_text</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span>, </span>
<span>                label <span class="op">=</span> <span class="fu">TeX</span><span class="op">(</span><span class="st">r'($\alpha  x^\alpha$, where $\alpha \in 1\ldots 5$)'</span>,</span>
<span>                                  output <span class="op">=</span> <span class="st">"character"</span>,<span class="op">)</span><span class="op">)</span>, parse <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="192"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="die-okabe-ito-farbpalette" class="level2 page-columns page-full" data-number="17.5"><h2 data-number="17.5" class="anchored" data-anchor-id="die-okabe-ito-farbpalette">
<span class="header-section-number">17.5</span> Die Okabe-Ito Farbpalette</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p>Mehr zum R Paket <code>see</code> auf der <a href="https://easystats.github.io/see/index.html">Hilfeseite des Paketes</a></p>
</div></div><p>Neben den klassischen Farben im R Paket <code>ggplot</code>gibt es noch weit, weit mehr Farbpaletten. Wir nutzen in der Folge immer wieder die Okabe-Ito Farbpalette aus dem R Paket <code>see</code>. Die Okabe-Ito Farbpalette ist speziell so gebaut, dass die Farben sich gut für farbenblinde Personen unterscheiden. Der Kontrast zwischen den Farben ist sehr gut. Wenn du eine andere Farbpalette nutzen willst, findest du hier noch andere <a href="https://easystats.github.io/see/articles/seecolorscales.html">Color Scales</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>           fill <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-labels-see-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-labels-see-0-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.19— Beispielhafte Abbildung der Okabe-Ito Farbpalette für Boxplots.</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>           color <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-labels-see-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-labels-see-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.20— Beispielhafte Abbildung der Okabe-Ito Farbpalette für Punkte.</figcaption></figure>
</div>
</div>
</div>
</section><section id="abbildungen-nebeneinander" class="level2" data-number="17.6"><h2 data-number="17.6" class="anchored" data-anchor-id="abbildungen-nebeneinander">
<span class="header-section-number">17.6</span> Abbildungen nebeneinander</h2>
<p>Das <a href="https://patchwork.data-imaginist.com/articles/patchwork.html">R Paket patchwork</a> erlaubt es mehrere <code>ggplot</code> Abbildungen nebeneinander oder in einem beliebigen Layout miteinander zu verbinden. Das tolle ist, dass die Idee sehr intutiv ist. Wir nutzen wieder das <code>+</code> um verschiedene Plots miteinander zu verbinden.</p>
<p>Im Folgenden erschaffen wir uns zwei <code>ggplots</code> und speichern die Plots in den Objekten <code>p1</code> und <code>p2</code>. Das ist wie wir es bisher kennen, nur das jetzt keine Abbildung erscheint sondern beide Plots in zwei Objekten gespeichert sind.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, </span>
<span>             <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flea_count</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>                 color <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">flea_dog_cat_tbl</span>, </span>
<span>                <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>                    color <span class="op">=</span> <span class="va">animal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wie können wir nun die beiden Abbildungen nebeneinander zeichnen? Wir nutzen einfach das <code>+</code> Symbol.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-labels-patchwork-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-ggplot_files/figure-html/fig-labels-patchwork-1-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.21— Beispielhafte Abbildung der zweier Plots nebeneinander.</figcaption></figure>
</div>
</div>
</div>
<p>Auf der Seite des <a href="https://patchwork.data-imaginist.com/articles/patchwork.html">R Paket patchwork</a> findest du viel mehr Möglichkeiten das Layout anzupassen und auch die einzelnen <a href="https://patchwork.data-imaginist.com/articles/guides/annotation.html">Subplots zu beschriften</a>.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./eda-descriptive.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./eda-transform.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>