<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 18&nbsp; Verteilung von Daten</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-tests-preface.html" rel="next">
<link href="./eda-transform.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Mit <code>purrr</code> und <code>furrr</code></span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Friedman Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Metanalysen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Permutationstest</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">Klassifikation oder maschinelles Lernen</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Data splitting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Data preprocessing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Decision trees</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Support vector machines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Neural networks</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-bewertungsbogen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Bewertungsbogen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Modulbeschreibung</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link active" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"> <span class="header-section-number">18.1</span> Genutzte R Pakete für das Kapitel</a></li>
  <li><a href="#daten-f%C3%BCr-verteilungen" id="toc-daten-für-verteilungen" class="nav-link" data-scroll-target="#daten-f%C3%BCr-verteilungen"> <span class="header-section-number">18.2</span> Daten für Verteilungen</a></li>
  <li><a href="#sec-normal" id="toc-sec-normal" class="nav-link" data-scroll-target="#sec-normal"> <span class="header-section-number">18.3</span> Die Normalverteilung</a></li>
  <li><a href="#die-standardnormalverteilung" id="toc-die-standardnormalverteilung" class="nav-link" data-scroll-target="#die-standardnormalverteilung"> <span class="header-section-number">18.4</span> Die Standardnormalverteilung</a></li>
  <li><a href="#sec-t-dist" id="toc-sec-t-dist" class="nav-link" data-scroll-target="#sec-t-dist"> <span class="header-section-number">18.5</span> Die t-Verteilung</a></li>
  <li><a href="#sec-poisson" id="toc-sec-poisson" class="nav-link" data-scroll-target="#sec-poisson"> <span class="header-section-number">18.6</span> Die Poissonverteilung</a></li>
  <li><a href="#sec-binom" id="toc-sec-binom" class="nav-link" data-scroll-target="#sec-binom"> <span class="header-section-number">18.7</span> Die Binominalverteilung</a></li>
  <li><a href="#sec-uniform" id="toc-sec-uniform" class="nav-link" data-scroll-target="#sec-uniform"> <span class="header-section-number">18.8</span> Die Uniformverteilung</a></li>
  <li><a href="#weitere-verteilungen" id="toc-weitere-verteilungen" class="nav-link" data-scroll-target="#weitere-verteilungen"> <span class="header-section-number">18.9</span> Weitere Verteilungen</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block">
<span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span>
</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><p><em>Version vom März 07, 2023 um 09:45:41</em></p>
<div class="cell">

</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir besuchen gerne die R Shiny App <a href="https://ben18785.shinyapps.io/distribution-zoo/">The distribution zoo</a> um mehr über die verschiedenen Verteilungen und deren Parameter zu erfahren.</p>
</div></div><p>In diesem Kapitel wollen wir uns mit Verteilungen beschäftigen. <span class="citation" data-cites="dormann2013parametrische">Dormann (<a href="#ref-dormann2013parametrische" role="doc-biblioref">2013</a>)</span> liefert eine weitreichende Übersicht über verschiedene Verteilungen. Natürlich ist diese Übersicht auch nicht abschließend. Es gibt eine sehr große Anzahl an Verteilungen, aber wir werden uns nur mit einer kleinen Auswahl beschäftigen. Die folgenden Verteilungen haben eine praktische Verwendung in der Data Science. Wir wollen uns in diesem Kapitel mit folgenden Verteilungen beginnen.</p>
<ul>
<li>der <em>Normalverteilung</em>, die Glockenkurve oder auch <em>Gaussian</em> im englischen Sprachgebrauch genannt, die kontinuierliche Zahlen repräsentiert.</li>
<li>die <em>Standardnormalverteilung</em>, als eine spezielle Form der Normalverteilung mit einer Fläche von Eins unter der Kurve.</li>
<li>die <em>t-Verteilung</em>, eine abgeleitete Verteilung von der Standardnormalverteilung, die ähnliche Eigenschaften wie die Standardnormalverteilung hat.</li>
<li>der <em>Poissonverteilung</em>, die diskrete Zähldaten repräsentiert.</li>
<li>die <em>Binomialverteilung</em>, die <span class="math inline">\(0/1\)</span> Zahlen und damit das Eintreten eines Ereignisses repräsentiert. Bekannt aus den Würfel und Münzwurfbeispielen.</li>
<li>die <em>Uniformverteilung</em>, eine Sockelverteilung, die über einen Zahlenrum nur einen Wert annimmt.</li>
</ul>
<p>Wir wollen uns jetzt die verschiedenen Verteilungen einmal in der Anwendung anschauen. Dabei lassen wir viel Mathematik recht und links liegen. Du kannst bei <span class="citation" data-cites="dormann2013parametrische">Dormann (<a href="#ref-dormann2013parametrische" role="doc-biblioref">2013</a>)</span> mehr zu dem Thema statistische Verteilungen anlesen. Dort gibt es auch nochmal mehr Informationen zu den einzelnen Eigenschaften, die eine Verteilung noch so haben kann. Wir konzentrieren uns hier auf die Lageparameter und die Streuung der Verteilungen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Wir halten den mathematischen Teil zu den Verteilungen sehr kurz oder überspringen den Teil ganz. Wir brauchen die Idee der Verteilungen, weil wir später den Methoden sagen müssen wie unser Outcome <span class="math inline">\(y\)</span> verteilt ist. Nur dann können wir die Daten richtig auswerten.</p>
</div></div><p>In diesem Kapitel geht es erstmal um das Grundverständnis, das Daten einer Verteilung folgen. Oder noch konkreter, dass unser Outcome <span class="math inline">\(y\)</span> einer Verteilung folgt. Wir müssen später unseren Alogrithmen sagen, welcher Verteilung <span class="math inline">\(y\)</span> entspringt, sonst können wir keine <em>korrekte</em> Analyse unser Daten rechnen.</p>
<section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="18.1"><h2 data-number="18.1" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">18.1</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">see</span>, <span class="va">readxl</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten-für-verteilungen" class="level2" data-number="18.2"><h2 data-number="18.2" class="anchored" data-anchor-id="daten-für-verteilungen">
<span class="header-section-number">18.2</span> Daten für Verteilungen</h2>
<p>Damit wir uns auch eine Verteilung anschauen können bruachen wir <em>viele</em> Beobachtungen. Wir haben das ja schon bei den Histogrammen gesehen, wenn wir ein aussagekräftiges Histogramm erstellen wollen, dann brauchen wir mehr als zwanzig Beobachtungen. Daher nehmen wir für dieses Kapitel einmal den Gummibärchendatensatz und schauen uns dort die Variablen <code>gender</code>, <code>height</code>, <code>count_bears</code> und <code>count_color</code> einmal genauer an. Wie immer nutzen wir die Funktion <code>select()</code> um die Spalten zu selektieren. Abschließend verwandeln wir das Geschlecht <code>gender</code> und das <code>module</code> noch in einen Faktor.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">gummi_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/gummibears.xlsx"</span><span class="op">)</span>  <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">year</span>, <span class="va">module</span>, <span class="va">gender</span>, <span class="va">height</span>, <span class="va">count_bears</span>, <span class="va">count_color</span>,
         <span class="va">most_liked</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>gender <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">gender</span><span class="op">)</span>,
         module <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">module</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir erhalten das Objekt <code>gummi_tbl</code> mit dem Datensatz in <a href="#tbl-data-dist-gummi">Tabelle&nbsp;<span>18.1</span></a> nochmal dargestellt. Wir brauchen nicht alle Spalten aus dem ursprünglichen Datensatz und somit ist die Tabelle etwas übersichtlicher.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-dist-gummi" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 18.1— Auszug aus den selektierten Daten zu den Gummibärchendaten.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">year</th>
<th style="text-align: center;">module</th>
<th style="text-align: center;">gender</th>
<th style="text-align: center;">height</th>
<th style="text-align: center;">count_bears</th>
<th style="text-align: center;">count_color</th>
<th style="text-align: center;">most_liked</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">FU Berlin</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">193</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">lightred</td>
</tr>
<tr class="even">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">FU Berlin</td>
<td style="text-align: center;">w</td>
<td style="text-align: center;">159</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">yellow</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">FU Berlin</td>
<td style="text-align: center;">w</td>
<td style="text-align: center;">159</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">white</td>
</tr>
<tr class="even">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">FU Berlin</td>
<td style="text-align: center;">w</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">white</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">FU Berlin</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">white</td>
</tr>
<tr class="even">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">FU Berlin</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">white</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">Biostatistik</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">175</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">lightred</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">Biostatistik</td>
<td style="text-align: center;">w</td>
<td style="text-align: center;">162</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">white</td>
</tr>
<tr class="even">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">Biostatistik</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">darkred</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">Biostatistik</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">187</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">darkred</td>
</tr>
<tr class="even">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">Biostatistik</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">194</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">orange</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">Biostatistik</td>
<td style="text-align: center;">m</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">darkred</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section><section id="sec-normal" class="level2 page-columns page-full" data-number="18.3"><h2 data-number="18.3" class="anchored" data-anchor-id="sec-normal">
<span class="header-section-number">18.3</span> Die Normalverteilung</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Wir sprechen in der Statistik auch von Verteilungs<em>familien</em>. Daher schreiben wir in R auch <code>family = gaussian</code>, wenn wir sagen wollen, dass unsere Daten einer Normalverteilung entstammen.</span></div></div>
<p>Wenn wir von de Normalverteilung sprechen, dann schreiben wir ein <span class="math inline">\(\mathcal{N}\)</span> Symbol - also ein großes N mit Serifen. Die Normalverteilung sieht aus wie eine Glocke, deshalb wird die Normalverteilung auch Glockenkurve genannt. Im englischen Sprachgebrauch und auch in R nutzen wir dagegen die Bezeichnung nach dem “Entdecker” der Normalverteilung, Carl Friedrich Gauß (1777 - 1985). Wir nennen daher die Normalverteilung auch Gaussian-Verteilung.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside"><em>Parameter</em> sind Zahlen, die eine Verteilungskurve beschreiben.</span></div></div>
<p>Eine Normalverteilung wird ruch zwei Verteilungs<em>parameter</em> definiert. Eine Verteilung hat Parameter. Parameter sind die Eigenschaften einer Verteilung, die notwendig sind um eine Verteilung vollständig zu beschreiben. Im Falle der Normalverteilung brauchen wir zum einen den Mittelwert <span class="math inline">\(\bar{y}\)</span>, der den höchsten Punkt unserer Glockenkurve beschreibt. Zum anderen brauchen wir auch die Standardabweichung <span class="math inline">\(s^2_y\)</span>, die die Ausbreitung oder Breite der Glockenkurve bestimmt. Wir beschreiben eine Normalverteilung für eine Stichprobe mit <span class="math inline">\(\bar{y}\)</span> und <span class="math inline">\(s^2_y\)</span> wie folgt.</p>
<p><span class="math display">\[
\mathcal{N}(\bar{y}, s^2_y)
\]</span></p>
<p>Oder mit mehr Details in folgender Form. Wir können hier Verallgemeinern und schreiben in der Grundgesamtheit mit <span class="math inline">\(\mu = \bar{y}\)</span> und <span class="math inline">\(\sigma^2 = s^2_y\)</span>. Das heißt, wenn wir unendlich viele Beobachtungen vorliegen hätten, dann wüssetn wir auch den wahren Mittelwert <span class="math inline">\(\mu\)</span> und die wahre Varianz <span class="math inline">\(\sigma^2\)</span> der Daten.</p>
<p><span class="math display">\[
f(y \mid\mu,\sigma^2)=\cfrac{1}{\sqrt{2\pi\sigma^2}} e^{-\cfrac{(y-\mu)^2}{2\sigma^2}}\quad -\infty&lt;y&lt;\infty
\]</span></p>
<p>Im Falle der Normalverteilung brauchen wir einen Paramter für den höchsten Punkt der Kurve, sowie einen Parameter für die Ausbreitung, also wie weit geht die Kurve nach links und nach rechts. Je nach <span class="math inline">\(\bar{y}\)</span> und <span class="math inline">\(s^2_y\)</span> können wir verschiedenste Normalverteilungen vorliegen haben. Eine Sammlung von Verteilungen nennen wir auch Familie (eng. <em>family</em>).</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Wir haben Varianzhomogenität vorliegen, wenn <span class="math inline">\(s^2_{1} = s^2_{2} = s^2_{3}\)</span> sind. Wir haben Varianzheterogenität vorliegen, wenn <span class="math inline">\(s^2_{1} \neq s^2_{2} \neq s^2_{3}\)</span> sind.</span></div></div>
<p>In <a href="#fig-normal-02">Abbildung&nbsp;<span>18.1</span></a> sehen wir verschiedene Normalverteilungen mit unterschiedlichen Mittelwerten. In <a href="#fig-normal-02-1">Abbildung&nbsp;<span>18.1 (a)</span></a> sehen wir eine Varianzhomogenität vorliegen, da die Varianzen in allen drei Normalverteilungen gleich sind. Wir können auch schreiben, dass <span class="math inline">\(s^2_{1} = s^2_{2} = s^2_{3} = 2\)</span>. In <a href="#fig-normal-02-2">Abbildung&nbsp;<span>18.1 (b)</span></a> haben wir Varianzheterogenität vorliegen, da die Varianzen der Normalverteilungen ungleich sind. Wir können hier dann schreiben, dass <span class="math inline">\(s^2_{1} = 6 \neq s^2_{2} = 1 \neq s^2_{3} = 3\)</span> sind. Häufig gehen statistische Verfahren davon aus, dass wir Varianzhomogenität über die Gruppen und daher auch die Normalverteilungen vorliegen haben. Konkret, wenn wir die Sprungweiten in[cm] von Hunde- und Katzenflöhen mit einander vergleichen wollen, dann gehen wir erstmal davon aus, dass die Mittelwerte verschieden sind, aber die Varianzen gleich sind.</p>
<div id="fig-normal-02" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-02-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-02-1.png" class="img-fluid figure-img" data-ref-parent="fig-normal-02" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Drei Normalverteilungen mit Varianzhomogenität.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-02-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-02-2.png" class="img-fluid figure-img" data-ref-parent="fig-normal-02" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Drei Normalverteilungen unter Varianzheterogenität.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.1— Histogramm verschiedener Normalverteilungen mit unterschiedlichen Mittelwerten.</figcaption><p></p>
</figure>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">In einer Normalverteilung liegen 68% der Werte innerhalb <span class="math inline">\(\bar{y}\pm 1 \cdot s_y\)</span> und 95% der Werte innerhalb <span class="math inline">\(\bar{y}\pm 2 \cdot s_y\)</span></span></div></div>
<p>Wenn wir eine Normalverteilung vorliegen haben, dann liegen 68% der Werte plus/minus einer Standardabweichung vom Mittelwert. Ebenso liegen 95% der Werte plus/minus zwei Standabweichungen vom Mittelwert. Über 99% der Werte befinden sich innerhalb von drei Standardabweichungen vom Mittelwert. Diese Eigenschaft einer Normalverteilung können wir später noch nutzen um abzuschätzen, ob wir einen relevanten Gruppenunterschied vorliegen haben oder aber ob unsere Daten <em>unnatürlich</em> breit streuen.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Wir nutzen das Wort <em>approximativ</em> wenn wir sagen wollen, dass ein Outcome näherungsweise normalverteilt ist.</span></div></div>
<p>Schauen wir uns die Normalverteilung einmal am Beispiel unserer Gummibärchendaten und der Körpergröße der Studierenden an. Wir färben das Histogramm nach dem Geschlecht ein. In <a href="#fig-normal-01">Abbildung&nbsp;<span>18.2</span></a> sehen wir das Ergebnis einmal als Histogramm und einmal als Densityplot dargestellt. Wir können annehmen, dass die Größe <em>approximativ</em> normalverteilt ist.</p>
<div id="fig-normal-01" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-01-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-01-1.png" class="img-fluid figure-img" data-ref-parent="fig-normal-01" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Histogramm.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-01-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-01-2.png" class="img-fluid figure-img" data-ref-parent="fig-normal-01" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Densityplot.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.2— Darstellung der Körpergröße in [cm] für die Geschlechter getrennt.</figcaption><p></p>
</figure>
</div>
<p>Wir können die Funktion <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> nutzen um uns zufällige Zahlen aus der Normalverteilung ziehen zu lassen. Dazu müssen wir mit <code>n =</code> spezifizieren wie viele Beobachtungen wir wollen und den Mittelwert <code>mean =</code> und die gewünschte Standardabweichung mit <code>sd =</code> angeben. Im Folgenden einmal ein Beispiel für die Nutzung der Funktion <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> mit zehn Werten.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span>, mean <span class="op">=</span> <span class="fl">5</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 6.97 6.24 5.59 5.27 6.30 4.91 4.13 4.92 3.67 4.42</code></pre>
</div>
</div>
<p>Du kannst ja mal den Mittelwert und die Standardabweichung der zehn Zahlen ausrechnen. Da wir es hier mit einer Stichprobe mit zehn Beobachtungen zu tun haben, wird der Mittelwert <span class="math inline">\(\bar{y}\)</span> und die Standardabweichung <span class="math inline">\(s_y\)</span> sich von den vorher definierten Mittelwert <span class="math inline">\(\mu_y = 5\)</span> und Standardabweichung <span class="math inline">\(\sigma_y = 2\)</span> der Grundgesamtheit unterscheiden.</p>
<p>Wir können auch aus unseren Gummibärchendaten für die Körpergröße in [cm] jeweils den Mittelwert und die Standardabweichung getrennt für die Geschlechter berechnen und dann die theoretische Normalverteilung zeichenen. In <a href="#fig-normal-03-2">Abbildung&nbsp;<span>18.3 (b)</span></a> und <a href="#fig-normal-03-4">Abbildung&nbsp;<span>18.3 (d)</span></a> sehen wir die Verteilung der theoretischen Werte, wenn wir die Mittelwerte und die Standardabweichung aus den Verteilungen in <a href="#fig-normal-03-1">Abbildung&nbsp;<span>18.3 (a)</span></a> schätzen. Spannderweise bildet sich den <em>zufällig</em> gezogenen Daten auch eine leichte Schulter bei der Verteilung der Körpergrößen. Auch <span class="math inline">\(n = 503\)</span> vollständige Beobachtungen bedeuten nicht, dass wir eine perfekte Normalverteilung erhalten.</p>
<div id="fig-normal-03" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-03-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-03-1.png" class="img-fluid figure-img" data-ref-parent="fig-normal-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Verteilung der beobachteten Werte.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-03-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-03-2.png" class="img-fluid figure-img" data-ref-parent="fig-normal-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Verteilung der theoretischen Werte.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-03-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-03-3.png" class="img-fluid figure-img" data-ref-parent="fig-normal-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(c) Verteilung der beobachteten Werte.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-normal-03-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-normal-03-4.png" class="img-fluid figure-img" data-ref-parent="fig-normal-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(d) Verteilung der theoretischen Werte.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.3— Darstellung der Körpergröße in [cm] für die Geschlechter getrennt. Auf der linken Seite die beobachteten Werte und auf der rechten Seite die theoretischen Werte. Einmal dargestellt als Histogramm und einmal als Densityplot.</figcaption><p></p>
</figure>
</div>
</section><section id="die-standardnormalverteilung" class="level2" data-number="18.4"><h2 data-number="18.4" class="anchored" data-anchor-id="die-standardnormalverteilung">
<span class="header-section-number">18.4</span> Die Standardnormalverteilung</h2>
<p>Es gibt viele Normalverteilungen. Eiegntlich gibt es unednlich viele Normalverteilunge, da wir für die Parameter Mittelwert <span class="math inline">\(\bar{y}\)</span> und die Standardabweichung <span class="math inline">\(s_y\)</span> beliebige Zahlen einsetzen können. Aber es gibt eine besondere Normalverteilung, so dass diese Verteilung einen eigenen Namen hat. Wir sprechen von der Standardnormalverteilung, wenn der Mittelwert gleich Null ist und die Standardabweichung gleich Eins. Du siehst hier nochmal die Standardnormalverteilung ausgeschrieben.</p>
<p><span class="math display">\[
\mathcal{N}(0, 1)
\]</span></p>
<p>Folgende Eigenschaften sind der Standardnormalverteilung gegeben. Die Standardnormalverteilung hat eine Fläche von <span class="math inline">\(A = 1\)</span> unter der Kurve. Darüber hinaus liegen 95% der Werte zwischen <span class="math inline">\(\approx -2\)</span> und <span class="math inline">\(\approx 2\)</span>. Die einzelnen Werte einer Standardnormalverteilung nennen wir <span class="math inline">\(z\)</span>-Werte. Wenn wir eine beliebige Normalverteilung in eine Standardnormalverteilung überführen wollen so machen wir die Umwandlung mit der <span class="math inline">\(z\)</span>-Transformation. Und jetzt fahren wir wieder in die Doppeldeutigkeit in R.</p>
<div id="fig-dist-t-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/distribution-t.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.4— Darstellung von dem Zusammenhang von <code>pnorm(p = 1.96)</code> und <code>qnorm(q = 0.025)</code>. Mit der Option <code>lower.tail</code> bestimmen wir auf welche Seite der Verteilung wir sein wollen.</figcaption><p></p>
</figure>
</div>
<p>In <a href="#fig-dist-t-01">Abbildung&nbsp;<span>18.4</span></a> haben wir eine Standardnormalverteilung gegeben. Können jetzt verschiedene Werte auf der <span class="math inline">\(x\)</span>-Achse und die Flächen links und rechts von diesen Werten berechnen. Wir nutzen die Funktion <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> wenn wir die Fläche rechts oder links von einem Wert <span class="math inline">\(q\)</span> berechnen wollen.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fl">1.96</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.025</code></pre>
</div>
</div>
<p>Wir berechen die Fläche links von <span class="math inline">\(q\)</span> und damit auch die Wahrscheinlichkeit <span class="math inline">\(Pr(X \leq q)\)</span> mit <code>lower.tail = TRUE</code>. Warum ist die Fläche jetzt eine Wahrscheinlichkeit? Wir haben unter der Kurve der Standardnormalverteilung eine Fläche von <span class="math inline">\(A = 1\)</span>. Damit ist jede Fläche auch gleich einer Wahrscheinlichkeit. Wenn wir an der Fläche rechts von <span class="math inline">\(q\)</span> interessiert sind und damit auch an der Wahrscheinlichkeit <span class="math inline">\(Pr(X &gt; q)\)</span> nutzen wir die Option <code>lower.tail = FALSE</code>. Das ist erstmal immer etwas verwirrend, aber schau dir den Zusammenhang nochmal in der <a href="#fig-dist-t-01">Abbildung&nbsp;<span>18.4</span></a> an. Wir brauchen diese Idee von der <em>Fläche ist auch gleich Wahrscheinlichkeit</em> im <a href="stat-tests-theorie.html"><span>Kapitel&nbsp;20</span></a> zum statistischen Testen.</p>
<p>Wir können die Berechnung von <span class="math inline">\(q\)</span> zu <span class="math inline">\(p\)</span> auch umdrehen. Wir geben eine Fläche vor und wollen wissen wie der Wert auf der x-Achse zu der entsprechenden Fläche ist. In diesem Fall will ich die Werte zu den Flächen von <span class="math inline">\(p = 0.025\)</span> und <span class="math inline">\(p = 0.05\)</span>. Da wir <code>lower.tail = FALSE</code> ausgewählt haben, sind wir auf der rechten Seite der Verteilung.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.05</span><span class="op">)</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.960 1.645</code></pre>
</div>
</div>
<p>Und hier einmal als Gegenprobe mit der Option <code>lower.tail = TRUE</code>. Wir springen dann damit auf die linke Seite der Verteilung und wie zu erwarten erhlaten wir dann auch den negativen Wert für die Fläche von <span class="math inline">\(p = 0.05\)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">0.05</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.645</code></pre>
</div>
</div>
<p>Die ganzen Berechnungen funktionieren natürlich auch, wenn wir nicht die Fläche <span class="math inline">\(A=1\)</span> unterhalb der Standardnormalverteilung hätten. Aber wir nutzen hier eben den Zusammenhang von Fläche zu Wahrscheinlichkeit um mit der Verteilung zu rechnen und Wahrscheinlichkeiten abzuschätzen.</p>
</section><section id="sec-t-dist" class="level2" data-number="18.5"><h2 data-number="18.5" class="anchored" data-anchor-id="sec-t-dist">
<span class="header-section-number">18.5</span> Die t-Verteilung</h2>
<p>Die t-Verteilung ist eine Abwandlung der Standardnormalverteilung. Wir haben wieder eine Fläche <span class="math inline">\(A = 1\)</span> unter der Verteilungskurve. Wir benötigen die t-Verteilung, als eine künstliche Verteilung, im <a href="stat-tests-ttest.html"><span>Kapitel&nbsp;22</span></a> zum statistischen Testen mit dem t-Test. Wir bezeichnen die t-Verteilung als eine künstliche Verteilung, da wir in der Biologie nichts beobachten können, was t-verteilt ist. Wir nutzen die t-Verteilung nur im statistischen Kontext und in diesem Kontekt nur um uns klar zu machen wie statistisches Testen konzeptionell funktioniert. Anwenden werden wir die Verteilung nicht.</p>
<p>Der Unterschied ist die Form der t-Verteilung. Wir geben mit der Option <code>df =</code> die Freiheitsgrade der Verteilung an. Hier soll es reichen, dass mit <span class="math inline">\(\lim_{df \to \infty}\)</span> sich die t-Verteilung der Standardnormalverteilung fast gleicht. Bei niedrigeren Freiheitsgraden ist die t-Verteilung nicht mehr so hoch und daher sind die Verteilungsenden weiter nach außen geschoben. Die t-Verteilung ist gestaucht wie wir in <a href="#fig-tdist-01">Abbildung&nbsp;<span>18.5</span></a> etwas überspitzt gezeichnet sehen. Die Freiheitsgrade hängen direkt an der beobachteten Fallzahl mit <span class="math inline">\(df = n_1 + n_2 - 2\)</span>.</p>
<div id="fig-tdist-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/t-verteilung_06.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.5— Die t-Verteilung für drei beispielhafte Freiheitsgrade. Je größer die Freiheitsgrade und damit die Fallzahl, desto näher kommt die t-Verteilung einer Normalverteilung nahe.</figcaption><p></p>
</figure>
</div>
<p>Wie auch bei der Standardnormalverteilung gilt folgender Zusammenhang, wenn wir die Flächen anhand eines gegebenen t-Wertes berechnen wollen. Wenn wir die Fläche links von dem t-Wert berechnen wollen, also die Wahrscheinlichkeit <span class="math inline">\(Pr(X \leq t)\)</span>, dann nutzen wir die Option <code>lower.tail = TRUE</code>. Wenn wir die Fläche auf der rechten Seite von unserem t-Wert berechnen wollen, dann nutzen wir mit <span class="math inline">\(Pr(X &gt; t)\)</span> die Option <code>lower.tail = FALSE</code>. In der Funktion <code><a href="https://rdrr.io/r/stats/TDist.html">pt()</a></code> ist das <code>q=</code> als <code>t=</code> zu lesen. Das macht das Verständnis vielleicht leichter.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fl">2.571</span>, df <span class="op">=</span> <span class="fl">5</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.025</code></pre>
</div>
</div>
<p>Neben der Berechnung der Wahrscheinlichkeit rechts und links eines gegebenen Wertes <span class="math inline">\(t\)</span> können wir auch <span class="math inline">\(t\)</span> berechnen, wenn wir eine Fläche vorgeben. Das kann uns dann die Funktion <code><a href="https://rdrr.io/r/stats/TDist.html">qt()</a></code> liefern. Wir sehen, dass mit steigender Fallzahl und damit steigenden Freiheitsgrad sich der berechnete Wert sich dem Wert der Standardnormalverteilung von <span class="math inline">\(1.96\)</span> für <span class="math inline">\(p = 0.05\)</span> annähert.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span><span class="op">)</span>, df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">20</span>, <span class="fl">100</span>, <span class="fl">1000</span><span class="op">)</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.571 2.228 2.086 1.984 1.962</code></pre>
</div>
</div>
<p>Wir haben gelernt, dass der Zusammenhang zwischen der Standardnormalverteilung und der t-Verteilung ziemlich stark ist. Nutzen werden wir die t-Verteilung aber nur im Rahmen des statistischen Testens.</p>
</section><section id="sec-poisson" class="level2 page-columns page-full" data-number="18.6"><h2 data-number="18.6" class="anchored" data-anchor-id="sec-poisson">
<span class="header-section-number">18.6</span> Die Poissonverteilung</h2>
<p>Eine weitere wichtige Verteilung ist die Poissonverteilung. Die Poissonverteilung ist eine diskrete Verteilung. Daher kommen nur ganze Zahlen vor. Damit bildet die Poissonverteilung die Zähldaten ab. Wenn wir also etwas Zählen, dann ist diese Variable mit den gezählten Ergebnissen poissonverteilt. Im Folgenden sehen wir die Poissonverteilung einmal dargestellt.</p>
<p><span class="math display">\[
\mathcal{Pois}(\lambda)
\]</span></p>
<p>Oder mit mehr Details in folgender Form.</p>
<p><span class="math display">\[
P_\lambda (k) = \frac{\lambda^k}{k!}\, \mathrm{e}^{-\lambda}
\]</span></p>
<p>Die Poisson-Verteilung gibt dann die Wahrscheinlichkeit einer bestimmten Ereignisanzahl <span class="math inline">\(k\)</span> im Einzelfall an, wenn die mittlere Ereignisrate <span class="math inline">\(\lambda\)</span> bekannt ist. Im Gegensatz zur Normalverteilung hat die Poissonverteilung nur einen Parameter. Den Lageparameter <span class="math inline">\(\lambda\)</span> ausgedrückt durch den griechischen Buchstaben Lambda. Eine Poissonverteilung mit <span class="math inline">\(\mathcal{Pois}(4)\)</span> hat den höchsten Punkt bei vier. Nun hat die Poissonverteilung hat mehrere Besonderheiten. Da die Poissonverteilung keinen Streuungsparameter hat, steigt mit dem <span class="math inline">\(\lambda\)</span> auch die Streuung. Daher haben Poissonverteilungen mit einem großen <span class="math inline">\(\lambda\)</span> auch eine große Streuung. ie Ausbreitung der Kurve ist eine Funktion von <span class="math inline">\(\lambda\)</span> und steigt mit <span class="math inline">\(\lambda\)</span> an. Du kannst diesen Zusammenhang in <a href="#fig-pois-00">Abbildung&nbsp;<span>18.6</span></a> beobachten.</p>
<p>Darüber hinaus kann eine Poissonverteilung nicht negativ werden. Es kann keine kleinere Zahl als die Null geben. Durch die diskreten Zahlen haben wir auch immer mal Lücken zwischen den Balken der Poissonverteilung. Das passiert besonders, wenn wir eine kleine Anzahl an Beobachtungen haben. Abschließend konvergiert die Poissonverteilung bei großen <span class="math inline">\(\lambda\)</span> hin zu einer Normalverteilung.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pois-00" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-00-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.6— Histogramm verschiedener Poissonverteilungen.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Schauen wir uns nun einmal die Poissonverteilung im Beispiel an. In <a href="#fig-pois-01">Abbildung&nbsp;<span>18.7</span></a> sehen wir die Histogramme der Anzahl an Gummibärchen in einer Tüte und die Anzahl an Farben in einer Tüte. Da wir es hier mit Zähldaten zu tun haben, könnte es sich um eine Poissonverteilung handeln. Wie müssen uns nun die Frage stellen, ob die Gummibärchen in einer Tüte und die Anzahl an Farben in einer Tüte <em>wirklich</em> eine zufällige Realistierung sind. Daher eine zufällige Stichprobe der Grundgesamtheit. Wir können diese Annahme überprüfen in dem wir die theoretischen Werte für die beiden Poissonverteilung mit <span class="math inline">\(\mathcal{Pois}(10)\)</span> und <span class="math inline">\(\mathcal{Pois}(5)\)</span> genieren.</p>
<div id="fig-pois-01" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-pois-01-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-01-1.png" class="img-fluid figure-img" data-ref-parent="fig-pois-01" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Anzahl an Bärchen</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-pois-01-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-01-2.png" class="img-fluid figure-img" data-ref-parent="fig-pois-01" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Anzahl an Farben</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.7— Histogramme der Anzahl an Gummibärchen und die Anzahl an Farben in einer Tüte. Es gibt nicht mehr als sechs Farben.</figcaption><p></p>
</figure>
</div>
<p>Wir können die Funktion <code><a href="https://rdrr.io/r/stats/Poisson.html">rpois()</a></code> nutzen um uns zufällige Zahlen aus der Poissonverteilung ziehen zu lassen. Dazu müssen wir mit <code>n =</code> spezifizieren wie viele Beobachtungen wir wollen und den Mittelwert <code>lambda =</code> angeben. Im Folgenden einmal ein Beispiel für die Nutzung der Funktion <code><a href="https://rdrr.io/r/stats/Poisson.html">rpois()</a></code> mit zehn Werten.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">rpois</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10</span>, lambda <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3 5 4 5 3 3 9 3 5 5</code></pre>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Es gibt neben der Poissonverteilung auch die negative Binomialverteilung sowie die Quasi-Poissonverteilung, die es erlauben einen Streuungsparameter für die Poissonverteilung zu schätzen.</span></div></div>
<p>Wir können nun auch aus unseren Gummibärchendaten für die Anzahl an Bärchen in einer Tüte sowie die Anzahl an Farben in einer Tüte die theoretische Poissonverteilung berechnen. In <a href="#fig-pois-03">Abbildung&nbsp;<span>18.8</span></a> sehen wir die Verteilung der beobachteten Werte für Anzahl an Bärchen in einer Tüte sowie die Anzahl an Farben in einer Tüte und deren theoretischen Verteilung nach dem geschätzen <span class="math inline">\(\lambda = 10\)</span> und <span class="math inline">\(\lambda = 5\)</span>. Wir sehen ganz klar, dass die beide Variablen <em>keine</em> Zufallsrealisierung sind. Zum einen haben wir das auch nicht erwartet, es gibt nicht mehr als sechs Farben und zum anderen ist zu vermuten, dass Haribo technisch in den Auswahlprozess eingreift. Wir haben auf jeden Fall eine sehr viel kleinere Streuung als bei einer <em>klassischen</em> Poissonverteilung anzunehmen wäre.</p>
<div id="fig-pois-03" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-pois-03-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-03-1.png" class="img-fluid figure-img" data-ref-parent="fig-pois-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Verteilung der beobachteten Anzahl an Bärchen.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-pois-03-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-03-2.png" class="img-fluid figure-img" data-ref-parent="fig-pois-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Verteilung der theoretischen Anzahl an Bärchen.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-pois-03-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-03-3.png" class="img-fluid figure-img" data-ref-parent="fig-pois-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(c) Verteilung der beobachteten Anzahl an Farben.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-pois-03-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-pois-03-4.png" class="img-fluid figure-img" data-ref-parent="fig-pois-03" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(d) Verteilung der theoretischen Anzahl an Farben.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.8— Darstellung Anzahl an Bärchen und Anzahl an Farben. Es gibt nicht mehr als sechs Farben. Auf der linken Seite die beobachteten Werte und auf der rechten Seite die theoretischen Werte.</figcaption><p></p>
</figure>
</div>
<p>In <a href="#fig-gummi-years-count">Abbildung&nbsp;<span>18.9</span></a> schauen wir uns nochmal an in wie weit sich die Füllung der Tütchen im Laufe der Jahre entwickelt hat. Die Daten werden ja schon seit 2018 erhoben. Wir schauen uns daher die Densityplot einmal aufgetrennt für die Jahre 2018 bis heute an. Das Jahr 2020 fehlt, da bedingt durch die Coronapandemie keine Präsenslehre stattfand. Wir sehen, dass sich die Verteilung anscheinend in dem Jahr 2022 langsam nach links zu weniger Bärchen in einer Tüte bewegt. Wir bleiben gespannt auf den weiteren Trend.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-gummi-years-count" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-gummi-years-count-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.9— Densityplot der Anzahl an Bärchen in einer Tüte aufgetrennt nach den Jahren der Erhebung. Das Jahr 2020 fehlt bedingt durch die Coronapandemie.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-gummi-mostliked">Abbildung&nbsp;<span>18.10</span></a> betrachten wir die Verteilung der am meisten gemochten Gummibärchen aufgeteilt nach dem angegebenen Geschlecht im Vergeich zu den Gummibärchen in den Tütchen. Wir sehen, dass Haribo die Tütchen sehr gleichmäßig verteilt und auf die Geschmäcker keinerlei Rücksicht nimmt. Entweder weiß Haribo nichts von den Vorlieben seiner Käufer:innen oder aber es ist dann doch zu viel Aufwand die Produktion anzupassen.</p>
<div id="fig-gummi-mostliked" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-gummi-mostliked-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-gummi-mostliked-1.png" class="img-fluid figure-img" data-ref-parent="fig-gummi-mostliked" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Anzahl am liebsten gemochten Gummibärchen aufgeteilt nach Geschlecht.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-gummi-mostliked-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-gummi-mostliked-2.png" class="img-fluid figure-img" data-ref-parent="fig-gummi-mostliked" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Anzahl der Gummibärchen pro Tüte nach Farbe.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.10— Histogramme der am liebsten gemochten Gummibärchchen im Vergleich zum Inhalt der Tütchen.</figcaption><p></p>
</figure>
</div>
</section><section id="sec-binom" class="level2 page-columns page-full" data-number="18.7"><h2 data-number="18.7" class="anchored" data-anchor-id="sec-binom">
<span class="header-section-number">18.7</span> Die Binominalverteilung</h2>
<p>Die Binomialverteilung wird uns vor allem später in den logistischen Regression wieder begegnen. An dieser Stelle ist es wichtig zu wissen, dass wir es bei der Binomialverteilung mit binären Ereignissen zu tun haben. Wir haben nur Erfolg oder nicht. Daher haben wir nur das Ergebnis <span class="math inline">\(0/1\)</span> daher Null oder Eins. Dieses Ergebnis ist im Prinzip auch die Beschreibung eines Patienten, ob dieser krank oder nicht krank ist. Deshalb finden wir die Binomialverteilung auch häufig in einem medizinischen Kontext.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Es gibt auch ein schönes Tutorial zur <a href="https://mse.redwoods.edu/darnold/math15/spring2013/R/Activities/binomial1.html">Binomial Distribution</a> von David Arnold.</p>
</div></div><p>Schauen wir uns die Formel für die Binomialverteilung einmal genauer an. Wichtig ist, dass wir etwas <span class="math inline">\(n\)</span>-mal wiederholen und uns dann fragen, wie <em>exakt</em> <span class="math inline">\(k\)</span>-oft haben wir Erfolg.</p>
<p><span class="math display">\[
B(k\mid p,n)=
\begin{cases}
  \binom nk p^k (1-p)^{n-k} &amp;\text{falls} \quad k\in\left\{0,1,\dots,n\right\}\\
  0            &amp; \text{sonst.}
  \end{cases}
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(n\)</span> gleich der Anzahl an Versuchen (eng. <em>trails</em>)</li>
<li>
<span class="math inline">\(k\)</span> gleich der Anzahl an Erfolgen</li>
<li>
<span class="math inline">\(p\)</span> gleich der Wahrscheinlichkeit für einen Erfolg.</li>
</ul>
<p>Bevor wir mit dem Beispiel beginnen können brauchen wir noch etwas mehr für die Berechnung der Formel. Wir brauchen noch für die Berechnung der Binomalverteilung den Binomialkoeffizienten <span class="math inline">\(\tbinom {n}{k}\)</span>, den wir wie folgt bestimmen können. Dabei bedeutet das <span class="math inline">\(!\)</span>, dass wir eine Zahl aufmultiplizieren. Daher müssen wir für <span class="math inline">\(4!\)</span> dann wie folgt rechnen <span class="math inline">\(4! = 1 \cdot 2 \cdot 3 \cdot 4 = 24\)</span>.</p>
<p><span class="math display">\[
\binom nk = \cfrac{n!}{k! \cdot (n-k)!}
\]</span></p>
<p>Nehmen wir dafür einmal ein Beispiel mit 5 über 3 und schauen uns die Rechnung einmal an. Wir erhalten den Binomialkoeffizienten <span class="math inline">\(\tbinom {5}{3}\)</span> wie folgt.</p>
<p><span class="math display">\[
\binom 5 3 = \frac{5!}{3! \cdot (5-3)!} = \frac{5!}{3! \cdot 2!} = \frac{1\cdot 2\cdot 3\cdot 4\cdot 5}{(1\cdot 2\cdot 3) \cdot (1\cdot 2)} = \frac{4\cdot 5}{1\cdot 2} = 10
\]</span></p>
<p>Viele Taschenrechner können den Binomialkoeffizienten flott ausrechnen. Wenn wir keinen Taschenrechner haben, dann können wir auch das Pascalsche (oder Pascal’sche) Dreieck nutzen. Das Pascalsche Dreieck ist eine Form der grafischen Darstellung der Binomialkoeffizienten <span class="math inline">\(\tbinom {n}{k}\)</span>. Wir sehen einmal in <a href="#fig-pascal">Abbildung&nbsp;<span>18.11</span></a> den Zusammenhang mit dem Binomialkoeffizienten dargestellt. Mit dem Pascalsche Dreieck können wir auch ohne Taschenrechner den Binomialkoeffizienten bestimmen.</p>
<div id="fig-pascal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/distribution-binom.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.11— Darstellung des Pascalsche (oder Pascal’sche) Dreieckes im Zusammenhang zum Binomialkoeffizienten.</figcaption><p></p>
</figure>
</div>
<p>Somit können wir auch einmal ein erweitertes Beispiel der Binomialverteilung rechnen. Was ist die Wahrscheinlichkeit bei <span class="math inline">\(n = 5\)</span> Münzwürfen <em>genau</em> dann <span class="math inline">\(k = 2\)</span> Erfolge zu erzielen, wenn die Münze fair ist und damit gilt <span class="math inline">\(p = 0.5\)</span>?</p>
<p><span class="math display">\[
\begin{aligned}
Pr(Y = 3) &amp;= \binom {5}{3} 0.5^{3} (1-0.5)^{5-3} \\  
&amp;= 10 \cdot 0.5^3 \cdot 0.5^2 \\
&amp;= 0.31
\end{aligned}
\]</span></p>
<p>Wir immer können wir die ganze Rechnung dann auch in R durchführen. Dank der Funktion <code><a href="https://rdrr.io/r/base/Special.html">choose()</a></code> können wir schnell den Binomialkoeffizienten berechnen. Der Rest ist dann nur noch das Einsetzen.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Special.html">choose</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">3</span><span class="op">)</span> <span class="op">*</span> <span class="fl">0.5</span><span class="op">^</span><span class="fl">3</span> <span class="op">*</span> <span class="fl">0.5</span><span class="op">^</span><span class="fl">2</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3125</code></pre>
</div>
</div>
<p>Auch hier geht es natürlich auch in R noch einen Schritt schneller. Leider heißt dann wieder alles anders. Wir wollen <code>x = k = 3</code> Erfolge aus <code>size = n = 5</code> Versuchen mit einer Erfolgswahrscheinlichkeit von <code>prob = 0.5</code>. Daran muss man sich dann gewöhnen, dass sich die Begrifflichkeiten dann doch immer mal wieder ändern.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">3</span>, size <span class="op">=</span> <span class="fl">5</span>, prob <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3125</code></pre>
</div>
</div>
<p>Was wäre wenn wir jetzt die Wahrscheinlichkeit <span class="math inline">\(Pr(Y \leq 3)\)</span> berechnen wollen? Also nicht <em>exakt</em> die Wahrscheinlichkeit für <span class="math inline">\(k=3\)</span> Erfolge sondern eben <span class="math inline">\(k\)</span> Erfolge oder weniger <span class="math inline">\(k \leq 3\)</span>. Dann müssen wir die Wahrscheinlichkeiten für <span class="math inline">\(Pr(Y = 0)\)</span>, <span class="math inline">\(Pr(Y = 1)\)</span>, <span class="math inline">\(Pr(Y = 2 )\)</span> und <span class="math inline">\(Pr(Y = 3)\)</span> berechnen und diese Wahrscheinlichkeiten aufaddieren.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">5</span>, <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">5</span>, <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">0.5</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8125</code></pre>
</div>
</div>
<p>Oder wir rechen einfach die Fläche und damit die Wahrscheinlichkeit links von <span class="math inline">\(k = 3\)</span> aus. Dafür haben wir dann die Funktion <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code>. Es geht dann eben doch etwas flotter. Wie immer können wir dann über die Option <code>lower.tail =</code> entscheiden, auf welche Seite der Verteilung wir schauen wollen.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">0.5</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8125</code></pre>
</div>
</div>
<p>Angenommen, eine Münze wird so gewichtet, dass sie in 60 % der Fälle Kopf ergibt. Wie hoch ist die Wahrscheinlichkeit, dass Sie nach 50 Würfen 25 oder mehr Köpfe erhalten? Dafür können wir dann auch die Funktion <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> einmal nutzen. Da wir <em>mehr</em> wollen, also “größer als”, müssen wir rechts von dem berechneten Wert schauen, also auswählen, dass <code>lower.tail = FALSE</code> ist.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">25</span>, <span class="fl">50</span>, <span class="fl">0.6</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9021926</code></pre>
</div>
</div>
<p>Zum Abschluss schauen wir nochmal in unseren Gummibärchendaten, wie dort ein Histogramm einer binären Variable mit nur zwei Ausprägungen aussehen würde. In <a href="#fig-gummi-binom">Abbildung&nbsp;<span>18.12</span></a> sehen wir einmal das Geschlecht als Balkendiagramm dargestellt. Mehr gibt es zu diesem Diagramm erstmal nicht zu berichten. Bei einer Variable bei einem unbekannten <span class="math inline">\(p\)</span> für eine der Kategorien, ist schwer etwas zu bewerten. Wir sehen aber, dass wir eine sehr schöne Gleichverteilung von den Geschlechtern in den Daten haben.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-gummi-binom" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-gummi-binom-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.12— Beispiel für eine Binomialverteilung anhand des Geschlechts. Die fehlenden Angaben wurden entfernt.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="sec-uniform" class="level2 page-columns page-full" data-number="18.8"><h2 data-number="18.8" class="anchored" data-anchor-id="sec-uniform">
<span class="header-section-number">18.8</span> Die Uniformverteilung</h2>
<p>Die Gleichverteilung oder Uniformverteilung brauchen wir in der Statistik eher selten. Da wir aber hin und wieder mal auf die Gleichverteilung in technischen Prozessen stoßen, wollen wir uns die Gleichverteilung nochmal anschauen. Wenn wir eine Gleichverteilung vorliegen haben, dann sind alle Kategorien gleich häufig vertreten. Es ergibt sich dann folgende Verteilung als Plateau. Das Eintreten jedes Ereignisses ist gleich wahrscheinlich.</p>
<p><span class="math display">\[
f(y)=
\begin{cases}
  \cfrac 1{b-a} &amp; a \le y \le b\\
  0            &amp; \text{sonst.}
\end{cases}
\]</span></p>
<div id="fig-dist-uni" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/distribution-uni.png" class="img-fluid figure-img" style="width:60.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.13— Darstellung der Uniformverteilung zwischen den beiden Punkten <span class="math inline">\(a\)</span> und <span class="math inline">\(b\)</span>.</figcaption><p></p>
</figure>
</div>
<p>Da gibt es auch sonst wenig mehr zu berichten. Nehmen wir daher nochmal ein technisches Beispiel aus unseren Gummibärchendaten. Wir würden je Farbe 838 Gummibärchen erwarten. Warum ist das so? Wir haben insgesamt 5029 ausgezählt. Wenn jede der sechs Kategorien mit der gleichen Wahrscheinlichkeit auftritt, dann erwarten wir jeweils <span class="math inline">\(1/6\)</span> von der Gesamtzahl. Wir erkennen, dass wir etwas zu wenig grüne Bärchen haben. Ebenso sind die hellroten Bärchen unterrepräsentiert. Dafür haben wir dann zwangsweise etwas mehr an gelben und orangen Gummibärchen. Dennoch würde ich hier von einer Gleichverteilung ausgehen.</p>
<div id="fig-gummi-uniform" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-gummi-uniform-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-gummi-uniform-1.png" class="img-fluid figure-img" data-ref-parent="fig-gummi-uniform" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(a) Verteilung der beobachteten Anzahl der Gummibärchen pro Tüte nach Farbe.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-gummi-uniform-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="eda-distribution_files/figure-html/fig-gummi-uniform-2.png" class="img-fluid figure-img" data-ref-parent="fig-gummi-uniform" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">(b) Verteilung der theoretischen Anzahl der Gummibärchen pro Tüte nach Farbe.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.14— Beispiel für eine uniforme Verteilung anhand der Anzahl der Gummibärchen pro Tüte nach Farbe</figcaption><p></p>
</figure>
</div>
</section><section id="weitere-verteilungen" class="level2 page-columns page-full" data-number="18.9"><h2 data-number="18.9" class="anchored" data-anchor-id="weitere-verteilungen">
<span class="header-section-number">18.9</span> Weitere Verteilungen</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir besuchen gerne die R Shiny App <a href="https://ben18785.shinyapps.io/distribution-zoo/">The distribution zoo</a> um mehr über die verschiedenen Verteilungen und deren Parameter zu erfahren.</p>
</div></div><p>Weitere Beispiele finden sich unter <a href="https://rstudio-pubs-static.s3.amazonaws.com/100906_8e3a32dd11c14b839468db756cee7400.html">Basic Probability Distributions in R</a>. Im Weiteren liefert <span class="citation" data-cites="dormann2013parametrische">Dormann (<a href="#ref-dormann2013parametrische" role="doc-biblioref">2013</a>)</span> eine gute Übersicht über verschiedene Verteilungen und deren Repräsentation in R. Das ist nur eine Auswahl an möglichen Verteilungen. Bitte hier nicht ins <em>rabbit hole</em> der Verteilungen gehen. Wir benötigen in unserer täglichen Arbeit nur einen kleinen Teil der Verteilungen. Es reicht, wenn du eine Vorstellungen der Verteilungen in diesem Kapitel hat.</p>
</section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-dormann2013parametrische" class="csl-entry" role="doc-biblioentry">
Dormann, Carsten F. 2013. <em>Parametrische Statistik</em>. Springer.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./eda-transform.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-tests-preface.html" class="pagination-link">
        <span class="nav-page-text">Frequentistische Hypothesentests</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>