<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 3&nbsp; Forschungsprozess</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./abschlussarbeit.html" rel="next">
<link href="./literature.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./preface.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Fortgeschrittene Versuchsplanung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Anhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spielecke</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li>
<a href="#zur%C3%BCck-in-die-zukunft" id="toc-zurück-in-die-zukunft" class="nav-link active" data-scroll-target="#zur%C3%BCck-in-die-zukunft"><span class="header-section-number">3.1</span> Zurück in die Zukunft</a>
  <ul class="collapse">
<li><a href="#klassischer-7g-unterricht" id="toc-klassischer-7g-unterricht" class="nav-link" data-scroll-target="#klassischer-7g-unterricht"><span class="header-section-number">3.1.1</span> Klassischer 7G-Unterricht</a></li>
  <li><a href="#future-skills" id="toc-future-skills" class="nav-link" data-scroll-target="#future-skills"><span class="header-section-number">3.1.2</span> Future Skills</a></li>
  </ul>
</li>
  <li>
<a href="#beispielhafte-forschungsprozesse" id="toc-beispielhafte-forschungsprozesse" class="nav-link" data-scroll-target="#beispielhafte-forschungsprozesse"><span class="header-section-number">3.2</span> Beispielhafte Forschungsprozesse</a>
  <ul class="collapse">
<li><a href="#logik" id="toc-logik" class="nav-link" data-scroll-target="#logik"><span class="header-section-number">3.2.1</span> Logik</a></li>
  <li><a href="#determinismus" id="toc-determinismus" class="nav-link" data-scroll-target="#determinismus"><span class="header-section-number">3.2.2</span> Determinismus</a></li>
  </ul>
</li>
  <li>
<a href="#eine-neue-physikalische-theorie-des-lebens" id="toc-eine-neue-physikalische-theorie-des-lebens" class="nav-link" data-scroll-target="#eine-neue-physikalische-theorie-des-lebens"><span class="header-section-number">3.3</span> Eine neue physikalische Theorie des Lebens</a>
  <ul class="collapse">
<li><a href="#evolutionstheorie" id="toc-evolutionstheorie" class="nav-link" data-scroll-target="#evolutionstheorie"><span class="header-section-number">3.3.1</span> Evolutionstheorie</a></li>
  <li><a href="#wiener-schule" id="toc-wiener-schule" class="nav-link" data-scroll-target="#wiener-schule"><span class="header-section-number">3.3.2</span> Wiener Schule</a></li>
  <li><a href="#falsifikationsprinzip" id="toc-falsifikationsprinzip" class="nav-link" data-scroll-target="#falsifikationsprinzip"><span class="header-section-number">3.3.3</span> Falsifikationsprinzip</a></li>
  <li><a href="#cargo-cult-science" id="toc-cargo-cult-science" class="nav-link" data-scroll-target="#cargo-cult-science"><span class="header-section-number">3.3.4</span> Cargo Cult Science</a></li>
  <li><a href="#wahrscheinlichkeitsbegriff" id="toc-wahrscheinlichkeitsbegriff" class="nav-link" data-scroll-target="#wahrscheinlichkeitsbegriff"><span class="header-section-number">3.3.5</span> Wahrscheinlichkeitsbegriff</a></li>
  <li><a href="#anthropoz%C3%A4n" id="toc-anthropozän" class="nav-link" data-scroll-target="#anthropoz%C3%A4n"><span class="header-section-number">3.3.6</span> Anthropozän</a></li>
  <li><a href="#data-science" id="toc-data-science" class="nav-link" data-scroll-target="#data-science"><span class="header-section-number">3.3.7</span> Data Science</a></li>
  </ul>
</li>
  <li><a href="#und-jetzt" id="toc-und-jetzt" class="nav-link" data-scroll-target="#und-jetzt"><span class="header-section-number">3.4</span> Und jetzt?</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-intro" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom July 23, 2023 um 21:07:54</em></p>
<blockquote class="blockquote">
<p><em>“In der Wissenschaft beginnt alles Neue damit, dass jemand brummt ‘Hmmm… ist ja komisch.’” — Isaac Asimov</em></p>
</blockquote>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/caution.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Wenn du forsche willst, musst du das was dich an Welt und Realität umgibt hinterfragen. Beginnen wir also mit einer kleinen Parabel von <span class="citation" data-cites="wallace2009water">Wallace (<a href="#ref-wallace2009water" role="doc-biblioref">2009</a>)</span> <a href="https://fs.blog/david-foster-wallace-this-is-water/">über das Wasser</a>.</p>
<blockquote class="blockquote">
<p>Da schwimmen zwei junge Fische und treffen zufällig einen älteren Fisch, der in die andere Richtung schwimmt, ihnen zunickt und sagt: “Morgen, Jungs. Wie ist das Wasser?” Und die beiden jungen Fische schwimmen eine Weile weiter, bis schließlich einer von ihnen zu dem anderen hinüberschaut und sagt: “Was zum Teufel ist Wasser?”</p>
</blockquote>
<p>Okay, nette Geschichte über Fische, aber was denn nun mit wissenschaftlicher Forschung zu tun? Keine Angst, wir kommen nochmal auf die Geschichte mit dem Wasser zurück. Aber zuerst die Frage nach dem Woher kommen wir eigentlich und wohin wollen wir? Das sind die Fragen, die wir in diesem Einführungskapitel zu dem Prozess der Forschung angehen wollen. Für viele Anfänger ist das wissenschaftliche Arbeiten immer etwas sperrig oder gar mysteriös. Irgendwie passt das wissenschaftliche Arbeiten nicht so richtig in die Alltagserfahrungen hinein. Oder etwas plakativer, wissenschaftliches Arbeiten soll und muss sich vom <em>gesunden Menschenverstand</em> unterscheiden.</p>
<p>Wissenschaftliches Arbeiten und Forschen ist nämlich eine eigne Kulturtechnik. Kulturtechniken sind kulturelle und technische Konzepte zur Bewältigung von Problemen in unterschiedlichen Lebenssituationen. Dabei besteht ein komplexer Zusammenhang zwischen der Gestaltung der Umstände, dem technischen Können und der verwendeten Technik. Wissenschaft betreiben zu Können ist eine von vielen Kulturtechniken. Um eine Kulturtechnik ausüben zu können, sind bestimmte Voraussetzungen unerlässlich. Dazu gehören das Beherrschen von Lesen, Schreiben und Rechnen sowie die Fähigkeit zur bildlichen Darstellung. Analytische Fähigkeiten, die Anwendung von kulturhistorischem Wissen und die Vernetzung verschiedener Methoden sind ebenfalls voneinander abhängig. Eine Kulturtechnik entsteht nicht allein durch das Individuum, sondern durch Gruppenleistungen im soziokulturellen Kontext. Daher erfordern alle genannten Voraussetzungen stets soziale Interaktion und gesellschaftliche Teilhabe.</p>
<blockquote class="blockquote">
<p><em>“Scientific knowledge, especially as stacked in textbooks, has an aura of objectivity - it is secure, uninfluenced by what we might hope or fear, and a solid assertion of what is true. Or, at least, that is what we are supposed to think. Knowledge, once formed, tends to become disembodied from its human origins. That is, while knowledge is preserved in the form of books, formulas, proofs, theorems, and such, we must not forget that before all this the formation of knowledge was the result of human thought, effort, and desire. Knowledge is a product of human hopes and fears; our emotions are crucial to its development, and its meaning cannot be truly understood if seen as some bloodless and emotionless enterprise.” — Writing science: how to write papers that get cited and proposals that get funded <span class="citation" data-cites="schimel2012writing">(<a href="#ref-schimel2012writing" role="doc-biblioref">Schimel 2012</a>)</span></em></p>
</blockquote>
<p>Hinter der Kulturtechnik des wissenschaftliches Arbeiten verbirgt sich konkret eine eigne Art zu Denken — eine wissenschaftliche Philosophie. Häufig ist dir gar nicht bewusst, dass es verschiedene Denkschulen und Denkansätze gibt. Mit Philosophen verbinden wir häufig die alten Griechen, die auf Plätzen, umrahmt von Marmorsäulen, einen Plausch abhalten. Oder aber wir haben das Bild von dem Philosophen Diogenes in dem Weinfaß vor Augen, was auch den Philosophen eher gering schätzt. Diogenes kommt als versoffener Obdachloser rüber, dem wir dann auch nicht zuhören müssen. Auch wenn er uns unbequeme Dinge sagen mag. Wir wollen uns also im folgenden Kapitel auf ein Abenteuer begeben und dabei uns verschiedene Denkschulen einmal näher anschauen. Dabei behalten wir im Hinterkopf, dass ein Abenteuer eine Unternehmung mit ungewissen Ausgang ist.</p>
<section id="zurück-in-die-zukunft" class="level2 page-columns page-full" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="zurück-in-die-zukunft">
<span class="header-section-number">3.1</span> Zurück in die Zukunft</h2>
<blockquote class="blockquote">
<p><em>“So. Zeitleitung einschalten. Flux Kompensator - fluxuriert. Maschine läuft. Es kann los gehen.” — George McFly in Zurück in die Zukunft</em></p>
</blockquote>
<p>Wo wollen wir eigentlich hin, wenn wir einmal den ganz großen Bogen spannen? Die Lehre soll sich ja immer in die Zukunft (eng. <em>future</em>) richten und Wissen von einer Generation zu der nächsten Transferieren. Wir haben ja immer nur eine begrenzte Zeit zu Verfügung in der ich dir Fähigkeiten (eng. <em>skills</em>) vermitteln kann. Nun ist die Frage, was soll ich eigentlich unterrichten und was wird in der <em>Zukunft</em> den nun gebraucht? Beginnen wir erstmal mit der klassischen 7G-Lehre, die du bis jetzt immer erlebt hast.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die Pyramiden von Gizeh entstanden etwa von 2620 bis 2500 v. Chr. und waren bis zur Errichtung des Eifelturms im Jahre 1889 n.&nbsp;Chr. das höchste, von Menschen erschaffene, Gebäude.</p>
</div></div><section id="klassischer-7g-unterricht" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="klassischer-7g-unterricht">
<span class="header-section-number">3.1.1</span> Klassischer 7G-Unterricht</h3>
<p>Was ist eigentliche die klassische Lehr- und Lernerfahrung aus der Schule? Oder andersherum, was ist Wasser im Bezug auf deine Schulerfahrung? Denn aus der Schule kommst du an die Hochschule und bringst für dich die Norm für deine Lehr- und Lernerfahrung mit. Deshalb hier einmal etwas mit Abstand auseinander genommen was klassischer Unterricht ist und warum dieser klassische Unterricht nach <span class="citation" data-cites="helmke2013individualisierung">Helmke (<a href="#ref-helmke2013individualisierung" role="doc-biblioref">2013</a>)</span> auch 7G-Unterricht genannt wird. Schule ist nicht so wie Schule ist, weil Schule so passiert, sondern weil ganz viele Akteure Schule so wollen.</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 35.0%;justify-content: center;">
<ul>
<li>
<strong>g</strong>leiches Alter</li>
<li>
<strong>g</strong>leicher Ort</li>
<li>
<strong>g</strong>leiche Zeit</li>
<li>
<strong>g</strong>leiche Art und Weise</li>
<li>
<strong>g</strong>leiches Lehrperson</li>
<li>
<strong>g</strong>leiche Inhalte</li>
<li>
<strong>g</strong>leiche Lernziele</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 65.0%;justify-content: center;">
<p>Im klassischen 7G-Unterricht bearbeiten <strong>g</strong>leichaltrige Schüler:innen im <strong>g</strong>leichen Raum zur <strong>g</strong>leichen Zeit auf die <strong>g</strong>leiche Art und Weise mit der <strong>g</strong>leichen Lehrperson die <strong>g</strong>leichen Inhalte – und orientieren sich dabei an den <strong>g</strong>leichen Zielen. Wir sehen also, es ist ein starker Fokus auf das <em>Gleiche</em> für jeden. Die individuellen Lernansprüche der Schüler:innen werden somit höchstens zufällig vom klassischen Unterricht erfüllt.</p>
</div>
</div>
</div>
<p>Darüber hinaus haben wir in der Schule einen Fokus auf das Ergebnis und nicht den Prozess. Du bist darauf trainiert, bei einem ersten Versuch besser als der Durchschnitt zu sein und zu vergessen, was du getan hast, sobald du deine Klausur geschrieben hast. Es geht also primär um die Note am Ende und um möglichst effizient eien gute Note zu erreichen. César A. Hidalgo schrieb zum diesem antrainierten Verhalten in der Schule und dem Spannungsfeld der späteren Arbeit einen längeren <a href="https://threadreaderapp.com/thread/1437043299852996608.html">Faden auf Twitter</a> mit folgenden Eingangstweet.</p>
<blockquote class="blockquote">
<p>Nachdem ich über ein Jahrzehnt lang Doktoranden und Masterstudierende beraten habe, stelle ich fest, dass die meisten Studierenden eine Sache erst einmal ablegen müssen: die Mentalität der Halbherzigkeit, die sie sich durch jahrelange Tests und Hausaufgaben angeeignet haben.</p>
</blockquote>
<p>Was ist also Wasser für dich in deiner Schulerfahrung? Hilft diese Erfahrung eigentlich zukünftige Herausforderungen zu meistern? Vor allem ändert sich jetzt vieles im Bezug auf die Hochschule. Am Anfang des Studiums ähnelt noch vieles der Schule oder dir kommt es eher noch so vor. Im Verlauf des Studiums erfährtst du dann eine immer stärker werdende Individualisierung. Du musst dich um viel mehr selber kümmern und auch auch die Lehr- und Lernformate ändern sich. Warum das so ist, wollen wir im nächsten Abschnitt einmal anschauen. Der Fokus geht nämlich weg vom 7G-Unterreicht und hin zu den Future Skills (eng. <em>Zukunfstfähigkeiten</em>).</p>
</section><section id="future-skills" class="level3" data-number="3.1.2"><h3 data-number="3.1.2" class="anchored" data-anchor-id="future-skills">
<span class="header-section-number">3.1.2</span> Future Skills</h3>
<blockquote class="blockquote">
<p><em>“Prognosen sind schwierig, vor allem, wenn sie die Zukunft betreffen.” — Mark Twain</em></p>
</blockquote>
<p>Nachdem wir uns etwas mit der Vergangenheit deiner Schulerfahrung beschäftigt haben wollen wir nun einen Blick in die Zukunft wagen. Wir fragen uns daher, welche Fähigkeiten brauchen wir um mit zukünftigen Herausforderungen an uns zu meistern? Was sind den nun die zukünftig notwendigen Fähigkeiten (eng. <em>Future Skills</em>)? Hierzu nutzen wir als die direkte Quelle den <a href="https://www.stifterverband.org/future-skills">Stifterverband-Initiative “Future Skills”</a>. Dort finden wir dann auch die <a href="https://www.stifterverband.org/medien/future-skills-2021/kompetenzen">Future Skills: Die Skills im Überblick</a>. Grundsätzlich ist die Idee nicht so neu, auch schon das <a href="https://de.wikipedia.org/wiki/Humboldtsches_Bildungsideal">humboldtsche Bildungsideal</a> spricht davon, soviel Welt wie möglich in sich aufzunehmen. Die Future Skills sind aber strukturierter und erlauben ein mehr gerichtetes Lehren und Lernen.</p>
<p>Die Future Skills teilen sich in vier Kompetenzen auf, die wiederum aus verschiedenen Inhalten bestehen. Sicherlich ist es nicht möglich alle Bereiche abzudecken oder ein tiefes Sachverständis zu erlangen. Dennoch sind das die Themenfelder, die zukünftig eine Rollen spielen werden. Und das Leben ist lang und lebenslanges Lernen bedeutet ja auch nichts anderes als immer wieder neue Fähigkeiten zu erlangen. Zum einen müssen wir zwischen Spezialisten für den Umgang mit transformativer Technologien und Schlüsselkompetenzen im Allgmeinen für alle Arbeitsbereiche. In der <a href="#fig-future-skills">Abbildung&nbsp;<span>3.1</span></a> wird dieser Zusammenhang nochmal dargestellt. Auch wenn du kein Spezialist für transformative Technologien sein willst, so solltest du dich in den Fachbegriffen auskennen, da du sicherlich im Team mit diesen Spezialisten arbeiten wirst. Im Bereich der zukünftigen Schlüsselkompetenzen machen die klassischen Kompetenzen nur noch einen kleinen Teil aus.</p>
<div id="fig-future-skills" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/future_skills_2021.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.1— Darstellung der vier Kategorien der Future Skills und deren Verbindung untereinander sowie deren zukünfige Gewichtung</figcaption></figure>
</div>
<p>Betrachten wir die einzelnen Kompetenzen und deren Inhalte in <a href="#tbl-future-skills">Tabelle&nbsp;<span>3.1</span></a> nochmal detaillierter. Dabei ist wichtig zu bachten, dass wir die vier Kompetenzfelder i) technologische Kompetenz, ii) digitale Schlüsselkompetenz, iii) klassische Kompetenz und iv) transformative Kompetenz vorliegen haben. In jeder dieser Kompetenz haben wir noch weitgefasste Inhaltsfelder. Besonders im Bereich der technologischen Kompetenzen lässt sich ein umfangreiches Wissen kaum erreichen. Hier sind wichtige zukünftige Inhaltsfelder benannt, die sich teilweise überschneiden. Die digitalen Schlüsselkompetenzen werden im Rahmen der Hochschullehre teilweise vermittelt. Die klassischen Kompetenzen sowie die die transformativen Kompetenzen gehören zum weiten Bereich der Persönlichkeitsentwicklung und sollen hier auch als Leitfaden und Orientierungshilfe dienen.</p>
<div id="tbl-future-skills" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;3.1— Die vier Kompetenzen der Future Skills zusammen mit den jeweiligen Inhalten.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead><tr class="header">
<th>Kompetenzen</th>
<th>Inhalte</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><em>Technologische Kompetenzen</em></td>
<td>Data Analytics &amp; KI, Softwareentwicklung, Nutzerzentriertes Design, IT-Architektur, Hardware/Robotikentwicklung, Quantencomputing</td>
</tr>
<tr class="even">
<td><em>Digitale Schlüsselkompetenzen</em></td>
<td>Digital Literacy, Digital Ethics, Digitale Kollaboration, Digital Learning, Agiles Arbeiten</td>
</tr>
<tr class="odd">
<td><em>Klassische Kompetenzen</em></td>
<td>Lösungsfähigkeit, Kreativität, Unternehmerisches Handeln &amp; Eigeninitiative, Interkulturelle Kommunikation, Resilienz</td>
</tr>
<tr class="even">
<td><em>Transformative Kompetenzen</em></td>
<td>Urteilsfähigkeit, Innovationskompetenz, Missionsorientierung, Veränderungskompetenz, Dialog- und Konfliktfähigkeit</td>
</tr>
</tbody>
</table>
</div>
<p>Wir immer im Leben gilt, dass niemand weiß, was in der Zukunft gebraucht wird und wirklich nüzlich ist. Die Future Skills bieten aber einen guten Leitfaden zur Orientierung. Nicht alles muss man erfüllen um für die Zukunft gewappnet zu sein, wie wir dann noch später lernen werden. Die Idee zu definieren welche Fähigkeiten der Mensch für die Zukunft braucht ist nämlich auch schon sehr alt und wurde schon von vielen Philosophen durchdacht. Jede Idee hat natürlich ihre Zeit aus der sie kommt, aber manche Ideen überdauern dann doch Jahrhunderte. Schauen wir uns also im Laufe des Kapitels einige an.</p>
</section></section><section id="beispielhafte-forschungsprozesse" class="level2 page-columns page-full" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="beispielhafte-forschungsprozesse">
<span class="header-section-number">3.2</span> Beispielhafte Forschungsprozesse</h2>
<blockquote class="blockquote">
<p><em>“Ein Schiff ist im Hafen sicher, doch dafür werden Schiffe nicht gebaut.” — John Augustus Shedd</em></p>
</blockquote>
<p>In diesem Abschnitt wollen wir uns verschiedene Forschungsprozesse an verschiedenen historischen Beispielen anschauen. Spannend ist, dass keiner dieser Forschungsprozesse wirklich abgeschlossen ist. Auch ist ein Forschungsprozess eher offen. Selten ist der Anfang und das Ende wirklich präsize zu benennen. Das kann ja auch nicht sein, den Forschung ist ein fortschreitende Prozess, der kein definiertes Ende hat. Das ist das meistens auch das schwierigste beim Forschen. Ein Ende zu finden und seine Ergebnisse zu publizieren und der Öffentlichkeit zu Verfügung zu stellen, obwohl man subjektiv noch gar nicht fertig ist. Zwar mögen Forschungszweige nicht mehr relevant sein und verschwinden, aber die ganz großen Fragen bleiben meist vollständig beantwortet.</p>
<p>In <a href="#fig-flammarion">Abbildung&nbsp;<span>3.2</span></a> sehen wir den Menschen der hinter das Himmelszelt schaut auf der Suche zu Verstehen wie die Himmelmechanik funktioniert. Dieses Bild von 1888 soll das mittelalterliche Weltbild symbolisieren. Der unbekannte Künstler zeigt in dem Holzstich die Suche des Menschen nach der Mechanik hinter der Welt. Die Welt folgt Regeln und diese Regeln sind zu entdecken. Damit sind diese Regeln auch determiniert bzw. besiegelt. Nun wissen wir aber aus unserer heutigen Weltsicht, dass dieses Weltbild nicht stimmt.</p>
<div id="fig-flammarion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/flammarion.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.2— Der Mensch auf der Suche nach neuen Erkenntnissen durchstößt den Horizont und entdeckt die dahinterliegenden Gesetze.</figcaption></figure>
</div>
<p>In der <a href="#tbl-kraenkung">Tabelle&nbsp;<span>3.2</span></a> sind als Auswahl vier <a href="https://de.wikipedia.org/wiki/Kr%C3%A4nkungen_der_Menschheit">Kränkungen der Menschheit</a> dargestellt. Es gibt je nach Aufzählung mal mehr oder weniger Kränkungen. Allen Kränkungen ist aber gemein, dass sie den Selbst- und Weltbezug der Menschen fundamental geändert haben. Jede dieser Kränkungen sorgte für einen Paradigmenwechsel in den folgenden Generationen. Nach diesen Entdeckungen war die Welt für die Menschen nicht mehr so, wie die Welt vor der Entdeckung war. In der Forschung werden diese Entdeckungen auch Kränkungen genannt, da sie den Menschen von dem Thron der Schöpfung stoßen und der Menschheit den Status der Ausgewähltheit nehmen. Am Ende sind wir dann doch nur felllose Trockennasenaffen, die auf einem x-beliebigen felsigen Planten im nirgendwo umtreiben.</p>
<div id="tbl-kraenkung" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;3.2— Die vier Kränkungen der Menschheit. Je nach Quelle sind es auch drei oder eben mehr.</caption>
<thead><tr class="header">
<th>Art der Kränkung</th>
<th>Quelle</th>
<th>Beschreibung</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>kosmologisch</td>
<td>
<a href="https://de.wikipedia.org/wiki/Kopernikus">Kopernikus</a> (1543)</td>
<td>Die Erde und damit auch der Mensch ist nicht Mittelpunkt der Welt.</td>
</tr>
<tr class="even">
<td>biologisch</td>
<td>
<a href="https://de.wikipedia.org/wiki/Charles_Darwin">Darwin</a> (1859)</td>
<td>Die Menschheit ist in das Entwicklungssystem der Organismen eingegliedert.</td>
</tr>
<tr class="odd">
<td>psychologisch</td>
<td>
<a href="https://de.wikipedia.org/wiki/Sigmund_Freud">Freud</a> (1895)</td>
<td>Der Mensch ist noch nicht Herr der eigenen Handlungen, sondern wird (vermutlich) vom Unbewussten gelenkt.</td>
</tr>
<tr class="even">
<td>ethologisch</td>
<td>
<a href="https://de.wikipedia.org/wiki/Oskar_Heinroth" title="Oskar Heinroth">Heinroth</a> 1910</td>
<td>Nicht nur unser Körperbau, sondern auch unser Verhalten ist aus dem Tierreich hervorgegangen.</td>
</tr>
</tbody>
</table>
</div>
<p>In den folgenden Abschnitten gehen wir auf die vier hier vorgestellten Kränkungen der Menschheit ein. Wir schauen uns an, was die Begleitumstände der Entdeckungen waren und wie sich die wissenschaftlichen Erkenntnisse einordnen lassen. Nach dem Motto ‘Was ist Wasser?’ schauen wir uns die verschiedenen Denkschulen und wissenschaftlichen Ideen einmal näher an. Was die endgültige Wahrheit ist, werden wir aber in der Folge nicht herausfinden können.</p>
<section id="logik" class="level3" data-number="3.2.1"><h3 data-number="3.2.1" class="anchored" data-anchor-id="logik">
<span class="header-section-number">3.2.1</span> Logik</h3>
<blockquote class="blockquote">
<p><em>“Alles was ich kenne, ist Logik.” — Commander Spock</em></p>
</blockquote>
<p>Wenn wir an Logik denken, dann kommt uns vermutlich als griechischer Vertreter Aristoteles (384–322 v. Chr.) in den Sinn. Wenn ich an Logik denke, dann habe ich Commander Spock (2230–2263 n.&nbsp;Chr.) und Commander Data (2338–2379 n.&nbsp;Chr.) vor den Augen, aber das ist ja popkulturell immer etwas unterschiedlich. Allgemein gesprochen, hat Logik nichts mit Gefühlen zu tun. Demnach wird logischen Argumenten auch die Emotion oder Empathie abgesprochen. Prinzipiell muss ein logischer Schluss nicht empathielos sein, da ein logischer Schluss aber ein allgemeingültige Aussage im Sinn hat, ist wenig Platz für das Individuum. Zwei zentrale Ideen der Logik sind dabei die Deduktion und Induktion. Beide Verfahren sind miteinander verwoben, was du nochmal in der <a href="#fig-logic-01">Abbildung&nbsp;<span>3.3</span></a> nachvollziehen kannst.</p>
<div id="fig-logic-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/preface_logic_01.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.3— Eine vereinfachenden Übersicht über Deduktion und Induktion. In der Empirie werden Daten aus Einzelfällen erhoben. Aus diesen wird dann per Induktion eine allgemeine Theorie gewonnen. Aus der Theorie wiederum können per Deduktion Aussagen über Einzelfälle in der Empirie gewonnen werden.</figcaption></figure>
</div>
<p>Betrachten wir nun als erstes die Deduktion. Die Deduktion ist ein logischer Denkprozess, bei dem spezifische Schlussfolgerungen aus allgemeinen Aussagen gezogen werden. In der Deduktion geht es darum, von bereits bekannten Informationen auf neue Erkenntnisse zu schließen. Dieser Prozess basiert auf der Anwendung von logischen Regeln. Ein klassisches Beispiel für die Deduktion ist das so genannte Syllogismus-Argument:</p>
<ul>
<li>
<em>Allgemeine Aussage:</em> Alle Menschen sind sterblich.</li>
<li>
<em>Spezifische Aussage:</em> Sokrates ist ein Mensch.</li>
<li>
<em>Schlussfolgerung:</em> Daher ist Sokrates sterblich.</li>
</ul>
<p>Im Kontrast dazu steht die Induktion. Die Induktion ist ein logischer Denkprozess, bei dem allgemeine Aussagen aufgrund spezifischer Beobachtungen oder Erfahrungen abgeleitet werden. Induktives Denken basiert auf der Annahme, dass wiederholte Beobachtungen oder Erfahrungen auf allgemeine Muster oder Prinzipien hindeuten. Ein Beispiel für induktives Denken ist folgendes:</p>
<ul>
<li>
<em>Beobachtung:</em> Jedes Mal, wenn ich einen Apfel fallen lasse, fällt er auf den Boden.</li>
<li>
<em>Beobachtung:</em> Jedes Mal, wenn meine Freunde einen Apfel fallen lassen, fällt er auf den Boden.</li>
<li>
<em>Beobachtung:</em> Jedes Mal, wenn Menschen auf der ganzen Welt einen Apfel fallen lassen, fällt er auf den Boden.</li>
<li>
<em>Schlussfolgerung:</em> Daher schließe ich, dass alle Objekte, die fallen gelassen werden, auf den Boden fallen.</li>
</ul>
<p>Es ist wichtig anzumerken, dass Induktion aufgrund der begrenzten Beobachtungen oder Erfahrungen immer zu gewissen Unsicherheiten führt. Eine Schlussfolgerung aufgrund induktiven Denkens kann immer widerlegt werden, wenn neue Beobachtungen oder Erfahrungen gemacht werden.</p>
<p>Zusammenfassend kann man sagen, dass Deduktion von Allgemeinem auf Spezifisches schließt, während Induktion von Spezifischem auf Allgemeines schließt. Deduktion bietet gewöhnlich eine hohe Gewissheit, während Induktion zu wahrscheinlichen Schlussfolgerungen führt, aber nicht notwendigerweise zu absoluten Wahrheiten. Die Deduktion und Induktion sind somit zwei grundlegende Methoden des logischen Denkens und des wissenschaftlichen Untersuchens. Sie werden in verschiedenen Bereichen der Philosophie, Mathematik, Logik und Wissenschaft angewendet.</p>
</section><section id="determinismus" class="level3 page-columns page-full" data-number="3.2.2"><h3 data-number="3.2.2" class="anchored" data-anchor-id="determinismus">
<span class="header-section-number">3.2.2</span> Determinismus</h3>
<blockquote class="blockquote">
<p><em>“Alles ist bestimmt, der Anfang wie das Ende, durch Kräfte, über die wir keine Kontrolle haben. Es ist sowohl für das Insekt als auch für den Stern bestimmt. Ob Mensch, Gemüse oder kosmischer Staub, wir alle tanzen nach einer geheimnisvollen Melodie, die in der Ferne von einem unsichtbaren Pfeifer intoniert wird.” — Albert Einstein</em></p>
</blockquote>
<p>Ist das Universum determiniert (lat. <em>vorbestimmt</em>) und lassen sich alle Ereignisse in der Vergangenheit und der Zukunft nach den Gesetzen der Physik vorhersagen? Wir haben die Logik der alten Griechen von unter anderem Aristoteles verstanden. Wir können über Deduktion und Induktion logische Schlüsse über die Welt um uns herum ziehen. Damit können wir durch das logische Verknüpfen von Aussagen zu allgemeinen Erkenntnissen gelangen. Nun fragen wir uns wie die Welt funktioniert.Damit sollte sich doch logisch die Realität und deren Gesetzte erklären lassen. Das hat sich auch Pierre-Simon Laplace (1749–1827) gedacht und kommt zu folgenden Schluss über die Welt.</p>
<blockquote class="blockquote">
<p><em>“Wir müssen also den gegenwärtigen Zustand des Universums als Folge eines früheren Zustandes ansehen und als Ursache des Zustandes, der danach kommt. Eine Intelligenz, die in einem gegebenen Augenblick alle Kräfte kennt, mit denen die Welt begabt ist, und die gegenwärtige Lage der Gebilde, die sie zusammensetzen, und die überdies umfassend genug wäre, diese Kenntnisse der Analyse zu unterwerfen, würde in der gleichen Formel die Bewegungen der größten Himmelskörper und die des leichtesten Atoms einbegreifen. Nichts wäre für sie ungewiss, Zukunft und Vergangenheit lägen klar vor ihren Augen.” — Pierre-Simon Laplace</em></p>
</blockquote>
<p>Nach dieser Aussage wäre es theoretisch möglich, eine Weltformel aufzustellen. Wir nennen diese Veranschaulichung auch den <a href="https://de.wikipedia.org/wiki/Laplacescher_D%C3%A4mon">Laplaceschen Dämon</a>. Der Laplaceschen Dämon ist die Veranschaulichung der erkenntnis- und wissenschaftstheoretischen Auffassung, nach der es im Sinne der Vorstellung eines geschlossenen mathematischen Weltgleichungssystems möglich ist. Grundlage dieses Gedankens ist der Gesetzesdeterminismus. Das Universum gleiche einem logischen Uhrwerk; eine Intelligenz habe das Universum mit seinen Gesetzen so geschaffen, wie ein Uhrmacher die perfekte Uhr bauen würde.</p>
<p>Ein ein Beispiel für den Determinismus wollen wir uns einmal unser Sonnensystem anschauen. Der Aufbau unseres Sonnensystems war ja Jahrtausende unbekannt. Wir wollen die flache Erde gleich hinter uns lassen und betrachten den Globus Erde im Planetensystem. Die ersten Theorien setzten die Erde in den Mittelpunkt. In <a href="#fig-deter-01">Abbildung&nbsp;<span>3.4</span></a> sehen wir einmal das sehr vereinfachte geozentrische Weltbild (altgriechisch <em>erdzentriert</em>), welches auf der Annahme basiert, dass die Erde und damit auch der Mensch im Universum eine zentrale Position einnehmen, so dass alle Himmelskörper, wie Mond, Sonne, die anderen Planeten und die Fixsterne, die Erde umkreisen.</p>
<div id="fig-deter-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/preface_deter_01.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.4— Geozentrische Darstellung des Sonnensystems mit der Erde im Zentrum und Planeten auf kreisförmigen Umlaufbahnen. Um 1540 entwarf Kopernikus die Idee des heliozentrische Weltbild mit der Sonne im Mittelpunkt. Erst um 1600 beschrieb Keppler die eliptischen Umlaufbahnen um die Sonne und ab 1821 wurde die Sonne nicht mehr als bewohnbaren Planet oder ‘terrestrische’ Sonne gesehen.</figcaption></figure>
</div>
<p>Das geozentrische Weltbild entspricht dem unmittelbaren Augenschein und wurde schon im klassischen Altertum in Griechenland, insbesondere bei Aristoteles, detailliert ausgearbeitet. Genauso wie die Flache Erde dem Augenschein entspricht. Das geozentrische Weltbild ist somit auch wesentlich besser mit dem gesunden Menschenverstand übereinzustimmen als eine sich bewegende Erde. Bei der Bewegung der Erde müsste man doch einen Fahrtwind spüren und fallenden Gegenstände eine schräge Bahn besitzen.</p>
<p>Koperinikus (1473–1543) und Kepler (1571–1630) haben die gängigen Ansichten über die Realität hinterfragt und versucht die Unstimmigkeiten in den Beobachtungen am Sternenhimmel durch ein besseres Modell der Wirklichkeit zu ersetzen. Dies gelang beiden auch bis zu einem Punkt. Zusammen mit der Gravitationstheorie von Newton konnte ein schlüssiges Modell des Sonnensystems erstellt werden. Es gab zwar noch ein paar Fragen, aber hier können wir einmal Philipp von Jolly (1809–1884) zitieren der dem jungen Max Planck (1858–1947) folgenden Rat mitgab.</p>
<blockquote class="blockquote">
<p><em>“Die Physik ist eine hochentwickelte, nahezu voll ausgereifte Wissenschaft, die nunmehr, nachdem ihr durch die Entdeckung der Energie gewissermaßen die Krone aufgesetzt wurde, wohl bald ihre endgültige stabile Form annehmen wird. Wohl gibt es vielleicht in einem oder dem anderen Winkel noch ein Stäubchen oder ein Bläschen zu prüfen und einzuordnen, aber das System als Ganzes steht ziemlich gesichert da, und die Theoretische Physik nähert sich merklich demjenigen Grade der Vollendung, wie ihn etwa die Geometrie schon seit Jahrhunderten besitzt.” – Philipp von Jolly zum jungen Max Planck 1874 <span class="citation" data-cites="ecker2017teilchen">(<a href="#ref-ecker2017teilchen" role="doc-biblioref">Ecker 2017</a>)</span></em></p>
</blockquote>
<p>Eine der Fragen, die Newotn nicht beantworten konnte, war die Frage nach der Übertragung der Information der Gravitation? Wenn die Gravitation eine Kraft ist, wie wird die Kraft übertragen. Wie weiß die Erde und der Mond, dass beide da sind? Woher weiß die Erde von der Graviation der Sonne? Wie wird die Kraft übertragen? Darüber hinaus stellte man noch eine andere zu beobachtende Anomalie fest. Diese Anomalie war nicht wegzudiskutieren, weil messbar. Im 19. Jahrhundert stellte man bei Bahnbeobachtungen des Merkur fest, dass seine tatsächliche Umlaufbahn von der Form einer Kepler-Ellipse abweicht. Der Fehler konnte mit verbesserter Teleskopen auf 43 Bogensekunden von 3600 Bogensekunden pro Jahrhundert reduziert werden. Somit ergab sich eine Abweichung von <span class="math inline">\(43/3600 = 0.012 = 1.2\%\)</span>. Auch wenn dieser Betrag sehr klein ist, bleibt das Ergebnis unvereinbar mit der Himmelsmechanik nach Isaac Newton (1642–1726).</p>
<div id="fig-deter-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/planet_vulkan.jpeg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.5— Um die Abweichung der Umlaufbahn des Merkurs durch das Modell nach Newton zu erklären, wurde der Planet Vulkan als Hypothese in den wissenschaftlichen Diskurs gebracht. Quelle: Lith. of E. Jones &amp; G.W. Newman - Library of Congress. https://www.loc.gov/resource/g3180.ct003790</figcaption></figure>
</div>
<p>Erst mit der allgemeinen Relativitätstheorie von Albert Einstein (1879–1955) war die Abweichung der Merkurlaufbahn hinreichend erklärbar. Massereiche Objekte krümmen die Raumzeit. Objekte laufen auf Bahnen entlang der gekrümmten Raumzeit und beeinflussen sich so gegenseitig. Es ist keine Kraft, die an den Objekten zieht sondern die Krümmung des Raums, welches Objekte beeinflusst. Somit war die theoretische Physik an einem Scheitelpunkt angekommen. Würde sich jetzt die Aussage von Philipp von Jolly erfüllen und alles wäre erklärt? Wie sich herausstellte gab es neben dem ganz Großen und deren Wechselwirkungen, den Planetenbewegungen und Objekten auf der Erde, noch die atomaren Wechselwirkungen. Die Effekte von Protonen auf Elektronen und das Verhalten von Atomkernen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Zum Nachdenken I: <em>Heisenberg und seine Unschärferelation</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="fig-math-cartoon" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/heisenberg_1.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.6— Warum ist der Cartoon witzig im Bezug auf Heisenberg und seine Unschärferelation? Was lernen wir aus dem Cartoon für die praktische Anwendung? Quelle: https://www.martin-perscheid.de/</figcaption></figure>
</div>
</div>
</div>
</div>
<p>Dann kam Werner Heisenberg (1901–1976) und formulierte 1927 die Heisenbergsche Unschärferelation, ein fundamentales Prinzip der Quantenmechanik. Die Heisenbergsche Unschärferelation besagt, dass zwei komplementäre Eigenschaften eines Teilchens nicht gleichzeitig beliebig genau bestimmbar sind. Die heisenbergsche Unschärferelation kann als Ausdruck des Wellencharakters der Materie betrachtet werden. Es herrscht ein Wellen-Teilchen-Dualismus vor. Wir können Elektronen oder Photonen als Welle oder aber als ein Teilchen beschrieben. Somit unterscheidet sich der konzeptionelle Aufbau der Quantenmechanik tiefgreifend von dem der klassischen Physik, so dass sich Einstein zu folgender Aussage hinreißen lies.</p>
<blockquote class="blockquote">
<p><em>“Gott würfelt nicht!” — Albert Einstein</em></p>
</blockquote>
<p>Bis zu seinem Tod stand Einstein mit der Quantentheorie und der statistischen Physik von Heisenberg und Co.&nbsp;im Zwiespalt. Die Idee, dass es zwei Modelle geben könnte, eines für die makroskopische Welt und eines für die atomare Welt, blieb für Einstein unbefriedigend. Wenn das kleinste Atom den Regeln des Zufalls folgt, dann kann es kein Weltengesetz nach Laplace geben. Wie soll etwas im Großen determiniert sein, wenn es im Kleinsten seines Aufbaues dem Zufall folgt? Hier ist die physikalische Forschung seit über einem Jahrhundert auf der Suche nach der Weltenformel, die die Quantenmeachnik mit der Gravitation zusammenbringt. So enden wir diesen Abschnitt mit dem 1. clarkschen Gesetz.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><a href="https://www.spektrum.de/kolumne/die-unschaerferelation-ist-eine-eigenschaft-der-fourier-transformation/2146671">Die Unschärferelation gilt nicht nur in der Quantenwelt</a>. Ort und Geschwindigkeit eines Elektrons lassen sich nicht gleichzeitig genau bestimmen. Doch auch in praktischen Bereichen wie Radarmessungen und Blitzern stößt man auf die Unschärferelation.</p>
</div></div><blockquote class="blockquote">
<p><em>“Wenn ein angesehener, aber älterer Wissenschaftler behauptet, dass etwas möglich ist, hat er mit an Sicherheit grenzender Wahrscheinlichkeit recht. Wenn er behauptet, dass etwas unmöglich ist, hat er höchstwahrscheinlich unrecht.” — Arthur C. Clarke, 1. Gesetz</em></p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Zum Nachdenken II: <em>Der Dopplereffekt</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="fig-math-cartoon-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/heisenberg_2.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.7— Warum ist der Cartoon witzig im Bezug auf den Dopplereffekt und der konstanten Lichtgeschwindigkeit? Was lernen wir aus dem Cartoon für die praktische Anwendung? Quelle: https://www.martin-perscheid.de/</figcaption></figure>
</div>
<div id="fig-math-cartoon-03" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/licht.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.8— Spektrum des sichtbaren Lichts un der Wellenlänge des Lichts.</figcaption></figure>
</div>
<p>Mehr Informationen zum <a href="https://en.wikipedia.org/wiki/Doppler_effect#Applications">Dopplereffekt und deren Anwendungen auf Wikipedia</a> und ein toller Artikel, der nochmal anders ins Detail geht sowie auf Deutsch ist, ist die Seite zu Christian Doppler <a href="https://www.christian-doppler.net/dopplereffekt/">https://www.christian-doppler.net/</a></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Zum Nachdenken III: <em>Warum ist es nachts dunkel?</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="https://www.weltderphysik.de/thema/hinter-den-dingen/dunkle-nacht/">Welt der Physik - Warum ist es nachts dunkel?</a></p>
<p><a href="https://www.christian-doppler.net/dopplereffekt/">Spektrum - Warum ist es nachts dunkel?</a></p>
</div>
</div>
</div>
</section></section><section id="eine-neue-physikalische-theorie-des-lebens" class="level2 page-columns page-full" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="eine-neue-physikalische-theorie-des-lebens">
<span class="header-section-number">3.3</span> Eine neue physikalische Theorie des Lebens</h2>
<blockquote class="blockquote">
<p><em>“Die Wissenschaft fängt eigentlich erst da an interessant zu werden, wo sie aufhört.” — Justus von Liebig</em></p>
</blockquote>
<p>Warum vergeht eigentlich Zeit? Was ist eigentlich Zeit? Und warum haben wir eigentlich Uhren, die auf einem 12er Zählung bzw. auf einer <a href="https://de.wikipedia.org/wiki/2-mal-12-Stunden-Z%C3%A4hlung">2-mal-12-Stunden-Zählung</a> und dann auf einer 60ziger Zählung beruhen? Zuerst klären wir einmal diese komische Anonmalie. Wir haben ein60ziger System, da die alten Griechen es von den Ägyptern und diese wiederum von den Babylonier übernommen haben. Die 12 ist eine sehr spannende Zahl und hat viele Teiler, so dass mathematisch interessierte Babylonier die 12 höher werteten als die 10. Niemand wusste ja, dass wir mal mit dem Unsinn programmieren würden wollen. Zwar gab es dann kurz den versuch die Zeit auf die <a href="https://de.wikipedia.org/wiki/Dezimalzeit">Dezimalzeit</a> umzustellen und es wurde im Rahmen der französichen Revolution auch ein neuer <a href="https://de.wikipedia.org/wiki/Franz%C3%B6sischer_Revolutionskalender">Französischer Revolutionskalender</a> erstellt, aber die Sache hat sich dann nicht so durchgesetzt. Zeit selber spielt übrigens erst seit der Erfindung der Eisenbahn eine echte Rolle. Vorher war es recht egal, wie <em>genau</em> die Uhren in der einen Stadt im Bezug zur anderen Stadt liefen. Man war ja eine ganz schön lange Zeit unterwegs, so dass Abweichungen nun auch keine Rolle mehr spielten.</p>
<p>Aber warum schreitet die Zeit eigentlich voran? Also warum gibt es ein gestern, heute und morgen? Dabei sind doch alle Naturgesetze in der klassischen Physik in der Zeit symmetrisch. Die Zeit ist auch symmetrisch im Bereich der neueren Entwicklungen wie der Relativitätstheorie als auch der Quantenphysik. Wir können also die Zeit in die eine Richtung laufen lassen wie auch in die andere Richtung. Daher gibt es eigentlich keinen physikalischen Grund, warum die Zeit immer nur in eine Richtung fortschreiten sollte. Es könnte also auch die Zeit rückwärts laufen. Der Tee und die Milch könnte sich in der Tasse der Queen wieder entmischen. Das passiert aber nicht.</p>
<p>Ein einziges Naturgesetz ist daran schuld und zwar der <a href="https://de.wikipedia.org/wiki/Zweiter_Hauptsatz_der_Thermodynamik">Zweite Hauptsatz der Thermodynamik</a>. Der Zweite Hauptsatz der Thermodynamik besagt, dass alle Vorgänge immer nur so ablaufen, dass dabei die “Unordnung” größer und niemals kleiner werden wird. Leider ist der Begriff “Unordnung” physikalisch wissenschaftlich schwer zu definieren. Unordnung ist ein sehr weiter Begriff und vieles kann Unordnung bedeuten. Hier kommt es dann acuh stark auf den Kontext an. Deshalb haben Physiker dafür das Wort <em>Entropie</em> erschaffen. Daher ist es die stets wachsende Entropie, die der Zeit einen eindeutigen Richtungspfeil aufzwingt. So kommen wir dann zu diesem Zitat von Rudolf Clausius (1822–1888), dem Entdecker des zweiten Hauptsatzes der Thermodynamik, Schöpfer der Begriffe Entropie.</p>
<blockquote class="blockquote">
<p><em>“Bei jedem natürlichen Vorgang nimmt die Entropie zu.” — Rudolf Clausius</em></p>
</blockquote>
<p>Die Entropie steigt also immer weiter an. Damit stehen wir aber vor einer interessanten Frage, wenn natürliche Vorgänge stets einen Ausgang mit höherer Entropie als der Eingangszustand bevorzugen, warum gibt es dann komplexes Leben? Wieso haben sich Makromoleküle als Grundlage des Lebens in der Ursuppe der Urerde gebildet, wenn es doch der Zunahme der Entropie widerspricht. Hier kommt die Idee von Jeremy <span class="citation" data-cites="england2013statistical">England (<a href="#ref-england2013statistical" role="doc-biblioref">2013</a>)</span> ins Spiel. Folgendes Zitat statt aus seiner wissenschaftlichen Arbeit zur einer neuen physikalische Theorie des Lebens.</p>
<blockquote class="blockquote">
<p><em>“You start with a random clump of atoms, and if you shine light on it for long enough, it should not be so surprising that you get a plant.” — Jeremy England</em></p>
</blockquote>

<div class="no-row-height column-margin column-container"><div class="">
<p>Noch ein ergänzender Artikel des The Quanta Magazine <a href="https://www.quantamagazine.org/a-new-thermodynamics-theory-of-the-origin-of-life-20140122/">A New Physics Theory of Life</a> und das <a href="https://www.englandlab.com/uploads/7/8/0/3/7803054/2013jcpsrep.pdf">PDF des Orginalartikels</a>. Sowie der Vortrags von Jeremy England <img src="images/youtube.png" class="img-fluid" data-fig-align="center" width="50"><span class="math inline">\(\;\)</span><a href="https://youtu.be/10cVVHKCRWw">No Turning Back: The Nonequilibrium Statistical Thermodynamics of becoming (and remaining) Life-Like</a></p>
</div></div><p>Die Idee von Jeremy England ist, dass wir durch kurzfristige <em>Erniedrigung</em> der Entropie durch komplexe Strukturen wie sie das Leben hervorbringt, langfristig ein sehr viel schnellere Erhöhung der Entropie erreichen. Das heißt im Umkehrschluss, dass der zweiten Hauptsatzes der Thermodynamik Leben und komplexere Lebensformen begünstigt. Jeremy England gibt ein Beispiel mit energiegeladenen Photonen, die von der Sonne abgestrahlt werden. In der <a href="#fig-england-01">Abbildung&nbsp;<span>3.9</span></a> siehst du, wie die energiegeladenen Photonen als kurzwelliges blaues Licht einen belebten Planeten treffen. Durch das Leben wird die Energie der Photonen durch Photosynthese sowie andere biologische Prozesse absorbieren. Bei den biologischen Prozessen entstehen jedoch mehr langwellige Photonen als kurzwellige auf den Planeten treffen, so dass in Summe zwanzig energiearme Photonen pro energiereichen Proton als langwelliges rotes Licht die Erde verlassen.</p>
<div id="fig-england-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/preface_england_01.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.9— Ein energiereichen, kurzwelliges Photon trifft die Erde und durch Prozesse des Lebens werden zwanzig energiearme, langwellige Photonen abgestrahlt. Die Entropie erhöht sich stark.</figcaption></figure>
</div>
<p>In <a href="#fig-england-02">Abbildung&nbsp;<span>3.10</span></a> siehst du als Gegenbeispiel einen unbelebten Planeten, der von einem Stern angestrahlt wird. Zwar werden auch die hochenergetischen Photonen des Sterns von dem unbelebten Planeten absorbiert und wieder abgestrahlt, aber die Umwandlung ist weit unter dem Wert, die ein belebter Planet verursachen würde.</p>
<div id="fig-england-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/preface_england_02.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.10— Ein energiereichen, kurzwelliges Photon trifft einen unbelebten Planten und kurzwellige Photonen werden wiederum abgestrahlt. Die Entropie erhöht sich kaum.</figcaption></figure>
</div>
<p><img src="images/youtube.png" class="img-fluid" data-fig-align="center" width="50"><span class="math inline">\(\;\)</span><a href="https://youtu.be/DxL2HoqLbyA">The Most Misunderstood Concept in Physics</a></p>
<section id="evolutionstheorie" class="level3 page-columns page-full" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="evolutionstheorie">
<span class="header-section-number">3.3.1</span> Evolutionstheorie</h3>
<blockquote class="blockquote">
<p><em>“It is not the strongest of the species that survives, nor the most intelligent that survives. It is the one that is most adaptable to change.” — Leon C. Megginson zugeschrieben Charles Darwin</em></p>
</blockquote>
<p>Würmer. Konkreter waren es das der Feld der Regenwürmer was Darwin am meisten beschäftige und Jahrzehnte seiner Forschung bestimmte. Anfang des 19. Jahrhunderts galten Regenwürmer als Schädlinge insbesondere außerhalb der Agrarwissenschaft. Darwins genaue Beobachtungen ihrer Lebensweise sowie seine Experimente über ihr Hörvermögen, ihre Lichtempfindlichkeit, ihr Kälte- und Wärmeempfinden und die Tätigkeit ihrer Reflexe führten dazu, dass sich das Wissen um die Nützlichkeit von Regenwürmern für den Ackerbau rasch verbreitete und auch außerhalb von Fachkreisen durchsetzte.</p>
<p>Darwin entwickelte die Evolutionstheorie während seiner Fahrt mit dem Segelschiff Beagle, die von Ende Dezember 1831 bis Oktober 1836 dauerte und ihn zu Küstenregionen und Inseln der südlichen Erdhalbkugel führte. An Bord der Beagle war Darwin als unbezahlter Naturforscher tätig. Darwin präsentierte erstmals eine frühe Version seiner Evolutionstheorie im Jahr 1858. Das Buch, in dem er seine Theorie ausführlich darlegte, “On the Origin of Species by Means of Natural Selection”, wurde 1859 veröffentlicht und war am Tag seines Erscheinens ausverkauft. Darwin betonte, dass Selektion ein entscheidender Faktor bei der Evolution ist. Obwohl zu Darwins Zeiten nur begrenzte genetische Kenntnisse vorhanden waren, erkannte Darwin die Zusammenhänge, die er auf seinen Reisen beobachtete, richtig.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die <a href="https://en.wikipedia.org/wiki/Bone_Wars">Bone Wars</a> war eine persönliche und wissenschaftliche Auseinandersetzung der beiden US-amerikanischen Paläontologen Othniel Charles Marsh und Edward Drinker Cope gegen Ende des 19. Jahrhunderts.</p>
</div></div><p>Im Gegensatz zu den Theorien Darwins, stelle Lamarck eine andere Evolutionstheorie auf. Der nach ihm benannte Lamarckismus war eine der frühen Evolutionstheorien um 1800. Der Lamarckismus besagt dabei, dass jede Art eine eigne Urform besitzt und dass diese Urform den Drang hat, sich möglichst perfekt anzupassen. Jede Art hat also einen innewohnenden Hang zum Perfektionismus. Dabei beeinflussen sich die ändernden Umweltbedingungen und die wechselnden Bedürfnisse der Tiere gegenseitig. Dadurch führt der Gebrauch bestimmter Organe zu ihrer Ausprägung, während der Nichtgebrauch bestimmter Organe zu ihrer Rückbildung führt. Diese erworbenen Eigenschaften werden dann an die Nachkommen weitervererbt. Beim Lamarckismus ist die Entwicklung gerichtet, und Arten entwickeln sich von einfachen zu komplexen Organismen. Jede Art hat eine eigene lineare Evolutionslinie und keinen gemeinsamen Vorfahren. Ein bedeutendes Problem zur Zeit von Lamarck war die Frage nach dem möglichen Aussterben von Arten. Die Frage kam auf als immer mehr Funde von Fossilien auftauchten, die keinen heutigen Tieren zugeordnet werden konnten. Lamarck bestritt jedoch weitgehend, dass Arten aussterben können. Die Fossilien seien vielmehr Ausprägungen einer bekannten Tierart, die jetzt nicht mehr existieren, da die Ausprägung nicht mehr notwendig ist.</p>
<p>Der Lamarckismus basiert auf einer willentlichen Ausübung der Evolution. Damit ist die Evolution von der Spezies gesteuert. Wir haben hier also wieder den Gedanken des Determinismus vorliegen. Das Schicksal einer Spezies ist in dem Sinn determiniert, dass es nur von einfach zu komplex geht und eine Spezies immer perfekter wird. Der Paradigmenwechsel von Darwin war die Idee, dass wir es mit Populationen von Arten zu tun haben und in diesen Population alle möglichen Eigenschaften schon in sich tragen. Die Populationen folgen einer Wahrscheinlichkeitsverteilung. Es gibt sehr viele Individuen mit den häufisgten Merkmalen aber auch ein paar wenige Individuen mit den seltenen Merkmalen. So kann es durch Naturereignisse, Zufälle oder anderer Ereignisse zu einer Selektion kommen. Durch die Selektion setzen sich vorher seltene Merkmale durch und die Merkmalsträger werden häufiger in der Population.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Zum Nachdenken IV: <em>Die Weltenveränderer</em>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die <a href="https://de.wikipedia.org/wiki/Gro%C3%9Fe_Sauerstoffkatastrophe">Große Sauerstoffkatastrophe</a> (abk. <em>GOE</em>, eng. <em>great oxygenation event</em>) veränderte die Welt vor etwa 2,4 Milliarden Jahren grundlegend. Der Verursacher war eine Alge. Konkret die Blaualge. Somit spielt die Blaualge eine bedeutende Rolle in der Entwicklung des Lebens auf der Erde. Vor dem Auftreten der Blaualge war die Atmosphäre der Erde reduzierend, nach dem Auftreten der Blaualge oxidierend. Die <a href="https://de.wikipedia.org/wiki/Entwicklung_der_Erdatmosph%C3%A4re">Entwicklung der Erdatmosphäre</a> machte einen erneuten Sprung. Große Mengen an Eisen oxidierten und sammelten sich in so genannten <a href="https://de.wikipedia.org/wiki/B%C3%A4ndererz">Bändererzen</a>.</p>
<p>Im Weiteren Verlauf der Evolution wurde die Blaualge in andere Organismen aufgenommen. Dieses Integrieren ist die Idee der <a href="https://de.wikipedia.org/wiki/Endosymbiontentheorie">Endosymbiontentheorie</a>. Die Endosymbiontentheorie besagt, dass die Chloroplasten in pflanzlichen Lebewesen vermutlich durch die Aufnahme durch Phagozytose von Cyanobakterien in die Ur-Form der pflanzlichen Zelle entstanden sind. Dafür spricht unter anderem die eigene DNA der Chloroplasten. Das gleiche gilt auch für die Mitochondrien in eukaryotischen Zellen.</p>
<p>Siehe dazu auch die <a href="https://de.wikibooks.org/wiki/Cyanobakterien:_Bedeutung_der_Cyanobakterien_f%C3%BCr_die_Entwicklung_des_irdischen_Lebens">Cyanobakterien oder Blaualgen: Bedeutung der Cyanobakterien für die Entwicklung des irdischen Lebens</a>.</p>
</div>
</div>
</div>
</section><section id="wiener-schule" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="wiener-schule">
<span class="header-section-number">3.3.2</span> Wiener Schule</h3>
<blockquote class="blockquote">
<p><em>“Wenn dich etwas Äußeres bedrückt, so liegt der Schmerz nicht an der Sache selbst, sondern an deiner Einschätzung derselben; und diese kannst du jederzeit widerrufen.” — Marcus Aurelius</em></p>
</blockquote>
<p>Der gute alte Determinismus, leider funktioniert der Determinismus nicht auf der Ebene des Universums und der physikalischen Naturgesetze. Aber vielleicht haben wir ja eine Chance, wenn wir uns auf das Gebiet der Psychologie begeben? Vielleicht ist der Mensch ja selber ein Getriebener von vorbestimmten psychologischen Abläufen. Das ist nämlich die nächste Kränkung der Menschheit. Sigmund Freud (1856—1939) sagt, dass der Mensch ist noch nicht Herr der eigenen Handlungen, sondern wird vermutlich vom Unbewussten gelenkt. Für mich ist der eigentliche Witz hier, dass wir mit Freud dann wieder zu dem Determinismus zurückkehren. Hat es nicht etwas befreiendes, dass man selber nur Opfer des eigenen Unbewussten ist? Alles Schlechte und alle Gewohnheiten sind gar nicht unter meiner direkten Kontrolle und so kann ich doch auch gar nichts dagegen tun.</p>
<p>Freud ist aber nur <em>ein</em> Vertreter der Wiener Schule der Psychologie, die Dann vielleicht im Schauen wir uns den nächsten Paradigmenwechsel einmal an.</p>
<ul>
<li>die <a href="https://de.wikipedia.org/wiki/Psychoanalyse">Psychoanalyse</a> nach Sigmund Freud (1856—1939),</li>
<li>die <a href="https://de.wikipedia.org/wiki/Individualpsychologie">Individualpsychologie</a> nach Alfred Adler (1870–1937)</li>
<li>die <a href="https://de.wikipedia.org/wiki/Logotherapie_und_Existenzanalyse">Existenzanalyse</a> von Viktor Frankl (1905–1997)</li>
</ul>
<div id="fig-adler-dreieck" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/adler_dreieck.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.11— Das Entscheidungsdreieck nach Adler: “Das arme Ich”, “Die bösen Anderen” und “Was sollte ich tun?”</figcaption></figure>
</div>
<p><a href="https://de.wikipedia.org/wiki/Viktor_Frankl">Viktor Frankl</a> <span class="citation" data-cites="frankl2010trotzdem">Frankl (<a href="#ref-frankl2010trotzdem" role="doc-biblioref">2010</a>)</span></p>
<p>Eines seiner bekanntesten Werke ist das im Jahr 1946 erschienene trotzdem Ja zum Leben sagen: Ein Psychologe erlebt das Konzentrationslager, in dem Frankl seine Erlebnisse und Erfahrungen in vier verschiedenen Konzentrationslagern</p>
<p>Das Arme ich was sollte ich tun</p>
<p>(Zitate aus dem Buch du bist gut genug?)</p>
<blockquote class="blockquote">
<p><em>“Du lebst nicht um die Erwartungen anderer Menschen zu erfüllen” — <span class="citation" data-cites="kishimi2018musst">Ichiro Kishimi und Koga (<a href="#ref-kishimi2018musst" role="doc-biblioref">2018</a>)</span></em></p>
</blockquote>
<p>Freud vs.&nbsp;Adler vs.&nbsp;Jung</p>
<p>Freiheitsbegriff: <span class="citation" data-cites="kishimi2018musst">Ichiro Kishimi und Koga (<a href="#ref-kishimi2018musst" role="doc-biblioref">2018</a>)</span> und <span class="citation" data-cites="kishimi2020bist">Ichirō Kishimi und Koga (<a href="#ref-kishimi2020bist" role="doc-biblioref">2020</a>)</span></p>
<ul>
<li>Alle Probleme sind zwischenmenschliche Beziehungsprobleme</li>
<li>Du lebst nicht, um die Erwartungen ander Menschen zu erfüllen</li>
<li>Aufgabentrennung, die Aufgaben anderer abweisen. Wer erhält am Ende das Resultat, das sich aus der Eintscheidung ergibt?</li>
<li>Freiheit heißt auch von anderen nicht gemocht zu werden.</li>
<li>Glück heißt, einen Beitrag leisten</li>
</ul>
<p>Extrovertiert vs.&nbsp;Introvertiert (jung)</p>
<p><img src="images/youtube.png" class="img-fluid" data-fig-align="center" width="50"><span class="math inline">\(\;\)</span><a href="https://youtu.be/acg6HivAu5E">Carl Jung’s Theory on Introverts, Extraverts, and Ambiverts</a></p>
<p>Carl Jung (1875–1961)</p>
<p>Adler: Um zu Mensch. Es gibt keine individuelle Vergangenheit. Der Mensch konstruiert sich den <em>Zweck</em></p>
<p>Alles kalter Kaffee? <a href="https://de.wikipedia.org/wiki/Mark_Aurel">Mark Aurel (121–180)</a> und</p>
<p><img src="images/youtube.png" class="img-fluid" data-fig-align="center" width="50"><span class="math inline">\(\;\)</span><a href="https://www.youtube.com/@DailyStoic">Daily Stoic</a></p>
<ul>
<li>Amor fati (lat. <em>Liebe zum Schicksal</em>) Es ist nicht dir passiert. Es ist für dich passiert. Das Schicksal hat es für dich ausgesucht. Akzeptiere es, nimm es an, ertrage es, mach etwas daraus.</li>
<li>Die Frucht dieses Lebens ist ein guter Charakter und Taten für das Gemeinwohl.</li>
<li>Memento morti. Du könntest jetzt aus dem Leben scheiden. Das Leben ist kurz.</li>
<li>Wir leiden mehr in der Phantasie als in der Wirklichkeit</li>
<li>Wir alle lieben uns selbst mehr als andere Menschen, kümmern uns aber mehr um deren Meinung als um unsere eigene</li>
<li>Du hast immer das Recht, keine Meinung zu einem bestimmten Thema zu haben</li>
</ul>
<p>Fromm nochmal anders einordnen</p>
<blockquote class="blockquote">
<p><em>“Liebe ist eine Entscheidung, ein Urteil, ein Versprechen. Wenn die Liebe nur ein Gefühl wäre, gäbe es keine Grundlage für das Versprechen, einander für immer zu lieben. Ein Gefühl kommt und kann gehen. Wie kann ich urteilen, dass es für immer bleibt, wenn meine Handlung kein Urteil und keine Entscheidung beinhaltet.” — Erich Fromm, Die Kunst des Liebens</em></p>
</blockquote>
<ul>
<li><a href="https://de.wikipedia.org/wiki/Erich_Fromm">Erich Fromm (1900–1980)</a></li>
<li><a href="https://de.wikipedia.org/wiki/Die_Kunst_des_Liebens">Die Kunst des Liebes</a></li>
</ul>
<blockquote class="blockquote">
<p><em>“Intimacy is the capacity to be rather weird with someone - and finding that that’s ok with them.” — Alain de Botton</em></p>
</blockquote>
<p><img src="images/youtube.png" class="img-fluid" data-fig-align="center" width="50"><span class="math inline">\(\;\)</span><a href="https://www.youtube.com/playlist?list=PLwxNMb28XmpcEwc0qydf2jSszQFSht81E">The School of Life - Learn, Heal, Grow</a></p>
<p>–&gt; Raus mit Karl Popper (1902–1994), dass das hier alles nicht zu falsifizieren ist.</p>
</section><section id="falsifikationsprinzip" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="falsifikationsprinzip">
<span class="header-section-number">3.3.3</span> Falsifikationsprinzip</h3>
<blockquote class="blockquote">
<p><em>“Soweit eine wissenschaftliche Aussage über die Realität spricht, muss sie falsifizierbar sein; und soweit sie nicht falsifizierbar ist, spricht sie nicht über die Realität.” — Karl Popper</em></p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Grundlagen der Wissenschaft und Falsifikationsprinzip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/h45ftLNsspM">Grundlagen der Wissenschaft und Falsifikationsprinzip</a> als Video Reihe.</p>
</div>
</div>
<p>Karl Popper</p>
<p>Karl Popper ging davon aus, dass die Annäherung an die Wahrheit für Menschen das höchste Ziel sei, jedoch eine endgültige Bestätigung oder Verifikation unmöglich sei, da nicht alle möglichen Fälle untersucht werden können. Einzig das Ergebnis einer Falsifikation könne als vorläufig gesichert gelten. Auf dieser Grundlage leitete Popper eine strenge, aber auch tolerante Vorgabe für neue und ungewöhnliche Theorien ab: Jede Idee könne als wissenschaftliche Theorie betrachtet werden – unter der Bedingung, dass sie durch Falsifikation überprüfbar ist!</p>
<p>Dieser Ansatz sollte sicherstellen, dass man entweder mit widerlegten oder noch nicht ausreichend abgesicherten Theorien arbeitet. Da wissenschaftlicher Fortschritt oft auf bereits Vorhandenem aufbaut, erlaubte Popper jedoch vorübergehend, Theorien zu akzeptieren, die bereits mehreren Falsifikationsversuchen standgehalten hatten – natürlich nur so lange, bis sie schlussendlich widerlegt werden würden.</p>
<p><a href="https://psychotherapie-wissenschaft.info/article/view/1776/2519">Wie man Poppers philosophischen Knüppel in einen Blumenstrauss für die Psychoanalyse verwandelt</a></p>
<p>Max von Petterkofer und der <a href="https://de.wikipedia.org/wiki/Positivismus">Positivismus</a></p>
<p>https://de.wikipedia.org/wiki/Max_von_Pettenkofer</p>
<p>Robert Koch</p>
</section><section id="cargo-cult-science" class="level3" data-number="3.3.4"><h3 data-number="3.3.4" class="anchored" data-anchor-id="cargo-cult-science">
<span class="header-section-number">3.3.4</span> Cargo Cult Science</h3>
<blockquote class="blockquote">
<p><em>“The first principle is that you must not fool yourself and you are the easiest person to fool.” — Richard P. Feynman</em></p>
</blockquote>
<p>Du betreibst Cargo Cult, wenn du eine Handlung formal korrekt durchführst, aber der Kontext keinen Sinn ergibt. Klingt jetzt erstmal kryptisch, aber viele Handlungen entspringen mehr einem Mem als einer rationalen Ursache.</p>
<p>Die Übertragung des Mems durch Kommunikation ist dabei nicht als Kopie („Blaupause”) eines Gedankens von Gehirn zu Gehirn zu verstehen, sondern – indem der wesentliche Kern der Botschaft erfasst und weitergegeben wird – eher wie ein “Backrezept” zur Reproduktion desselben Gedankens.</p>
<p><span class="citation" data-cites="feynman1998cargo">Feynman (<a href="#ref-feynman1998cargo" role="doc-biblioref">1998</a>)</span></p>
<div id="fig-wumo-study" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/study.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;3.12— Professor Zapinsky proved thate the squid is more intelligent than the housecat when posed with puzzles under similar condistions. Quelle: wumo.com</figcaption></figure>
</div>
<blockquote class="blockquote">
<p><em>“Jede hinreichend fortschrittliche Technologie ist von Magie nicht zu unterscheiden.” — Arthur C. Clarke, 3. Gesetz</em></p>
</blockquote>
<div id="fig-cargo-overview" class="quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-cargo-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/cargo_cult_01.jpg" class="img-fluid figure-img" data-ref-parent="fig-cargo-overview"></p>
<figcaption class="figure-caption">(a) Bilder des Tages. Quelle: der-postillon.com</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-cargo-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/cargo_cult_02a.png" class="img-fluid figure-img" data-ref-parent="fig-cargo-overview"></p>
<figcaption class="figure-caption">(b) Birds Arent’t Real Kampagne. Quelle: nytimes.com</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-cargo-03" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/preface/cargo_cult_03.webp" class="img-fluid figure-img" data-ref-parent="fig-cargo-overview"></p>
<figcaption class="figure-caption">(c) Bewohner Neuguineas, Neukaledoniens, der Salomonen. Quelle: tellmeboutblog.wordpress.com</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;3.13— Verschiedene Beispiele für Fake News im Spiegel des Cargo Cults. Durch moderne KI-gestützte Bildbearbeitung sind eigene Realitäten möglich, die es so nicht gibt.</figcaption><p></p>
</figure>
</div>
</section><section id="wahrscheinlichkeitsbegriff" class="level3" data-number="3.3.5"><h3 data-number="3.3.5" class="anchored" data-anchor-id="wahrscheinlichkeitsbegriff">
<span class="header-section-number">3.3.5</span> Wahrscheinlichkeitsbegriff</h3>
<blockquote class="blockquote">
<p><em>“Gott würfelt nicht!” — Albert Einstein</em></p>
</blockquote>
<ul>
<li><a href="https://de.wikipedia.org/wiki/Frequentistischer_Wahrscheinlichkeitsbegriff">Frequentistischer Wahrscheinlichkeitsbegriff</a></li>
<li><a href="https://de.wikipedia.org/wiki/Bayesscher_Wahrscheinlichkeitsbegriff">Bayessche Wahrscheinlichkeitsbegriff</a></li>
</ul></section><section id="anthropozän" class="level3" data-number="3.3.6"><h3 data-number="3.3.6" class="anchored" data-anchor-id="anthropozän">
<span class="header-section-number">3.3.6</span> Anthropozän</h3>
<p>Holozän, die vor 11.700 Jahren begann, beendet und das Anthropozän formal in der Geologischen Zeittafel eingeführt werden</p>
<p>Zeitalter des Menschen</p>
<p>Crawfordsee in Ontario, Kanada Im warmen Sommer werden Kalzitminerale ausgefällt, die herabrieseln und alljährlich eine markante weiße Lage bilden. Wie Baumringe.</p>
<p>„Global Boundary Stratotype Section and Point”, GSSP, heißt das sperrig im Fachjargon. Zuweilen sagt man auch „Golden Spike”,</p>
<p>Vor allem aber sei ab den frühen 1950er-Jahren das Isotop Plutonium-239 nachweisbar – eine globale Signatur von Kernwaffentests.</p>
</section><section id="data-science" class="level3" data-number="3.3.7"><h3 data-number="3.3.7" class="anchored" data-anchor-id="data-science">
<span class="header-section-number">3.3.7</span> Data Science</h3>
<ul>
<li>Real World Data <span class="citation" data-cites="liu2022real">Liu und Panagiotakos (<a href="#ref-liu2022real" role="doc-biblioref">2022</a>)</span>
</li>
<li>Warum <strong>Data</strong> Science <span class="citation" data-cites="hariri2019uncertainty">Hariri, Fredericks, und Bowers (<a href="#ref-hariri2019uncertainty" role="doc-biblioref">2019</a>)</span>
</li>
</ul>
<p>Von den Daten zu Erkenntnis und zurück.</p>
</section></section><section id="und-jetzt" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="und-jetzt">
<span class="header-section-number">3.4</span> Und jetzt?</h2>
<p><span class="citation" data-cites="zull2006key">Zull (<a href="#ref-zull2006key" role="doc-biblioref">2006</a>)</span></p>
<ul>
<li>Qualitative / Quantitative Forschung</li>
<li>Why the pen its mightiger than the keyboard <span class="citation" data-cites="mueller2014pen">Mueller und Oppenheimer (<a href="#ref-mueller2014pen" role="doc-biblioref">2014</a>)</span>
</li>
<li>Eigene Sachen <span class="citation" data-cites="kruppa2021statistics">Kruppa u.&nbsp;a. (<a href="#ref-kruppa2021statistics" role="doc-biblioref">2021</a>)</span>
</li>
<li>Paradigmenwechsel?</li>
</ul>
<p>Warum eigentlich Prozess? Geht es nicht eigentlich um das Ergebnis? Also wollen wir nicht was Neues entdecken?</p>
<p>Kapitalistische Idee des Gefühles des Mangels als Triebfeder für den Konsum und das Wirtschaftssystem.</p>
</section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-ecker2017teilchen" class="csl-entry" role="listitem">
Ecker, Gerhard. 2017. <em>Teilchen, Felder, Quanten: Von der Quantenmechanik zum Standardmodell der Teilchenphysik</em>. Springer-Verlag.
</div>
<div id="ref-england2013statistical" class="csl-entry" role="listitem">
England, Jeremy L. 2013. <span>„Statistical physics of self-replication“</span>. <em>The Journal of chemical physics</em> 139 (12).
</div>
<div id="ref-feynman1998cargo" class="csl-entry" role="listitem">
Feynman, Richard P. 1998. <span>„Cargo cult science“</span>. In <em>The art and science of analog circuit design</em>, 55–61. Elsevier.
</div>
<div id="ref-frankl2010trotzdem" class="csl-entry" role="listitem">
Frankl, Viktor E. 2010<em>... trotzdem Ja zum Leben sagen: ein Psychologe erlebt das Konzentrationslager</em>. K<span>ö</span>sel-Verlag.
</div>
<div id="ref-hariri2019uncertainty" class="csl-entry" role="listitem">
Hariri, Reihaneh H, Erik M Fredericks, und Kate M Bowers. 2019. <span>„Uncertainty in big data analytics: survey, opportunities, and challenges“</span>. <em>Journal of Big Data</em> 6 (1): 1–16.
</div>
<div id="ref-helmke2013individualisierung" class="csl-entry" role="listitem">
Helmke, Andreas. 2013. <span>„Individualisierung: Hintergrund, Missverst<span>ä</span>ndnisse, Perspektiven“</span>. <em>Pädagogik</em> 35: 34–37.
</div>
<div id="ref-kishimi2018musst" class="csl-entry" role="listitem">
Kishimi, Ichiro, und Fumitake Koga. 2018. <em>Du musst nicht von allen gemocht werden: vom Mut, sich nicht zu verbiegen</em>. Rowohlt Verlag GmbH.
</div>
<div id="ref-kishimi2020bist" class="csl-entry" role="listitem">
Kishimi, Ichirō, und Fumitake Koga. 2020. <em>Du bist genug: vom Mut, gl<span>ü</span>cklich zu sein</em>. Rowohlt Taschenbuch Verlag.
</div>
<div id="ref-kruppa2021statistics" class="csl-entry" role="listitem">
Kruppa, Jochen, Jessica Rohmann, Carolin Herrmann, Miriam Sieg, Kerstin Rubarth, und Sophie Piper. 2021. <span>„What statistics instructors need to know about concept acquisition to make statistics stick“</span>. <em>Journal of University Teaching &amp; Learning Practice</em> 18 (2): 02.
</div>
<div id="ref-liu2022real" class="csl-entry" role="listitem">
Liu, Fang, und Demosthenes Panagiotakos. 2022. <span>„Real-world data: a brief review of the methods, applications, challenges and opportunities“</span>. <em>BMC Medical Research Methodology</em> 22 (1): 287.
</div>
<div id="ref-mueller2014pen" class="csl-entry" role="listitem">
Mueller, Pam A, und Daniel M Oppenheimer. 2014. <span>„The pen is mightier than the keyboard: Advantages of longhand over laptop note taking“</span>. <em>Psychological science</em> 25 (6): 1159–68.
</div>
<div id="ref-schimel2012writing" class="csl-entry" role="listitem">
Schimel, Joshua. 2012. <em>Writing science: how to write papers that get cited and proposals that get funded</em>. OUP USA.
</div>
<div id="ref-wallace2009water" class="csl-entry" role="listitem">
Wallace, David Foster. 2009. <em>This is water: Some thoughts, delivered on a significant occasion, about living a compassionate life</em>. Hachette UK.
</div>
<div id="ref-zull2006key" class="csl-entry" role="listitem">
Zull, James E. 2006. <span>„Key aspects of how the brain learns“</span>. <em>New directions for adult and continuing education</em> 110: 3.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./literature.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./abschlussarbeit.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>