<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 50&nbsp; Äquivalenz oder Nichtunterlegenheit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-meta.html" rel="next">
<link href="./stat-modeling-survival.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-modeling-preface.html">Statistisches Modellieren</a></li><li class="breadcrumb-item"><a href="./stat-modeling-noninferiority.html"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Hauptkomponentenanalyse</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Fortgeschrittene Versuchsplanung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Anhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spielecke</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link active" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">50.1</span> Genutzte R Pakete</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"><span class="header-section-number">50.2</span> Daten</a></li>
  <li>
<a href="#technische-gleichheit" id="toc-technische-gleichheit" class="nav-link" data-scroll-target="#technische-gleichheit"><span class="header-section-number">50.3</span> Technische Gleichheit</a>
  <ul class="collapse">
<li><a href="#bestimmtheitsma%C3%9F-r2" id="toc-bestimmtheitsmaß-r2" class="nav-link" data-scroll-target="#bestimmtheitsma%C3%9F-r2"><span class="header-section-number">50.3.1</span> Bestimmtheitsmaß <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#korrelation" id="toc-korrelation" class="nav-link" data-scroll-target="#korrelation"><span class="header-section-number">50.3.2</span> Korrelation</a></li>
  <li><a href="#mse-rmse-nrmse-und-mae" id="toc-mse-rmse-nrmse-und-mae" class="nav-link" data-scroll-target="#mse-rmse-nrmse-und-mae"><span class="header-section-number">50.3.3</span> MSE, RMSE, nRMSE und MAE</a></li>
  </ul>
</li>
  <li>
<a href="#medizinische--oder-behandlungsgleichheit" id="toc-medizinische--oder-behandlungsgleichheit" class="nav-link" data-scroll-target="#medizinische--oder-behandlungsgleichheit"><span class="header-section-number">50.4</span> Medizinische- oder Behandlungsgleichheit</a>
  <ul class="collapse">
<li><a href="#anova-mit-effektsch%C3%A4tzer" id="toc-anova-mit-effektschätzer" class="nav-link" data-scroll-target="#anova-mit-effektsch%C3%A4tzer"><span class="header-section-number">50.4.1</span> ANOVA mit Effektschätzer</a></li>
  <li><a href="#%C3%A4quivalenztest" id="toc-äquivalenztest" class="nav-link" data-scroll-target="#%C3%A4quivalenztest"><span class="header-section-number">50.4.2</span> Äquivalenztest</a></li>
  </ul>
</li>
  <li><a href="#weiterf%C3%BChrende-links" id="toc-weiterführende-links" class="nav-link" data-scroll-target="#weiterf%C3%BChrende-links"><span class="header-section-number">50.5</span> Weiterführende Links</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-noninf" class="quarto-section-identifier"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom July 28, 2023 um 20:27:43</em></p>
<blockquote class="blockquote">
<p><em>“Absence of evidence is not evidence of absence” — <span class="citation" data-cites="altman1995statistics">Altman und Bland (<a href="#ref-altman1995statistics" role="doc-biblioref">1995</a>)</span></em></p>
</blockquote>
<p>In diesem Kapitel wollen wir uns mit Gleichheit beschäftigen. Dabei gibt es zwei Arten von Gleichheit. Zum einen können wir uns die technische Gleichheit anschauen oder aber die medizinische- oder Behandlungsgruppengleichheit. Wir definieren die beiden Settings daher wie folgt.</p>
<ul>
<li>
<strong>Technische Gleichheit</strong> wollen wir nachweisen, wenn wir zwei <em>technische</em> Messmethoden miteinander vergleichen. Wir messen also einmal ein Wachstum mit dem Verfahren A und einmal mit dem Verfahren B. In beiden Fällen erhalten wir dann eine kontinuierliche Zahl, wie zum Beispiel das Gewicht. Jetzt wollen wir wissen, ob das Verfahren A gleich dem Verfahren B das Wachstum gemessen hat.</li>
<li>
<strong>Medizinische- oder Behandlungsgleichheit</strong> wollen wir nachweisen, wenn wir verschiedene Behandlungs<em>gruppen</em> haben. Damit wollen wir auch verschiedene Hypothesen testen. Diese Behandlungsgruppen vergleichen wir dann zu <em>einer</em> Kontrolle oder Standard und wollen nachweisen, dass unsere Behandlungsgruppen <em>gleich</em> zu dem Standard sind. Die Anwendung ist auch eher bei Tieren oder Menschen zu finden. Wir wollen hier also explizit keine technische Gleichheit nachweisen.</li>
</ul>
<p>Je nachdem welche <em>Gleichheit</em> du dir anschauen willst, musst du natürlich auch andere statistische Verfahren wählen. Wir schauen uns daher in diesem Kapitel zuerst einmal die technische Gleichheit an - die ich hier mal so benenne - und danach die medizinische Gleichheit, die sich auf das statistische Hypothesentesten bezieht.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Bei der <em>technischen</em> Gleichheit nutzen wir die lineare Regression und deren Gütekriterien. Bei der <em>medizinischen</em> Gleichheit drehen wir die statistischen Null- und Alternativehypothese und haben damit andere Probleme. Wir rechnen aber einen klassischen Hypothesentest.</p>
</div></div><section id="genutzte-r-pakete" class="level2" data-number="50.1"><h2 data-number="50.1" class="anchored" data-anchor-id="genutzte-r-pakete">
<span class="header-section-number">50.1</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">broom</span>, <span class="va">readxl</span>,</span>
<span>               <span class="va">effectsize</span>, <span class="va">multcompView</span>, <span class="va">multcomp</span>,</span>
<span>               <span class="va">janitor</span>, <span class="va">see</span>, <span class="va">parameters</span>, <span class="va">yardstick</span>,</span>
<span>               <span class="va">rcompanion</span>, <span class="va">emmeans</span>, <span class="va">conflicted</span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">dplyr</span><span class="fu">::</span><span class="va"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">dplyr</span><span class="fu">::</span><span class="va"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">dplyr</span><span class="fu">::</span><span class="va"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">)</span></span>
<span><span class="va">cbbPalette</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#000000"</span>, <span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, </span>
<span>                <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2" data-number="50.2"><h2 data-number="50.2" class="anchored" data-anchor-id="daten">
<span class="header-section-number">50.2</span> Daten</h2>
<p>Als erstes wollen wir uns einmal die Daten für die Überprüfung der technischen Gleichheit anschauen. Die Daten stammen aus Dronenüberflügen zur Bestimmung der Grasdichte auf Weideflächen aus der Datei <code>drone_tech.xlsx</code>. Dabei haben wir zum einen die Grasdichte traditionell mit einem Druckstab gemessen <code>pressure_stick</code> und vergleichen diese Werte dann mit den Werten aus dem Dronenüberflug. Der Drohnenüberflug liefert uns Bilder und aus den Bildern extrahieren wir einen RGB-Wert (abk. <em>Red, Green, Blue</em>) in der Spalte <code>drone_rgb</code> oder einen CMYK-Wert (abk. <em>Cyan, Magenta, Yellow (Gelb), Key (Schwarz)</em>) in der Spalte <code>drone_cmyk</code>. Wir wollen nun schauen, ob wir die drei Werte sinnvoll in ein Verhältnis setzen können. Ein Auszug aus den Daten ist nochmal in der <a href="#tbl-equal-tech-01">Tabelle&nbsp;<span>50.1</span></a> dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-equal-tech-01" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;50.1— Datentabelle für den technischen Vergleich eines Druckstabes und dem RGB-Werten eines Dronenüberflugs auf die Grasdichte auf Weideflächen.</caption>
<thead><tr class="header">
<th style="text-align: center;">pressure_stick</th>
<th style="text-align: center;">drone_rgb</th>
<th style="text-align: center;">drone_cmyk</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1048.24</td>
<td style="text-align: center;">373.31</td>
<td style="text-align: center;">254.65</td>
</tr>
<tr class="even">
<td style="text-align: center;">1284.31</td>
<td style="text-align: center;">671.45</td>
<td style="text-align: center;">234.86</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1170.07</td>
<td style="text-align: center;">544.5</td>
<td style="text-align: center;">184.01</td>
</tr>
<tr class="even">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1013.34</td>
<td style="text-align: center;">355.84</td>
<td style="text-align: center;">219.67</td>
</tr>
<tr class="even">
<td style="text-align: center;">1134.29</td>
<td style="text-align: center;">537.43</td>
<td style="text-align: center;">212.86</td>
</tr>
<tr class="odd">
<td style="text-align: center;">917.29</td>
<td style="text-align: center;">266.74</td>
<td style="text-align: center;">178.46</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In unserem zweiten Datenbeispiel schauen wir uns die Keimungsdaten nach Behandlung mit sechs biologischen Pilzmittel unter zwei Kältebehandlungen aus der Datei <code>cold_seeds.xlsx</code> an. Dabei ist wichtig zu wissen, dass es eine Kontrolle gibt, die das chemische Standardpräparat repräsentiert. Wir wollen jetzt wissen, ob unsere biologischen Alternativen <em>gleich</em> gut sind. Das heißt, wir wollen nicht mehr oder weniger als das Standardpräparat sondern gleichviel. Als Outcome zählen wir die Sporen auf den jungen Keimlingen. Da unsere Pflanze auch eine Kältebehandlung überstehen würde, haben wir auch noch die beiden Kältevarianten mit untersucht. In der <a href="#tbl-noninf-01">Tabelle&nbsp;<span>50.2</span></a> sind die Daten einmal dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-noninf-01" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;50.2— Nicht transformierter Datensatz zu dem Keimungsexperiment mit biologischen Pilzpräparaten.</caption>
<thead><tr class="header">
<th style="text-align: center;">trt</th>
<th style="text-align: center;">cold</th>
<th style="text-align: center;">non_cold</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">386.25</td>
<td style="text-align: center;">22.9</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">100.52</td>
<td style="text-align: center;">169.59</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">56.84</td>
<td style="text-align: center;">65.46</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">357.65</td>
<td style="text-align: center;">142.44</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">37668.6</td>
<td style="text-align: center;">20659.77</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">28302.99</td>
<td style="text-align: center;">7333.37</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2334.1</td>
<td style="text-align: center;">352.41</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">9776.15</td>
<td style="text-align: center;">5025.68</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">1932.27</td>
<td style="text-align: center;">918.05</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">777.63</td>
<td style="text-align: center;">149.17</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2933.99</td>
<td style="text-align: center;">1416.51</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">5731.01</td>
<td style="text-align: center;">2022.39</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir müssen jetzt leider nochmal ran und die Daten etwas aufräumen. Zum einen muss die erste Behandlung raus, hier handelt es sich nur um eine positive Kontrolle, ob überhaupt etwas gewachsen ist. Dann wollen wir uns die Daten auch log-transformieren. Das hat den Grund, dass die statistischen Verfahren in der Äquivalenzanalyse eine Normalverteilung verlangen. Mit der log-Transformation erreichen wir log-normalverteilte Daten, die einer Normalverteilung recht nahe kommen. Am Ende wollen wir dann auch die zweite Behandlung so benennen, dass wir auch immer die Kontrolle erkennen.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cold_seed_tbl</span> <span class="op">&lt;-</span> <span class="va">cold_seed_tbl</span> <span class="op">%&gt;%</span>   </span>
<span>  <span class="va">clean_names</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">trt</span> <span class="op">!=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>trt <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">trt</span><span class="op">)</span>,</span>
<span>         log_cold <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">cold</span><span class="op">)</span>,</span>
<span>         log_non_cold <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">non_cold</span><span class="op">)</span>,</span>
<span>         trt <span class="op">=</span> <span class="fu">fct_recode</span><span class="op">(</span><span class="va">trt</span>, ctrl <span class="op">=</span> <span class="st">"2"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Es ergibt sich dann die <a href="#tbl-noninf-02">Tabelle&nbsp;<span>50.3</span></a>. Wir werden dann in der folgenden Analyse nur noch die log-transformierten Spalten <code>log_cold</code> und <code>log_non_cold</code> nutzen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-noninf-02" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;50.3— Transformierter Datensatz zu dem Keimungsexperiment mit biologischen Pilzpräparaten.</caption>
<thead><tr class="header">
<th style="text-align: center;">trt</th>
<th style="text-align: center;">cold</th>
<th style="text-align: center;">non_cold</th>
<th style="text-align: center;">log_cold</th>
<th style="text-align: center;">log_non_cold</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">37668.6</td>
<td style="text-align: center;">20659.77</td>
<td style="text-align: center;">10.54</td>
<td style="text-align: center;">9.94</td>
</tr>
<tr class="even">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">28302.99</td>
<td style="text-align: center;">7333.37</td>
<td style="text-align: center;">10.25</td>
<td style="text-align: center;">8.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">2874.76</td>
<td style="text-align: center;">1325.42</td>
<td style="text-align: center;">7.96</td>
<td style="text-align: center;">7.19</td>
</tr>
<tr class="even">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">7564.44</td>
<td style="text-align: center;">2103.64</td>
<td style="text-align: center;">8.93</td>
<td style="text-align: center;">7.65</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">1932.27</td>
<td style="text-align: center;">918.05</td>
<td style="text-align: center;">7.57</td>
<td style="text-align: center;">6.82</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">777.63</td>
<td style="text-align: center;">149.17</td>
<td style="text-align: center;">6.66</td>
<td style="text-align: center;">5.01</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2933.99</td>
<td style="text-align: center;">1416.51</td>
<td style="text-align: center;">7.98</td>
<td style="text-align: center;">7.26</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">5731.01</td>
<td style="text-align: center;">2022.39</td>
<td style="text-align: center;">8.65</td>
<td style="text-align: center;">7.61</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section><section id="technische-gleichheit" class="level2 page-columns page-full" data-number="50.3"><h2 data-number="50.3" class="anchored" data-anchor-id="technische-gleichheit">
<span class="header-section-number">50.3</span> Technische Gleichheit</h2>
<p>Beginnen wir also mit der Beurteilung von der technischen Gleichheit zweier Verfahren. Ich nutze hier das Wort <em>technische</em> Gleichheit, da wir hier nicht zwei Gruppen miteinander vergleichen, sondern eben kontinuierlich gemessene Werte haben und wissen wollen, ob diese gemessenen Werte aus den beiden Verfahren gleich sind. In unserem Beispiel wollen wir wissen, ob wir den Druckstab zum Messen der Grasdichte durch einen Drohnenüberflug erstetzen können. Der Dronenflug produziert Bilder und wir können auf zwei Arten Zahlen aus den Bildern generieren. Wir extrahieren entweder die RGB-Werte der Bilder oder aber die CMYK-Werte. Hier ist natürlich ein Schritt den ich überspringe, wir erhalten am Ende eben einen Wert für ein Bild. Oder andersherum, wir können genau einer Messung mit dem Druckstab ein Bild der Drone zuordnen.</p>
<p>In der <a href="#fig-equal-tech-01-1">Abbildung&nbsp;<span>50.1 (a)</span></a> und in der <a href="#fig-equal-tech-01-2">Abbildung&nbsp;<span>50.1 (b)</span></a> sehen wir den Zusammenhang zwischen dem Druckstab und der Dronenmessung für beide Farbskalenwerte nochmal visualisiert. In einer <em>idealen</em> Welt würden alle Punkte auf einer Linie liegen. Das heißt, wir haben einen perfekten Zusammenhang zwischen dem Druckstab und den Farbskalenwerten. So ein perfekter Zusammenhang tritt in der Natur nie auf, deshalb müssen wir uns nun mit statistischen Maßzahlen behelfen.</p>
<p>Wir können die Funktion <code>geom_smooth()</code> nutzen um eine lineare Funktion durch die Punkte zu legen. Wir sehen ist der Fehler, dargestellt als grauer Bereich, bei den CMYK-Werten größer. Auch haben wir Punkte die etwas anch oben weg streben. In der RGB-Skala haben wir eher einen linearen Zusammenhang. Im Folgenden wollen wir uns dann einmal die statistischen Maßzahlen zu der Visualisierung anschauen.</p>
<div class="page-columns page-full">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">drone_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">drone_rgb</span>, <span class="va">pressure_stick</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">drone_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">drone_cmyk</span>, <span class="va">pressure_stick</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-equal-tech-01" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-equal-tech-01-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-noninferiority_files/figure-html/fig-equal-tech-01-1.png" class="img-fluid figure-img" data-ref-parent="fig-equal-tech-01" width="480"></p>
<figcaption class="figure-caption">(a) Dronenmessung mit RGB-Werten.</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-equal-tech-01-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-noninferiority_files/figure-html/fig-equal-tech-01-2.png" class="img-fluid figure-img" data-ref-parent="fig-equal-tech-01" width="480"></p>
<figcaption class="figure-caption">(b) Dronenmessung mit CMYK-Werten.</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;50.1— Vergleich der beiden Farbskalen aus der Dronenmessung zu der Grasdichte durch den Druckstab.</figcaption><p></p>
</figure>
</div>
</div>
<section id="bestimmtheitsmaß-r2" class="level3" data-number="50.3.1"><h3 data-number="50.3.1" class="anchored" data-anchor-id="bestimmtheitsmaß-r2">
<span class="header-section-number">50.3.1</span> Bestimmtheitsmaß <span class="math inline">\(R^2\)</span>
</h3>
<p>Für die genaueren Werte der linearen Funktion nutzen wir dann die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. Wir brauchen die statistischen Maßzahlen höchstens, wenn uns eine Umrechung von den Werten von der einen Messung zu der anderen Messung interessiert.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_drone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">pressure_stick</span> <span class="op">~</span> <span class="va">drone_rgb</span>, data <span class="op">=</span> <span class="va">drone_tbl</span><span class="op">)</span></span>
<span><span class="va">fit_drone</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   | Coefficient |   SE |           95% CI | t(279) |      p
---------------------------------------------------------------------
(Intercept) |      766.33 | 5.12 | [756.26, 776.41] | 149.70 | &lt; .001
drone rgb   |        0.78 | 0.01 | [  0.76,   0.81] |  61.76 | &lt; .001</code></pre>
</div>
</div>
<p>Zum einen können wir uns jetzt auch die lineare Funktion und damit den Zusammenhang von dem Druckstab zu der RGB-Farbskala erstellen. Mir der folgenden Formel können wir dann die Werte der Dronen RGB-Farbskala in die Werte des Druckstabes umrechnen.</p>
<p><span class="math display">\[
pressure\_stick = 766.33 + 0.78 \cdot drone\_rgb
\]</span></p>
<p>Zum anderen erhalten wir mit der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> dann auch die Möglichkeit das Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> zu berechnen. Du kennst das Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> schon aus dem Kapitel für die Qualität einer linearen Regression. Hier nochmal kurz zusammengefasst, das Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> beschreibt, wie gut die Punkte auf der Geraden liegen. Ein Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> von 1 bedeutet, dass die Punkte perfekt auf der Geraden liegen. Ein Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> von 0, dass die Punkte eher wild um eine potenzielle Graden liegen.</p>
<p>Im Folgenden können wir uns noch einmal die Formel des Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> anschauen um etwas besser zu verstehen, wie die Zusammenhänge mathematisch sind. Zum einen brauchen wir den Mittelwert von <span class="math inline">\(y\)</span> als <span class="math inline">\(\bar{y}\)</span> sowie die Werte der einzelnen Punkte <span class="math inline">\(\bar{y}\)</span> und die Werte auf der Geraden mit <span class="math inline">\(\hat{y}_i\)</span>.</p>
<p><span class="math display">\[
\mathit{R}^2 =
\cfrac{\sum_{i=1}^N \left(\hat{y}_i- \bar{y}\right)^2}{\sum_{i=1}^N \left(y_i - \bar{y}\right)^2}
\]</span></p>
<p>In der <a href="#fig-bestimmtheit-tech-01">Abbildung&nbsp;<span>50.2</span></a> sehen wir den Zusammenhang nochmal visualisiert. Wenn die Abstände von dem Mittelwert zu den einzelnen Punkten mit <span class="math inline">\(y_i - \bar{y}\)</span> gleich dem Abstand der Mittelwerte zu den Punkten <em>auf</em> der Geraden mit <span class="math inline">\(\hat{y}_i- \bar{y}\)</span> ist, dann haben wir einen perfekten Zusammenhang.</p>
<div id="fig-bestimmtheit-tech-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/statistical_modeling_bestimmtheit.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Abbildung&nbsp;50.2— Auf der linken Seite sehen wir eine Gerade die nicht perfekt durch die Punkte läuft. Wir nehmen ein Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> von ca. 0.7 an. Die Abstände der einzelnen Beobachtungen <span class="math inline">\(y_i\)</span> zu dem Mittelwert der y-Werte <span class="math inline">\(\bar{y}\)</span> ist nicht gleich den Werten auf der Geraden <span class="math inline">\(\hat{y}_i\)</span> zu dem Mittelwert der y-Werte <span class="math inline">\(\bar{y}\)</span>. Dieser Zusammenhang wird in der rechten Abbildung mit einem Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> von 1 nochmal deutlich.</figcaption></figure>
</div>
<p>Wir können die Funktion <code>glance()</code> nutzen um uns das <code>r.squared</code> und das <code>adj.r.squared</code> wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_drone</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">glance</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">r.squared</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  r.squared
      &lt;dbl&gt;
1     0.932</code></pre>
</div>
</div>
<p>Wir haben wir ein <span class="math inline">\(R^2\)</span> von <span class="math inline">\(0.932\)</span> vorliegen. Damit erklärt unser Modell bzw. die Gerade 93.2% der Varianz. Der Anteil der erklärten Varianz ist auch wunderbar hoch, so dass wir davon ausgehen können, dass der Druckstab und die RGB-Werte der Drone ungefähr das Gleiche wiedergeben.</p>
</section><section id="korrelation" class="level3 page-columns page-full" data-number="50.3.2"><h3 data-number="50.3.2" class="anchored" data-anchor-id="korrelation">
<span class="header-section-number">50.3.2</span> Korrelation</h3>
<p>Neben der Information wie gut die Punkte auf der Geraden liegen, also wie die Punkte um die Gerade streuen, können wir uns auch die Korrelation und damit die Steigung der Gerade wiedergeben lassen. Das Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> sagt uns nämlich nichts über die Richtung der Geraden aus. Die Korrelation liefert uns die Steigung der Geraden mit dem Vorzeichen.</p>
<p>Wir können hier verschiedene Korrelationsmaße berechnen. Am häufigsten werden wir die Korrelation nach Pearson berechnen, da wir von einem normalverteilten <span class="math inline">\(y\)</span> ausgehen. Wenn dies nicht der Fall sein sollte empfiehlt sich stattdessen den Korrelationkoeffizienten nach Spearman zu nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%$%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_rgb</span>, method <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.97</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%$%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_rgb</span>, method <span class="op">=</span> <span class="st">"spearman"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.96</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir nutzen hier den <code>%$%</code>-Operator, da wir in die Funktion <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> die Spalten übergeben wollen. Die Funktion <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> ist relativ alt und möchte daher keinen Datensatz sondern zwei Vektoren.</p>
</div></div><p>Nachdem wir die Korrelation berechnet haben, sehen wir das wir einen <em>positiven</em> Zusammenhang vorliegen haben. Die Gerade durch die Punkte steigt an und ist fast eine 45<span class="math inline">\(^{\circ}\)</span> Gerade, da wir eine Korrelation nahe 1 vorliegen haben.</p>
</section><section id="mse-rmse-nrmse-und-mae" class="level3" data-number="50.3.3"><h3 data-number="50.3.3" class="anchored" data-anchor-id="mse-rmse-nrmse-und-mae">
<span class="header-section-number">50.3.3</span> MSE, RMSE, nRMSE und MAE</h3>
<p>Neben der Betrachtung der Abweichung vom Mittelwert von <span class="math inline">\(y\)</span> können wir uns auch die Abstände von den geschätzten Punkten <em>auf</em> der Geraden <span class="math inline">\(\hat{y}_i\)</span> zu den eigentlichen Punkten anschauen <span class="math inline">\(y_i\)</span>. Wir haben jetzt zwei Möglichkeiten die Abstände zu definieren.</p>
<ol type="1">
<li>Wir schauen uns die quadratischen Abstände mit <span class="math inline">\((y_i - \hat{y}_i)^2\)</span> an. Wir berechnen dann die mittlere quadratische Abweichung (eng. <em>mean square error</em> abk. <em>MSE</em>).</li>
<li>Wir schauen uns die absoluten Abstände mit <span class="math inline">\(|y_i - \hat{y}_i|\)</span> an. Wir berechnen dann den mittleren absoluten Fehler (eng. <em>mean absolute error</em>, abk. <em>MAE</em>).</li>
</ol>
<p>Im Folgenden betrachten wir erst den MSE und seine Verwandten. Wie wir an der Formel sehen, berechnen wir für den MSE einfach nur die quadratische Abweichung zwischen den Beobachtungen <span class="math inline">\(y_i\)</span> und den Werten auf der berechneten Geraden <span class="math inline">\(\hat{y}_i\)</span>. Dann summieren wir alles auf und teilen noch durch die Anzahl der Beobachtungen also Punkte <span class="math inline">\(n\)</span>.</p>
<p><span class="math display">\[
MSE = \cfrac{1}{n}\sum^n_{i=1}(y_i - \hat{y}_i)^2
\]</span></p>
<p>Häufig wollen wir dann nicht die <em>quadratischen</em> Abweichungen angeben. Wir hätten dann ja auch die Einheit der Abweichung im Quadrat. Daher ziehen wir die Wurzel aus dem MSE und erhalten den <em>root mean square error</em> (abk. <em>RMSE</em>). Hierfür gibt es dann keine gute Übersetzung ins Deutsche.</p>
<p><span class="math display">\[
RMSE = \sqrt{MSE} = \sqrt{\cfrac{1}{n}\sum^n_{i=1}(y_i - \hat{y}_i)^2}
\]</span></p>
<p>Der RMSE ist ein gewichtetes Maß für die Modellgenauigkeit, das auf der gleichen Skala wie das Vorhersageziel angegeben wird. Einfach ausgedrückt kann der RMSE als der durchschnittliche Fehler interpretiert werden, den die Vorhersagen des Modells im Vergleich zum tatsächlichen Wert aufweisen, wobei größere Vorhersagefehler zusätzlich gewichtet werden.</p>
<p>Je näher der RMSE-Wert bei 0 liegt, desto genauer ist das Modell. Der RMSE-Wert wird jedoch auf derselben Skala zurückgegeben wie das Ziel, für das Sie Vorhersagen treffen, und daher gibt es keine allgemeine Regel für die Interpretation von Wertebereichen. Die Interpretation Ihres Wertes kann nur innerhalb Ihres Datensatzes bewertet werden.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">rmse</span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_rgb</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard        694.</code></pre>
</div>
</div>
<p>Als letzte Möglichkeit sei noch der normalisierte <em>root mean square error</em> (abk. <em>nRMSE</em>) genannt. In diesem Fall wird der RMSE nochmal durch den Mittelwert von <span class="math inline">\(y\)</span> geteilt.</p>
<p><span class="math display">\[
nRMSE = \cfrac{RMSE}{\bar{y}} = \cfrac{\sqrt{MSE}}{\bar{y}} = \cfrac{\sqrt{\cfrac{1}{N}\sum^N_{i=1}(y_i - \hat{y}_i)^2}}{\bar{y}}
\]</span></p>
<p>In wie weit jetzt jedes MSE Abweichungsmaß sinnvoll ist und auch in der Anwendung passen mag, sei einmal dahingestellt. Wichtig ist hier zu Wissen, dass wir die MSE-Fehler nutzen um verschiedene Verfahren zu vergleichen. Ein kleiner Fehler ist immer besser. Ein einzelner MSE-Wert an sich, ist dann immer schwer zu interpretieren.</p>
<p>Als Alternative zu den MSE-Fehlern bietet sich dann der MAE an. Hier schauen wir dann auf die <em>absoluten</em> Abstände. Wir nehmen also das Vorzeichen raus, damit sich die Abstände nicht zu 0 aufaddieren. Wir haben dann folgende Formel vorliegen.</p>
<p><span class="math display">\[
MAE = \cfrac{1}{n}\sum^n_{i=1}|y_i - \hat{y}_i|
\]</span></p>
<p>Der MAE hat gegenüber dem RMSE Vorteile in der Interpretierbarkeit. Der MAE ist der Durchschnitt der absoluten Werte der Fehler. MAE ist grundsätzlich leichter zu verstehen als die Quadratwurzel aus dem Durchschnitt der quadrierten Fehler. Außerdem beeinflusst jede einzelne Abweichung den MAE in direktem Verhältnis zum absoluten Wert der Abweichung, was bei der RMSE nicht der Fall ist. Der MAE ist nicht identisch mit dem mittleren quadratischen Fehler (RMSE), auch wenn einige Forscher ihn so angeben und interpretieren. MAE ist konzeptionell einfacher und auch leichter zu interpretieren als RMSE: Es ist einfach der durchschnittliche absolute vertikale oder horizontale Abstand zwischen jedem Punkt in einem Streudiagramm und der Geraden.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mae</span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_rgb</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 mae     standard        691.</code></pre>
</div>
</div>
<p>Wir können uns mit der Funktion <code>metrics()</code> auch die Fehler zusammenausgeben lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">metrics</span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_rgb</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     694.   
2 rsq     standard       0.932
3 mae     standard     691.   </code></pre>
</div>
</div>
<p>Wie schon oben geschrieben, der MSE und Co.&nbsp;sind nur in einem Vergleich sinnvoll. Deshalb hier nochmal der Vergleich der beiden Farbskalen der Dronenbilder.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">metrics</span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_rgb</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     694.   
2 rsq     standard       0.932
3 mae     standard     691.   </code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">drone_tbl</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">metrics</span><span class="op">(</span><span class="va">pressure_stick</span>, <span class="va">drone_cmyk</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     843.   
2 rsq     standard       0.546
3 mae     standard     831.   </code></pre>
</div>
</div>
<p>Wir schon zu erwarten ist auch hier der Fehler bei den RGB-Werten kleiner als bei den CMYK-Werten. Daher würden wir uns hier für die Umrechnung der RGB-Werte entscheiden.</p>
</section></section><section id="medizinische--oder-behandlungsgleichheit" class="level2 page-columns page-full" data-number="50.4"><h2 data-number="50.4" class="anchored" data-anchor-id="medizinische--oder-behandlungsgleichheit">
<span class="header-section-number">50.4</span> Medizinische- oder Behandlungsgleichheit</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Disclaimer - Wichtig! Lesen!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Der folgende Text ist ein <em>Lehr</em>text für Studierende. Es handelt sich keinesfalls um eine textliche Beratung für Ethikanträge oder Tierversuchsanträge geschweige den der Auswertung einer klinischen Studie. Alle Beispiel sind im Zweifel an den Haaren herbeigezogen und dienen nur der Veranschaulichung <em>möglicher</em> Sachverhalte.</p>
<p>Antragsteller:innen ist die statistische Beratung von einer entsprechenden Institution dringlichst angeraten.</p>
</div>
</div>
<p>Wir eingangs schon geschrieben wollen wir bei der <em>Medizinische- oder Behandlungsgleichheit</em> nachweisen, dass sich verschiedene Behandlungs<em>gruppen</em> zu <em>einer</em> Kontrolle oder Standard <em>gleich</em> oder äquivalent sind. Wir haben es hier als mit einem klassischen Gruppenvergleich zu tun, bei dem wir die Hypothesen drehen. Wenn wir auf Unterschied testen, dann haben wir in der Nullhypothese <span class="math inline">\(H_0\)</span> die Gleichheit zwischen zwei Mittelwerten stehen. Wir wollen die Gleichheit der Mittelwerte ablehnen. Wir schreiben also unsere beiden Hypothesenpaare wie folgt.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wie immer gibt es auch tolle Tutorien wie das Tutorium von Daniël Lakens <a href="https://lakens.github.io/statistical_inferences/09-equivalencetest.html">Equivalence Testing and Interval Hypotheses</a></p>
</div></div><dl>
<dt>Statistischer Test auf Unterschied</dt>
<dd>
<p><span class="math display">\[
\begin{aligned}
H_0: \bar{y}_{1} &amp;= \bar{y}_{2} \\  
H_A: \bar{y}_{1} &amp;\neq \bar{y}_{2} \\   
\end{aligned}
\]</span></p>
</dd>
</dl>
<p>Wenn wir jetzt einen statiistischen Teste für die Äquivalenz oder Nichtunterlegenheit rechnen wollen, dann drehen wir das Hypothesenpaar. Wir wollen jetzt in der Nullhypothese die “Ungleichheit” der Mittelwerte ablehnen.</p>
<dl>
<dt>Statistischer Test auf Gleichheit</dt>
<dd>
<p><span class="math display">\[
\begin{aligned}
H_0: \bar{y}_{1} &amp;\neq \bar{y}_{2} \\  
H_A: \bar{y}_{1} &amp;= \bar{y}_{2} \\   
\end{aligned}
\]</span></p>
</dd>
</dl>
<p>Und hier beginnt auch schon die Krux. Konnten wir uns relativ einfach einigen, dass ein Mittelwertesunterschied <span class="math inline">\(\Delta\)</span> von 0 eine Gleichheit zwischen den beiden Mittelwerten der beiden Gruppen bedeutet, so ist die Festlegung auf einen Unterschied schon schwieriger. Die Bewertung, ob zwei Mittelwerte sich für zwei Gruppen unterscheiden, kann nur im Kontext der biologischen oder medizinischen Fragestellung beantwortet werden. Die Diskussion, ob ein <span class="math inline">\(\Delta\)</span> von 0.1 noch gleich oder ungleich ist, kann rein numerisch schwer geführt werden. Deshalb gibt es einige Richtlinien und Richtwerte.</p>
<p>Aus dem Grund definieren wir Äquivalenzgrenzen oder Äquivalenzzone. Die Äquivalenzzone wird durch eine untere Äquivalenzgrenze und/oder eine obere Äquivalenzgrenze definiert. Die untere Äquivalenzgrenze (UEG) definiert deine untere Grenze der Akzeptanz für die Mittelwertsdifferenz. Die obere Äquivalenzgrenze (UEL) definiert die obere Grenze der Akzeptanz für die Mittelwertsdifferenz. Jede Abweichung von der Mittelwertsdifferenz, die innerhalb dieses Bereichs der Äquivalenzgrenzen liegt, wird als unbedeutend angesehen. Du kannst hier statt Mittelwertsdifferenz natürlich auch in Anteilen denken, wenn es um das Odds ratio oder Risk ratio geht.</p>
<p>Als erstes Beispiel einer Behörde hier einmal das Zitat der Europäische Behörde für Lebensmittelsicherheit (EFSA) für die Zulassung eines Pilzmittels aus unseren Beispiel. Hier sei angemerkt, dass viele statistische Methoden von einem normalverteilten Outcome oder aber approximativ log-normalverteilten Outcome ausgehen. Deshalb werden die Äquivalenzgrenzen hier auch auf der <span class="math inline">\(log\)</span>-Skala benannt.</p>
<blockquote class="blockquote">
<p>“The limits for equivalence were set to <span class="math inline">\(-\cfrac{1}{2}\log\)</span> and <span class="math inline">\(\cfrac{1}{2}\log\)</span> equal to -0.5 and 0.5 because of the log transformation of the outcome.” — <a href="https://www.efsa.europa.eu/de">Europäische Behörde für Lebensmittelsicherheit (EFSA)</a></p>
</blockquote>
<p>Häufig werden die Effekte aus verschiedenen Studien auch skaliert, damit wir dann die Effekte besser vergleichen können. Als Skalierung bietet sich eine Normalisierung oder Standardisierung an. Als Beispiel in den Pflanzenwissenschaften sei <span class="citation" data-cites="van2019equivalence">Voet u.&nbsp;a. (<a href="#ref-van2019equivalence" role="doc-biblioref">2019</a>)</span> genannt. <span class="citation" data-cites="van2019equivalence">Voet u.&nbsp;a. (<a href="#ref-van2019equivalence" role="doc-biblioref">2019</a>)</span> führen Analysen zum Schutz vor unbeabsichtigten Auswirkungen von gentechnisch verändertem Mais auf die Umwelt oder die menschliche Gesundheit durch [<a href="https://www.sciencedirect.com/science/article/pii/S0278691519300572">Link</a>]. Hier hilft besonders sich von anderen Studien <em>vor</em> dem Experiment zu inspirieren zu lassen. Um eine ausgiebige Literaturrecherche kommt man dann meist nicht rum.</p>
<p>Auch sei noch das Institut für Qualität und Wirtschaftlichkeit im Gesundheitswesen (IQWiG) erwähnt, welches für die Regulierung von Anwendungen in der Humanmedizin zu tun hat. Da sind ja die Grenzen immer etwas fließend. Wann ist ein Medikament <em>nur</em> für die Agrarwissenschaften relevant und hate keine Auswirkungen auf den Menschen? Diese Frage lasse ich hier offen. Hier hilft aber auch der Blick in das Papier <em>Allgemeine Methoden</em> und dann das Kapitel 9. Hier einmal ein Zitat aus dem Abschnitt zu dem Nachweis zur Gleichheit. Wir sehen. so einfach ist die Sachlage nicht.</p>
<blockquote class="blockquote">
<p>“Umgekehrt erfordert auch die Interpretation nicht statistisch signifikanter Ergebnisse Aufmerksamkeit. Insbesondere wird ein solches Ergebnis nicht als Nachweis für das Nichtvorhandensein eines Effekts (Abwesenheit bzw. Äquivalenz) gewertet.” — Kapitel 9.3.5 Nachweis der Gleichheit in <a href="https://www.iqwig.de/ueber-uns/methoden/methodenpapier/">Allgemeine Methoden des Institut für Qualität und Wirtschaftlichkeit im Gesundheitswesen (IQWiG)</a></p>
</blockquote>
<p>Schauen wir uns nun nochmal unsere Keimungsdaten nach Behandlung mit sechs biologischen Pilzmittel unter zwei Kältebehandlungen an. Wenn wir den Richtlinien der EFSA folgen, dann rechnen wir auf den <span class="math inline">\(\log\)</span>-transformierten Daten. Die <span class="math inline">\(\log\)</span>-transformierten Daten sind damit auch approximativ normalverteilt, so dass wir hier dann alle statistischen Methoden nutzen können, die eine Normalverteilung voraussetzen. In der <a href="#fig-noninf-1">Abbildung&nbsp;<span>50.3</span></a> sehen wir, dass die <span class="math inline">\(\log\)</span>-transformierten Daten eindeutig mehr einer Normalverteilung folgen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cold_seed_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pivot_longer</span><span class="op">(</span><span class="va">cold</span><span class="op">:</span><span class="fu">last_col</span><span class="op">(</span><span class="op">)</span>,</span>
<span>               names_to <span class="op">=</span> <span class="st">"type"</span>,</span>
<span>               values_to <span class="op">=</span> <span class="st">"growth"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>type <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="va">trt</span>, <span class="va">growth</span>, fill <span class="op">=</span> <span class="va">trt</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">type</span>, scales <span class="op">=</span> <span class="st">"free_y"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-noninf-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-noninferiority_files/figure-html/fig-noninf-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;50.3— Boxplots der Wachstumsraten des Pilzes in der Standardkontrolle sowie den sechs neunen Präparaten. Die oberen Abbildungen sind auf der normalen Datenskala, die unteren Abbildungen sind <span class="math inline">\(\log\)</span>-transformiert.</figcaption></figure>
</div>
</div>
</div>
<p>Im Folgenden gehen wir jetzt von einfach nach kompliziert. Daher schauen wir uns erstmal die einfachste statistische Methode an, die wir nutzen können und werden dann inhaltlich komplizierter.</p>
<section id="anova-mit-effektschätzer" class="level3" data-number="50.4.1"><h3 data-number="50.4.1" class="anchored" data-anchor-id="anova-mit-effektschätzer">
<span class="header-section-number">50.4.1</span> ANOVA mit Effektschätzer</h3>
<p>Als erstes <em>missbrauchen</em> wir die ANOVA für den Nachweis der Gleichheit. Das ist die Schlechteste der denkbaren Möglichkeiten aber im Rahmen einer Bachelorarbeit oder aber um sich einen ersten Überblick zu verschaffen sinnvoll. Warum ist die die ANOVA so schlecht? Wir testen hier weiterhin die Nullhypothese auf Gleichheit. Wenn wir also einen signifikante ANOVA vorfinden, dann würden wir die Nullhypothese der Gleichheit ablehnen und auf einen Mittelwertsunterschied schließen. Wie wir schon vorab gelernt haben, ist eine <em>nicht</em> signifikante ANOVA kein schlüssiger Beweis für die Gültigkeit der Nullhypothese der Gleichheit. Wir arbeiten mit dem Falsifikationsprinzip, wir können nur Hypothesen ablehnen. Eine abgelehnte Hypothese bedeutet aber nicht im Umkehrschluss, dass die Gegenhypothese wahr ist. Daher nutzen wir hier die ANOVA als einen Art Seismographen. Eine signifikante ANOVA deutet auf einen Unterschied in den Mittelwerten hin, dann ist es vermutlich unwahrscheinlich, dass wir Gleichheit vorliegen haben.</p>
<p>Schauen wir uns dazu einmal die zwei einfaktoriellen ANOVA’s für die kälte und nicht-kälte Behandlung einmal an. Als erstes rechnen wir eine einfacktorielle ANOVA und schauen, ob wir ein signifkantes Eregbnis vorliegen haben.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_non_cold_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">log_non_cold</span> <span class="op">~</span> <span class="va">trt</span>, data <span class="op">=</span> <span class="va">cold_seed_tbl</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_non_cold_fit</span> <span class="op">%&gt;%</span> <span class="va">anova</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter | Sum_Squares | df | Mean_Square |    F |     p
---------------------------------------------------------
trt       |       26.39 |  6 |        4.40 | 2.75 | 0.018
Residuals |      118.50 | 74 |        1.60 |      |      

Anova Table (Type 1 tests)</code></pre>
</div>
</div>
<p>Da der <span class="math inline">\(p\)</span>- Wert kleiner ist als das Signifikanzniveau <span class="math inline">\(\alpha\)</span> müssen wir die Nullhypothese der Gleichheit ablehnen. Mindestens einen paarweisen Unterschied zwischen den Gruppen gibt es. Prinzipiell könnten wir natürlich hoffen, dass alle Gruppen gleich zur Kontrolle sind und sich nur zwei Behandlungsgruppen unterscheiden, aber es ist schonmal ein schlechtes Zeichen, wenn wir eine signifikante ANOVA vorliegen haben und auf Gleichheit der Behandlungen zur Kontrolle aus sind.</p>
<p>Schauen wir nochmal auf den Effekt. Wenn wir einen großen Effekt der Behandlungsgruppen vorliegen haben, dann deutet dies auch nicht gerade auf gleiche Gruppenunterschiede.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_non_cold_fit</span> <span class="op">%&gt;%</span> <span class="fu">eta_squared</span><span class="op">(</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
trt       | 0.18 | [0.02, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Wir sehen, dass wir nur 18% der Varianz durch unsere Behandlungsgruppen erklären. Daher würden wir hier nicht von einem großen Effekt ausgehen. Würde auch hier viel Varianz erklärt, dann könnten wir hier auch aufhören. Schauen wir uns nochmal die andere Art der Vorbehandlung an.</p>
<p>Jetzt schauen wir nochmal wo die paarweisen Unterschiede sind. Wir nutzen dazu den <code><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test()</a></code>. Darüber hinaus haben wir bei den nicht-kälte behandelten Samen eine stark unterschiedliche Streuung der einzelnen Beobachtungen in den Gruppen. Durch die unterschiedlichen Varianzen in den Gruppen setzten wir <code>pool.sd = FALSE</code> und nehmen hier Varianzheterogenität an. Dann schauen wir uns einmal das <em>compact letter display</em> an und sehen, welche Behandlungen sich voneinander unterscheiden oder nicht.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cold_seed_tbl</span> <span class="op">%$%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span><span class="va">log_non_cold</span>, <span class="va">trt</span>, pool.sd <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>                  p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">extract2</span><span class="op">(</span><span class="st">"p.value"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">fullPTable</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">multcompLetters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ctrl    3    4    5    6    7    8 
 "a" "ab" "ab"  "b"  "a"  "b" "ab" </code></pre>
</div>
</div>
<p>Wir sehen, dass wir Unterschiede haben. Da wir hier nur zur Kontrolle vergleichen wollen, schauen wir nach dem Buchstaben der Kontrolle und sehen, dass wir hier den <em>letter</em> <code>a</code>haben. Wir interpretieren das <em>compact letter display</em> nun etwas statistisch schief in dem Sinne, das gleiche Buchstaben Gleichheit aussagen. Immerhin unterscheiden sich die Behandlungen 3, 4, 6 und 8 nicht von der Kontrolle.</p>
<p>Den gleichen Ablauf können wir jetzt auch einmal für die kälte-behandleten Samen machen. Wir rechnen wieder als erstes eine einfaktorielle ANOVA und schauen, ob wir einen signifikanten Unterschied zwischen den Gruppen haben.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_cold_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">log_cold</span> <span class="op">~</span> <span class="va">trt</span>, data <span class="op">=</span> <span class="va">cold_seed_tbl</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_cold_fit</span> <span class="op">%&gt;%</span> <span class="va">anova</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter | Sum_Squares | df | Mean_Square |    F |     p
---------------------------------------------------------
trt       |        9.80 |  6 |        1.63 | 2.71 | 0.020
Residuals |       44.59 | 74 |        0.60 |      |      

Anova Table (Type 1 tests)</code></pre>
</div>
</div>
<p>Auch hier zeigt die signifikante ANOVA, dass wir mindestens einen paarweisen Mittelwertsunterschied zwischen den Behandlungsgruppen haben. Welche Gruppen sich nun unterscheiden werden wir dann gleich einmal in dem paarweisen t-Test uns anschauen. Vorher nochmal schauen wir nochmal wie stark der Effekt der Behandlungsgruppen ist.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_cold_fit</span> <span class="op">%&gt;%</span> <span class="fu">eta_squared</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
trt       | 0.18 | [0.02, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Auch hier können wir 18% der Varianz in dem Wachstum durch die Behandlungsgruppen erklären. Das ist recht wenig. Schauen wir aber jetzt einmal den paarweisen t-Test an. Die Varianzen sind ungefähr gleich in den Gruppen, die Boxplots haben ungefähr die gleiche Ausdehnung nach der Logarithmierung. Deshalb nutzen wir hier einmal dei Funktionalität von <code>emmeans</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_cold_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">trt</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">cld</span><span class="op">(</span>Letters <span class="op">=</span> <span class="va">letters</span>, adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> trt  emmean    SE df lower.CL upper.CL .group
 5      7.71 0.234 74     7.24     8.17  a    
 4      7.87 0.224 74     7.42     8.32  a    
 8      7.97 0.224 74     7.53     8.42  a    
 3      8.09 0.224 74     7.64     8.54  a    
 7      8.13 0.224 74     7.68     8.57  a    
 6      8.14 0.245 74     7.65     8.62  a    
 ctrl   8.88 0.224 74     8.43     9.32   b   

Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Hier unterscheiden sich nun alle Behandlungsgruppen von der Kontrolle. Die neuen Behandlungen unterscheiden sich aber untereinander nicht. Jetzt können wir uns noch anschauen, wie groß den der Mittelwertsunterschied für die einzelnen Behandlungen jeweils ist. Das kann uns die Funktion <code>pwpm()</code> wiedergeben.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_cold_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">trt</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pwpm</span><span class="op">(</span>adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ctrl        3        4        5        6        7      8
ctrl   [8.88]   0.0151   0.0021   0.0005   0.0286   0.0206 0.0057
3     0.78844   [8.09]   0.4900   0.2401   0.8895   0.9033 0.7181
4     1.00830  0.21986   [7.87]   0.6146   0.4258   0.4173 0.7413
5     1.17217  0.38373  0.16387   [7.71]   0.2088   0.1965 0.4093
6     0.74212 -0.04632 -0.26618 -0.43005   [8.14]   0.9816 0.6292
7     0.74980 -0.03865 -0.25851 -0.42238  0.00767   [8.13] 0.6296
8     0.90329  0.11485 -0.10501 -0.26888  0.16117  0.15350 [7.97]

Row and column labels: trt
Upper triangle: P values 
Diagonal: [Estimates] (emmean) 
Lower triangle: Comparisons (estimate)   earlier vs. later</code></pre>
</div>
</div>
<p>Wir lesen <code>Lower triangle: Comparisons (estimate)   earlier vs. later</code> und damit wird jeweils der <code>ctrl</code>- Mittelwert minus den Behandlungsmittelwerten in der ersten Spalte angegeben. Wir sehen, dass die Kontrolle immer ein größeres Wachstum hat. Damit haben wir zwar keine Gleichheit gezeigt, aber unsere Behandlungen haben alle <em>weniger</em> als die Kontrolle. Eventuell reicht das ja aus, wir haben zwar nicht gleich viel Wachstum wie die Kontrolle, aber durchgehend weniger.</p>
<p>Das war jetzt hier natürlich die Version für Arme bzw. wenn wir im Rahmen einer Abschlussarbeit noch zusätzlich was berechnen wollen. Wenn es etwas aufwendiger sein soll, dann gibt es natürlich auch richtige statistischen Methoden für den Äquivalenztest.</p>
</section><section id="äquivalenztest" class="level3" data-number="50.4.2"><h3 data-number="50.4.2" class="anchored" data-anchor-id="äquivalenztest">
<span class="header-section-number">50.4.2</span> Äquivalenztest</h3>
<p>Wenn wir wirklich in unserem Experiment oder Studie einen Äquivalenztest gleich von Anfang an rechnen wollen, dann können wir auch in R auf ein weitreichendes Angebot an Paketen und Funktionen zurückgreifen. Wie immer ist die Frage, was wollen wir? Wichtig ist, dass wir immer eine Gruppe brauchen zu der wir die Äquivalenz oder Gleichheit bestimmen wollen. Im Weiteren haben wir die Wahl zwischen zwei Ansätzen. Einmal den frequentistischen Ansatz sowie die bayesianische Variante. Ich möchte hier nicht mehr so ins Detail gehen, wir nutzen den frequentistischen Ansatz. Das hat auch den Vorteil, dass wir die Äquivalenz an 95% Konfidenzintervallen überprüfen. Mehr gibt es dann jeweils auf den beiden Hilfeseiten der Funktionen.</p>
<ul>
<li>Einmal den frequentistischen Ansatz aus dem Paket <code>parameters</code> durch die Funktion <a href="https://easystats.github.io/parameters/reference/equivalence_test.lm.html">parameters::equivalence_test()</a>
</li>
<li>Oder die bayesianische Variante aus dem R Paket <code>bayestestR</code> durch die Funktion <a href="https://easystats.github.io/bayestestR/reference/equivalence_test.html">bayestestR::equivalence_test()</a>
</li>
</ul>
<p>Wichtig ist, dass wir immer zum ersten Level des Faktors der Behandlung vergleichen! Das heißt, deine Kontrollgruppe sollte immer die erste Gruppe sein und das erste Level haben. Du kannst sonst mit der Funktion <code>fct_relevel()</code> und <code>mutate()</code> die Level neu anordnen. Wir haben hier aber das Glück, dass wir die Kontrolle als erstes Level der Behandlung <code>trt</code> vorliegen haben.</p>
<p>Wie gehen wir nun vor? Die Funktion <code>equivalence_test()</code> berechnet 95% Konfidenzintervalle für die paarweisen Vergleiche von jeder Behandlung zur Kontrolle. Wir erhalten also sechs 95% Konfidenzintervalle. Im Weiteren müssen wir entscheiden wie groß der Bereich der Äquivalenzzone sein soll. Wir müssen also über die Option <code>range =</code> Grenzen definieren und lassen die Funktion <code>equivalence_test()</code> die Grenzen selbstständig berechnen. Ich empfehle immer die Grenzen aus der Litertaur zu nehmen. In unserem Fall sind es die <span class="math inline">\(\log\)</span>-Grenzen aus der EFSA Regulierung mit -0.5 und 0.5, die setzen wir dann in die Option <code>range =</code> ein. Die <code>range</code> repräsentiert hierbei die <em>Region of Practical Equivalence (ROPE)</em> oder eben unsere Äquivalenzgrenzen.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_non_cold</span> <span class="op">&lt;-</span> <span class="fu">parameters</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/equivalence_test.html">equivalence_test</a></span><span class="op">(</span><span class="va">lm_non_cold_fit</span>, </span>
<span>                                             ci <span class="op">=</span> <span class="fl">0.95</span>,</span>
<span>                                             range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">res_non_cold</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># TOST-test for Practical Equivalence

  ROPE: [-0.50 0.50]

Parameter   |         90% CI | % in ROPE |        H0 |      p
-------------------------------------------------------------
(Intercept) | [ 6.99,  8.21] |        0% |  Rejected | &gt; .999
trt [3]     | [-1.81, -0.08] |    24.15% |  Rejected | 0.807 
trt [4]     | [-1.94, -0.22] |    16.43% |  Rejected | 0.868 
trt [5]     | [-2.87, -1.11] |        0% |  Rejected | 0.997 
trt [6]     | [-1.41,  0.39] |    49.41% | Undecided | 0.541 
trt [7]     | [-2.16, -0.43] |     3.80% |  Rejected | 0.936 
trt [8]     | [-1.90, -0.18] |    18.81% |  Rejected | 0.851 </code></pre>
</div>
</div>
<p>Wir sehen also einmal das Ergebnis unseres Äquivalenztest. Wichtig hierbei ist, dass wir zu der Kontrolle testen. Unsere Kontrolle steckt in dem <code>(Intercept)</code> und die Effekte aus der linearen Regression in <code>lm_non_cold_fit</code> beziehen sich ja alle auf den Intercept, so wird das Modell mit kategorialen Variablen gebaut. In der Spalte <code>% in ROPE</code> sehen wir in wie weit der Unterschied zwischen den Behandlungen, dargestellt als 95% Konfidenzintervall, in den Äquivalenzgrenzen liegt. In der folgenden Spalte <code>H0</code> dann die Entscheidung für oder gegen die die Nullhypothese im Sinne der Gleichheit. Gut, das ist etwas wirr, schauen wir uns einmal die <a href="#fig-noninf-2">Abbildung&nbsp;<span>50.4</span></a> an, dann wird es klarer.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res_non_cold</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-noninf-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-noninferiority_files/figure-html/fig-noninf-2-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;50.4— Darstellung der zweiseitigen 95% Konfidenzintervalle für die Vergleiche der Behandlungen zu der Kontrolle. Liegt ein 95% Konfidenzintervall in den Äquivalenzgrenzen so kann die Nullhypothese und damit Gleichheit zur Kontrolle nicht abgelehnt werden.</figcaption></figure>
</div>
</div>
</div>
<p>Als Ergebnis können wir mitnehmen, dass keine der Behandlungen gleich zur Kontrolle ist. Die Behandlung 6 ist noch am nächsten dran, gleich zu sein, aber wir können hier anhand den Daten keine Entscheidung treffen. Am Ende unterscheiden sich alle Behandlungen von der Kontrolle.</p>
<p>Als anderes Beispiel schauen wir uns dann einmal noch die kälte Behandlung an. Hier sehen wir dann schon ein anderes Bild. Die Interpretation ist die gleiche wie eben schon. Wir wollen, dass die 95% Konfidenzintervalle in den Äquivalenzgrenzn von <code>ROPE: [-0.50 0.50]</code> liegen.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_cold</span> <span class="op">&lt;-</span> <span class="fu">parameters</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/equivalence_test.html">equivalence_test</a></span><span class="op">(</span><span class="va">lm_cold_fit</span>, </span>
<span>                                         ci <span class="op">=</span> <span class="fl">0.95</span>,</span>
<span>                                         range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">res_cold</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># TOST-test for Practical Equivalence

  ROPE: [-0.50 0.50]

Parameter   |         90% CI | % in ROPE |       H0 |      p
------------------------------------------------------------
(Intercept) | [ 8.50,  9.25] |        0% | Rejected | &gt; .999
trt [3]     | [-1.32, -0.26] |    22.68% | Rejected | 0.817 
trt [4]     | [-1.54, -0.48] |     1.85% | Rejected | 0.944 
trt [5]     | [-1.71, -0.63] |        0% | Rejected | 0.979 
trt [6]     | [-1.30, -0.19] |    28.13% | Rejected | 0.766 
trt [7]     | [-1.28, -0.22] |    26.34% | Rejected | 0.784 
trt [8]     | [-1.43, -0.38] |    11.80% | Rejected | 0.896 </code></pre>
</div>
</div>
<p>In der <a href="#fig-noninf-3">Abbildung&nbsp;<span>50.5</span></a> sehen wir den Zusammenhang nochmal visualisiert. Hier fällt nochmal deutlicher auf, dass alle Behandlungen geringere Wachstumszahlen aufweisen. Wir könnten also Gleichheit auch so definieren, dass weniger oder gleich auch als äquivalent gilt. Das hängt natürlich vom biologischen Kontext ab, aber wir machen das jetzt einfach mal.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res_cold</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-noninf-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-noninferiority_files/figure-html/fig-noninf-3-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;50.5— Darstellung der zweiseitigen 95% Konfidenzintervalle für die Vergleiche der Behandlungen zu der Kontrolle. Liegt ein 95% Konfidenzintervall in den Äquivalenzgrenzen so kann die Nullhypothese und damit Gleichheit zur Kontrolle nicht abgelehnt werden.</figcaption></figure>
</div>
</div>
</div>
<p>Wenn du keine untere oder obere Grenze möchtest, also eigentlich nur eine Grenze, dann kannst du die andere Grenze auf Unendlich <code>Inf</code> setzen. Wir setzen hier mal die untere Grenze der Äquivalenz auf <code>-Inf</code> und testen somit faktisch nur einseitig.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_low_cold</span> <span class="op">&lt;-</span> <span class="fu">parameters</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/equivalence_test.html">equivalence_test</a></span><span class="op">(</span><span class="va">lm_cold_fit</span>, </span>
<span>                                             ci <span class="op">=</span> <span class="fl">0.95</span>,</span>
<span>                                             range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="cn">Inf</span>, <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">res_low_cold</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># TOST-test for Practical Equivalence

  ROPE: [-Inf 0.50]

Parameter   |         90% CI | % in ROPE |       H0 |      p
------------------------------------------------------------
(Intercept) | [ 8.50,  9.25] |        0% | Accepted | &lt; .001
trt [3]     | [-1.32, -0.26] |      100% | Accepted | 0.817 
trt [4]     | [-1.54, -0.48] |      100% | Accepted | 0.944 
trt [5]     | [-1.71, -0.63] |      100% | Accepted | 0.979 
trt [6]     | [-1.30, -0.19] |      100% | Accepted | 0.766 
trt [7]     | [-1.28, -0.22] |      100% | Accepted | 0.783 
trt [8]     | [-1.43, -0.38] |      100% | Accepted | 0.896 </code></pre>
</div>
</div>
<p>Wir sehen jetzt, dass sich alle 95% Konfidenzintervalle im ROPE-Bereich befinden. Damit sind dann auch alle Behandlungen gleich zur Kontrolle. Das gilt natürlich nur, da wir weniger als gleich definiert haben! Schauen wir nochmal in der <a href="#fig-noninf-4">Abbildung&nbsp;<span>50.6</span></a> uns die Visualisierung an.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res_low_cold</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-noninf-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-noninferiority_files/figure-html/fig-noninf-4-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;50.6— Darstellung der einseitigen 95% Konfidenzintervalle für die Vergleiche der Behandlungen zu der Kontrolle. Liegt ein 95% Konfidenzintervall in den Äquivalenzgrenzen so kann die Nullhypothese und damit Gleichheit zur Kontrolle nicht abgelehnt werden. Hier wurde nur einseitig getestet, da weniger als die Kontrolle in dem biologischen Kontext auch als Äquivalenz zählt.</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="weiterführende-links" class="level2" data-number="50.5"><h2 data-number="50.5" class="anchored" data-anchor-id="weiterführende-links">
<span class="header-section-number">50.5</span> Weiterführende Links</h2>
<p>Am Ende nochmal ein paar Links, die noch von Interesse sein könnten und die ich hier noch nicht verarbeitet habe. Vielleicht mache ich das dann noch oder ich finde noch andere spannende Referenzen. Ich sammle hier dann mal.</p>
<ul>
<li>
<a href="https://aaroncaldwell.us/TOSTERpkg/">TOSTER</a> und die dazugehörigen Referenzen auf der Seite geben nochmal einen super Überblick.</li>
<li>Der alte Blogpost zu <a href="https://daniellakens.blogspot.com/2016/12/tost-equivalence-testing-r-package.html">TOST equivalence testing R package (TOSTER) and spreadsheet</a>.</li>
<li>Mehr Informationen zu <a href="https://easystats.github.io/bayestestR/articles/region_of_practical_equivalence.html">Region of Practical Equivalence (ROPE)</a> aus dem R Paket <code>bayestestR</code>.</li>
</ul></section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-altman1995statistics" class="csl-entry" role="listitem">
Altman, Douglas G, und J Martin Bland. 1995. <span>„Statistics notes: Absence of evidence is not evidence of absence“</span>. <em>Bmj</em> 311 (7003): 485.
</div>
<div id="ref-van2019equivalence" class="csl-entry" role="listitem">
Voet, Hilko van der, Paul W Goedhart, Esteban Garcı́a-Ruiz, Concepción Escorial, und Jana Tulinská. 2019. <span>„Equivalence limit scaled differences for untargeted safety assessments: Comparative analyses to guard against unintended effects on the environment or human health of genetically modified maize“</span>. <em>Food and Chemical Toxicology</em> 125: 540–48.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-modeling-survival.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-meta.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>