<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 42&nbsp; Poisson Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-multinom.html" rel="next">
<link href="./stat-modeling-gaussian.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-modeling-preface.html">Statistisches Modellieren</a></li><li class="breadcrumb-item"><a href="./stat-modeling-poisson.html"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Einfache Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Fortgeschrittene Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Anhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spielecke</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#annahmen-an-die-daten" id="toc-annahmen-an-die-daten" class="nav-link active" data-scroll-target="#annahmen-an-die-daten"><span class="header-section-number">42.1</span> Annahmen an die Daten</a></li>
  <li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"><span class="header-section-number">42.2</span> Genutzte R Pakete für das Kapitel</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"><span class="header-section-number">42.3</span> Daten</a></li>
  <li><a href="#fit-des-modells" id="toc-fit-des-modells" class="nav-link" data-scroll-target="#fit-des-modells"><span class="header-section-number">42.4</span> Fit des Modells</a></li>
  <li><a href="#performance-des-modells" id="toc-performance-des-modells" class="nav-link" data-scroll-target="#performance-des-modells"><span class="header-section-number">42.5</span> Performance des Modells</a></li>
  <li><a href="#interpretation-des-modells" id="toc-interpretation-des-modells" class="nav-link" data-scroll-target="#interpretation-des-modells"><span class="header-section-number">42.6</span> Interpretation des Modells</a></li>
  <li><a href="#zeroinflation" id="toc-zeroinflation" class="nav-link" data-scroll-target="#zeroinflation"><span class="header-section-number">42.7</span> Zeroinflation</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-poisson" class="quarto-section-identifier"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom August 11, 2023 um 17:40:26</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Einführung in die Poisson Regression per Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/HTgsASKrpB8">Poisson Regression</a> als Video Reihe. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>
<p>In diesem Kapitel wollen wir eine Poisson Regression rechnen. Wir müssen uns hier wieder überlegen, was ist eigentlich unser Outcome <span class="math inline">\(y\)</span> und was sind unsere Einflussvariablen <span class="math inline">\(x\)</span>. Die Poisson Regression ist je nach Hintergurnd des Anwenders eher selten. In der Ökologie, wo gerne mal gezaählt wird, wie oft etwas vorkommt, ist die Poisson Regression häufig vertreten. Sonst fristet die Poisson Regresson eher ein unbekanntes Dasein.</p>
<p>Ein häufig unterschätzter Vorteil der Poisson Regression ist, dass wir auch auch <span class="math inline">\(0/1\)</span> Daten eine Poisson Regression rechnen können. Moment, wirst du jetzt vielleicht denken, das machen wir doch mit der logistsichen Regression. Ja, das stimmt, aber wir können auf Zahlen viel rechnen. Wenn wir auf ein <span class="math inline">\(0/1\)</span> Outcome eine Poisson Regression rechnen, dann kriegen wir nicht Odds Ratios <span class="math inline">\(OR\)</span> als Effektschätzer sondern Risk Ratios <span class="math inline">\(RR\)</span>. Wir erhalten also keine Chancen sondern Wahrscheinlichkeiten. Unter der Annahme, dass das Modell auch konvergiert und wir sinnvolle Zahlen erhalten.</p>
<p>Ein weiteres Problem sind die zu vielen Nullen in dem Outcome <span class="math inline">\(y\)</span>. Daherher wir zählen über die Maßen viel <em>Nichts</em>. Wir nennen diesen Fall <em>zero inflation</em> und beschreiben damit die zu vielen Nullen in den Daten. Hier muss dann noch speziell modelliert werden. Eine Poisson Regression hat schon so seine speziellen Tücken.</p>
<section id="annahmen-an-die-daten" class="level2 page-columns page-full" data-number="42.1"><h2 data-number="42.1" class="anchored" data-anchor-id="annahmen-an-die-daten">
<span class="header-section-number">42.1</span> Annahmen an die Daten</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Unser gemessenes Outcome <span class="math inline">\(y\)</span> folgt einer Poissonverteilung.</span></div></div>
<p>Im folgenden Kapitel zu der multiplen Poisson linearen Regression gehen wir davon aus, dass die Daten in der vorliegenden Form <em>ideal</em> sind. Das heißt wir haben weder fehlende Werte vorliegen, noch haben wir mögliche Ausreißer in den Daten. Auch wollen wir keine Variablen selektieren. Wir nehmen alles was wir haben mit ins Modell. Sollte eine oder mehre Bedingungen nicht zutreffen, dann schaue dir einfach die folgenden Kapitel an.</p>
<ul>
<li>Wenn du fehlende Werte in deinen Daten vorliegen hast, dann schaue bitte nochmal in das <a href="stat-modeling-missing.html"><span>Kapitel&nbsp;39</span></a> zu Imputation von fehlenden Werten.</li>
<li>Wenn du denkst, dass du Ausreißer oder auffälige Werte in deinen Daten hast, dann schaue doch bitte nochmal in das <a href="stat-modeling-outlier.html"><span>Kapitel&nbsp;38</span></a> zu Ausreißer in den Daten.</li>
<li>Wenn du denkst, dass du zu viele Variablen in deinem Modell hast, dann hilft dir das <a href="stat-modeling-variable-selection.html"><span>Kapitel&nbsp;37</span></a> bei der Variablenselektion.</li>
</ul>
<p>Daher sieht unser Modell wie folgt aus. Wir haben ein <span class="math inline">\(y\)</span> und <span class="math inline">\(p\)</span>-mal <span class="math inline">\(x\)</span>. Wobei <span class="math inline">\(p\)</span> für die Anzahl an Variablen auf der rechten Seite des Modells steht. Im Weiteren folgt unser <span class="math inline">\(y\)</span> einer Poissonverteilung. Das ist hier sehr wichtig, denn wir wollen ja eine multiple Poisson lineare Regression rechnen.</p>
<p><span class="math display">\[
y \sim x_1 + x_2 + ... + x_p
\]</span></p>
<p>Wir können in dem Modell auch Faktoren <span class="math inline">\(f\)</span> haben, aber es geht hier nicht um einen Gruppenvergleich. Das ist ganz wichtig. Wenn du einen Gruppenvergleich rechnen willst, dann musst du in <a href="stat-tests-posthoc.html"><span>Kapitel&nbsp;32</span></a> nochmal nachlesen.</p>
</section><section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="42.2"><h2 data-number="42.2" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">42.2</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">conflicted</span>, <span class="va">broom</span>,</span>
<span>               <span class="va">parameters</span>, <span class="va">performance</span>, <span class="va">MASS</span>, <span class="va">pscl</span>, <span class="va">see</span>,</span>
<span>               <span class="va">modelsummary</span>, <span class="va">scales</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"mutate"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="va">cbbPalette</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#000000"</span>, <span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, </span>
<span>                <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2 page-columns page-full" data-number="42.3"><h2 data-number="42.3" class="anchored" data-anchor-id="daten">
<span class="header-section-number">42.3</span> Daten</h2>
<p>Im folgenden schauen wir uns ein Datenbeispiel mit Hechten an. Es handelt sich um langnasige Hechte in nordamerikanischen Flüssen. Wir haben uns insgesamt <span class="math inline">\(n = 68\)</span> Flüsse einmal angesehen und dort die Anzahl an Hechten gezählt. Im Weiteren haben wir dann noch andere Flussparameter erhoben und fragen uns nun, welche dieser Parameter einen Einfluss auf die Anzahl an Hechten in den Flussarmen haben. In <a href="example-complex.html#sec-example-longnose"><span>Kapitel&nbsp;9.2</span></a> findest du nochmal mehr Informationen zu den Daten. Wir entfernen hier die Informationen zu den Flüssen, die brauchen wir in dieser Analyse nicht.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die Daten zu den langnasigen Hechten stammt von <a href="https://rcompanion.org/rcompanion/e_05.html">Salvatore S. Mangiafico - An R Companion for the Handbook of Biological Statistics</a>.</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">longnose_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_csv2</span><span class="op">(</span><span class="st">"data/longnose.csv"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">stream</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full">
<div class="cell-output-display column-page">
<div id="tbl-pois-longnose" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;42.1— Auszug aus dem Daten zu den langnasigen Hechten.</caption>
<thead><tr class="header">
<th style="text-align: center;">longnose</th>
<th style="text-align: center;">area</th>
<th style="text-align: center;">do2</th>
<th style="text-align: center;">maxdepth</th>
<th style="text-align: center;">no3</th>
<th style="text-align: center;">so4</th>
<th style="text-align: center;">temp</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">13</td>
<td style="text-align: center;">2528</td>
<td style="text-align: center;">9.6</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">2.28</td>
<td style="text-align: center;">16.75</td>
<td style="text-align: center;">15.3</td>
</tr>
<tr class="even">
<td style="text-align: center;">12</td>
<td style="text-align: center;">3333</td>
<td style="text-align: center;">8.5</td>
<td style="text-align: center;">83</td>
<td style="text-align: center;">5.34</td>
<td style="text-align: center;">7.74</td>
<td style="text-align: center;">19.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">54</td>
<td style="text-align: center;">19611</td>
<td style="text-align: center;">8.3</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;">0.99</td>
<td style="text-align: center;">10.92</td>
<td style="text-align: center;">19.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">19</td>
<td style="text-align: center;">3570</td>
<td style="text-align: center;">9.2</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">5.44</td>
<td style="text-align: center;">16.53</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">26</td>
<td style="text-align: center;">1450</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">2.96</td>
<td style="text-align: center;">8.84</td>
<td style="text-align: center;">18.6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">4106</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;">2.62</td>
<td style="text-align: center;">5.45</td>
<td style="text-align: center;">15.4</td>
</tr>
<tr class="even">
<td style="text-align: center;">38</td>
<td style="text-align: center;">10274</td>
<td style="text-align: center;">9.3</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">5.45</td>
<td style="text-align: center;">24.76</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">19</td>
<td style="text-align: center;">510</td>
<td style="text-align: center;">6.7</td>
<td style="text-align: center;">82</td>
<td style="text-align: center;">5.25</td>
<td style="text-align: center;">14.19</td>
<td style="text-align: center;">26.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Im Folgenden werden wir die Daten nur für das Fitten eines Modells verwenden. In den anderen oben genannten Kapiteln nutzen wir die Daten dann anders. In <a href="#fig-pois-model-longnose">Abbildung&nbsp;<span>42.1</span></a> sehen wir nochmal die Verteilung der Anzahl der Hechte in den Flüssen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">longnose_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">longnose</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pois-model-longnose" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-poisson_files/figure-html/fig-pois-model-longnose-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;42.1— Histogramm der Verteilung der Hechte in den beobachteten Flüssen.</figcaption></figure>
</div>
</div>
</div>
</section><section id="fit-des-modells" class="level2 page-columns page-full" data-number="42.4"><h2 data-number="42.4" class="anchored" data-anchor-id="fit-des-modells">
<span class="header-section-number">42.4</span> Fit des Modells</h2>
<p>In diesem Abschnitt wollen wir verschiedene Modelle für Zähldaten schätzen. Die Poissonverteilung hat keinen eignen Parameter für die Streung wie die Normalverteilung. Die Poissonverteilung ist mit <span class="math inline">\(\mathcal{Pois}(\lambda)\)</span> definiert und hat somit die Eigenschaft das die Varianz eins zu eins mit dem Mittelwert <span class="math inline">\(\lambda\)</span> der Poissonverteilung ansteigt. Es kann aber sein, dass wir in den Daten nicht diesen ein zu eins Zusammenhang von Mittelwert und Varianz vrliegen haben. Häufig ist die Varianz viel größer und steigt schneller an. Wenn die Varianz in Wirklichkeit sehr viel größer ist, dann würden wir die Varianz in unseren Modell unterschätzen.</p>
<ul>
<li>Ein klassisches Poissonmodell <code>glm(..., familiy = poisson)</code> mit der Annahme keiner Overdisperison.</li>
<li>Ein Quasi-Poissonmodell <code>glm(..., family = quasipoisson)</code> mit der Möglichkeit der Berücksichtigung einer Overdispersion.</li>
<li>Ein negative Binomialmodell <code>glm.nb(...)</code> ebenfalls mit der Berücksichtigung einer Overdispersion.</li>
</ul>
<p>Beginnen wollen wir aber mit einer klassischen Poissonregression ohne die Annahme von einer Overdispersion in den Daten. Wir nutzen dafür die Funktion <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> und spezifizieren die Verteilungsfamilie als <code>poisson</code>. Wir nehmen wieder alle Variablen in das Modell auf der rechten Seite des <code>~</code>. Auf der linken Seite des <code>~</code> kommt dann unser Outcome <code>longnose</code> was die Anzahl an Hechten erhält.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Hier gibt es nur die Kurzfassung der <em>link</em>-Funktion. <span class="citation" data-cites="dormann2013parametrische">Dormann (<a href="#ref-dormann2013parametrische" role="doc-biblioref">2013</a>)</span> liefert hierzu in Kapitel 7.1.3 nochmal ein Einführung in das Thema.</span></div></div>
<p>Wir müssen für die Possionregression noch beachten, dass die Zähldaten von <span class="math inline">\(0\)</span> bis <span class="math inline">\(+\infty\)</span> laufen. Damit wir normalverteilte Residuen erhalten und einen lineren Zusammenhang, werden wir das Modell auf dem <span class="math inline">\(\log\)</span>-scale fitten. Das heißt, wir werden den Zusammenhang von <span class="math inline">\(y\)</span> und <span class="math inline">\(x\)</span> logarithmieren. Wichtig ist hierbei der <em>Zusammenhang</em>. Wir transformieren nicht einfach <span class="math inline">\(y\)</span> und lassen den Rest unberührt. Das führt dazu, dass wir am Ende die Koeffizienten der Poissonregression exponieren müssen. Das können die gängigen Funktionen, wir müssen das Exponieren aber aktiv durchführen. Deshalb hier schon mal erwähnt.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poisson_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">longnose</span> <span class="op">~</span> <span class="va">area</span> <span class="op">+</span> <span class="va">do2</span> <span class="op">+</span> <span class="va">maxdepth</span> <span class="op">+</span> <span class="va">no3</span> <span class="op">+</span> <span class="va">so4</span> <span class="op">+</span> <span class="va">temp</span>,</span>
<span>                    <span class="va">longnose_tbl</span>, family <span class="op">=</span> <span class="va">poisson</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir schauen uns die Ausgabe des Modells einmal mit der <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> Funktion an, da wir hier einmal händisch schauen wollen, ob eine Overdispersion vorliegt. Sonst könnten wir auch die Funktion <code>model_parameters()</code> nehmen. Die nutzen wir später für die Interpretation des Modells, hier wollen wir erstmal sehen, ob alles geklappt hat.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poisson_fit</span> <span class="op">%&gt;%</span> <span class="va">summary</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = longnose ~ area + do2 + maxdepth + no3 + so4 + 
    temp, family = poisson, data = longnose_tbl)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-9.234  -4.086  -1.662   1.771  14.362  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.564e+00  2.818e-01  -5.551 2.83e-08 ***
area         3.843e-05  2.079e-06  18.480  &lt; 2e-16 ***
do2          2.259e-01  2.126e-02  10.626  &lt; 2e-16 ***
maxdepth     1.155e-02  6.688e-04  17.270  &lt; 2e-16 ***
no3          1.813e-01  1.068e-02  16.974  &lt; 2e-16 ***
so4         -6.810e-03  3.622e-03  -1.880   0.0601 .  
temp         7.854e-02  6.530e-03  12.028  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 2766.9  on 67  degrees of freedom
Residual deviance: 1590.0  on 61  degrees of freedom
AIC: 1936.9

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Wir schauen in die Summary-Ausgabe des Poissonmodells und sehen, dass dort steht, dass <code>Dispersion parameter for poisson family taken to be 1</code>. Wir modellieren also einen eins zu eins Zusammenhang von Mittelwert und Varianz. Wenn dieser Zusammenhang nicht in unseren Daten existiert, dann haben wir eine Overdispersion vorliegen.</p>
<p>Wir können die Overdispersion mit abschätzen indem wir die <code>Residual deviance</code> durch die Freiheitsgrade der <code>Residual deviance</code> teilen. Daher erhalten wir eine Overdispersion von <span class="math inline">\(\cfrac{1590.04}{61} \approx 26.1\)</span>. Damit haben wir eine eindeutige Overdispersion vorliegen. Damit steigt die Varianz in einem Verhältnis von ca. 1 zu 26. Wir können auch die Funktion <code>check_overdispersion()</code> aus dem R Paket <code>performance</code> nutzen um die Overdispersion zu berechnen. Die Funktion kann das schneller und ist auch in der Abfolge einer Analyse besser geeignet.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poisson_fit</span> <span class="op">%&gt;%</span> <span class="fu">check_overdispersion</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Overdispersion test

       dispersion ratio =   29.403
  Pearson's Chi-Squared = 1793.599
                p-value =  &lt; 0.001</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Overdispersion detected.</code></pre>
</div>
</div>
<p>Wenn wir Overdispersion vorliegen haben und damit die Varianz zu niedrig schätzen, dann erhalten wir viel mehr signifikante Ergebnisse als es in den Daten zu erwarten wäre. Schauen wir uns nochmal die Parameter der Poissonverteilung und die <span class="math inline">\(p\)</span>-Werte einmal an.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poisson_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   |  Log-Mean |       SE |         95% CI |     z |      p
--------------------------------------------------------------------
(Intercept) |     -1.56 |     0.28 | [-2.12, -1.01] | -5.55 | &lt; .001
area        |  3.84e-05 | 2.08e-06 | [ 0.00,  0.00] | 18.48 | &lt; .001
do2         |      0.23 |     0.02 | [ 0.18,  0.27] | 10.63 | &lt; .001
maxdepth    |      0.01 | 6.69e-04 | [ 0.01,  0.01] | 17.27 | &lt; .001
no3         |      0.18 |     0.01 | [ 0.16,  0.20] | 16.97 | &lt; .001
so4         | -6.81e-03 | 3.62e-03 | [-0.01,  0.00] | -1.88 | 0.060 
temp        |      0.08 | 6.53e-03 | [ 0.07,  0.09] | 12.03 | &lt; .001</code></pre>
</div>
</div>
<p>In der Spalte <code>p</code> finden wir die <span class="math inline">\(p\)</span>-Werte für alle Variablen. Wir sehen, dass fast alle Variablen signifikant sind und das wir eine sehr niedrige Varianz in der Spalte <code>SE</code> sehen. Das heißt unser geschätzer Fehler ist sehr gering. Das ahnten wir ja schon, immerhin haben wir eine Overdisperson vorliegen. Das Modell ist somit falsch. Wir müssen uns ein neues Modell suchen, was Overdispersion berückscihtigen und modellieren kann.</p>
<p>Die Quasi-Poisson Verteilung hat einen zusätzlichen, unabhänigen Parameter um die Varianz der Verteilung zu schätzen. Daher können wir die Overdispersion mit einer Quasi-Poisson Verteilung berückscihtigen. Wir können eine Quasi-Poisson Verteilung auch mit der Funktion <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> schätzen nur müssen wir als Verteilungsfamilie <code>quasipoisson</code> angeben.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">quasipoisson_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">longnose</span> <span class="op">~</span> <span class="va">area</span> <span class="op">+</span> <span class="va">do2</span> <span class="op">+</span> <span class="va">maxdepth</span> <span class="op">+</span> <span class="va">no3</span> <span class="op">+</span> <span class="va">so4</span> <span class="op">+</span> <span class="va">temp</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">longnose_tbl</span>, family <span class="op">=</span> <span class="va">quasipoisson</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nach dem Modellti können wir nochmal in der <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> Funktion schauen, ob wir die Overdispersion richtig berücksichtigt haben.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">quasipoisson_fit</span> <span class="op">%&gt;%</span> <span class="va">summary</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = longnose ~ area + do2 + maxdepth + no3 + so4 + 
    temp, family = quasipoisson, data = longnose_tbl)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-9.234  -4.086  -1.662   1.771  14.362  

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -1.564e+00  1.528e+00  -1.024  0.30999   
area         3.843e-05  1.128e-05   3.408  0.00116 **
do2          2.259e-01  1.153e-01   1.960  0.05460 . 
maxdepth     1.155e-02  3.626e-03   3.185  0.00228 **
no3          1.813e-01  5.792e-02   3.130  0.00268 **
so4         -6.810e-03  1.964e-02  -0.347  0.73001   
temp         7.854e-02  3.541e-02   2.218  0.03027 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 29.40332)

    Null deviance: 2766.9  on 67  degrees of freedom
Residual deviance: 1590.0  on 61  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>An der Zeile <code>Dispersion parameter for quasipoisson family taken to be 29.403319</code> in der Summary-Ausgabe sehen wir, dass das Modell der Quasi-Possion Verteilung die Overdispersion korrekt berücksichtigt hat. Wir können uns nun einmal die Modellparameter anschauen. Die Interpretation machen wir am Ende des Kapitels.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">quasipoisson_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   |  Log-Mean |       SE |        95% CI | t(61) |      p
-------------------------------------------------------------------
(Intercept) |     -1.56 |     1.53 | [-4.57, 1.41] | -1.02 | 0.306 
area        |  3.84e-05 | 1.13e-05 | [ 0.00, 0.00] |  3.41 | &lt; .001
do2         |      0.23 |     0.12 | [ 0.00, 0.45] |  1.96 | 0.050 
maxdepth    |      0.01 | 3.63e-03 | [ 0.00, 0.02] |  3.18 | 0.001 
no3         |      0.18 |     0.06 | [ 0.07, 0.29] |  3.13 | 0.002 
so4         | -6.81e-03 |     0.02 | [-0.05, 0.03] | -0.35 | 0.729 
temp        |      0.08 |     0.04 | [ 0.01, 0.15] |  2.22 | 0.027 </code></pre>
</div>
</div>
<p>Jetzt sieht unser Modell und die <span class="math inline">\(p\)</span>-Werte zusammen mit dem Standardfehler <code>SE</code> schon sehr viel besser aus. Wir können also diesem Modell erstmal von der Seite der Overdispersion vertrauen.</p>
<p>Am Ende wollen wir nochmal das Modell mit der negativen Binomialverteilung rechnen. Die negativen Binomialverteilung erlaubt auch eine Unabhängigkeit von dem Mittelwert zu der Varianz. Wir können hier auch für die Overdispersion adjustieren. Wir rechnen die negativen Binomialregression mit der Funktion <code>glm.nb()</code> aus dem R Paket <code>MASS</code>. Wir müssen keine Verteilungsfamilie angeben, die Funktion <code>glm.nb()</code> kann nur die negative Binomialverteilung modellieren.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">negativebinomial_fit</span> <span class="op">&lt;-</span> <span class="fu">glm.nb</span><span class="op">(</span><span class="va">longnose</span> <span class="op">~</span> <span class="va">area</span> <span class="op">+</span> <span class="va">do2</span> <span class="op">+</span> <span class="va">maxdepth</span> <span class="op">+</span> <span class="va">no3</span> <span class="op">+</span> <span class="va">so4</span> <span class="op">+</span> <span class="va">temp</span>,</span>
<span>                               data <span class="op">=</span> <span class="va">longnose_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Auch hier schauen wir mit der Funktion <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> einmal, ob die Overdisprsion richtig geschätzt wurde oder ob hier auch eine Unterschätzung des Zusammenhangs des Mittelwerts und der Varianz vorliegt.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">negativebinomial_fit</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = longnose ~ area + do2 + maxdepth + no3 + so4 + 
    temp, data = longnose_tbl, init.theta = 1.666933879, link = log)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.4601  -0.9876  -0.4426   0.4825   2.2776  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.946e+00  1.305e+00  -2.256 0.024041 *  
area         4.651e-05  1.300e-05   3.577 0.000347 ***
do2          3.419e-01  1.050e-01   3.256 0.001130 ** 
maxdepth     9.538e-03  3.465e-03   2.752 0.005919 ** 
no3          2.072e-01  5.627e-02   3.683 0.000230 ***
so4         -2.157e-03  1.517e-02  -0.142 0.886875    
temp         9.460e-02  3.315e-02   2.854 0.004323 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.6669) family taken to be 1)

    Null deviance: 127.670  on 67  degrees of freedom
Residual deviance:  73.648  on 61  degrees of freedom
AIC: 610.18

Number of Fisher Scoring iterations: 1

              Theta:  1.667 
          Std. Err.:  0.289 

 2 x log-likelihood:  -594.175 </code></pre>
</div>
</div>
<p>Auch hier sehen wir, dass die Overdispersion mit dem Parameter <span class="math inline">\(\theta\)</span> berücksichtigt wird. Wir können die Zahl <span class="math inline">\(1.67\)</span> nicht direkt mit der Overdispersion aus einer Poissonregression verglechen, aber wir sehen dass das Verhältnis von <code>Residual deviance</code> zu den Freiheitsgraden mit <span class="math inline">\(\cfrac{73.65}{61} \approx 1.20\)</span> fast bei 1:1 liegt. Wir könnten also auch eine negative Binomialverteilung für das Modellieren nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">negativebinomial_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   |  Log-Mean |       SE |         95% CI |     z |      p
--------------------------------------------------------------------
(Intercept) |     -2.95 |     1.31 | [-5.85, -0.10] | -2.26 | 0.024 
area        |  4.65e-05 | 1.30e-05 | [ 0.00,  0.00] |  3.58 | &lt; .001
do2         |      0.34 |     0.11 | [ 0.11,  0.58] |  3.26 | 0.001 
maxdepth    |  9.54e-03 | 3.47e-03 | [ 0.00,  0.02] |  2.75 | 0.006 
no3         |      0.21 |     0.06 | [ 0.10,  0.32] |  3.68 | &lt; .001
so4         | -2.16e-03 |     0.02 | [-0.03,  0.03] | -0.14 | 0.887 
temp        |      0.09 |     0.03 | [ 0.03,  0.16] |  2.85 | 0.004 </code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wie immer gibt es reichtlich Tipps &amp; Tricks welches Modell du nun nehmen solltest. <a href="https://stats.stackexchange.com/questions/201903/how-to-deal-with-overdispersion-in-poisson-regression-quasi-likelihood-negativ/332250#332250">How to deal with overdispersion in Poisson regression: quasi-likelihood, negative binomial GLM, or subject-level random effect?</a> und das Tutorial <a href="https://online.stat.psu.edu/stat504/lesson/9/9.2-0">Modeling Count Data</a>. Auch ich mus immer wieder schauen, was am besten konkret in der Anwendung passen könnte und würde.</p>
</div></div><p>Welches Modell nun das beste Modell ist, ist schwer zu sagen. Wenn du Overdisperion vorliegen hast, dann ist natürlich nur das Quasi-Poissonmodell oder das negative Binomialmodell möglich. Welche der beiden dann das bessere ist, hängt wieder von der Fragestellung ab. Allgemein gesprochen ist das Quasi-Poissonmodell <em>besser</em> wenn dich die Zusammenhänge von <span class="math inline">\(y\)</span> zu <span class="math inline">\(x\)</span> am meisten interessieren. Und das ist in unserem Fall hier die Sachlage. Daher gehen wir mit den Quasi-Poissonmdell dann weiter.</p>
</section><section id="performance-des-modells" class="level2" data-number="42.5"><h2 data-number="42.5" class="anchored" data-anchor-id="performance-des-modells">
<span class="header-section-number">42.5</span> Performance des Modells</h2>
<p>In diesem kurzen Abschnitt wollen wir uns einmal anschauen, ob das Modell neben der Overdispersion auch sonst aus statistischer Sicht in Ordnung ist. Wir wollen ja mit dem Modell aus dem Fit <code>quasipoisson_fit</code> weitermachen. Also schauen wir uns einmal das pseudo-<span class="math inline">\(R^2\)</span> für die Poissonregression an. Da wir es mit einem GLM zu tun haben, ist das <span class="math inline">\(R^2\)</span> mit vorsicht zu genießen. In einer Gaussianregression können wir das <span class="math inline">\(R^2\)</span> als Anteil der erklärten Varianz durch das Modell interpretieren. Im Falle von GLM’s müssen wir hier vorsichtiger sein. In GLM’s gibt es ja keine Varianz sondern eine Deviance.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">r2_efron</span><span class="op">(</span><span class="va">quasipoisson_fit</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3257711</code></pre>
</div>
</div>
<p>Mit einem pseudo-<span class="math inline">\(R^2\)</span> von <span class="math inline">\(0.33\)</span> erklären wir ca. 33% der Varianz in der Anzahl der Hechte. Das ist zwar keine super gute Zahl, aber dafür, dass wir nur eine handvoll von Parametern erfasst haben, ist es dann auch wieder nicht so schlecht. Die Anzahl an Hechten wird sicherlich an ganz vielen Parametern hängen, wir konnten immerhin einige wichtige Stellschrauben vermutlich finden.</p>
<p>In <a href="#fig-pois-model-check">Abbildung&nbsp;<span>42.2</span></a> schauen wir uns nochmal die Daten in den Modelgüteplots an. Wir sehen vorallem, dass wir vielelicht doch einen Ausreißer mit der Beobachtung 17 vorliegen haben. Auch ist der Fit nicht so super, wie wir an dem QQ-Plot sehen. Die Beobachtungen fallen in dem QQ-Plot nicht alle auf eine Linie. Auch sehen wir dieses Muster in dem Residualplot. Hiererwarten wir eine gerade blaue Linie und auch hier haben wir eventuell Ausreißer mit in den Daten.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_model</span><span class="op">(</span><span class="va">quasipoisson_fit</span>, colors <span class="op">=</span> <span class="va">cbbPalette</span><span class="op">[</span><span class="fl">6</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span>, </span>
<span>            check <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"qq"</span>, <span class="st">"outliers"</span>, <span class="st">"pp_check"</span>, <span class="st">"homogeneity"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pois-model-check" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-poisson_files/figure-html/fig-pois-model-check-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption class="figure-caption">Abbildung&nbsp;42.2— Ausgabe ausgewählter Modelgüteplots der Funktion <code>check_model()</code>.</figcaption></figure>
</div>
</div>
</div>
</section><section id="interpretation-des-modells" class="level2" data-number="42.6"><h2 data-number="42.6" class="anchored" data-anchor-id="interpretation-des-modells">
<span class="header-section-number">42.6</span> Interpretation des Modells</h2>
<p>Um die Effektschätzer einer Poissonregression oder aber einer Quasipoisson-Regression interpretieren zu können müssen wir uns einmal einen Beispieldatensatz mit bekannten Effekten zwischen den Gruppen bauen. Im Folgenden bauen wir uns einen Datensatz mit zwei Gruppen. Einmal einer Kontrollgruppe mit einer mittleren Anzahl an <span class="math inline">\(15\)</span> und einer Behandlungsgruppe mit einer um <span class="math inline">\(\beta_1 = 10\)</span> höheren Anzahl. Wir haben also in der Kontrolle im Mittel eine Anzahl von <span class="math inline">\(15\)</span> und in der Behandlungsgruppe eine mittlere Anzahl von <span class="math inline">\(25\)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sample_size</span> <span class="op">&lt;-</span> <span class="fl">100</span></span>
<span><span class="va">longnose_small_tbl</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>grp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, each <span class="op">=</span> <span class="va">sample_size</span><span class="op">)</span>,</span>
<span>                             count <span class="op">=</span> <span class="fl">15</span> <span class="op">+</span> <span class="fl">10</span> <span class="op">*</span> <span class="va">grp</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">2</span> <span class="op">*</span> <span class="va">sample_size</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>count <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span>,</span>
<span>         grp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">grp</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ctrl"</span>, <span class="st">"trt"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <a href="#tbl-pois-longnose-small">Tabelle&nbsp;<span>42.2</span></a> sehen wir nochmal die Daten als Ausschnitt dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-pois-longnose-small" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;42.2— How much is the fish? Der Datensatz über <span class="math inline">\(n = 1000\)</span> Beobachtungen an dem wir überlegen wollen wie wir die Effektschätzer einer Poissonregression zu interpretieren haben.</caption>
<thead><tr class="header">
<th style="text-align: center;">grp</th>
<th style="text-align: center;">count</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">trt</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="odd">
<td style="text-align: center;">trt</td>
<td style="text-align: center;">26</td>
</tr>
<tr class="even">
<td style="text-align: center;">trt</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="odd">
<td style="text-align: center;">trt</td>
<td style="text-align: center;">27</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Da sich die Tabelle schlecht liest hier nochmal der Boxplot in <a href="#fig-pois-model-small">Abbildung&nbsp;<span>42.3</span></a>. Wir sehen den Grupenunterschied von <span class="math inline">\(10\)</span> sowie die unterschiedlichen mittleren Anzahlen für die Kontrolle und die Behandlung.</p>
<div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">longnose_small_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">grp</span>, y <span class="op">=</span> <span class="va">count</span>, fill <span class="op">=</span> <span class="va">grp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_okabeito</span><span class="op">(</span><span class="op">)</span> </span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">longnose_small_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">count</span>, fill <span class="op">=</span> <span class="va">grp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.75</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">""</span>, y <span class="op">=</span> <span class="st">""</span>, fill <span class="op">=</span> <span class="st">"Gruppe"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">10</span>, <span class="fl">30</span>, by <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="fl">30</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-pois-model-small" class="cell quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-pois-model-small-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-poisson_files/figure-html/fig-pois-model-small-1.png" class="img-fluid figure-img" data-ref-parent="fig-pois-model-small" width="480"></p>
<figcaption class="figure-caption">(a) Verteilung der Werte als Boxplot.</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-pois-model-small-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-poisson_files/figure-html/fig-pois-model-small-2.png" class="img-fluid figure-img" data-ref-parent="fig-pois-model-small" width="480"></p>
<figcaption class="figure-caption">(b) Verteilung der Werte als Densityplot.</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;42.3— How much is the fish? Der Boxplot über <span class="math inline">\(n = 1000\)</span> Beobachtungen an dem wir überlegen wollen wie wir die Effektschätzer einer Poissonregression zu interpretieren haben.</figcaption><p></p>
</figure>
</div>
</div>
<p>Jetzt fitten wir einmal das simple Poissonmodell mit der Anzahl als Outcome und der Gruppe mit den zwei Leveln als <span class="math inline">\(x\)</span>. Wir pipen dann das Ergebnis des Fittes gleich in die Funktion <code>model_parameters()</code> weiter um die Ergebnisse des Modellierens zu erhalten.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">count</span> <span class="op">~</span> <span class="va">grp</span>, data <span class="op">=</span> <span class="va">longnose_small_tbl</span>, family <span class="op">=</span> <span class="va">poisson</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   |   IRR |   SE |         95% CI |      z |      p
-------------------------------------------------------------
(Intercept) | 15.17 | 0.39 | [14.42, 15.95] | 105.91 | &lt; .001
grp [trt]   |  1.65 | 0.05 | [ 1.54,  1.75] |  15.30 | &lt; .001</code></pre>
</div>
</div>
<p>Als erstes fällt auf, dass wir die Ausgabe des Modells exponieren müssen. Um einen linearen Zusamenhang hinzukriegen bedient sich die Poissonregression den Trick, das der Zusammenhang zwischen dem <span class="math inline">\(y\)</span> und dem <span class="math inline">\(x\)</span> <em>transformiert</em> wird. Wir rechnen unsere Regression nicht auf den echten Daten sondern auf dem <span class="math inline">\(\log\)</span>-scale. Daher müssen wir die Koeffizienten der Poissonregression wieder zurücktransfomieren, wenn wir die Koeffizienten interpretieren wollen. Das können wir mit der Option <code>exponentiate = TRUE</code> durchführen.</p>
<p>Gut soweit, aber was heißen den jetzt die Zahlen? Wir haben einen Intercept von <span class="math inline">\(14.99\)</span> das entspricht der mittleren Anzahl in der Kontrollgruppe. Und was sagt jetzt die <span class="math inline">\(1.67\)</span> vom Level <code>trt</code> des Faktors <code>grp</code>? Wenn wir <span class="math inline">\(14.99 \cdot 1.67\)</span> rechnen, dann erhalten wir als Ergebnis <span class="math inline">\(25.03\)</span>, also die mittlere Anzahl in der Behandlungsgruppe. Was sagt uns das jetzt aus? Wir erhalten aus der Poissonregression eine Wahrscheinlichkeit oder aber ein Risk Ratio. Wir können sagen, dass die Anzahl in der Behandlungsgruppe <span class="math inline">\(1.67\)</span>-mal so groß ist wie in der Kontrollgruppe.</p>
<p>Schauen wir uns nochmal das volle Modell an und interpretieren die Effekte der einzelnen Variablen.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">quasipoisson_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   |  IRR |       SE |       95% CI | t(61) |      p
-------------------------------------------------------------
(Intercept) | 0.21 |     0.32 | [0.01, 4.11] | -1.02 | 0.306 
area        | 1.00 | 1.13e-05 | [1.00, 1.00] |  3.41 | &lt; .001
do2         | 1.25 |     0.14 | [1.00, 1.57] |  1.96 | 0.050 
maxdepth    | 1.01 | 3.67e-03 | [1.00, 1.02] |  3.18 | 0.001 
no3         | 1.20 |     0.07 | [1.07, 1.34] |  3.13 | 0.002 
so4         | 0.99 |     0.02 | [0.95, 1.03] | -0.35 | 0.729 
temp        | 1.08 |     0.04 | [1.01, 1.16] |  2.22 | 0.027 </code></pre>
</div>
</div>
<p>So schön auch die Funktion <code>model_parameters()</code> ist, so haben wir aber hier das Problem, dass wir den Effekt von <code>area</code> nicht mehr richtig sehen. Wir kriegen hier eine zu starke Rundung auf zwei Nachkommastellen. Wir nutzen jetzt mal die Funktion <code>tidy()</code> um hier Abhilfe zu leisten. Ich muss hier noch die Spalte <code>estimate</code> mit <code>num(..., digits = 5)</code> anpassen, damit du in der Ausgabe auf der Webseite auch die Nachkommastellen siehst.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">quasipoisson_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span>, digits <span class="op">=</span> <span class="fl">5</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">term</span>, <span class="va">estimate</span>, <span class="va">p.value</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>p.value <span class="op">=</span> <span class="fu">pvalue</span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span>,</span>
<span>         estimate <span class="op">=</span> <span class="fu">num</span><span class="op">(</span><span class="va">estimate</span>, digits <span class="op">=</span> <span class="fl">5</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  term         estimate p.value
  &lt;chr&gt;       &lt;num:.5!&gt; &lt;chr&gt;  
1 (Intercept)   0.20922 0.310  
2 area          1.00004 0.001  
3 do2           1.25342 0.055  
4 maxdepth      1.01162 0.002  
5 no3           1.19879 0.003  
6 so4           0.99321 0.730  
7 temp          1.08171 0.030  </code></pre>
</div>
</div>
<p>Schauen wir uns die Effekte der Poissonregression einmal an und versuchen die Ergebnisse zu interpretieren. Dabei ist wichtig sich zu erinnern, dass kein Effekt eine 1 bedeutet. Wir schauen hier auf einen Faktor. Wenn wir eine Anzahl mal Faktor 1 nehmen, dann ändert sich nichts an der Anzahl.</p>
<ul>
<li>
<code>(Intercept)</code> beschreibt den Intercept der Poissonregression. Wenn wir mehr als eine simple Regression vorliegen haben, wie in diesem Fall, dann ist der Intercept schwer zu interpretieren. Wir konzentrieren uns auf die Effekte der anderen Variablen.</li>
<li>
<code>area</code>, beschreibt den Effekt der Fläche. Steigt die Fläche um ein Quadratmeter an, so erhöht sich die <em>Anzahl an Fischen</em> um den <span class="math inline">\(1.00001\)</span>. Daher würde man hier eher sagen, erhöht sich die Fläche um jeweils 1000qm so erhöht sich die <em>Anzahl an Fischen</em> um den Faktor <span class="math inline">\(1.1\)</span>. Dann haben wir auch einen besser zu interpretierenden Effektschätzer. Die Signifikanz bleibt hier davon unbetroffen.</li>
<li>
<code>do2</code>, beschreibt den Partzialdruck des Sauerstoffs. Steigt dieser um eine Einheit an, so sehen wie eine Erhöhung der <em>Anzahl an Fischen</em> um den Faktor <span class="math inline">\(1.25\)</span>. Der Effekt ist gerade <em>nicht</em> signifikant.</li>
<li>
<code>maxdepth</code>, beschreibt die maximale Tiefe. Je tiefer ein Fluß, desto mehr Hechte werden wir beobachten. Der Effekt von <span class="math inline">\(1.01\)</span> pro Meter Tiefe ist signifikant.</li>
<li>
<code>no3</code>, beschreibt den Anteil an Nitrat in den Flüssen. Je mehr Nitrat desto signifiant mehr Hechte werden wir beobachten. Hier steigt der Faktor auch um <span class="math inline">\(1.20\)</span>.</li>
<li>
<code>so4</code>, beschreibt den Schwefelgehalt und mit steigenden Schwefelgehalt nimmt die <em>Anzahl an Fischen</em> leicht ab. Der Effekt ist aber überhauot nicht signifikant.</li>
<li>
<code>temp</code>, beschreibt die Temperatur der Flüsse. Mit steigender Tempertaur erwarten wir mehr Hechte zu beobachten. Der Effekt von <span class="math inline">\(1.08\)</span> Fischen pro Grad Erhöhung ist signifikant.</li>
</ul>
<p>Was nehmen wir aus der Poissonregression zu den langnasigen Hechten mit? Zum einen haben die Fläche, die Tiefe und der Nitratgehalt einen signifikanten Einfluss auf die Anzahl an Hechten. Auch führt eine höhere Temperatur zu mehr gefundenen Hechten. Die erhöhte Temperatur steht etwas im Widerspuch zu dem Sauerstoffpartizaldruck. Denn je höher die Temperatur desto weniger Sauerstoff wird in dem Wasser gelöst sein. Auch scheint die Oberfläche mit der Tiefe korreliert. Allgemein scheinen Hechte große Flüße zu mögen. Hier bietet sich also noch eine Variablenselektion oder eine Untersuchung auf Ausreißer an um solche Effekte nochmal gesondert zu betrachten.</p>
</section><section id="zeroinflation" class="level2" data-number="42.7"><h2 data-number="42.7" class="anchored" data-anchor-id="zeroinflation">
<span class="header-section-number">42.7</span> Zeroinflation</h2>
<p>So eine Poissonregression hat schon einiges an Eigenheiten. Neben dem Problem der Overdispersion gibt es aber noch eine weitere Sache, die wir beachten müssen. Wir können bei einer Poissonregression auch eine Zeroinflation vorliegen haben. Das heißt, wir beobachten viel mehr Nullen in den Daen, als wir aus der Poissonverteilung erwarten würden. Es gibt also einen biologischen oder künstlichn Prozess, der uns Nullen produziert. Häufig wissen wir nicht, ob wir den Prozess, der uns die Nullen in den Daten produziert, auch abbilden. Das heißt, es kann sein, dass wir einfach nichts Zählen, weil dort nichts ist oder aber es gibt dafür einen Grund. Diesen Grund müssten wir dann irgendwie in unseren Daten erfasst haben, aber meistens haben wir das nicht.</p>
<p>Schauen wir usn dafür einmal ein Datenbeispiel von Eidechsen in der Lüneburgerheide an. Wir haben Eidechsen <code>lizard</code> in zwei verschiedenen Habitaten <code>grp</code> gezählt. Einmal, ob die Eidechsen eher im offenen Gelände oder eher im bedeckten Gelände zu finden waren. Im Weiteren haben wir geschaut, ob der Boden keinen Regen erhalten hatte, trocken war oder gar feucht. Mit trocken ist hier eine gewisse Restfeuchte gemeint. Am Ende haben wir noch bestimmt, ob wir eher nah an einer Siedlung waren oder eher weiter entfernt. Du kannst dir den Daten satz in der Datei <code>lizards.csv</code> nochmal anschauen. In <a href="#tbl-lizard-data">Tabelle&nbsp;<span>42.3</span></a> sind die Daten nochmal dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-lizard-data" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;42.3— Ausschnitt aus den Eidechsendaten für die zwei Habitate unter verschiedenen Feuchtigkeitsbedingungen und Nähe zur nächsten Siedlung.</caption>
<thead><tr class="header">
<th style="text-align: center;">grp</th>
<th style="text-align: center;">rain</th>
<th style="text-align: center;">pop</th>
<th style="text-align: center;">lizard</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">near</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">near</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">near</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">near</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">near</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">far</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">open</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">far</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#fig-pois-lizard-data">Abbildung&nbsp;<span>42.4</span></a> sehen wir die Zähldaten der Eidechsen nochmal als Histogramm dargestellt. Wenn wir an einem Punkt keine Eidechsen gefunden haben, dann haben wir keine fehlenden Werte eingetragen, sondern eben, dass wir keine Eidechsen gezählt haben. Wir sehen das wir sehr viele Nullen in unseren Daten haben. Ein Indiz für eine Inflation an Nullen oder eben einer Zeroinflation.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">lizard_zero_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">lizard</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Anzahl der gefundenen Eidechsen"</span>, y <span class="op">=</span> <span class="st">"Anzahl"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="fl">7</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pois-lizard-data" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-poisson_files/figure-html/fig-pois-lizard-data-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;42.4— Histogramm der Verteilung der Hechte in den beobachteten Flüssen.</figcaption></figure>
</div>
</div>
</div>
<p>Um zu überprüfen, ob wir eine Zeroinflation in den Daten vorliegen haben, werden wir erstmal eine ganz normale Poissonregression auf den Daten rechnen. Wir ignorieren auch eine potenzielle Overdispersion. Das schauen wir uns dann in den Daten später nochmal an.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">lizard</span> <span class="op">~</span> <span class="va">grp</span> <span class="op">+</span> <span class="va">rain</span> <span class="op">+</span> <span class="va">pop</span>, data <span class="op">=</span> <span class="va">lizard_zero_tbl</span>,</span>
<span>                  family <span class="op">=</span> <span class="va">poisson</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wie immer nutzen wir die Funktion <code>model_parameters()</code> um uns die exponierten Koeffizienten aus dem Modell wiedergeben zu lassen. Das Modell dient uns jetzt nur als Ausgangsmodell und wir werden das Poissonmodell jetzt nicht weiter tiefer verwenden.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   |  IRR |   SE |       95% CI |     z |      p
---------------------------------------------------------
(Intercept) | 1.06 | 0.29 | [0.60, 1.77] |  0.20 | 0.840 
grp [cover] | 1.88 | 0.46 | [1.18, 3.07] |  2.61 | 0.009 
rain [dry]  | 0.31 | 0.09 | [0.17, 0.53] | -4.12 | &lt; .001
rain [wet]  | 0.13 | 0.05 | [0.06, 0.28] | -4.98 | &lt; .001
pop [far]   | 2.41 | 0.61 | [1.49, 4.04] |  3.47 | &lt; .001</code></pre>
</div>
</div>
<p>Wir sehen, dass wir in der Variable <code>rain</code> eine starke Reduzierung der Anzahl an Eidechsen sehen. Vielleicht ist dies eine Variable, die zu viele Nullen produziert. Auch hat die Variable <code>pop</code>, die für die Nähe an einer Siedlung kodiert, einen starken positiven Effekt auf unsere Anzahl an Eidechsen. Hier wollen wir also einmal auf eine Zeroinflation überprüfen. Wir nutzen dazu die Funktion <code>check_zeroinflation()</code> aus dem R Paket <code>performance</code>. Die Funktion läuft nur auf einem Modellfit.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_zeroinflation</span><span class="op">(</span><span class="va">lizard_fit</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for zero-inflation

   Observed zeros: 31
  Predicted zeros: 27
            Ratio: 0.87</code></pre>
</div>
</div>
<p>Die Funktion gibt uns wieder, dass wir vermutlich eine Zeroinflation vorliegen haben. Das können wir aber Modellieren. Um eine Zeroinflation <em>ohne Overdispersion</em> zu modellieren nutzen wir die Funktion <code>zeroinfl()</code> aus dem R Paket <code>pscl</code>. Der erste Teil der Funktion ist leicht erkläret. Wir bauen uns wieder unswer Model zusammen, was wir fitten wollen. Dann kommt aber ein <code>|</code> und mit diesem Symbol <code>|</code> definieren wir, ob wir wissen, woher die Nullen kommen oder aber ob wir die Nullen mit einem zufälligen Prozess modellieren wollen.</p>
<p>Wenn wir das Modell in der Form <code>y ~ f1 + f2 | 1</code> schreiben, dann nehmen wir an, dass das Übermaß an Nullen in unseren Daten rein zufällig entstanden sind. Wir haben keine Spalte in de Daten, die uns eine Erklärung für die zusätzlichen Nullen liefern würde.</p>
<p>Wir können auch <code>y ~ f1 + f2 | x3</code> schreiben. Dann haben wir eine Variable <code>x3</code> in den Daten von der wir glauben ein Großteil der Nullen herrührt. Wir könnten also in unseren Daten annehmen, dass wir den Überschuss an Nullen durch den Regen erhalten haben und damit über die Spalte <code>rain</code> den Exzess an Nullen modellieren.</p>
<p>Man sollte immer mit dem einfachsten Modell anfangen, deshalb werden wir jetzt einmal ein Modell fitten, dass annimmt, dass die Nullen durch einen uns unbekannten Zufallsprozess entstanden sind.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_infl_intercept_fit</span> <span class="op">&lt;-</span> <span class="fu">zeroinfl</span><span class="op">(</span><span class="va">lizard</span> <span class="op">~</span> <span class="va">grp</span> <span class="op">+</span> <span class="va">pop</span> <span class="op">+</span> <span class="va">rain</span> <span class="op">|</span> <span class="fl">1</span>, </span>
<span>                                           data <span class="op">=</span> <span class="va">lizard_zero_tbl</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir schauen uns das Modell dann wieder einmal an und sehen eine Zweiteilung der Ausgabe. In dem oberen Teil der Ausgabe wird unsere Anzahl an Eidechsen modelliert. In dem unteren Teil wird der Anteil der Nullen in den Daten modelliert. Daher können wir über Variablen in dem <code>Zero-Inflation</code> Block keine Aussagen über die Anzahl an Eidechsen treffen. Variablen tauchen nämlich nur in einem der beiden Blöcke auf.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_infl_intercept_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   |  IRR |   SE |       95% CI |     z |      p
---------------------------------------------------------
(Intercept) | 1.06 | 0.31 | [0.60, 1.87] |  0.22 | 0.830 
grp [cover] | 2.03 | 0.51 | [1.25, 3.31] |  2.84 | 0.005 
pop [far]   | 2.59 | 0.67 | [1.56, 4.31] |  3.67 | &lt; .001
rain [dry]  | 0.31 | 0.10 | [0.17, 0.56] | -3.82 | &lt; .001
rain [wet]  | 0.14 | 0.06 | [0.06, 0.31] | -4.73 | &lt; .001

# Zero-Inflation

Parameter   | Odds Ratio |   SE |       95% CI |     z |     p
--------------------------------------------------------------
(Intercept) |       0.11 | 0.11 | [0.02, 0.74] | -2.26 | 0.024</code></pre>
</div>
</div>
<p>Als erstes beobachten wir einen größeren Effekt der Variable <code>grp</code>. Das ist schon mal ein spannender Effekt. An der Signifikanz hat scih nicht viel geändert. Wir werden am Ende des Kapitels einmal alle Modell für die Modellierung der Zeroinflation vergleichen.</p>
<p>Nun könnte es auch sein, dass der Effekt der vielen Nullen in unserer Variable <code>rain</code> verborgen liegt. Wenn es also regnet, dann werden wir viel weniger Eidechsen beoabchten. Nehmen wir also <code>rain</code> als ursächliche Variable mit in das Modell für die Zeroinflation.</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_infl_rain_fit</span> <span class="op">&lt;-</span> <span class="fu">zeroinfl</span><span class="op">(</span><span class="va">lizard</span> <span class="op">~</span> <span class="va">grp</span> <span class="op">+</span> <span class="va">pop</span> <span class="op">|</span> <span class="va">rain</span>, </span>
<span>                                      data <span class="op">=</span> <span class="va">lizard_zero_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wieder schauen wir uns einmal die Ausgabe des Modells einmal genauer an.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_infl_rain_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   |  IRR |   SE |       95% CI |    z |     p
-------------------------------------------------------
(Intercept) | 1.13 | 0.34 | [0.63, 2.03] | 0.42 | 0.677
grp [cover] | 1.60 | 0.42 | [0.95, 2.67] | 1.77 | 0.077
pop [far]   | 1.84 | 0.51 | [1.07, 3.18] | 2.20 | 0.028

# Zero-Inflation

Parameter   | Odds Ratio |     SE |          95% CI |     z |     p
-------------------------------------------------------------------
(Intercept) |       0.04 |   0.08 | [0.00,    2.09] | -1.60 | 0.109
rain [dry]  |      27.94 |  59.06 | [0.44, 1760.08] |  1.58 | 0.115
rain [wet]  |      83.71 | 178.43 | [1.28, 5459.08] |  2.08 | 0.038</code></pre>
</div>
</div>
<p>Es ändert sich einiges. Zum einen erfahren wir, dass der Regen anscheined doch viele Nullen in den Daten produziert. Wir haben ein extrem hohes <span class="math inline">\(OR\)</span> für die Variable <code>rain</code>. Die Signifikanz ist jedoch eher gering. Wir haben nämlich auch eine sehr hohe Streuung mit den großen <span class="math inline">\(OR\)</span> vorliegen. Au der anderen Seite verlieren wir jetzt auch die Signifikanz von unseren Habitaten und dem Standort der Population. Nur so mäßig super dieses Modell.</p>
<p>Wir können jetzt natürlich auch noch den Standort der Population mit in den Prozess für die Entstehung der Nullen hineinnehmen. Wir schauen uns dieses Modell aber nicht mehr im Detail an, sondern dann nur im Vergleich zu den anderen Modellen.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_infl_rain_pop_fit</span> <span class="op">&lt;-</span> <span class="fu">zeroinfl</span><span class="op">(</span><span class="va">lizard</span> <span class="op">~</span> <span class="va">grp</span> <span class="op">|</span> <span class="va">rain</span> <span class="op">+</span> <span class="va">pop</span>, </span>
<span>                                          data <span class="op">=</span> <span class="va">lizard_zero_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die Gefahr besteht immer, das man sich an die Wand modelliert und vor lauter Modellen die Übersicht verliert. Neben der Zeroinflation müssen wir ja auch schauen, ob wir eventuell eine Overdispersion in den Daten vorliegen haben. Wenn das der Fall ist, dann müsen wir nochmal überlegen, was wir dann machen. Wir testen nun auf Ovrdisprsion in unserem <em>ursprünglichen</em> Poissonmodell mit der Funktion <code>check_overdispersion()</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_overdispersion</span><span class="op">(</span><span class="va">lizard_fit</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Overdispersion test

       dispersion ratio =  1.359
  Pearson's Chi-Squared = 74.743
                p-value =  0.039</code></pre>
</div>
</div>
<p>Tja, und so erfahren wir, dass wir auch noch Overdispersion in unseren Daten vorliegen haben. Wir müsen also beides Modellieren. Einmal modellieren wir die Zeroinflation und einmal die Overdispersion. Wir können beides in einem negativen binominalen Modell fitten. Auch hier hilft die Funktion <code>zeroinfl()</code> mit der Option <code>dist = negbin</code>. Mit der Option geben wir an, dass wir eine negative binominal Verteilungsfamilie wählen. Damit können wir dann auch die Ovrdispersion in unseren Daten modellieren.</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_nb_intercept_fit</span> <span class="op">&lt;-</span> <span class="fu">zeroinfl</span><span class="op">(</span><span class="va">lizard</span> <span class="op">~</span> <span class="va">grp</span> <span class="op">+</span> <span class="va">rain</span> <span class="op">+</span> <span class="va">pop</span> <span class="op">|</span> <span class="fl">1</span>, </span>
<span>                                         dist <span class="op">=</span> <span class="st">"negbin"</span>, data <span class="op">=</span> <span class="va">lizard_zero_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dann schauen wir usn einmal das Modell an. Zum einen sehen wir, dass der Effekt ähnlich groß ist, wie bei dem Intercept Modell der Funktion <code>zeroinfl</code>. Auch bleiben die Signifikanzen ähnlich.</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lizard_zero_nb_intercept_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   |  IRR |   SE |       95% CI |     z |      p
---------------------------------------------------------
(Intercept) | 1.06 | 0.31 | [0.60, 1.87] |  0.22 | 0.830 
grp [cover] | 2.03 | 0.51 | [1.25, 3.31] |  2.84 | 0.005 
rain [dry]  | 0.31 | 0.10 | [0.17, 0.56] | -3.82 | &lt; .001
rain [wet]  | 0.14 | 0.06 | [0.06, 0.31] | -4.73 | &lt; .001
pop [far]   | 2.59 | 0.67 | [1.56, 4.31] |  3.67 | &lt; .001

# Zero-Inflation

Parameter   | Odds Ratio |   SE |       95% CI |     z |     p
--------------------------------------------------------------
(Intercept) |       0.11 | 0.11 | [0.02, 0.74] | -2.26 | 0.024</code></pre>
</div>
</div>
<p>Nun haben wir vier Modelle geschätzt und wolen jetzt wissen, was ist das beste Modell. Dafür hilft usn dann eine Gegenüberstellung der Modelle mit der Funktion <code>modelsummary()</code>. Wir könnten die Modelle auch gegeneinander statistsich Testen, aber hier behalten wir uns einmal den beschreibenden Vergleich vor. In <a href="#tbl-model-comp-zero">Tabelle&nbsp;<span>42.4</span></a> sehen wir einmal die vier Modelle nebeneinander gestellt. Für eine bessere Übrsicht, habe ich aus allen Modellen den Intercept entfernt.</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">modelsummary</span><span class="op">(</span><span class="fu">lst</span><span class="op">(</span><span class="st">"ZeroInfl Intercept"</span> <span class="op">=</span> <span class="va">lizard_zero_infl_intercept_fit</span>,</span>
<span>                 <span class="st">"ZeroInfl rain"</span> <span class="op">=</span> <span class="va">lizard_zero_infl_rain_fit</span>,</span>
<span>                 <span class="st">"ZeroInfl rain+pop"</span> <span class="op">=</span> <span class="va">lizard_zero_infl_rain_pop_fit</span>,</span>
<span>                 <span class="st">"NegBinom intercept"</span> <span class="op">=</span> <span class="va">lizard_zero_nb_intercept_fit</span><span class="op">)</span>,</span>
<span>             statistic <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"conf.int"</span>,</span>
<span>                           <span class="st">"s.e. = {std.error}"</span>, </span>
<span>                           <span class="st">"t = {statistic}"</span>,</span>
<span>                           <span class="st">"p = {p.value}"</span><span class="op">)</span>,</span>
<span>             coef_omit <span class="op">=</span> <span class="st">"Intercept"</span>, </span>
<span>             exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-model-comp-zero" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabelle&nbsp;42.4— Modellvergleich mit den vier Modellen. Wir schauen in wie weit sich die Koeffizienten und Modelgüten für die einzelnen Modelle im direkten Vergleich zum vollen Modell verändert haben.</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;ZeroInfl Intercept</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;ZeroInfl rain</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;ZeroInfl rain+pop</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NegBinom intercept</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">count_grpcover</td>
<td style="text-align: center;">2.031</td>
<td style="text-align: center;">1.595</td>
<td style="text-align: center;">1.611</td>
<td style="text-align: center;">2.031</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[1.245, 3.313]</td>
<td style="text-align: center;">[0.951, 2.675]</td>
<td style="text-align: center;">[0.912, 2.845000e+00]</td>
<td style="text-align: center;">[1.245, 3.313]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 0.507</td>
<td style="text-align: center;">s.e. = 0.421</td>
<td style="text-align: center;">s.e. = 0.468</td>
<td style="text-align: center;">s.e. = 0.507</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = 2.839</td>
<td style="text-align: center;">t = 1.771</td>
<td style="text-align: center;">t = 1.642</td>
<td style="text-align: center;">t = 2.839</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">p = 0.005</td>
<td style="text-align: center;">p = 0.077</td>
<td style="text-align: center;">p = 0.101</td>
<td style="text-align: center;">p = 0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">count_popfar</td>
<td style="text-align: center;">2.591</td>
<td style="text-align: center;">1.844</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">2.591</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">[1.558, 4.310]</td>
<td style="text-align: center;">[1.069, 3.183]</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">[1.558, 4.310]</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 0.673</td>
<td style="text-align: center;">s.e. = 0.513</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">s.e. = 0.673</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = 3.667</td>
<td style="text-align: center;">t = 2.199</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">t = 3.667</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">p =</td>
<td style="text-align: center;">p = 0.028</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">p =</td>
</tr>
<tr class="odd">
<td style="text-align: left;">count_raindry</td>
<td style="text-align: center;">0.308</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.308</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[0.168, 0.564]</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">[0.168, 0.564]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 0.095</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">s.e. = 0.095</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = −3.816</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">t = −3.816</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">p =</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">p =</td>
</tr>
<tr class="even">
<td style="text-align: left;">count_rainwet</td>
<td style="text-align: center;">0.135</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.135</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">[0.059, 0.310]</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">[0.059, 0.310]</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 0.057</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">s.e. = 0.057</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = −4.726</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">t = −4.726</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">p =</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">p =</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zero_raindry</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">27.939</td>
<td style="text-align: center;">98.196</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">[0.443, 1760.078]</td>
<td style="text-align: center;">[0.000, 7.610178e+07]</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">s.e. = 59.059</td>
<td style="text-align: center;">s.e. = 679.400</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">t = 1.575</td>
<td style="text-align: center;">t = 0.663</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">p = 0.115</td>
<td style="text-align: center;">p = 0.507</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">zero_rainwet</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">83.713</td>
<td style="text-align: center;">402.409</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">[1.284, 5459.081]</td>
<td style="text-align: center;">[0.000, 4.187125e+08]</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">s.e. = 178.434</td>
<td style="text-align: center;">s.e. = 2844.677</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">t = 2.077</td>
<td style="text-align: center;">t = 0.848</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">p = 0.038</td>
<td style="text-align: center;">p = 0.396</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">zero_popfar</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.148</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">[0.022, 1.000000e+00]</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">s.e. = 0.144</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">t = −1.960</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; box-shadow: 0px 1px;"></td>
<td style="text-align: center; box-shadow: 0px 1px;"></td>
<td style="text-align: center; box-shadow: 0px 1px;"></td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.050</td>
<td style="text-align: center; box-shadow: 0px 1px;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.620</td>
<td style="text-align: center;">0.477</td>
<td style="text-align: center;">0.454</td>
<td style="text-align: center;">0.620</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.585</td>
<td style="text-align: center;">0.449</td>
<td style="text-align: center;">0.435</td>
<td style="text-align: center;">0.585</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">157.3</td>
<td style="text-align: center;">167.2</td>
<td style="text-align: center;">167.4</td>
<td style="text-align: center;">159.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">169.8</td>
<td style="text-align: center;">179.8</td>
<td style="text-align: center;">180.0</td>
<td style="text-align: center;">173.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RMSE</td>
<td style="text-align: center;">1.27</td>
<td style="text-align: center;">1.27</td>
<td style="text-align: center;">1.32</td>
<td style="text-align: center;">1.27</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Die beiden Intercept Modelle haben die kleinsten <span class="math inline">\(AIC\)</span>-Werte der vier Modelle. Darüber hinaus haben dann beide Modelle auch die höchsten <span class="math inline">\(R^2_{adj}\)</span> Werte. Beide Modelle erklären also im Verhältnis viel Varianz mit 58.5%. Auch ist der <span class="math inline">\(RMSE\)</span> Wert als Fehler bei beiden Modellen am kleinsten. Damit haben wir die Qual der Wahl, welches Modell wir nehmen. Ich würde das negative binominal Modell nehmen. Wir haben ins unseren Daten vermutlich eine Zeroinflation sowie eine Overdispersion vorliegen. Daher bietest es sich an, beides in einer negativen binominalen Regression zu berücksichtigen. Zwar sind die beiden Intercept Modelle in diesem Beispielfall von den Koeffizienten fast numerisch gleich, aber das hat eher mit dem reduzierten Beispiel zu tun, als mit dem eigentlichen Modell. In unserem Fall ist die Overdispersion nicht so extrem.</p>
<p>Wie sehe den unser negative binominal Modell aus, wenn wir mit dem Modell einmal die zu erwartenden Eidechsen vorhersagen würden? Auch das kann helfen um abzuschätzen, ob das Modelle einigermaßen funktioniert hat. Wir haben ja hier den Vorteil, dass wir nur mit kategorialen Daten arbeiten. Wir haben keine kontiniuerlichen Variablen vorliegen und darüber hinaus auch nicht so viele Variablen insgesamt.</p>
<p>Daher bauen wir uns mit <code>expand_grid()</code> erstmal einen Datensatz, der nur aus den Faktorkombinationen besteht. Wir haben also nur eine Beobachtung je Faktorkombination. Danach nutzen wir die Daten einmal in der Funktion <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> um uns die vorhergesagten Eidechsen nach dem gefitten Modell wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">newdata_tbl</span> <span class="op">&lt;-</span> <span class="fu">expand_grid</span><span class="op">(</span>grp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"open"</span>, <span class="st">"cover"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                           rain <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"no"</span>, <span class="st">"dry"</span>, <span class="st">"wet"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                           pop <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"near"</span>, <span class="st">"far"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pred_lizards</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">lizard_zero_nb_intercept_fit</span>, newdata <span class="op">=</span> <span class="va">newdata_tbl</span><span class="op">)</span> </span>
<span>  </span>
<span><span class="va">newdata_tbl</span> <span class="op">&lt;-</span> <span class="va">newdata_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>lizard <span class="op">=</span> <span class="va">pred_lizards</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nachdem wir in dem Datensatz <code>newdata_tbl</code> nun die vorhergesagten Eidechsen haben, können wir uns jetzt in der <a href="#fig-pred-lizard">Abbildung&nbsp;<span>42.5</span></a> die Zusammenhänge nochmal anschauen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">newdata_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">rain</span>, y <span class="op">=</span> <span class="va">lizard</span>, colour <span class="op">=</span> <span class="va">grp</span>, group <span class="op">=</span> <span class="va">grp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">pop</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Feuchtigkeit nach Regen"</span>, y <span class="op">=</span> <span class="st">"Anzahl der gezählten Eidechsen"</span>,</span>
<span>       color <span class="op">=</span> <span class="st">"Gruppe"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pred-lizard" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-poisson_files/figure-html/fig-pred-lizard-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption class="figure-caption">Abbildung&nbsp;42.5— Scatterplot der vorhergesagten Eidechsen in den Habitaten (<code>grp</code>), der Feuchtigkeit des Bodens nach Regen und dem Abstand zur nächsten Ortschaft.</figcaption></figure>
</div>
</div>
</div>
<p>Wir erkennen, dass mit der Erhöhung der Feuchtigkeit die Anzahl an aufgefundenen Eidechsen sinkt. Der Effekt ist nicht mehr so stark, wenn es schon einmal geregnet hat. Ebenso macht es einen Unterschied, ob wir nahe einer Siedlung sind oder nicht. Grundsätzlich finden wir immer mehr Eidechsen in geschützten Habitaten als in offenen Habitaten.</p>
</section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-dormann2013parametrische" class="csl-entry" role="listitem">
Dormann, Carsten F. 2013. <em>Parametrische Statistik</em>. Springer.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-modeling-gaussian.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-multinom.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>