<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 35&nbsp; Variablenselektion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-outlier.html" rel="next">
<link href="./stat-modeling-basic.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Variablenselektion</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen und Hunden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen, Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes-site.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren in Habitaten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Von Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimentel-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimentel-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">Klassifikation oder maschinelles Lernen</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Random Forest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-lectures-semester.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Logbuch</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-bewertungsbogen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Bewertungsbogen</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#theoretischer-hintergrund" id="toc-theoretischer-hintergrund" class="nav-link active" data-scroll-target="#theoretischer-hintergrund"> <span class="header-section-number">35.1</span> Theoretischer Hintergrund</a></li>
  <li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"> <span class="header-section-number">35.2</span> Genutzte R Pakete für das Kapitel</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"> <span class="header-section-number">35.3</span> Daten</a></li>
  <li>
<a href="#methoden-der-variablenselektion" id="toc-methoden-der-variablenselektion" class="nav-link" data-scroll-target="#methoden-der-variablenselektion"> <span class="header-section-number">35.4</span> Methoden der Variablenselektion</a>
  <ul class="collapse">
<li><a href="#per-hand" id="toc-per-hand" class="nav-link" data-scroll-target="#per-hand"> <span class="header-section-number">35.4.1</span> Per Hand</a></li>
  <li><a href="#univariate-vorselektion" id="toc-univariate-vorselektion" class="nav-link" data-scroll-target="#univariate-vorselektion"> <span class="header-section-number">35.4.2</span> Univariate Vorselektion</a></li>
  <li><a href="#sonderfall-gaussian-linear-regression" id="toc-sonderfall-gaussian-linear-regression" class="nav-link" data-scroll-target="#sonderfall-gaussian-linear-regression"> <span class="header-section-number">35.4.3</span> Sonderfall Gaussian linear Regression</a></li>
  <li><a href="#schrittweise-mit-stepaic" id="toc-schrittweise-mit-stepaic" class="nav-link" data-scroll-target="#schrittweise-mit-stepaic"> <span class="header-section-number">35.4.4</span> Schrittweise mit <code>stepAIC</code></a></li>
  <li><a href="#feature-selektion-mit-ranger" id="toc-feature-selektion-mit-ranger" class="nav-link" data-scroll-target="#feature-selektion-mit-ranger"> <span class="header-section-number">35.4.5</span> Feature Selektion mit <code>ranger</code></a></li>
  <li><a href="#feature-selektion-mit-boruta" id="toc-feature-selektion-mit-boruta" class="nav-link" data-scroll-target="#feature-selektion-mit-boruta"> <span class="header-section-number">35.4.6</span> Feature Selektion mit <code>boruta</code></a></li>
  </ul>
</li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-variable-selection" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell">

</div>
<p><em>Version vom November 02, 2022 um 11:59:29</em></p>
<section id="theoretischer-hintergrund" class="level2 page-columns page-full" data-number="35.1"><h2 data-number="35.1" class="anchored" data-anchor-id="theoretischer-hintergrund">
<span class="header-section-number">35.1</span> Theoretischer Hintergrund</h2>
<p>Die Selektion von Variablen in einem Modell. Ein schwieriges Thema. Entweder kenne ich mein Experiment und habe das Experiment so geplant, dass nur die bedeutenden Variablen mit in dem Experiment sind oder ich habe keine Ahnung. Gut, dass ist überspitzt und gemein formuliert. Wir wollen uns in diesem Kapitel den Fall anschauen, dass du sehr viele Variablen <span class="math inline">\(x\)</span> erhoben hast und nun <em>statistisch</em> bestimmen willst, welche Variablen nun mit in das finale Modell sollen. Achtung, ich spreche hier nicht von einem Blockdesign oder aber einem Feldexperiment. Da hat die Variablenselektion nichts zu suchen. Daher tritt der Fall der Variablenselektion eher in dem Feld Verhaltensbiologie oder aber auch Ökologie auf. Ebenfalls kann die Anwendung in automatisch erfassten Daten einen Sinn machen. Wir nutzen dann die Variablenselektion (eng. <em>feature selection</em>) zu Dimensionsreduktion des Datensatzes. Der Datensatz soll damit einfacher sein… ob der Datensatz das damit auch wird, ist wieder eine andere Frage.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>In diesem Kapitel prügeln wir aber einen statistischen Engel. Wir werden hier mal schauen müssen, was alles geht und was nicht. Variablen Selektion ist faktisch nicht <em>ein</em> Kapitel sondern ein Regal(kilo)meter voll mit Büchern.</p>
</div></div><p>Zu der Frage welches Verfahren denn nun das richtige Verfahren zur Selektion von Variablen ist, gibt es die Standardantwort in der Statistik: <em>Es kommt auf die Fragestellung an…</em>. Oder aber was ist wie gut implementiert, dass wir das Verfahren einigermaßen gut nutzen können. Wir gehen daher von einfach zu kompliziert und du musst dann schauen, was du nutzen willst und kannst. Wir müssen zum Beispiel unterscheiden, welcher Verteilung das Outcome <span class="math inline">\(y\)</span> folgt. Wenn wir ein normalverteiltes <span class="math inline">\(y\)</span> haben, dann haben wir andere Möglichkeiten, als wenn wir uns ein poissonverteiltes oder binominalverteiltes <span class="math inline">\(y\)</span> anschauen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Das <a href="https://olsrr.rsquaredacademy.com/articles/variable_selection.html">R Paket <code>olsrr</code></a> erlaubt eine weitreichende Variablen Selektion, wenn ein normalverteiltes Outcome <span class="math inline">\(y\)</span> vorliegt.</p>
</div></div><p>Im Folgenden will ich <em>kurz</em> die fünf Mythen der Variablenselektion von <span class="citation" data-cites="heinze2017five">Heinze und Dunkler (<a href="#ref-heinze2017five" role="doc-biblioref">2017</a>)</span> zusammenfassen. Wie immer ersetzt meine deutsche Zusammenfassung und Auswahl nicht das eigenständige Lesen der <em>englischen</em> Orgnialquelle, wenn du die Informationen in deiner Abschlussarbeit zitieren willst.</p>
<ol type="1">
<li>
<strong>Die Anzahl der Variablen in einem Modell sollte reduziert werden, bis es 10 Ereignisse pro Variable gibt.</strong> Simulationsstudien haben gezeigt, dass multivariable Modelle bei zu niedrigen Verhältnissen von Ereignissen bzw. Beobachtungen pro Variable (eng <em>events per variable</em>, abk. <em>EPV</em>) sehr instabil werden. Aktuelle Empfehlungen besagen, dass je nach Kontext mindestens 5-15 EPV verfügbar sein sollten. Wahrscheinlich sind sogar viel höhere Werte wie 50 EPV erforderlich, um annähernd stabile Ergebnisse zu erzielen.</li>
<li>
<strong>Nur Variablen mit nachgewiesener Signifikanz des univariaten Modells sollten in ein Modell aufgenommen werden.</strong> Die univariable Vorfilterung trägt nicht zur Stabilität des Auswahlprozesses bei, da sie auf stochastischen Quanten beruht und dazu führen kann, dass wichtige Anpassungsvariablen übersehen werden.</li>
<li>
<strong>Nicht signifikante Effekte sollten aus einem Modell entfernt werden.</strong> Regressionskoeffizienten hängen im Allgemeinen davon ab, welche anderen Variablen in einem Modell enthalten sind, und ändern folglich ihren Wert, wenn eine der anderen Variablen in einem Modell weggelassen wird.</li>
<li>
<strong>Der berichtete P-Wert quantifiziert den Typ-I-Fehler einer fälschlich ausgewählten Variablen.</strong> Ein P-Wert ist ein Ergebnis der Datenerhebung und -analyse und quantifiziert die Plausibilität der beobachteten Daten unter der Nullhypothese. Daher quantifiziert der P-Wert nicht den Fehler vom Typ I. Es besteht auch die Gefahr einer falschen Eliminierung von Variablen, deren Auswirkungen durch die bloße Angabe des endgültigen Modells eines Variablenauswahlverfahrens überhaupt nicht quantifiziert werden können.</li>
<li>
<strong>Variablenauswahl vereinfacht die Analyse.</strong> Für das jeweilige Problem muss eine geeignete Variablenauswahlmethode gewählt werden. Statistiker haben die Rückwärtselimination als die zuverlässigste unter den Methoden empfohlen, die sich mit Standardsoftware leicht durchführen lassen. Eine Auswahl ist eine “harte Entscheidung”, die aber oft auf vagen Größen beruht. Untersuchungen zur Modellstabilität sollten jede angewandte Variablenauswahl begleiten, um die Entscheidung für das schließlich berichtete Modell zu rechtfertigen oder zumindest die mit der Auswahl der Variablen verbundene Unsicherheit zu quantifizieren.</li>
</ol>
<p>Im Weiteren sei auch noch auf <span class="citation" data-cites="heinze2018variable">Heinze, Wallisch, und Dunkler (<a href="#ref-heinze2018variable" role="doc-biblioref">2018</a>)</span> und <span class="citation" data-cites="talbot2019descriptive">Talbot und Massamba (<a href="#ref-talbot2019descriptive" role="doc-biblioref">2019</a>)</span> verwiesen. Beide Veröffentlichungen liefern nochmal einen fundierten Block auf die Variablenselektion. Wiederum ist das natürlich nur ein winziger Ausschnitt aus der Literatur zur Variablenselektion. Im Zweifel einfach einmal bei <a href="https://scholar.google.com/scholar?hl=de&amp;as_sdt=0%2C5&amp;q=variable+selection+review&amp;btnG=">Google Scholar</a> nach Variablenselektion suchen und schauen was so in dem Feld der eigenen Forschung alles gemacht wird.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Sensitivitätsanalysen nach der Variablenselektion
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>“Variable selection should always be accompanied by sensitivity analyses to avoid wrong conclusions.”</em> <span class="citation" data-cites="heinze2017five">(<a href="#ref-heinze2017five" role="doc-biblioref">Heinze und Dunkler 2017</a>, p.&nbsp;9)</span></p>
<p>Nachdem wir Variablen aus unseren Daten entfernt haben, ist es üblich noch eine Sensitivitätsanalysen durchzuführen. Wir Vergleich dann das selektierte Modell mit <em>anderen</em> Modellen. Oder wir wollen die Frage beantworten, was hat eigentlich meine Variablenselektion am Ergebnis geändert? Habe ich eine wichtige Variable rausgeschmissen? Das machen wir dann gesammelt in dem <a href="#sec-sensitivity"><span class="quarto-unresolved-ref">sec-sensitivity</span></a> zu den Sensitivitätsanalysen.</p>
</div>
</div>
</section><section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="35.2"><h2 data-number="35.2" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">35.2</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">dlookr</span>, 
               <span class="va">MASS</span>, <span class="va">ranger</span>, <span class="va">Boruta</span>, <span class="va">broom</span>, 
               <span class="va">scales</span>, <span class="va">olsrr</span>, <span class="va">gtsummary</span>, <span class="va">parameters</span>,
               <span class="va">conflicted</span><span class="op">)</span>
<span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span>
<span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2 page-columns page-full" data-number="35.3"><h2 data-number="35.3" class="anchored" data-anchor-id="daten">
<span class="header-section-number">35.3</span> Daten</h2>
<p>Um die Variablenselektion einmal durchzuführen nurtzen wir zwei Datensätze. Zum einen den Datensatz zu den Kichererbsen in Brandenburg mit einem normalverteilten Outcome <span class="math inline">\(y\)</span> mit <code>dryweight</code>. Wir laden wieder den Datensatz in R und schauen uns einmal die Daten in <a href="#tbl-chickpea-var">Tabelle&nbsp;<span class="quarto-unresolved-ref">tbl-chickpea-var</span></a> als Auszug aus dem Tabellenblatt an.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Wir du schon siehst, wir brauchen Fallzahl um hier überhaupt was zu machen. Bitte keine Variablenselektion im niedrigen zweistelligen Bereich an Beobachtungen.</span></div></div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">chickpea_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/chickpeas.xlsx"</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir sehen, dass wir sehr viele Variablen vorleigen haben. Sind denn jetzt alle Variablen notwendig? Oder können auch ein paar Variablen raus aus dem Modell. So viele Beobachtungen haben wir mit <span class="math inline">\(n = 95\)</span> ja nicht vorliegen. Daher wollen wir an diesem Datensatz die Variablenselektion unter der Annahme eines normalverteilten <span class="math inline">\(y\)</span> durchgehen.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display column-page">
<div id="tbl-chickpea-var" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 35.1— Auszug aus dem Daten zu den Kichererbsen in Brandenburg.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 17%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">temp</th>
<th style="text-align: center;">rained</th>
<th style="text-align: center;">location</th>
<th style="text-align: center;">no3</th>
<th style="text-align: center;">fe</th>
<th style="text-align: center;">sand</th>
<th style="text-align: center;">forest</th>
<th style="text-align: center;">dryweight</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">25.26</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">5.56</td>
<td style="text-align: center;">4.43</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">&gt;1000m</td>
<td style="text-align: center;">255.4</td>
</tr>
<tr class="even">
<td style="text-align: center;">21.4</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">9.15</td>
<td style="text-align: center;">2.58</td>
<td style="text-align: center;">51.17</td>
<td style="text-align: center;">&lt;1000m</td>
<td style="text-align: center;">217.55</td>
</tr>
<tr class="odd">
<td style="text-align: center;">27.84</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">5.57</td>
<td style="text-align: center;">2.19</td>
<td style="text-align: center;">55.57</td>
<td style="text-align: center;">&lt;1000m</td>
<td style="text-align: center;">232.52</td>
</tr>
<tr class="even">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="odd">
<td style="text-align: center;">29.04</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">5.64</td>
<td style="text-align: center;">2.87</td>
<td style="text-align: center;">53.27</td>
<td style="text-align: center;">&gt;1000m</td>
<td style="text-align: center;">228.58</td>
</tr>
<tr class="even">
<td style="text-align: center;">24.11</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">4.31</td>
<td style="text-align: center;">3.66</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">&gt;1000m</td>
<td style="text-align: center;">251.75</td>
</tr>
<tr class="odd">
<td style="text-align: center;">28.88</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">7.92</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">65.75</td>
<td style="text-align: center;">&lt;1000m</td>
<td style="text-align: center;">274.46</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Was wir auch noch wissen, ist wie die Effekte in den Daten <em>wirklich</em> sind. Die Daten wurden ja künstlich erstellt, deshalb hier die Ordnung der Effektstärke für jede Variable. Im Prinzip müsste diese Reihenfolge auch bei der Variablenselektion rauskommen. Schauen wir mal, was wir erhalten.</p>
<p><span class="math display">\[
y \sim \beta_0 + 3 * sand + 2 * temp + 1.5 * rained - 1.2 * forest + 1.1 * no3  
\]</span></p>
<p>Viele Beispiele laufen immer unter der Annahme der Normalverteilung. Deshalb als zweites Beispiel nochmal die Daten von den infizierten Ferkeln mit einem binomialverteilten Outcome <span class="math inline">\(y\)</span> mit <code>infected</code>. Auch hier können wir uns den Auszug der Daten in <a href="#tbl-pigs-var">Tabelle&nbsp;<span class="quarto-unresolved-ref">tbl-pigs-var</span></a> anschauen.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/infected_pigs.xlsx"</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das schöne an diesem Datensatz ist jetzt, dass wir mit <span class="math inline">\(n = 412\)</span> Beobachtungen sehr viele Daten vorliegen haben. Daher können wir auch alle Methoden gut verwenden und haben nicht das Problem einer zu geringen Fallzahl.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display column-page">
<div id="tbl-pigs-var" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 35.2— Auszug aus dem Daten zu den kranken Ferkeln.</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">age</th>
<th style="text-align: center;">sex</th>
<th style="text-align: center;">location</th>
<th style="text-align: center;">activity</th>
<th style="text-align: center;">crp</th>
<th style="text-align: center;">frailty</th>
<th style="text-align: center;">bloodpressure</th>
<th style="text-align: center;">weight</th>
<th style="text-align: center;">creatinin</th>
<th style="text-align: center;">infected</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">61</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">15.31</td>
<td style="text-align: center;">22.38</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">49.88</td>
<td style="text-align: center;">16.94</td>
<td style="text-align: center;">3.07</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">53</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">13.01</td>
<td style="text-align: center;">18.64</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">58.2</td>
<td style="text-align: center;">17.95</td>
<td style="text-align: center;">4.88</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">66</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">11.31</td>
<td style="text-align: center;">18.76</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">56.8</td>
<td style="text-align: center;">19.02</td>
<td style="text-align: center;">3.98</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="odd">
<td style="text-align: center;">61</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">15.26</td>
<td style="text-align: center;">23.1</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">58.5</td>
<td style="text-align: center;">18.23</td>
<td style="text-align: center;">2.73</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">59</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">13.13</td>
<td style="text-align: center;">20.23</td>
<td style="text-align: center;">pre-frail</td>
<td style="text-align: center;">57.33</td>
<td style="text-align: center;">17.21</td>
<td style="text-align: center;">5.42</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">63</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">10.01</td>
<td style="text-align: center;">19.89</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">55.85</td>
<td style="text-align: center;">17.76</td>
<td style="text-align: center;">6.18</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Auch in diesem Beispiel wurden die Daten von mir mit folgenden Effekten generiert. Schauen wir mal, was die Variablenselektion bei der hohen Fallzahl mit den Variablen macht bzw. welche Sortierung am Ende rauskommt.</p>
<p><span class="math display">\[
y \sim \beta_0 + 2 * crp + 0.5 * sex + 0.5 * frailty + 0.2 * bloodpressure + 0.05 * creatinin +  0.01 * weight
\]</span></p>
<p>Damit haben wir unsere beiden Beispiel und jetzt gehen wir mal eine Auswahl an Methoden zur Variablenselektion durch. Besonders hier, haltet den statistsichen Engel nah bei euch. Es wird leider etwas ruppig für den statistischen Engel.</p>
</section><section id="methoden-der-variablenselektion" class="level2 page-columns page-full" data-number="35.4"><h2 data-number="35.4" class="anchored" data-anchor-id="methoden-der-variablenselektion">
<span class="header-section-number">35.4</span> Methoden der Variablenselektion</h2>
<p>In den folgenden Abschnitten wollen wir uns eine Reihe an Methoden anschauen um eine Variablenselektion durchzuführen. Dabei gehen wir von einfach nach komplex. Wobei das komplex eher die Methode und nicht die Anwendung meint. Wir nutzen R Pakete und gehen nicht sehr ins Detail <em>wie</em> der Algorithmus jetzt die Auswahl trifft. Für den Hintergrund sind dann die Verweise auf die anderen Kapitel.</p>
<section id="per-hand" class="level3" data-number="35.4.1"><h3 data-number="35.4.1" class="anchored" data-anchor-id="per-hand">
<span class="header-section-number">35.4.1</span> Per Hand</h3>
<p>Manchmal ist der Anfang auch das Ende. Wir müssen ja gar keinen Algorithmus auf unsere Daten loslassen um eine Variablenselektion durchzuführen. Deshalb möchte ich gleich den ersten Abschnitt mit einem Zitat von <span class="citation" data-cites="heinze2017five">Heinze und Dunkler (<a href="#ref-heinze2017five" role="doc-biblioref">2017</a>)</span> beginnen.</p>
<p><em>“Oft gibt es keinen wissenschaftlichen Grund, eine (algorithmische) Variablenauswahl durchzuführen. Insbesondere erfordern Methoden der (algorithmische) Variablenselektion einen viel größeren Stichprobenumfang als die Schätzung eines multiplen Modells mit einem festen Satz von Prädiktoren auf der Grundlage (klinischer) Erfahrung.”</em> <span class="citation" data-cites="heinze2017five">(Übersetzt und ergänzt nach <a href="#ref-heinze2017five" role="doc-biblioref">Heinze und Dunkler 2017</a>, p.&nbsp;9)</span></p>
<p>Fazit dieses kurzen Abschnitts. Wir können auf alles Folgende einfach verzichten und uns überlegen welche Variablen <em>sinnvollerweise</em> mit ins Modell sollen und das mit unserem Expertenwissen begründen. Gut, und was ist, wenn ich kein Experte bin? Oder wir aber <em>wirklich</em> Neuland betreten? Dann können wir eine Reihe anderer Verfahren nutzen um uns algortimisch einer Wahrheit anzunähern.</p>
</section><section id="univariate-vorselektion" class="level3 page-columns page-full" data-number="35.4.2"><h3 data-number="35.4.2" class="anchored" data-anchor-id="univariate-vorselektion">
<span class="header-section-number">35.4.2</span> Univariate Vorselektion</h3>
<p>Und weiter geht es mit Zitaten aus <span class="citation" data-cites="heinze2017five">Heinze und Dunkler (<a href="#ref-heinze2017five" role="doc-biblioref">2017</a>)</span> zu der Variablenselektion. Dazu musst du wissen, dass die univariate Vorselektion sehr beliebt war und auch noch ist. Denn die univariate Vorselektion ist einfach durchzuführen und eben auch gut darzustellen.</p>
<p><em>“Obwohl die univariable Vorfilterung nachvollziehbar und mit Standardsoftware leicht durchführbar ist, sollte man sie besser ganz vergessen, da sie für die Erstellung multivariabler Modelle weder Voraussetzung noch von Nutzen ist.”</em> <span class="citation" data-cites="heinze2017five">(Übersetzt nach <a href="#ref-heinze2017five" role="doc-biblioref">Heinze und Dunkler 2017</a>, p.&nbsp;8)</span></p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Ich sage immer, auch mit einem Hammer kann man Scheiben putzen. Halt nur einmal… Deshalb auch hier die univariate Variante der Vorselektion.</span></div></div>
<p>Wir sehen also, eigentlich ist die univariate Variablensleketion nicht so das gelbe vom Ei, aber vielleicht musst die Variablenselektion durchführen, so dass her die Lösung in R einmal dargestellt ist. Wir nutzen einmal die gaussian lineare Regression für den Kichererbsendatensatz. Es ist eine ganze Reihe an Code, das hat aber eher damit zu tun, dass wir die Modellausgabe noch filtern und anpassen wollen. Die eigentliche Idee ist simple. Wir nehmen unseren Datensatz und pipen den Datensatz in select und entfernen unser Outcome <code>drymatter</code>. Nun iterieren wir für <em>jede</em> Variable <code>.x</code> im Datensatz mit der Funktion <code>map()</code> und rechnen in jeder Iteration eine gaussian lineare Regression. Dann entferne wir noch den Intercept und sortieren nach den <span class="math inline">\(p\)</span>-Werten.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">chickpea_tbl</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">dryweight</span><span class="op">)</span> <span class="op">%&gt;%</span>                   
  <span class="fu">map</span><span class="op">(</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">dryweight</span> <span class="op">~</span> <span class="va">.x</span>, data <span class="op">=</span> <span class="va">chickpea_tbl</span>, family <span class="op">=</span> <span class="va">gaussian</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>    
  <span class="fu">map</span><span class="op">(</span><span class="va">tidy</span><span class="op">)</span> <span class="op">%&gt;%</span>                          
  <span class="fu">map</span><span class="op">(</span><span class="va">filter</span>, <span class="va">term</span> <span class="op">!=</span> <span class="st">"(Intercept)"</span><span class="op">)</span> <span class="op">%&gt;%</span>       
  <span class="fu">map</span><span class="op">(</span><span class="va">select</span>, <span class="op">-</span><span class="va">term</span>, <span class="op">-</span><span class="va">std.error</span>, <span class="op">-</span><span class="va">statistic</span><span class="op">)</span> <span class="op">%&gt;%</span>                        
  <span class="fu">bind_rows</span><span class="op">(</span>.id<span class="op">=</span><span class="st">"term"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">arrange</span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>p.value <span class="op">=</span> <span class="fu">pvalue</span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span>,
         estimate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 x 3
  term     estimate p.value
  &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;  
1 sand         2.93 &lt;0.001 
2 location   -10.2  0.028  
3 no3          2.06 0.080  
4 temp         1.08 0.090  
5 rained       3.96 0.255  
6 location    -4.02 0.256  
7 fe           1.31 0.386  
8 forest       2.81 0.403  </code></pre>
</div>
</div>
<p>Würden wir nur nach dem Signifikanzniveau von 5% gehen, dann hätten wir die Variablen <code>sand</code> und <code>location</code> selektiert. Bei der selektion mit dem <span class="math inline">\(p\)</span>-Wert wird aber eher eine Schwelle von 15.7% vorgeschlagen <span class="citation" data-cites="heinze2017five">(<a href="#ref-heinze2017five" role="doc-biblioref">Heinze und Dunkler 2017</a>, p.&nbsp;9)</span>. Daher würden wir auch noch <code>no3</code> und <code>temp</code> mit Selektieren und in unser Modell nehmen.</p>
<p>Es gibt ja immer zwei Wege nach Rom. Deshalb hier auch nochmal die Funktion <code>tbl_uvregression()</code> aus dem R Paket <code>gtsummary</code>, die es erlaubt die univariaten Regressionen über alle Variablen laufen zu lassen. Wir kriegen dann auch eine schöne <a href="#tbl-chick-gt">Tabelle&nbsp;<span class="quarto-unresolved-ref">tbl-chick-gt</span></a> wieder.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Das R Paket <code>gtsummary</code> erlaubt es Ergebnisse der Regression in dem <a href="https://www.danieldsjoberg.com/gtsummary/articles/tbl_regression.html">Tutorial: tbl_regression</a> gut darzustellen.</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">chickpea_tbl</span> <span class="op">%&gt;%</span>
  <span class="fu">tbl_uvregression</span><span class="op">(</span>
    method <span class="op">=</span> <span class="va">glm</span>,
    y <span class="op">=</span> <span class="va">dryweight</span>,
    method.args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>family <span class="op">=</span> <span class="va">gaussian</span><span class="op">)</span>,
    pvalue_fun <span class="op">=</span> <span class="op">~</span><span class="fu">style_pvalue</span><span class="op">(</span><span class="va">.x</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">add_global_p</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>  <span class="co"># add global p-value </span>
  <span class="fu">add_q</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>         <span class="co"># adjusts global p-values for multiple testing</span>
  <span class="fu">bold_p</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>        <span class="co"># bold p-values under a given threshold (default 0.05)</span>
  <span class="fu">bold_p</span><span class="op">(</span>t <span class="op">=</span> <span class="fl">0.10</span>, q <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># now bold q-values under the threshold of 0.10</span>
  <span class="fu">bold_labels</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-chick-gt" class="anchored">

<div id="lthacahjzx" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lthacahjzx .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lthacahjzx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lthacahjzx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lthacahjzx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lthacahjzx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lthacahjzx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lthacahjzx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lthacahjzx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lthacahjzx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lthacahjzx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lthacahjzx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lthacahjzx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lthacahjzx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lthacahjzx .gt_from_md > :first-child {
  margin-top: 0;
}

#lthacahjzx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lthacahjzx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lthacahjzx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#lthacahjzx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#lthacahjzx .gt_row_group_first td {
  border-top-width: 2px;
}

#lthacahjzx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lthacahjzx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#lthacahjzx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#lthacahjzx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lthacahjzx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lthacahjzx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lthacahjzx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lthacahjzx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lthacahjzx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lthacahjzx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lthacahjzx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lthacahjzx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lthacahjzx .gt_left {
  text-align: left;
}

#lthacahjzx .gt_center {
  text-align: center;
}

#lthacahjzx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lthacahjzx .gt_font_normal {
  font-weight: normal;
}

#lthacahjzx .gt_font_bold {
  font-weight: bold;
}

#lthacahjzx .gt_font_italic {
  font-style: italic;
}

#lthacahjzx .gt_super {
  font-size: 65%;
}

#lthacahjzx .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#lthacahjzx .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#lthacahjzx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#lthacahjzx .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#lthacahjzx .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#lthacahjzx .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
<caption>Tabelle 35.3—  Univariate Regression mit der Funktion tbl_uvregression(). </caption>
  
  <thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>
</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>q-value</strong><sup class="gt_footnote_marks">2</sup>
</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">temp</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center">1.1</td>
<td class="gt_row gt_center">-0.16, 2.3</td>
<td class="gt_row gt_center">0.087</td>
<td class="gt_row gt_center">0.15</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">rained</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.25</td>
<td class="gt_row gt_center">0.35</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">high</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">low</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">4.0</td>
<td class="gt_row gt_center">-2.8, 11</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">location</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.082</td>
<td class="gt_row gt_center">0.15</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">north</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">northeast</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-4.0</td>
<td class="gt_row gt_center">-11, 2.9</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">west</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-10</td>
<td class="gt_row gt_center">-19, -1.3</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">no3</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center">2.1</td>
<td class="gt_row gt_center">-0.22, 4.4</td>
<td class="gt_row gt_center">0.077</td>
<td class="gt_row gt_center">0.15</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">fe</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center">1.3</td>
<td class="gt_row gt_center">-1.6, 4.3</td>
<td class="gt_row gt_center">0.38</td>
<td class="gt_row gt_center">0.40</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">sand</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center">2.9</td>
<td class="gt_row gt_center">2.6, 3.2</td>
<td class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td>
<td class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">forest</td>
<td class="gt_row gt_center">95</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.40</td>
<td class="gt_row gt_center">0.40</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">&lt;1000m</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">&gt;1000m</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">2.8</td>
<td class="gt_row gt_center">-3.7, 9.4</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
</tbody>
<tfoot class="gt_footnotes">
<tr>
<td class="gt_footnote" colspan="6">
<sup class="gt_footnote_marks">1</sup> CI = Confidence Interval</td>
    </tr>
<tr>
<td class="gt_footnote" colspan="6">
<sup class="gt_footnote_marks">2</sup> False discovery rate correction for multiple testing</td>
    </tr>
</tfoot>
</table>
</div>
</div>
</div>
</div>
<p>Nun führen wir die univariate Regression erneut auf den Ferkeldaten aus. Hier ändern wir nur die <code>family = binomial</code>, da wir hier jetzt eine logistische lineare Regression rechnen müssen. Unser Outcome <code>infected</code> ist ja <span class="math inline">\(0/1\)</span> codiert. Sonst ändert sich der Code nicht.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">infected</span><span class="op">)</span> <span class="op">%&gt;%</span>                   
  <span class="fu">map</span><span class="op">(</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">.x</span>, data <span class="op">=</span> <span class="va">pig_tbl</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>    
  <span class="fu">map</span><span class="op">(</span><span class="va">tidy</span><span class="op">)</span> <span class="op">%&gt;%</span>                          
  <span class="fu">map</span><span class="op">(</span><span class="va">filter</span>, <span class="va">term</span> <span class="op">!=</span> <span class="st">"(Intercept)"</span><span class="op">)</span> <span class="op">%&gt;%</span>       
  <span class="fu">map</span><span class="op">(</span><span class="va">select</span>, <span class="op">-</span><span class="va">term</span>, <span class="op">-</span><span class="va">std.error</span>, <span class="op">-</span><span class="va">statistic</span><span class="op">)</span> <span class="op">%&gt;%</span>                        
  <span class="fu">bind_rows</span><span class="op">(</span>.id<span class="op">=</span><span class="st">"term"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">arrange</span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>p.value <span class="op">=</span> <span class="fu">pvalue</span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span>,
         estimate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 x 3
   term          estimate p.value
   &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;  
 1 crp               1.01 &lt;0.001 
 2 bloodpressure     0.06 0.058  
 3 location         -0.35 0.192  
 4 sex               0.23 0.258  
 5 location         -0.27 0.360  
 6 activity          0.04 0.474  
 7 age               0.02 0.489  
 8 location         -0.19 0.528  
 9 frailty          -0.12 0.719  
10 weight            0.02 0.728  
11 frailty           0.08 0.796  
12 creatinin        -0.01 0.857  </code></pre>
</div>
</div>
<p>In diesem Fall reicht die Schwelle von 15.7% nur für zwei Variablen <span class="citation" data-cites="heinze2017five">(<a href="#ref-heinze2017five" role="doc-biblioref">Heinze und Dunkler 2017</a>, p.&nbsp;9)</span>. Wir erhalten die Variablen <code>crp</code> und <code>bloodpressure</code> für das Modell selektiert.</p>
<p>In der <a href="#tbl-pig-gt">Tabelle&nbsp;<span class="quarto-unresolved-ref">tbl-pig-gt</span></a> sehen wir dann nochmal die Anwendung der Funktion <code>tbl_uvregression()</code> auf den Ferkeldatensatz. Ich musste hier die Option <code>pvalue_fun = ~style_pvalue(.x, digits = 2)</code> entfernen, da sonst die Variable <code>crp</code> keinen <span class="math inline">\(p\)</span>-Wert erhält. Leider sehe ich den <span class="math inline">\(p\)</span>-Wert mit <span class="math inline">\(&lt;0.001\)</span> in meiner Ausgabe in R aber wie du siehst, wird die Tabelle auf der Webseite nicht korrekt angezeigt. Das Problem von automatischen Tabellen. Ein Fluch und Segen zugleich. Du musst immer wieder überprüfen, ob die Optionen dann auch für sich und deine Analyse passen.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span> <span class="op">%&gt;%</span>
  <span class="fu">tbl_uvregression</span><span class="op">(</span>
    method <span class="op">=</span> <span class="va">glm</span>,
    y <span class="op">=</span> <span class="va">infected</span>,
    method.args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span>,
    exponentiate <span class="op">=</span> <span class="cn">TRUE</span>
  <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">add_global_p</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>  <span class="co"># add global p-value </span>
  <span class="fu">add_nevent</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>    <span class="co"># add number of events of the outcome</span>
  <span class="fu">add_q</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>         <span class="co"># adjusts global p-values for multiple testing</span>
  <span class="fu">bold_p</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>        <span class="co"># bold p-values under a given threshold (default 0.05)</span>
  <span class="fu">bold_p</span><span class="op">(</span>t <span class="op">=</span> <span class="fl">0.10</span>, q <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># now bold q-values under the threshold of 0.10</span>
  <span class="fu">bold_labels</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-pig-gt" class="anchored">

<div id="ypuaqkbosv" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ypuaqkbosv .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ypuaqkbosv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ypuaqkbosv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ypuaqkbosv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ypuaqkbosv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ypuaqkbosv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ypuaqkbosv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ypuaqkbosv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ypuaqkbosv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ypuaqkbosv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ypuaqkbosv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ypuaqkbosv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ypuaqkbosv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ypuaqkbosv .gt_from_md > :first-child {
  margin-top: 0;
}

#ypuaqkbosv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ypuaqkbosv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ypuaqkbosv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ypuaqkbosv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ypuaqkbosv .gt_row_group_first td {
  border-top-width: 2px;
}

#ypuaqkbosv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ypuaqkbosv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ypuaqkbosv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ypuaqkbosv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ypuaqkbosv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ypuaqkbosv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ypuaqkbosv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ypuaqkbosv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ypuaqkbosv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ypuaqkbosv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ypuaqkbosv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ypuaqkbosv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ypuaqkbosv .gt_left {
  text-align: left;
}

#ypuaqkbosv .gt_center {
  text-align: center;
}

#ypuaqkbosv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ypuaqkbosv .gt_font_normal {
  font-weight: normal;
}

#ypuaqkbosv .gt_font_bold {
  font-weight: bold;
}

#ypuaqkbosv .gt_font_italic {
  font-style: italic;
}

#ypuaqkbosv .gt_super {
  font-size: 65%;
}

#ypuaqkbosv .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#ypuaqkbosv .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#ypuaqkbosv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ypuaqkbosv .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#ypuaqkbosv .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#ypuaqkbosv .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
<caption>Tabelle 35.4—  Univariate Regression mit der Funktion tbl_uvregression(). </caption>
  
  <thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Event N</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>OR</strong><sup class="gt_footnote_marks">1</sup>
</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>
</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>q-value</strong><sup class="gt_footnote_marks">2</sup>
</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">age</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center">1.02</td>
<td class="gt_row gt_center">0.97, 1.06</td>
<td class="gt_row gt_center">0.5</td>
<td class="gt_row gt_center">0.8</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">sex</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.3</td>
<td class="gt_row gt_center">0.8</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">female</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">male</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">1.26</td>
<td class="gt_row gt_center">0.84, 1.90</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">location</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.6</td>
<td class="gt_row gt_center">0.8</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">north</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">northeast</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.76</td>
<td class="gt_row gt_center">0.43, 1.36</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">northwest</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.71</td>
<td class="gt_row gt_center">0.42, 1.19</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">west</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.83</td>
<td class="gt_row gt_center">0.46, 1.49</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">activity</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center">1.05</td>
<td class="gt_row gt_center">0.93, 1.18</td>
<td class="gt_row gt_center">0.5</td>
<td class="gt_row gt_center">0.8</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">crp</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center">2.73</td>
<td class="gt_row gt_center">2.23, 3.42</td>
<td class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td>
<td class="gt_row gt_center" style="font-weight: bold;">&lt;0.001</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">frailty</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.7</td>
<td class="gt_row gt_center">0.8</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">frail</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">pre-frail</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.89</td>
<td class="gt_row gt_center">0.46, 1.70</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">robust</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">1.08</td>
<td class="gt_row gt_center">0.58, 2.00</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">bloodpressure</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center">1.06</td>
<td class="gt_row gt_center">1.00, 1.12</td>
<td class="gt_row gt_center">0.057</td>
<td class="gt_row gt_center">0.3</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">weight</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center">1.02</td>
<td class="gt_row gt_center">0.90, 1.17</td>
<td class="gt_row gt_center">0.7</td>
<td class="gt_row gt_center">0.8</td>
</tr>
<tr>
<td class="gt_row gt_left" style="font-weight: bold;">creatinin</td>
<td class="gt_row gt_center">412</td>
<td class="gt_row gt_center">257</td>
<td class="gt_row gt_center">0.99</td>
<td class="gt_row gt_center">0.85, 1.14</td>
<td class="gt_row gt_center">0.9</td>
<td class="gt_row gt_center">0.9</td>
</tr>
</tbody>
<tfoot class="gt_footnotes">
<tr>
<td class="gt_footnote" colspan="7">
<sup class="gt_footnote_marks">1</sup> OR = Odds Ratio, CI = Confidence Interval</td>
    </tr>
<tr>
<td class="gt_footnote" colspan="7">
<sup class="gt_footnote_marks">2</sup> False discovery rate correction for multiple testing</td>
    </tr>
</tfoot>
</table>
</div>
</div>
</div>
</div>
<p>Neben der Berechnung von univariaten logistischen Regressionen ist auch die Darstellung der Daten in einer <a href="#tbl-pigs-table1">Tabelle&nbsp;<span class="quarto-unresolved-ref">tbl-pigs-table1</span></a> bei Medizinern sehr beliebt. Deshalb an dieser Stelle auch die Tabelle 1 (eng. <em>table 1</em>) für die Zusammenfasung der Daten getrennt nach dem Infektionsstatus zusammen mit dem <span class="math inline">\(p\)</span>-Wert. Ich nutze hier die Funktion <code>tbl_summary()</code> aus dem R Paket <code>gtsummary</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span> <span class="op">%&gt;%</span> <span class="fu">tbl_summary</span><span class="op">(</span>by <span class="op">=</span> <span class="va">infected</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu">add_p</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-pigs-table1" class="anchored">

<div id="actazldkhc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#actazldkhc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#actazldkhc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#actazldkhc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#actazldkhc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#actazldkhc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#actazldkhc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#actazldkhc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#actazldkhc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#actazldkhc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#actazldkhc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#actazldkhc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#actazldkhc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#actazldkhc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#actazldkhc .gt_from_md > :first-child {
  margin-top: 0;
}

#actazldkhc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#actazldkhc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#actazldkhc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#actazldkhc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#actazldkhc .gt_row_group_first td {
  border-top-width: 2px;
}

#actazldkhc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#actazldkhc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#actazldkhc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#actazldkhc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#actazldkhc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#actazldkhc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#actazldkhc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#actazldkhc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#actazldkhc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#actazldkhc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#actazldkhc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#actazldkhc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#actazldkhc .gt_left {
  text-align: left;
}

#actazldkhc .gt_center {
  text-align: center;
}

#actazldkhc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#actazldkhc .gt_font_normal {
  font-weight: normal;
}

#actazldkhc .gt_font_bold {
  font-weight: bold;
}

#actazldkhc .gt_font_italic {
  font-style: italic;
}

#actazldkhc .gt_super {
  font-size: 65%;
}

#actazldkhc .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#actazldkhc .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#actazldkhc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#actazldkhc .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#actazldkhc .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#actazldkhc .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
<caption>Tabelle 35.5—  Zusammenfasung der Daten getrennt nach dem Infektionsstatus zusammen mit dem p-Wert. </caption>
  
  <thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>0</strong>, N = 155<sup class="gt_footnote_marks">1</sup>
</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>1</strong>, N = 257<sup class="gt_footnote_marks">1</sup>
</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>p-value</strong><sup class="gt_footnote_marks">2</sup>
</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left">age</td>
<td class="gt_row gt_center">60.0 (57.0, 63.0)</td>
<td class="gt_row gt_center">60.0 (57.0, 63.0)</td>
<td class="gt_row gt_center">0.5</td>
</tr>
<tr>
<td class="gt_row gt_left">sex</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.3</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">female</td>
<td class="gt_row gt_center">66 (43%)</td>
<td class="gt_row gt_center">95 (37%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">male</td>
<td class="gt_row gt_center">89 (57%)</td>
<td class="gt_row gt_center">162 (63%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left">location</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.6</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">north</td>
<td class="gt_row gt_center">40 (26%)</td>
<td class="gt_row gt_center">81 (32%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">northeast</td>
<td class="gt_row gt_center">33 (21%)</td>
<td class="gt_row gt_center">51 (20%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">northwest</td>
<td class="gt_row gt_center">51 (33%)</td>
<td class="gt_row gt_center">73 (28%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">west</td>
<td class="gt_row gt_center">31 (20%)</td>
<td class="gt_row gt_center">52 (20%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left">activity</td>
<td class="gt_row gt_center">13.35 (12.29, 14.34)</td>
<td class="gt_row gt_center">13.24 (12.25, 14.53)</td>
<td class="gt_row gt_center">0.7</td>
</tr>
<tr>
<td class="gt_row gt_left">crp</td>
<td class="gt_row gt_center">19.12 (18.17, 19.92)</td>
<td class="gt_row gt_center">20.66 (19.85, 21.46)</td>
<td class="gt_row gt_center">&lt;0.001</td>
</tr>
<tr>
<td class="gt_row gt_left">frailty</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.7</td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">frail</td>
<td class="gt_row gt_center">20 (13%)</td>
<td class="gt_row gt_center">33 (13%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">pre-frail</td>
<td class="gt_row gt_center">54 (35%)</td>
<td class="gt_row gt_center">79 (31%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">robust</td>
<td class="gt_row gt_center">81 (52%)</td>
<td class="gt_row gt_center">145 (56%)</td>
<td class="gt_row gt_center"></td>
</tr>
<tr>
<td class="gt_row gt_left">bloodpressure</td>
<td class="gt_row gt_center">56.8 (53.9, 58.6)</td>
<td class="gt_row gt_center">57.0 (54.9, 59.0)</td>
<td class="gt_row gt_center">0.10</td>
</tr>
<tr>
<td class="gt_row gt_left">weight</td>
<td class="gt_row gt_center">18.36 (17.32, 19.34)</td>
<td class="gt_row gt_center">18.33 (17.36, 19.44)</td>
<td class="gt_row gt_center">0.9</td>
</tr>
<tr>
<td class="gt_row gt_left">creatinin</td>
<td class="gt_row gt_center">4.82 (4.06, 5.88)</td>
<td class="gt_row gt_center">4.97 (3.97, 5.87)</td>
<td class="gt_row gt_center">0.8</td>
</tr>
</tbody>
<tfoot class="gt_footnotes">
<tr>
<td class="gt_footnote" colspan="4">
<sup class="gt_footnote_marks">1</sup> Median (IQR); n (%)</td>
    </tr>
<tr>
<td class="gt_footnote" colspan="4">
<sup class="gt_footnote_marks">2</sup> Wilcoxon rank sum test; Pearson's Chi-squared test</td>
    </tr>
</tfoot>
</table>
</div>
</div>
</div>
</div>
<p>Tja, auch hier ist dann die Frage, wie sortiere ich Variablen. Da es sich bei dem <em>table 1</em>-Stil um eine Übersichtstabelle handelt, ist die Tabelle nach den Variablen sortiert. Auch hier finden wir dann die Variablen <code>crp</code> und <code>bloodpressure</code> wieder. Das Problem hierbei ist natürlich, dass sich die <span class="math inline">\(p\)</span>-Werte unterscheiden. Das muss ja auch so sein, denn eine logitische Regression ist nun mal kein <em>Wilcoxon rank sum test</em> oder ein <em>Pearson’s Chi-squared test</em>.</p>
<p>Fassen wir als Fazit dieses Abschnitts zusammen wie unsere Modelle nach der Variablenslektion aussehen würde. In unserem Beispiel für die Kichererbsen im sandigen Brandenburg würden wir dann folgendes Modell nehmen.</p>
<p><span class="math display">\[
y \sim \beta_0 + sand + location + no3 + temp
\]</span></p>
<p>Unsere infizierten Ferkel würden dann folgendes selektiertes Modell erhalten.</p>
<p><span class="math display">\[
y \sim \beta_0 + crp + bloodpressure
\]</span></p>
<p>Schauen wir mal, was die anderen Algorithmen noch so finden.</p>
</section><section id="sonderfall-gaussian-linear-regression" class="level3" data-number="35.4.3"><h3 data-number="35.4.3" class="anchored" data-anchor-id="sonderfall-gaussian-linear-regression">
<span class="header-section-number">35.4.3</span> Sonderfall Gaussian linear Regression</h3>
<p>Für die gaussian lineare Regression gibt es mit dem R Paket <code>oslrr</code> eine große Auswahl an <a href="https://olsrr.rsquaredacademy.com/articles/variable_selection.html">Variable Selection Methods</a>. Einfach mal die Möglichkeiten anschauen, die dort angeboten werden. Wir nutzen jetzt nicht alles was din <code>oslrr</code> möglich ist, sondern nur eien Auswahl. Zuerst müssen wir wieder unser Modell fitten. Wir nehmen alle Variablen mit rein und nutzen die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> für ein lineares Modell mit einem normalverteilten Outcome <span class="math inline">\(y\)</span> mit <code>dryweight</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">chickenpea_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">dryweight</span> <span class="op">~</span> <span class="va">temp</span> <span class="op">+</span> <span class="va">rained</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">no3</span> <span class="op">+</span> <span class="va">fe</span> <span class="op">+</span> <span class="va">sand</span> <span class="op">+</span> <span class="va">forest</span>, 
                     data <span class="op">=</span> <span class="va">chickpea_tbl</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nun gibt es wirklich viele Lösungen in dem R Paket <code>oslrr</code>. Ich möchte einmal die Variante mit <code>ols_step_all_possible</code> präsnetieren. In dem Fall rechnen wir alle Modelle die gehen. Und damit meine ich wirklich alle Modelle. Deshalb filtern wir noch nach dem <span class="math inline">\(R^2_{adj}\)</span> um nicht von dem Angebot erschlagen zu werden. Darüber hinaus möchte ich nur Modelle sehen, die maximal vier Variablen mit in dem Modell haben. Das ist zufällig von mir gewählt… ich will ja ein kleineres Modell haben.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">ols_step_all_possible</span><span class="op">(</span><span class="va">chickenpea_fit</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="va">as_tibble</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">adjr</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&lt;=</span> <span class="fl">4</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">select</span><span class="op">(</span><span class="va">predictors</span>, <span class="va">adjr</span>, <span class="va">aic</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 98 x 3
   predictors                 adjr   aic
   &lt;chr&gt;                     &lt;dbl&gt; &lt;dbl&gt;
 1 temp rained no3 sand      0.873  598.
 2 temp location no3 sand    0.873  599.
 3 temp no3 sand             0.873  597.
 4 temp no3 sand forest      0.872  598.
 5 temp no3 fe sand          0.872  598.
 6 temp rained fe sand       0.865  604.
 7 temp rained sand          0.865  603.
 8 temp rained sand forest   0.864  605.
 9 temp rained location sand 0.864  606.
10 temp location fe sand     0.864  606.
# ... with 88 more rows</code></pre>
</div>
</div>
<p>Eine Alternative ist die Funktion <code>ols_step_backward_aic()</code>, die es erlaubt die Selektion anhand dem <span class="math inline">\(AIC\)</span>-Wert zu machen. Der <span class="math inline">\(AIC\)</span>-Wert beschreibt die Güte eines Modells und je kleiner der <span class="math inline">\(AIC\)</span>-Wert ist, desto besser ist das Modell im Vergleich zu anderen Modellen gleicher Art. Da der <span class="math inline">\(AIC\)</span>-Wert von den Daten abhängt in denen der <span class="math inline">\(AIC\)</span>-Wert geschätzt wurde, können verschiedene <span class="math inline">\(AIC\)</span>-Werte nicht übergreifend vergleichen werden.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">chick_step_aic</span> <span class="op">&lt;-</span> <span class="fu">ols_step_backward_aic</span><span class="op">(</span><span class="va">chickenpea_fit</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <a href="#fig-ols-diag">Abbildung&nbsp;<span class="quarto-unresolved-ref">fig-ols-diag</span></a> sehen wir einmal den Verlauf der <span class="math inline">\(AIC\)</span>-Wert durch die Entfernung der jeweiligen Variable. Wenn du auf die y-Achse schaust, ist der Effekt numerisch nicht sehr groß. Davon darf man sich aber nicht beeindrucken lassen., Wir erhalten ein besseres Modell, wenn wir Variablen entfernen. Darüber hinaus sehen wir auch eine Sättigung.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">chick_step_aic</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ols-diag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-variable-selection_files/figure-html/fig-ols-diag-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 35.1— Visualisierung der <code>ols_step_backward_aic</code> mit der Reduktion des AIC-Wertes.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Gut, und wie sieht nun unser finales Modell aus? Dafür müssen wir usn aus dem Objekt <code>chick_step_aic</code> das <code>model</code> raus ziehen. Dafür nutzen wir die Funktion <code>pluck()</code>. Dann noch die Ausgabe in die Funktion <code>model_parameters()</code> gepipt und schon haben wir das finale Modell nach <span class="math inline">\(AIC\)</span>-Werten in einer gaussian linearen Regression.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">pluck</span><span class="op">(</span><span class="va">chick_step_aic</span>, <span class="st">"model"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   | Coefficient |    SE |         95% CI | t(91) |      p
-------------------------------------------------------------------
(Intercept) |       11.11 | 10.07 | [-8.90, 31.11] |  1.10 | 0.273 
temp        |        1.80 |  0.23 | [ 1.34,  2.25] |  7.78 | &lt; .001
no3         |        1.25 |  0.42 | [ 0.41,  2.09] |  2.95 | 0.004 
sand        |        3.05 |  0.12 | [ 2.80,  3.29] | 24.61 | &lt; .001</code></pre>
</div>
</div>
<p>Spannenderweise ist <code>location</code> nicht mehr im finalen Modell plus die Variable <code>location</code> flog auch sehr früh raus. Das passt auch besser zu den Daten. Ich hatte die Daten so gebaut, dass der Ort eigentlich keinen Effekt haben sollte. Wir sehen, dass je nach Verfahren was anderes herauskommt. Aber Achtung, das schrittweise Verfahren ist der Auswahl nach <span class="math inline">\(p\)</span>-Werten auf jeden Fall vorzuziehen!</p>
</section><section id="schrittweise-mit-stepaic" class="level3" data-number="35.4.4"><h3 data-number="35.4.4" class="anchored" data-anchor-id="schrittweise-mit-stepaic">
<span class="header-section-number">35.4.4</span> Schrittweise mit <code>stepAIC</code>
</h3>
<p>Was das R Paket <code>oslrr</code> für die gaussian linear Regression kann, kann das R Paket <code>MASS</code> mit der Funktion <code>stepAIC</code> für den Rest der möglichen Verteilungen. Da wir mit dem Fekerldatensatz ein binominales Outcome <span class="math inline">\(y\)</span> mit <code>infected</code> vorliegen haben nutzen wir un die Funktion <code>stepAIC()</code>. Wir hätten auch den Kichererbsendatensatz mit der Funktion bearbeiten können, aber im Falle der Normalverteilung stehen uns dann eben noch andere Algorithmen zu Verfügung. Wie immer müssen wir zuerst das volle Modell mit der Funktion <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> fitten. Wir geben noch die Verteilungsfamilie mit <code>family = binomial</code> noch mit an und definieren so eine logistische lineare Regression.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> <span class="va">frailty</span> <span class="op">+</span> <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>, 
           data <span class="op">=</span> <span class="va">pig_tbl</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nachdem wir das Modell gefittet haben, können wir das Modell direkt in die Funktion <code>stepAIC</code> stecken. Wir nutzen noch die Option <code>direction = "backward"</code> um eine Rückwärtsselektion durchzuführen.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">fit_step</span> <span class="op">&lt;-</span> <span class="fu">stepAIC</span><span class="op">(</span><span class="va">fit</span>, direction <span class="op">=</span> <span class="st">"backward"</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=425.65
infected ~ age + sex + location + activity + crp + frailty + 
    bloodpressure + weight + creatinin

                Df Deviance    AIC
- location       3   402.73 422.73
- frailty        2   400.81 422.81
- creatinin      1   399.76 423.76
- weight         1   400.76 424.76
- activity       1   400.82 424.82
- age            1   400.87 424.87
&lt;none&gt;               399.65 425.65
- sex            1   407.60 431.60
- bloodpressure  1   407.64 431.64
- crp            1   533.68 557.68

Step:  AIC=422.73
infected ~ age + sex + activity + crp + frailty + bloodpressure + 
    weight + creatinin

                Df Deviance    AIC
- frailty        2   403.89 419.89
- creatinin      1   402.80 420.80
- activity       1   403.67 421.67
- weight         1   403.75 421.75
- age            1   404.05 422.05
&lt;none&gt;               402.73 422.73
- sex            1   410.29 428.29
- bloodpressure  1   410.77 428.77
- crp            1   535.73 553.73

Step:  AIC=419.89
infected ~ age + sex + activity + crp + bloodpressure + weight + 
    creatinin

                Df Deviance    AIC
- creatinin      1   403.91 417.91
- activity       1   404.72 418.72
- weight         1   404.91 418.91
- age            1   405.05 419.05
&lt;none&gt;               403.89 419.89
- sex            1   411.67 425.67
- bloodpressure  1   412.32 426.32
- crp            1   536.68 550.68

Step:  AIC=417.91
infected ~ age + sex + activity + crp + bloodpressure + weight

                Df Deviance    AIC
- activity       1   404.76 416.76
- weight         1   404.95 416.95
- age            1   405.09 417.09
&lt;none&gt;               403.91 417.91
- sex            1   411.84 423.84
- bloodpressure  1   412.44 424.44
- crp            1   536.82 548.82

Step:  AIC=416.76
infected ~ age + sex + crp + bloodpressure + weight

                Df Deviance    AIC
- weight         1   405.76 415.76
- age            1   406.09 416.09
&lt;none&gt;               404.76 416.76
- sex            1   412.39 422.39
- bloodpressure  1   413.16 423.16
- crp            1   536.83 546.83

Step:  AIC=415.76
infected ~ age + sex + crp + bloodpressure

                Df Deviance    AIC
- age            1   407.01 415.01
&lt;none&gt;               405.76 415.76
- sex            1   412.40 420.40
- bloodpressure  1   413.89 421.89
- crp            1   537.87 545.87

Step:  AIC=415.01
infected ~ sex + crp + bloodpressure

                Df Deviance    AIC
&lt;none&gt;               407.01 415.01
- sex            1   413.63 419.63
- bloodpressure  1   415.95 421.95
- crp            1   538.13 544.13</code></pre>
</div>
</div>
<p>Jetzt ist die Selektion durchgelaufen und wir sehen in jeden Schritt welche Variable jeweils entfernt wurde und wie sich dann der <span class="math inline">\(AIC\)</span>-Wert ändert. Wir starten mit einem <span class="math inline">\(AIC = 425.65\)</span> und enden bei einem <span class="math inline">\(AIC=415.01\)</span>. Schauen wir uns nochmal das finale Modell an.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">fit_step</span> <span class="op">%&gt;%</span> 
  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter     | Log-Odds |   SE |           95% CI |     z |      p
-------------------------------------------------------------------
(Intercept)   |   -27.16 | 3.46 | [-34.23, -20.65] | -7.86 | &lt; .001
sex [male]    |     0.69 | 0.27 | [  0.16,   1.23] |  2.55 | 0.011 
crp           |     1.05 | 0.11 | [  0.83,   1.28] |  9.21 | &lt; .001
bloodpressure |     0.11 | 0.04 | [  0.04,   0.19] |  2.93 | 0.003 </code></pre>
</div>
</div>
<p>Hier erscheint jetzt noch die Variable <code>sex</code> mit in der Auswahl. Das hat natürlich auch weitreichende Auswirkungen! Es macht schon einen gewaltigen Unterschied, ob wir annehmen das, dass Geschelcht der Ferkel keinen Einfluss auf die Infektion hat oder eben doch. Wir sehen auch hier, dass wir Aufpassen müssen wenn wir eine Variablenselektion durchführen. Aber Achtung, das schrittweise Verfahren ist der Auswahl nach <span class="math inline">\(p\)</span>-Werten auf jeden Fall vorzuziehen!</p>
</section><section id="feature-selektion-mit-ranger" class="level3" data-number="35.4.5"><h3 data-number="35.4.5" class="anchored" data-anchor-id="feature-selektion-mit-ranger">
<span class="header-section-number">35.4.5</span> Feature Selektion mit <code>ranger</code>
</h3>
<p>In diesem Abschnitt wollen wir die Variablenselektion mit einem maschinellen Lernverfahren durchführen. Im Bereich des maschinellen Lernens heist die Variablenselektion dann aber <em>Feature Selektion</em>. Wir versuchen jetzt die Selektion auf den Orginaldaten durchzuführen. Eigentlich wird empfohlen die Daten vorher zu normalisieren und dann mit den maschinellen Lernverfahren zu nutzen.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Standardisieren oder Normalisieren von Daten
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eine Herausforderung für maschinelle Lernverfahren sind nicht normalisierte Daten. Das heist, dass wir Variablen haben, die kategorial oder kontinuierlich sein können oder aber sehr unterschiedlich von den Einheiten sind. Deshalb wird empfohlen die Daten vorher zu Standardisieren oder zu Normalisieren. In dem <a href="#sec-eda-transform"><span class="quarto-unresolved-ref">sec-eda-transform</span></a> kannst du mehr über das Transformieren von Daten nachlesen.</p>
</div>
</div>
<p>Wir nutzen als erstes einen Random Forest Algorithmus wie er in <a href="#sec-class-rf"><span class="quarto-unresolved-ref">sec-class-rf</span></a> beschrieben ist. Es bietet sich hier die Implementation im R Paket <code>ranger</code> an. Bevor wir aber einen Random Forest auf unsere Daten laufen lassen, Standardisieren wir unsere Daten nochmal. Überall wo wir einen numerischen Wert als Variableneintrag haben rechnen wir eine <span class="math inline">\(z\)</span>-Transformation. Wir erhalten dann die standardisierten Daten zurück.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_norm_tbl</span> <span class="op">&lt;-</span> <span class="va">pig_tbl</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.character</span><span class="op">)</span>, <span class="va">as_factor</span><span class="op">)</span>,
         <span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="fu">dlookr</span><span class="fu">::</span><span class="va"><a href="https://choonghyunryu.github.io/dlookr/reference/transform.html">transform</a></span>, <span class="st">"zscore"</span><span class="op">)</span><span class="op">)</span>

<span class="va">pig_norm_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 412 x 10
   age        sex    location  activity    crp        frailty   bloodpressure
   &lt;transfrm&gt; &lt;fct&gt;  &lt;fct&gt;     &lt;transfrm&gt;  &lt;transfrm&gt; &lt;fct&gt;     &lt;transfrm&gt;   
 1  0.2156014 male   northeast  1.23906607  1.6154076 robust    -2.019564072 
 2 -1.5521155 male   northwest -0.15495130 -0.9942285 robust     0.414746999 
 3  1.3204244 female northeast -1.18531196 -0.9104969 robust     0.005127347 
 4 -0.2263278 female north      0.03899895 -0.4848611 robust    -0.091425856 
 5  0.6575306 male   northwest  0.87540937  1.0502190 robust     0.897513016 
 6 -1.1101862 male   northwest  1.54211333  0.9664873 robust     0.385488452 
 7 -2.4359739 male   west       0.32386336 -0.7569889 pre-frail -1.331988229 
 8 -1.5521155 male   northwest  0.13597407 -0.7569889 robust     1.233986301 
 9 -0.4472924 female west      -0.87014282  1.2735034 robust    -0.029982909 
10 -0.6682570 male   northwest  0.46326510  0.6245832 robust    -0.082648292 
# ... with 402 more rows, and 3 more variables: weight &lt;transfrm&gt;,
#   creatinin &lt;transfrm&gt;, infected &lt;transfrm&gt;</code></pre>
</div>
</div>
<p>Den Random Forest rechnen wir mit der Funktion <code>ranger()</code>. Dafür müssen wir wieder unser vollständiges Modell definieren und können dann die Funktion starten. Damit wir eine Variablenwichtigkeit (eng. <em>variable importance</em>) wiederbekommen, müssen wir noch die Option <code>importance = "permutation"</code> verwenden.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">fit_raw</span> <span class="op">&lt;-</span> <span class="fu">ranger</span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> <span class="va">frailty</span> <span class="op">+</span> <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>, 
                  data <span class="op">=</span> <span class="va">pig_tbl</span>, ntree <span class="op">=</span> <span class="fl">1000</span>, importance <span class="op">=</span> <span class="st">"permutation"</span><span class="op">)</span>

<span class="fu">pluck</span><span class="op">(</span><span class="va">fit_raw</span>, <span class="st">"variable.importance"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span>decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          crp        weight bloodpressure           sex     creatinin 
        0.113         0.005         0.004         0.002         0.001 
      frailty      activity      location           age 
        0.000        -0.002        -0.002        -0.003 </code></pre>
</div>
</div>
<p>Wir sehen, dass wir als wichtigste Variable wiederum <code>crp</code> zurückbekommen. Danach wird es schon etwas schwieriger, da die Werte sehr schnell kleiner werden und auch ein Art Plateau bilden. Daher würde man hier nur annehmen, dass <code>crp</code> bedeutend für das Modell ist. Es kann aber auch sein, dass hier eine kontinuierliche Variable sehr vom Algorithmus bevorzugt wurde. Daher schauen wir uns die Sachlage einmal mit den standardisierten Daten an.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">fit_norm</span> <span class="op">&lt;-</span> <span class="fu">ranger</span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> <span class="va">frailty</span> <span class="op">+</span> <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>, 
                  data <span class="op">=</span> <span class="va">pig_norm_tbl</span>, ntree <span class="op">=</span> <span class="fl">1000</span>, importance <span class="op">=</span> <span class="st">"permutation"</span><span class="op">)</span>

<span class="fu">pluck</span><span class="op">(</span><span class="va">fit_norm</span> , <span class="st">"variable.importance"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span>decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          crp        weight           sex      location bloodpressure 
        0.443         0.014         0.009        -0.002        -0.002 
      frailty     creatinin      activity           age 
       -0.002        -0.010        -0.014        -0.015 </code></pre>
</div>
</div>
<p>Auch hier erhalten wir ein ähnliches Bild. Audf jeden Fall ist <code>crp</code> bedeutend für den Infektionsstatus. Danach werden die Werte etwas zufällig. Wir können Werte für die <em>variable importance</em> nicht unter Datensätzen vergleichen. Jeder Datensatz hat seine eigene <em>variable importance</em>, die von den Werten in dem Datensatz abhängt.</p>
<p>Wir ziehen als Fazit, dass wir nur <code>crp</code> als bedeutenden Wert für die Klassifikation des Infektionsstatus ansehen würden. Hier stehen wir wirklich etwas wie das Schwein vor dem Uhrwerk, denn was nun richtiger ist, <code>stepAIC</code> oder <code>ranger</code> lässt sich so einfach nicht bewerten. Zum einen wollen wir ja eigentlich mit Random Forest eine Klassifikation durchführen und mit linearen Regressionsmodellen eher kausale Modelle schätzen. Am Ende musst du selber abschätzen, was in das finale Modell soll. Ich kann ja auch den Threshold für den Variablenausschluss selber wählen. Wähle ich einen Threshold von <span class="math inline">\(0.008\)</span>, dann hätte ich <code>crp</code>, <code>weight</code>, <code>bloodpressure</code> und <code>sex</code> mit in dem finalen Modell.</p>
</section><section id="feature-selektion-mit-boruta" class="level3 page-columns page-full" data-number="35.4.6"><h3 data-number="35.4.6" class="anchored" data-anchor-id="feature-selektion-mit-boruta">
<span class="header-section-number">35.4.6</span> Feature Selektion mit <code>boruta</code>
</h3>
<p>Mit dem Boruta Algorithmus steht uns noch eine andere Implemnetierung des Random Forest Algorithmus zu verfügung um Feature Selektion zu betreiben. Wir nutzen wieder den Boruta Algorithmus in seine einfachen Form und gehen nicht tiefer auf alle Optionen ein. Wir nehmen wieder als Beispiel den Datensatz zu den infizierten Ferkeln und nutzen in diesem Fall auch nur die rohen Daten. Über eine Standardisierung könnte man wiederum nachdenken.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Ich empfehle noch das Tutorium <a href="https://www.datacamp.com/tutorial/feature-selection-R-boruta">Feature Selection in R with the Boruta R Package</a>. Wir gehen hier nicht tiefer auf die Funktionalität von Boruta ein.</p>
</div></div><div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Standardisieren oder Normalisieren von Daten
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eine Herausforderung für maschinelle Lernverfahren sind nicht normalisierte Daten. Das heist, dass wir Variablen haben, die kategorial oder kontinuierlich sein können oder aber sehr unterschiedlich von den Einheiten sind. Deshalb wird empfohlen die Daten vorher zu Standardisieren oder zu Normalisieren. In dem <a href="#sec-eda-transform"><span class="quarto-unresolved-ref">sec-eda-transform</span></a> kannst du mehr über das Transformieren von Daten nachlesen.</p>
</div>
</div>
<p>Um die Funktion <code>Boruta()</code> zu nutzen brauchen wir wieder das Modell und den Datensatz. Sonst ist erstmal nichts weiter anzugeben. Die Funktion läuft dann durch und gibt auch gleich den gewollten Informationshappen. Wichtig ist hierbei, dass wir natürlich noch andere Optionen mit angeben können. Wir können die Anzahl an Iterationen erhöhen und andere Tuning Parameter eingeben. Hier muss man immer schauen was am besten passt. Da würde ich auch immer rumprobieren und auf der Hilfeseite der Funktion <code>?Boruta</code> einmal nachlesen.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">20221031</span><span class="op">)</span>
<span class="va">boruta_output</span> <span class="op">&lt;-</span> <span class="fu">Boruta</span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> <span class="va">frailty</span> <span class="op">+</span> <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>,  
                        data <span class="op">=</span> <span class="va">pig_tbl</span><span class="op">)</span>  

<span class="va">boruta_output</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Boruta performed 99 iterations in 6.167403 secs.
 1 attributes confirmed important: crp;
 7 attributes confirmed unimportant: activity, age, creatinin, frailty,
location and 2 more;
 1 tentative attributes left: bloodpressure;</code></pre>
</div>
</div>
<p>Manchmal ist es super praktisch, wenn eine Funktion einem die Antwort auf die Frage welche Variable bedeutend ist, gleich liefert. Wir erhalten die Information, dass die Variable <code>crp</code> als bedeutsam angesehen wird. Wir können uns den Zusammenhang auch in der <a href="#fig-buruta">Abbildung&nbsp;<span class="quarto-unresolved-ref">fig-buruta</span></a> auch einmal anschauen. Die grünen Variablen sind die bedeutenden Variablen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">boruta_output</span>, cex.axis<span class="op">=</span><span class="fl">.7</span>, las<span class="op">=</span><span class="fl">2</span>, xlab<span class="op">=</span><span class="st">""</span>, main<span class="op">=</span><span class="st">"Variable Importance"</span><span class="op">)</span>  </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-buruta" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-variable-selection_files/figure-html/fig-buruta-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 35.2— Visualisierung der Boruta Ausgabe.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Am Ende finden wir auch hier die Variable <code>crp</code> als einziges als bedeutend wieder. Wenn wir noch Variablen haben die verdächtig oder vorläufig bedeutend sind, angezeigt durch <code>2 tentative attributes left: bloodpressure, sex</code>, dann können wir noch die Funktion <code>TentativeRoughFix()</code> nutzen. Die Funktion <code>TentativeRoughFix()</code> rechnet die Variablen nochmal nach und versucht alle Variablen in bedeutend oder nicht bedeutend zu klassifizieren. Wir haben ja zwei <em>tentative</em> Variablen in unseren Fall vorliegen, also nutzen wir noch kurz die Funktion um uns auch hier Klarheit zu schaffen.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">TentativeRoughFix</span><span class="op">(</span><span class="va">boruta_output</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Boruta performed 99 iterations in 6.167403 secs.
Tentatives roughfixed over the last 99 iterations.
 1 attributes confirmed important: crp;
 8 attributes confirmed unimportant: activity, age, bloodpressure,
creatinin, frailty and 3 more;</code></pre>
</div>
</div>
<p>Am Ende ist die klare Aussage einer Funktion auch immer ein zweischneidiges Schwert. Wir verlieren jetzt noch die beiden <em>tentative</em> Variablen. Wo wir bei <code>ranger</code> die Qual der Wahl haben, werden wir bei <code>Boruta</code> eher vor vollendete Tatsachen gestellt. Meistens neigt man nach einer <code>Boruta</code>-Analyse nicht dazu noch eine zusätzliche Variable mit ins Modell zu nehmen. Dafür ist dann die Ausgabe zu bestimmt, obwohl die Entscheidung am Ende auch genau so unsicher ist wie von <code>ranger</code> und den anderen Modellen.</p>
</section></section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-heinze2017five" class="csl-entry" role="doc-biblioentry">
Heinze, Georg, und Daniela Dunkler. 2017. <span>„Five myths about variable selection“</span>. <em>Transplant International</em> 30 (1): 6–10.
</div>
<div id="ref-heinze2018variable" class="csl-entry" role="doc-biblioentry">
Heinze, Georg, Christine Wallisch, und Daniela Dunkler. 2018. <span>„Variable selection–a review and recommendations for the practicing statistician“</span>. <em>Biometrical journal</em> 60 (3): 431–49.
</div>
<div id="ref-talbot2019descriptive" class="csl-entry" role="doc-biblioentry">
Talbot, Denis, und Victoria Kubuta Massamba. 2019. <span>„A descriptive review of variable selection methods in four epidemiologic journals: there is still room for improvement“</span>. <em>European journal of epidemiology</em> 34 (8): 725–30.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-modeling-basic.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-outlier.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Ausreißer</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>