<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 29&nbsp; Der \(\mathcal{X}^2\)-Test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-tests-diagnostic.html" rel="next">
<link href="./stat-tests-friedman.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-tests-preface.html">Frequentistische Hypothesentests</a></li><li class="breadcrumb-item"><a href="./stat-tests-chi-test.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der $\mathcal{X}^2$-Test</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Einfache Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Fortgeschrittene Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./abspann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abspann</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spielecke</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link active" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">29.1</span> Genutzte R Pakete</a></li>
  <li><a href="#daten-f%C3%BCr-den-mathcalx2-test" id="toc-daten-für-den-mathcalx2-test" class="nav-link" data-scroll-target="#daten-f%C3%BCr-den-mathcalx2-test"><span class="header-section-number">29.2</span> Daten für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test</a></li>
  <li><a href="#hypothesen-f%C3%BCr-den-mathcalx2-test" id="toc-hypothesen-für-den-mathcalx2-test" class="nav-link" data-scroll-target="#hypothesen-f%C3%BCr-den-mathcalx2-test"><span class="header-section-number">29.3</span> Hypothesen für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test</a></li>
  <li><a href="#mathcalx2-test-theoretisch" id="toc-mathcalx2-test-theoretisch" class="nav-link" data-scroll-target="#mathcalx2-test-theoretisch"><span class="header-section-number">29.4</span> <span class="math inline">\(\mathcal{X}^2\)</span>-Test theoretisch</a></li>
  <li><a href="#mathcalx2-test-in-r" id="toc-mathcalx2-test-in-r" class="nav-link" data-scroll-target="#mathcalx2-test-in-r"><span class="header-section-number">29.5</span> <span class="math inline">\(\mathcal{X}^2\)</span>-Test in R</a></li>
  <li>
<a href="#test-auf-gleiche-oder-gegebene-anteile" id="toc-test-auf-gleiche-oder-gegebene-anteile" class="nav-link" data-scroll-target="#test-auf-gleiche-oder-gegebene-anteile"><span class="header-section-number">29.6</span> Test auf gleiche oder gegebene Anteile</a>
  <ul class="collapse">
<li><a href="#vergleich-eines-anteils-p_1-gegen-einen-gegebenen-anteil-p_0" id="toc-vergleich-eines-anteils-p_1-gegen-einen-gegebenen-anteil-p_0" class="nav-link" data-scroll-target="#vergleich-eines-anteils-p_1-gegen-einen-gegebenen-anteil-p_0"><span class="header-section-number">29.6.1</span> Vergleich eines Anteils <span class="math inline">\(p_1\)</span> gegen einen gegebenen Anteil <span class="math inline">\(p_0\)</span></a></li>
  <li><a href="#vergleich-zweier-anteile-p_1-und-p_2" id="toc-vergleich-zweier-anteile-p_1-und-p_2" class="nav-link" data-scroll-target="#vergleich-zweier-anteile-p_1-und-p_2"><span class="header-section-number">29.6.2</span> Vergleich zweier Anteile <span class="math inline">\(p_1\)</span> und <span class="math inline">\(p_2\)</span></a></li>
  <li><a href="#vergleich-mehrerer-anteile-p_1-p_2-bis-p_k" id="toc-vergleich-mehrerer-anteile-p_1-p_2-bis-p_k" class="nav-link" data-scroll-target="#vergleich-mehrerer-anteile-p_1-p_2-bis-p_k"><span class="header-section-number">29.6.3</span> Vergleich mehrerer Anteile <span class="math inline">\(p_1\)</span>, <span class="math inline">\(p_2\)</span> bis <span class="math inline">\(p_k\)</span></a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-chi-test" class="quarto-section-identifier"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom August 18, 2023 um 14:43:34</em></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Was macht der <span class="math inline">\(\mathcal{X}^2\)</span>-Test?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ein <span class="math inline">\(\mathcal{X}^2\)</span>-Test vergleicht die Anteile zweier oder mehrerer Gruppen. Da Anteile Wahrscheinlichkeiten sind, vergleicht der <span class="math inline">\(\mathcal{X}^2\)</span>-Test damit auch Wahrscheinlichkeiten.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Einführung in den <span class="math inline">\(\mathcal{X}^2\)</span>-Test per Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/B6YNtxBsK3c">Der Chi-Quadrat-Test erklärt</a> als Video Reihe. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>
<p>Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test wird häufig verwendet, wenn wir zwei Faktoren mit jeweils zwei Leveln miteinander vergleichen wollen. Das heißt wir haben zum Beispiel unseren Faktor <code>animal</code> mit den beiden Leveln <code>cat</code> und <code>dog</code>. Wir schauen uns jetzt den Infektionsstatus mit Flöhen auf den Tieren an. Wir erhalten wiederum einen Faktor <code>infected</code> mit zwei Leveln <code>yes</code> und <code>no</code>. Wir sind bei dem <span class="math inline">\(\mathcal{X}^2\)</span>-Test nicht auf nur Faktoren mit zwei Leveln eingeschränkt. Traditionell wird aber versucht ein 2x2 Setting zu erreichen.</p>
<p>Im Bereich der Agrarwissenschaften kommt der <span class="math inline">\(\mathcal{X}^2\)</span>-Test eher selten vor. Im Bereich der Humanwissenschaften und vor allem der Epidemiologie ist der <span class="math inline">\(\mathcal{X}^2\)</span>-Test weit verbreitet.</p>
<p>Das eigentlich besondere an dem <span class="math inline">\(\mathcal{X}^2\)</span>-Test ist gra nicht mal der Test selber sondenr die Datenstruktur die der <span class="math inline">\(\mathcal{X}^2\)</span>-Test zugrunde liegt: der Vierfeldertafel oder 2x2 Kreuztabelle. Wir werden diese Form von Tabelle noch später im maschinellen Lernen und in der Testdiagnostik wiederfinden.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ein Wort zur Klausur
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Wir rechnen den <span class="math inline">\(\mathcal{X}^2\)</span>-Test per Hand in der Klausur. Teilweise füllen wir die <span class="math inline">\(2x2\)</span> Tabelle aus, teilweise berechnen wir nur die Randsummen.</p>
<p>Bitte schau dir die Aufgaben in den <a href="https://github.com/jkruppa/teaching/tree/main/Klausur">gesammelten Klausurfragen auf GitHub</a> an um eine Idee zu haben, welche Fragen zum <span class="math inline">\(\mathcal{X}^2\)</span>-Test drankommen.</p>
<p>Wenn kein <span class="math inline">\(\chi^2_{\alpha=5\%}\)</span> in der Klausur gegeben ist, setzen wir <span class="math inline">\(\chi^2_{\alpha=5\%} = 3.84\)</span>.</p>
</div>
</div>
</div>
<section id="genutzte-r-pakete" class="level2" data-number="29.1"><h2 data-number="29.1" class="anchored" data-anchor-id="genutzte-r-pakete">
<span class="header-section-number">29.1</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">effectsize</span>, <span class="va">rstatix</span>,</span>
<span>               <span class="va">scales</span>, <span class="va">parameters</span>, <span class="va">conflicted</span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">stats</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">stats</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test</a></span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten-für-den-mathcalx2-test" class="level2" data-number="29.2"><h2 data-number="29.2" class="anchored" data-anchor-id="daten-für-den-mathcalx2-test">
<span class="header-section-number">29.2</span> Daten für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test</h2>
<p>Wie eben schon benannt schauen wir uns für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test eine Vierfeldertafel oder aber 2x2 Kreuztabelle an. In <a href="#tbl-chi-square-obs">Tabelle&nbsp;<span>29.1</span></a> sehen wir eine solche 2x2 Kreuztabelle. Da wir eine Mindestanzahl an Zellbelegung brauchen um überhaupt mit dem <span class="math inline">\(\mathcal{X}^2\)</span>-Test rechnen zu können, mutzen wir hier gleich aggrigierte Beispieldaten. Wir brauchen mindestens fünf Beobachtungen je Zelle, dass heißt mindestens 20 Tiere. Da wir dann aber immer noch sehr wenig haben, ist die Daumenregel, dass wir etwa 30 bis 40 Beobachtungen brauchen. In unserem Beispiel schauen wir uns 65 Tiere an.</p>
<div id="tbl-chi-square-obs" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;29.1— Eine 2x2 Tabelle als Beispiel für unterschiedliche Flohinfektionen bei Hunden und Katzen. Dargestellt sind die <em>beobachteten</em> Werte.</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Infected</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Animal</strong></td>
<td style="text-align: center;"><em>Dog</em></td>
<td style="text-align: center;"><span class="math inline">\(23_{\;\Large a}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(10_{\;\Large b}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{a+b = 33}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Cat</em></td>
<td style="text-align: center;"><span class="math inline">\(18_{\;\Large c}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(14_{\;\Large d}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{c+d = 32}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{a+c = 41}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{b+d = 24}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = 65\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>In der Tabelle sehen wir, dass in den zeieln die Level des Faktors <code>animal</code> angegeben sind und in den Spalten die Level des Faktors <code>infected</code>. Wir haben somit <span class="math inline">\(23\)</span> Hunde, die mit Flöhen infiziert sind, dann <span class="math inline">\(10\)</span> Hunde, die nicht mit Flöhen infirziert sind. Auf der Seite der Katzen haben wir <span class="math inline">\(18\)</span> Katzen, die infiziert sind und <span class="math inline">\(14\)</span> Katzen, die keine Flöhe haben. An den Rändern stehen die Randsummen. Wir haben <span class="math inline">\(33\)</span> Hunde und <span class="math inline">\(32\)</span> Katzen sowie <span class="math inline">\(41\)</span> infizierte Tiere und <span class="math inline">\(24\)</span> nicht infizierte Tiere. Somit haben wir dann in Summe <span class="math inline">\(n = 65\)</span> Tiere. Diese Form der Tabelle wird uns immer wieder begegnen.</p>
<p>Bevor wir jetzt diese 2x2 Kreuztabelle verwenden, müssen wir uns nochmal überlegen, welchen Schluß wir eigentlich über die Nullhypothese machen. Wie immer können wir nur die Nullhypothese ablehnen. Daher überlegen wir uns im Folgenden wie die Nullhypothese in dem <span class="math inline">\(\mathcal{X}^2\)</span>-Test aussieht. Dann bilden wir anhand der Nullhypothese noch die Alternativehypothese.</p>
</section><section id="hypothesen-für-den-mathcalx2-test" class="level2" data-number="29.3"><h2 data-number="29.3" class="anchored" data-anchor-id="hypothesen-für-den-mathcalx2-test">
<span class="header-section-number">29.3</span> Hypothesen für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test</h2>
<p>Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test betrachtet die Zellbelegung gegeben den Randsummen um einen Unterschied nachzuweisen. Daher haben wir die Nullhypothese als Gleichheitshypothese. In unserem Beispiel lautet die Nullhypothese, dass die Zahlen in den Zellen gegeben der Randsummen gleich sind. Wir betrachten hier nur die Hypothesen in Prosa und die mathematischen Hypothesen. Es ist vollkommen ausreichend, wenn du die Nullhypothese des <span class="math inline">\(\mathcal{X}^2\)</span>-Test nur in Prosa kennst.</p>
<p><span class="math display">\[
H_0: \; \mbox{Zellbelegung sind gleichverteilt gegeben der Randsummen}
\]</span></p>
<p>Die Alternative lautet, dass sich die Zahlen in den Zellen gegeben der Randsummen unterscheiden.</p>
<p><span class="math display">\[
H_A: \; \mbox{Zellbelegung sind nicht gleichverteilt gegeben der Randsummen}
\]</span></p>
<p>Wir schauen uns jetzt einmal den <span class="math inline">\(\mathcal{X}^2\)</span>-Test theoretisch an bevor wir uns mit der Anwendung des <span class="math inline">\(\mathcal{X}^2\)</span>-Test in R beschäftigen.</p>
</section><section id="mathcalx2-test-theoretisch" class="level2" data-number="29.4"><h2 data-number="29.4" class="anchored" data-anchor-id="mathcalx2-test-theoretisch">
<span class="header-section-number">29.4</span> <span class="math inline">\(\mathcal{X}^2\)</span>-Test theoretisch</h2>
<p>In <a href="#tbl-chi-square-obs">Tabelle&nbsp;<span>29.1</span></a> von oben hatten wir die <em>beobachteten</em> Werte. Das sind die Zahlen, die wir in unserem Experiment erhoben und gemessen haben. Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test vergleicht nun die <em>beobachteten</em> Werte mit den anhand der Randsummen zu <em>erwartenden</em> Werte. Daher ist die Formel für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test wie folgt.</p>
<p><span class="math display">\[
\chi^2_{calc} = \sum\cfrac{(O - E)^2}{E}
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(O\)</span> für die beobachteten Werte</li>
<li>
<span class="math inline">\(E\)</span> für die nach den Randsummen zu erwartenden Werte</li>
</ul>
<p>In <a href="#tbl-chi-square-exp">Tabelle&nbsp;<span>29.2</span></a> kannst du sehen wie wir anhand der Randsummen die erwartenden Zellbelegungen berechnen. Hierbei können auch krumme Zahlen rauskommen. Wir würden keinen Unterschied zwischen Hunde und Katzen gegeben deren Infektionsstatus erwarten, wenn die Abweichungen zwischen den beobachteten Werten und den zu erwartenden Werten klein wären. Wir berechnen nun die zu erwartenden Werte indem wir die Randsummen der entsprechenden Zelle multiplizieren und durch die Gesamtanzahl teilen.</p>
<div id="tbl-chi-square-exp" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;29.2— Eine 2x2 Tabelle als Beispiel für unterschiedliche Flohinfektionen bei Hunden und Katzen. Dargestellt sind die zu <em>erwartenden</em> Werte.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 6%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 14%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Infected</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Animal</strong></td>
<td style="text-align: center;"><em>Dog</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{41 \cdot 33}{65} = 20.82\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{24 \cdot 33}{65} = 12.18\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{33}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Cat</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{41 \cdot 32}{65} = 20.18\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{24 \cdot 32}{65} = 11.82\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{32}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{41}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{24}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = 65\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Wir können dann die Formel für den <span class="math inline">\(\mathcal{X}^2\)</span>-Test entsprechend ausfüllen. Dabei ist wichtig, dass die Abstände quadriert werden. Das ist ein Kernkonzept der Statistik, Abstände bzw. Abweichungen werden immer quadriert.</p>
<span class="math display">\[\begin{aligned}
\chi^2_{calc} &amp;= \cfrac{(23 - 20.82)^2}{20.82} + \cfrac{(10 - 12.18)^2}{12.18} + \\
&amp;\phantom{=}\;\; \cfrac{(18 - 20.18)^2}{20.18} + \cfrac{(14 - 11.82)^2}{11.82} = 1.25
\end{aligned}\]</span>
<p>Es ergibt sich ein <span class="math inline">\(\chi^2_{calc}\)</span> von <span class="math inline">\(1.25\)</span> mit der Regel, dass wenn <span class="math inline">\(\chi^2_{calc} \geq \chi^2_{\alpha=5\%}\)</span> die Nullhypothese abgelehnt werden kann. Mit einem <span class="math inline">\(\chi^2_{\alpha=5\%} = 3.84\)</span> können wir die Nullhypothese nicht ablehnen. Es besteht kein Zusammenhang zwischen den Befall mit Flöhen und der Tierart. Oder anders herum, Hunde und Katzen werden gleich stark mit Flöhen infiziert.</p>
<p>Wie stark ist nun der beobachtete Effekt? Wir konnten zwar die Nullhypothese nicht ablehnen, aber es wäre auch von Interesse für die zukünftige Versuchsplanung, wie stark sich die Hunde und Katzen im Befall mit Flöhen unterscheiden. Wir haben nun die Wahl zwischen zwei statistischen Maßzahlen für die Beschreibung eines Effektes bei einem <span class="math inline">\(\mathcal{X}^2\)</span>-Test.</p>
<p>Zum einen Cramers <span class="math inline">\(V\)</span>, das wir in etwa interpretieren wie eine Korrelation und somit auch einheitslos ist. Wenn Cramers <span class="math inline">\(V\)</span> gleich 0 ist, dann haben wir keinen Unterschied zwischen den Hunden und Katzen gegeben dem Flohbefall. Bei einem Cramers <span class="math inline">\(V\)</span> von 0.5 haben wir einen sehr starken Unterschied zwischen dem Flohbefall zwischen den beiden Tierarten. Der Vorteil von Cramers V ist, dass wir Cramers <span class="math inline">\(V\)</span> auch auf einer beliebig großen Kreuztabelle berechnen können. Die Formel ist nicht sehr komplex.</p>
<p><span class="math display">\[
V = \sqrt{\cfrac{\mathcal{X}^2/n}{\min(c-1, r-1)}}
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(\mathcal{X}^2\)</span> gleich der Chi-Quadrat-Statistik</li>
<li>
<span class="math inline">\(n\)</span> gleich der Gesamtstichprobengröße</li>
<li>
<span class="math inline">\(r\)</span>: Anzahl der Reihen</li>
<li>
<span class="math inline">\(c\)</span>: Anzahl der Spalten</li>
</ul>
<p><span class="math display">\[
V = \sqrt{\cfrac{1.26/65}{1}} = 0.14
\]</span></p>
<p>Wir setzen also den Wert <span class="math inline">\(\chi^2_{calc}\)</span> direkt in die Formel ein. Wir wissen ja auch, dass wir <span class="math inline">\(n = 65\)</span> Tiere untersucht haben. Da wir eine 2x2 Kreuztabelle vorliegen haben, haben wir <span class="math inline">\(r = 2\)</span> und <span class="math inline">\(c = 2\)</span> und somit ist das Minimum von <span class="math inline">\(r-1\)</span> und <span class="math inline">\(c-1\)</span> gleich <span class="math inline">\(1\)</span>. Wir erhalten ein Cramers <span class="math inline">\(V\)</span> von <span class="math inline">\(0.14\)</span> was für einen schwachen Effekt spricht. Wir können uns auch grob an der folgenden Tabelle der Effektstärken für Carmers <span class="math inline">\(V\)</span> orientieren.</p>
<table class="table">
<thead><tr class="header">
<th></th>
<th>schwach</th>
<th>mittel</th>
<th>stark</th>
</tr></thead>
<tbody><tr class="odd">
<td>Cramers <span class="math inline">\(V\)</span>
</td>
<td>0.1</td>
<td>0.3</td>
<td>0.5</td>
</tr></tbody>
</table>
<p>Zum anderen haben wir noch die Möglichkeit die Odds Ratios oder das Chancenverhältnis zu berechnen. Die Odds Ratios lassen sich direkter als Effekt interpretieren als Cramers <span class="math inline">\(V\)</span> haben aber den Nachteil, dass wir die Odds Ratios nur auf einer 2x2 Kreuztabelle berechnen können. Wichtig bei der Berechnung der Odds Ratios und der anschließenden Interpretation ist die <em>obere Zeile</em> der 2x2 Kreuztabelle. Die <em>obere Zeile</em> ist der Bezug für die Interpretation. Wir nutzen folgende Formel für die Berechnung der Odds Ratios.</p>
<p><span class="math display">\[
\mbox{Odds Ratio} = OR = \cfrac{a\cdot d}{b \cdot c} = \cfrac{23\cdot 14}{10 \cdot 18} = 1.79
\]</span></p>
<p>Es ist zwingend notwendig für die folgenden Interpretation der Odds Ratios, dass in den Spalten links die <span class="math inline">\(ja\)</span> Spalte steht und rechts die <span class="math inline">\(nein\)</span> Spalte. Ebenso interpretieren wie die Odds Ratios im Bezug zur oberen Zeile. In unserem Fall ist also die Chance sich mit Flöhen zu infizieren <em>bei Hunden</em> 1.79 mal größer als bei Katzen. Diese Interpretation ist nur korrekt, wenn die 2x2 Kreuztabelle wie beschrieben erstellt ist!</p>
</section><section id="mathcalx2-test-in-r" class="level2 page-columns page-full" data-number="29.5"><h2 data-number="29.5" class="anchored" data-anchor-id="mathcalx2-test-in-r">
<span class="header-section-number">29.5</span> <span class="math inline">\(\mathcal{X}^2\)</span>-Test in R</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test wird meist in anderen Funktionen in R verwendet und nicht direkt. Wenn du Fragen dazu hast, schreib mir einfach eine Mail.</span></div></div>
<p>Wenn wir den <span class="math inline">\(\mathcal{X}^2\)</span>-Test in R rechnen wollen nutzen wir die Funktion <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code>, die eine Matrix von Zahlen verlangt. Dies ist etwas umständlich. Wir müssen nur beachten, dass wir die Matrix so bauen, wie wir die Matrix auch brauchen. Deshalb immer mal doppelt schauen, ob deine Matrix auch deinen beobachteten Werten entspricht.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">23</span>, <span class="fl">10</span>, <span class="fl">18</span>, <span class="fl">14</span><span class="op">)</span>, </span>
<span>              byrow <span class="op">=</span> <span class="cn">TRUE</span>, nrow <span class="op">=</span> <span class="fl">2</span>,</span>
<span>              dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>animal <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dog"</span>, <span class="st">"cat"</span><span class="op">)</span>,</span>
<span>                              infected <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"yes"</span>, <span class="st">"no"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">mat</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  mat
X-squared = 1.2613, df = 1, p-value = 0.2614</code></pre>
</div>
</div>
<p>Als ein mögliches Effektmaß können wir Cramers <span class="math inline">\(V\)</span> berechnen. Wir nutzen hierzu die Funktion <code>cramers_v()</code>. Auf einer reinen 2x2 Kreuztabelle wäre aber Pearsons <span class="math inline">\(\phi\)</span> durch die Funktion <code>phi()</code> vorzuziehen. Siehe dazu auch <a href="https://easystats.github.io/effectsize/reference/phi.html"><span class="math inline">\(\phi\)</span> and Other Contingency Tables Correlations</a> auf der Hilfeseite des R Paketes <code>effectsize</code>. Wir bleiben hier dann aber bei Cramers <span class="math inline">\(V\)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">cramers_v</span><span class="op">(</span><span class="va">mat</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.06              | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Wir sehen, dass der Effekt mit einem <span class="math inline">\(V = 0.06\)</span> schwach ist. Ein Wert von 0 bedeutet keine Assoziation und ein Wert von 1 einen maximalen Zusammenhang. Wir können die Werte von <span class="math inline">\(V\)</span> wie eine Korrelation interpretieren. Der in R berechnete Wert unterscheidet sich von unseren händsichen berechneten Wert, da wir hier mit dem adjustierten Cramers <span class="math inline">\(V\)</span> rechnen. Wir würden auch in der Anwendung den adjustierten Wert verwenden, aber für das Verständnis reicht der händisch berechnete Wert.</p>
<p>Haben wir eine geringe Zellbelegung von unter 5 in einer der Zellen der 2x2 Kreuztabelle, dann verwenden wir den Fisher Exakt Test. Der Fisher Exakt Test hat auch den Vorteil, dass wir direkt die Odds Ratios wiedergegeben bekommen. Wir können auch den Fisher Exakt Test rechnen, wenn wir viele Beobachtungen pro Zelle haben und einfach an die Odds Ratios rankommen wollen. Der Unterschied zwischen dem klassischen <span class="math inline">\(\mathcal{X}^2\)</span>-Test und dem Fisher Exakt Test ist in der praktischen Anwendung nicht so groß.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test</a></span><span class="op">(</span><span class="va">mat</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  mat
p-value = 0.3102
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.5756546 5.6378438
sample estimates:
odds ratio 
   1.77279 </code></pre>
</div>
</div>
<p>Wir sehen auch hier den nicht signifikanten <span class="math inline">\(p\)</span>-Wert sowie eine Odds Ratio von 1.77. Hunde haben aso eine um 1.77 höhere Chance sich mit Flöhen zu infizieren.</p>
</section><section id="test-auf-gleiche-oder-gegebene-anteile" class="level2 page-columns page-full" data-number="29.6"><h2 data-number="29.6" class="anchored" data-anchor-id="test-auf-gleiche-oder-gegebene-anteile">
<span class="header-section-number">29.6</span> Test auf gleiche oder gegebene Anteile</h2>
<p>Neben dem Test auf absolute Anteile, wie der <span class="math inline">\(\mathcal{X}^2\)</span>-Test es rechnet, wollen wir manchmal auch relative Anteile testen. Also haben wir nicht 8 kranke Erdbeeren gezählt sondern 8 kranke von 12 Erdbeeren. Damit sind dann 66% bzw. 0.66 kranke Erdbeeren vorhanden. Wir rechnen also mit Wahrscheinlichkeiten, also <em>eng. proportions</em>. Deshalb können wir hier auch die R Funktion <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> nutzen. Wichtig ist zu wissen, dass wir trotz allem erst die Anzahl an beschädigten Erdbeeren <span class="math inline">\(x\)</span> sowie die absolute Anzahl an Erdbeeren <span class="math inline">\(n\)</span> brauchen. Das wird jetzt aber gleich in dem Beispiel etwas klarer. Im Prinzip ist der <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> also eine andere Art den <span class="math inline">\(\mathcal{X}^2\)</span>-Test zu rechnen.</p>
<section id="vergleich-eines-anteils-p_1-gegen-einen-gegebenen-anteil-p_0" class="level3 page-columns page-full" data-number="29.6.1"><h3 data-number="29.6.1" class="anchored" data-anchor-id="vergleich-eines-anteils-p_1-gegen-einen-gegebenen-anteil-p_0">
<span class="header-section-number">29.6.1</span> Vergleich eines Anteils <span class="math inline">\(p_1\)</span> gegen einen gegebenen Anteil <span class="math inline">\(p_0\)</span>
</h3>
<p>Nehmen wir ein etwas konstruiertes Beispiel zur Erdbeerernte. Wir haben einen neuen Roboter entwickelt, der Erdbeeren erntet. Nun stellen wir fest, dass von 100 Erdbeeren 76 heile sind. Jetzt lesen wir im Handbuch, dass der Ernteroboter eigentlich 84% der Erdbeeren heile ernten sollte. Sind jetzt 76 von 100, also 76%, signifikant unterschiedlich von 84%? Oder können wir die Nullhypothese der Gleichheit zwischen den beiden Wahrscheinlichkeiten nicht ablehnen? Damit können wir den Test auf Anteile nutzen, wenn wir eine beobachtete Wahrscheinlichkeit oder Anteil <span class="math inline">\(p_1\)</span> gegen eine gegebene Wahrscheinlichkeit oder Anteil <span class="math inline">\(p_0\)</span> vergleichen wollen.</p>
<p>In unserem Fall haben wir mit <span class="math inline">\(p_1\)</span> die Wahrscheinlichkeit vorliegen, dass die Erdbeeren in unserem Experiment heile sind. Wir wissen also, dass <span class="math inline">\(p_1 = \cfrac{x}{n} = \cfrac{76}{100} = 0.76 = 76\%\)</span> ist. Damit ist die Wahrscheinlichkeit <span class="math inline">\(p_1\)</span> auch die <em>beobachte</em> Wahrscheinlichkeit. Wir <em>erwarten</em> auf der anderen Seite die Wahrscheinlichkeit <span class="math inline">\(p_0 = 0.84 = 84\%\)</span>. Die Roboterfirma hat uns aj zugesagt, dass 84% der Erdbeeren heile bleiben sollen.</p>
<p>Wir berechnen jetzt einmal die <em>beobachten</em> Werte. Zum einen haben wir <span class="math inline">\(x=76\)</span> heile Erdbeeren von <span class="math inline">\(n=100\)</span> Erdbeeren gezählt. Damit ergeben sich dann <span class="math inline">\(x = 76\)</span> heile Erdbeeren und <span class="math inline">\(24\)</span> beschädigte Erdbeeren. Die Summe muss ja am Ende wieder 100 Erdbeeren ergeben.</p>
<p><span class="math display">\[
\begin{aligned}
O &amp;=
\begin{pmatrix}
x &amp;|&amp; n - x
\end{pmatrix}
=
\begin{pmatrix}
76 &amp;|&amp; 100 - 76
\end{pmatrix} \\
&amp; =
\begin{pmatrix}
76 &amp;|&amp; 24
\end{pmatrix}
\end{aligned}
\]</span></p>
<p>Dann müssen wir uns noch die Frage stellen, welche Anzahl an heilen Erdbeeren hätten wir <em>erwartet</em>? In diesem Fall ja 84% heile Erdbeeren. Das macht dann bei 100 Erdbeeren <span class="math inline">\(0.84 \cdot 100 = 84\)</span> heile Erdbeeren und <span class="math inline">\((1 - 0.84) \cdot 100 = 16\)</span> beschädigte Erdbeeren.</p>
<p><span class="math display">\[
\begin{aligned}
E &amp;=
\begin{pmatrix}
n \cdot p &amp;|&amp; n \cdot (1 - p)
\end{pmatrix}
=
\begin{pmatrix}
100 \cdot 0.84 &amp;|&amp; 100 \cdot (1 - 0.84)
\end{pmatrix} \\
&amp; =
\begin{pmatrix}
84 &amp;|&amp; 16
\end{pmatrix}
\end{aligned}
\]</span></p>
<p>Jetzt müssen wir nur noch die <em>beobachteten</em> Anteile mit den zu <em>erwarteten</em> Anteilen durch die <span class="math inline">\(\mathcal{X}^2\)</span>-Formel in Kontext setzten. Wir subtrahieren von jedem beobachten Anteil den zu erwartenden Anteil, quadrieren und addieren auf. Dann erhalten wir die <span class="math inline">\(\mathcal{X}^2\)</span>-Statistik.</p>
<p><span class="math display">\[
\chi^2_{calc} = \sum\cfrac{(O-E)^2}{E} = \cfrac{(76 - 84)^2}{84} + \cfrac{(24 - 16)^2}{16} = 4.76
\]</span></p>
<p>Wir können diese einfache Berechnung dann auch schnell nochmal in R durchführen. Wir setzten dafür einfach <code>x</code>, <code>n</code> und <code>p</code> fest und berechnen dann die beobachten Anteile <span class="math inline">\(O\)</span> sowwie die zu erwartenden Anteile <span class="math inline">\(E\)</span>. Wir berechnen dann hier auch den gleichen Wert für <span class="math inline">\(\mathcal{X}^2\)</span>-Statistik.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">76</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">100</span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fl">0.84</span></span>
<span><span class="va">O</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">n</span> <span class="op">-</span> <span class="va">x</span><span class="op">)</span></span>
<span><span class="va">E</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">n</span> <span class="op">*</span> <span class="va">p</span>, <span class="va">n</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">O</span> <span class="op">-</span> <span class="va">E</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">/</span><span class="va">E</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.761905</code></pre>
</div>
</div>
<p>Und wie immer gibt es auch eine Funktion <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code>, die uns ermöglicht einen beobachteten Anteil <code>x/n</code> zu einem erwarteten Anteil <code>p</code> zu vergleichen. Auch hier sehen wir, dass sich die <span class="math inline">\(\mathcal{X}^2\)</span>-Statistik aus der R Funktion nicht von unser berechneten <span class="math inline">\(\mathcal{X}^2\)</span>-Statistik unterscheidet.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">76</span>, n <span class="op">=</span> <span class="fl">100</span>, p <span class="op">=</span> <span class="fl">0.84</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test without continuity correction

data:  76 out of 100, null probability 0.84
X-squared = 4.7619, df = 1, p-value = 0.0291
alternative hypothesis: true p is not equal to 0.84
95 percent confidence interval:
 0.6676766 0.8330867
sample estimates:
   p 
0.76 </code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Was ist die Yates Korrektur, die wir mit <code>correct = TRUE</code> auswählen? Die Korrektur von Yates subtrahiert von jedem Summanden des Chi-Quadrat-Tests 0.5, so dass die Chi-Quadrat-Statistik geringer ausfällt.</p>
</div></div></section><section id="vergleich-zweier-anteile-p_1-und-p_2" class="level3" data-number="29.6.2"><h3 data-number="29.6.2" class="anchored" data-anchor-id="vergleich-zweier-anteile-p_1-und-p_2">
<span class="header-section-number">29.6.2</span> Vergleich zweier Anteile <span class="math inline">\(p_1\)</span> und <span class="math inline">\(p_2\)</span>
</h3>
<p>Nun haben wir nicht einen Ernteroboter sondern zwei brandneue Robotertypen. Einmal die Marke <em>Picky</em> und einmal den Roboter <em>Colly</em>. Wir wollen jetzt wieder bestimmen, wie viel Erdbeeren bei der Ernte beschädigt werden. Erdbeeren sind ja auch ein sehr weiches Obst. Wir vergleichen hier also wieder zwei Anteile miteinander. Der Roboter <em>Picky</em> beschädigt 76 von 100 Erdbeeren und der Roboter <em>Colly</em> detscht 91 von 100 Erdbeeren an. Das sind ganz schön meise Werte, aber was will man machen, wir haben jetzt nur die beiden Roboter vorliegen. Die Frage ist nun, ob sich die beiden Roboter in der Häufigkeit der beschädigten Erdbeeren unterscheiden. Wir können hier eine 2x2 Kreuztabelle in der <a href="#tbl-chi-square-exp-3">Tabelle&nbsp;<span>29.5</span></a> aufmachen und die jeweiligen Anteile berechnen. Picky beschädigt 76% der Erdbeeren und Colly ganze 91%.</p>
<div id="tbl-chi-square-exp-3" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;29.3— Eine 2x2 Tabelle für die zwei Ernteroboter und der beschädigten Erdbeeren. Dargestellt sind die <em>beobachteten</em> Werte.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 23%">
<col style="width: 22%">
<col style="width: 23%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Damaged</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Robot</strong></td>
<td style="text-align: center;"><em>Picky</em></td>
<td style="text-align: center;"><span class="math inline">\(76\)</span></td>
<td style="text-align: center;"><span class="math inline">\(24\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{100}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Colly</em></td>
<td style="text-align: center;"><span class="math inline">\(91\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{100}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{167}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{33}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = 200\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Wir können die erwarteten Anteile jetzt wie schon bekannt berechnen oder aber wir nutzen folgende Formel um <span class="math inline">\(\hat{p}\)</span>, die Wahrscheinlichkeit für ein Ereignis, zu berechnen. Wir nutzen dann <span class="math inline">\(\hat{p}\)</span> um die erwarteten Werte <span class="math inline">\(E\)</span> aus zurechnen. Dafür addieren wir alle beobachteten <span class="math inline">\(x\)</span> zusammen und teilen diese Summe durch die gesammte Anzahl an Beobachtungen.</p>
<p><span class="math display">\[
\hat{p} = \cfrac{\sum x}{\sum n} = \cfrac{79 + 91}{100 + 100} = \cfrac{170}{200} = 0.85
\]</span></p>
<p>Im Folgenden die Rechenschritte nochmal in R aufgedröselt zum besseren nachvollziehen. Wie auch schon im obigen Beispiel berechnen wir erst die beobachten Anteil <span class="math inline">\(O\)</span> sowie die erwartenden Anteile <span class="math inline">\(E\)</span>. Dann nutzen wir die Formel des <span class="math inline">\(\mathcal{X}^2\)</span>-Test um die <span class="math inline">\(\mathcal{X}^2\)</span>-Statistik zu berechnen.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">76</span>, <span class="fl">91</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">100</span>, <span class="fl">100</span><span class="op">)</span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">O</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">n</span> <span class="op">-</span> <span class="va">x</span><span class="op">)</span></span>
<span><span class="va">E</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">n</span> <span class="op">*</span> <span class="va">p</span>, <span class="va">n</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">O</span> <span class="op">-</span> <span class="va">E</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">/</span><span class="va">E</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.165487</code></pre>
</div>
</div>
<p>Auch hier vergleichen wir nochmal unser händisches Ergebnis mit dem Ergebnis der R Funktion <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code>. Der Funktion übergeben wir dann einmal die beobachteten Anteile <span class="math inline">\(x\)</span> sowie dann die jeweils Gesamtanzahlen <span class="math inline">\(n\)</span>. Wichtig ist hier, dass wir als 95% Konfidenzintervall die Differenz der beiden Wahrscheinlichkeiten erhalten.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">76</span>, <span class="fl">91</span><span class="op">)</span>, n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">100</span>, <span class="fl">100</span><span class="op">)</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  c(76, 91) out of c(100, 100)
X-squared = 8.1655, df = 1, p-value = 0.00427
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.25076198 -0.04923802
sample estimates:
prop 1 prop 2 
  0.76   0.91 </code></pre>
</div>
</div>
<p>Wir wir sehen unterscheiden sich die beiden Anteil von <span class="math inline">\(76/100\)</span> gleich 76% von <span class="math inline">\(91/100\)</span> gleich 91%. Damit sollten wir den Roboter Picky nehmen, denn da werden prozentual weniger Erdbeeren zermanscht. Ob das jetzt gut oder schlecht ist 76% Erdbeeren zu zerstören ist aber wieder eine Frage, die die Statistik an dieser Stelle nicht beantworten kann.</p>
</section><section id="vergleich-mehrerer-anteile-p_1-p_2-bis-p_k" class="level3 page-columns page-full" data-number="29.6.3"><h3 data-number="29.6.3" class="anchored" data-anchor-id="vergleich-mehrerer-anteile-p_1-p_2-bis-p_k">
<span class="header-section-number">29.6.3</span> Vergleich mehrerer Anteile <span class="math inline">\(p_1\)</span>, <span class="math inline">\(p_2\)</span> bis <span class="math inline">\(p_k\)</span>
</h3>
<p>Im Folgenden haben wir jetzt nicht mehr zwei Gruppen, die wir miteinander vergleichen wollen, sondern mehrere Behandlungen als Gruppen. Wir haben uns in einem Experiment die beschädigten Erdbeeren nach vier neue Erntearten, A bis D, angeschaut. Beide Vektoren können wir dann in die Funktion <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> stecken.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">damaged</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>A <span class="op">=</span> <span class="fl">105</span>, B <span class="op">=</span> <span class="fl">100</span>, C <span class="op">=</span> <span class="fl">139</span>, D <span class="op">=</span> <span class="fl">96</span><span class="op">)</span></span>
<span><span class="va">berries</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">106</span>, <span class="fl">113</span>, <span class="fl">156</span>, <span class="fl">102</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span><span class="va">damaged</span>, <span class="va">berries</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    4-sample test for equality of proportions without continuity correction

data:  damaged out of berries
X-squared = 11.747, df = 3, p-value = 0.008303
alternative hypothesis: two.sided
sample estimates:
   prop 1    prop 2    prop 3    prop 4 
0.9905660 0.8849558 0.8910256 0.9411765 </code></pre>
</div>
</div>
<p>Wir erhalten dann einen <span class="math inline">\(p\)</span>-Wert für die Signifikanz von 0.0056 wieder. Was testen wir hier eigentlich? Unsere Nullhypothese ist, dass alle paarweisen Wahrscheinlichkeiten zwischen den Gruppen gleich sind.</p>
<p><span class="math display">\[
H_0: \; \mbox{Der Anteil der beschädigten Erdbeeren ist in den vier Gruppen ähnlich hoch}
\]</span></p>
<p><span class="math display">\[
H_A: \; \mbox{Der Anteil der beschädigten Erdbeeren in mindestens einer der Behandlungen unterschiedlich ist.}
\]</span></p>
<p>Wie wir sehen ist das nicht der Fall. Wir haben hier vier Wahrscheinlichkeiten vorliegen und mindestens zwei unterscheiden sich. Welche das sind, ist wieder die Frage. Hierzu nutzen wir dann gleich die Funktion <code><a href="https://rdrr.io/r/stats/pairwise.prop.test.html">pairwise.prop.test()</a></code>. Wir immer geht die Ausgabe auch schöner und aufgeräumter.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span><span class="va">damaged</span>, <span class="va">berries</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4-sample test for equality of proportions without continuity correction

Proportion                        | Chi2(3) |     p
---------------------------------------------------
99.06% / 88.50% / 89.10% / 94.12% |   11.75 | 0.008

Alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>Warum ist ein Test auf Anteile ein <span class="math inline">\(\mathcal{X}^2\)</span>-Test? Hierfür brauchen wir noch die Informationen zu den nicht beschädigten Erdbeeren.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">non_damaged</span> <span class="op">&lt;-</span> <span class="va">berries</span> <span class="op">-</span> <span class="va">damaged</span> </span>
<span><span class="va">non_damaged</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> A  B  C  D 
 1 13 17  6 </code></pre>
</div>
</div>
<p>Nun können wir uns erstmal eine Tabelle bauen auf der wir dann den <span class="math inline">\(\mathcal{X}^2\)</span>-Test und den <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> rechnen können. Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test ist nicht nur auf eine 2x2 Kreuztabelle beschränkt. Wir können in einem <span class="math inline">\(\mathcal{X}^2\)</span>-Test auch andere <span class="math inline">\(n \times m\)</span> Tabellen testen. Auf der anderen Seite ist der <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> auf eine <span class="math inline">\(n \times 2\)</span> Tabelle beschränkt. Es müssen also immer zwei Spalten sein.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">damaged_tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">damaged</span>, <span class="va">non_damaged</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">damaged_tab</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  damaged non_damaged
A     105           1
B     100          13
C     139          17
D      96           6</code></pre>
</div>
</div>
<p>Wir erhalten die <a href="#tbl-chi-square-exp-2">Tabelle&nbsp;<span>29.4</span></a> mit den beobachteten Werten sowie die <a href="#tbl-chi-square-exp-3">Tabelle&nbsp;<span>29.5</span></a> mit den erwarteten Werten. Die Berechnung der erwarteten Werte kennen wir schon aus dem klassischen <span class="math inline">\(\mathcal{X}^2\)</span>-Test. Hier machen wir die Berechnungen nur auf einer größeren Tabelle.</p>
<div id="tbl-chi-square-exp-2" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;29.4— Eine 4x2 Tabelle für die vier Erntearten und der beschädigten Erdbeeren. Dargestellt sind die <em>beobachteten</em> Werte.</caption>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Damaged</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>damaged</em></td>
<td style="text-align: center;"><em>non_damaged</em></td>
<td style="text-align: center;"><em>berries</em></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Group</strong></td>
<td style="text-align: center;"><em>A</em></td>
<td style="text-align: center;"><span class="math inline">\(105\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{106}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>B</em></td>
<td style="text-align: center;"><span class="math inline">\(100\)</span></td>
<td style="text-align: center;"><span class="math inline">\(13\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{113}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>C</em></td>
<td style="text-align: center;"><span class="math inline">\(139\)</span></td>
<td style="text-align: center;"><span class="math inline">\(17\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{156}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>D</em></td>
<td style="text-align: center;"><span class="math inline">\(96\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{102}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{440}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{37}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = 477\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Jetzt können wir auch die Anteile der beschädigten Erdbeeren von allen Erdbeeren berechnen pro Ernteart berechnen.</p>
<p><span class="math display">\[
\begin{aligned}
Pr(A) &amp;= \cfrac{105}{106} = 0.9906 = 99.06\%\\
Pr(B) &amp;= \cfrac{100}{113} = 0.8850 = 88.50\%\\
Pr(C) &amp;= \cfrac{139}{156} = 0.8910 = 89.10\%\\
Pr(D) &amp;= \cfrac{96}{102} = 0.9411 = 94.12\%
\end{aligned}
\]</span></p>
<div id="tbl-chi-square-exp-3" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;29.5— Eine 4x2 Tabelle für die vier Erntearten und der beschädigten Erdbeeren. Dargestellt sind die zu <em>erwartenden</em> Werte, die sich aus den Randsummen ergeben würden.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 36%">
<col style="width: 34%">
<col style="width: 14%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Damaged</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>damaged</em></td>
<td style="text-align: center;"><em>non_damaged</em></td>
<td style="text-align: center;"><em>berries</em></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Group</strong></td>
<td style="text-align: center;"><em>A</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{440 \cdot 106}{477} = 97.78\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{37 \cdot 106}{477} = 8.22\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{106}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>B</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{440 \cdot 113}{477} = 104.23\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{37 \cdot 113}{477} = 8.77\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{113}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>C</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{440 \cdot 156}{477} = 143.90\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{37 \cdot 156}{477} = 12.10\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{156}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>D</em></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{440 \cdot 102}{477} = 94.09\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cfrac{37 \cdot 102}{477} = 7.91\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{102}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{440}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{37}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = 477\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Schauen wir uns nun an, ob es einen Unterschied zwischen den vier Erntearten A bis D für die Erdbeeren gibt. Einmal nutzen wir hierfür die Funktion <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code> und einmal die Funktion <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">damaged_tab</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pearson's Chi-squared test

Chi2(3) |     p
---------------
11.75   | 0.008</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span><span class="va">damaged_tab</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4-sample test for equality of proportions without continuity correction

Proportion                        | Chi2(3) |     p
---------------------------------------------------
99.06% / 88.50% / 89.10% / 94.12% |   11.75 | 0.008

Alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>Nachdem wir beide Funktionen gerechnet haben, sehen wir, dass beide Tests auf der <span class="math inline">\(\mathcal{X}^2\)</span> Statistik basieren. Das macht ja auch Sinn, denn wir rechnen ja die <em>Proportions</em> indem wir die beobachteten Werte durch die Gesamtzahl berechnen. Hier haben wir im Prinzip die gleiche Idee wie schon in den beiden obigen Beispielen umgesetzt. Wir können daher den <span class="math inline">\(\mathcal{X}^2\)</span>-Test auch einmal per Hand rechnen und kommen auf fast die gleiche <span class="math inline">\(\mathcal{X}^2\)</span>-Statistik. Wir haben eine leichte andere Statistik, da wir hier mehr runden.</p>
<p><span class="math display">\[
\begin{aligned}
\chi^2_{calc} &amp;= \cfrac{(105 - 97.78)^2}{97.78} + \cfrac{(1 - 8.22)^2}{8.22} + \\
&amp;\phantom{=}\;\; \cfrac{(100 - 104.23)^2}{104.23} + \cfrac{(13 - 8.77)^2}{8.77} + \\
&amp;\phantom{=}\;\; \cfrac{(139 - 143.90)^2}{143.90} + \cfrac{(17 - 12.10)^2}{12.10} + \\
&amp;\phantom{=}\;\; \cfrac{(96 - 94.09)^2}{94.09} + \cfrac{(6 - 7.91)^2}{7.91} = 11.74 \approx 10.04
\end{aligned}
\]</span></p>
<p>Wir wissen nun, dass es mindestens einen paarweisen Unterschied zwischen den Wahrscheinlichkeiten für eine Beschädigung der Erdbeeren der vier Behandlungen gibt.</p>
<p>Führen wir den Test nochmal detaillierter mit der Funktion <code>prop_test()</code> aus dem R Paket <code>rstatix</code> durch. Es handelt sich hier um eine Alternative zu der Standardfunktion <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code>. Das Ergebnis ist das Gleiche, aber die Aufarbeitung der Ausgabe ist anders und manchmal etwas besser weiterverarbeiteten.</p>
<p>Der Zugang ist etwas anders, deshalb bauen wir uns erstmal eine Tabelle mit den beschädigten und nicht beschädigten Erdbeeren. Dann benennen wir uns noch die Tabelle etwas um, damit haben wir dann einen besseren Überblick. Eigentlich unnötig, aber wir wollen uns hier ja auch mal mit der Programmierung beschäftigen.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">damaged_tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">damaged</span>, <span class="va">non_damaged</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">damaged_tab</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  Infected <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"yes"</span>, <span class="st">"no"</span><span class="op">)</span>,</span>
<span>  Groups <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">damaged_tab</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Groups
Infected   A   B   C   D
     yes 105 100 139  96
     no    1  13  17   6</code></pre>
</div>
</div>
<p>Dann können wir die Funktion <code>prop_test()</code> nutzen um den Test zu rechnen. Wir erhalten hier viele Informationen und müssen dann schauen, was wir dann brauchen. Dafür nutzen wir dann die Funktion <code>select()</code> und mutieren dann die Variablen in der Form, wie wir die Variablen haben wollen.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">prop_test</span><span class="op">(</span><span class="va">damaged_tab</span>, detailed <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="fu">matches</span><span class="op">(</span><span class="st">"estimate"</span><span class="op">)</span>, <span class="va">p</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>p <span class="op">=</span> <span class="fu">pvalue</span><span class="op">(</span><span class="va">p</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate_if</span><span class="op">(</span><span class="va">is.numeric</span>, <span class="va">round</span>, <span class="fl">2</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  estimate1 estimate2 estimate3 estimate4 p    
      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;
1      0.99      0.88      0.89      0.94 0.008</code></pre>
</div>
</div>
<p>Wir erhalten auch hier das gleiche Ergebnis. War auch zu erwarten, denn im Kern sind die beiden Funktionen <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> und <code>prop_test()</code> gleich. Nun können wir uns einmal den paarweisen Vergleich anschauen. Wir wollen dann im Anschluß noch das <em>Compact letter display</em> für die Darstellung der paarweisen Vergleiche berechnen. Dafür brauchen wir dann noch folgende R Pakete.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Du kannst mehr über das <em>Compact letter display</em> in dem Kapitel <a href="stat-tests-posthoc.html">Multiple Vergleiche oder Post-hoc Tests</a> erfahren.</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">rcompanion</span>, <span class="va">multcompView</span>, <span class="va">multcomp</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die Standardfunktion für die paarweisen Vergleiche von Anteilen in R ist die Funktion <code><a href="https://rdrr.io/r/stats/pairwise.prop.test.html">pairwise.prop.test()</a></code>. Wir wollen hier einmal die <span class="math inline">\(p\)</span>-Werte nicht adjustieren, deshalb schreiben wir auch <code>p.adjust.method = "none"</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.prop.test.html">pairwise.prop.test</a></span><span class="op">(</span><span class="va">damaged</span>, <span class="va">berries</span>, </span>
<span>                   p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Pairwise comparison of proportions 

data:  damaged out of berries 

  A      B      C     
B 0.0035 -      -     
C 0.0040 1.0000 -     
D 0.1118 0.2264 0.2466

P value adjustment method: none </code></pre>
</div>
</div>
<p>Wir können auch die Funktion <code>pairwise_prop_test()</code> aus dem R Paket <code>rstatix</code> nutzen. Hier haben wir dann eine andere Ausgabe der Vergleiche. Manchmal ist diese Art der Ausgabe der Ergebnisse etwas übersichlicher. Wir nutzen dann noch die Funktion <code>pvalue()</code> um die <span class="math inline">\(p\)</span>-Werte einmal besser zu formatieren.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pairwise_prop_test</span><span class="op">(</span><span class="va">damaged_tab</span>, </span>
<span>                   p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>p <span class="op">=</span> <span class="fu">pvalue</span><span class="op">(</span><span class="va">p.adj</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  group1 group2 p        p.adj p.adj.signif
  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;       
1 A      B      0.004  0.00354 **          
2 A      C      0.004  0.00401 **          
3 B      C      &gt;0.999 1       ns          
4 A      D      0.112  0.112   ns          
5 B      D      0.226  0.226   ns          
6 C      D      0.247  0.247   ns          </code></pre>
</div>
</div>
<p>Dann benutzen wir noch die Funktion <code>multcompLetters()</code> um uns das <em>Compact letter display</em> wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.prop.test.html">pairwise.prop.test</a></span><span class="op">(</span><span class="va">damaged</span>, <span class="va">berries</span>, </span>
<span>                   p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="st">"p.value"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">fullPTable</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">multcompLetters</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="st">"Letters"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   A    B    C    D 
 "a"  "b"  "b" "ab" </code></pre>
</div>
</div>
<p>Hier sehen wir dann auch den Unterschied zwischen den beiden Funktionen. Wir können für die Funktion <code>pairwise_prop_test()</code> etwas einfacher das <em>Compact letter display</em> berechnen lassen. Wir müssen uns nur eine neue Spalte <code>contrast</code> mit den Vergleichen bauen.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pairwise_prop_test</span><span class="op">(</span><span class="va">damaged_tab</span>, </span>
<span>                   p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>contrast <span class="op">=</span> <span class="fu">str_c</span><span class="op">(</span><span class="va">group1</span>, <span class="st">"-"</span>, <span class="va">group2</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pull</span><span class="op">(</span><span class="va">p</span>, <span class="va">contrast</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">multcompLetters</span><span class="op">(</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   A    B    C    D 
 "a"  "b"  "b" "ab" </code></pre>
</div>
</div>
<p>Am Ende sehen wir, dass sich die Behandlung <span class="math inline">\(A\)</span> von den Behandlungen <span class="math inline">\(B\)</span> und <span class="math inline">\(C\)</span> unterscheidet, da sich die Behandlungen nicht den gleichen Buchstaben teilen. Die Behandlung <span class="math inline">\(A\)</span> unterscheidet sich aber nicht von der Behandlung <span class="math inline">\(D\)</span>. In dieser Art und Weise können wir dann alle Behandlungen durchgehen. Du kannst mehr über das <em>Compact letter display</em> in dem Kapitel <a href="stat-tests-posthoc.html">Multiple Vergleiche oder Post-hoc Tests</a> erfahren.</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-tests-friedman.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-tests-diagnostic.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>