<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Skript Bio Data Science - 49&nbsp; Lineare gemischte Modelle</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-gee.html" rel="next">
<link href="./stat-modeling-prob-model.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-modeling-preface.html">Statistisches Modellieren</a></li><li class="breadcrumb-item"><a href="./stat-modeling-mixed.html"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-quarto-shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Quarto und Shiny App</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Testen von Hypothesen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Pre-Test oder Vortest</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelle Designs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Einfache Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Fortgeschrittene Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface-app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistische Gruppenvergleiche</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Der Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-prob-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Linear Probability Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./time-space-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zeitliche und räumliche Analysen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-pseudo-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Pseudo Zeitreihen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Zeitreihen (eng. <em>time series</em>)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Räumliche Daten (eng. <em>spatial data</em>)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./abspann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abspann</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Spielecke</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#dump-of-ideas-remove-me" id="toc-dump-of-ideas-remove-me" class="nav-link active" data-scroll-target="#dump-of-ideas-remove-me"><span class="header-section-number">49.1</span> Dump of ideas (remove me)</a></li>
  <li><a href="#annahmen-an-die-daten" id="toc-annahmen-an-die-daten" class="nav-link" data-scroll-target="#annahmen-an-die-daten"><span class="header-section-number">49.2</span> Annahmen an die Daten</a></li>
  <li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">49.3</span> Genutzte R Pakete</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"><span class="header-section-number">49.4</span> Daten</a></li>
  <li><a href="#modellierung" id="toc-modellierung" class="nav-link" data-scroll-target="#modellierung"><span class="header-section-number">49.5</span> Modellierung</a></li>
  <li><a href="#sec-mult-comp-lmer-reg" id="toc-sec-mult-comp-lmer-reg" class="nav-link" data-scroll-target="#sec-mult-comp-lmer-reg"><span class="header-section-number">49.6</span> Gruppenvergleich</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-mixed" class="quarto-section-identifier"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><em>Letzte Änderung am 09. December 2023 um 21:20:21</em></p>
<blockquote class="blockquote">
<p><em>“Wer die Arbeit kennt und sich nicht drückt, der ist verrückt.” — Tick, Trick und Track</em></p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Einführung in die linearen gemischten Modelle per Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/54ba9cn3MeY">Lineare gemischte Modelle</a> als Video Reihe. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>
<p>In diesem Kapitel vollen wir die Grundzüge der lineare gemischten Modell (eng. <em>linear mixed models</em>, abk. <em>lmm</em>) zu versuchen zu verstehen. Wir immer, es gibt dazu auch hervorragende Literatur wie das sehr ausführliche Buch von <span class="citation" data-cites="zuur2009mixed">Zuur u.&nbsp;a. (<a href="#ref-zuur2009mixed" role="doc-biblioref">2009</a>)</span>. Fangen wir also einmal an zu verstehen, wie eigentlich ein Experiment aussehen muss, damit wir ein lineares gemischtes Modell rechnen wollen. Wir haben häufig in den Agarwissenschaften Faktoren als unser <span class="math inline">\(x\)</span> vorliegen. Für das <span class="math inline">\(y\)</span> können aber jeden Messwert abbilden. Dafür gibt es dann die Funktion <code>glmer()</code>, die das Äquivalent zu der Funktion <code>glm()</code> ist. Wir haben also folgendes, mehrfaktorielles Modell vorliegen.</p>
<p><span class="math display">\[
y \sim f_1 + f_2 + f_3 + f_4
\]</span></p>
<p>Und eigentlich haben wir ja gar nicht vier <em>gleichwertige</em> Faktoren vorliegen, sondern meistens unsere Behandlungsfaktor <span class="math inline">\(f_1\)</span> und <span class="math inline">\(f_2\)</span> an dem wir interessiert sind und dann noch bis zu zwei weitere Faktoren <span class="math inline">\(f_3\)</span> und <span class="math inline">\(f_4\)</span>, die eine weitere Gruppierung repräsentieren. Wir können auch noch mehr Faktoren vorliegen haben, aber ich empfehle ein Design immer auf maximal vier Faktoren zu begrenzen. Unsere beiden Faktoren <span class="math inline">\(f_3\)</span> und <span class="math inline">\(f_4\)</span> beschreiben jetzt aber nicht noch mehr Behandlungen sondern stellen ein Feld, einen Block oder aber einen Stall dar. Wir haben es also mit Faktoren für eine “Position” zu tun. Die Position kann auch eine zeitliche Komponente sein. Deshalb schreiben wir etwas allgemeiner für die Faktoren <span class="math inline">\(f_3\)</span> und <span class="math inline">\(f_4\)</span> dann als Blockfaktor <span class="math inline">\(b_1\)</span> und <span class="math inline">\(b_2\)</span>. Wie schon erwähnt es handelt sich nicht ausschließlich um Blöcke, es können auch andere Positionen in Raum und Zeit sein. Es geht immer mehr und manchmal braucht man auch mehr Faktoren, aber in unserem Kontext hier würde ich anraten sich auf eher auf drei Faktoren zu begrenzen. Also entweder zwei Behandlungsfaktoren und ein Positionsfaktor oder aber ein Behandlungsfaktor und zwei Positionsfaktoren. Damit können wir wie folgt unser Modell schreiben.</p>
<p><span class="math display">\[
y \sim f_1 + f_2 + b_1 + b_2
\]</span></p>
<p>Als wäre das nicht kompliziert genug, haben wir meistens auch noch verschachtelte (eng. <em>nested</em>) Daten vorliegen. Damit meine ich, dass wir den Faktor <span class="math inline">\(b_1\)</span> in jedem Level des Faktors <span class="math inline">\(b_2\)</span> vorliegen haben. Wir können eben verschiedene Standorte als Faktor <span class="math inline">\(b_2\)</span> betrachten und an jedem der Standorte haben wir Blöcke <span class="math inline">\(b_1\)</span> vorliegen. Mehr dazu findest du dann auch in dem Kapitel <a href="experimental-design-r.html">Versuchsplanung in R</a> und gleich nochmal weiter unten im Text.</p>
<p>Was ist nun das Besondere an einem linearen gemischten Modell? Wie der Name schon sagt, haben wir irgendwas gemischt. Glücklicherweise mischen wir nur zwei Dinge miteinander. Wir mischen hier feste Effekte (eng. <em>fixed effect</em>) und zufällige Effekte (eng. <em>random effect</em>) miteinander. Bis jetzt kennst du eigentlich nur feste Effekte. Immer wenn wir ein Modell gebaut haben, dann haben wir das Modell mit festen Effekten gebaut. Wir haben dabei Fakotoren als feste Effekte modelliert. Was ist also nun der Unterschied zwischen der Wahl einen Faktor als festen Effekt oder zufälligen Effekt anzusehen? Zuerst ist dies eine Modellierungsentscheidung. Wir müssen uns also zwischen Arten von Modellen unterscheiden. Daher können wir auch verschiedene Modelle mit unterschiedlichen Anzahlen an Faktoren bauen und dann diese Modelle vergleichen. Welcher Faktor jetzt als fester Effekt und welcher als zufälliher Effekt gilt, liegt dabei an uns.</p>
<p>Die Idee hinter dem Modell mit <strong>festen Effekten</strong> ist, dass die beobachteten Effektgrößen von Block zu Block variieren können, was aber nur auf den Varianz der Blöcke zurückzuführen ist. In Wirklichkeit sind die wahren Effektgrößen alle gleich: Sie sind fix. Alle Blöcke haben den gleichen Mittelwert und variieren nur in der Varianz. Wir sehen aber diesen wahren Mittelwert nicht, da sich alle Blöcke eben immer leicht unterscheiden. Mehr dazu auch in <a href="https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/pooling-es.html#fem">The Fixed-Effect Model</a>)</p>
<p>Das Modell der <strong>zufälligen Effekte</strong> geht davon aus, dass es nicht nur eine wahre Effektgröße gibt, sondern eine Verteilung der wahren Effektgrößen. Jeder unserer Blöcke kann also einen anderen wahren Mittelwert haben. Das Ziel des Modells mit zufälligen Effekten ist es daher nicht, die eine wahre Effektgröße aller Blöcke zu schätzen, sondern den Mittelwert der Verteilung der wahren Effekte. Mehr dazu auch in <a href="https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/pooling-es.html#rem">The Random-Effect Model</a>)</p>
<p>Dabei verbinden die gemischten Modelle die Vorteile eines Modells mit festen Effekt sowie eines Modells mit zufälligen Effekten. Lineare gemischte Modelle schätzen nun die subjektspezifischen Auswirkungen (eng. <em>subject-specific</em>) auf die Varianz eines Versuches. Dabei kommt es häufig darauf an unter welchen Umständen eine Beobachtung gemessen wurde. Stehen die Pflanze zusammen auf einem Feld? Sind die Ferkel alle Nachkommen einer Sau? Daher erweitern wir unser lineare Modell um einen zufälligen Effekt <span class="math inline">\(z\)</span> und schreiben wie folgt.</p>
<p><span class="math display">\[
y \sim f_1 + 1|z_1
\]</span></p>
<p>Wir schreiben in R den Term für da zufällige Modell in der Form <span class="math inline">\(z_0|z_1\)</span>. Meist setzen wir den Intercept <span class="math inline">\(z_0\)</span> für den zufälligen Effekt auf <code>1</code>. Wenn wir darstellen wollen, das ein zufälliger Faktor in einem anderen zufälligen Fakotr genestet ist, dann schreiben wir <code>1|z_1/z_2</code>.</p>
<p><span class="math display">\[
y \sim f_1 + 1|z_1/z_2
\]</span></p>
<p>Das heißt, dass der zufällige Blockfaktor <span class="math inline">\(z_1\)</span> in den zufälligen Blockfaktor <span class="math inline">\(z_2\)</span> genestet ist. Das klingt jetzt etwas schräg, also einmal ein Beispiel. Wir haben eine Schule, dann sind die Schulklassen dieser Schule in der Schule genestet. Es gibt diese spezifischen Klassen mit den Schülern schlichtweg nicht in anderen Schulen. Wir sagen genestet (eng. <em>nested</em>), wenn wir sagen wollen, dass ein Faktor in einen anderen Faktor verschränkt ist. Die Klassen einer Schule sind in der Schule genestet.</p>
<p>In der <a href="#fig-mermaid-r-mixed-01">Abbildung&nbsp;<span>49.1</span></a> siehst du einmal exemplarisch die Darstellung eines experimentellen Designs mit drei Faktoren. Die Behandlung ist dabei ein fester Effekt und die beiden Faktoren für die Tische und die Gewächshäuser sind zufällige Effekte. Damit wir in der Folge nicht immer so sehr durcheinanderkommen, habe ich die festen Effekt als blau Kästen und die zufälligen Effekte als orange Kästen gesetzt.</p>
<div class="cell" data-fig-width="6">
<div class="cell-output-display">
<div id="fig-mermaid-r-mixed-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div>
<pre class="mermaid mermaid-js" data-label="fig-mermaid-r-mixed-01">flowchart LR
    C(Behandlungen):::fixed --- D(((nested))) --&gt; E(Tische):::random --- F(((nested))) --&gt; G(Gewächshäuser):::random
    classDef fixed fill:#56B4E9,stroke:#333,stroke-width:0.75px
    classDef random fill:#E69F00,stroke:#333,stroke-width:0.75px
</pre>
</div>
<figcaption class="figure-caption">Abbildung&nbsp;49.1— Beispiel für drei Faktoren und deren Abhänigigkeitsstruktur untereinander. Die Behandlungen sind in den Tischen genested und die Tische in den Gewächshäusern. Die festen Effekte sind als blaue Kästen und die zufälligen als orange Kästen eingefärbt.</figcaption>
</figure>
</div>
</div>
</div>
<p>Okay, das ist jetzt bis hierher sehr abstrakt. Machen wir das mal konkret mit einem Beispiel mit drei Behandlungen gegen Blattläuse auf jeweils vier Tischen in drei Gewächshäusern. Pro Behandlung nehmen wir fünf Pflanzen. Damit ergibt sich folgendes Schema der Abhängigkeiten mit den jeweiligen Anzahlen.</p>
<p><span class="math display">\[
\overbrace{\mbox{Gewächshauser}}^{n_g = 3} \xrightarrow[alle]{beinhaltet} \underbrace{\mbox{Tische}}_{n_t = 4} \xrightarrow[alle]{beinhaltet} \overbrace{\mbox{Behandlungen}}^{n_b = 3} \xrightarrow[alle]{beinhaltet} \underbrace{\mbox{Beobachtungen}}_{n_w = 5}
\]</span></p>
<p>Wie du an dem obigen Beispiel sehen kannst, kommen wir bei linearen gemischten Modellen sehr schnell auf sehr große Fallzahlen. Wir haben im obigen, kleinen Beispiel alleine schon eine Fallzahl von <span class="math inline">\(n_{gesamt} = 3 \times 4 \times 3 \times 5 = 180\)</span> Pflanzen. Und damit ist eigentlich unser Beispiel sehr klein gewählt. Eigentlich brauchen wir für einen zufälligen Effekt als Daumenregel immer mehr als fünf Level für eine gute Modellschätzung.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Weitere Tutorien zu gemischten Modellen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wie immer und natürlich im Besonderen bei linearen gemischten Modellen, gibt es eine Reihe von tollen Hilfen. Daher hier einmal eine lose Sammlung an Ideen und Tutorien, die mir geholfen haben dieses Kapitel hier zu schreiben. Fast jede Quelle hat dann nochmal Referezen zu weiteren Informationen und Hilfen.</p>
<ul>
<li><a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#should-i-treat-factor-xxx-as-fixed-or-random">GLMM FAQ – Ben Bolker and others</a> ist meine Anlaufstelle, wenn ich mal was nachlesen muss. Eine sehr hilfreiche und umfangreiche Sammlung.</li>
<li><a href="https://m-clark.github.io/mixed-models-with-R/">Mixed Models with R – Getting started with random effects</a> ist ein freies Buch, was ich auch immer mal wieder anschaue, wenn ich Fragen rund um das gemischte Modell habe. Dies ist hier nur ein Kapitel mit einer Zusammenfassung und eben kein ganzes Buch.</li>
<li>Teile dieses Kapitel auf dem tollen <a href="https://ourcodingclub.github.io/tutorials/mixed-models/">Tutorium von Gabriela K Hajduk</a>. Die Daten und Inhalte wurden von mir teilweise gekürzt sowie inhaltlich angepasst. Auch hier findest du sehr viel mehr Informationen und dann auch Links zu weiteren Quellen.</li>
<li>Ideen und weitere Erklärungen sind auch beim <a href="https://rlbarter.github.io/Practical-Statistics/2017/03/03/fixed-mixed-and-random-effects/">Tutorium von Sara Stoudt</a> zu finden. Hier musst du dich aber mehr Einarbeiten, da der Artikel etwas mehr mathematisch aufgebaut ist.</li>
<li>Als weiteres Tutorium für die Auswertung von linearen gemischten Modellen und allgemein dem Modellieren von agarwissenschaftlichen Daten kann ich die Seite <a href="https://schmidtpaul.github.io/dsfair_quarto/">Data Science for Agriculture in R</a> sehr empfehlen. Dort findest du dann auch die Anwebdung der R Pakete aus diesem Kapitel.</li>
<li><a href="https://cran.r-project.org/web/packages/broom.mixed/vignettes/broom_mixed_intro.html">Introduction to <code>{broom.mixed}</code></a> hilft dabei die Ausgaben der verschiedenen R Pakte, die es zu gemischten Modellen gibt zu vereinheitlichen. Wir erhalten dann immer die gleiche <code>tidy()</code>-Ausgabe und nicht immer was anderes von den Funktionen wiedergegeben.</li>
</ul>
</div>
</div>
<section id="dump-of-ideas-remove-me" class="level2" data-number="49.1">
<h2 data-number="49.1" class="anchored" data-anchor-id="dump-of-ideas-remove-me"><span class="header-section-number">49.1</span> Dump of ideas (remove me)</h2>
<p><a href="https://multilevelmod.tidymodels.org/articles/multilevelmod.html" class="uri">https://multilevelmod.tidymodels.org/articles/multilevelmod.html</a></p>
</section>
<section id="annahmen-an-die-daten" class="level2" data-number="49.2">
<h2 data-number="49.2" class="anchored" data-anchor-id="annahmen-an-die-daten"><span class="header-section-number">49.2</span> Annahmen an die Daten</h2>
<p>Im folgenden Kapitel zu den linearen gemischten Modellen gehen wir davon aus, dass die Daten in der vorliegenden Form <em>ideal</em> sind. Das heißt wir haben weder fehlende Werte vorliegen, noch haben wir mögliche Ausreißer in den Daten. Auch wollen wir keine Variablen selektieren. Wir nehmen alles was wir haben mit ins Modell. Sollte eine oder mehre Bedingungen nicht zutreffen, dann schaue dir einfach die folgenden Kapitel an.</p>
<ul>
<li>Wenn du fehlende Werte in deinen Daten vorliegen hast, dann schaue bitte nochmal in das <a href="stat-modeling-missing.html"><span>Kapitel&nbsp;42</span></a> zu Imputation von fehlenden Werten.</li>
<li>Wenn du denkst, dass du Ausreißer oder auffällige Werte in deinen Daten hast, dann schaue doch bitte nochmal in das <a href="stat-modeling-outlier.html"><span>Kapitel&nbsp;41</span></a> zu Ausreißer in den Daten.</li>
<li>Wenn du denkst, dass du zu viele Variablen in deinem Modell hast, dann hilft dir das <a href="stat-modeling-variable-selection.html"><span>Kapitel&nbsp;40</span></a> bei der Variablenselektion.</li>
</ul>
<p>Das Thema Modellvergleich und Variablenselektion ist im Falle des linearen gemischten Modells nochmal etwas spezieller. Wir gehen hier auch nochmal in einem Abschnitt drauf ein, wie wir das hier in dem Fall von linearen gemischten Modellen machen.</p>
</section>
<section id="genutzte-r-pakete" class="level2" data-number="49.3">
<h2 data-number="49.3" class="anchored" data-anchor-id="genutzte-r-pakete"><span class="header-section-number">49.3</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, magrittr, broom, see, simstudy,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               multcomp, emmeans, lme4, broom.mixed, readxl,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               parameters, ggridges, scales, performance, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               conflicted)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"select"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"filter"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>cbbPalette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#000000"</span>, <span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section>
<section id="daten" class="level2" data-number="49.4">
<h2 data-number="49.4" class="anchored" data-anchor-id="daten"><span class="header-section-number">49.4</span> Daten</h2>
<p>In diesem fiktiven Datenbeispiel wollen wir uns die Testscores eines Intelligentest bei <span class="math inline">\(N = 480\)</span> Drachen anschauen. Wir sind dafür an acht Berge gefahren und haben die dortigen Drachen an den drei Flanken des Berges getestet. Daher hat der Faktor <code>mountain</code> acht Level mit Bavarian, Ligurian, Emmental, Central, Maritime, Southern, Julian, und Sarntal. Die drei Flanken des Berges bilden wir im Faktor <code>site</code> mit den Leveln north, east und south ab. In <a href="#fig-mountain-site">Abbildung&nbsp;<span>49.2</span></a> sehen wir eine Skizze für drei Berge mit den jeweiligen Flanken, wo gemessen wurde.</p>
<div id="fig-mountain-site" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/mountain.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.2— Beispiel für drei der acht Berge mit <em>Bavarian</em>, <em>Central</em> und <em>Julian</em>. Auf jeden der acht Berge wurden an drei Seiten <em>north</em>, <em>east</em> und <em>south</em> die Testscores der dort lebenden Drachen erhoben. Die dort lebenden Drachen wurden dann in fünf Gruppen nach der Körperlänge eingeteilt.</figcaption>
</figure>
</div>
<p>Damit haben wir dann folgende Struktur der Faktoren vorliegen.</p>
<div class="cell" data-fig-width="6">
<div class="cell-output-display">
<div id="fig-mermaid-r-mixed-dragon" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div>
<pre class="mermaid mermaid-js" data-label="fig-mermaid-r-mixed-dragon">flowchart LR
    C(dragons):::fixed --- D(((nested))) --&gt; E(site):::random --- F(((nested))) --&gt; G(mountain):::random
    classDef fixed fill:#56B4E9,stroke:#333,stroke-width:0.75px
    classDef random fill:#E69F00,stroke:#333,stroke-width:0.75px
</pre>
</div>
<figcaption class="figure-caption">Abbildung&nbsp;49.3— In unseren Drachendaten leben die einzelnen Drachen auf einer der drei Seiten <code>site</code> eines Berges <code>mountain</code>. Daher sind die Drachen mit ihrem Faktor <code>body_length_cat</code> in dem Faktor <code>site</code> genestet. Der Faktor <code>site</code> ist dann wiederum in jedem Faktor <code>mountain</code> genestet.</figcaption>
</figure>
</div>
</div>
</div>
<p>Die Daten liegen in dem Datensatz <code>dragons.csv</code> ab. Wir müssen aber noch einen Faktor <code>body_length_cat</code> bilden in dem wir die <code>body_length</code> der einzelnen Drachen in Kategorien umwandeln. Wir wollen später noch Gruppenvergleiche rechnen und brauchen daher einen Faktor mit Leveln. Daher nutzen wir die Funktion <code>case_when()</code> um einen Faktor mit fünf Größenkategorien zu bilden. Danach müssen wir wie immer noch die <code>character</code> Spalten in die entsprechenden Faktoren umwandeln.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dragons_tbl <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"data/dragons.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">body_length_cat =</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">case_when</span>(body_length <span class="sc">&lt;</span> <span class="dv">170</span> <span class="sc">~</span> <span class="st">"tiny"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                     body_length <span class="sc">&gt;=</span> <span class="dv">170</span> <span class="sc">&amp;</span> body_length <span class="sc">&lt;</span> <span class="dv">180</span> <span class="sc">~</span> <span class="st">"small"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>                     body_length <span class="sc">&gt;=</span> <span class="dv">180</span> <span class="sc">&amp;</span> body_length <span class="sc">&lt;</span> <span class="dv">200</span> <span class="sc">~</span> <span class="st">"medium"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                     body_length <span class="sc">&gt;=</span> <span class="dv">200</span> <span class="sc">&amp;</span> body_length <span class="sc">&lt;</span> <span class="dv">220</span> <span class="sc">~</span> <span class="st">"large"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                     body_length <span class="sc">&gt;=</span> <span class="dv">220</span> <span class="sc">~</span> <span class="st">"gigantic"</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">body_length_cat =</span> <span class="fu">as_factor</span>(body_length_cat),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">mountain =</span> <span class="fu">as_factor</span>(mountain),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">site =</span> <span class="fu">factor</span>(site, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"north"</span>, <span class="st">"east"</span>, <span class="st">"south"</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(test_score, body_length, body_length_cat, <span class="fu">everything</span>())</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Es ergibt sich dann der Datensatz wie in <a href="#tbl-dragon">Tabelle&nbsp;<span>49.1</span></a> gezeigt. Wir belassen die Körperlänge der Drachen in der kontinuierlichen Form nochmal mit in den Daten.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-dragon" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;49.1— Datensatz der Testscores für die Drachen auf verschiedenen Bergen und dort an verschiedenen Flanken der Berge.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">test_score</th>
<th style="text-align: center;">body_length</th>
<th style="text-align: center;">body_length_cat</th>
<th style="text-align: center;">mountain</th>
<th style="text-align: center;">site</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">16.15</td>
<td style="text-align: center;">165.55</td>
<td style="text-align: center;">tiny</td>
<td style="text-align: center;">Bavarian</td>
<td style="text-align: center;">north</td>
</tr>
<tr class="even">
<td style="text-align: center;">33.89</td>
<td style="text-align: center;">167.56</td>
<td style="text-align: center;">tiny</td>
<td style="text-align: center;">Bavarian</td>
<td style="text-align: center;">north</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6.04</td>
<td style="text-align: center;">165.88</td>
<td style="text-align: center;">tiny</td>
<td style="text-align: center;">Bavarian</td>
<td style="text-align: center;">north</td>
</tr>
<tr class="even">
<td style="text-align: center;">18.84</td>
<td style="text-align: center;">167.69</td>
<td style="text-align: center;">tiny</td>
<td style="text-align: center;">Bavarian</td>
<td style="text-align: center;">north</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">59.37</td>
<td style="text-align: center;">213.58</td>
<td style="text-align: center;">large</td>
<td style="text-align: center;">Sarntal</td>
<td style="text-align: center;">south</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68.75</td>
<td style="text-align: center;">207.63</td>
<td style="text-align: center;">large</td>
<td style="text-align: center;">Sarntal</td>
<td style="text-align: center;">south</td>
</tr>
<tr class="even">
<td style="text-align: center;">74.89</td>
<td style="text-align: center;">198.25</td>
<td style="text-align: center;">medium</td>
<td style="text-align: center;">Sarntal</td>
<td style="text-align: center;">south</td>
</tr>
<tr class="odd">
<td style="text-align: center;">65.95</td>
<td style="text-align: center;">208.06</td>
<td style="text-align: center;">large</td>
<td style="text-align: center;">Sarntal</td>
<td style="text-align: center;">south</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Bevor wir mit dem Modellieren beginnen, wollen wir erstmal visuell überprüfen, ob unser Outcome <span class="math inline">\(y\)</span> mit dem Testscore auch normalverteilt ist. Wir benötigen für das <em>klaissche</em> lineare gemischte Modell ein normalverteiltes Outcome <span class="math inline">\(y\)</span>. In <a href="#fig-mixed-1">Abbildung&nbsp;<span>49.4</span></a> sehen wir das Histogramm der Verteilung des Testscores für alle <span class="math inline">\(N = 480\)</span> Drachen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(test_score)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-1-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.4— Histogramm des Testscores über alle Datenpunkte zur Überprüfung der Annahme der Normalverteilung. Wir sehen eine approximative Normalverteilung des Testscores.</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir können in der <a href="#fig-mixed-2">Abbildung&nbsp;<span>49.5</span></a> auch nochmal schauen, ob die Annahme der annährenden Normalverteilung für unseren Testscore auch für jedes Level unseres Faktors der Körperlängen gegeben ist. Wir sehen auch hier, dass der Testscore einer Normalverteilung über alle Kategorien der Körperlänge folgt.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(<span class="at">y =</span> body_length_cat, <span class="at">x =</span> test_score, <span class="at">fill =</span> body_length_cat)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_ridges</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-2-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.5— Histogramm des Testscores aufgeteilt nach Kategorie der Körpergröße zur Überprüfung der Annahme der Normalverteilung. Wir sehen eine approximative Normalverteilung des Testscores für alle Kategorien der Körpergröße.</figcaption>
</figure>
</div>
</div>
</div>
<p>Natürlich können wir uns hier noch weitere Abbildungen erstellen, aber hier soll es erstmal reichen. Wir sehen, dass der Testscore einer Normalverteilung folgt und dass die Varianzen vermutlich homogen sind, da die Histogramme ungefähr gleich breit sind. Ja, ein wenig unterscheiden sich die Verteilungen, aber so gravierend ist es erstmal nicht.</p>
</section>
<section id="modellierung" class="level2 page-columns page-full" data-number="49.5">
<h2 data-number="49.5" class="anchored" data-anchor-id="modellierung"><span class="header-section-number">49.5</span> Modellierung</h2>
<p>Bevor wir jetzt mit dem Modellieren beginnen, müssen wir noch kurz in einem QQ-Plot schauen, ob unser Ourcome <code>testscore</code> auch ungefähr normalverteilt ist. <a href="#fig-mixed-6">Abbildung&nbsp;<span>49.6</span></a> zeigt den QQ-Plot des Testscores. Wir sehen, dass der Hauptteil der Beobachtungen auf der Geraden liegt und wir nehmen daher an, dass der Testscore zumindest approximativ normalverteilt ist. Wir können also mit einem gaussian linearen gemischten Modell weitermachen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(<span class="at">sample =</span> test_score)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_okabeito</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-6-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.6— QQ-Plot zu Überprüfung, ob der Testscore einer Normalverteilung folgt. Die Punkte liegen ungefähr auf der Geraden als Winkelhalbierende, so dass wi eine Normalverteilung des Testscores annehmen können.</figcaption>
</figure>
</div>
</div>
</div>
<p>Schauen wir uns nun als erstes das Modell <code>lm_simple_fit</code> einmal an. Wir bauen das Modell nur mit der Faktorvariable <code>body_length_cat</code>. Wir erhalten dann gleich die Ausgabe des Modells über die Funktion <code>model_parameters()</code> in einer aufgearbeiteten Form.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm_simple_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(test_score <span class="sc">~</span> body_length_cat, <span class="at">data =</span> dragons_tbl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>lm_simple_fit <span class="sc">%&gt;%</span> <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter                  | Coefficient |   SE |         95% CI | t(475) |      p
----------------------------------------------------------------------------------
(Intercept)                |       24.61 | 4.33 | [16.10, 33.12] |   5.68 | &lt; .001
body length cat [small]    |        2.63 | 5.39 | [-7.96, 13.21] |   0.49 | 0.626 
body length cat [medium]   |       24.89 | 4.68 | [15.70, 34.07] |   5.32 | &lt; .001
body length cat [large]    |       32.50 | 4.55 | [23.56, 41.43] |   7.15 | &lt; .001
body length cat [gigantic] |       29.32 | 5.20 | [19.10, 39.54] |   5.64 | &lt; .001</code></pre>
</div>
</div>
<p>Der Intercept beinhaltet den Mittelwert für die Drachen des Levels <code>[tiny]</code>. Die jeweiligen Koeffizienten dann die Abweichung von den Drachen des Levels <code>[tiny]</code>. Daher sind Drachen des Levels <code>[small]</code> ungefähr um <span class="math inline">\(2.63\)</span> Einheiten intelligenter. Wir sehen dann an dem <span class="math inline">\(p\)</span>-Wert, ob sich die Koeffizienten signifikant von 0 unterscheiden. In <a href="#fig-mixed-3">Abbildung&nbsp;<span>49.7</span></a> sehen wir nochmal die Boxplots der einzelnen Testscores aufgeteilt nach der Körpergröße. Wir erkennen, dass die kleineren Drachen tendenziell dümmer sind als die großen Drachen. Wir sehen zwei Plateaus.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(<span class="at">x =</span> body_length_cat, <span class="at">y =</span> test_score, <span class="at">fill =</span> body_length_cat)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-3-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.7— Boxplots der einzelnen Testscores aufgeteilt nach der Körpergröße.</figcaption>
</figure>
</div>
</div>
</div>
<p>Nun haben wir aber nicht nur die Körpergrößen gemessen sondern auch auf welchem Berg wir die jeweiligen Drachen gefunden haben. Nun könnte es sein, dass der Berg einen viel größeren Einfluss auf die Inteliegenz hat als die Drachenkörpergröße. Wir könnten einen Confoundereffekt durch die Berge vorliegen haben. Ergänzen wir also das Modell um den Faktor <code>mountain</code> und erhalten das Modell <code>lm_mountain_fit</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lm_mountain_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(test_score <span class="sc">~</span> body_length_cat <span class="sc">+</span> mountain, <span class="at">data =</span> dragons_tbl)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lm_mountain_fit <span class="sc">%&gt;%</span> <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter                  | Coefficient |   SE |         95% CI | t(468) |      p
----------------------------------------------------------------------------------
(Intercept)                |       20.93 | 3.34 | [14.36, 27.49] |   6.27 | &lt; .001
body length cat [small]    |        1.67 | 3.89 | [-5.98,  9.32] |   0.43 | 0.668 
body length cat [medium]   |        3.55 | 3.72 | [-3.76, 10.85] |   0.95 | 0.341 
body length cat [large]    |        3.59 | 4.30 | [-4.86, 12.03] |   0.83 | 0.405 
body length cat [gigantic] |        0.08 | 4.85 | [-9.45,  9.60] |   0.02 | 0.988 
mountain [Ligurian]        |       17.33 | 3.58 | [10.28, 24.37] |   4.83 | &lt; .001
mountain [Emmental]        |       15.91 | 3.63 | [ 8.79, 23.04] |   4.39 | &lt; .001
mountain [Central]         |       35.62 | 3.69 | [28.36, 42.88] |   9.64 | &lt; .001
mountain [Maritime]        |       48.75 | 3.24 | [42.39, 55.11] |  15.06 | &lt; .001
mountain [Southern]        |        8.47 | 2.74 | [ 3.08, 13.85] |   3.09 | 0.002 
mountain [Julian]          |       45.74 | 3.86 | [38.15, 53.33] |  11.85 | &lt; .001
mountain [Sarntal]         |       41.03 | 3.30 | [34.54, 47.53] |  12.42 | &lt; .001</code></pre>
</div>
</div>
<p>Wie wir sehen, werden nun die Körpergrößen der Drachen nicht mehr als signifikant ausgegeben. Die Effekte der Körpergröße auf den Testscore sind auch viel kleiner geworden, wenn wir die <code>mountain</code> mit in das Modell nehmen. Anscheinend hat der Berg auf dem wir den Drachen getroffen haben einen viel größeren Einfluss auf die Intelligenz als die Körpergröße. Wir können uns den Zusammenhang zwischen dem Testscore und dem Berg auch in der <a href="#fig-mixed-4">Abbildung&nbsp;<span>49.8</span></a> einmal anschauen.</p>
<p>Eigentlich würden wir erwarten, dass es keinen Effekt der Berge auf den Testscore der Drachen gibt. Es müsste eigentlich egal sein, wo wir einen Drachen befragen, wenn wir nur an der Körpergröße und dem Testscore interessiert sind. Wir sehen jedoch in der <a href="#fig-mixed-4">Abbildung&nbsp;<span>49.8</span></a> einen klaren Unterschied zwischen den Bergen im Bezug auf den Testscore.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(mountain, test_score, <span class="at">fill =</span> mountain)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-4-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.8— Boxplots der einzelnen Testscores aufgeteilt nach dem Berg der Befragung.</figcaption>
</figure>
</div>
</div>
</div>
<p>In der <a href="#fig-mixed-5">Abbildung&nbsp;<span>49.9</span></a> sehen wir den Zusammenhang von Testscore und der Körpergröße sowie den Bergen auf denen das Interview stattgefunden hat. so langsam dämmert uns warum wir hier einen Effekt der Körperlänge zu dem Testscore sehen. Die kleineren Drache sind alle nur auf bestimmten Bergen zu finden! Betrachten wir die Berge mit in dem Modell, dann hat die Körpergröße keinen Einfluß mehr.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(<span class="at">x =</span> body_length_cat, <span class="at">y =</span> test_score, <span class="at">fill =</span> mountain)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">preserve =</span> <span class="st">"single"</span>)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>() <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Mountain"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-5-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.9— Boxplots der einzelnen Testscores aufgeteilt nach dem Berg der Befragung und der Körpergröße.</figcaption>
</figure>
</div>
</div>
</div>
<p>Der Zusammenhang wird vielleicht in <a href="#fig-mixed-7">Abbildung&nbsp;<span>49.10</span></a> nochmal klarer. Hier schauen wir uns den Zusamenhang wieder für die Körperlänge getrennt für die Berge an. Nur zeichnen wir jetzt jeden einzelnen Berg in ein Subplot. Wir sehen, dass es hier fast keinen Unterschied macht, wie lang die Drachen sind. Der Testscore ist immer gleich. Was einen Unterschied macht, sind die Berge.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dragons_tbl, <span class="fu">aes</span>(<span class="at">x =</span> body_length_cat, <span class="at">y =</span> test_score, <span class="at">fill =</span> mountain)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">preserve =</span> <span class="st">"single"</span>)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>() <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Mountain"</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> mountain) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mixed-7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-7-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.10— Boxplots der einzelnen Testscores aufgeteilt nach dem Berg der Befragung und der Körpergröße in getrennten Subplots.</figcaption>
</figure>
</div>
</div>
</div>
<p>Schauen wir uns nun einmal ein lineares gemischtes Modell an. Wir nutzen daszu das R Paket <code>{lme4}</code>. Wir haben auch noch andere Pakete zur Aswahl, aber wir nutzen hier erstmal das gängiste Paket. Um ein lineares gemischtes Modell in R zu schätzen nutzen wir die Funktion <code>lmer()</code>. Die Funktion <code>lmer()</code> nimmt an, dass das Outcome <code>test_score</code> normalverteilt ist. Wir haben diese Annahme ja weiter oben in dem QQ-Plot überprüft.</p>
<p>In einem lineare gemischten Modell müssen wir die <em>festen</em> Effekte sowie die <em>zufälligen</em> Effekte definieren. Die festen Effekte werden ganz normal wie wir es gewohnt sind in das Modell eingegeben. Die zufälligen Effkete schreiben wir in eine Klammer in der Form <code>(1|)</code>.</p>
<p>Wir schreiben <code>(1|moutain_range)</code> und definieren damit die Variable <code>mountain</code> als zufälligen Effekt im Modell. Wir schreiben <code>1|</code> vor <code>mountain</code>, da wir für jeden Berg die gleiche Steigung von Körperlänge und Testscore annehmen. Wir können dann später noch das Model komplizierter aufbauen und jedem Berg eine eigene Steigung erlauben. Bauen wir uns jetzt erstmal ein lineares gemischtes Modell mit einem festen Effekt <code>body_length_cat</code> und einem zufälligen Effekt <code>(1|mountain)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lmer_1_fit <span class="ot">&lt;-</span> <span class="fu">lmer</span>(test_score <span class="sc">~</span> body_length_cat <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> mountain), <span class="at">data =</span> dragons_tbl)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>lmer_1_fit <span class="sc">%&gt;%</span> <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter                  | Coefficient |   SE |         95% CI | t(473) |      p
----------------------------------------------------------------------------------
(Intercept)                |       46.85 | 7.43 | [32.25, 61.45] |   6.30 | &lt; .001
body length cat [small]    |        1.68 | 3.89 | [-5.97,  9.33] |   0.43 | 0.666 
body length cat [medium]   |        4.08 | 3.71 | [-3.20, 11.37] |   1.10 | 0.271 
body length cat [large]    |        4.49 | 4.27 | [-3.90, 12.88] |   1.05 | 0.293 
body length cat [gigantic] |        1.03 | 4.81 | [-8.43, 10.49] |   0.21 | 0.831 

# Random Effects

Parameter                | Coefficient
--------------------------------------
SD (Intercept: mountain) |       18.21
SD (Residual)            |       14.96</code></pre>
</div>
</div>
<p>Unser Model sieht etwas aufgeräumter aus. Als feste Effekte haben wir nur noch die Körperlänge <code>body_length_cat</code> und die dazugehörigen Koeffizienten des Modells. Unsere Variable <code>mountain</code> verschwindet dann in den zufälligen Effekten. Die Funktion <code>summary</code> liefert uns den gesamten Ausdruck, der etwas überwältigend ist. Vieles brauchen wir auch nicht davon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lmer_1_fit <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/lmer_summary.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
<p>Was wir extrahieren wollen ist die Information von den zufälligen Effekten. Wir wollen wissen, wieviel Varianz durch die zufälligen Effekte erklärt wird. Wir nutzen dazu die Funktion <code>VarCorr()</code>, die uns erlaubt die Information zu en zufälligen Effekten zu extrahieren und auszugeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">VarCorr</span>(lmer_1_fit), <span class="at">comp =</span> <span class="st">"Variance"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Variance
 mountain (Intercept) 331.42  
 Residual             223.83  </code></pre>
</div>
</div>
<p>Wieviel Varianz erklären nun die Berge? Wir können die erklärte Varianz der zufälligen Effekte einfach berechnen. Wir vergleichen die erklärte Varianz von <code>mountain</code> mit der gesamten Varianz. Die gesamte Varianz ist die Varianz aller zufälligen Effekte plus der residualen Varianz. Wir erhalten dann <span class="math inline">\(R^2_{random} = 339.7/(339.7 + 223.8) \approx 0.60\)</span>. Wir sehen, dass ca. 60% der Varianz in unseren Daten von der Variable <code>mountain</code> verursacht wird.</p>
<p>Wir können die Funktion <code>model_performance()</code> nutzen um mehr über den Fit des Modells zu erfahren. Das <code>R2 (cond.)</code> ist faktisch das gleiche wie wir gerade oben berechnet haben. Wir benötigen also nicht immer den Ausdruck der zufälligen Effekte. Wir können auch die Informationen aus der Funktion <code>model_performance()</code> nehmen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>lmer_1_fit <span class="sc">%&gt;%</span> <span class="fu">model_performance</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC      |     AICc |      BIC | R2 (cond.) | R2 (marg.) |   ICC |   RMSE |  Sigma
----------------------------------------------------------------------------------
3983.403 | 3983.640 | 4012.620 |      0.598 |      0.004 | 0.597 | 14.774 | 14.961</code></pre>
</div>
</div>
<p>In der Abbildung <a href="#fig-mixed-8">Abbildung&nbsp;<span>49.11</span></a> schauen wir uns nochmal an, ob wir das Modell auch gut gefittet haben. Der Residualplot sieht gut aus, wir erkennen kein Muster. Ebenso sieht der QQ-Plot gut aus, die Beobachtungen liegen alle auf der Geraden. Wir sind mit dem Modell soweit erstmal ganz zufrieden.</p>
<div id="fig-mixed-8" class="cell column-page quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-mixed-8-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-8-1.png" class="img-fluid figure-img" data-ref-parent="fig-mixed-8" width="480"></p>
<figcaption class="figure-caption">(a) Residualplot</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-mixed-8-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-mixed-8-2.png" class="img-fluid figure-img" data-ref-parent="fig-mixed-8" width="480"></p>
<figcaption class="figure-caption">(b) QQ-Plot</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;49.11— Visuelle Überprüfung des Modells mit dem Residual und QQ-Plot.</figcaption><p></p>
</figure>
</div>
<p>Wir haben noch eine Variable in unseren Daten ignoriert. Wir haben uns bis jetzt nicht die Variabl <code>site</code> angeschaut. Auf jedem Berg haben wir die Drachen noch auf verschiedenen Flanken des Berges <code>site</code> befragt. Das heißt, wir haben die Variable <code>site</code>, die in der Variable <code>mountain_site</code> genestet ist. Wir schreiben daher ein neues Modell und nutzen die Schreibweise <code>(1|mountain/site)</code> um zu beschreiben, dass <code>site</code> immer zusamen in einem Berg vorkommt. Schaue dir dazu nochmal die Abbidlung ganz zu Beginn dieses Kapitels an um die Zusammenhänge nochmal visualisiert zu bekommen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lmer_2_fit <span class="ot">&lt;-</span> <span class="fu">lmer</span>(test_score <span class="sc">~</span> body_length_cat <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>mountain<span class="sc">/</span>site), <span class="at">data =</span> dragons_tbl) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>lmer_2_fit <span class="sc">%&gt;%</span> <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter                  | Coefficient |   SE |          95% CI | t(472) |      p
-----------------------------------------------------------------------------------
(Intercept)                |       46.89 | 7.80 | [ 31.56, 62.22] |   6.01 | &lt; .001
body length cat [small]    |        1.32 | 3.99 | [ -6.51,  9.16] |   0.33 | 0.740 
body length cat [medium]   |        3.34 | 4.61 | [ -5.73, 12.41] |   0.72 | 0.470 
body length cat [large]    |        4.85 | 5.15 | [ -5.26, 14.97] |   0.94 | 0.346 
body length cat [gigantic] |        1.37 | 5.83 | [-10.08, 12.83] |   0.24 | 0.814 

# Random Effects

Parameter                     | Coefficient
-------------------------------------------
SD (Intercept: site:mountain) |        4.79
SD (Intercept: mountain)      |       17.88
SD (Residual)                 |       14.46</code></pre>
</div>
</div>
<p>Das Modell hat nun einen weiteren zufälligen Effekt. Es werden jetzt auch nochmal für jeden Berg die Flankeneffekte mit berücksichtigt. Hat das überhaupt einen Einfluss auf das Modell? Schauen wir uns einmal die Modellgüte mit der Funktion <code>model_performance()</code> an.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>lmer_2_fit <span class="sc">%&gt;%</span> <span class="fu">model_performance</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC      |     AICc |      BIC | R2 (cond.) | R2 (marg.) |   ICC |   RMSE |  Sigma
----------------------------------------------------------------------------------
3970.693 | 3970.999 | 4004.084 |      0.623 |      0.004 | 0.621 | 14.120 | 14.460</code></pre>
</div>
</div>
<p>Wir sehen, dass sich die erklärte varianz leicht erhöht hat. Die <span class="math inline">\(R^2_{random}\)</span> liegt jetzt bei <span class="math inline">\(0.623\)</span> also fast 62%. Etwas besser als vorher, aber auch nicht unbedingt sehr viel mehr.</p>
<p>Wie können wir nun unsere vier Modelle miteinander vergleichen? Wir haben ja folgende Modelle vorliegen:</p>
<ul>
<li>Das simple lineare Modell <code>lm_simple_fit</code> mit <code>test_score ~ body_length_cat</code>.</li>
<li>Das multiple lineare Modell <code>lm_mountain_fit</code> mit <code>test_score ~ body_length_cat + mountain</code>.</li>
<li>Das gemischte lineare Modell <code>lmer_1_fit</code> mit <code>test_score ~ body_length_cat + (1|mountin_range)</code>.</li>
<li>Das genestete gemischte lineare Modell <code>lmer_2_fit</code> mit <code>test_score ~ body_length_cat + (1|mountain/site)</code>.</li>
</ul>
<p>Um die Modelle miteinander zu vergleichen können wir die Funktion <code>compare_performance()</code> nutzen. Wir erhalten mit der Option <code>rank = TRUE</code> auch eine Sortierung der Modelle wieder. Das beste Modell steht dann ganz oben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(lm_simple_fit, lm_mountain_fit, lmer_1_fit, lmer_2_fit, <span class="at">rank =</span> <span class="cn">TRUE</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name            |   Model |   RMSE |  Sigma | AIC weights | AICc weights | BIC weights | Performance-Score
----------------------------------------------------------------------------------------------------------
lm_mountain_fit |      lm | 14.772 | 14.960 |       1.000 |        1.000 |       0.330 |            86.49%
lmer_2_fit      | lmerMod | 14.120 | 14.460 |    5.84e-05 |     7.41e-05 |       0.655 |            60.00%
lmer_1_fit      | lmerMod | 14.774 | 14.961 |    1.72e-07 |     2.26e-07 |       0.016 |            36.89%
lm_simple_fit   |      lm | 20.661 | 20.770 |    1.24e-67 |     1.68e-67 |    9.06e-62 |             0.00%</code></pre>
</div>
</div>
<p>In diesem Beispiel wäre sogar eine multiple lineare Regression das beste Modell. Wir würden also auch mit zwei festen Effekten die Variabilität der Berge richtig modellieren. Der Effekt der Flanken auf den Testscore scheint ziemlich klein zu sein, so dass wir auch auf die Variable <code>site</code> verzichten können.</p>
</section>
<section id="sec-mult-comp-lmer-reg" class="level2" data-number="49.6">
<h2 data-number="49.6" class="anchored" data-anchor-id="sec-mult-comp-lmer-reg"><span class="header-section-number">49.6</span> Gruppenvergleich</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/caution.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>text</p>
<p><code>{simstudy}</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>gen_school <span class="ot">&lt;-</span> <span class="fu">defData</span>(<span class="at">varname =</span> <span class="st">"n_classes"</span>, <span class="at">dist =</span> <span class="st">"nonrandom"</span>, <span class="at">formula =</span> <span class="dv">3</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="st">"id_school"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>gen_school <span class="ot">&lt;-</span> <span class="fu">defData</span>(gen_school, <span class="at">varname =</span> <span class="st">"s0"</span>, <span class="at">dist =</span> <span class="st">"normal"</span>, <span class="at">formula =</span> <span class="dv">0</span>, <span class="at">variance =</span> <span class="dv">3</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">282721</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>dt_school <span class="ot">&lt;-</span> <span class="fu">genData</span>(<span class="dv">9</span>, gen_school)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>dt_school <span class="ot">&lt;-</span> <span class="fu">trtAssign</span>(dt_school, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">grpName =</span> <span class="st">"trt"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>dt_school</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_school n_classes         s0 trt
1:         1         3  0.9732297   2
2:         2         3  3.5741932   1
3:         3         3  0.1121028   1
4:         4         3  0.5147236   3
5:         5         3  0.4594058   3
6:         6         3 -0.1287554   2
7:         7         3  2.4400170   2
8:         8         3 -1.2496060   1
9:         9         3  0.5028116   3</code></pre>
</div>
</div>
<p>text</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>gen_class <span class="ot">&lt;-</span> <span class="fu">defDataAdd</span>(<span class="at">varname =</span> <span class="st">"n_students"</span>, <span class="at">dist =</span> <span class="st">"nonrandom"</span>, <span class="at">formula =</span> <span class="dv">5</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>gen_class <span class="ot">&lt;-</span> <span class="fu">defDataAdd</span>(gen_class, <span class="at">varname =</span> <span class="st">"c0"</span>, <span class="at">dist =</span> <span class="st">"normal"</span>, <span class="at">formula =</span> <span class="dv">0</span>, <span class="at">variance =</span> <span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>dt_class <span class="ot">&lt;-</span> <span class="fu">genCluster</span>(dt_school, <span class="st">"id_school"</span>, <span class="at">numIndsVar =</span> <span class="st">"n_classes"</span>, <span class="at">level1ID =</span> <span class="st">"id_class"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dt_class <span class="ot">&lt;-</span> <span class="fu">addColumns</span>(gen_class, dt_class)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>dt_class <span class="sc">%&lt;&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_column</span>(<span class="at">trt_new =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">9</span>))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dt_class)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_school n_classes        s0 trt id_class n_students         c0 trt_new
1:         1         3 0.9732297   2        1          5 -2.0229423       1
2:         1         3 0.9732297   2        2          5 -0.5205577       2
3:         1         3 0.9732297   2        3          5 -0.6273398       3
4:         2         3 3.5741932   1        4          5  0.3799622       1
5:         2         3 3.5741932   1        5          5 -0.1720926       2
6:         2         3 3.5741932   1        6          5  4.4164429       3</code></pre>
</div>
</div>
<p>text</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>gen_student <span class="ot">&lt;-</span> <span class="fu">defDataAdd</span>(<span class="at">varname =</span> <span class="st">"test"</span>, <span class="at">dist =</span> <span class="st">"normal"</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">formula =</span> <span class="st">"50 + s0 + c0 + 8 * trt"</span>, <span class="at">variance =</span> <span class="dv">2</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>dt_student <span class="ot">&lt;-</span> <span class="fu">genCluster</span>(dt_class, <span class="at">cLevelVar =</span> <span class="st">"id_class"</span>, <span class="at">numIndsVar =</span> <span class="st">"n_students"</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">level1ID =</span> <span class="st">"id_child"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>dt_student <span class="ot">&lt;-</span> <span class="fu">addColumns</span>(gen_student, dt_student) <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id_class =</span> <span class="fu">as_factor</span>(id_class),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">id_school =</span> <span class="fu">as_factor</span>(id_school),</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> <span class="fu">as_factor</span>(trt),</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt_new =</span> <span class="fu">as_factor</span>(trt_new))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Generierung von Daten: 1 fester Effekt und 2 zufällige Effekte
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Aus Gründen der Einfachheit haben wir immer ein balanciertes Design vorliegen. Wir haben also immer in allen Faktorkombinationen die gleiche Anzahl an Beobachtungen <code>n_reps</code> vorliegen. In der Anwendung mag es Unterschiede geben, so hat eine Sau sicherlich nicht immer exakt zwölf Ferkel, aber in unseren Beispielen macht es keinen Unterschied. Balanciert oder unbalanciert ist bei gemischten Modellen eher nachrangig wichtig.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>n_school <span class="ot">&lt;-</span> <span class="dv">9</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>n_class_per_school <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>n_trt <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>n_reps <span class="ot">&lt;-</span> <span class="dv">20</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p><a href="#tbl-mixed-simple-2fac">Tabelle&nbsp;<span>49.2</span></a></p>
<div id="tbl-mixed-simple-2fac" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;49.2— Kurzform eines dreifaktoriellen Datensatzes mit zwei zufälligen Effekten für <code>school</code> und <code>class</code> sowie einem Bahandlungsfaktor <code>trt</code>. Die zufälligen Effekte sind normalverteilt mit <span class="math inline">\(\mathcal{N}(0, s^2)\)</span>. Pro Behandlung haben wir dann nur zwei Wiederholungen. Dennoch erreichen wir eine Fallzahl von sechzehn Beobachtungen.</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 6%">
<col style="width: 25%">
<col style="width: 4%">
<col style="width: 23%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">school</th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{eff_{school}}\)</span></th>
<th style="text-align: center;">class</th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{eff_{class}}\)</span></th>
<th style="text-align: center;">trt</th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{eff_{trt}}\)</span></th>
<th style="text-align: center;">reps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(-0.14\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(-0.14\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(-0.14\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(-0.14\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.21\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.21\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.21\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(0.23\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.21\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(-0.83\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(-0.83\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(-0.83\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(-0.83\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(0.59\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(0.59\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(0.59\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.71\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(0.59\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(5\)</span></td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>n_s <span class="ot">&lt;-</span> <span class="dv">9</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>s_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">s_id =</span> <span class="dv">1</span><span class="sc">:</span>n_s,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">s_0 =</span> <span class="fu">rnorm</span>(n_s, <span class="dv">0</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_column</span>(<span class="at">trt =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">3</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(<span class="at">c_per_s =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>foo <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">s_id =</span> <span class="dv">1</span><span class="sc">:</span>n_s,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">s_0 =</span> <span class="fu">rnorm</span>(n_s, <span class="dv">0</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_column</span>(<span class="at">trt =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">3</span>),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">t_eff =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">10</span>, <span class="dv">30</span>), <span class="dv">3</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(<span class="at">c_per_s =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">c_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">27</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">c_0 =</span> <span class="fu">rnorm</span>(<span class="dv">27</span>, <span class="dv">0</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(<span class="at">reps =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">test =</span> <span class="dv">50</span> <span class="sc">+</span> s_0 <span class="sc">+</span> c_0 <span class="sc">+</span> t_eff <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">n</span>(), <span class="dv">0</span>, <span class="dv">2</span>),</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">s_id =</span> <span class="fu">as_factor</span>(s_id),</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">c_id =</span> <span class="fu">as_factor</span>(c_id),</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> <span class="fu">as_factor</span>(trt))</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>foo <span class="sc">%&gt;%</span> </span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trt, test, <span class="at">fill =</span> s_id, <span class="at">group =</span> c_id)) <span class="sc">+</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() </span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>lmer_fit <span class="ot">&lt;-</span> <span class="fu">lmer</span>(test <span class="sc">~</span> trt <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>s_id) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>c_id), <span class="at">data =</span> foo) </span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>lmer_fit <span class="sc">%&gt;%</span> </span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span> trt) <span class="sc">%&gt;%</span> </span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">expand_grid</span>(<span class="fu">tibble</span>(<span class="at">s_id =</span> <span class="dv">1</span><span class="sc">:</span>n_s,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">s_0 =</span> <span class="fu">rnorm</span>(n_s, <span class="dv">0</span>, <span class="dv">2</span>)),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">tibble</span>(<span class="at">trt =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trt_eff =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="dv">20</span>))) </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">&lt;-</span> s_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">c_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">27</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">c_0 =</span> <span class="fu">rnorm</span>(<span class="dv">27</span>, <span class="dv">0</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(<span class="at">reps =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">test =</span> <span class="dv">50</span> <span class="sc">+</span> s_0 <span class="sc">+</span> c_0 <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> trt <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">n</span>(), <span class="dv">0</span>, <span class="dv">2</span>),</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">s_id =</span> <span class="fu">as_factor</span>(s_id),</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">c_id =</span> <span class="fu">as_factor</span>(c_id),</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> <span class="fu">as_factor</span>(trt))</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>final_data <span class="sc">%&gt;%</span> </span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trt, test, <span class="at">fill =</span> s_id, <span class="at">group =</span> c_id)) <span class="sc">+</span></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>n_s <span class="ot">&lt;-</span> <span class="dv">9</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>s_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">s_id =</span> <span class="dv">1</span><span class="sc">:</span>n_s,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">s_0 =</span> <span class="fu">rnorm</span>(n_s, <span class="dv">0</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_column</span>(<span class="at">trt =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">3</span>)) </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>c_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">c_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">c_0 =</span> <span class="fu">rnorm</span>(<span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">5</span>))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">&lt;-</span> s_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(c_tbl,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">reps =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">test =</span> <span class="dv">50</span> <span class="sc">+</span> s_0 <span class="sc">+</span> c_0 <span class="sc">+</span> <span class="dv">8</span> <span class="sc">*</span> trt <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">n</span>(), <span class="dv">0</span>, <span class="dv">2</span>),</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">s_id =</span> <span class="fu">as_factor</span>(s_id),</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">c_id =</span> <span class="fu">as_factor</span>(c_id),</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> <span class="fu">as_factor</span>(trt))</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>final_data <span class="sc">%&gt;%</span> </span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trt, test, <span class="at">fill =</span> c_id)) <span class="sc">+</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>s_id)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>dt_student <span class="sc">%&gt;%</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(id_class, test, <span class="at">fill =</span> id_school, <span class="at">linetype =</span> trt, <span class="at">color =</span> trt)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stat-modeling-mixed_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dt_student <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trt, test, <span class="at">fill =</span> id_school, <span class="at">group =</span> id_class)) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stat-modeling-mixed_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page"><code>lmer</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false"><code>lm</code></a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lmer_fit <span class="ot">&lt;-</span> <span class="fu">lmer</span>(test <span class="sc">~</span> trt <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id_school) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id_class), <span class="at">data =</span> dt_student) </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>lmer_fit2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(test <span class="sc">~</span> trt <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>id_class<span class="sc">/</span>id_school), <span class="at">data =</span> dt_student) </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(lmer_fit, lmer_fit2, <span class="at">rank =</span> <span class="cn">TRUE</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Some of the nested models seem to be identical and probably only vary in
  their random effects.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name      |   Model | R2 (cond.) | R2 (marg.) |   ICC |  RMSE | Sigma | AIC weights | AICc weights | BIC weights | Performance-Score
------------------------------------------------------------------------------------------------------------------------------------
lmer_fit  | lmerMod |      0.958 |      0.809 | 0.780 | 1.303 | 1.438 |       0.967 |        0.967 |       0.967 |            62.50%
lmer_fit2 | lmerMod |      0.957 |      0.831 | 0.745 | 1.295 | 1.438 |       0.033 |        0.033 |       0.033 |            37.50%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>lmer_fit <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_performance</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC     |    AICc |     BIC | R2 (cond.) | R2 (marg.) |   ICC |  RMSE | Sigma
-----------------------------------------------------------------------------
550.013 | 550.669 | 567.444 |      0.958 |      0.809 | 0.780 | 1.303 | 1.438</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>lmer_fit <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span> trt) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    estimate   SE df t.ratio p.value
 trt1 - trt2    -7.20 1.99  6  -3.617  0.0259
 trt1 - trt3   -15.38 1.99  6  -7.727  0.0006
 trt2 - trt3    -8.18 1.99  6  -4.110  0.0148

Degrees-of-freedom method: kenward-roger 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>lmer_fit <span class="sc">%&gt;%</span> anova</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table
    npar Sum Sq Mean Sq F value
trt    2 123.57  61.784  29.896</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(test <span class="sc">~</span> trt <span class="sc">+</span> id_school <span class="sc">+</span> id_class, <span class="at">data =</span> dt_student) </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_performance</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC     |    AICc |     BIC |    R2 | R2 (adj.) |  RMSE | Sigma
---------------------------------------------------------------
506.990 | 522.311 | 588.338 | 0.965 |     0.956 | 1.286 | 1.438</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span> trt) <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: A nesting structure was detected in the fitted model:
    id_school %in% trt, id_class %in% (trt*id_school)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    estimate    SE  df t.ratio p.value
 trt1 - trt2    -7.20 0.303 108 -23.754  &lt;.0001
 trt1 - trt3   -15.38 0.303 108 -50.746  &lt;.0001
 trt2 - trt3    -8.18 0.303 108 -26.992  &lt;.0001

Results are averaged over the levels of: id_class, id_school 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="sc">%&gt;%</span> anova</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: test
           Df Sum Sq Mean Sq   F value    Pr(&gt;F)    
trt         2 5329.2 2664.58 1289.3153 &lt; 2.2e-16 ***
id_school   6  534.8   89.13   43.1271 &lt; 2.2e-16 ***
id_class   18  240.4   13.35    6.4612 1.474e-10 ***
Residuals 108  223.2    2.07                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Anwendungsbeispiel: Dreifaktorieller Gruppenvergleich für das Gewicht
</div>
</div>
<div class="callout-body-container callout-body">
<p>Im folgenden Beispiel schauen wir uns nochmal ein praktische Auswertung von einem agrarwissenschaftlichen Beispiel mit Brokkoli an. Wir haben uns in diesem Experiment verschiedene Dosen <code>fert_amount</code> von einem Dünger aufgebracht sowie verschiedene Zeitpunkte der Düngung <code>fert_time</code> berücksichtigt. Auch hier haben wir einige Besonderheiten in den Daten, da nicht jede Faktorkombination vorliegt. Wir ignorieren aber diese Probleme und rechnen einfach stumpf unseren Gruppenvergleich.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>broc_tbl <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/broccoli_weight.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fert_time =</span> <span class="fu">factor</span>(fert_time, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"none"</span>, <span class="st">"early"</span>, <span class="st">"late"</span>)),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">fert_amount =</span> <span class="fu">as_factor</span>(fert_amount),</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">block =</span> <span class="fu">as_factor</span>(block)) <span class="sc">%&gt;%</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>stem_hollowness) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dann können wir auch schon die Gaussian Regression mit <code>lm()</code> rechnen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> fert_time <span class="sc">+</span> fert_amount <span class="sc">+</span> fert_time<span class="sc">:</span>fert_amount <span class="sc">+</span> block, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> broc_tbl) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Jetzt rechnen wir in den beiden folgenden Tabs einmal die ANOVA und dann auch den multiplen Gruppenvergleich mit <code>{emmeans}</code>. Da wir hier normalveteilte Daten haben, können wir dann einfach die Standardverfahren nehmen. Eventuell müssten wir bei dem Gruppenvergleich mit <code>emmeans()</code> nochmal für Varianzheterogenität adjustieren, aber da erfährst du dann mehr in dem Kapitel zu den <a href="stat-tests-posthoc.html">Multiple Vergleichen oder Post-hoc Tests</a>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">ANOVA mit <code>anova()</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Gruppenvergleich mit <code>emmeans()</code></a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>Wir rechnen hier einmal die ANOVA und nutzen den <span class="math inline">\(\mathcal{X}^2\)</span>-Test für die Ermittelung der p-Werte. Wir müssen hier einen Test auswählen, da per Standardeinstellung kein Test gerechnet wird. Wir machen dann die Ausgabe nochmal schöner und fertig sind wir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="sc">%&gt;%</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter             | Sum_Squares |   df | Mean_Square |     F |      p
-------------------------------------------------------------------------
fert_time             |    2.44e+06 |    2 |    1.22e+06 | 44.12 | &lt; .001
fert_amount           |    2.11e+06 |    2 |    1.05e+06 | 38.06 | &lt; .001
block                 |    7.21e+06 |    3 |    2.40e+06 | 86.73 | &lt; .001
fert_time:fert_amount |    26973.84 |    2 |    13486.92 |  0.49 | 0.615 
Residuals             |    4.28e+07 | 1544 |    27692.44 |       |       

Anova Table (Type 1 tests)</code></pre>
</div>
</div>
<p>Wir sehen, dass der Effekt der Düngerzeit und die Menge des Düngers signifikant ist, jedoch wir keinen signifikanten Einfluss durch die Interaktion haben. Wir haben aber also keine Interaktion vorliegen. Leider ist auch der Block signifikant, so dass wir eigentlich nicht über den Block mitteln sollten. Wir rechnen trotzdem die Analyse gemittelt über die Blöcke. Wenn du hier mehr erfahren möchtest, dann schaue dir das Beispiel hier nochmal im Kapitel zu dem <a href="#sec-mixed">linearen gemischten Modellen</a> an.</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Im Folgenden rechnen wir einmal über alle Faktorkombinationen von <code>fert_time</code> und <code>fert_amount</code> einen Gruppenvergleich. Dafür nutzen wir die Option <code>fert_time * fert_amount</code>. Wenn du die Analyse <em>getrennt</em> für die Menge und den Zeitpunkt durchführen willst, dann nutze die Option <code>fert_time | fert_amount</code>. Dann adjustieren wir noch nach Bonferroni und sind fertig.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>emm_obj <span class="ot">&lt;-</span> lm_fit <span class="sc">%&gt;%</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span> fert_time <span class="sc">*</span> fert_amount) <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cld</span>(<span class="at">Letters =</span> letters, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>emm_obj</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> fert_time fert_amount emmean    SE   df lower.CL upper.CL .group
 none      0              169 33.97 1544     71.1      266  a    
 late      150            400 11.25 1544    367.8      432   b   
 early     150            432 11.05 1544    399.9      463   bc  
 late      225            467 11.20 1544    434.9      499    cd 
 early     225            497  7.97 1544    473.8      520     d 
 late      300            506 11.40 1544    473.1      539     d 
 early     300            517 11.38 1544    484.8      550     d 
 early     0           nonEst    NA   NA       NA       NA       
 late      0           nonEst    NA   NA       NA       NA       
 none      150         nonEst    NA   NA       NA       NA       
 none      225         nonEst    NA   NA       NA       NA       
 none      300         nonEst    NA   NA       NA       NA       

Results are averaged over the levels of: block 
Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 12 estimates 
P value adjustment: bonferroni method for 66 tests 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Das <code>emm_obj</code> Objekt werden wir dann gleich einmal in <code>{ggplot}</code> visualisieren. Die <code>emmean</code> stellt den mittleren Gewicht des Brokkoli je Faktorkombination dar gemittelt über alle Blöcke. Das Mitteln über die Blöcke ist eher fragwürdig, da wir ja einen Effekt der Blöcke in der ANOVA gefunden hatten. Hier schauen wir dann nochmal auf das Beispiel im Kapitel zu den <a href="#sec-mixed">linearen gemischten Modellen</a>. Dann können wir zum Abschluss auch das <em>compact letter display</em> anhand der Abbildung interpretieren.</p>
</div>
</div>
</div>
<p>In der <a href="#fig-log-mod-gaussian-broc">Abbildung&nbsp;<span>49.12</span></a> siehst du das Ergebnis der Auswertung in einem Säulendiagramm. Wir sehen einen klaren Effekt der Düngezeitpunkte sowie der Düngermenge auf das Gewicht von Brokkoli. Wenn wir ein mittleres Gewicht von <span class="math inline">\(500g\)</span> für den Handel erreichen wollen, dann erhalten wir das Zielgewicht nur bei einer Düngemenge von <span class="math inline">\(300mg/l\)</span>. Hier stellt sich dann die Frage, ob wir bei <span class="math inline">\(225mg/l\)</span> und einem frühen Zeitpunkt der Düngung nicht auch genug Brokkoli erhalten. Das Ziel ist es ja eigentlich in einen Zielbereich zu kommen. Die Köpfe sollen ja nicht zu schwer und auch nicht zu leicht sein. Aber diese Frage und andere Fragen der biologischen Anwendung lassen wir dann hier einmal offen, denn das Beispiel soll ja nur ein Beispiel sein.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>emm_obj <span class="sc">%&gt;%</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> fert_time, <span class="at">y =</span> emmean, <span class="at">fill =</span> fert_amount)) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mittleres Gewicht [g] des Brokkoli"</span>, <span class="at">x =</span> <span class="st">"Düngezeitpunkt"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Düngemenge [mg/l]"</span>) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">500</span>, <span class="at">by =</span> <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">500</span>, <span class="at">size =</span> <span class="fl">0.75</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, </span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>, <span class="at">preserve =</span> <span class="st">"single"</span>)) <span class="sc">+</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> .group, <span class="at">y =</span> emmean <span class="sc">+</span> SE <span class="sc">+</span> <span class="fl">0.01</span>),  </span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> emmean<span class="sc">-</span>SE, <span class="at">ymax =</span> emmean<span class="sc">+</span>SE),</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>,  </span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>, <span class="at">preserve =</span> <span class="st">"single"</span>)) <span class="sc">+</span></span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-log-mod-gaussian-broc" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-log-mod-gaussian-broc-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.12— Säulendigramm der mittleren Brokkoligewichte aus einer Gaussian Regression. Das <code>lm()</code>-Modell berechnet das mittler Gewicht des Brokkoli in jeder Faktorkombination. Das <em>compact letter display</em> wird dann in <code>{emmeans}</code> generiert. Wir nutzen hier den Standardfehler, da die Standardabweichung mit der großen Fallzahl rießig wäre. Wir haben noch ein Mindestgewicht von 500g ergänzt.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Anwendungsbeispiel: Dreifaktorieller Gruppenvergleich für Thripsenbefall
</div>
</div>
<div class="callout-body-container callout-body">
<p>Im folgenden Beispiel schauen wir uns nochmal ein praktische Auswertung von einem agrarwissenschaftlichen Beispiel mit jungen Apfelbäumen an. Wir haben uns in diesem Experiment verschiedene Dosen <code>trt</code> von einem Insektizid aufgebracht sowie verschiedene Startanzahlen von Raubmilben als biologische Alternative untersucht. Dann haben wir noch fünf Zeitpunkte bestimmt, an denen wir die Anzahl an Thripsen auf den Blättern gezählt haben. Wir haben nicht die Blätter per se gezählt sondern Fallen waagerecht aufgestellt. Dann haben wir geschaut, wie viele Thripsen wir über <code>above</code> und unter <code>below</code> von den Fallen gefunden haben. In unserem Fall beschränken wir uns auf die obere Anzahl an Thripsen und schauen uns auch nur die Behandlung mit dem Insektizid an.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>insects_tbl <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/insects_count.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">timepoint =</span> <span class="fu">factor</span>(timepoint, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1 Tag"</span>, <span class="st">"4 Tag"</span>, <span class="st">"7 Tag"</span>, <span class="st">"11 Tag"</span>, <span class="st">"14 Tag"</span>)),</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">rep =</span> <span class="fu">as_factor</span>(rep),</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> <span class="fu">as_factor</span>(trt)) <span class="sc">%&gt;%</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(timepoint, trt, rep, <span class="at">thripse =</span> thripse_above, <span class="at">mite =</span> mite_above) <span class="sc">%&gt;%</span> </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trt <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"10ml"</span>, <span class="st">"30ml"</span>, <span class="st">"60ml"</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dann können wir auch schon die Poisson Regression mit <code>glm()</code> rechnen. Auch hier wieder darauf achten, dass wir dann als Option <code>family = poisson</code> oder <code>family = quasipoisson</code> wählen. Es hängt jetzt davon ab, ob du in deinen Daten Overdispersion vorliegen hast oder nicht. In den beiden folgenden Tabs, rechne ich dann mal beide Modelle.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true"><code>family = poisson</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false"><code>family = quasipoisson</code></a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>Als Erstes rechnen wir eine normale Poisson Regression und schauen einmal, ob wir Overdispersion vorliegen haben. Wenn wir Overdispersion vorliegen haben, dann können wir keine Poisson Regression rechnen, sondern müssen auf eine Quasipoisson Regression ausweichen. Das ist aber sehr einfach, wie du im anderen Tab sehen wirst.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>insects_poisson_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(thripse <span class="sc">~</span> trt <span class="sc">+</span> timepoint <span class="sc">+</span> trt<span class="sc">:</span>timepoint, </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> insects_tbl, </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">family =</span> poisson) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bevor wir uns das Modell mit <code>summary()</code> überhaupt anschauen, wollen wir erstmal überprüfen, ob wir überhaupt Overdispersion vorliegen haben. Wenn ja, dann können wir uns die <code>summary()</code> hier gleich sparen. Also einmal geguckt, was die Overdispersion macht.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>insects_poisson_fit <span class="sc">%&gt;%</span> <span class="fu">check_overdispersion</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Overdispersion test

       dispersion ratio =   23.498
  Pearson's Chi-Squared = 3172.179
                p-value =  &lt; 0.001</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Overdispersion detected.</code></pre>
</div>
</div>
<p>Wir haben sehr starke Overdispersion vorliegen und gehen daher rüber in den anderen Tab und rechnen eine Quasipoisson Regression. Nur wenn du keine Overdispersion vorliegen hast, dann kannst du eine eine Poisson Regression rechnen.</p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>Entweder hast du in deinen Daten eine Overdispersion gefunden oder aber du meinst, es wäre besser gleich eine Quasipoisson zu rechnen. Beides ist vollkommen in Ordnung. Ich rechne meistens immer eine Quasipoisson und schaue dann nur, ob die Overdispersion sehr groß war. In den seltensten Fällen hast du eine Overdispersion vorliegen, die eher klein ist. Daher mache ich erst die Lösung und schaue, ob das Problem dann da war.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>insects_quasipoisson_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(thripse <span class="sc">~</span> trt <span class="sc">+</span> timepoint <span class="sc">+</span> trt<span class="sc">:</span>timepoint, </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">data =</span> insects_tbl, </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">family =</span> quasipoisson) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Du kannst in der <code>summary()</code> Ausgabe direkt sehen, ob du Overdispersion vorliegen hast. Du musst nur relativ weit unten schauen, was zu dem <code>Dispersion parameter</code> in den Klammern geschrieben ist. Wenn da eine Zahl größer als 1 drin steht, dann hast du Overdispersion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>insects_quasipoisson_fit <span class="sc">%&gt;%</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = thripse ~ trt + timepoint + trt:timepoint, family = quasipoisson, 
    data = insects_tbl)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-9.7421  -4.1556  -0.5495   1.9488  14.0290  

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              3.861686   0.211964  18.219   &lt;2e-16 ***
trt30ml                 -0.565849   0.376336  -1.504   0.1350    
trt60ml                 -1.058326   0.432830  -2.445   0.0158 *  
timepoint4 Tag          -0.448440   0.339528  -1.321   0.1888    
timepoint7 Tag          -0.001914   0.299907  -0.006   0.9949    
timepoint11 Tag         -0.121854   0.309323  -0.394   0.6942    
timepoint14 Tag         -0.177363   0.313970  -0.565   0.5731    
trt30ml:timepoint4 Tag   0.476840   0.553141   0.862   0.3902    
trt60ml:timepoint4 Tag  -0.579968   0.809916  -0.716   0.4752    
trt30ml:timepoint7 Tag   0.154299   0.519303   0.297   0.7668    
trt60ml:timepoint7 Tag   0.252555   0.585830   0.431   0.6671    
trt30ml:timepoint11 Tag  0.121854   0.537661   0.227   0.8210    
trt60ml:timepoint11 Tag  0.091083   0.620448   0.147   0.8835    
trt30ml:timepoint14 Tag -0.162407   0.575416  -0.282   0.7782    
trt60ml:timepoint14 Tag -0.201195   0.670025  -0.300   0.7644    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 23.49807)

    Null deviance: 4263.4  on 149  degrees of freedom
Residual deviance: 3345.0  on 135  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Wir haben hier auf jeden Fall Overdispersion vorliegen. Daher nutze ich dann auch das Modell hier mit der Annahme an eine Quasipoissonverteilung. Dann stimmt es auch mit unseren Varianzen und wir produzieren nicht zufällig zu viele signifikante Ergebnisse, die es dann gar nicht gibt.</p>
</div>
</div>
</div>
<p>Ich habe mich gerade in den obigen Tabs für eine Quasipoisson Regression entschieden, da wir Overdispersion vorliegen haben. Damit mache ich dann mit dem <code>insects_quasipoisson_fit</code> Modell weiter. In den beiden folgenden Tabs findest du dann einmal das Ergebnis für die ANOVA und einmal für den Gruppenvergleich mit dem R Paket <code>{emmeans}</code>. Bitte beachte, dass die ANOVA für ein <code>glm()</code>-Objekt nicht ganz gleich wie für ein <code>lm()</code>-Objekt ist. Du kannst aber die ANOVA erstmal ganz normal interpretieren, nur haben wir hier nicht die Möglichkeit ein <span class="math inline">\(\eta^2\)</span> zu bestimmen. Dann nutzen wir <code>{emmeans}</code> für den Gruppenvergleich. Nochmal, weil wir Overdispersion festgestellt haben, nutzen wir das Objekt <code>insects_quasipoisson_fit</code> mit der Berücksichtigung der Overdispersion.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">ANOVA mit <code>anova()</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Gruppenvergleich mit <code>emmeans()</code></a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>Wir rechnen hier einmal die ANOVA und nutzen den <span class="math inline">\(\mathcal{X}^2\)</span>-Test für die Ermittelung der p-Werte. Wir müssen hier einen Test auswählen, da per Standardeinstellung kein Test gerechnet wird. Wir machen dann die Ausageb nochmal schöner und fertig sind wir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>insects_quasipoisson_fit <span class="sc">%&gt;%</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova</span>(<span class="at">test =</span> <span class="st">"Chisq"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>(<span class="at">drop =</span> <span class="st">"NULL"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter     | df | Deviance | df (error) | Deviance (error) |      p
----------------------------------------------------------------------
trt           |  2 |   730.20 |        147 |          3533.22 | &lt; .001
timepoint     |  4 |   112.27 |        143 |          3420.95 | 0.311 
trt:timepoint |  8 |    75.93 |        135 |          3345.03 | 0.919 

Anova Table (Type 1 tests)</code></pre>
</div>
</div>
<p>Wir sehen, dass der Effekt für die Behandlung signifikant ist, jedoch die Zeit und die Interaktion keinen signifikanten Einfluss haben. Wir haben aber also keine Interaktion vorliegen. Daher können wir dann die Analyse gemeinsam über alle Zeitpunkte rechnen.</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<p>Im Folgenden rechnen wir einmal über alle Faktorkombinationen von <code>trt</code> und <code>timepoint</code> einen Gruppenvergleich. Dafür nutzen wir die Opition <code>trt * timepoint</code>. Wenn du die Analyse <em>getrennt</em> für die Zeitpunkte durchführen willst, dann nutze die Option <code>trt | timepoint</code>. Wir wollen die Wahrscheinlichkeiten für das Auftreten einer Beschädigung von wiedergegeben bekommen, deshalb die Option <code>regrid = "response</code>. Dann adjustieren wir noch nach Bonferroni und sind fertig.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>emm_obj <span class="ot">&lt;-</span> insects_quasipoisson_fit <span class="sc">%&gt;%</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span> trt <span class="sc">*</span> timepoint, <span class="at">regrid =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cld</span>(<span class="at">Letters =</span> letters, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>emm_obj</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> trt  timepoint rate    SE  df asymp.LCL asymp.UCL .group
 60ml 4 Tag      5.9  3.72 Inf    -5.029      16.8  a    
 60ml 14 Tag    11.3  5.15 Inf    -3.825      26.4  ab   
 60ml 11 Tag    16.0  6.13 Inf    -1.998      34.0  ab   
 60ml 1 Tag     16.5  6.23 Inf    -1.777      34.8  ab   
 30ml 14 Tag    19.2  7.08 Inf    -1.572      40.0  ab   
 60ml 7 Tag     21.2  7.06 Inf     0.483      41.9  ab   
 30ml 1 Tag     27.0  8.40 Inf     2.356      51.6  ab   
 30ml 11 Tag    27.0  8.40 Inf     2.356      51.6  ab   
 30ml 4 Tag     27.8  8.52 Inf     2.782      52.8  ab   
 10ml 4 Tag     30.4  8.05 Inf     6.725      54.0  ab   
 30ml 7 Tag     31.4  9.06 Inf     4.849      58.0  ab   
 10ml 14 Tag    39.8  9.22 Inf    12.748      66.9  ab   
 10ml 11 Tag    42.1  9.48 Inf    14.258      69.9   b   
 10ml 7 Tag     47.5 10.07 Inf    17.902      77.0   b   
 10ml 1 Tag     47.5 10.08 Inf    17.965      77.1   b   

Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 15 estimates 
P value adjustment: bonferroni method for 105 tests 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Das <code>emm_obj</code> Objekt werden wir dann gleich einmal in <code>{ggplot}</code> visualisieren. Die <code>rate</code> stellt die mittlere Anzahl an Thripsen je Faktorkombination dar. Dann können wir auch das <em>compact letter display</em> anhand der Abbildung interpretieren.</p>
</div>
</div>
</div>
<p>In der <a href="#fig-log-mod-pois-insect">Abbildung&nbsp;<span>49.13</span></a> siehst du das Ergebnis der Auswertung in einem Säulendiagramm. Hier unbedingt <code>SE</code> als den Standardfehler für die Fehlerbalken nutzen, da wir sonst Fehlerbalken größer und kleiner als <span class="math inline">\(0\)</span> erhalten, wenn wir die Standardabweichung nutzen würden. Das ist in unserem Fall nicht so das Problem, aber wenn du eher kleine Anzahlen zählst, kann das schnell zu Werten kleiner Null führen. Wir sehen einen klaren Effekt der Behandlung <code>60ml</code>. Die Zeit hat keinen Effekt, was ja schon aus der ANOVA klar war, die Säulen sehen für jeden Zeitpunkt vollkommen gleich aus. Gut etwas Unterschied ist ja immer.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>emm_obj <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> timepoint, <span class="at">y =</span> rate, <span class="at">fill =</span> trt)) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mittlere Anzahl an Thripsen"</span>, <span class="at">x =</span> <span class="st">"Messzeitpunkte der Zählungen"</span>,</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Dosis"</span>) <span class="sc">+</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, </span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>, <span class="at">preserve =</span> <span class="st">"single"</span>)) <span class="sc">+</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> .group, <span class="at">y =</span> rate <span class="sc">+</span> SE <span class="sc">+</span> <span class="fl">0.01</span>),  </span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> rate<span class="sc">-</span>SE, <span class="at">ymax =</span> rate<span class="sc">+</span>SE),</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>,  </span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>, <span class="at">preserve =</span> <span class="st">"single"</span>)) <span class="sc">+</span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-log-mod-pois-insect" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="stat-modeling-mixed_files/figure-html/fig-log-mod-pois-insect-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.13— Säulendigramm der mitleren Zahl der Thripsen aus einer Poisson Regression. Das <code>glm()</code>-Modell berechnet die mittlere Anzahl in jeder Faktorkombination. Das <em>compact letter display</em> wird dann in <code>{emmeans}</code> generiert.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="referenzen" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-zuur2009mixed" class="csl-entry" role="listitem">
Zuur AF, Ieno EN, Walker NJ, Saveliev AA, Smith GM, others. 2009. Mixed effects models and extensions in ecology with R. Springer.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./stat-modeling-prob-model.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Linear Probability Model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-gee.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>