<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 23&nbsp; Die ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-tests-ancova.html" rel="next">
<link href="./stat-tests-ttest.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Mit <code>purrr</code> und <code>furrr</code></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Friedman Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Logistische Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Metaanalysen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Permutationstest</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Fortgeschrittene Versuchsplanung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">Klassifikation oder maschinelles Lernen</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Data splitting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Data preprocessing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Decision trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Support vector machines</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Neural networks</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Anhang</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-bewertungsbogen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Bewertungsbogen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Modulbeschreibung</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link active" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"><span class="toc-section-number">23.1</span>  Genutzte R Pakete für das Kapitel</a></li>
  <li>
<a href="#sec-fac1" id="toc-sec-fac1" class="nav-link" data-scroll-target="#sec-fac1"><span class="toc-section-number">23.2</span>  Einfaktorielle ANOVA</a>
  <ul class="collapse">
<li><a href="#daten-f%C3%BCr-die-einfaktorielle-anova" id="toc-daten-für-die-einfaktorielle-anova" class="nav-link" data-scroll-target="#daten-f%C3%BCr-die-einfaktorielle-anova"><span class="toc-section-number">23.2.1</span>  Daten für die einfaktorielle ANOVA</a></li>
  <li><a href="#hypothesen-f%C3%BCr-die-einfaktorielle-anova" id="toc-hypothesen-für-die-einfaktorielle-anova" class="nav-link" data-scroll-target="#hypothesen-f%C3%BCr-die-einfaktorielle-anova"><span class="toc-section-number">23.2.2</span>  Hypothesen für die einfaktorielle ANOVA</a></li>
  <li><a href="#einfaktoriellen-anova-theoretisch" id="toc-einfaktoriellen-anova-theoretisch" class="nav-link" data-scroll-target="#einfaktoriellen-anova-theoretisch"><span class="toc-section-number">23.2.3</span>  Einfaktoriellen ANOVA theoretisch</a></li>
  <li><a href="#einfaktoriellen-anova-in-r" id="toc-einfaktoriellen-anova-in-r" class="nav-link" data-scroll-target="#einfaktoriellen-anova-in-r"><span class="toc-section-number">23.2.4</span>  Einfaktoriellen ANOVA in R</a></li>
  </ul>
</li>
  <li>
<a href="#sec-fac2" id="toc-sec-fac2" class="nav-link" data-scroll-target="#sec-fac2"><span class="toc-section-number">23.3</span>  Zweifaktorielle ANOVA</a>
  <ul class="collapse">
<li><a href="#daten-f%C3%BCr-die-zweifaktorielle-anova" id="toc-daten-für-die-zweifaktorielle-anova" class="nav-link" data-scroll-target="#daten-f%C3%BCr-die-zweifaktorielle-anova"><span class="toc-section-number">23.3.1</span>  Daten für die zweifaktorielle ANOVA</a></li>
  <li><a href="#hypothesen-f%C3%BCr-die-zweifaktorielle-anova" id="toc-hypothesen-für-die-zweifaktorielle-anova" class="nav-link" data-scroll-target="#hypothesen-f%C3%BCr-die-zweifaktorielle-anova"><span class="toc-section-number">23.3.2</span>  Hypothesen für die zweifaktorielle ANOVA</a></li>
  <li><a href="#zweifaktoriellen-anova-in-r" id="toc-zweifaktoriellen-anova-in-r" class="nav-link" data-scroll-target="#zweifaktoriellen-anova-in-r"><span class="toc-section-number">23.3.3</span>  Zweifaktoriellen ANOVA in R</a></li>
  </ul>
</li>
  <li><a href="#und-weiter" id="toc-und-weiter" class="nav-link" data-scroll-target="#und-weiter"><span class="toc-section-number">23.4</span>  Und weiter?</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-anova" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="cell">

</div>
<p><em>Version vom Mai 16, 2023 um 11:08:28</em></p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Historisch betrachtet ist die ANOVA, <em>das</em> statistische Verfahren was gut per Hand ohne Computer berechnet werden kann. Daher war die ANOVA von den 20zigern bis in die frühen 90ziger des letzten Jahrhunderts <em>das</em> statistische Verfahren der Wahl.</span></div></div>
<p>Die ANOVA (eng. <em>analysis of variance</em>) ist wichtig. Was für ein schöner Satz um anzufangen. Wir brauchen die ANOVA aus mehreren Gründen. Die Hochzeiten der ANOVA sind eigentlich vorbei, wir haben in der Statistik für viele Fälle mittlerweile besser Werkzeuge, aber als Allrounder ist die ANOVA immer noch nutzbar. Wir werden immer wieder auf die ANOVA inhaltlich zurück kommen und in vielen Abschlussarbeiten wird die ANOVA immer noch als integraler Bestandteil genutzt.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die tolle Webseite <a href="https://schmidtpaul.github.io/DSFAIR/index.html">Data Science for Agriculture in R</a> liefert eine Vielzahl von experimentellen Designs sowie deren Auswertung. Neben anderen komplexeren Designs, auch diese einfacheren Designs, die jeder kennen sollte.</p>
<ul>
<li><p><a href="https://schmidtpaul.github.io/DSFAIR/CRD_Mead1993.html">Completely randomized design</a>, ist das Standarddesign für ein Feldexperiment.</p></li>
<li><p><a href="https://schmidtpaul.github.io/DSFAIR/RCBD_ClewerScarisbrick2001.html">Randomized complete block design (RCBD) with 1 factor</a>, beschreibt ein Experiment mit Blöcken und einem Behandlungsfaktor.</p></li>
<li><p><a href="https://schmidtpaul.github.io/DSFAIR/RCBD_2f_rice.html">Randomized complete block design (RCBD) with 2 factors</a>, beschreibt ein Experiment mit Blöcken und einem Behandlungsfaktor sowie einem weiteren Faktor.</p></li>
<li><p><a href="https://schmidtpaul.github.io/DSFAIR/latsquare_Bridges1989.html">Latin square design</a>, ist ein etwas spezielleres Design, wird aber auch viel genutzt.</p></li>
</ul>
<p>Wir gehen in einem späteren <a href="experimental-design-basic.html"><span>Kapitel&nbsp;51</span></a> nochmal auf die experimentellen Designs ein.</p>
</div></div><p>Wofür und wann brauchen wir die ANOVA, wenn wir Daten auswerten?</p>
<ol type="1">
<li>Wir brauchen die ANOVA um mehr als zwei Gruppen <em>gleichzeitig</em> miteinander zu vergleichen. Das heißt wir haben einen Faktor mit mehr als zwei Levels und wollen wissen, ob sich <em>mindestens</em> zwei Level bzw. Gruppen im Mittelwert unterscheiden.</li>
<li>Wir brauchen die ANOVA und deren Varianzzerlegung in der Züchtung. Hier spielt die ANOVA eine gewichtige Rolle bei der Abschätzung des genetischen Effekts. Wir werden aktuell (Stand Ende 2022) hierauf noch nicht tiefer eingehen.</li>
<li>Wir nutzen die ANOVA in vielen Anwendungsgebieten als eine Arte Vortest um zu schauen, ob sich ein Effekt in den Daten verbirgt. Eigentlich stammt dieses Ritual mit einer ANOVA als Vortest und dann ein Posthoc Test noch aus der Zeit, wo wir keine modernen Rechner zu Verfügung hatten. Damals machte diese Reihenfolge noch Sinn. Wir werdend darüber aber später nochmal lesen.</li>
<li>Experimentelle Designs sind darauf ausgelegt mit der ANOVA ausgewertet zu werden. Insbesondere in den Agrarwissenschaften hat die ANOVA daher eine historische Bedeutung. Insbesondere durch die enge Verzahnung vom Experiment auf dem Feld und der eigentlichen Auswertung mit der ANOVA.</li>
</ol>
<p>Wir können die <em>einfaktorielle</em> ANOVA in folgender Form schreiben mit einem <span class="math inline">\(f_1\)</span> für den Faktor. Damit haben wir einen bessere Übersicht. Wieder ist das <span class="math inline">\(y\)</span> und der Faktor <span class="math inline">\(f_1\)</span> jeweils eine separate Spalte in unserem Datensatz.</p>
<p><span class="math display">\[
y \sim f_1
\]</span></p>
<p>Somit erklärt sich die zweifaktorielle ANOVA schon fast von alleine. Wir erweitern einfach das Modell um einen zweiten Faktor <span class="math inline">\(f_2\)</span> und haben somit eine zweifaktorielle ANOVA vorliegen. Auch hier müssen wir beachten, dass das <span class="math inline">\(y\)</span> und die Faktoren <span class="math inline">\(f_1\)</span> und <span class="math inline">\(f_2\)</span> jeweils eine separate Spalte in unserem Datensatz sind.</p>
<p><span class="math display">\[
y \sim f_1 + f_2
\]</span></p>
<p>Wir sehen also, dass die ANOVA zum einen alt ist, aber auch heute noch viel verwendet wird. Daher werden wir in diesem <em>langem</em> Kapitel uns einmal mit der ANOVA ausgiebig beschäftigen. Fangen wir also an, dieses großartige Schweizertaschenmesser der Statistik besser zu verstehen.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Was macht die ANOVA?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die <em>einfaktorielle</em> ANOVA vergleicht die Parameter mehrerer Normalverteilungen miteinander. Oder etwas anders formuliert, vergleicht die ANOVA die Mittlelwerte von mehreren Gruppen bzw. Behandlungen miteinander.</p>
<p>Die <em>zweifaktorielle</em> ANOVA vergleicht die Parameter mehrerer Normalverteilungen von zwei Faktoren miteinander. Oder etwas anders formuliert, vergleicht die ANOVA die Mittelwerte von mehreren Gruppen bzw. Behandlungen miteinander. Dabei kann die <em>zweifaktorielle</em> ANOVA auch die Interaktion zwischen zwei Variablen abbilden.</p>
</div>
</div>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Ein Wort zur Klausur
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Wir rechnen keine ANOVA in der Klausur <em>per Hand</em> sondern interpretieren die Ausgabe der R Funktionen einer einfaktoriellen oder zweifaktoriellen ANOVA. Auch hier gilt, überprüfe was du in der Vorlesung gehört hast!</p>
<p>Bitte schau dir unbedingt die Aufgaben in den <a href="https://github.com/jkruppa/exam/blob/main/Gesammelte_Klausurfragen_Bio_Data_Science.pdf">gesammelten Klausurfragen auf GitHub</a> an um eine Idee zu haben, welche Fragen zu der ANOVA drankommen.</p>
<p>Wenn kein <span class="math inline">\(F_{\alpha = 5\%}\)</span> in der Klausur gegeben ist, setzen wir <span class="math inline">\(F_{\alpha = 5\%} = 3.55\)</span>.</p>
</div>
</div>
</div>
<section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="23.1"><h2 data-number="23.1" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">23.1</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">broom</span>, </span>
<span>               <span class="va">readxl</span>, <span class="va">effectsize</span>, <span class="va">ggpubr</span>, </span>
<span>               <span class="va">see</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="sec-fac1" class="level2 page-columns page-full" data-number="23.2"><h2 data-number="23.2" class="anchored" data-anchor-id="sec-fac1">
<span class="header-section-number">23.2</span> Einfaktorielle ANOVA</h2>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Einführung in die einfaktorielle ANOVA per Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/JDltrsRdAS4">die einfaktorielle ANOVA</a> als Video. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
<p>Ein <a href="https://youtu.be/LMgMIy2mh1k">weiteres Video</a> mit mehr Fokus auf die Visualisierung findest du ebenfalls auf YouTube.</p>
</div>
</div>
<p>Die einfaktorielle ANOVA ist die simpelste Form der ANOVA. Wir nutzen einen Faktor <span class="math inline">\(x\)</span> mit mehr als zwei Leveln. Im Rahmen der einfaktoriellen ANOVA wollen wir uns auch die ANOVA theoretisch einmal anschauen. Danach wie die einfaktorielle ANOVA in R genutzt wird. Ebenso werden wir die einfaktorielle ANOVA visualisieren. Abschließend müssen wir uns noch überlegen, ob es einen Effektschätzer für die einfaktorielle ANOVA gibt.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Die einfaktorielle ANOVA verlangt ein normalverteiltes <span class="math inline">\(y\)</span> sowie Varianzhomogenität über den Behandlungsfaktor <span class="math inline">\(x\)</span>. Daher alle Level von <span class="math inline">\(x\)</span> sollen die gleiche Varianz haben.</p>
<p>Unsere Annahme an die Daten <span class="math inline">\(D\)</span> ist, dass das dein <span class="math inline">\(y\)</span> normalverteilt ist und das die Level vom <span class="math inline">\(x\)</span> homogen in den Varianzen sind. Später mehr dazu, wenn wir beides nicht vorliegen haben…</p>
</div></div><section id="daten-für-die-einfaktorielle-anova" class="level3" data-number="23.2.1"><h3 data-number="23.2.1" class="anchored" data-anchor-id="daten-für-die-einfaktorielle-anova">
<span class="header-section-number">23.2.1</span> Daten für die einfaktorielle ANOVA</h3>
<p>Wir wollen uns nun erstmal den einfachsten Fall anschauen mit einem simplen Datensatz. Wir nehmen ein normalverteiltes <span class="math inline">\(y\)</span> aus den Datensatz <code>flea_dog_cat_fox.csv</code> und einen Faktor mit mehr als zwei Leveln. Hätten wir nur zwei Level, dann hätten wir auch einen t-Test rechnen können.</p>
<p>Im Folgenden selektieren mit der Funktion <code>select()</code> die beiden Spalten <code>jump_length</code> als <span class="math inline">\(y\)</span> und die Spalte <code>animal</code> als <span class="math inline">\(x\)</span>. Danach müssen wir noch die Variable <code>animal</code> in einen Faktor mit der Funktion <code>as_factor()</code> umwandeln.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fac1_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_csv2</span><span class="op">(</span><span class="st">"data/flea_dog_cat_fox.csv"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">animal</span>, <span class="va">jump_length</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>animal <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">animal</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir erhalten das Objekt <code>fac1_tbl</code> mit dem Datensatz in <a href="#tbl-data-anova-1">Tabelle&nbsp;<span>23.1</span></a> nochmal dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-anova-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle&nbsp;23.1— Selektierter Datensatz für die einfaktorielle ANOVA mit einer normalverteilten Variable <code>jump_length</code> und einem Faktor <code>animal</code> mit drei Leveln.</caption>
<thead><tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">jump_length</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">5.7</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">11.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">5.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">9.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">3.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">2.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">5.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">4.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">4.3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">7.9</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">6.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">7.7</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">8.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">9.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">9.7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">10.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">8.6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">10.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir bauen daher mit den beiden Variablen mit dem Objekt <code>fac1_tbl</code> folgendes Modell für die spätere Analyse in R.</p>
<p><span class="math display">\[
jump\_length \sim animal
\]</span></p>
<p>Bevor wir jetzt das Modell verwenden, müssen wir uns nochmal überlegen, welchen Schluß wir eigentlich über die Nullhypothese machen. Wir immer können wir nur die Nullhypothese ablehnen. Daher überlegen wir uns im Folgenden wie die Nullhypothese in der einfaktoriellen ANOVA aussieht. Dann bilden wir anhand der Nullhypothese noch die Alternativehypothese.</p>
</section><section id="hypothesen-für-die-einfaktorielle-anova" class="level3" data-number="23.2.2"><h3 data-number="23.2.2" class="anchored" data-anchor-id="hypothesen-für-die-einfaktorielle-anova">
<span class="header-section-number">23.2.2</span> Hypothesen für die einfaktorielle ANOVA</h3>
<p>Die ANOVA betrachtet die Mittelwerte und nutzt die Varianzen um einen Unterschied nachzuweisen. Daher haben wir in der Nullhypothese als Gleichheitshypothese. In unserem Beispiel lautet die Nullhypothese, dass die Mittelwerte jedes Levels des Faktors <code>animal</code> gleich sind.</p>
<p><span class="math display">\[
H_0: \; \bar{y}_{cat} = \bar{y}_{dog} = \bar{y}_{fox}
\]</span></p>
<p>Die Alternative lautet, dass sich mindestens ein paarweiser Vergleich in den Mittelwerten unterschiedet. Hierbei ist das <em>mindestens ein Vergleich</em> wichtig. Es können sich alle Mittelwerte unterschieden oder eben nur ein Paar. Wenn eine ANOVA die <span class="math inline">\(H_0\)</span> ablehnt, also ein signifikantes Ergebnis liefert, dann wissen wir nicht, welche Mittelwerte sich unterscheiden.</p>
<p><span class="math display">\[
\begin{aligned}
H_A: &amp;\; \bar{y}_{cat} \ne \bar{y}_{dog}\\
\phantom{H_A:} &amp;\; \bar{y}_{cat} \ne \bar{y}_{fox}\\
\phantom{H_A:} &amp;\; \bar{y}_{dog} \ne \bar{y}_{fox}\\
\phantom{H_A:} &amp;\; \mbox{für mindestens ein Paar}
\end{aligned}
\]</span></p>
<p>Wir schauen uns jetzt einmal die ANOVA theoretisch an bevor wir uns mit der Anwendung der ANOVA in R beschäftigen.</p>
</section><section id="einfaktoriellen-anova-theoretisch" class="level3 page-columns page-full" data-number="23.2.3"><h3 data-number="23.2.3" class="anchored" data-anchor-id="einfaktoriellen-anova-theoretisch">
<span class="header-section-number">23.2.3</span> Einfaktoriellen ANOVA theoretisch</h3>
<p>Kommen wir zurück zu den Daten in <a href="#tbl-data-anova-1">Tabelle&nbsp;<span>23.1</span></a>. Wenn wir die ANOVA per Hand rechnen wollen, dann ist nicht das Long Format die beste Wahl sondern das Wide Format. Wir haben ein balanciertes Design vorliegen, dass heißt in jeder Level sind die gleiche Anzahl Beobachtungen. Wir schauen uns jeweils sieben Flöhe von jeder Tierart an. Für eine ANOVA ist aber ein balanciertes Design nicht notwendig, wir können auch mit ungleichen Gruppengrößen eine ANOVA rechnen.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Statt einer einfaktoriellen ANOVA könnten wir auch gleich einen <code><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test()</a></code>rechnen. Historisch betrachtet ist die einfaktorielle ANOVA die Visualisierung des paarweisen t-Tests.</span></div></div>
<p>Eine einfaktorielle ANOVA macht eigentlich keinen großen Sinn, wenn wir anschließend sowieso paarweise Vergleich, wie in <a href="stat-tests-posthoc.html"><span>Kapitel&nbsp;31</span></a> beschrieben, rechnen. Aus der Historie stellte sich die Frage, ob es sich lohnt die ganze Arbeit für die paarweisen t-Tests per Hand zu rechnen. Daher wurde die ANOVA davor geschaltet. War die ANOVA nicht signifikant, dann konnte man sich dann auch die Rechnerei für die paarweisen t-Tests sparen.</p>
<p>In <a href="#tbl-fac1-wide-01">Tabelle&nbsp;<span>23.2</span></a> sehen wir die Daten einmal als Wide-Format dargestellt.</p>
<div id="tbl-fac1-wide-01" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.2— Wide Format der Beispieldaten <code>fac1_tbl</code> für die jeweils <span class="math inline">\(j=7\)</span> Beobachtungen für den Faktor <code>animal</code>.</caption>
<thead><tr class="header">
<th style="text-align: center;">j</th>
<th style="text-align: center;">dog</th>
<th style="text-align: center;">cat</th>
<th style="text-align: center;">fox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">7.7</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">8.9</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">8.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">11.8</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">9.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">4.1</td>
<td style="text-align: center;">9.7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">10.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">9.1</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">8.6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">7.6</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">10.3</td>
</tr>
</tbody>
</table>
</div>
<p>Wir können jetzt für jedes der Level den Mittelwert über all <span class="math inline">\(j=7\)</span> Beobachtungen berechnen.</p>
<p><span class="math display">\[
\begin{aligned}
\bar{y}_{dog} &amp;= 8.13 \\
\bar{y}_{cat} &amp;= 4.74 \\
\bar{y}_{fox} &amp;= 9.16 \\
\end{aligned}
\]</span></p>
<p>Wir tun jetzt für einen Moment so, als gebe es den Faktor <code>animal</code> nicht in den Daten und schauen uns die Verteilung der einzelnen Beobachtungen in <a href="#fig-anova-exp-1-1">Abbildung&nbsp;<span>23.1 (a)</span></a> einmal an. Wir sehen das sich die Beobachtungen von ca. 2.2cm bis 11 cm streuen. Woher kommt nun diese Streuung bzw. Varianz? Was ist die Quelle der Varianz? In <a href="#fig-anova-exp-1-2">Abbildung&nbsp;<span>23.1 (b)</span></a> haben wir die Punkte einmal nach dem Faktor <code>animal</code> eingefärbt. Wir sehen, dass die blauen Beobachtungen eher weitere Sprunglängen haben als die grünen Beobachtungen. Wir gruppieren die Beobachtungen in <a href="#fig-anova-exp-1-3">Abbildung&nbsp;<span>23.1 (c)</span></a> nach dem Faktor <code>animal</code> und sehen, dass ein Teil der Varianz der Daten von dem Faktor <code>animal</code> ausgelöst wird.</p>
<div id="fig-anova-exp-1" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-exp-1-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-1-1.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-1" width="480"></p>
<p></p><figcaption class="figure-caption">(a) Die Sprungweite in [cm] ohne den Faktor <code>animal</code> betrachtet.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-exp-1-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-1-2.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-1" width="480"></p>
<p></p><figcaption class="figure-caption">(b) Die Sprungweite in [cm] mit den Faktor <code>animal</code> eingefärbt.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-exp-1-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-1-3.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-1" width="480"></p>
<p></p><figcaption class="figure-caption">(c) Die Sprungweite in [cm] mit den Faktor <code>animal</code> eingefärbt und gruppiert.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.1— Die Spungweite in [cm] in Abhängigkeit von dem Faktor <code>animal</code> dargestellt.</figcaption><p></p>
</figure>
</div>
<p>Gehen wir einen Schritt weiter und zeichnen einmal das globale Mittel in die <a href="#fig-anova-exp-5-1">Abbildung&nbsp;<span>23.2 (a)</span></a> von <span class="math inline">\(\bar{y}_{..} = 7.34\)</span> und lassen die Beobachtungen gruppiert nach dem Faktor <code>animal</code>. Wir sehen, dass die Level des Faktors <code>animal</code> um das globale Mittel streuen. Was ja auch bei einem Mittelwert zu erwarten ist. Wir können jetzt in <a href="#fig-anova-exp-5-2">Abbildung&nbsp;<span>23.2 (b)</span></a> die lokalen Mittel für die einzelnen Level <code>dog</code>, <code>cat</code>und <code>fox</code> ergänzen. Und abschließend in <a href="#fig-anova-exp-5-3">Abbildung&nbsp;<span>23.2 (c)</span></a> die Abweichungen <span class="math inline">\(\\beta_i\)</span> zwischen dem globalen Mittel <span class="math inline">\(\bar{y}_{..} = 7.34\)</span> und den einzelnen lokalen Mittel berechnen. Die Summe der Abweichungen <span class="math inline">\(\\beta_i\)</span> ist <span class="math inline">\(0.79 + (-2.6) + 1.81 \approx 0\)</span>. Das ist auch zu erwarten, den das globale Mittel muss ja per Definition als Mittelwert gleich großen Abstand “nach oben” wie “nach unten” haben.</p>
<div id="fig-anova-exp-5" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-exp-5-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-5-1.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-5" width="480"></p>
<p></p><figcaption class="figure-caption">(a) Die Sprungweite in [cm] mit den Faktor <code>animal</code> gruppiert und das globale Mittel <span class="math inline">\(\bar{y}_{..} = 7.34\)</span> ergänzt.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-exp-5-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-5-2.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-5" width="480"></p>
<p></p><figcaption class="figure-caption">(b) Die Sprungweite in [cm] mit den Faktor <code>animal</code> gruppiert und die lokalen Mittel <span class="math inline">\(\bar{y}_{i.}\)</span> für jedes Level ergänzt.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-exp-5-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-5-3.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-5" width="480"></p>
<p></p><figcaption class="figure-caption">(c) Die Sprungweite in [cm] mit den Faktor <code>animal</code> gruppiert und die Abweichungen <span class="math inline">\(\beta_i\)</span> ergänzt.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.2— Dotplot der Spungweite in [cm] in Abhängigkeit von dem Faktor <code>animal</code>.</figcaption><p></p>
</figure>
</div>
<p>Wir tragen die Werte der lokalen Mittelwerte <span class="math inline">\(\bar{y}_{i.}\)</span> und deren Abweichungen <span class="math inline">\(\beta_i\)</span> vom globalen Mittelwert <span class="math inline">\(\bar{y}_{..} = 7.34\)</span> noch in die <a href="#tbl-fac1-wide-02">Tabelle&nbsp;<span>23.3</span></a> ein. Wir sehen in diesem Beispiel warum das Wide Format <em>besser</em> zum Verstehen der ANOVA ist, weil wir ja die lokalen Mittelwerte und die Abweichungen per Hand berechnen. Da wir in der Anwendung aber <em>nie</em> die ANOVA per Hand rechnen, liegen unsere Daten immer in R als Long-Format vor. Es handelt sich hier nur um die Veranschaulichung des Konzepts der ANOVA.</p>
<div id="tbl-fac1-wide-02" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.3— Wide Format der Beispieldaten <code>fac1_tbl</code> für die jeweils <span class="math inline">\(j=7\)</span> Beobachtungen für den Faktor <code>animal</code>. Wir ergänzen die lokalen Mittlwerte <span class="math inline">\(\bar{y}_{i.}\)</span> und deren Abweichungen <span class="math inline">\(\beta_i\)</span> vom globalen Mittelwert <span class="math inline">\(\bar{y}_{..} = 7.34\)</span>.</caption>
<thead><tr class="header">
<th style="text-align: center;">j</th>
<th style="text-align: center;">dog</th>
<th style="text-align: center;">cat</th>
<th style="text-align: center;">fox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">7.7</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">8.9</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">8.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">11.8</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">9.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">4.1</td>
<td style="text-align: center;">9.7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">10.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">9.1</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">8.6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">7.6</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">10.3</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\bar{y}_{i.}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\beta_i\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-2.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.79\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.81\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Wie kriegen wir nun die ANOVA rechnerisch auf die Straße? Schauen wir uns dazu einmal die <a href="#fig-anova-exp-6">Abbildung&nbsp;<span>23.3</span></a> an. Auf der linken Seiten sehen wir vier Gruppen, die keinen Effekt haben. Die Gruppen liegen alle auf der gleichen Höhe. Es ist mit keinem Unterschied zwischen den Gruppen zu rechnen. Alle Gruppen<em>mittel</em> liegen auf dem globalen Mittel. Die Abweichungen der einzelnen Gruppen<em>mittel</em> zum globalen Mittel ist damit gleich null. Auf der rechten Seite sehen wir vier Gruppen mit einem Effekt. Die Gruppen unterscheiden sich in ihren Gruppen<em>mitteln</em>. Dadurch unterscheide sich aber auch die Gruppen<em>mittel</em> von dem globalen Mittel.</p>
<div id="fig-anova-exp-6" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-anova-exp-6-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-6-1.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-6" width="576"></p>
<p></p><figcaption class="figure-caption">(a) Kein Effekt</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-anova-exp-6-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-exp-6-2.png" class="img-fluid figure-img" data-ref-parent="fig-anova-exp-6" width="576"></p>
<p></p><figcaption class="figure-caption">(b) Leichter bis mittlerer Effekt</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.3— Darstellung von keinem Effekt und leichtem bis mittleren Effekt in einer einfaktoriellen ANOVA mit einem Faktor mit vier Leveln A - D.</figcaption><p></p>
</figure>
</div>
<p>Wir können daher wie in <a href="#tbl-sum-anova-eff">Tabelle&nbsp;<span>23.4</span></a> geschrieben die Funktionsweise der ANOVA zusammenfassen. Wir vergleichen die Mittelwerte indem wir die Varianzen nutzen.</p>
<div id="tbl-sum-anova-eff" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.4— Zusammenfassung der ANOVA Funktionsweise.</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 5%">
<col style="width: 67%">
</colgroup>
<tbody><tr class="odd">
<td style="text-align: center;">All level means are equal.</td>
<td style="text-align: center;">=</td>
<td style="text-align: center;">The differences between level means and the total mean are small.</td>
</tr></tbody>
</table>
</div>
<p>Nun kommen wir zum eigentlichen Schwenk und warum eigentlich die ANOVA meist etwas verwirrt. Wir wollen eine Aussage über die Mittelwerte machen. Die Nullhypothese lautet, dass alle Mittelwerte gleich sind. Wie wir in <a href="#tbl-sum-anova-eff">Tabelle&nbsp;<span>23.4</span></a> sagen, heißt alle Mittelwerte gleich auch, dass die Abweichungen von den Gruppenmitteln zum globalen Mittel klein ist.</p>
<p>Wie weit die Gruppenmittel von dem globalen Mittel weg sind, dazu nutzt die ANOVA die Varianz. Die ANOVA vergleicht somit</p>
<ul>
<li>die Varianz der einzelnen Mittelwerte der (Gruppen)Level zum globalen Mittel (eng. <em>variability between levels</em>)</li>
<li>und die Varianz der Beobachtungen zu den einzelnen Mittelwerten der Level (eng. <em>variability within one level</em>)</li>
</ul>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Die <em>sum of squares</em> sind nichts anderes als die Varianz. Wir nennen das hier nur einmal anders…</span></div></div>
<p>Wir berechnen also wie die Beobachtungen jeweils um das globale Mittel streuen (<span class="math inline">\(SS_{total}\)</span>), die einzelnen Beobachtungen um die einzelnen Gruppenmittel <span class="math inline">\(SS_{error}\)</span> und die Streuung der Gruppenmittel um das globale Mittel (<span class="math inline">\(SS_{animal}\)</span>). Wir nennen die Streuung Abstandquadrate (eng. <em>sum of squares</em>) und damit sind die <em>Sum of Square</em> <span class="math inline">\((SS)\)</span> nichts anderes als die Varianz. Die <a href="#tbl-sumsquares">Tabelle&nbsp;<span>23.5</span></a> zeigt die Berechnung des Anteils jeder einzelnen Beobachtung an den jeweiligen <em>Sum of Squares</em>.</p>
<div class="column-page">
<div id="tbl-sumsquares" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.5— Berechnung der <span class="math inline">\(SS_{animal}\)</span>, <span class="math inline">\(SS_{error}\)</span> und <span class="math inline">\(SS_{total}\)</span> anhand der einzelnen gemessenen Werte <span class="math inline">\(y\)</span> für durch die jeweiligen Gruppenmittel <span class="math inline">\(\bar{y}_{i.}\)</span> und dem globalen Mittel <span class="math inline">\(\bar{y}_{..}\)</span> über alle Beobachtungen</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">animal (x)</th>
<th style="text-align: center;">jump_length (y)</th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{\bar{y}_{i.}}\)</span></th>
<th style="text-align: center;">SS<span class="math inline">\(_{\boldsymbol{animal}}\)</span>
</th>
<th style="text-align: center;">SS<span class="math inline">\(_{\boldsymbol{error}}\)</span>
</th>
<th style="text-align: center;">SS<span class="math inline">\(_{\boldsymbol{total}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(5.7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((5.7 - 8.13)^2 = 5.90\)</span></td>
<td style="text-align: center;"><span class="math inline">\((5.7 - 7.34)^2 = 2.69\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(8.9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.9 - 8.13)^2 = 0.59\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.9 - 7.34)^2 = 2.43\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(11.8\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((11.8 - 8.13)^2 = 13.47\)</span></td>
<td style="text-align: center;"><span class="math inline">\((11.8 - 7.34)^2 = 19.89\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(8.2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.2 - 8.13)^2 = 0.00\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.2 - 7.34)^2 = 0.74\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(5.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((5.6 - 8.13)^2 = 6.40\)</span></td>
<td style="text-align: center;"><span class="math inline">\((5.6 - 7.34)^2 = 3.03\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(9.1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.1 - 8.13)^2 = 0.94\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.1 - 7.34)^2 = 3.10\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;"><span class="math inline">\(7.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.13 - 7.34)^2 = 0.62\)</span></td>
<td style="text-align: center;"><span class="math inline">\((7.6 - 8.13)^2 = 0.28\)</span></td>
<td style="text-align: center;"><span class="math inline">\((7.6 - 7.34)^2 = 0.07\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(3.2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((3.2 - 4.74)^2 = 2.37\)</span></td>
<td style="text-align: center;"><span class="math inline">\((3.2 - 7.34)^2 = 17.14\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(2.2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.2 - 4.74)^2 = 6.45\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.2 - 7.34)^2 = 26.42\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(5.4\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((5.4 - 4.74)^2 = 0.44\)</span></td>
<td style="text-align: center;"><span class="math inline">\((5.4 - 7.34)^2 = 3.76\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(4.1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.1 - 4.74)^2 = 0.41\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.1 - 7.34)^2 = 10.50\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(4.3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.3 - 4.74)^2 = 0.19\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.3 - 7.34)^2 = 9.24\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(7.9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((7.9 - 4.74)^2 = 9.99\)</span></td>
<td style="text-align: center;"><span class="math inline">\((7.9 - 7.34)^2 = 0.31\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;"><span class="math inline">\(6.1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.74\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.74 - 7.34)^2 = 6.76\)</span></td>
<td style="text-align: center;"><span class="math inline">\((6.1 - 4.74)^2 = 1.85\)</span></td>
<td style="text-align: center;"><span class="math inline">\((6.1 - 7.34)^2 = 1.54\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(7.7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((7.7 - 9.16)^2 = 2.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\((7.7 - 7.34)^2 = 0.13\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(8.1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.1 - 9.16)^2 = 1.12\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.1 - 7.34)^2 = 0.58\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(9.1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.1 - 9.16)^2 = 0.00\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.1 - 7.34)^2 = 3.10\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(9.7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.7 - 9.16)^2 = 0.29\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.7 - 7.34)^2 = 5.57\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(10.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((10.6 - 9.16)^2 = 2.07\)</span></td>
<td style="text-align: center;"><span class="math inline">\((10.6 - 7.34)^2 = 10.63\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(8.6\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.6 - 9.16)^2 = 0.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.6 - 7.34)^2 = 1.59\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;"><span class="math inline">\(10.3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.16\)</span></td>
<td style="text-align: center;"><span class="math inline">\((9.16 - 7.34)^2 = 3.31\)</span></td>
<td style="text-align: center;"><span class="math inline">\((10.3 - 9.16)^2 = 1.30\)</span></td>
<td style="text-align: center;"><span class="math inline">\((10.3 - 7.34)^2 = 8.76\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(74.68\)</span></td>
<td style="text-align: center;"><span class="math inline">\(56.53\)</span></td>
<td style="text-align: center;"><span class="math inline">\(131.21\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Die ANOVA wird deshalb auch Varianz<em>zerlegung</em> genannt, da die ANOVA versucht den Abstand der Beobachtungen auf die Variablen im Modell zu zerlegen. Also wie viel der Streuung von den Beobachtungen kann von dem Faktor <code>animal</code> erklärt werden? Genau der Abstand von den Gruppenmitteln zu dem globalen Mittelwert.</p>
<p>Du kannst dir das ungefähr als eine Reise von globalen Mittelwert zu der einzelnen Beobachtung vorstellen. Nehmen wir als Beispiel die kleinste Sprungweite eines Katzenflohs von 2.2 cm und visualisieren wir uns die Reise wie in <a href="#fig-single-cat-anova">Abbildung&nbsp;<span>23.4</span></a> zu sehen. Wie kommen wir jetzt <em>numerisch</em> vom globalen Mittel mit <span class="math inline">\(7.34\)</span> zu der Beobachtung? Wir können zum einen den direkten Abstand mit <span class="math inline">\(2.2 - 7.34\)</span> gleich <span class="math inline">\(-5.14\)</span> cm berechnen. Das wäre der <em>total</em> Abstand. Wie sieht es nun aus, wenn wir das Gruppenmittel mit beachten? In dem Fall gehen wir vom globalen Mittel zum Gruppenmittel <code>cat</code> mit <span class="math inline">\(\bar{y}_{cat} - \bar{y}_{..} = 4.74 -7.34\)</span> gleich <span class="math inline">\(\beta_{cat} = -2.6\)</span> cm. Jetzt sind wir aber noch nicht bei der Beobachtung. Wir haben noch einen Rest von <span class="math inline">\(y_{cat,2} - \bar{y}_{cat} = 2.2 - 4.74\)</span> gleich <span class="math inline">\(\epsilon_{cat, 2} = -2.54\)</span> cm, die wir noch zurücklegen müssen. Das heißt, wir können einen Teil der Strecke mit dem Gruppenmittelwert erklären. Oder anders herum, wir können die Strecke vom globalen Mittelwert zu der Beobachtung in einen Teil für das Gruppenmittel und einen unerklärten Rest zerlegen.</p>
<div class="column-page">
<div id="fig-single-cat-anova" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/anova-pre-01.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.4— Visualisierung der Varianzzerlegung des Weges vom globalen Mittel zu der einzelnen Beoabchtung. Um zu einer einzelnen Beobachtung zu kommen legen wir den Weg vom globalen Mittelwert über den Abstand vom globalen Mittel zum Gruppenmittel <span class="math inline">\(\beta\)</span> zurück. Dann fehlt noch der Rest oder Fehler oder Residuum <span class="math inline">\(\epsilon\)</span>.</figcaption><p></p>
</figure>
</div>
</div>
<p>Wir rechnen also eine ganze Menge an Abständen und quadrieren dann diese Abstände zu den Sum of Squares. Oder eben der Varianz. Dann fragen wir uns, ob der Faktor in unserem Modell einen Teil der Abstände erklären kann. Wir bauen uns dafür eine ANOVA Tabelle. <a href="#tbl-anova-fac1-theo">Tabelle&nbsp;<span>23.6</span></a> zeigt eine theoretische, einfaktorielle ANOVA Tabelle. Wir berechnen zuerst die Abstände als <span class="math inline">\(SS\)</span>. Nun ist es aber so, dass wenn wir in einer Gruppe viele Level und/oder Beobachtungen haben, wir auch größere Sum of Squares bekommen. Wir müssen also die Sum of Squares in mittlere Abweichungsquadrate (eng. <em>mean squares</em>) mitteln. Abschließend können wir die F Statistik berechnen, indem wir die <span class="math inline">\(MS\)</span> des Faktors durch die <span class="math inline">\(MS\)</span> des Fehlers teilen. Das Verhältnis von erklärter Varianz vom Faktor zu dem unerklärten Rest.</p>
<div class="column-page">
<div id="tbl-anova-fac1-theo" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.6— Einfaktorielle ANOVA in der theoretischen Darstellung. Die sum of squares müssen noch zu den Mean squares gemittelt werden. Abschließend wird die F Statistik als Prüfgröße berechnet.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 39%">
<col style="width: 23%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Varianzquelle</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of squares</th>
<th style="text-align: center;">Mean squares</th>
<th style="text-align: center;">F<span class="math inline">\(_{\boldsymbol{calc}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">animal</td>
<td style="text-align: center;"><span class="math inline">\(k-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal} = \sum_{i=1}^{k}n_i(\bar{y}_{i.} - \bar{y}_{..})^2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal} = \cfrac{SS_{animal}}{k-1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{MS_{animal}}{MS_{error}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">error</td>
<td style="text-align: center;"><span class="math inline">\(n-k\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{error} = \sum_{i=1}^{k}\sum_{j=1}^{n_i}(y_{ij} - \bar{y}_{i.})^2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{error} = \cfrac{SS_{error}}{N-k}\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">total</td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total} = \sum_{i=1}^{k}\sum_{j=1}^{n_i}(y_{ij} - \bar{y}_{..})^2\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Wir füllen jetzt die <a href="#tbl-anova-fac1-example">Tabelle&nbsp;<span>23.7</span></a> einmal mit den Werten aus. Nachdem wir das getan haben oder aber die Tabelle in R ausgegeben bekommen haben, können wir die Zahlen interpretieren.</p>
<div class="column-page">
<div id="tbl-anova-fac1-example" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.7— Einfaktorielle ANOVA mit den ausgefüllten Werten. Die <span class="math inline">\(SS_{total}\)</span> sind die Summe der <span class="math inline">\(SS_{animal}\)</span> und <span class="math inline">\(SS_{error}\)</span>. Die <span class="math inline">\(MS\)</span> berechnen sich dann direkt aus den <span class="math inline">\(SS\)</span> und den Freiheitsgraden (<span class="math inline">\(df\)</span>). Abschließend ergibt sich dann die F Statistik.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 33%">
<col style="width: 31%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Varianzquelle</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of squares</th>
<th style="text-align: center;">Mean squares</th>
<th style="text-align: center;">F<span class="math inline">\(_{\boldsymbol{calc}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">animal</td>
<td style="text-align: center;"><span class="math inline">\(3-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal} = 74.68\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal} = \cfrac{74.68}{3-1} = 37.34\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{37.34}{3.14} = 11.89\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">error</td>
<td style="text-align: center;"><span class="math inline">\(21-3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{error} = 56.53\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{error} = \cfrac{56.53}{18} = 3.14\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">total</td>
<td style="text-align: center;"><span class="math inline">\(21-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total} = 131.21\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Zu erst ist die berechnete F Statistik <span class="math inline">\(F_{calc}\)</span> von Interesse. Wir haben hier eine <span class="math inline">\(F_{calc}\)</span> von 11.89. Wir vergleichen wieder die berechnete F Statistik mit einem kritischen Wert. Der kritische F Wert <span class="math inline">\(F_{\alpha = 5\%}\)</span> lautet für die einfaktorielle ANOVA in diesem konkreten Beispiel mit <span class="math inline">\(F_{\alpha = 5\%} = 3.55\)</span>. Die Entscheidungsregel nach der F Teststatistik lautet, die <span class="math inline">\(H_0\)</span> abzulehnen, wenn <span class="math inline">\(F_{calc} &gt; F_{\alpha = 5\%}\)</span>.</p>
<p>Wir können also die Nullhypothese <span class="math inline">\(H_0\)</span> in unserem Beispiel ablehnen. Es liegt ein signifikanter Unterschied zwischen den Tiergruppen vor. Mindestens ein Mittelwertsunterschied in den Sprungweiten liegt vor.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Entscheidung mit der berechneten Teststatistik <span class="math inline">\(F_{\boldsymbol{calc}}\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bei der Entscheidung mit der berechneten Teststatistik <span class="math inline">\(F_{calc}\)</span> gilt, wenn <span class="math inline">\(F_{calc} \geq F_{\alpha = 5\%}\)</span> wird die Nullhypothese (H<span class="math inline">\(_0\)</span>) abgelehnt.</p>
<p><strong>Achtung –</strong> Wir nutzen die Entscheidung mit der Teststatistik <em>nur und ausschließlich</em> in der Klausur. In der praktischen Anwendung hat die Betrachtung der berechneten Teststatistik <em>keine</em> Verwendung mehr. Wir nutzen in der praktischen Anwendung den <span class="math inline">\(p\)</span>-Wert.</p>
</div>
</div>
<p>Abschließend noch ein Wort zu der Annahme an eine ANOVA. Wir wollen ja für eine ANOVA ein normalverteiltes Outcome <span class="math inline">\(y\)</span> und die gleichen Varianzen über alle Gruppen. Wir wollen Varianzhomogenität vorliegen haben. In <a href="#fig-anova-assumption">Abbildung&nbsp;<span>23.5</span></a> siehst du vier Behandlungsgruppen sowie deren lokale Mittel. Die Gruppe D hat eine sehr viel größere Varianz. Auch ist fraglich, ob die Gruppe D einer Normalverteilung folgt. Dadurch passieren zwei Dinge. Erstens ist der lokale Mittelwert von der Gruppe D viel näher am globalen Mittel als er eigentlich wäre, dadurch wird die <em>Summe</em> aus <span class="math inline">\(MS_{treatment}\)</span> kleiner. Zweitens sind die Beobachtungen sehr weit um das lokale Mittel gestreut, dadurch wird die <em>Summe</em> aus <span class="math inline">\(MS_{error}\)</span> viel größer. Wir erhalten dadurch eine sehr viel kleinere F Statistik. Im Prinzip vergleichst du mit einer ANOVA ein Set an gleich aussehenden Normalverteilungen. Wenn alles schief und krumm ist, dann ist es vermutlich sogar besser, als wenn wir eine total verkorkste Gruppenverteilung haben, wie hier in Beispiel D.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">In <a href="eda-transform.html"><span>Kapitel&nbsp;17</span></a> kannst du nochmal über die <span class="math inline">\(\log\)</span>-Transformation vom Outcome <span class="math inline">\(y\)</span> nachlesen. Nach der <span class="math inline">\(\log\)</span>-Transformation können Daten dann <em>approximativ</em> normalverteilt sein.</span></div></div>
<div id="fig-anova-assumption" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/anova-assumptions.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.5— Visualisierung der Annahmen an eine ANOVA. Wir berechnen den <span class="math inline">\(MS_{treatment}\)</span> in dem wir alle Abweichungen vom gloablen Mittel <span class="math inline">\(\bar{y}_{..}\)</span> aufaddieren. Ebenso berechnen wir den <span class="math inline">\(MS_{error}\)</span> indem wir die einzelen Abweichungen von den Bobachtungen <span class="math inline">\(\epsilon\)</span> zu den lokalen Mitteln berechnen. Hat jetzt eine Gruppe, wie die Gruppe D, eine abweichende Streuung, wird das <span class="math inline">\(MS_{error}\)</span> überproportional groß. Damit wird dann die F Statistik klein.</figcaption><p></p>
</figure>
</div>
<p>Wir können das einmal numerisch mit einem kritischen Wert für <span class="math inline">\(F_{\alpha = 5\%} = 3.55\)</span> durchspielen. Nehmen wir folgende Summe für <span class="math inline">\(MS_{treatment}\)</span> aus der <a href="#fig-anova-assumption">Abbildung&nbsp;<span>23.5</span></a> mit den einzelnen <span class="math inline">\(MS\)</span> einmal wie folgt an. Wir nehmen an das <span class="math inline">\(MS_A\)</span> gleich 10, <span class="math inline">\(MS_B\)</span> gleich 20, <span class="math inline">\(MS_C\)</span> gleich 8 und <span class="math inline">\(MS_D\)</span> gleich 7 ist. Dann können wir durch das Summieren das <span class="math inline">\(MS_{treatment}\)</span> berechnen.</p>
<p><span class="math display">\[
MS_{treatment} = 10 + 20 + 8 + 7 = 45
\]</span></p>
<p>Wenn wir jetzt die Summe für <span class="math inline">\(MS_{error}\)</span> berechnen, wird diese Summe sehr große, da die Gruppe D eine sehr große Varianz mit einbringt.</p>
<p><span class="math display">\[
MS_{error} = 5 + 6 + 4 + 20 = 35
\]</span></p>
<p>Das führt am Ende dazu, dass wir eine sehr kleine F Statistik erhalten. Auch wenn sich vielleicht Gruppe B von Gruppe C unterscheidet, können wir den Unterschied wegen der großen Varianz aus Gruppe D nicht nachweisen.</p>
<p><span class="math display">\[
F = \cfrac{MS_{treatment}}{MS_{error}} = \cfrac{45}{35} = 1.28 \leq 3.55
\]</span></p>
<p>Du siehst hier wie wichtig es ist, ich die Daten einmal zu visualisieren um zu sehen vorher mögliche Probleme herrühren können. Auf der anderen Seite können wir die ANOVA auf ein Recht breites Spektrum an Daten anwenden, solange wir wissen, das die Verteilungen in etwa für jede Gruppe gleich aussehen. Wir müssen nur mit dem <span class="math inline">\(\eta^2\)</span> aufpassen, wenn wir zu schiefe Verteilungen haben. Dann gibt uns <span class="math inline">\(\eta^2\)</span> keine valide Aussage mehr über den Anteil der erklärten Varianz.</p>
</section><section id="einfaktoriellen-anova-in-r" class="level3 page-columns page-full" data-number="23.2.4"><h3 data-number="23.2.4" class="anchored" data-anchor-id="einfaktoriellen-anova-in-r">
<span class="header-section-number">23.2.4</span> Einfaktoriellen ANOVA in R</h3>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Um eine ANOVA zu rechnen nutzen wir <em>zuerst</em> die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, warum das so ist kannst du im <a href="stat-linear-reg-basic.html"><span>Kapitel&nbsp;32</span></a> nachlesen. Du brauchst das Wissen aber hier nicht unbedingt.</span></div></div>
<p>Wir rechnen keine ANOVA per Hand sondern nutzen R. Dazu müssen wir als erstes das Modell definieren. Das ist im Falle der einfaktoriellen ANOVA relativ einfach. Wir haben unseren Datensatz <code>fac1_tbl</code> mit einer kontinuierlichen Variable <code>jump_lemgth</code> als <span class="math inline">\(y\)</span> vorliegen sowie einen Faktor <code>animal</code> mit mehr als zwei Leveln als <span class="math inline">\(x\)</span>. Wir definieren das Modell in R in der Form <code>jump_length ~ animal</code>. Um das Modell zu rechnen nutzen wir die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> - die Abkürzung für <em>linear model</em>. Danach pipen wir die Ausgabe vom <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> direkt in die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code>. Die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> berechnet uns dann die eigentliche einfaktorielle ANOVA. Wir speichern die Ausgabe der ANOVA in <code>fit_1</code>. Schauen wir uns die ANOVA Ausgabe einmal an.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1</span> <span class="op">&lt;-</span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span>, data <span class="op">=</span> <span class="va">fac1_tbl</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">anova</span></span>
<span></span>
<span><span class="va">fit_1</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: jump_length
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
animal     2 74.683  37.341   11.89 0.0005113 ***
Residuals 18 56.529   3.140                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Wir erhalten die Information was wir gerechnet haben, eine Varianzanalyse. Darunter steht, was das <span class="math inline">\(y\)</span> war nämlich die <code>jump_length</code>. Wir erhalten eine Zeile für den Faktor <code>animal</code> und damit die <span class="math inline">\(SS_{animal}\)</span> und eine Zeile für den Fehler und damit den <span class="math inline">\(SS_{error}\)</span>. In R heißen die <span class="math inline">\(SS_{error}\)</span> dann <code>Residuals</code>. Die Zeile für die <span class="math inline">\(SS_{total}\)</span> fehlt.</p>
<p>Neben der berechneten F Statistik <span class="math inline">\(F_{calc}\)</span> von <span class="math inline">\(11.89\)</span> erhalten wir auch den p-Wert mit <span class="math inline">\(0.005\)</span>. Wir ignorieren die F Statistik, da wir in der Anwendung nur den p-Wert berücksichtigen. Die Entscheidung gegen die Nulhypothese lautet, dass wenn der p-Wert kleiner ist als das Signifkanzniveau <span class="math inline">\(\alpha\)</span> von 5% wir die Nullhypothese ablehnen.</p>
<p>Wir haben hier ein signifikantes Ergebnis vorliegen. Mindestens ein Gruppenmittelerstunterschied ist signifikant. <a href="#fig-boxplot-anova-1">Abbildung&nbsp;<span>23.6</span></a> zeigt nochmal die Daten <code>fac1_tbl</code> als Boxplot. Wir überprüfen visuell, ob das Ergebnis der ANOVA stimmen kann. Ja, die Boxplots und das Ergebnis der ANOVA stimmen überein. Die Boxplots liegen nicht alle auf einer Ebene, so dass hier auch ein signifikanter Unterschied zu erwarten war.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot-anova-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-boxplot-anova-1-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.6— Boxplot der Sprungweiten [cm] von Hunden-, Katzen- und Fuchsflöhen.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Abschließend können wir noch die Funktion <code>eta_squared()</code> aus dem R Paket <code>effectsize</code> nutzen um einen Effektschätzer für die einfaktorielle ANOVA zu berechnen. Wir können mit <span class="math inline">\(\eta^2\)</span> abschätzen, welchen Anteil der Faktor <code>animal</code> an der gesamten Varianz erklärt.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1</span> <span class="op">%&gt;%</span> <span class="va">eta_squared</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
animal    | 0.57 | [0.27, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Das <span class="math inline">\(\eta^2\)</span> können wir auch einfach händisch berechnen.</p>
<p><span class="math display">\[
\eta^2 = \cfrac{SS_{animal}}{SS_{total}} = \cfrac{74.68}{131.21} = 0.57 = 57\%
\]</span></p>
<p>Wir haben nun die Information, das 57% der Varianz der Beobachtungen durch den Faktor <code>animal</code> rklärt wird. Je nach Anwendungsgebiet kann die Relevanz sehr stark variieren. Im Bereich der Züchtung mögen erklärte Varianzen von unter 10% noch sehr relevant sein. Im Bereich des Feldexperiments erwarten wir schon höhere Werte für <span class="math inline">\(\eta^2\)</span>. Immerhin sollte ja unsere Behandlung maßgeblich für die z.B. größeren oder kleineren Pflanzen gesorgt haben.</p>
</section></section><section id="sec-fac2" class="level2 page-columns page-full" data-number="23.3"><h2 data-number="23.3" class="anchored" data-anchor-id="sec-fac2">
<span class="header-section-number">23.3</span> Zweifaktorielle ANOVA</h2>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Einführung in die zweifaktorielle ANOVA per Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/82SUzQL1AEw">die zweifaktorielle ANOVA</a> als Video. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Die zweifaktorielle ANOVA verlangt ein normalverteiltes <span class="math inline">\(y\)</span> sowie Varianzhomogenität jeweils separat über beide Behandlungsfaktor <span class="math inline">\(x_1\)</span> und <span class="math inline">\(x_2\)</span>. Daher alle Level von <span class="math inline">\(x_1\)</span> sollen die gleiche Varianz haben. Ebenso sollen alle Level von <span class="math inline">\(x_2\)</span> die gleiche Varianz haben.</p>
<p>Unsere Annahme an die Daten <span class="math inline">\(D\)</span> ist, dass das dein <span class="math inline">\(y\)</span> normalverteilt ist und das die Level vom <span class="math inline">\(x_1\)</span> und <span class="math inline">\(x_2\)</span> jeweils für sich homogen in den Varianzen sind. Später mehr dazu, wenn wir beides nicht vorliegen haben…</p>
</div></div><p>Die zweifaktorielle ANOVA ist eine wunderbare Methode um herauszufinden, ob zwei Faktoren einen Einfluss auf ein normalverteiltes <span class="math inline">\(y\)</span> haben. Die Stärke der zweifaktoriellen ANOVA ist hierbei, dass die ANOVA <em>beide</em> Effekte der Faktoren auf das <span class="math inline">\(y\)</span> simultan modelliert. Darüber hinaus können wir auch noch einen Interaktionsterm mit in das Modell aufnehmen um zu schauen, ob die beiden Faktoren untereinander auch interagieren. Somit haben wir mit der zweifaktoriellen ANOVA die Auswertungsmehode für ein randomiziertes Blockdesign vorliegen.</p>
<section id="daten-für-die-zweifaktorielle-anova" class="level3" data-number="23.3.1"><h3 data-number="23.3.1" class="anchored" data-anchor-id="daten-für-die-zweifaktorielle-anova">
<span class="header-section-number">23.3.1</span> Daten für die zweifaktorielle ANOVA</h3>
<p>Wir wollen uns nun einen etwas komplexes Modell anschauen mit einem etwas komplizierteren Datensatz <code>flea_dog_cat_fox_site.csv</code>. Wir brauchen hierfür ein normalverteiltes <span class="math inline">\(y\)</span> und sowie zwei Faktoren. Das macht auch soweit Sinn, denn wir wollen ja auch eine zweifaktorielle ANOVA rechnen.</p>
<p>Im Folgenden selektieren mit der Funktion <code>select()</code> die beiden Spalten <code>jump_length</code> als <span class="math inline">\(y\)</span> und die Spalte <code>animal</code> sowie die Spalte <code>site</code> als <span class="math inline">\(x\)</span>. Danach müssen wir noch die Variable <code>animal</code> sowie die Variable <code>site</code> in einen Faktor mit der Funktion <code>as_factor()</code> umwandeln.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fac2_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_csv2</span><span class="op">(</span><span class="st">"data/flea_dog_cat_fox_site.csv"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">animal</span>, <span class="va">site</span>, <span class="va">jump_length</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>animal <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">animal</span><span class="op">)</span>,</span>
<span>         site <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">site</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir erhalten das Objekt <code>fac2_tbl</code> mit dem Datensatz in <a href="#tbl-data-anova-2">Tabelle&nbsp;<span>23.8</span></a> nochmal dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-anova-2" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle&nbsp;23.8— Selektierter Datensatz für die zweifaktorielle ANOVA mit einer normalverteilten Variable <code>jump_length</code> und einem Faktor <code>animal</code> mit drei Leveln sowie dem Faktor <code>site</code> mit vier Leveln.</caption>
<thead><tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">site</th>
<th style="text-align: center;">jump_length</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">12.04</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">11.98</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">16.10</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">13.42</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">12.37</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">16.36</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">14.91</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Die Beispieldaten sind in <a href="#fig-boxplot-anova-2">Abbildung&nbsp;<span>23.7</span></a> abgebildet. Wir sehen auf der x-Achse den Faktor <code>animal</code> mit den drei Leveln <code>dog</code>, <code>cat</code> und <code>fox</code>. Jeder dieser Faktorlevel hat nochmal einen Faktor in sich. Dieser Faktor lautet <code>site</code> und stellt dar, wo die Flöhe gesammelt wurden. Die vier Level des Faktors <code>site</code> sind <code>city</code>, <code>smalltown</code>, <code>village</code> und <code>field</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot-anova-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-boxplot-anova-2-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.7— Boxplot der Sprungweiten [cm] von Hunden und Katzen.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Wir bauen dann mit den beiden Variablen bzw. Faktoren <code>animal</code> und <code>site</code> aus dem Objekt <code>fac2_tbl</code> folgendes Modell für die zweifaktorielle ANOVA:</p>
<p><span class="math display">\[
jump\_length \sim animal + site
\]</span></p>
<p>Bevor wir jetzt das Modell verwenden, müssen wir uns nochmal überlegen, welchen Schluß wir eigentlich über die Nullhypothese machen. Wir immer können wir nur die Nullhypothese ablehnen. Daher überlegen wir uns im Folgenden wie die Nullhypothese in der zweifaktoriellen ANOVA aussieht. Dann bilden wir anhand der Nullhypothese noch die Alternativehypothese.</p>
</section><section id="hypothesen-für-die-zweifaktorielle-anova" class="level3" data-number="23.3.2"><h3 data-number="23.3.2" class="anchored" data-anchor-id="hypothesen-für-die-zweifaktorielle-anova">
<span class="header-section-number">23.3.2</span> Hypothesen für die zweifaktorielle ANOVA</h3>
<p>Wir haben für jeden Faktor der zweifaktoriellen ANOVA ein Hypothesenpaar. Im Folgenden sehen wir die jeweiligen Hypothesenpaare. Einmal für <code>animal</code>, als Haupteffekt. Wir nennen einen Faktor den Hauptfaktor, weil wir an diesem Faktor am meisten interessiert sind. Wenn wir später einen Posthoc Test durchführen würden, dann würden wir diesen Faktor nehmen. Wir sind primär an dem Unterschied der Sprungweiten in [cm] in Gruppen Hund, Katze und Fuchs interessiert.</p>
<p><span class="math display">\[
\begin{aligned}
H_0: &amp;\; \bar{y}_{cat} = \bar{y}_{dog} = \bar{y}_{fox}\\
H_A: &amp;\; \bar{y}_{cat} \ne \bar{y}_{dog}\\
\phantom{H_A:} &amp;\; \bar{y}_{cat} \ne \bar{y}_{fox}\\
\phantom{H_A:} &amp;\; \bar{y}_{dog} \ne \bar{y}_{fox}\\
\phantom{H_A:} &amp;\; \mbox{für mindestens ein Paar}
\end{aligned}
\]</span></p>
<p>Einmal für <code>site</code>, als Nebeneffekt oder Blockeffekt oder Clustereffekt. Meist eine Variable, die wir auch erhoben haben und <em>vermutlich</em> auch einen Effekt auf das <span class="math inline">\(y\)</span> haben wird. Oder aber wir haben durch das exprimentelle Design noch eine Aufteilungsvariable wie Block vorliegen. In unserem Beispiel ist es <code>site</code> oder der Ort, wo wir die Hunde-, Katzen, und Fuchsflöhe gefunden haben.</p>
<p><span class="math display">\[
\begin{aligned}
H_0: &amp;\; \bar{y}_{city} = \bar{y}_{smalltown} = \bar{y}_{village} = \bar{y}_{field}\\
H_A: &amp;\; \bar{y}_{city} \ne \bar{y}_{smalltown}\\
\phantom{H_A:} &amp;\; \bar{y}_{city} \ne \bar{y}_{village}\\
\phantom{H_A:} &amp;\; \bar{y}_{city} \ne \bar{y}_{field}\\
\phantom{H_A:} &amp;\; \bar{y}_{smalltown} \ne \bar{y}_{village}\\
\phantom{H_A:} &amp;\; \bar{y}_{smalltown} \ne \bar{y}_{field}\\
\phantom{H_A:} &amp;\; \bar{y}_{village} \ne \bar{y}_{field}\\
\phantom{H_A:} &amp;\; \mbox{für mindestens ein Paar}
\end{aligned}
\]</span></p>
<p>Einmal für die Interaktion <code>animal:site</code> - die eigentliche Stärke der zweifaktoriellen ANOVA. Wir können uns anschauen, ob die beiden Faktoren miteinander interagieren. Das heißt, ob eine Interaktion zwischen dem Faktor <code>animal</code> und dem Faktor <code>site</code> vorliegt.</p>
<p><span class="math display">\[
\begin{aligned}
H_0: &amp;\; \mbox{keine Interaktion}\\
H_A: &amp;\; \mbox{eine Interaktion zwischen animal und site}
\end{aligned}
\]</span></p>
<p>Wir haben also jetzt die verschiedenen Hypothesenpaare definiert und schauen uns jetzt die ANOVA in R einmal in der Anwendung an.</p>
</section><section id="zweifaktoriellen-anova-in-r" class="level3 page-columns page-full" data-number="23.3.3"><h3 data-number="23.3.3" class="anchored" data-anchor-id="zweifaktoriellen-anova-in-r">
<span class="header-section-number">23.3.3</span> Zweifaktoriellen ANOVA in R</h3>
<p>Bei der einfaktoriellen ANOVA haben wir die Berechnungen der Sum of squares nochmal nachvollzogen. Im Falle der zweifaktoriellen ANOVA verzichten wir darauf. Das Prinzip ist das gleiche. Wir haben nur mehr Mitelwerte und mehr Abweichungen von diesen Mittelwerten, da wir ja nicht nur einen Faktor <code>animal</code> vorliegen haben sondern auch noch den Faktor <code>site</code>. Da wir aber die ANOVA nur Anwenden und dazu R nutzen, müssen wir jetzt nicht per Hand die zweifaktorielle ANOVA rechnen. Du musst aber die R Ausgabe der ANOVA verstehen. Und diese Ausgabe schauen wir uns jetzt einmal ohne und dann mit Interaktionsterm an.</p>
<section id="ohne-interaktionsterm" class="level4 page-columns page-full" data-number="23.3.3.1"><h4 data-number="23.3.3.1" class="anchored" data-anchor-id="ohne-interaktionsterm">
<span class="header-section-number">23.3.3.1</span> Ohne Interaktionsterm</h4>
<p>Wir wollen nun einmal die zweifaktorielle ANOVA ohne Interaktionsterm rechnen die in <a href="#tbl-anova-fac2-ohne-inter">Tabelle&nbsp;<span>23.9</span></a> dargestellt ist. Die <span class="math inline">\(SS\)</span> und <span class="math inline">\(MS\)</span> für die zweifaktorielle ANOVA berechnen wir nicht selber sondern nutzen die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> in R.</p>
<div class="column-page">
<div id="tbl-anova-fac2-ohne-inter" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.9— Zweifaktorielle ANOVA ohne Interaktionseffekt in der theoretischen Darstellung. Die Sum of squares müssen noch zu den Mean squares gemittelt werden. Abschließend wird die F Statistik als Prüfgröße berechnet.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 42%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Varianzquelle</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of squares</th>
<th style="text-align: center;">Mean squares</th>
<th style="text-align: center;">F<span class="math inline">\(_{\boldsymbol{calc}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">animal</td>
<td style="text-align: center;"><span class="math inline">\(a-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{MS_{animal}}{MS_{error}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">site</td>
<td style="text-align: center;"><span class="math inline">\(b-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{site}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{site}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{MS_{site}}{MS_{error}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">error</td>
<td style="text-align: center;"><span class="math inline">\(n-(a-1)(b-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{error}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{error}\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">total</td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Du kannst mehr über Geraden sowie lineare Modelle und deren Eigenschaften im <a href="stat-linear-reg-basic.html"><span>Kapitel&nbsp;32</span></a> erfahren.</span></div></div>
<p>Im Folgenden sehen wir nochmal das Modell ohne Interaktionsterm. Wir nutzen die Schreibweise in R für eine Modellformel.</p>
<p><span class="math display">\[
jump\_length \sim animal + site
\]</span></p>
<p>Wir bauen nun mit der obigen Formel ein lineares Modell mit der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> in R. Danach pipen wir das Modell in die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> wie auch in der einfaktoriellen Variante der ANOVA. Die Funktion bleibt die Gleiche, was sich ändert ist das Modell in der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">&lt;-</span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span> <span class="op">+</span> <span class="va">site</span>, data <span class="op">=</span> <span class="va">fac2_tbl</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">anova</span></span>
<span></span>
<span><span class="va">fit_2</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: jump_length
           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
animal      2 180.03  90.017 19.8808 3.92e-08 ***
site        3   9.13   3.042  0.6718    0.571    
Residuals 114 516.17   4.528                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Wir erhalten wiederum die ANOVA Ergebnistabelle. Anstatt nur die Zeile <code>animal</code> für den Effekt des Faktors <code>animal</code> sehen wir jetzt auch noch die Zeile <code>site</code> für den Effekt des Faktors <code>site</code>. Zuerst ist weiterhin der Faktor <code>animal</code> signifikant, da der <span class="math inline">\(p\)</span>-Wert mit <span class="math inline">\(0.000000039196\)</span> kleiner ist als das Signifikanzniveau <span class="math inline">\(\alpha\)</span> von 5%. Wir können von mindestens einem Gurppenunterschied im Faktor <code>animal</code> ausgehen. Im Weiteren ist der Faktor <code>site</code> nicht signifikant. Es scheint keinen Unterschied zwischend den einzelnen Orten und der Sprunglänge von den Hunde-, Katzen- und Fuchsflöhen zu geben.</p>
<p>Neben der Standausgabe von R können wir auch die <code>tidy</code> Variante uns ausgeben lassen. In dem Fall sieht die Ausgabe etwas mehr aufgeräumt aus.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">%&gt;%</span> <span class="va">tidy</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 6
  term         df  sumsq meansq statistic       p.value
  &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;
1 animal        2 180.    90.0     19.9    0.0000000392
2 site          3   9.13   3.04     0.672  0.571       
3 Residuals   114 516.     4.53    NA     NA           </code></pre>
</div>
</div>
<p>Abschließend können wir uns übr <span class="math inline">\(\eta^2\)</span> auch die erklärten Anteile der Varianz wiedergeben lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">%&gt;%</span> <span class="va">eta_squared</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter | Eta2 (partial) |       95% CI
-----------------------------------------
animal    |           0.26 | [0.15, 1.00]
site      |           0.02 | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Wir sehen, dass nur ein kleiner Teil der Varianz von dem Faktor <code>animal</code> erklärt wird, nämlich 26%. Für den Faktor <code>site</code> haben wir nur einen Anteil von 2% der erklärten Varianz. Somit hat die <code>site</code> weder einen signifikanten Einflluss auf die Sprungweite von Flöhen noch ist dieser Einfluss als relevant zu betrachten.</p>
<p>Abschließend können wir die Werte in der <a href="#tbl-anova-fac2-ohne-inter-example">Tabelle&nbsp;<span>23.10</span></a> ergänzen. Die Frage ist inwieweit diese Tabelle in der Form von Interesse ist. Meist wird geschaut, ob die Faktoren signifikant sind oder nicht. Abschließend eventuell noch die <span class="math inline">\(\eta^2\)</span> Werte berichtet. Hier musst du schauen, was in deinem Kontext der Forschung oder Abschlussarbeit erwartet wird.</p>
<div class="column-page">
<div id="tbl-anova-fac2-ohne-inter-example" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.10— Zweifaktorielle Anova ohne Interaktionseffekt mit den ausgefüllten Werten. Die <span class="math inline">\(SS_{total}\)</span> sind die Summe der <span class="math inline">\(SS_{animal}\)</span> und <span class="math inline">\(SS_{error}\)</span>. Die <span class="math inline">\(MS\)</span> berechnen sich dann direkt aus den <span class="math inline">\(SS\)</span> und den Freiheitsgraden (<span class="math inline">\(df\)</span>). Abschließend ergibt sich dann die F Statistik.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 34%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Varianzquelle</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of squares</th>
<th style="text-align: center;">Mean squares</th>
<th style="text-align: center;">F<span class="math inline">\(_{\boldsymbol{calc}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">animal</td>
<td style="text-align: center;"><span class="math inline">\(3-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal} = 180.03\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal} = 90.02\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{90.02}{4.53} = 19.88\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">site</td>
<td style="text-align: center;"><span class="math inline">\(4-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{site} = 9.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{site} = 3.04\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{3.04}{4.53} = 0.67\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">error</td>
<td style="text-align: center;"><span class="math inline">\(120-(3-1)(4-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{error} = 516.17\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{error} = 4.53\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">total</td>
<td style="text-align: center;"><span class="math inline">\(120-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total} = 705.33\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="mit-interaktionssterm" class="level4 page-columns page-full" data-number="23.3.3.2"><h4 data-number="23.3.3.2" class="anchored" data-anchor-id="mit-interaktionssterm">
<span class="header-section-number">23.3.3.2</span> Mit Interaktionssterm</h4>
<p>Wir wollen nun noch einmal die zweifaktorielle ANOVA mit Interaktionsterm rechnen, die in <a href="#tbl-anova-fac3-inter">Tabelle&nbsp;<span>23.11</span></a> dargestellt ist. Die <span class="math inline">\(SS\)</span> und <span class="math inline">\(MS\)</span> für die zweifaktorielle ANOVA berechnen wir nicht selber sondern nutzen wie immer die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> in R.</p>
<div class="column-page">
<div id="tbl-anova-fac3-inter" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.11— Zweifaktorielle ANOVA mit Interaktionseffekt in der theoretischen Darstellung. Die Sum of squares müssen noch zu den Mean squares gemittelt werden. Abschließend wird die F Statistik als Prüfgröße berechnet.</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 39%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Varianzquelle</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of squares</th>
<th style="text-align: center;">Mean squares</th>
<th style="text-align: center;">F<span class="math inline">\(_{\boldsymbol{calc}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">animal</td>
<td style="text-align: center;"><span class="math inline">\(a-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{MS_{animal}}{MS_{error}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">site</td>
<td style="text-align: center;"><span class="math inline">\(b-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{site}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{site}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{MS_{site}}{MS_{error}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">animal <span class="math inline">\(\times\)</span> site</td>
<td style="text-align: center;"><span class="math inline">\((a-1)(b-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal \times site}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal \times site}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{MS_{animal \times site}}{MS_{error}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">error</td>
<td style="text-align: center;"><span class="math inline">\(n-ab\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{error}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{error}\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">total</td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Im Folgenden sehen wir nochmal das Modell mit Interaktionsterm. Wir nutzen die Schreibweise in R für eine Modellformel. Einen Interaktionsterm bilden wir durch das <code>:</code> in R ab. Wir können theoretisch auch noch weitere Interaktionsterme bilden, also auch <code>x:y:z</code>. Ich würde aber davon abraten, da diese Interaktionsterme schwer zu interpretieren sind.</p>
<p><span class="math display">\[
jump\_length \sim animal + site + animal:site
\]</span></p>
<p>Wir bauen nun mit der obigen Formel ein lineares Modell mit der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> in R. Es wieder das gleich wie schon zuvor. Danach pipen wir das Modell in die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> wie auch in der einfaktoriellen Variante der ANOVA. Die Funktion bleibt die Gleiche, was sich ändert ist das Modell in der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. Auch die Interaktion müssen wir nicht extra in der ANOVA Funktion angeben. Alles wird im Modell des <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> abgebildet.</p>
<p>Die visuelle Regel zur Überprüfung der Interaktion lautet nun wie folgt. <a href="#fig-anova-inter-example">Abbildung&nbsp;<span>23.8</span></a> zeigt die entsprechende Vislualisierung. Wir haben keine Interaktion vorliegen, wenn die Geraden parallel zueinander laufen und die Abstände bei bei jedem Faktorlevel gleich sind. Wir schauen uns im Prinzip die erste Faktorstufe auf der x-Achse an. Wir sehen den Abstand von der roten zu blauen Linie sowie das die blaue Gerade über der roten Gerade liegt. Dieses Muster erwarten wir jetzt auch an dem Faktorlevel B und C. Eine leichte bis mittlere Interaktion liegt vor, wenn sich die Abstände von dem zweiten Faktor über die Faktorstufen des ersten Faktors ändern. Eine starke Interaktion liegt vor, wenn sich die Geraden schneiden.</p>
<div id="fig-anova-inter-example" class="cell column-page quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-inter-example-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-inter-example-1.png" class="img-fluid figure-img" data-ref-parent="fig-anova-inter-example" width="480"></p>
<p></p><figcaption class="figure-caption">(a) Keine Interaktion</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-inter-example-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-inter-example-2.png" class="img-fluid figure-img" data-ref-parent="fig-anova-inter-example" width="480"></p>
<p></p><figcaption class="figure-caption">(b) Leichte bis mittlere Intraktion</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-anova-inter-example-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-anova-inter-example-3.png" class="img-fluid figure-img" data-ref-parent="fig-anova-inter-example" width="480"></p>
<p></p><figcaption class="figure-caption">(c) Starke Interaktion</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.8— Darstellung von keiner Interaktion, leichter bis mittler Interaktion und starker Interaktion in einer zweifaktoriellen ANOVA mit einem Faktor mit drei Leveln A, B und C sowie einem Faktor mit zwei Leveln (rot und blau).</figcaption><p></p>
</figure>
</div>
<p>In der <a href="#fig-interact-anova-1">Abbildung&nbsp;<span>23.9</span></a> sehen wir den Interaktionsplot für unser Beispiel. Auf der y-Achse ist die Sprunglänge abgebildet und auf der x-Achse der Faktor <code>animal</code>. Die einzelnen Farben stellen die Level des Faktor <code>site</code> dar.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">fac2_tbl</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">animal</span>, y <span class="op">=</span> <span class="va">jump_length</span>,</span>
<span>                     color <span class="op">=</span> <span class="va">site</span>, group <span class="op">=</span> <span class="va">site</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"point"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"line"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interact-anova-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-anova_files/figure-html/fig-interact-anova-1-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;23.9— Boxplot der Sprungweiten [cm] von Hunden und Katzen.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Wenn sich die Geraden in einem Interaktionsplot schneiden, haben wir eine Interaktion zwischen den beiden Faktoren vorliegen</span></div></div>
<p>Wir schauen zur visuellen Überprüfung auf den Faktor <code>animal</code> und das erste level <code>cat</code>. Wir sehen die Ordnung des zweiten Faktors <code>site</code> mit <code>field</code>, <code>village</code>, <code>smalltown</code> und <code>city</code>. Diese Ordnung und die Abstände sind bei zweiten Faktorlevel <code>dog</code> schon nicht mehr gegeben. Die Geraden schneiden sich. Auch liegt bei dem Level <code>fox</code> eine andere ordnung vor. Daher sehen wir hier eine starke Interaktion zwischen den beiden Faktoren <code>animal</code> und <code>site</code>.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Du kannst mehr über Geraden sowie lineare Modelle und deren Eigenschaften im <a href="stat-linear-reg-basic.html"><span>Kapitel&nbsp;32</span></a> erfahren.</span></div></div>
<p>Wir nehmen jetzt auf jeden Fall den Interaktionsterm <code>animal:site</code> mit in unser Modell und schauen uns einmal das Ergebnis der ANOVA an. Das lineare Modell der ANOVA wird erneut über die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> berechnet und anschließend in die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> gepipt.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_3</span> <span class="op">&lt;-</span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span> <span class="op">+</span> <span class="va">site</span> <span class="op">+</span> <span class="va">animal</span><span class="op">:</span><span class="va">site</span>, data <span class="op">=</span> <span class="va">fac2_tbl</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">anova</span></span>
<span></span>
<span><span class="va">fit_3</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: jump_length
             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
animal        2 180.03  90.017 30.2807 3.63e-11 ***
site          3   9.13   3.042  1.0233   0.3854    
animal:site   6 195.11  32.519 10.9391 1.71e-09 ***
Residuals   108 321.05   2.973                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Wenn wir eine signifikante Interaktion vorliegen haben, dann müssen wir den Faktor A getrennt für jedes Levels des Faktors B auswerten.</span></div></div>
<p>Die Ergebnistabelle der ANOVA wiederholt sich. Wir sehen, dass der Faktor <code>animal</code> signifikant ist, da der p-Wert mit <span class="math inline">\(0.000000000036\)</span> kleiner ist als das Signifikanzniveau <span class="math inline">\(\alpha\)</span> von 5%. Wir können daher die Nullhypothese ablehnen. Mindestens ein Mittelwertsvergleich unterschiedet sich zwischen den Levels des Faktors <code>animal</code>. Im Weiteren sehen wir, dass der Faktor <code>site</code> nicht signifkant ist, da der p-Wert mit <span class="math inline">\(0.39\)</span> größer ist als das Signifikanzniveau <span class="math inline">\(\alpha\)</span> von 5%. Wir können daher die Nullhypothese nicht ablehnen. Abschließend finden wir die Interaktion zwischen dem Faktor <code>animal</code>und <code>site</code> las signifikant vor. Wenn wir eine signifikante Interaktion vorliegen haben, dann müssen wir den Faktor <code>animal</code> getrennt für jedes Levels des Faktors <code>site</code> auswerten. Wir können keine Aussage über die Sprungweite von Hunde-, Katzen- und Fuchsflöhen <em>unabhängig</em> von der Herkunft <code>site</code> der Flöhe machen.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">In <span class="quarto-unresolved-ref">?sec-app-example-anova-inter</span> findest du ein Beispiel für eine signifikante Interaktion und die folgende Auswertung</span></div></div>
<p>Wir können wie immer die etwas aufgeräumte Variante der ANOVA Ausgabe mit der Funktion <code>tidy()</code> uns ausgeben lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_3</span> <span class="op">%&gt;%</span> <span class="fu">tidy</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 6
  term           df  sumsq meansq statistic   p.value
  &lt;chr&gt;       &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 animal          2 180.    90.0      30.3   3.63e-11
2 site            3   9.13   3.04      1.02  3.85e- 1
3 animal:site     6 195.    32.5      10.9   1.71e- 9
4 Residuals     108 321.     2.97     NA    NA       </code></pre>
</div>
</div>
<p>Im Folgenden können wir noch die <span class="math inline">\(\eta^2\)</span> für die ANOVA als Effektschätzer berechnen lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_3</span> <span class="op">%&gt;%</span> <span class="va">eta_squared</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter   | Eta2 (partial) |       95% CI
-------------------------------------------
animal      |           0.36 | [0.24, 1.00]
site        |           0.03 | [0.00, 1.00]
animal:site |           0.38 | [0.24, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Wir sehen, dass nur ein kleiner Teil der Varianz von dem Faktor <code>animal</code> erklärt wird, nämlich 36%. Für den Faktor <code>site</code> haben wir nur einen Anteil von 3% der erklärten Varianz. Die Interaktion zwischen <code>animal</code> und <code>site</code> erklärt 38% der beobachteten Varianz udn ist somit auch vom Effekt her nicht zu ignorieren. Somit hat die <code>site</code> weder einen signifikanten Einflluss auf die Sprungweite von Flöhen noch ist dieser Einfluss als relevant zu betrachten.</p>
<p>Abschließend können wir die Werte in der <a href="#tbl-anova-fac3-inter-example">Tabelle&nbsp;<span>23.12</span></a> ergänzen. Die Frage ist inwieweit diese Tabelle in der Form von Interesse ist. Meist wird geschaut, ob die Faktoren signifikant sind oder nicht. Abschließend eventuell noch die <span class="math inline">\(\eta^2\)</span> Werte berichtet. Hier musst du schauen, was in deinem Kontext der Forschung oder Abschlussarbeit erwartet wird.</p>
<div class="column-page">
<div id="tbl-anova-fac3-inter-example" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;23.12— Zweifaktorielle Anova mit Interaktionseffekt mit den ausgefüllten Werten. Die <span class="math inline">\(SS_{total}\)</span> sind die Summe der <span class="math inline">\(SS_{animal}\)</span> und <span class="math inline">\(SS_{error}\)</span>. Die <span class="math inline">\(MS\)</span> berechnen sich dan direkt aus den <span class="math inline">\(SS\)</span> und den Freiheitsgraden (<span class="math inline">\(df\)</span>). Abschließend ergibt sich dann die F Statistik.</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 23%">
<col style="width: 22%">
<col style="width: 26%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Varianzquelle</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of squares</th>
<th style="text-align: center;">Mean squares</th>
<th style="text-align: center;">F<span class="math inline">\(_{\boldsymbol{calc}}\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">animal</td>
<td style="text-align: center;"><span class="math inline">\(3-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal} = 180.03\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal} = 90.02\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{90.02}{2.97} = 30.28\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">site</td>
<td style="text-align: center;"><span class="math inline">\(4-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{site} = 9.13\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{site} = 3.04\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{3.04}{2.97} = 1.02\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">animal <span class="math inline">\(\times\)</span> site</td>
<td style="text-align: center;"><span class="math inline">\((3-1)(4-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{animal \times site} = 195.12\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{animal \times site} = 32.52\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{calc} = \cfrac{32.52}{2.97} = 10.94\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">error</td>
<td style="text-align: center;"><span class="math inline">\(120 - (3 \cdot 4)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{error} = 321.06\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{error} = 2.97\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">total</td>
<td style="text-align: center;"><span class="math inline">\(120-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total} = 705.34\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</section></section></section><section id="und-weiter" class="level2 page-columns page-full" data-number="23.4"><h2 data-number="23.4" class="anchored" data-anchor-id="und-weiter">
<span class="header-section-number">23.4</span> Und weiter?</h2>
<p>Nach einer berechneten ANOVA können wir zwei Fälle vorliegen haben.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Wenn du in deinem Experiment keine <em>signifikanten</em> Ergebnisse findest, ist das nicht schlimm. Du kannst deine Daten immer noch mit der explorativen Datenanalyse auswerten wie in <a href="eda-ggplot.html"><span>Kapitel&nbsp;16</span></a> beschrieben.</span></div></div>
<ol type="1">
<li>Wir habe eine nicht signifikante ANOVA berechnet. Wir können die Nullhypothese <span class="math inline">\(H_0\)</span> nicht ablehnen und die Mittelwerte über den Faktor sind vermutlich alle gleich. Wir enden hier mit unserer statistischen Analyse.</li>
<li>Wir haben eine signifikante ANOVA berechnet. Wir können die Nullhypothese <span class="math inline">\(H_0\)</span> ablehnen und mindestens ein Gruppenvergleich über mindestens einen Faktor ist vermutlich unterschiedlich. Wir können dann in <a href="stat-tests-posthoc.html"><span>Kapitel&nbsp;31</span></a> eine Posthoc Analyse rechnen.</li>
</ol>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-tests-ttest.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-tests-ancova.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>