<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 48&nbsp; Robuste und Quantilesregression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-survival.html" rel="next">
<link href="./stat-modeling-non-linear.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-modeling-preface.html">Statistisches Modellieren</a></li><li class="breadcrumb-item"><a href="./stat-modeling-robust-quantile.html"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Einfache experimentelle Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Fortgeschrittene experimentelle Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Anhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spielecke</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link active" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">48.1</span> Genutzte R Pakete</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"><span class="header-section-number">48.2</span> Daten</a></li>
  <li>
<a href="#gew%C3%B6hnliche-lineare-regression" id="toc-gewöhnliche-lineare-regression" class="nav-link" data-scroll-target="#gew%C3%B6hnliche-lineare-regression"><span class="header-section-number">48.3</span> Gewöhnliche lineare Regression</a>
  <ul class="collapse">
<li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova"><span class="header-section-number">48.3.1</span> ANOVA</a></li>
  <li><a href="#gruppenvergleich" id="toc-gruppenvergleich" class="nav-link" data-scroll-target="#gruppenvergleich"><span class="header-section-number">48.3.2</span> Gruppenvergleich</a></li>
  </ul>
</li>
  <li>
<a href="#sec-robust-reg" id="toc-sec-robust-reg" class="nav-link" data-scroll-target="#sec-robust-reg"><span class="header-section-number">48.4</span> Robuste Regression</a>
  <ul class="collapse">
<li><a href="#anova-1" id="toc-anova-1" class="nav-link" data-scroll-target="#anova-1"><span class="header-section-number">48.4.1</span> ANOVA</a></li>
  <li><a href="#gruppenvergleich-1" id="toc-gruppenvergleich-1" class="nav-link" data-scroll-target="#gruppenvergleich-1"><span class="header-section-number">48.4.2</span> Gruppenvergleich</a></li>
  </ul>
</li>
  <li>
<a href="#sec-quantile-reg" id="toc-sec-quantile-reg" class="nav-link" data-scroll-target="#sec-quantile-reg"><span class="header-section-number">48.5</span> Quantilsregression</a>
  <ul class="collapse">
<li><a href="#anova-2" id="toc-anova-2" class="nav-link" data-scroll-target="#anova-2"><span class="header-section-number">48.5.1</span> ANOVA</a></li>
  <li><a href="#gruppenvergleich-2" id="toc-gruppenvergleich-2" class="nav-link" data-scroll-target="#gruppenvergleich-2"><span class="header-section-number">48.5.2</span> Gruppenvergleich</a></li>
  </ul>
</li>
  <li>
<a href="#modellvergleich" id="toc-modellvergleich" class="nav-link" data-scroll-target="#modellvergleich"><span class="header-section-number">48.6</span> Modellvergleich</a>
  <ul class="collapse">
<li><a href="#basilikumdaten" id="toc-basilikumdaten" class="nav-link" data-scroll-target="#basilikumdaten"><span class="header-section-number">48.6.1</span> Basilikumdaten</a></li>
  <li><a href="#gurkendaten" id="toc-gurkendaten" class="nav-link" data-scroll-target="#gurkendaten"><span class="header-section-number">48.6.2</span> Gurkendaten</a></li>
  </ul>
</li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-reg-quantile" class="quarto-section-identifier"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom August 10, 2023 um 21:44:17</em></p>
<blockquote class="blockquote">
<p><em>“Methods for robust statistics, a state of the art in the early 2000s, notably for robust regression and robust multivariate analysis.” — <a href="https://cran.r-project.org/web/packages/robust/index.html">robust: Port of the S+ “Robust Library”</a></em></p>
</blockquote>
<p>In diesem Kapitel geht es um zwei Arten der Regression, die immer wieder genannt werden, aber dennoch eine Art Nischendasein fristen. Zum einen möchte ich hier die robuste Regression (eng. <em>robust regression</em>) und zum anderen die Quantilsregression (eng. <em>quantile regression</em>) vorstellen. Die robuste Regression ist faktisch statistisch tot. Das heißt, die Implementierungen werden kaum weiterentwickelt und auch findet methodische Forschung nur in der theoretischen Nische statt. Zwar wird die robuste Regression in ihrer ursprünglichen Form als Regression angewendet, aber das reicht meistens nicht. Selten wollen wir nur durch ein paar Punkte eine Gerade ziehen und uns über das gute Modell erfreuen. Wir haben mit dem Modell meist mehr vor. Wir wollen eine ANOVA rechnen und dann auch einen wie auch immer gearteten Mittelwertsvergleich. Wenn dies zwar theoretisch möglich ist, praktisch aber nicht implementiert, dann wollen und können wir die Methoden nur eingeschränkt verwenden. Bei der Quantilsregression sieht es etwas anders aus, hier können wir dann schon den ein oder anderen Mittelwertsvergleich rechnen. Was bei der Quantilsregression eher problematisch ist, ist das das Modell nicht immer konvergiert oder aber nicht algorithmisch eine Lösung für einen spezifischen Datensatz findet. In diesem Datensatz dann den einen Grund zu finden, ist dann meist so aufwendig, dass wir es auch gleich mit der Quantilsregression lassen können.</p>
<p>Der Charme der Quantilesregression ist ja am Ende, dass wir auch den Median als Quantile auswählen können. So haben wir dann die Möglichkeit eine Regression auf den Medianen zu rechnen. Wir vergleichen damit dann auch die Mediane und sind so nicht mehr auf die Normalverteilung unseres Outcomes wie in der gewöhnlichen Regression angewiesen. Also eigentlich eine tolle Sache, wenn wir nur an den Mittelwertsvergleichen interessiert sind. Eine klassische ANOVA geht leider nicht auf einer Medianregression. Eine klassische ANOVA wäre aber mit nicht parametrischen Methoden sowieso nicht möglich gewesen. Wir verlieren also nicht so viel, gewinnen aber etwas, wenn das Modell konvergiert und ein Ergebnis liefert.</p>
<p>In diesem Kapitel brechen wir etwas die bisherige Struktur der Regressionskapitel auf. Wir schauen uns hier zuerst die beiden Modelle an und entscheiden dann, ob wir die Modelle für die ANOVA oder den Gruppenvergleich <em>überhaupt</em> nutzen können. Am Ende vergleichen wir dann einmal alle Modell mit dem fantastische Paket <code>modelsummary</code> mit der gleichnamigen Funktion. Hier hilft dann wie immer die tolle <a href="https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html">Hilfsseite von modelsummary</a> zu besuchen.</p>
<section id="genutzte-r-pakete" class="level2" data-number="48.1"><h2 data-number="48.1" class="anchored" data-anchor-id="genutzte-r-pakete">
<span class="header-section-number">48.1</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">conflicted</span>, <span class="va">broom</span>, <span class="va">quantreg</span>,</span>
<span>               <span class="va">see</span>, <span class="va">performance</span>, <span class="va">emmeans</span>, <span class="va">multcomp</span>, <span class="va">janitor</span>,</span>
<span>               <span class="va">parameters</span>, <span class="va">effectsize</span>, <span class="va">MASS</span>, <span class="va">modelsummary</span>,</span>
<span>               <span class="va">robustbase</span>, <span class="va">multcompView</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"mutate"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="va">cbbPalette</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#000000"</span>, <span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, </span>
<span>                <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2 page-columns page-full" data-number="48.2"><h2 data-number="48.2" class="anchored" data-anchor-id="daten">
<span class="header-section-number">48.2</span> Daten</h2>
<p>Für unser erstes Beispiel nutzen wir die Daten aus einem Wachstumsversuch mit Basilikum mit vier Bodenbehandlungen und vier Blöcken, die Blöcke sind eigentlich Gewächshaustische. Wir wollen also einen klassischen Gruppenvergleich mit Berücksichtigung der Blockstruktur rechnen.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/keimversuch_basilikum_block.xlsx"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">clean_names</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>versuchsgruppe <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">versuchsgruppe</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">versuchsgruppe</span>, <span class="va">block_1</span><span class="op">:</span><span class="va">block_4</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <a href="#tbl-model-1">Tabelle&nbsp;<span>48.1</span></a> sehen wir einmal die Daten im Wide-Format. Wir haben also das Frischgewicht der Basilikumpflanzen gemessen und wollen wissen, ob die verschiedenen Bodenarten einen Einfluss auf das Wachstum haben.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-model-1" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;48.1— Datensatz des Frischegewichts von Basilikumpflanzen auf vier Tischen bzw. Blöcken in vier Versuchsgruppen.</caption>
<thead><tr class="header">
<th style="text-align: center;">versuchsgruppe</th>
<th style="text-align: center;">block_1</th>
<th style="text-align: center;">block_2</th>
<th style="text-align: center;">block_3</th>
<th style="text-align: center;">block_4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Erde</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: center;">Erde</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Erde</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: center;">Erde</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Erde</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: center;">Erde+Fließ</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">Erde+Perlite</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Perlite+Fließ</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: center;">Perlite+Fließ</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">26</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Perlite+Fließ</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="even">
<td style="text-align: center;">Perlite+Fließ</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Perlite+Fließ</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">22</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Da wir die Daten im Wide-Format vorliegen haben, müssen wir die Daten nochmal in Long-Format umwandeln. Wie immer nutzen wir dafür die Funktion <code>pivot_longer()</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_block_tbl</span> <span class="op">&lt;-</span> <span class="va">basi_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pivot_longer</span><span class="op">(</span>cols <span class="op">=</span> <span class="va">block_1</span><span class="op">:</span><span class="va">block_4</span>,</span>
<span>               values_to <span class="op">=</span> <span class="st">"weight"</span>,</span>
<span>               names_to <span class="op">=</span> <span class="st">"block"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>block <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">block</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#fig-robust-basi-00">Abbildung&nbsp;<span>48.1</span></a> siehst du einmal die Daten als Dotplots mit Mittelwert und Standardabweichung. Wir machen hier mal einen etwas komplizierteren Plot, aber immer nur Barplot ist ja auch langweilig.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">basi_block_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">versuchsgruppe</span>, <span class="va">weight</span>, color <span class="op">=</span> <span class="va">block</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span>, shape <span class="op">=</span> <span class="fl">4</span>, size <span class="op">=</span> <span class="fl">2.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data<span class="op">=</span><span class="st">"mean_sdl"</span>, fun.args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>mult <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, </span>
<span>               geom<span class="op">=</span><span class="st">"pointrange"</span>, position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, fun.min <span class="op">=</span> <span class="st">"min"</span>, fun.max <span class="op">=</span> <span class="st">"max"</span>, geom <span class="op">=</span> <span class="st">"line"</span>,</span>
<span>               position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-robust-basi-00" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-robust-basi-00-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;48.1— Dotplot des Frischegewichts von Basilikumpflanzen auf vier Tischen bzw. Blöcken in vier Versuchsgruppen mit Mittelwert und Standardabweichung.</figcaption></figure>
</div>
</div>
</div>
<p>Unser zweiter Datensatz ist ein Anwendungsdatensatz aus dem Gemüsebau. Wir schauen uns das Wachstum von drei Gurkensorten über siebzehn Wochen an. Die Gurkensorten sind hier unsere Versuchsgruppen. Da wir es hier mit echten Daten zu tun haben, müssen wir uns etwas strecken damit die Daten dann auch passen. Wir wollen das Wachstum der drei Gurkensorten <em>über</em> die Zeit betrachten - also faktisch den Verlauf des Wachstums. Wir ignorieren hier einmal die abhängige Datenstruktur über die Zeitpunkte.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Mit einer abhängigen Datenstruktur müssten wir eigentlich ein lineares gemischtes Modell rechnen. Aber wir nutzen hier die Daten einmal anders.</p>
</div></div><p>Im Weiteren haben wir zwei Typen von Daten für das Gurkenwachstum. Einmal messen wir den Durchmesser für jede Sorte (<code>D</code> im Namen der Versuchsgruppe) oder aber die Länge (<code>L</code> im Namen der Versuchsgruppe). Wir betrachten hier nur das Längenwachstum und deshalb filtern wir erstmal nach allen Versuchsgruppen mit einem <code>L</code> im Namen. Am Ende schmeißen wir noch Spalten raus, die wir nicht weiter brauchen.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gurke_raw_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/wachstum_gurke.xlsx"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">clean_names</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu">str_detect</span><span class="op">(</span><span class="va">versuchsgruppe</span>, <span class="st">"L$"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">pfl</span>, <span class="op">-</span><span class="va">erntegewicht</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>versuchsgruppe <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">versuchsgruppe</span>, </span>
<span>                                 labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Katrina"</span>, <span class="st">"Proloog"</span>, <span class="st">"Quarto"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#tbl-model-2">Tabelle&nbsp;<span>48.2</span></a> sehen wir einmal die rohen Daten dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-model-2" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;48.2— Datensatz zu dem Längen- und Dickenwachstum von Gurken.</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">versuchsgruppe</th>
<th style="text-align: center;">t1</th>
<th style="text-align: center;">t2</th>
<th style="text-align: center;">t3</th>
<th style="text-align: center;">t4</th>
<th style="text-align: center;">t5</th>
<th style="text-align: center;">t6</th>
<th style="text-align: center;">t7</th>
<th style="text-align: center;">t8</th>
<th style="text-align: center;">t9</th>
<th style="text-align: center;">t10</th>
<th style="text-align: center;">t11</th>
<th style="text-align: center;">t12</th>
<th style="text-align: center;">t13</th>
<th style="text-align: center;">t14</th>
<th style="text-align: center;">t15</th>
<th style="text-align: center;">t16</th>
<th style="text-align: center;">t17</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Proloog</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">7.4</td>
<td style="text-align: center;">8.9</td>
<td style="text-align: center;">9.9</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">14.4</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">19.8</td>
<td style="text-align: center;">21.2</td>
<td style="text-align: center;">23.2</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">29.7</td>
<td style="text-align: center;">32.8</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">Proloog</td>
<td style="text-align: center;">4.6</td>
<td style="text-align: center;">5.1</td>
<td style="text-align: center;">6.4</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Proloog</td>
<td style="text-align: center;">5.3</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">6.8</td>
<td style="text-align: center;">8.3</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">12.3</td>
<td style="text-align: center;">14.6</td>
<td style="text-align: center;">17.6</td>
<td style="text-align: center;">19.3</td>
<td style="text-align: center;">23.1</td>
<td style="text-align: center;">23.8</td>
<td style="text-align: center;">31.7</td>
<td style="text-align: center;">32.3</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">Proloog</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">6.9</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">8.6</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">12.1</td>
<td style="text-align: center;">14.5</td>
<td style="text-align: center;">16.2</td>
<td style="text-align: center;">17.1</td>
<td style="text-align: center;">19.3</td>
<td style="text-align: center;">21.6</td>
<td style="text-align: center;">28.5</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Proloog</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">6.3</td>
<td style="text-align: center;">7.5</td>
<td style="text-align: center;">8.3</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">12.2</td>
<td style="text-align: center;">14.4</td>
<td style="text-align: center;">16.5</td>
<td style="text-align: center;">19.9</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">22.9</td>
<td style="text-align: center;">30.4</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">Proloog</td>
<td style="text-align: center;">4.2</td>
<td style="text-align: center;">4.6</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">5.3</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9.3</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">12.5</td>
<td style="text-align: center;">22.3</td>
<td style="text-align: center;">24.2</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">Katrina</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4.7</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">5.3</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Katrina</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">4.4</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6.2</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">6.2</td>
<td style="text-align: center;">6.8</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">9.4</td>
<td style="text-align: center;">10.4</td>
<td style="text-align: center;">13.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Katrina</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">2.8</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Katrina</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">5.9</td>
<td style="text-align: center;">6.9</td>
<td style="text-align: center;">8.4</td>
<td style="text-align: center;">9.4</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">12.2</td>
<td style="text-align: center;">13.5</td>
<td style="text-align: center;">17.9</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">Katrina</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">4.6</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">9.5</td>
<td style="text-align: center;">10.5</td>
<td style="text-align: center;">11.7</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">13.4</td>
<td style="text-align: center;">17.9</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Katrina</td>
<td style="text-align: center;">3.1</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">3.8</td>
<td style="text-align: center;">4.2</td>
<td style="text-align: center;">4.9</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">6.8</td>
<td style="text-align: center;">7.7</td>
<td style="text-align: center;">9.1</td>
<td style="text-align: center;">10.7</td>
<td style="text-align: center;">12.3</td>
<td style="text-align: center;">17.7</td>
<td style="text-align: center;">18.6</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Dann müssen wir die Daten noch in Long-Format bringen. Da wir dann auch noch auf zwei Arten die Daten über die Zeit darstellen wollen, brauchen wir einmal die Zeit als Faktor <code>time_fct</code> und einmal als numerisch <code>time_num</code>. Leider haben wir auch Gurken mit einer Länge von 0 cm, diese Gruken lassen wir jetzt mal drin, da wir ja eine robuste Regression noch rechnen wollen. Auch haben wir ab Woche 14 keine Messungen mehr in der Versuchsgruppe <code>Prolong</code>, also nehmen wir auch nur die Daten bis zur vierzehnten Woche.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gurke_time_len_tbl</span> <span class="op">&lt;-</span> <span class="va">gurke_raw_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pivot_longer</span><span class="op">(</span>cols <span class="op">=</span> <span class="va">t1</span><span class="op">:</span><span class="va">t17</span>,</span>
<span>               values_to <span class="op">=</span> <span class="st">"length"</span>,</span>
<span>               names_to <span class="op">=</span> <span class="st">"time"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>time_fct <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">time</span><span class="op">)</span>,</span>
<span>         time_num <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">time_fct</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">time_num</span> <span class="op">&lt;=</span> <span class="fl">14</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#fig-robust-gurke-00">Abbildung&nbsp;<span>48.2</span></a> sehen wir dann nochmal den Scatterplot für das Gurkenwachstum. Die gestrichtelten Linien stellen den Median und die durchgezogene Line den Mittelwert der Gruppen dar.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">gurke_time_len_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">time_num</span>, <span class="va">length</span>, color <span class="op">=</span> <span class="va">versuchsgruppe</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point2</span><span class="op">(</span>position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"line"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"median"</span>, geom <span class="op">=</span> <span class="st">"line"</span>, linetype <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">14</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-robust-gurke-00" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-robust-gurke-00-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;48.2— Scatterplot des Längenwachstums der drei Gurkensorten über vierzehn Wochen. Die gestrichtelten Linien stellen den Median und die durchgezogene Line den Mittelwert der Gruppen dar.</figcaption></figure>
</div>
</div>
</div>
</section><section id="gewöhnliche-lineare-regression" class="level2" data-number="48.3"><h2 data-number="48.3" class="anchored" data-anchor-id="gewöhnliche-lineare-regression">
<span class="header-section-number">48.3</span> Gewöhnliche lineare Regression</h2>
<p>Damit wir einen Vergleich zu der robusten Regression und der Quantilsregression haben wollen wir hier zu Anfang nochmal schnell die gewöhnliche Regression (eng. <em>ordinary linear regression</em>), die du schon durch die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> kennst. Wir fitten also einmal das Modell mit Interaktionsterm für den Basilikumdatensatz.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_lm_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="anova" class="level3" data-number="48.3.1"><h3 data-number="48.3.1" class="anchored" data-anchor-id="anova">
<span class="header-section-number">48.3.1</span> ANOVA</h3>
<p>Dann schauen wir uns nochmal den Interaktionsplot in <a href="#fig-stat-robust">Abbildung&nbsp;<span>48.3</span></a> mit der Funktion <code>emmip()</code> aus dem R Paket <code>emmeans</code> an. Wir sehen, das wir eventuell eine leichte Interaktion vorliegen haben könnten, da sich einige der Geraden überschneiden.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">emmip</span><span class="op">(</span><span class="va">basi_lm_fit</span>, <span class="va">versuchsgruppe</span> <span class="op">~</span> <span class="va">block</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      cov.reduce <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-stat-robust" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-stat-robust-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;48.3— Interaktionsplot über die Versuchsgruppen und Blöcke.</figcaption></figure>
</div>
</div>
</div>
<p>Schauen wir einmal in eine zweifaktorielle ANOVA, ob sich unser leichter Verdacht validieren lässt.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_lm_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter            | Sum_Squares | df | Mean_Square |     F |      p
----------------------------------------------------------------------
versuchsgruppe       |      158.84 |  3 |       52.95 |  6.53 | &lt; .001
block                |      355.34 |  3 |      118.45 | 14.60 | &lt; .001
versuchsgruppe:block |       83.51 |  9 |        9.28 |  1.14 | 0.346 
Residuals            |      519.20 | 64 |        8.11 |       |       

Anova Table (Type 1 tests)</code></pre>
</div>
</div>
<p>Wir sehen, dass wir mindestens einen paarweisen Unterschied zwischen den Versuchsgruppen und den Blöcken erwarten. Die Interaktion ist nicht signifikant. Betrachten wir noch kurz das <span class="math inline">\(\eta^2\)</span> um zu sehen, wie viel Varianz jeweils die Versuchsgruppe und Blöcke erklären.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_lm_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">eta_squared</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter            | Eta2 (partial) |       95% CI
----------------------------------------------------
versuchsgruppe       |           0.23 | [0.08, 1.00]
block                |           0.41 | [0.24, 1.00]
versuchsgruppe:block |           0.14 | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Leider erklären hier die Blöcke sehr viel der Varianz, das ist nicht so schön, aber in diesem Kapitel lassen wir es dabei.</p>
</section><section id="gruppenvergleich" class="level3" data-number="48.3.2"><h3 data-number="48.3.2" class="anchored" data-anchor-id="gruppenvergleich">
<span class="header-section-number">48.3.2</span> Gruppenvergleich</h3>
<p>Wir haben keine Interaktion vorliegen, alos mitteln wir einmal über alle Blöcke. Wenn du den Code <code>| block</code> zu dem Aufruf der <code>emmeans()</code> Funktion hinzufügst, dann hast du die Analyse für die Blöcke getrennt durchgeführt.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_lm_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span>specs <span class="op">=</span> <span class="op">~</span> <span class="va">versuchsgruppe</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">cld</span><span class="op">(</span>Letters <span class="op">=</span> <span class="va">letters</span>, adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> versuchsgruppe emmean    SE df lower.CL upper.CL .group
 Erde+Fließ       19.4 0.637 64     18.1     20.7  a    
 Erde             19.8 0.637 64     18.5     21.0  a    
 Perlite+Fließ    22.1 0.637 64     20.8     23.3   b   
 Erde+Perlite     22.6 0.637 64     21.4     23.9   b   

Results are averaged over the levels of: block 
Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Wenn wir uns die unadjustierten <span class="math inline">\(p\)</span>-Werte anschauen, dann sehen wir einen leichten Effekt zwischen den einzelnen Versuchsgruppen. Warum sage ich leichten Effekt? Die Mittelwerte der Gruppen in der spalte <code>emmean</code> unterscheiden sich kaum. Aber soviel zu der gewöhnlichen Regression, das war ja hier nur der Vergleich und die Erinnerung.</p>
</section></section><section id="sec-robust-reg" class="level2 page-columns page-full" data-number="48.4"><h2 data-number="48.4" class="anchored" data-anchor-id="sec-robust-reg">
<span class="header-section-number">48.4</span> Robuste Regression</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nur Normalverteilung? Geht auch mehr?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nein es geht auch mit allen anderen Modellen. So ist auch das <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> für die robuste Regression implementiert. Wir schauen uns aber nur die Grundlagen für die klassische robuste Regression unter der Annahme eines nromalverteilten Outcomes an.</p>
</div>
</div>
<p>Bei einer robusten Regression werden jeder Beobachtung auf der Grundlage ihres Residuums unterschiedliche Gewichte (eng. <em>robustness weights</em>) von 0 bis 1 zugewiesen. Wir kennen ja ein Residuum als die Differenz zwischen den beobachteten und den vorhergesagten Werten der Daten. Die vorhergesagten Daten sind ja die Punkte auf der Geraden. Je kleiner also das Residuum ist, desto größer ist die Gewichtung und desto näher liegt eine Beobachtung an der geschätzten Geraden. Wir bestrafen also Punkte, die weit weg von unserer potenziellen Gerade liegen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Ein englisches Tutorium gibt es dann nochmal ausführlicher unter <a href="https://yuzar-blog.netlify.app/posts/2022-09-02-robustregression/">R demo | Robust Regression (don’t depend on influential data!)</a></p>
<p>Ebenso liefert auch das Tutorium <a href="https://stats.oarc.ucla.edu/r/dae/robust-regression/">Robust regression | R data analysis example</a> einen Überblick.</p>
</div></div><p>Schauen wir uns das Problem an einem kleinen Spieldatensatz einmal an, den es so in vielen Geschmacksrichtungen gibt. Wir haben acht Beobachtungen mit jeweils einem <span class="math inline">\(x\)</span> und einem <span class="math inline">\(y\)</span> Wert in unserem Datensatz <code>reg_tbl</code>. Wie folgt einmal dargestellt.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg_tbl</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">7</span><span class="op">)</span>,</span>
<span>                  y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1.4</span>, <span class="fl">2.5</span>, <span class="fl">2.7</span>, <span class="fl">4.3</span>, <span class="fl">5.2</span>, <span class="fl">0</span>, <span class="fl">6.7</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir rechnen jetzt einmal eine gewöhnliche lineare Regression mit der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> und eine robuste Regression mit dem Paket <code>MASS</code> und der Funtkion <code>rlm()</code>. Es gibt noch das R Paket <code>robustbase</code> und der Funktion <code>rq()</code> aber wir können die Ergebnisse dann nicht in <code>emmeans</code> weiter nutzen, was uns dann etwas den Weg mit versperrt. Wir können aber für die multiplen Mittelwertsvergleich mit <code>robustbase</code> das R Paket <code>multcomp</code> nutzen. Aber fangen wir hier erstmal mit dem Beispiel an und vergleichen die beiden Implementierungen der robusten Regression zu der gewöhnlichen Regression</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg_lm_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>, <span class="va">reg_tbl</span><span class="op">)</span></span>
<span><span class="va">reg_rlm_fit</span> <span class="op">&lt;-</span> <span class="fu">rlm</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>, <span class="va">reg_tbl</span><span class="op">)</span></span>
<span><span class="va">reg_lmrob_fit</span> <span class="op">&lt;-</span> <span class="fu">lmrob</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>, <span class="va">reg_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#fig-stat-robust-demo">Abbildung&nbsp;<span>48.4</span></a> sehen wir einmal den Unterschied zwischen den beiden robusten Regressionen und der gewöhnlichen Regression.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">reg_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, label <span class="op">=</span> <span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_label</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reg_lm_fit</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reg_rlm_fit</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"rlm"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reg_lmrob_fit</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"lmrob"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_colour_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"Method"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-stat-robust-demo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-stat-robust-demo-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;48.4— Scatterplot für den Unterschied zwischen einer robusten und gewöhnlichen Regression. Die gewöhnliche Regression ist gelb, die robuste Regression MASS::rlm() grün und die robuste Regression robustbase::lmrob() blau.</figcaption></figure>
</div>
</div>
</div>
<p>In unserem Beispiel ist die sechste Beobachtung der Ausreißer. Die <code>lm</code>-Regression wird durch den Wert 0 der sechsten Beobachtung nach unten gezogen. Die sechste Beobachtung erhält ein viel zu starkes Gewicht in der gewöhnlichen Regression im Bezug auf den Verlauf der Geraden. Die robusten Regressionen geben der sechsten Beobachtung hingegen ein viel geringeres Gewicht, so dass die Beobachtung keinen Einfluss auf den Verlauf der Geraden hat. In einer robusten Regression erhält eine Beobachtung mit einem großen Residuum sehr wenig Gewicht, in diesem konstruierten Beispiel fast 0. Daher können wir sagen, das unser Modell <em>robust</em> gegen Ausreißer ist.</p>
<p>Okay, soweit lernt es jeder und die Idee der robusten Regression ist auch ziemlich einleuchtend. Aber in der Wissenschaft zeichnen wir keine Gerade durch Punkte und freuen uns drüber, dass die eine gerade besser passt als die andere Gerade. Wir nutzen dann ja das Modell weiter in eine ANOVA oder aber eben in einem paarweisen Gruppenvergleich. Und hier fangen dann die Probleme der <em>Implementierung</em> an. Leider ist es so, dass nicht alle Funktionalitäten implementiert sind. Das heißt, die Funktion <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> oder <code>emmeans()</code> kann mit der Ausgabe der robusten Regressionen mit <code><a href="https://rdrr.io/pkg/MASS/man/rlm.html">MASS::rlm()</a></code> und <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob()</a></code> nichts anfangen. Das ist problematisch und nicht anwenderfreundlich. Und wir sind hier nunmal Anwender…</p>
<p>Warum so unbeliebt? Das ist eine gute Frage. Zu der robusten Regression gibt es eine lange Geschichte mit vielen Wirrungen und Irrungen. Am Ende kannst du in Wikipedia noch etwas zur <a href="https://en.wikipedia.org/wiki/Robust_regression#History_and_unpopularity_of_robust_regression">History and unpopularity of robust regression</a> nachlesen. Nach <span class="citation" data-cites="stromberg2004write">Stromberg (<a href="#ref-stromberg2004write" role="doc-biblioref">2004</a>)</span> hat es auch etwas mit der schlechten und mangelhaften Implementierung in gängiger Statistiksoftware zu tun. Das merke ich hier auch gerade, als ich versuche die Funktionen zusammen zubauen und miteinander zu vernetzen. Sicherlich gibt es auch die biologische Diskussion. Gibt es in biologischen Daten eigentlich überhaupt Ausreißer? Oder müssten wir nicht Ausreißer besonders betrachten, weil die Ausreißer dann doch mehr über die Daten verraten? Macht es also Sinn die Ausreißer einfach platt zu bügeln und nicht mehr weiter zu beachten oder ist nicht die Beobachtung Nr.6 oben von Interesse? Denn vielleicht ist was mit dem Experiment schief gelaufen und diese Beobachtung ist gerade ein Anzeichen dafür. Dann müssten auch die anderen Messwerte kritisch hinterfragt werden.</p>
<p>Wie immer es auch sein. Wir fitten jetzt mal die beiden robusten Regression in der Standardausstattung mit der Funktion <code><a href="https://rdrr.io/pkg/MASS/man/rlm.html">MASS::rlm()</a></code> aus dem Paket <code>MASS</code> wie folgt.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_rlm_fit</span> <span class="op">&lt;-</span> <span class="fu">rlm</span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dann natürlich noch die Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob()</a></code> aus dem Paket <code>robustbase</code>. Hinter dem Paket <code>robusbase</code> steht ein ganzen Buch von <span class="citation" data-cites="maronna2019robust">Maronna u.&nbsp;a. (<a href="#ref-maronna2019robust" role="doc-biblioref">2019</a>)</span>, aber leider keine gute Internetseite mit Beispielen und Anwendungen in R, wie es eigentlich heutzutage üblich ist. Aber dennoch, hier einmal das Modell.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_lmrob_fit</span> <span class="op">&lt;-</span> <span class="fu">lmrob</span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="anova-1" class="level3" data-number="48.4.1"><h3 data-number="48.4.1" class="anchored" data-anchor-id="anova-1">
<span class="header-section-number">48.4.1</span> ANOVA</h3>
<p>Dann wollen wir einmal eine zweifaktorielle ANOVA auf den Modell der robusten Regression mit der Funktion <code><a href="https://rdrr.io/pkg/MASS/man/rlm.html">MASS::rlm()</a></code> rechnen. Leider kann ich schon gleich sagen, dass wir hier ein Problem kriegen. Es ist nicht ganz klar unter Theoretikern welche Anzahl an Beobachtungen für die Residuen in der robusten Regression genutzt werden soll. Welche Beobachtungen werden den im Modell berücksichtigt und welche nicht? Daher ist dann der Wert für die Freiheitsgrade <span class="math inline">\(df\)</span> leer und wir erhalten keine <span class="math inline">\(F\)</span>-Statistik und dann auch keine <span class="math inline">\(p\)</span>-Werte. Für mich super unbefriedigend, so kann man dann auch keine Funktionen richtig nutzen. Die Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob()</a></code> bietet die ANOVA nicht an.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_rlm_aov</span> <span class="op">&lt;-</span> <span class="va">basi_rlm_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">basi_rlm_aov</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  term                    df sumsq meansq statistic p.value
  &lt;chr&gt;                &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 versuchsgruppe           3 114.   37.9         NA      NA
2 block                    3 318.  106.          NA      NA
3 versuchsgruppe:block     9  63.7   7.07        NA      NA
4 Residuals               NA 527.   NA           NA      NA</code></pre>
</div>
</div>
<p>Was als Freiheitsgrad für die Residuen nehmen? In unserem Datensatz haben wir 80 Basilikumpflanzen und somit auch Beobachtungen vorliegen. Wir setzen jetzt einfach brutal die Freiheitsgrade <code>df</code> für die Residuen auf 80 und können dann die Mean Squares für die Residuen berechnen. Also einmal flott die <code>meansq</code> für die Residuen durch die Anzahl an Beobachtungen geteilt.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ms_resid</span> <span class="op">&lt;-</span> <span class="fl">527</span> <span class="op">/</span> <span class="fl">80</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mit den Mean Square der Residuen können wir dann auch die <span class="math inline">\(F\)</span>-Werte berechnen. Den rechnerischen Weg kennen wir ja schon aus der zweifaktoriellen ANOVA.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">f_calc</span> <span class="op">&lt;-</span> <span class="va">basi_rlm_aov</span><span class="op">$</span><span class="va">meansq</span> <span class="op">/</span> <span class="va">ms_resid</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wie kriegen wir jetzt aus den ganzen berechneten <span class="math inline">\(F\)</span>-Werten die entsprechenden <span class="math inline">\(p\)</span>-Werte? Die <span class="math inline">\(p\)</span>-Werte sind die Fläche rechts von den berechneten Werten. Wir können die Funktion <code><a href="https://rdrr.io/r/stats/Fdist.html">pf()</a></code> nutzen um diese Flächen zu berechnen. Wir machen das einmal beispielhaft für einen <span class="math inline">\(F_{calc} = 3.41\)</span> für 4 Gruppen mit <span class="math inline">\(df_1 = 4 - 1 = 3\)</span> und 12 Beobachtungen <span class="math inline">\(df_2 = 12\)</span>. Die Berechnung von <span class="math inline">\(df_2\)</span> ist statistisch <em>falsch</em> aber für unseren MacGyver Hack hinreichend.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">pf</a></span><span class="op">(</span><span class="fl">3.41</span>, <span class="fl">3</span>, <span class="fl">12</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.053</code></pre>
</div>
</div>
<p>Und siehe da, wir erhalten einen <span class="math inline">\(p\)</span>-Wert von <span class="math inline">\(0.053\)</span>. Nun können wir das nicht nur für einzelnen <span class="math inline">\(F\)</span>-Werte machen sondern auch für unseren ganzen Vektor <code>f_calc</code>. Als <span class="math inline">\(df_2\)</span> setzen wir die Anzahl an Basilikumpflanzen.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p_vec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">pf</a></span><span class="op">(</span><span class="va">f_calc</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">9</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">80</span>, <span class="fl">80</span>, <span class="fl">80</span><span class="op">)</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pvalue_format.html">pvalue</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die berechneten <span class="math inline">\(F\)</span>-Werte und <span class="math inline">\(p\)</span>-Werte können wir jetzt in die ANOVA Tabelle ergänzen.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_rlm_aov</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>statistic <span class="op">=</span> <span class="va">f_calc</span>, </span>
<span>         p.value <span class="op">=</span> <span class="va">p_vec</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  term                    df sumsq meansq statistic p.value
  &lt;chr&gt;                &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  
1 versuchsgruppe           3 114.   37.9       5.75 0.001  
2 block                    3 318.  106.       16.1  &lt;0.001 
3 versuchsgruppe:block     9  63.7   7.07      1.07 0.391  
4 Residuals               NA 527.   NA        NA    &lt;NA&gt;   </code></pre>
</div>
</div>
<p>Das war jetzt ein ganz schöner Angang und den <span class="math inline">\(p\)</span>-Werten ist nur approximativ zu trauen, aber wenn wir weit vom Signifikanzniveau <span class="math inline">\(\alpha\)</span> gleich 5% sind, dann macht eine numerische Ungenauigkeit auch nicht viel aus. Achtung deshalb bei <span class="math inline">\(p\)</span>-Werten nahe des Signifikanzniveau <span class="math inline">\(\alpha\)</span>, hier ist dann die Aussage mit Vorsicht zu treffen oder eher nicht möglich.</p>
<p>Glücklicherweise können wir aus den Sum of squares dann unsere <span class="math inline">\(\eta^2\)</span>-Werte für die erklärte Varianz unserer ANOVA berechnen. Das ist dann doch schon mal was. Wir sehen, dass die Blöcke am meisten der Varianz erklären und die Versuchsgruppen sehr wenig. Das ist für das Modell dann nicht so schön, deckt sich aber mit den Ergebnissen gewöhnlichen Regression. Wir erhalten eine Konfidenzintervalle, woran du schon erkennen kannst, dass in der Ausgabe der ANOVA der robusten Regression was fehlt.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_rlm_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">eta_squared</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter            | Eta2 (partial) |    95% CI
-------------------------------------------------
versuchsgruppe       |           0.18 | [ , 1.00]
block                |           0.38 | [ , 1.00]
versuchsgruppe:block |           0.11 | [ , 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Nochmal als Erinnerung, mit der Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob()</a></code> ist die ANOVA nicht möglich. Die Funktionalität ist nicht implementiert.</p>
</section><section id="gruppenvergleich-1" class="level3" data-number="48.4.2"><h3 data-number="48.4.2" class="anchored" data-anchor-id="gruppenvergleich-1">
<span class="header-section-number">48.4.2</span> Gruppenvergleich</h3>
<p>Dafür geht der Gruppenvergleich für die robuste Regression mit <code><a href="https://rdrr.io/pkg/MASS/man/rlm.html">MASS::rlm()</a></code> wie von alleine. Wir haben keine Interaktion vorliegen, daher müssen wir auch nicht den Block berücksichtigen. Das wir in Block 1 ein Problem haben, steht dann aber auf einem anderen Blatt. Da aber <em>alle</em> Basilikumpflanzen immer im Block 1 kleiner sind, passt es dann wieder im Sinne keiner Interaktion. Mit Interaktion hätten wir sonst <code>versuchsgruppe | block</code> statt nur <code>versuchsgruppe</code> hinter die Tilde geschrieben. Dann wollen wir noch das <em>compact letter disply</em> und alles ist wie es sein sollte.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_rlm_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span>specs <span class="op">=</span> <span class="op">~</span> <span class="va">versuchsgruppe</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">cld</span><span class="op">(</span>Letters <span class="op">=</span> <span class="va">letters</span>, adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> versuchsgruppe emmean    SE df asymp.LCL asymp.UCL .group
 Erde+Fließ       19.7 0.668 NA      18.4      21.0  a    
 Erde             19.9 0.668 NA      18.6      21.2  a    
 Perlite+Fließ    22.2 0.668 NA      20.9      23.5   b   
 Erde+Perlite     22.4 0.668 NA      21.1      23.7   b   

Results are averaged over the levels of: block 
Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Wir sehen also, dass sich Erde+Fließ und Erde nicht unterscheiden. Die beiden aber dann von Perlite+Fließ sowie Erde+Perlite. Am Ende unterscheiden sich Perlite+Fließ und Erde+Perlite nicht.</p>
<p>Für die Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob()</a></code> müssen wir dann auf das R Paket <code>multcomp</code> umswitchen. Hier kriegen wir dann ein Problem, wenn wir eine Interaktion vorliegen ahben, da ist <code>multcomp</code> nicht so schön anzuwenden, wie dann <code>emmeans</code>. Aber hier schauen wir uns dann mal die einfache Implementierung ohne Interaktion an. Bei einer Interaktion müssten wir dann händisch über die Funktion <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> die Analysen für die einzelnen Blöcke aufspalten.</p>
<p>Wir lassen jetzt aber erstmal auf dem Modell aus der Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob()</a></code> den paarweisen Vergleich nach Tukey laufen.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mult_lmrob</span> <span class="op">&lt;-</span> <span class="fu">glht</span><span class="op">(</span><span class="va">basi_lmrob_fit</span>, linfct <span class="op">=</span> <span class="fu">mcp</span><span class="op">(</span>versuchsgruppe <span class="op">=</span> <span class="st">"Tukey"</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das erhaltende Objekt können wir dann mit <code>tidy()</code> aufräumen und uns dann die gewünschten Spalten wiedergeben lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mult_lmrob_tbl</span> <span class="op">&lt;-</span> <span class="va">mult_lmrob</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">contrast</span>, <span class="va">estimate</span>, <span class="va">conf.low</span>, <span class="va">conf.high</span>, <span class="va">adj.p.value</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">mult_lmrob_tbl</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  contrast                     estimate conf.low conf.high adj.p.value
  &lt;chr&gt;                           &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1 Erde+Fließ - Erde              1.68      -1.79      5.14       0.592
2 Erde+Perlite - Erde            1.63      -2.38      5.64       0.717
3 Perlite+Fließ - Erde           4.84      -1.35     11.0        0.181
4 Erde+Perlite - Erde+Fließ     -0.0439    -2.86      2.78       1.00 
5 Perlite+Fließ - Erde+Fließ     3.17      -2.52      8.85       0.474
6 Perlite+Fließ - Erde+Perlite   3.21      -2.79      9.21       0.509</code></pre>
</div>
</div>
<p>Wir sehen, dass wir mit der Adjustierung keinen signifikanten Unterschied zwischen den Bodensorten finden. Im Folgenden dann noch die Darstellung im <em>compact letter display</em>, wo wir etwas rumfrickeln müssen damit die Funktion <code>multcompLetters()</code> auch die Kontraste aus der Funktion <code>glht()</code> akzeptiert. Aber das haben wir dann alles zusammen.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mult_lmrob_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>contrast <span class="op">=</span> <span class="fu">str_replace_all</span><span class="op">(</span><span class="va">contrast</span>, <span class="st">"\\s"</span>, <span class="st">""</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pull</span><span class="op">(</span><span class="va">adj.p.value</span>, <span class="va">contrast</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">multcompLetters</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="st">"Letters"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Erde+Fließ  Erde+Perlite Perlite+Fließ          Erde 
          "a"           "a"           "a"           "a" </code></pre>
</div>
</div>
<p>Auch hier sehen wir keinen Unterschied im <em>compact letter display</em> für die adjustierten <span class="math inline">\(p\)</span>-Werte. Für die unadjustierten rohen <span class="math inline">\(p\)</span>-Werte nutzen wir dann den Umweg über die <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> Funktion. Die unadjustierten <span class="math inline">\(p\)</span>-Werte können wir dann auch in das <em>compact letter display</em> umwandeln lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mult_lmrob</span>, test <span class="op">=</span> <span class="fu">adjusted</span><span class="op">(</span><span class="st">"none"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>contrast <span class="op">=</span> <span class="fu">str_replace_all</span><span class="op">(</span><span class="va">contrast</span>, <span class="st">"\\s"</span>, <span class="st">""</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pull</span><span class="op">(</span><span class="va">p.value</span>, <span class="va">contrast</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">multcompLetters</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="st">"Letters"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Erde+Fließ  Erde+Perlite Perlite+Fließ          Erde 
         "ab"          "ab"           "a"           "b" </code></pre>
</div>
</div>
<p>Und wenn man eine andere Funktion nutzt, dann kommen auch leicht andere Ergebnisse raus. Bei den rohen <span class="math inline">\(p\)</span>-Werten haben wir jetzt etwas andere Unterschiede. Aber das liegt auch an den sehr ähnlichen Mittelwerten. So groß sind die Unterschiede nicht, so dass wir hier natürlich durch unterschiedliche Algorithmen leicht andere Ergebnisse kriegen. Wieder ein Grund die <span class="math inline">\(p\)</span>-Werte zu adjustieren um dann auch konsistente Ergebnisse zu haben.</p>
</section></section><section id="sec-quantile-reg" class="level2 page-columns page-full" data-number="48.5"><h2 data-number="48.5" class="anchored" data-anchor-id="sec-quantile-reg">
<span class="header-section-number">48.5</span> Quantilsregression</h2>
<p>Jetzt wollen wir uns als Spezialfall der robusten Regression einmal die Quantilesregression anschauen. Wir der Name schon sagt, optimiert die Quantilregression nicht über den Mittelwert und die Standardabweichung als quadratische Abweichungen sondern über den Median und die absoluten Abweichungen. Wir haben es also hier mit einer Alternativen zu der gewöhnlichen Regression zu tun. Das schöne an der Quantilesregression ist, dass der Median nicht so anfällig gegenüber Ausreißern ist. Hier haben wir einen Vorteil. Wir können theoretisch auch andere Quantile als Referenzwert nehmen und die absoluten Abstände berechnen. Wenn wir aber später dann mit <code>emmeans</code> die Gruppenvergleiche rechnen wollen, geht das nur über den Median.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Ein englisches Tutorium gibt es dann nochmal ausführlicher unter <a href="https://yuzar-blog.netlify.app/posts/2022-12-01-quantileregression/">Quantile Regression as an useful Alternative for Ordinary Linear Regression</a></p>
</div></div><p>Um die Quantilesregression zu rechnen nutzen wir das R Paket <code>quantreg</code> und die Funktion <code>rq()</code>. Wichtig ist hier, dass wir das <code>tau</code> auf <span class="math inline">\(0.5\)</span> setzen und somit dann eine Median-Regression rechnen. Wir können theoretisch auch andere Quantile als Referenz wählen, aber dann passt es nicht mehr mit <code>emmeans()</code>. Wir nutzen hier auch nochmal die Gelegenheit zwei Modelle mit anzupassen. Wir rechnen einmal ein Modell mit einer linearen Komponente der Zeit <code>time_num</code> und einmal ein Modell mit der quadratischen Komponente der Zeit mit <code>poly(time_num, 2)</code> was nicht anderes als <code>time_num</code><span class="math inline">\(^2\)</span> ist. Neben dieser Variante ist mit <code>nlrq()</code> auch eine Möglichkeit implementiert um noch komplexere nicht lineare Zusammenhänge zu modellieren. Hier dann einfach mal die Hilfeseite von <code>?nlrq</code> anschauen.</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">time_rq_lin_fit</span> <span class="op">&lt;-</span> <span class="fu">rq</span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">time_num</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">time_num</span>, tau <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>                      <span class="va">gurke_time_len_tbl</span><span class="op">)</span></span>
<span><span class="va">time_rq_quad_fit</span> <span class="op">&lt;-</span> <span class="fu">rq</span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span><span class="op">(</span><span class="va">time_num</span>, <span class="fl">2</span><span class="op">)</span>, tau <span class="op">=</span> <span class="fl">0.5</span>, </span>
<span>                       <span class="va">gurke_time_len_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#fig-robust-gurke-01">Abbildung&nbsp;<span>48.5</span></a> plotten wir einmal die Modelle aus der linearen und der quadratischen Anpassung des zeitlichen Verlaufs in die Abbildung. Wir sehen, dass das Modell mit der quadratischen Anpassung besser zu den Daten passt. Daher nutzen wir jetzt im weiteren das Modell <code>time_rq_quad_fit</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">gurke_time_len_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">time_num</span>, <span class="va">length</span>, color <span class="op">=</span> <span class="va">versuchsgruppe</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point2</span><span class="op">(</span>position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">time_rq_quad_fit</span><span class="op">)</span>, linetype <span class="op">=</span> <span class="st">"Quadratic"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">time_rq_lin_fit</span><span class="op">)</span>, linetype <span class="op">=</span> <span class="st">"Linear"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">14</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>linetype <span class="op">=</span> <span class="st">""</span>, color <span class="op">=</span> <span class="st">""</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-robust-gurke-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-robust-gurke-01-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Abbildung&nbsp;48.5— Scatterplot des Längenwachstums der drei Gurkensorten über vierzehn Wochen. Die gestrichtelten Linien stellen den Median und die durchgezogene Line den Mittelwert der Gruppen dar.</figcaption></figure>
</div>
</div>
</div>
<section id="anova-2" class="level3" data-number="48.5.1"><h3 data-number="48.5.1" class="anchored" data-anchor-id="anova-2">
<span class="header-section-number">48.5.1</span> ANOVA</h3>
<p>Machen wir es kurz. Die ANOVA ist für die Quantilsregression nicht implementiert und damit auch nicht anwendbar. Damit können wir aber leben, wenn wir die ANOVA nur als Vortest ansehen. Wir müssen dann eine mögliche Interaktion visuell überprüfen. Um die Interaktion visuell zu überprüfen nutzen wir die Funktion <code>emimp()</code> aus dem R Paket <code>emmeans</code>. Wir sehen in der <a href="#fig-rob-inter-time">Abbildung&nbsp;<span>48.6</span></a>, dass sich die Gerade für die Versuchsgruppen über die Zeit nicht schneiden, was gegen eine starke Interaktion spricht. Die Steigung ist aber für alle drei Versuchsgruppen über die Zeit nicht gleich, wir haben zumindest eine mittlere Interaktion.</p>
<div>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">emmip</span><span class="op">(</span><span class="va">time_rq_lin_fit</span>, <span class="va">versuchsgruppe</span> <span class="op">~</span> <span class="va">time_num</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      cov.reduce <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">emmip</span><span class="op">(</span><span class="va">time_rq_quad_fit</span>, <span class="va">versuchsgruppe</span> <span class="op">~</span> <span class="va">time_num</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      cov.reduce <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_okabeito</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-rob-inter-time" class="cell quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-rob-inter-time-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-rob-inter-time-1.png" class="img-fluid figure-img" data-ref-parent="fig-rob-inter-time" width="480"></p>
<figcaption class="figure-caption">(a) Linear</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-rob-inter-time-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-robust-quantile_files/figure-html/fig-rob-inter-time-2.png" class="img-fluid figure-img" data-ref-parent="fig-rob-inter-time" width="480"></p>
<figcaption class="figure-caption">(b) Quadratic</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;48.6— Interaktionsplot über den zeitlichen Verlauf für alle drei Sorten für die Quantilesregression.</figcaption><p></p>
</figure>
</div>
</div>
<p>Wir würden also in unseren Gruppenvergleich der Mediane auf jeden Fall die Interaktion mit rein nehmen und die <code>emmeans()</code> Funktion entsprechend mit dem <code>|</code> anpassen.</p>
</section><section id="gruppenvergleich-2" class="level3" data-number="48.5.2"><h3 data-number="48.5.2" class="anchored" data-anchor-id="gruppenvergleich-2">
<span class="header-section-number">48.5.2</span> Gruppenvergleich</h3>
<p>Wenn wir den Gruppenvergleich in <code>emmeans()</code> rechnen wollen, dann geht es nur dem Spezialfall der Median-Regression. Wir müssen also zwangsweise in der Quantilesregression <code>rq()</code> das <code>tau = 0.5</code> setzen um dann eine Median-Regression zu rechnen. Sonst können wir nicht <code>emmeans</code> nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">time_rq_quad_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">|</span> <span class="va">time_num</span>, </span>
<span>          adjust <span class="op">=</span> <span class="st">"none"</span>, at <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>time_num <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">7</span>, <span class="fl">14</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">cld</span><span class="op">(</span>Letters <span class="op">=</span> <span class="va">letters</span>, adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>time_num =  1:
 versuchsgruppe emmean     SE  df lower.CL upper.CL .group
 Quarto           2.30 0.0513 243     2.20     2.40  a    
 Katrina          3.30 0.2879 243     2.73     3.87   b   
 Proloog          5.00 0.2243 243     4.56     5.44    c  

time_num =  7:
 versuchsgruppe emmean     SE  df lower.CL upper.CL .group
 Quarto           3.83 0.2467 243     3.35     4.32  a    
 Katrina          5.20 0.3184 243     4.57     5.83   b   
 Proloog         11.97 0.2938 243    11.39    12.55    c  

time_num = 14:
 versuchsgruppe emmean     SE  df lower.CL upper.CL .group
 Quarto           7.30 1.7815 243     3.79    10.81  a    
 Katrina         11.36 3.1038 243     5.25    17.47  a    
 Proloog         30.06 1.6609 243    26.79    33.34   b   

Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Das sieht ja schon mal ganz gut aus. Interessant ist, dass wir an dann in der vierzehnten Woche dann keinen signifikanten Unterschied mehr vorliegen zwischen Quarto und Katrina vorliegen haben. Das liegt dann aber alleinig an dem hohen Standardfehler <code>SE</code> der Sorte Katrina mit <span class="math inline">\(3.1\)</span> gegenüber den anderen Sorten. Vermutlich sehe das Ergebnis leicht anders aus, wenn wir die unsinnigen Gurken mit einer Länge von 0 cm wirklich aus den Dten entfernen würden und nicht zu Demonstrationszwecken wie hier drin lassen würden.</p>
<p>Aber Achtung, die Spalte <code>emmean</code> beschriebt hier die Mediane. Wir haben also hier die Mediane des Längenwachstums für die Gurken vorliegen. Wenn wir die paarweisen Vergleich rechnen wollen würden dann können wir noch <code>pairwise ~ versuchsgruppe</code> statt <code>~ versuchsgruppe</code> schreiben. Auch liefert die Funktion <code>pwpm()</code> die Medianunterschiede wie wir im Folgenden einmal sehen. Ich habe hier mal das <code>at</code> entfernt und da die Zeit numrisch ist, haben wir dann auch nur noch eine Tabelle. Die <code>Diagonal: [Estimates] (emmean)</code> sind die Mediane des Längenwachstums.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">time_rq_quad_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">|</span> <span class="va">time_num</span>, adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">pwpm</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Katrina Proloog  Quarto
Katrina [ 5.50]  &lt;.0001  0.0095
Proloog   -7.41 [12.91]  &lt;.0001
Quarto     1.48    8.89 [ 4.02]

Row and column labels: versuchsgruppe
Upper triangle: P values   adjust = "tukey"
Diagonal: [Estimates] (emmean) 
Lower triangle: Comparisons (estimate)   earlier vs. later</code></pre>
</div>
</div>
</section></section><section id="modellvergleich" class="level2" data-number="48.6"><h2 data-number="48.6" class="anchored" data-anchor-id="modellvergleich">
<span class="header-section-number">48.6</span> Modellvergleich</h2>
<p>Im Folgenden wollen wir einmal verschiedene Modelle miteinander vergleichen und schauen, welches Modell hier das beste ist. Das machen wir dann einmal für die Basilikumdaten sowie die Wachstumsdaten für die Gurken.</p>
<section id="basilikumdaten" class="level3" data-number="48.6.1"><h3 data-number="48.6.1" class="anchored" data-anchor-id="basilikumdaten">
<span class="header-section-number">48.6.1</span> Basilikumdaten</h3>
<p>Für den Modellvergleich der gewöhnlichen, robusten und medianen Regression nutzen wir nochmal den Datensatz für das Basilikumwachstum. In einem ersten Schritt fitten wir wieder alle Modelle und achten darauf, dass wir bei der Quantilesregression angeben welches Quantile wir wollen. Wir wählen mit <code>tau = 0.5</code> dann den Median und rechnen so eine Medianregression.</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">basi_lm_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span><span class="op">)</span></span>
<span><span class="va">basi_rlm_fit</span> <span class="op">&lt;-</span> <span class="fu">rlm</span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span><span class="op">)</span></span>
<span><span class="va">basi_lmrob_fit</span> <span class="op">&lt;-</span> <span class="fu">lmrob</span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span><span class="op">)</span></span>
<span><span class="va">basi_rq_fit</span> <span class="op">&lt;-</span> <span class="fu">rq</span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">block</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">block</span>, <span class="va">basi_block_tbl</span>,</span>
<span>                  tau <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Im Folgenden nutzen wir dann das fantastische Paket <code>modelsummary</code> mit der gleichnamigen Funktion um uns einmal die Modelle im Vergleich anzuschauen. Hier hilft dann wie immer die tolle <a href="https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html">Hilfsseite von modelsummary</a> zu besuchen. Ich möchte nur nicht den Intercept und die Schätzer für die Blöcke haben, deshalb fliegen die hier einmal raus.</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">modelsummary</span><span class="op">(</span><span class="fu">lst</span><span class="op">(</span><span class="st">"Ordinary"</span> <span class="op">=</span> <span class="va">basi_lm_fit</span>,</span>
<span>                 <span class="st">"MASS::rlm"</span> <span class="op">=</span> <span class="va">basi_rlm_fit</span>,</span>
<span>                 <span class="st">"robustbase::lmrob"</span> <span class="op">=</span> <span class="va">basi_lmrob_fit</span>,</span>
<span>                 <span class="st">"Quantile"</span> <span class="op">=</span> <span class="va">basi_rq_fit</span><span class="op">)</span>,</span>
<span>             estimate  <span class="op">=</span> <span class="st">"{estimate}"</span>,</span>
<span>             statistic <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"conf.int"</span>,</span>
<span>                           <span class="st">"s.e. = {std.error}"</span>, </span>
<span>                           <span class="st">"t = {statistic}"</span>,</span>
<span>                           <span class="st">"p = {p.value}"</span><span class="op">)</span>,</span>
<span>             coef_omit <span class="op">=</span> <span class="st">"Intercept|block"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Ordinary</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">MASS::rlm</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">robustbase::lmrob</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Quantile</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">versuchsgruppeErde+Fließ</td>
<td style="text-align: center;">2.200</td>
<td style="text-align: center;">1.515</td>
<td style="text-align: center;">1.680</td>
<td style="text-align: center;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[−1.399, 5.799]</td>
<td style="text-align: center;">[−2.257, 5.286]</td>
<td style="text-align: center;">[−1.053, 4.413]</td>
<td style="text-align: center;">[−0.374, 2.374]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 1.801</td>
<td style="text-align: center;">s.e. = 1.888</td>
<td style="text-align: center;">s.e. = 1.368</td>
<td style="text-align: center;">s.e. = 0.701</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = 1.221</td>
<td style="text-align: center;">t = 0.802</td>
<td style="text-align: center;">t = 1.228</td>
<td style="text-align: center;">t = 1.426</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">p = 0.226</td>
<td style="text-align: center;">p = 0.425</td>
<td style="text-align: center;">p = 0.224</td>
<td style="text-align: center;">p = 0.159</td>
</tr>
<tr class="even">
<td style="text-align: left;">versuchsgruppeErde+Perlite</td>
<td style="text-align: center;">2.200</td>
<td style="text-align: center;">1.515</td>
<td style="text-align: center;">1.636</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">[−1.399, 5.799]</td>
<td style="text-align: center;">[−2.257, 5.286]</td>
<td style="text-align: center;">[−1.526, 4.799]</td>
<td style="text-align: center;">[−3.073, 3.073]</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 1.801</td>
<td style="text-align: center;">s.e. = 1.888</td>
<td style="text-align: center;">s.e. = 1.583</td>
<td style="text-align: center;">s.e. = 1.568</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = 1.221</td>
<td style="text-align: center;">t = 0.802</td>
<td style="text-align: center;">t = 1.034</td>
<td style="text-align: center;">t = 0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">p = 0.226</td>
<td style="text-align: center;">p = 0.425</td>
<td style="text-align: center;">p = 0.305</td>
<td style="text-align: center;">p = 1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">versuchsgruppePerlite+Fließ</td>
<td style="text-align: center;">5.200</td>
<td style="text-align: center;">4.683</td>
<td style="text-align: center;">4.843</td>
<td style="text-align: center;">6.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[1.601, 8.799]</td>
<td style="text-align: center;">[0.911, 8.455]</td>
<td style="text-align: center;">[−0.027, 9.714]</td>
<td style="text-align: center;">[1.045, 10.955]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 1.801</td>
<td style="text-align: center;">s.e. = 1.888</td>
<td style="text-align: center;">s.e. = 2.438</td>
<td style="text-align: center;">s.e. = 2.528</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = 2.887</td>
<td style="text-align: center;">t = 2.480</td>
<td style="text-align: center;">t = 1.987</td>
<td style="text-align: center;">t = 2.373</td>
</tr>
<tr class="odd">
<td style="text-align: left; box-shadow: 0px 1px;"></td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.005</td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.016</td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.051</td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.021</td>
</tr>
<tr class="even">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.535</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.501</td>
<td style="text-align: center;">0.480</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.426</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.384</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">410.7</td>
<td style="text-align: center;">411.8</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">404.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">451.1</td>
<td style="text-align: center;">452.3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">442.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">−188.326</td>
<td style="text-align: center;">−188.914</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: center;">4.912</td>
<td style="text-align: center;">3.903</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">RMSE</td>
<td style="text-align: center;">2.55</td>
<td style="text-align: center;">2.57</td>
<td style="text-align: center;">2.55</td>
<td style="text-align: center;">2.69</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Wie wir sehen sehen haben nicht alle Modelle die gleichen Informationen zurück gegeben. Insbesondere das fehlen des Bestimmtheitsmaßes <span class="math inline">\(R^2\)</span> bei der robusten Regression <code><a href="https://rdrr.io/pkg/MASS/man/rlm.html">MASS::rlm</a></code> ist schmerzlich, da wir hier dann nicht die Möglichkeit haben eine Aussage über die erklärte Varianz der robusten Regression zu treffen. Auch fehlt bei der Medianregression das adjustierte <span class="math inline">\(R^2\)</span>, was die Nutzung bei Modellen mit mehr als einer Einflussvariable <span class="math inline">\(x\)</span> im Modell erschwert bis nutzlos macht. Da ist dann die Funktion aus dem Paket <code>robustbase</code> besser, hier haben wir dann ein <span class="math inline">\(R^2\)</span> vorliegen. Daher bleibt uns am Ende nur das AIC oder BIC, wobei wir dort den kleinsten Wert als besser erachten. Die AIC und BIC Werte sind somit am besten für die Quantilesregression. Für die Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob</a></code> haben wir dann kein AIC. Dafür ist dann aber der Fehler RMSE bei der gewöhnlichen Regressionzusammen mit der Funktion <code><a href="https://rdrr.io/pkg/robustbase/man/lmrob.html">robustbase::lmrob</a></code> am niedrigsten. Und so stehe ich wieder davor und weiß nicht was das beste Modell ist. Hier müsste ich dann nochmal überlegen, ob ich lieber über Mittelwerte oder Mediane berichten möchte und das ist ohne die Forschungsfrage nicht hier zu lösen.</p>
</section><section id="gurkendaten" class="level3" data-number="48.6.2"><h3 data-number="48.6.2" class="anchored" data-anchor-id="gurkendaten">
<span class="header-section-number">48.6.2</span> Gurkendaten</h3>
<p>Für den Modellvergleich der gewöhnlichen, robusten und medianen Regression nutzen wir nochmal den Datensatz für das Längenwachstum der Gurken. In einem ersten Schritt fitten wir wieder alle Modelle und achten darauf, dass wir bei der Quantilesregression angeben welches Quantile wir wollen. Wir wählen mit <code>tau = 0.5</code> dann den Median und rechnen so eine Median-Regression. Darüber hinaus schauen wir uns nochmal die quadratische Anpassung der Zeit in dem letzten Modell an. Mal schauen, ob das Modell dann auch bei den Kennzahlen das beste Modell ist. Visuell sah das quadratische Modell des zeitlichen Verlaufs schon mal sehr gut aus.</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">time_lm_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">time_num</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">time_num</span>, <span class="va">gurke_time_len_tbl</span><span class="op">)</span></span>
<span><span class="va">time_rlm_fit</span> <span class="op">&lt;-</span> <span class="fu">rlm</span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">time_num</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">time_num</span>, <span class="va">gurke_time_len_tbl</span><span class="op">)</span></span>
<span><span class="va">time_rq_lin_fit</span> <span class="op">&lt;-</span> <span class="fu">rq</span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">+</span> <span class="va">time_num</span> <span class="op">+</span> <span class="va">versuchsgruppe</span><span class="op">:</span><span class="va">time_num</span>, tau <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>                      <span class="va">gurke_time_len_tbl</span><span class="op">)</span></span>
<span><span class="va">time_rq_quad_fit</span> <span class="op">&lt;-</span> <span class="fu">rq</span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">versuchsgruppe</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span><span class="op">(</span><span class="va">time_num</span>, <span class="fl">2</span><span class="op">)</span>, tau <span class="op">=</span> <span class="fl">0.5</span>, </span>
<span>                       <span class="va">gurke_time_len_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Auch hier nutzen wir dann das fantastische Paket <code>modelsummary</code> mit der gleichnamigen Funktion um uns einmal die Modelle im Vergleich anzuschauen.</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">modelsummary</span><span class="op">(</span><span class="fu">lst</span><span class="op">(</span><span class="st">"Ordinary"</span> <span class="op">=</span> <span class="va">time_lm_fit</span>,</span>
<span>                 <span class="st">"Robust"</span> <span class="op">=</span> <span class="va">time_rlm_fit</span>,</span>
<span>                 <span class="st">"Quantile linear"</span> <span class="op">=</span> <span class="va">time_rq_lin_fit</span>,</span>
<span>                 <span class="st">"Quantile quadratic"</span> <span class="op">=</span> <span class="va">time_rq_quad_fit</span><span class="op">)</span>,</span>
<span>             estimate  <span class="op">=</span> <span class="st">"{estimate}"</span>,</span>
<span>             statistic <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"conf.int"</span>,</span>
<span>                           <span class="st">"s.e. = {std.error}"</span>, </span>
<span>                           <span class="st">"t = {statistic}"</span>,</span>
<span>                           <span class="st">"p = {p.value}"</span><span class="op">)</span>,</span>
<span>             coef_omit <span class="op">=</span> <span class="st">"Intercept|time_num"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Ordinary</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Robust</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Quantile linear</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Quantile quadratic</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">versuchsgruppeProloog</td>
<td style="text-align: center;">−0.218</td>
<td style="text-align: center;">−1.028</td>
<td style="text-align: center;">−0.823</td>
<td style="text-align: center;">8.483</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[−3.056, 2.619]</td>
<td style="text-align: center;">[−2.693, 0.638]</td>
<td style="text-align: center;">[−2.852, 1.206]</td>
<td style="text-align: center;">[6.612, 10.353]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 1.440</td>
<td style="text-align: center;">s.e. = 0.846</td>
<td style="text-align: center;">s.e. = 1.035</td>
<td style="text-align: center;">s.e. = 0.954</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = −0.152</td>
<td style="text-align: center;">t = −1.215</td>
<td style="text-align: center;">t = −0.795</td>
<td style="text-align: center;">t = 8.890</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">p = 0.880</td>
<td style="text-align: center;">p = 0.225</td>
<td style="text-align: center;">p = 0.427</td>
<td style="text-align: center;">p =</td>
</tr>
<tr class="even">
<td style="text-align: left;">versuchsgruppeQuarto</td>
<td style="text-align: center;">−0.412</td>
<td style="text-align: center;">−0.641</td>
<td style="text-align: center;">−0.986</td>
<td style="text-align: center;">−1.883</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">[−3.249, 2.426]</td>
<td style="text-align: center;">[−2.307, 1.025]</td>
<td style="text-align: center;">[−3.045, 1.074]</td>
<td style="text-align: center;">[−3.817, 0.050]</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">s.e. = 1.440</td>
<td style="text-align: center;">s.e. = 0.846</td>
<td style="text-align: center;">s.e. = 1.051</td>
<td style="text-align: center;">s.e. = 0.986</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">t = −0.286</td>
<td style="text-align: center;">t = −0.758</td>
<td style="text-align: center;">t = −0.938</td>
<td style="text-align: center;">t = −1.909</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1px;"></td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.775</td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.449</td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.349</td>
<td style="text-align: center; box-shadow: 0px 1px;">p = 0.057</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">252</td>
<td style="text-align: center;">252</td>
<td style="text-align: center;">252</td>
<td style="text-align: center;">252</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.581</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.548</td>
<td style="text-align: center;">0.537</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.572</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">1472.0</td>
<td style="text-align: center;">1488.9</td>
<td style="text-align: center;">1345.9</td>
<td style="text-align: center;">1316.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">1496.7</td>
<td style="text-align: center;">1513.6</td>
<td style="text-align: center;">1367.1</td>
<td style="text-align: center;">1348.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">−729.020</td>
<td style="text-align: center;">−737.435</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">68.209</td>
<td style="text-align: center;">269.196</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE</td>
<td style="text-align: center;">4.37</td>
<td style="text-align: center;">4.51</td>
<td style="text-align: center;">4.53</td>
<td style="text-align: center;">4.59</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Hier sieht es ähnlich aus wie bei den Modellvergleichen von den Basilikumdaten. Nur hier wissen wir, dass wir Ausreißer in der Form von Gurken mit einer Länge von 0 cm in den Daten haben. Daher sehen wir auch, dass die robuste Regression und die Median-Regression ein niedrigeres AIC und BIC haben. Für mich interessant ist, dass der Fehler RMSE wieder am kleinsten bei der gewöhnlichen Regression ist, das mag aber auch an der Berechnung liegen. Da wir Ausreißer haben, sind natürlich dann auch die robuste Regression und die Median-Regression vorzuziehen. Da die Median-Regression den kleineren AIC Wert hat, nehmen wir dann die Median-Regression als die beste Regression an. Der RMSE ist am kleinsten für die quadratische Anpassung des zeitlichen Verlaufs. Deshalb wäre dann das vierte Modell mit dem niedrigsten AIC und dem niedrigsten RMSE das Modell der Wahl.</p>
<p>Ich wiederhole mich hier wirklich, aber vermutlich wäre es schlauer zuerst die Daten zu bereinigen und die Gurken mit einem Wachstum von 0 cm zu entfernen. Auch die anderen Wachstumskurven von anderen Gurken sind etwas wirr. Da müsste man auch nochmal ran und schauen, ob nicht die Gurken lieber aus der Analyse raus müssen. Am Ende ist dann natürlich die Frage, ob man die Daten dann nicht doch lieber über ein gemischtes Modell auswertet, da natürlich die Zeitpunkte voneinander abhängig sind, wenn wir immer die glecihen Gurken messen und nicht ernten. Aber wie immer im Leben, alles geht nicht.</p>
</section></section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-maronna2019robust" class="csl-entry" role="listitem">
Maronna, Ricardo A, R Douglas Martin, Victor J Yohai, und Matı́as Salibián-Barrera. 2019. <em>Robust statistics: theory and methods (with R)</em>. John Wiley &amp; Sons.
</div>
<div id="ref-stromberg2004write" class="csl-entry" role="listitem">
Stromberg, Arnold. 2004. <span>„Why write statistical software? The case of robust statistical methods“</span>. <em>Journal of Statistical Software</em> 10: 1–8.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-modeling-non-linear.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-survival.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>