<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Ein Kochbuch mit Rezepten der Bio Data Science, Biostatistik, Biometrie und Statistik">

<title>Bio Data Science - 21&nbsp; Der Effektschätzer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-tests-pretest.html" rel="next">
<link href="./stat-tests-theorie.html" rel="prev">
<link href="./cover2024_favi.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Bio Data Science - 21&nbsp; Der Effektschätzer">
<meta property="og:description" content="Ein Kochbuch mit Rezepten der Bio Data Science, Biostatistik, Biometrie und Statistik">
<meta property="og:image" content="https://github.com/jkruppa/jkruppa.github.io/raw/master/cover2024.png">
<meta property="og:site_name" content="Bio Data Science">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-tests-preface-theory.html">Testen von Hypothesen</a></li><li class="breadcrumb-item"><a href="./stat-tests-effect.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bio Data Science</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/jkruppa/jkruppa.github.io/" title="Quellcode" class="quarto-navigation-tool px-1" aria-label="Quellcode"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Dunkelmodus umschalten"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-quarto-shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Quarto und Shiny App</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Testen von Hypothesen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Pre-Test oder Vortest</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelle Designs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Einfache Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Fortgeschrittene Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface-app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistische Gruppenvergleiche</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Der Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Permutationstest &amp; Bootstraping</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen des Modellierens</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Fehlende Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Modellieren in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-prob-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Linear Probability Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-beta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Beta Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Fragebogenanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./time-space-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zeitliche und räumliche Analysen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-pseudo-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Pseudo Zeitreihen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Zeitreihen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Räumliche Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./abspann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abspann</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Spielecke</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link active" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">21.1</span> Genutzte R Pakete</a></li>
  <li><a href="#unterschied-zweier-mittelwerte" id="toc-unterschied-zweier-mittelwerte" class="nav-link" data-scroll-target="#unterschied-zweier-mittelwerte"><span class="header-section-number">21.2</span> Unterschied zweier Mittelwerte</a>
  <ul class="collapse">
  <li><a href="#cohens-d" id="toc-cohens-d" class="nav-link" data-scroll-target="#cohens-d"><span class="header-section-number">21.2.1</span> Cohen’s d</a></li>
  <li><a href="#hedges-g" id="toc-hedges-g" class="nav-link" data-scroll-target="#hedges-g"><span class="header-section-number">21.2.2</span> Hedges’ g</a></li>
  </ul></li>
  <li><a href="#unterschied-zweier-anteile" id="toc-unterschied-zweier-anteile" class="nav-link" data-scroll-target="#unterschied-zweier-anteile"><span class="header-section-number">21.3</span> Unterschied zweier Anteile</a>
  <ul class="collapse">
  <li><a href="#wahrscheinlichkeitsverhältnis-oder-risk-ratio-rr" id="toc-wahrscheinlichkeitsverhältnis-oder-risk-ratio-rr" class="nav-link" data-scroll-target="#wahrscheinlichkeitsverhältnis-oder-risk-ratio-rr"><span class="header-section-number">21.3.1</span> Wahrscheinlichkeitsverhältnis oder Risk Ratio (RR)</a></li>
  <li><a href="#chancenverhältnis-oder-odds-ratio-or" id="toc-chancenverhältnis-oder-odds-ratio-or" class="nav-link" data-scroll-target="#chancenverhältnis-oder-odds-ratio-or"><span class="header-section-number">21.3.2</span> Chancenverhältnis oder Odds Ratio (OR)</a></li>
  <li><a href="#odds-ratio-or-zu-risk-ratio-rr" id="toc-odds-ratio-or-zu-risk-ratio-rr" class="nav-link" data-scroll-target="#odds-ratio-or-zu-risk-ratio-rr"><span class="header-section-number">21.3.3</span> Odds Ratio (OR) zu Risk Ratio (RR)</a></li>
  </ul></li>
  <li><a href="#sec-effect-wirkung" id="toc-sec-effect-wirkung" class="nav-link" data-scroll-target="#sec-effect-wirkung"><span class="header-section-number">21.4</span> Wirkungsgrad von Pflanzenschutzmitteln</a>
  <ul class="collapse">
  <li><a href="#sec-effect-ht" id="toc-sec-effect-ht" class="nav-link" data-scroll-target="#sec-effect-ht"><span class="header-section-number">21.4.1</span> Wirkungsgrad nach <span class="citation" data-cites="henderson1955tests">Henderson und Tilton (1955)</span></a></li>
  <li><a href="#sec-effect-abbott" id="toc-sec-effect-abbott" class="nav-link" data-scroll-target="#sec-effect-abbott"><span class="header-section-number">21.4.2</span> Wirkungsgrad nach <span class="citation" data-cites="abbott1925method">Abbott u.&nbsp;a. (1925)</span></a></li>
  <li><a href="#sec-effect-ss" id="toc-sec-effect-ss" class="nav-link" data-scroll-target="#sec-effect-ss"><span class="header-section-number">21.4.3</span> Wirkungsgrad nach Sun-Shepard</a></li>
  <li><a href="#sec-effect-so" id="toc-sec-effect-so" class="nav-link" data-scroll-target="#sec-effect-so"><span class="header-section-number">21.4.4</span> Wirkungsgrad nach Schneider-Orelli</a></li>
  </ul></li>
  <li><a href="#sec-effect-interrater" id="toc-sec-effect-interrater" class="nav-link" data-scroll-target="#sec-effect-interrater"><span class="header-section-number">21.5</span> Interrater Reliabilität</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jkruppa/jkruppa.github.io/edit/master/stat-tests-effect.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/blob/master/stat-tests-effect.qmd" class="toc-action"><i class="bi empty"></i>Quellcode anzeigen</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-tests-preface-theory.html">Testen von Hypothesen</a></li><li class="breadcrumb-item"><a href="./stat-tests-effect.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-effect" class="quarto-section-identifier"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Letzte Änderung am 05. März 2024 um 14:31:24</em></p>
<blockquote class="blockquote">
<p><em>“Alles, was wir hören, ist eine Meinung, keine Tatsache. Alles, was wir sehen, ist eine Perspektive, nicht die Wahrheit.” — Marcus Aurelius, Meditationen</em></p>
</blockquote>
<p>Der Effektschätzer. Ein seltsames Kapitel, denn ich tue mich sehr schwer, dieses Kapitel irgendwo in die Linearität dieses Buches hier einzuordnen. Deshalb ist dieses Kapitel eigentlich immer an der falschen Stelle. Entweder hast du schon die statistischen Tests gelesen und du wüsstest gerne was die Effektschätzer sind <em>oder</em> du suchst hier nochmal die Beschreibung der Effektschätzer zum Beispiel aus der multiple Regression heraus. Also steht jetzt dieses Kapitel hier im Raum und du musst schauen, was du wirklich brauchst. Oder ob du dieses Kapitel erst überspringst und dann später nochmal hier liest. Eine wunderbare Übersicht über den Begriff <em>Effektschätzer</em> liefert das englische Buch <a href="https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/effects.html">Doing Meta-Analysis with R: A Hands-On Guide</a>. Der Effektschätzer wird dabei auch gerne Theta <span class="math inline">\(\boldsymbol{\theta}\)</span> genannt. Da wir dann aber später noch mit anderen Konzepten in die Quere kommen, nutze ich das etwas intuitivere Delta <span class="math inline">\(\boldsymbol{\Delta}\)</span>.</p>
<p>Wenn wir einen der vielen Effektschätzer berechnen wollen, dann nutzen wir dafür die Effektschätzer aus dem <a href="https://easystats.github.io/effectsize/index.html">R Paket <code>{effectsize}</code></a>. Das R Paket <code>{effectsize}</code> liefert Effektschätzer für fast alle statistischen Gelegenheiten. Wir werden hier wie immer nur den groben Überblick abdecken. Vermutlich wird das Kapitel dann noch Anwachsen. Streng genommen gehört das <a href="stat-tests-diagnostic.html" class="quarto-xref"><span>Kapitel 35</span></a> zu den diagnostischen Tests auf einer 2x2 Kreuztabelle auch irgendwie zu Effektschätzern. Wenn du Spezifität und Sensitivität suchst bist du in dem Kapitel zu diagnostischen Tests richtig.</p>
<p>Wir unterscheiden hier erstmal grob in vier Arten von Effektschätzern:</p>
<ol type="1">
<li>Effektschätzer, die einen <em>Mittelwertsunterschied</em> zwischen Behandlungen beschreiben.</li>
<li>Effektschätzer, die einen <em>Anteilsunterschied</em> zwischen Behandlungen beschreiben.</li>
<li>Effektschätzer, die einen <em>Wirkungsgrad</em> einer Behandlung zu einer Kontrolle beschreiben.</li>
<li>Effektschätzer, die eine <em>Übereinstimmung</em> zwischen Bewertern beschreibt.</li>
</ol>
<p>Daneben gibt es wie noch die Korrelation wie in <a href="stat-linear-reg-corr.html" class="quarto-xref"><span>Kapitel 40</span></a> beschrieben. Die Korrelation wollen wir aber in diesem Kapitel nicht vorgreifen bzw. wiederholen.</p>
<p>Am Ende muss du immer den Effekt im Kontext der Fragestellung bzw. des Outcomes <span class="math inline">\(y\)</span> bewerten. Der numerische Unterschied von <span class="math inline">\(0.1\)</span> cm kann in einem Kontext viel sein. Das Wachstum von Bakterienkolonien kann ein Unterschied von <span class="math inline">\(0.1\)</span> cm viel sein. Oder aber sehr wenig, wenn wir uns das Wachstum von Bambus pro Tag anschauen. Hier bist du gefragt, den Effekt in den Kontext richtig einzuordnen. Ebenso stellt sich die Frage, ob ein Unterschied von 6% viel oder wenig ist.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Effektschätzer zwischen Behandlungen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn wir uns einen Unterschied eines <strong>Mittelwerts</strong> anschauen, dann haben wir <em>keinen</em> Effekt vorliegen, wenn der Mittlwertsunterschied <span class="math inline">\(\Delta\)</span> zwischen der Gruppe <span class="math inline">\(A\)</span> und der Gruppe <span class="math inline">\(B\)</span> gleich 0 ist. Die Nullhypothese gilt. Beide Gruppen <span class="math inline">\(A\)</span> und <span class="math inline">\(B\)</span> haben den gleichen Mittelwert.</p>
<p><span class="math display">\[
\Delta_{A-B} = A - B = 0
\]</span></p>
<p>Wenn wir uns einen Unterschied eines <strong>Anteils</strong> anschauen, dann haben wir <em>keinen</em> Effekt vorliegen, wenn der Anteilsunterschied <span class="math inline">\(\Delta\)</span> zwischen der Gruppe <span class="math inline">\(A\)</span> und der Gruppe <span class="math inline">\(B\)</span> gleich 1 ist. Die Nullhypothese gilt. Beide Gruppen <span class="math inline">\(A\)</span> und <span class="math inline">\(B\)</span> haben den gleichen Anteil.</p>
<p><span class="math display">\[
\Delta_{A/B} = \cfrac{A}{B} = 1
\]</span></p>
<p>Dieses Wissen brauchen wir um die Signifikanzschwelle bei einem 95% Konfidenzintervall richtig zu setzen und interpretieren zu können. Siehe dazu auch nochmal das <a href="stat-tests-basic.html#sec-ki" class="quarto-xref"><span>Kapitel 19.2.3</span></a>.</p>
</div>
</div>
<section id="genutzte-r-pakete" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="genutzte-r-pakete"><span class="header-section-number">21.1</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, magrittr, see, scales,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               effectsize, parameters, broom, readxl,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               emmeans, conflicted)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"select"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"filter"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"mutate"</span>, <span class="st">"dplyr"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section>
<section id="unterschied-zweier-mittelwerte" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="unterschied-zweier-mittelwerte"><span class="header-section-number">21.2</span> Unterschied zweier Mittelwerte</h2>
<p>Wir berechnen zwei Mittelwerte <span class="math inline">\(\bar{y}_1\)</span> und <span class="math inline">\(\bar{y}_2\)</span>. Wenn wir wissen wollen wie groß der Effekt zwischen den beiden Mittelwerten ist, dann bilden wir die Differenz. Wir berechnen das <span class="math inline">\(\Delta_{y_1-y_2}\)</span> für <span class="math inline">\(y_1\)</span> und <span class="math inline">\(y_2\)</span> indem wir die beiden Mittelwerte voneinander abziehen.</p>
<p><span class="math display">\[
\Delta_{y_1-y_2} = \bar{y}_1 - \bar{y}_2
\]</span></p>
<p>Wenn es keinen Unterschied zwischen den beiden Mittelwerten <span class="math inline">\(\bar{y}_1\)</span> und <span class="math inline">\(\bar{y}_2\)</span> gibt, dann ist die Differenz <span class="math inline">\(\Delta_{y_1-y_2} = \bar{y}_1 - \bar{y}_2\)</span> gleich 0. Wir sagen, die Nullhypothese <em>vermutlich</em> gilt, wenn die Differenz klein ist. Warum schreiben wir hier vermutlich? Ein statistischer Test ist eine Funktion von <span class="math inline">\(\Delta\)</span>, <span class="math inline">\(s\)</span> und <span class="math inline">\(n\)</span>. Wir können auch mit kleinem <span class="math inline">\(\Delta\)</span> die Nullhypothese ablehnen, wenn <span class="math inline">\(s\)</span> und <span class="math inline">\(n\)</span> eine passende Teststatistik generieren. Siehe dazu auch das <a href="stat-tests-basic.html#sec-delta-n-s" class="quarto-xref"><span>Kapitel 19.3</span></a>. Was wir besser annehmen können ist, dass die Relevanz klein ist. Effekt mit einem geringen Mittelwertsunterschied sind meistens nicht relevant. Aber diese Einschätzung hängt stark von der Fragestellung ab.</p>
<p><span class="math display">\[
H_0: \Delta_{y_1-y_2} = \bar{y}_1 - \bar{y}_2 = 0
\]</span></p>
<p>In <a href="#tbl-dog-cat-small-delta" class="quarto-xref">Tabelle&nbsp;<span>21.1</span></a> ist nochmal ein sehr simples Datenbeispiel gegeben an dem wir den Zusammenhang nochmal nachvollziehen wollen.</p>
<div class="cell">
<div id="tbl-dog-cat-small-delta" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dog-cat-small-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.1— Beispiel für die Berechnung von einem Mittelwertseffekt an der Sprunglänge [cm] von Hunde und Katzenflöhen.
</figcaption>
<div aria-describedby="tbl-dog-cat-small-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">jump_length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">8.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">7.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">8.3</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">9.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">9.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Nehmen wir an, wir berechnen für die Sprungweite [cm] der Hundeflöhe einen Mittelwert von <span class="math inline">\(\bar{y}_{dog} = 8.2\)</span> und für die Sprungweite [cm] der Katzenflöhe einen Mittelwert von <span class="math inline">\(\bar{y}_{cat} =8.3\)</span>. Wie große ist nun der Effekt? Oder anders gesprochen, welchen Unterschied in der Sprungweite macht es aus ein Hund oder eine Katze zu sein? Was ist also der Effekt von <code>animal</code>? Wir rechnen <span class="math inline">\(\bar{y}_{dog} - \bar{y}_{cat} = 8.2 - 8.3 = -0.1\)</span>. Zum einen wissen wir jetzt “die Richtung”. Da wir ein Minus vor dem Mittelwertsunterschied haben, müssen die Katzenflöhe weiter springen als die Hundeflöhe, nämlich 0.1 cm. Dennoch ist der Effekt sehr klein.</p>
<section id="cohens-d" class="level3" data-number="21.2.1">
<h3 data-number="21.2.1" class="anchored" data-anchor-id="cohens-d"><span class="header-section-number">21.2.1</span> Cohen’s d</h3>
<p>Da der Mittlwertsunterschied <em>alleine</em> nnur eine eingeschränkte Aussage über den Effekt erlaubt, gibt es noch Effektschätzer, die den Mittelwertsunterschied <span class="math inline">\(\Delta_{y_1-y_2}\)</span> mit der Streuung <span class="math inline">\(s^2\)</span> sowie der Fallzahl zusammenbringt. Der bekannteste Effektschätzer für einen Mittelwertsunterschied bei großer Fallzahl mit mehr als 20 Beobachtungen ist Cohen’s d.&nbsp;Wir können Cohen’s d wie folgt berechnen.</p>
<p><span class="math display">\[
|d| = \cfrac{\bar{y}_1-\bar{y}_2}{\sqrt{\cfrac{s_1^2+s_2^2}{2}}}
\]</span></p>
<p>Wenn wir die berechneten Mittelwerte und die Varianz der beiden Gruppen in die Formel einsetzten ergibt sich ein absolutes Cohen’s d von 0.24 für den Gruppenvergleich.</p>
<p><span class="math display">\[
|d| = \cfrac{8.2 - 8.3}{\sqrt{(0.5^2+0.3^2) /2}} = \cfrac{-0.1}{0.41} = \lvert-0.24\rvert
\]</span></p>
<p>Was denn nun Cohen’s d <em>exakt</em> aussagt, kann niemand sagen. Aber wir haben einen Wust an möglichen Grenzen. Hier soll die Grenzen von Cohen (1988) einmal angegeben werden. Cohen (1988) hat in seiner Arbeit folgende Grenzen in <a href="#tbl-cohen-d" class="quarto-xref">Tabelle&nbsp;<span>21.2</span></a> für die Interpretation von <span class="math inline">\(d\)</span> vorgeschlagen. Mehr Informationen zu Cohen’s d gibt es auf der Hilfeseite von <code>effectsize</code>: <a href="https://easystats.github.io/effectsize/reference/interpret_cohens_d.html">Interpret standardized differences</a>.</p>
<div id="tbl-cohen-d" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cohen-d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.2— Interpretation der Effektstärke nach Cohen (1988).
</figcaption>
<div aria-describedby="tbl-cohen-d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Cohen’s d</th>
<th style="text-align: center;">Interpretation des Effekts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(d &lt; 0.2\)</span></td>
<td style="text-align: center;">Sehr klein</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(0.2 \leq d &lt; 0.5\)</span></td>
<td style="text-align: center;">Klein</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(0.5 \leq d &lt; 0.8\)</span></td>
<td style="text-align: center;">Mittel</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(d \geq 0.8\)</span></td>
<td style="text-align: center;">Stark</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Wir können auch über die Funktion <code>cohens_d()</code> Cohen’s d einfach in R berechnen. Die Funktion <code>cohens_d()</code> akzeptiert die Formelschreibweise. Die 95% Konfidenzintervalle sind mit Vorsicht zu interpretieren. Denn die Nullhypothese ist hier nicht so klar formuliert. Wir lassen also die 95% Konfidenzintervalle erstmal hier so stehen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(jump_length <span class="sc">~</span> animal, <span class="at">data =</span> data_tbl, <span class="at">pooled_sd =</span> <span class="cn">TRUE</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |        95% CI
-------------------------
0.24      | [-1.16, 1.62]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<p>Dankenswerterweise gibt es noch die Funktion <code>interpret_cohens_d</code>, die es uns erlaubt auszusuchen nach welche Literturquelle wir den Wert von Cohen’s d interpretieren wollen. Ob dieser Effekt relevant zur Fragestellung ist musst du selber entscheiden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(<span class="fl">0.24</span>, <span class="at">rules =</span> <span class="st">"cohen1988"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "small"
(Rules: cohen1988)</code></pre>
</div>
</div>
</section>
<section id="hedges-g" class="level3" data-number="21.2.2">
<h3 data-number="21.2.2" class="anchored" data-anchor-id="hedges-g"><span class="header-section-number">21.2.2</span> Hedges’ g</h3>
<p>Soweit haben wir uns mit sehr großen Fallzahlen beschäftigt. Cohen’s d ist dafür auch sehr gut geeigent und wenn wir mehr als 20 Beobachtungen haben, können wir Cohen’s d auch gut anwenden. Wenn wir weniger Fallzahl vorliegen haben, dann können wir Hedges’ g nutzen. Hedges’ g bietet eine Verzerrungskorrektur für kleine Stichprobengrößen (<span class="math inline">\(N &lt; 20\)</span>) sowie die Möglichkeit auch für <em>unbalanzierte</em> Gruppengrößen einen Effektschätzeer zu berechnen. Die Formel sieht mit dem Korrekturterm recht mächtig aus.</p>
<p><span class="math display">\[
g = \cfrac{\bar{y}_1 - \bar{y}_2}{s^*} \cdot \left(\cfrac{N-3}{N-2.25}\right) \cdot \sqrt{\cfrac{N-2}{N}}
\]</span></p>
<p>mit</p>
<p><span class="math display">\[
s^* = \sqrt{\cfrac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1+n_2-2}}
\]</span></p>
<p>Wir können aber einfach die Mittelwerte und die Varianzen aus unserem beispiel einsetzen. Da unsere beiden Gruppen gleich groß sind <span class="math inline">\(n_1 = n_2\)</span> und damit ein balanziertes Design vorliegt, sind Cohen’s d und Hedges’ g numerisch gleich. Wir können dann noch für die geringe Fallzahl korrigieren und erhalten ein händisches <span class="math inline">\(g = 0.18\)</span>.</p>
<p><span class="math display">\[
g = \cfrac{8.2 - 8.3}{0.41} \cdot \left(\cfrac{8-3}{8-2.25}\right) \cdot \sqrt{\cfrac{8-2}{8}} = \lvert-0.24\rvert \cdot 0.87 \cdot 0.87 \approx 0.18
\]</span></p>
<p>mit</p>
<p><span class="math display">\[
s^* = \sqrt{\cfrac{(4-1)\cdot0.5^2 + (4-1)\cdot0.3^2}{4+4-2}} = \sqrt{\cfrac{0.75 + 0.27}{6}} = 0.41
\]</span></p>
<p>In R gibt es die Funktion <code>hedges_g()</code> die uns erlaubt in der Formelschreibweise direkt Hedges’ g zu berechnen. Wir sehen hier eine Abweichung von unserer händischen Rechnung. Das ist aber in soweit nicht ungewöhnlich, da es noch eine Menge Varianten der Anpassung für die geringe Fallzahl gibt. In der Anwendung nutzen wir die Funktion aus dem Paket <code>{effectsize}</code> wie hier durchgeführt.</p>
<p>Wir ignorieren wie auch bei Cohen’s d das 95% Konfidenzintervall, da die Interpretation ohne die Nullhypothese nicht möglich ist. Die Nullhypothese ist in diesem Fall komplexer. Wir lassen daher das 95% Konfidenzintervall erstmal einfach hier so stehen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hedges_g</span>(jump_length <span class="sc">~</span> animal, <span class="at">data =</span> data_tbl, <span class="at">pooled_sd =</span> <span class="cn">TRUE</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |        95% CI
-------------------------
0.21      | [-1.01, 1.41]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<p>Auch für Hedges’ g gibt es die Möglichkeit sich über die Funktion <code>interpret_hedges_g()</code> den Wert von <span class="math inline">\(g=0.21\)</span> interpretieren zu lassen. Nach Sawilowsky (2009) haben wir hier einen kleinen Effekt vorliegen. Ob dieser Effekt relevant zur Fragestellung ist musst du selber entscheiden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_hedges_g</span>(<span class="fl">0.21</span>, <span class="at">rules =</span> <span class="st">"sawilowsky2009"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "small"
(Rules: sawilowsky2009)</code></pre>
</div>
</div>
<p><a href="https://easystats.github.io/effectsize/reference/interpret_cohens_d.html">Die Hilfeseite zu dem Paket <code>effectsize</code></a> bietet eine Liste an möglichen Referenzen für die Wahl der Interpretation der Effektstärke. Du musst dann im Zweifel schauen, welche der Quellen und damit Grenzen du nutzen willst.</p>
</section>
</section>
<section id="unterschied-zweier-anteile" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="unterschied-zweier-anteile"><span class="header-section-number">21.3</span> Unterschied zweier Anteile</h2>
<p>Neben den Unterschied zweier Mittelwerte ist auch häufig das Interesse an dem Unterschied zwischen zwei Anteilen. Nun unterscheiden wir zwischen Wahrscheinlichkeiten und Chancen. Beide Maßzahlen, die Wahrscheinlichkeit wie auch die Chance, beschreiben einen Anteil. Hier tritt häufig Verwirrung auf, daher hier zuerst ein Beispiel.</p>
<p>Wir behandelt <span class="math inline">\(n = 65\)</span> Hunde mit dem Antiflohmittel <em>FleaEx</em>. Um die Wirkung von <em>FleaEx</em> auch bestimmen zu können haben wir uns zwei Gruppen von Hunden ausgesucht. Wir haben Hunde, die mit Flöhe infiziert sind und Hunde, die nicht mit Flöhen infiziert sind. Wir schauen nun in wie weit <em>FleaEx</em> gegen Flöhe hilft im Vergleich zu einer Kontrolle.</p>
<div id="tbl-2x2-ratio-delta" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2-ratio-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.3— Eine 2x2 Tabelle als Beispiel für unterschiedliche Flohinfektionen bei nach einer Behandlung mit <em>FleaEx</em> für die Berechnung von Effektschätzern eines Anteils.
</figcaption>
<div aria-describedby="tbl-2x2-ratio-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Group</strong></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>FleaEx</em></td>
<td style="text-align: center;"><em>Control</em></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Infected</strong></td>
<td style="text-align: center;"><em>Yes (1)</em></td>
<td style="text-align: center;"><span class="math inline">\(18_{\;\Large a}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(23_{\;\Large b}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>No (0)</em></td>
<td style="text-align: center;"><span class="math inline">\(14_{\;\Large c}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(10_{\;\Large d}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Aus der <a href="#tbl-2x2-ratio-delta" class="quarto-xref">Tabelle&nbsp;<span>21.3</span></a> können wir entnehmen, dass 18 behandelte Hunde mit Flöhen infiziert sind und 14 Hunde keine Infektion aufweisen. Bei den Hunden aus der Kontrolle haben wir 23 infizierte und 10 gesunde Tiere beobachtet.</p>
<p>Wir können nun zwei Arten von Anteilen berechnen um zu beschreiben, wie sich der Anteil an infizierten Hunden verhält. Das bekanntere ist die Frequenz oder Wahrscheinlichkeit oder Risk Ratio (<span class="math inline">\(RR\)</span>). Das andere ist das Chancenverhältnis oder Odds Ratio (<span class="math inline">\(OR\)</span>). Beide kommen in der Statistik vor und sind unterschiedlich zu interpretieren. Es gibt verschiedene Typen von klinischen Studien, also Untersuchungen an Menschen. Einige Studien liefern nur <span class="math inline">\(OR\)</span> wieder andere Studientypen liefern <span class="math inline">\(RR\)</span>. <span class="citation" data-cites="george2020s">George u.&nbsp;a. (<a href="#ref-george2020s" role="doc-biblioref">2020</a>)</span> liefert eine gute Übersicht über <em>What’s the risk: differentiating risk ratios, odds ratios, and hazard ratios?</em></p>
<p>Um die die Odds Ratio und die Risk Ratios auch in R berechnen zu können müssen wir einmal die 2x2 Kreuzabelle in R nachbauen. Wir nutzen dafür die Funktion <code>matrix()</code> und müssen schauen, dass die Zahlen in der 2x2 Kreuztabelle in R dann auch so sind, wie in der Datentabelle. Das ist jetzt ein schöner Codeblock, ist aber dafür da um sicherzustellen, dass wir die Zahlen richtig eintragen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cross_mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">23</span>, <span class="dv">14</span>, <span class="dv">10</span>),</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimnames =</span> <span class="fu">list</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Infected =</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Group =</span> <span class="fu">c</span>(<span class="st">"FleaEx"</span>, <span class="st">"Control"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>cross_mat</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Group
Infected FleaEx Control
     Yes     18      23
     No      14      10</code></pre>
</div>
</div>
<p>Später werden wir das <span class="math inline">\(OR\)</span> und <span class="math inline">\(RR\)</span> wieder treffen. Das <span class="math inline">\(OR\)</span> kommt in der logistsichen Regression als Effektschätzer vor. Wir nutzen das <span class="math inline">\(RR\)</span> als Effektschätzer in der Poissonregression.</p>
<section id="wahrscheinlichkeitsverhältnis-oder-risk-ratio-rr" class="level3" data-number="21.3.1">
<h3 data-number="21.3.1" class="anchored" data-anchor-id="wahrscheinlichkeitsverhältnis-oder-risk-ratio-rr"><span class="header-section-number">21.3.1</span> Wahrscheinlichkeitsverhältnis oder Risk Ratio (RR)</h3>
<p>Wir berechnen wir nun das Wahrscheinlichkeitsverhältnis oder Risk Ratio (RR)? Das Risk Ratio ist das Verhältnis von den infizierten Hunden in der Behandlung (<span class="math inline">\(a\)</span>) zu allen infizierten Hunden (<span class="math inline">\(a+c\)</span>) zu dem Verhältnis der gesunden Hunde in der Behandlung (<span class="math inline">\(b\)</span>) zu allen gesunden Hunden (<span class="math inline">\(b+d\)</span>). Das klingt jetzt etwas wirr, deshalb helfen manchmal wirklich Formeln, den Zusammenhang besser zu verstehen. Damit ist <span class="math inline">\(Pr(\mbox{FleaEx}|\mbox{infected})\)</span> die Wahrscheinlichkeit infiziert zu sein, wenn der Hund mit <em>FleaEx</em> behandelt wurde.</p>
<p><span class="math display">\[
Pr(\mbox{FleaEx}|\mbox{infected}) = \cfrac{a}{a+c} = \cfrac{18}{18+14} \approx 0.56
\]</span></p>
<p>Die Wahrscheinlichkeit <span class="math inline">\(Pr(\mbox{Control}|\mbox{infected})\)</span> ist dann die Wahrscheinlichkeit infiziert zu sein, wenn der Hund mit in der Kontrolle war.]{.aside}</p>
<p><span class="math display">\[
Pr(\mbox{Control}|\mbox{infected}) = \cfrac{b}{b+d} = \cfrac{23}{23 + 10} \approx 0.70
\]</span></p>
<p>Das Risk Ratio ist mehr oder minder das Verhältnis von der beiden Spalten der <a href="#tbl-2x2-ratio-delta" class="quarto-xref">Tabelle&nbsp;<span>21.3</span></a> für die Behandlung. Wir erhalten also ein <span class="math inline">\(RR\)</span> von <span class="math inline">\(0.76\)</span>. Damit mindert die Gabe von <em>FleaEx</em> die Wahrscheinlichkeit sich mit Flöhen zu infizieren.</p>
<p><span class="math display">\[
\Delta_{y_1/y_2} = RR = \cfrac{Pr(\mbox{FleaEx}|\mbox{infected})}{Pr(\mbox{Control}|\mbox{infected})} =  \cfrac{0.56}{0.70} \approx 0.80
\]</span></p>
<p>Wir überprüfen kurz mit der Funktion <code>riskratio()</code> ob wir richtig gerechnet haben. Das 95% Konfidenzintervall können wir interpretieren, dafür brauchen wir aber noch einmal eine Idee was “kein Effekt” bei einem Risk Ratio heist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(cross_mat)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Risk ratio |       95% CI
-------------------------
0.81       | [0.55, 1.18]</code></pre>
</div>
</div>
<p>Wann liegt nun kein Effekt bei einem Anteil wie dem RR vor? Wenn der Anteil in der einen Gruppe genauso groß ist wie der Anteil der anderen Gruppe.</p>
<p><span class="math display">\[
H_0: RR = \cfrac{Pr(\mbox{dog}|\mbox{infected})}{Pr(\mbox{cat}|\mbox{infected})} = 1
\]</span></p>
<p>Wir interpretieren das <span class="math inline">\(RR\)</span> nun wie folgt. Unter der Annahme, dass ein kausaler Effekt zwischen der Behandlung und dem Outcome besteht, können die Werte des relativen Risikos auf folgende Art und Weise interpretiert werden:</p>
<ul>
<li><span class="math inline">\(RR = 1\)</span> bedeutet, dass die Behandlung keinen Einfluss auf das Outcome hat</li>
<li><span class="math inline">\(RR &lt; 1\)</span> bedeutet, dass das Risiko für das Outcome durch die Behandlung verringert wird, was ein “Schutzfaktor” ist</li>
<li><span class="math inline">\(RR &gt; 1\)</span> bedeutet, dass das Risiko für das Outcome durch die Behandlung erhöht wird, was ein “Risikofaktor” ist.</li>
</ul>
<p>Das heist in unserem Fall, dass wir mit einem RR von <span class="math inline">\(0.80\)</span> eine protektive Behandlung vorliegen haben. Die Gabe von <em>FleaEx</em> reduziert das Risiko mit Flöhen infiziert zu werden. Durch das 95% Konfidenzintervall wissen wir auch, dass das <span class="math inline">\(RR\)</span> nicht signifikant ist, da die 1 im 95% Konfidenzintervall enthalten ist.</p>
</section>
<section id="chancenverhältnis-oder-odds-ratio-or" class="level3" data-number="21.3.2">
<h3 data-number="21.3.2" class="anchored" data-anchor-id="chancenverhältnis-oder-odds-ratio-or"><span class="header-section-number">21.3.2</span> Chancenverhältnis oder Odds Ratio (OR)</h3>
<p>Neben dem Risk Ratio gibt es noch das Odds Ratio. Das Odds Ratio ist ein Chancenverhältnis. Wenn der Mensch an sich schon Probleme hat für sich Wahrscheinlichkeiten richtig einzuordnen, scheitert man allgemein an der Chance vollkommen. Dennoch ist das Odds Ratio eine gute Maßzahl um abzuschätzen wie die Chancen stehen, einen infizierten Hund vorzufinden, wenn der Hund behandelt wurde.</p>
<p>Schauen wir uns einmal die Formeln an. Im Gegensatz zum Risk Ratio, welches die Spalten miteinander vergleicht, vergleicht das Odds Ratio die Zeilen. Als erstes berechnen wir die Chance unter der Gabe von <em>FleaEx</em> infiziert zu sein wie folgt.</p>
<p><span class="math display">\[
Odds(\mbox{FleaEx}|\mbox{infected}) = a:b = 18:23 = \cfrac{18}{23} = 0.78
\]</span></p>
<p>Dann berechnen wir die Chance in der Kontrollgruppe infiziert zu sein wie folgt.</p>
<p><span class="math display">\[
Odds(\mbox{Control}|\mbox{infected}) = c:d = 14:10 = \cfrac{14}{10} \approx 1.40
\]</span></p>
<p>Abschließend bilden wir das Chancenverhältnis der Chance unter der Gabe von <em>FleaEx</em> infiziert zu sein zu der Chance in der Kontrollgruppe infiziert zu sein. Es ergbit sich das Odds Ratio wie folgt.</p>
<p><span class="math display">\[
\Delta_{y_1/y_2} = OR =  \cfrac{Odds(\mbox{Flea}|\mbox{infected})}{Odds(\mbox{Control}|\mbox{infected})} = \cfrac{a \cdot d}{b \cdot c} = \cfrac{0.78}{1.40} \approx 0.56
\]</span></p>
<p>Wir überprüfen kurz mit der Funktion <code>oddsratio()</code> ob wir richtig gerechnet haben. Das 95% Konfidenzintervall können wir interpretieren, dafür brauchen wir aber noch einmal eine Idee was “kein Effekt” bei einem Odds Ratio heist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(cross_mat)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Odds ratio |       95% CI
-------------------------
0.56       | [0.20, 1.55]</code></pre>
</div>
</div>
<p>Wann liegt nun kein Effekt bei einem Anteil wie dem OR vor? Wenn der Anteil in der einen Gruppe genauso groß ist wie der Anteil der anderen Gruppe.</p>
<p><span class="math display">\[
H_0: OR =  \cfrac{Odds(\mbox{dog}|\mbox{infected})}{Odds(\mbox{cat}|\mbox{infected})} = 1
\]</span></p>
<p>Wir interpretieren das <span class="math inline">\(OR\)</span> nun wie folgt. Unter der Annahme, dass ein kausaler Effekt zwischen der Behandlung und dem Outcome besteht, können die Werte des Odds Ratio auf folgende Art und Weise interpretiert werden:</p>
<ul>
<li><span class="math inline">\(OR = 1\)</span> bedeutet, dass die Behandlung keinen Einfluss auf das Outcome hat</li>
<li><span class="math inline">\(OR &lt; 1\)</span> bedeutet, dass sich die Chance das Outcome zu bekommen durch die Behandlung verringert wird, was ein “Schutzfaktor” ist</li>
<li><span class="math inline">\(OR &gt; 1\)</span> bedeutet, dass sich die Chance das Outcome zu bekommen durch die Behandlung erhöht wird, was ein “Risikofaktor” ist.</li>
</ul>
<p>Das heist in unserem Fall, dass wir mit einem OR von <span class="math inline">\(0.56\)</span> eine protektive Behandlung vorliegen haben. Die Gabe von <em>FleaEx</em> reduziert die Chance mit Flöhen infiziert zu werden. Durch das 95% Konfidenzintervall wissen wir auch, dass das <span class="math inline">\(OR\)</span> nicht signifikant ist, da die 1 im 95% Konfidenzintervall enthalten ist.</p>
</section>
<section id="odds-ratio-or-zu-risk-ratio-rr" class="level3" data-number="21.3.3">
<h3 data-number="21.3.3" class="anchored" data-anchor-id="odds-ratio-or-zu-risk-ratio-rr"><span class="header-section-number">21.3.3</span> Odds Ratio (OR) zu Risk Ratio (RR)</h3>
<p>Wenn wir das OR berechnet haben, wollen wir eventuell das <span class="math inline">\(OR\)</span> in dem Sinne eines Riskoverhältnisses berichten. Leider ist es nun so, dass wir das nicht einfach mit einem <span class="math inline">\(OR\)</span> machen können. Ein <span class="math inline">\(OR\)</span> von 3.5 ist ein großes Chancenverhältnis. Aber ist es auch 3.5-mal so wahrscheinlich? Nein so einfach können wir das OR nicht interpretieren. Wir können aber das <span class="math inline">\(OR\)</span> in das <span class="math inline">\(RR\)</span> umrechnen. Dafür brauchen wir aber das <span class="math inline">\(p_0\)</span>. Dabei ist das <span class="math inline">\(p_0\)</span> das Basisrisiko also die Wahrscheinlichkeit des Ereignisses ohne die Intervention. Wenn wir nichts tun würden, wie wahrscheinlich wäre dann das Auftreten des Ereignisses? Es ergibt sich dann die folgende Formel für die Umrechnung des <span class="math inline">\(OR\)</span> in das <span class="math inline">\(RR\)</span>. <span class="citation" data-cites="grant2014converting">Grant (<a href="#ref-grant2014converting" role="doc-biblioref">2014</a>)</span> gibt nochmal eine wissenschaftliche Diskussion des Themas zur Konvertierung von OR zu RR.</p>
<p><span class="math display">\[
RR = \cfrac{OR}{(1 - p_0 + (p_0 \cdot OR))}
\]</span></p>
<p>Schauen wir uns das einmal in einem Beispiel an. Wir nutzen für die Umrechnung die Funktion <code>oddsratio_to_riskratio()</code> aus dem R Paket <code>{effectsize}</code>. Wenn wir ein <span class="math inline">\(OR\)</span> von 3.5 haben, so hängt das <span class="math inline">\(RR\)</span> von dem Basisriskio ab. Wenn das Basisirisko für die Erkrankung ohne die Behandlung sehr hoch ist mit <span class="math inline">\(p_0 = 0.85\)</span>, dann ist das <span class="math inline">\(RR\)</span> sehr klein.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fl">3.5</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>baserate <span class="ot">&lt;-</span> <span class="fl">0.85</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio_to_riskratio</span>(OR, baserate) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.12</code></pre>
</div>
</div>
<p>Auf der anderen Seite nähert sich das <span class="math inline">\(OR\)</span> dem <span class="math inline">\(RR\)</span> an, wenn das Basisriskio für die Erkrankung mit <span class="math inline">\(p_0 = 0.04\)</span> sehr klein ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fl">3.5</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>baserate <span class="ot">&lt;-</span> <span class="fl">0.04</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio_to_riskratio</span>(OR, baserate) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.18</code></pre>
</div>
</div>
<p>Weil wir natürlich das Basisrisiko nur abschätzen können, verbleibt hier eine gewisse Unsicherheit, wie das <span class="math inline">\(RR\)</span> zu einem gegebenen <span class="math inline">\(OR\)</span> aussieht.</p>
</section>
</section>
<section id="sec-effect-wirkung" class="level2 page-columns page-full" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="sec-effect-wirkung"><span class="header-section-number">21.4</span> Wirkungsgrad von Pflanzenschutzmitteln</h2>
<p>Neben den klassischen Effektmaßzahlen, die sich aus einem Mittelwert oder einem Anteil direkt berechnen, gibt es noch andere Effektmaße. Einer dieser Effektmaße ist der Wirkungsgrad für zum Beispiel ein Pflanzenschutzmittel. Wir können hier aber auch weiter denken und uns überlegen in wie weit wir eine Population von Schaderregern durch eine Behandlung reduzieren können. Unabdingbar ist in diesem Fall eine positive Kontrolle in der nichts gemacht wird sondern nur der normale Befall gemessen wird. Merke also, ohne eine Kontrolle geht bei der Bestimmung des Wirkungsgrades gar nichts.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Übersicht über Wirkungsgrade
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Die Seite <a href="https://www.ehabsoft.com/ldpline/onlinecontrol.htm">LdP Line by Ehab Bakr</a> liefert nochmal die Formeln und Berechungsmöglichkeiten für andere Wirkungsgrade mit einem praktischen Online-Rechner. Leider ist die Seite sehr alt und die Sicherheitsbestimmungen lassen moderne Browser zweifeln.</li>
<li>Der <a href="http://www.biometrische-gesellschaft.de/fileadmin/AG_Daten/Landwirtschaft/tagungsberichte_pdf/buechse.pdf">Vortrag von Andreas Büchse</a> <em>“Nutzung der Wirkungsgradberechnung nach Abbott und Henderson-Tilton in der angewandten Agrarforschung”</em> gibt auch nochmal weitere Einblicke und ist die Grundlage für die Beispiele hier.</li>
</ul>
</div>
</div>
<p>In der <a href="#tbl-effect-wirk" class="quarto-xref">Tabelle&nbsp;<span>21.4</span></a> sehen wir nochmal eine Übersicht über vier mögliche Arten den Wirkungsgrad zu berechnen. Je nachdem was wir vorliegen haben, entweder einen Befall mit Zähldaten oder aber eine Sterblichkeit bzw. Mortalität, müssen wir eine andere Methode wählen. Auch müssen wir unterscheiden, ob wir eine homogene Population vorliegen haben oder eher eine heterogene Population. Ich kann hier aber schon mal etwas abkürzen, meistens können wir nur den Wirkungsgrad nach <span class="citation" data-cites="abbott1925method">Abbott u.&nbsp;a. (<a href="#ref-abbott1925method" role="doc-biblioref">1925</a>)</span> berechnen, da unser experimentelles Design nicht mehr hergibt. Der Wirkungsgrad nach Abbott hat nämlich nur die räumliche Komponente und nicht die zeitliche. So lässt sich Abbott häufig einfacher durchführen und ausrechnen. Für eine zeitliche Komponente wie bei Henderson-Tilton müssten wir dann den Befall wiederholt messen.</p>
<div id="tbl-effect-wirk" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-effect-wirk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.4— Übersicht der möglichen Wirkungsgrade nach Population und gemessen Werten an den Beobachtungen.
</figcaption>
<div aria-describedby="tbl-effect-wirk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<tbody>
<tr class="odd">
<td></td>
<td style="text-align: center;"><strong>Homogene Population</strong></td>
<td style="text-align: center;"><strong>Heterogene Population (Vorbefall differenziert)</strong></td>
</tr>
<tr class="even">
<td><strong>Befall oder lebende Individuen</strong></td>
<td style="text-align: center;"><a href="#sec-effect-abbott">Abbott</a> [<em>räumlicher Bezug</em>]</td>
<td style="text-align: center;"><a href="#sec-effect-ht">Henderson-Tilton</a> [<em>zeitlich und räumlicher Bezug</em>]</td>
</tr>
<tr class="odd">
<td><strong>Sterblichkeit oder tote Individuen</strong></td>
<td style="text-align: center;"><a href="#sec-effect-so">Schneider-Orelli</a></td>
<td style="text-align: center;"><a href="#sec-effect-ss">Sun-Shepard</a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Im Folgenden gehen wir einmal die vier Wirkungsgrade durch. Neben Abbott stelle ich dann hier nochmal den Wirkungsgrad nach <span class="citation" data-cites="henderson1955tests">Henderson und Tilton (<a href="#ref-henderson1955tests" role="doc-biblioref">1955</a>)</span> vor. Die anderen Wirkungsgrade nur als Formeln, da mir aktuell noch keine Anwendungen hier über den Weg gelaufen sind. Der Hauptfokus liegt dann aber am Ende auf den Wirkungsgrad nach Abbott. Den Wirkungsgrad brauchen wir eben dann doch am meisten, da wir nach Abbott nur den gezählten Befall nach der Behandlung bestimmen müssen. Der Wirkungsgrad nach Abbott entspricht meistens eher der experimentellen Wirklichkeit. Das soll dich natürlich nicht davon abschrecken auch die anderen Wirkunsggrade zu nutzen, aber dafür musst du meistens mehr Aufwand betreiben.</p>
<section id="sec-effect-ht" class="level3" data-number="21.4.1">
<h3 data-number="21.4.1" class="anchored" data-anchor-id="sec-effect-ht"><span class="header-section-number">21.4.1</span> Wirkungsgrad nach <span class="citation" data-cites="henderson1955tests">Henderson und Tilton (<a href="#ref-henderson1955tests" role="doc-biblioref">1955</a>)</span></h3>
<p>Der Wirkungsgrad nach Henderson-Tilton hate den großen Vorteil, dass wir auch eine zzeitliche Komponente mit berücksichtigen können. Wie verhält sich der BEfall der Kontrolle und der Behandlung über die Zeit des Versuches? Wir müssen dafür den Befall vor (eng. <em>before</em>, abk. <em>b</em>) und den Befall nach (eng. <em>after</em>, abk. <em>a</em>) der Applikation bestimmen. Dann erhalten wir folgende Formel, die die Anzahlen der Behandlung und Kontrolle räumlich wie zeitlich zusamenfasst. Nämlich einmal zu Beginn des Versuches und einmal zum Ende. Henderson-Tilton erlaubt es damit zusätzlich Unterschiede in der Populationsdynamik zu bewerten.</p>
<p><span class="math display">\[
WG_{HT} = \left(1 - \cfrac{T_a}{T_b}\cdot\cfrac{C_b}{C_a}\right)
\]</span></p>
<p>mit</p>
<ul>
<li><span class="math inline">\(T_{a}\)</span> Anzahl lebend in behandelter Parzelle <em>nach</em> Applikation (eng. <em>after</em>)</li>
<li><span class="math inline">\(T_{b}\)</span> Anzahl lebend in behandelter Parzelle <em>vor</em> Applikation (eng. <em>before</em>)</li>
<li><span class="math inline">\(C_{a}\)</span> Anzahl lebend in Kontrolle <em>nach</em> Applikation (eng. <em>after</em>)</li>
<li><span class="math inline">\(C_{b}\)</span> Anzahl lebend in Kontrolle <em>vor</em> Applikation (eng. <em>before</em>)</li>
</ul>
<p>Hier nochmal ein kleines numerisches Beispiel mit <span class="math inline">\(T_b = 300\)</span> sowie <span class="math inline">\(T_a = 30\)</span> und <span class="math inline">\(C_b = 500\)</span> sowie <span class="math inline">\(C_a = 1000\)</span>. Wir fangen also in einer Population mit einem Befall von <span class="math inline">\(500\)</span> Trepsen in der Kontrolle an und haben am Ende des Versuches dann <span class="math inline">\(1000\)</span> Trepsen in unserem Versuch vorliegen. In der Behandlung haben wir zu Beginn des Versuches <span class="math inline">\(300\)</span> Trepsen im Feld gezählt und finden nach der Applikation unseres Pflanzenschutzmittels am Ende des Versuches noch <span class="math inline">\(30\)</span> Trepsen wieder. Dann können wir einmal die Zahlen in die Formel einsetzen.</p>
<p><span class="math display">\[
WG_{HT} = \left(1 - \cfrac{T_a}{T_b}\cdot\cfrac{C_b}{C_a}\right)  = \left(1 - \cfrac{30}{300}\cdot\cfrac{500}{1000}\right) = 1 - (0.1 \cdot 0.5) = 0.95
\]</span></p>
<p>Wir haben hier nun einen räumlichen und zeitlichen Bezug in unserem Wirkungsgrad abgebildet. Leider haben wir nicht immer einen Befall in unserem Bestand. Der Befall tritt erst während der Applikation auf. Dann müssen wir die Formel nach Abbott nutzen, die sich nur auf die Entwicklung des Befalls am Ende des Versuches konzentriert.</p>
</section>
<section id="sec-effect-abbott" class="level3 page-columns page-full" data-number="21.4.2">
<h3 data-number="21.4.2" class="anchored" data-anchor-id="sec-effect-abbott"><span class="header-section-number">21.4.2</span> Wirkungsgrad nach <span class="citation" data-cites="abbott1925method">Abbott u.&nbsp;a. (<a href="#ref-abbott1925method" role="doc-biblioref">1925</a>)</span></h3>
<p>Im Folgenden wollen wir uns auf die Berechnung des Wirkungsgrad nach Abbott konzentrieren. Der Wirkungsgrad wird sehr häufig genutzt, so dass sich hier eine tiefere Betrachtung lohnt. Wir berechnen hier den Wirkungsgrad nach <span class="citation" data-cites="abbott1925method">Abbott u.&nbsp;a. (<a href="#ref-abbott1925method" role="doc-biblioref">1925</a>)</span> erstmal sehr simpel an einem Beispiel. Dann nutzen wir R um die ganze Berechnung nochmal etwas komplexer durchzuführen. Abschließend schauen wir uns mit der Anpassung von <span class="citation" data-cites="finner1989berechnung">Finner u.&nbsp;a. (<a href="#ref-finner1989berechnung" role="doc-biblioref">1989</a>)</span> noch eine Erweiterung des Wirkungsgrads nach Abbott an. Der Wirkungsgrad <span class="math inline">\(WG\)</span> eines Schutzmittels im Vergleich zur Kontrolle berechnet sich wie folgt.</p>
<p><span class="math display">\[
WG_{Ab} = \left(\cfrac{C_a - T_a}{C_a}\right) = \left(1-\cfrac{T_a}{C_a}\right)
\]</span></p>
<p>mit</p>
<ul>
<li><span class="math inline">\(T_a\)</span> Anzahl lebend in der Behandlung <em>nach</em> Applikation (eng. <em>after</em>)</li>
<li><span class="math inline">\(C_a\)</span> Anzahl lebend in der Kontrolle <em>nach</em> Applikation (eng. <em>after</em>)</li>
</ul>
<p>Wir können auch nur den räumlichen Bezug mit dem Wirkungsgrad nach Abbott abbilden. Hier nochmal ein kleines numerisches Beispiel von oben mit <span class="math inline">\(T_b = 300\)</span> sowie <span class="math inline">\(T_a = 30\)</span> und <span class="math inline">\(C_b = 500\)</span> sowie <span class="math inline">\(C_a = 1000\)</span>. Wir fangen also in einer Population mit einem Befall von <span class="math inline">\(500\)</span> Trepsen in der Kontrolle an und haben am Ende des Versuches dann <span class="math inline">\(1000\)</span> Trepsen in unserem Versuch vorliegen. In der Behandlung haben wir zu Beginn des Versuches <span class="math inline">\(300\)</span> Trepsen im Feld gezählt und finden nach der Applikation unseres Pflanzenschutzmittels am Ende des Versuches noch <span class="math inline">\(30\)</span> Trepsen wieder. Hier ist es wichtig, dass wir uns nicht den Zusammenhang über die Zeit anschauen können. Also entweder betrachten wir den Zusammenhang von <em>nach</em> unser Applikation oder aber den Vergleich von vorher und nachher von unserer Behandlung.</p>
<p><span class="math display">\[
WG_{Ab} = \left(1-\cfrac{T_a}{C_a}\right) = \left(1-\cfrac{30}{1000}\right) = 0.97
\]</span></p>
<p>Oder wir konzentrieren uns eben nur auf den zeitlichen Bezug in dem wir die Formel nach Abbott etwas modidifzieren und nur auf die Behandlung <span class="math inline">\(T\)</span> schauen.</p>
<p><span class="math display">\[
WG_{Ab^*} = \left(1-\cfrac{T_a}{T_b}\right) = \left(1-\cfrac{30}{300}\right) = 0.90
\]</span></p>
<p>Natürlich ist die Formel wieder auf sehr einfachen Daten gut zu verstehen. Wir haben aber später dann in der Anwendung natürlich Datensätze, so dass wir uns hier einmal zwei Beispieldaten anschauen wollen. Zuerst schauen wir uns einen Datensatz zu dem Befall mit Trespe, einem Wildkraut, an. Wir haben also Parzellen in denen sich die Trespe ausbreitet und haben verschiedene Behandlungen durchgeführt. Wichtig hierbei, wir haben auch Parzellen wo wir nichts gemacht haben, das ist dann unsere positive Kontrolle (<em>ctrl</em>).</p>
<div class="cell">
<div id="tbl-effect-trespe" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-effect-trespe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.5— Trespebefall in einem randomisierten Blockdesign mit vier Behandlungsvarianten.
</figcaption>
<div aria-describedby="tbl-effect-trespe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">variante</th>
<th style="text-align: center;">block_1</th>
<th style="text-align: center;">block_2</th>
<th style="text-align: center;">block_3</th>
<th style="text-align: center;">block_4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">crtl</td>
<td style="text-align: center;">16.0</td>
<td style="text-align: center;">16.0</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">11.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">4.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">2.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">10.4</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">8.0</td>
<td style="text-align: center;">8.8</td>
<td style="text-align: center;">7.2</td>
<td style="text-align: center;">4.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In der <a href="#tbl-effect-trespe-abbott" class="quarto-xref">Tabelle&nbsp;<span>21.6</span></a> haben wir dann einmal den Wirkungsgrad nach Abbott <code>wg_abbott</code> aus dem mittleren Befall über die vier Blöcke berechnet. Wir lassen hier mal weg, dass wir in einigen Parzellen mehr Befall hatten und deshab negative Wirkunsggrade. Hier hilft dann der Mittelwert.</p>
<div class="cell">
<div id="tbl-effect-trespe-abbott" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-effect-trespe-abbott-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.6— Trespebefall in einem randomisierten Blockdesign mit vier Behandlungsvarianten ergänzt um den Wirkungsgrad nach Abbott <code>wg_abbott</code> berechnet aus dem mittleren Befall über die Blöcke.
</figcaption>
<div aria-describedby="tbl-effect-trespe-abbott-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">variante</th>
<th style="text-align: center;">block_1</th>
<th style="text-align: center;">block_2</th>
<th style="text-align: center;">block_3</th>
<th style="text-align: center;">block_4</th>
<th style="text-align: center;">mean</th>
<th style="text-align: center;">wg_abbott</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">crtl</td>
<td style="text-align: center;">16.0</td>
<td style="text-align: center;">16.0</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">11.2</td>
<td style="text-align: center;">12.0</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">4.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">2.8</td>
<td style="text-align: center;">0.77</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">10.4</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">0.73</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">8.0</td>
<td style="text-align: center;">8.8</td>
<td style="text-align: center;">7.2</td>
<td style="text-align: center;">4.0</td>
<td style="text-align: center;">7.0</td>
<td style="text-align: center;">0.42</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Dann das Ganze auch nochmal händisch aufbereitet und berechnet. Wir erhalten die gleichen Werte wie auch oben in der Tabelle.</p>
<p><span class="math display">\[
\begin{align}
WG_2 &amp;= \left(1 - \cfrac{2.8}{12}\right) = 0.77 \\
WG_3 &amp;= \left(1 - \cfrac{3.2}{12}\right) = 0.73 \\
WG_4 &amp;= \left(1 - \cfrac{7.0}{12}\right) = 0.42
\end{align}
\]</span></p>
<p>Jetzt wollen wir etwas tiefer in die Thematik einsteigen und müssen daher einmal die Daten umwandeln, da unsere Daten nicht im Long-Format vorliegen. Wir müssen die Daten erst noch anpassen und dann die Spalte <code>block</code> in einen Faktor umwandeln. Laden wir einmal den Datensatz in R und verwandeln das Wide-Format in das Long-Format. Dann natürlich wie immer alle Faktoren als Faktoren mutieren.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>trespe_tbl <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/raubmilben_data.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"trespe"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(block_1<span class="sc">:</span>block_4,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"block"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"count"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">block =</span> <span class="fu">factor</span>(block, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">variante =</span> <span class="fu">as_factor</span>(variante))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#fig-effect-1" class="quarto-xref">Abbildung&nbsp;<span>21.1</span></a> sehen wir nochmal die orginalen, untransformierten Daten sowie die <span class="math inline">\(log\)</span>-transformierten Daten. Wir nutzen die Funktion <code>log1p()</code> um die Anzahl künstlich um 1 zu erhöhen, damit wir Nullen in den Zähldaten zum Logarithmieren vermeiden.</p>
<div class="cell page-columns page-full" data-layout-nrow="1" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trespe_tbl, <span class="fu">aes</span>(variante, count, <span class="at">fill =</span> block)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">"y"</span>, <span class="at">stackdir =</span> <span class="st">"center"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Behandlungsvariante"</span>, <span class="at">y =</span> <span class="st">"Anzahl"</span>, <span class="at">fill =</span> <span class="st">"Block"</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trespe_tbl, <span class="fu">aes</span>(variante, <span class="fu">log1p</span>(count), <span class="at">fill =</span> block)) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">"y"</span>, <span class="at">stackdir =</span> <span class="st">"center"</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Behandlungsvariante"</span>, <span class="at">y =</span> <span class="st">"log(Anzahl)"</span>, <span class="at">fill =</span> <span class="st">"Block"</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-effect-1" class="quarto-layout-panel page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-effect-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<div class="quarto-layout-row page-columns page-full">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-effect-1" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-effect-1-1" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-effect-1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="stat-tests-effect_files/figure-html/fig-effect-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-effect-1" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-effect-1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Verteilung der Werte auf der originalen Skala.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-effect-1" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-effect-1-2" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-effect-1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="stat-tests-effect_files/figure-html/fig-effect-1-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-effect-1" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-effect-1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Verteilung der Werte auf der logarithmischen Skala. Beobachtungen mit einer 0 Zählung wurden auf 1 gesetzt.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effect-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.1— Dotplot der Anzahl an Trespen je Sorte und Block.
</figcaption>
</figure>
</div>
</div>
<p>Nun geht es eigentlich ganz fix den Wirkungsgrad nach Abbott mit einer linearen Poisson Regression zu berechnen. Erstmal schätzen wir eine Poissonregression mit der Anzahl der Trespen als Outcome. Es ist wichtig in der Funktion <code>glm()</code> die Option <code>family = poisson</code> zu setzen. Sonst rechnen wir auch keine Poissonregression. Wir haben hier im Prinzip die effizientere Variante vorliegen, da wir durch die Modellierung auch noch andere Einflussfaktoren mit ins Modell nehemn können als nur den Block. Da wir hier aber nichts Weiteres gemessen haben, bleibt es bei dem einfachen Modell.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(count <span class="sc">~</span> variante <span class="sc">+</span> block, <span class="at">data =</span> trespe_tbl, <span class="at">family =</span> poisson)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir nutzen die Schätzer aus dem Modell um mit der Funktion <code>emmeans()</code> die Raten in jeder Variante gemittelt über alle Blöcke zu berechnen. Dann müssen wir nur noch die Formel nach Abbott nutzen um jede Rate in das Verhältnis zur Rate der Kontrolle <code>rate[1]</code> zu setzen. Wir erhalten dann den Wirkungsgrad nach Abbott für unsere drei Varianten. Wie wir sehen, sind auch hier die Werte gleich.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>res_trespe_tbl <span class="ot">&lt;-</span> fit <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span>variante, <span class="at">type =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">WG_abbott =</span> (rate[<span class="dv">1</span>] <span class="sc">-</span> rate)<span class="sc">/</span>rate[<span class="dv">1</span>],</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">WG_abbott_per =</span> <span class="fu">percent</span>(WG_abbott)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(variante, rate, WG_abbott, WG_abbott_per)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>res_trespe_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 4
  variante  rate WG_abbott WG_abbott_per
  &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;        
1 crtl     10.8      0     0.0%         
2 2         2.52     0.767 76.7%        
3 3         2.89     0.733 73.3%        
4 4         6.31     0.417 41.7%        </code></pre>
</div>
</div>
<p>Damit haben wir den Wirkungsgard <span class="math inline">\(WG_{abbott}\)</span> für unser Trepsenbeispiel einmal berechnet. Die Interpretation ist dann eigentlich sehr intuitiv. Wir haben zum Beispiel bei Variante 2 einen Wirkungsgrad von 76.7% der Kontrolle und somit auch eine Reduzierung von 76.7% der Trepsen auf unseren Parzellen im Vergleich zur Kontrolle.</p>
<p>Wir können auch einfach testen, ob sich die Kontrolle von den anderen Varianten sich unterscheidet. Wir nutzen dafür wieder die Funktion <code>emmeans()</code> und vergleichen alle Varianten zu der Kontrolle. Da die Kontrolle in der ersten Zeile steht bzw. das erste Level des Faktors <code>variante</code> ist, müssen wir noch die Referenz mit <code>ref = 1</code> setzen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(trt.vs.ctrlk <span class="sc">~</span> variante, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">ref =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pluck</span>(<span class="st">"contrasts"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast ratio     SE  df null z.ratio p.value
 2 / crtl 0.233 0.0774 Inf    1  -4.385  &lt;.0001
 3 / crtl 0.267 0.0839 Inf    1  -4.202  0.0001
 4 / crtl 0.583 0.1387 Inf    1  -2.267  0.0633

Results are averaged over the levels of: block 
P value adjustment: dunnettx method for 3 tests 
Tests are performed on the log scale </code></pre>
</div>
</div>
<p>Wir wir sehen, sind alle Varianten, bis auf die Variante 4, signifikant unterschiedlich zu der Kontrolle. Nun könnten wir uns auch Fragen in wie weit sich die Wirkungsgrade untereinander unterscheiden. Dafür müssen wir dann die Anteile mit der Funktion <code>pairwise.prop.test()</code> paarweise Vergleichen. Da wir natürlich auf die Kontrolle standardisieren hat der Vergleich mit der Kontrolle nur so halbwegs Sinn, mag aber von Interesse sein.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.prop.test</span>(<span class="at">x =</span> res_trespe_tbl<span class="sc">$</span>WG_abbott <span class="sc">*</span> <span class="dv">100</span>, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>, <span class="dv">100</span>, <span class="dv">100</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">p.adjust.method =</span> <span class="st">"none"</span>) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Pairwise comparison of proportions 

data:  res_trespe_tbl$WG_abbott * 100 out of c(100, 100, 100, 100) 

  1       2       3      
2 &lt; 2e-16 -       -      
3 &lt; 2e-16 0.7     -      
4 1.4e-12 1.0e-06 1.2e-05

P value adjustment method: none </code></pre>
</div>
</div>
<p>Wir sehen, dass sich alle Varianten in ihrem Wirkungsgrad von der Kontrolle unterscheiden, die Kontrolle hat hier die ID 1. Die Variante 4 unterscheidet sich von allen anderen Varianten in ihrem Wirkungsgrad.</p>
<p>Im zweiten Beispiel wollen wir uns mit dem geometrischen Mittel <span class="math inline">\(WG_{geometric}\)</span> als Schätzer für den Wirkungsgrad beschäftigen. Hier kochen wir dann einmal die Veröffentlichung von <span class="citation" data-cites="finner1989berechnung">Finner u.&nbsp;a. (<a href="#ref-finner1989berechnung" role="doc-biblioref">1989</a>)</span> nach. Dafür brauchen wir einmal die Daten zu den Raubmilben, die ich schon als Exceldatei aufbereitet habe. Wie immer sind die Rohdaten im Wide-Format, wir müssen aber im Long-Format rechnen. Da bauen wir uns also einmal schnell die Daten um. Dann wollen wir noch die Anzahlen der Raubmilben logarithmieren, so dass wir jede Anzahl um 1 erhöhen um logarithmierte Nullen zu vermeiden. Das ganze machen wir dann in einem Rutsch mit der Funktion <code>log1p()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mite_tbl <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/raubmilben_data.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"mite"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(block_1<span class="sc">:</span>block_5,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"block"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"count"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">block =</span> <span class="fu">factor</span>(block, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">sorte =</span> <span class="fu">as_factor</span>(sorte),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_count =</span> <span class="fu">log1p</span>(count))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-effect-mite" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-effect-mite-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.7— Raubmilbenbefall auf acht Sorten und einer Kontrolle.
</figcaption>
<div aria-describedby="tbl-effect-mite-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">sorte</th>
<th style="text-align: center;">block_1</th>
<th style="text-align: center;">block_2</th>
<th style="text-align: center;">block_3</th>
<th style="text-align: center;">block_4</th>
<th style="text-align: center;">block_5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">302</td>
<td style="text-align: center;">108</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">26</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">154</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">41</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">141</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">37</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">240</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ctrl</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">20</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Schauen wir uns einmal die Daten in der <a href="#fig-effect-2" class="quarto-xref">Abbildung&nbsp;<span>21.2</span></a> an. Wichtig ist, dass wir usn merken, dass in unseren Daten jetzt die Kontrolle an der neuten Position ist. Das ist eben in diesen Daen so, ich hätte die Sortierung dann anders gemacht. Aber wir arbeiten hier mit dem was wir vorliegen haben.</p>
<div class="cell page-columns page-full" data-layout-nrow="1" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mite_tbl, <span class="fu">aes</span>(sorte, count, <span class="at">fill =</span> block)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">"y"</span>, <span class="at">stackdir =</span> <span class="st">"center"</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sorten"</span>, <span class="at">y =</span> <span class="st">"Anzahl"</span>, <span class="at">fill =</span> <span class="st">"Block"</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mite_tbl, <span class="fu">aes</span>(sorte, <span class="fu">log1p</span>(count), <span class="at">fill =</span> block)) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">"y"</span>, <span class="at">stackdir =</span> <span class="st">"center"</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sorten"</span>, <span class="at">y =</span> <span class="st">"log(Anzahl)"</span>, <span class="at">fill =</span> <span class="st">"Block"</span>) <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_okabeito</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-effect-2" class="quarto-layout-panel page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-effect-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<div class="quarto-layout-row page-columns page-full">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-effect-2" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-effect-2-1" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-effect-2-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="stat-tests-effect_files/figure-html/fig-effect-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-effect-2" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-effect-2-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Verteilung der Werte auf der originalen Skala.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-effect-2" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-effect-2-2" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-effect-2-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="stat-tests-effect_files/figure-html/fig-effect-2-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-effect-2" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-effect-2-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Verteilung der Werte auf der logarithmischen Skala. Beobachtungen mit einer 0 Zählung wurden auf 1 gesetzt.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effect-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.2— Dotplot der Anzahl an Raubmilden je Sorte und Block.
</figcaption>
</figure>
</div>
</div>
<p>Wir brauchen jetzt eine Helferfunktion, die uns aus <span class="math inline">\(Pr\)</span> die Gegenwahrscheinlichkeit <span class="math inline">\(1 - Pr\)</span> berechnet. Auch wollen wir dann die Prozentangabe der Gegenwahrscheinlichkeit, also die Gegenwahrscheinlichkeit <span class="math inline">\(1 - Pr\)</span> multipliziert mit Einhundert. Dann brauchen wir als Variable noch die Gruppengröße <span class="math inline">\(n_g\)</span>, die bei uns ja bei 5 liegt. Wir haben pro Sorte fünf Beobachtungen je Block.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>get_q <span class="ot">&lt;-</span> <span class="cf">function</span>(x){<span class="dv">100</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x)}</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>n_group <span class="ot">&lt;-</span> <span class="dv">5</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir nutezn jetzt das <a href="eda-descriptive.html#sec-desc-stat-geometric">geometrisches Mittel</a> um den Effekt der Behandlung bzw. Sorte im Verhältnis zur Kontrolle zu berechnen. Hierbei ist es wichtig sich zu erinnern, dass wir nicht alle paarweisen Vergleiche rechnen, sondern nur jede Sorte <span class="math inline">\(j\)</span> zu der Kontrolle <span class="math inline">\(ctrl\)</span> vergleichen. Dabei nutzen wir dann das Verhältnis der geometrisches Mittel um zu Beschreiben um wie viel weniger Befall mit Raubmilden wir in den Sorten <span class="math inline">\(y_j\)</span> im Verhältnis zur Kontrolle <span class="math inline">\(y_{ctrl}\)</span> vorliegen haben.</p>
<p><span class="math display">\[
\Delta_{geometric} = \left(\cfrac{\prod_{i=1}^n y_j}{\prod_{i=1}^n y_{ctrl}}\right)^{1/n_j} \mbox{ für Sorte } j
\]</span></p>
<p>Berechnen wir also als erstes einmal das Produkt aller gezählten Raubmilden pro Sorte und speichern das Ergebnis in der Spalte <code>prod</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mite_wg_gemetric_tbl <span class="ot">&lt;-</span> mite_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count =</span> count <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sorte) <span class="sc">%&gt;%</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">prod =</span> <span class="fu">prod</span>(count)) </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>mite_wg_gemetric_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 x 2
  sorte       prod
  &lt;fct&gt;      &lt;dbl&gt;
1 1            198
2 2     2576106000
3 3       10108800
4 4      497624400
5 5      916413472
6 6      673639344
7 7           3672
8 8             20
9 ctrl   186729543</code></pre>
</div>
</div>
<p>Jetzt können wir im nächsten Schritt einmal das <span class="math inline">\(\Delta_{geometric}\)</span> berechnen und dann den Wirkungsgrad über die Gegenwahrscheinlichkeit. Wichtig ist hier, dass die Kontrolle in der neunten Zeile ist. Daher teilen wir immer durch das Produkt an neunter Position mit <code>prod[9]</code>. Wir sehen ganz klar, das wir ein Delta von 1 für die Kontrolle erhalten, da wir ja die Kontrolle ins Verhältnis zur Kontrolle setzen. Damit sollte der Rest auch geklappt haben. Den Wirkungsgrad der Sorten in Prozent gegen Raubmilbenbefall im Verhältnis zur Kontrolle können wir dann direkt ablesen. Die Funktion <code>percent()</code> berechnet uns aus den Gegenwahrscheinlichkeiten dann gleich die Prozent. Wir brauchen daher hier noch nicht unsere Funktion <code>get_q()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mite_wg_gemetric_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">delta_geometric =</span> (prod<span class="sc">/</span>prod[<span class="dv">9</span>])<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>n_group),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">WG_geometric =</span> <span class="fu">percent</span>(<span class="dv">1</span> <span class="sc">-</span> delta_geometric))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 x 4
  sorte       prod delta_geometric WG_geometric
  &lt;fct&gt;      &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;       
1 1            198          0.0638 93.6%       
2 2     2576106000          1.69   -69.0%      
3 3       10108800          0.558  44.2%       
4 4      497624400          1.22   -21.7%      
5 5      916413472          1.37   -37.5%      
6 6      673639344          1.29   -29.3%      
7 7           3672          0.114  88.6%       
8 8             20          0.0404 96.0%       
9 ctrl   186729543          1      0.0%        </code></pre>
</div>
</div>
<p>Soweit haben wir erstmal nur eine andere Variante des Wirkungsgrades berechnet. Im Gegensatz zu der Berechnung nach <span class="citation" data-cites="abbott1925method">Abbott u.&nbsp;a. (<a href="#ref-abbott1925method" role="doc-biblioref">1925</a>)</span> können wir aber bei den geometrischen Wirkungsgrad auch ein einseitiges 95% Konfidenzintervall <span class="math inline">\([-\infty; upper]\)</span> angeben. Dafür müssen wir erstmal den Exponenten <span class="math inline">\(a\)</span> berechnen und mit diesem dann die obere Konfidenzschranke <span class="math inline">\(upper\)</span>. Dafür brauchen wir dann doch ein paar statistische Maßzahlen.</p>
<p><span class="math display">\[
\begin{align}
a &amp;= \sqrt{2/n} \cdot s \cdot t_{\alpha=5\%} + \ln(1 - \Delta_{geometric})\\
upper &amp;= 1 - e^a
\end{align}
\]</span></p>
<p>Wir brauchen zum einen die Freiheitsgrade der Residuen <code>df.residual</code> sowie den Standardfehler der Residuen <code>sigma</code> oder <span class="math inline">\(s\)</span>. Beides erhalten wir aus einem linearen Modell auf den logarithmierten Anzahlen der Raubmilben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>residual_tbl <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_count <span class="sc">~</span> sorte <span class="sc">+</span> block, <span class="at">data =</span> mite_tbl) <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(df.residual, sigma)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>residual_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 2
  df.residual sigma
        &lt;int&gt; &lt;dbl&gt;
1          32 0.962</code></pre>
</div>
</div>
<p>Mit den Freiheitsgraden der Residuen können wir jetzt den kritischen Wert <span class="math inline">\(t_{\alpha = 5\%}\)</span> aus der <span class="math inline">\(t\)</span>-Verteilung berechnen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>t_quantile <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.05</span>, <span class="at">df =</span> residual_tbl<span class="sc">$</span>df.residual, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>t_quantile</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.693889</code></pre>
</div>
</div>
<p>Wir können jetzt unseren Datensatz <code>mite_wg_gemetric_tbl</code> um die Spalte mit den Werten des Exponenten <span class="math inline">\(a\)</span> ergänzen und aus diesem dann die obere Schranke des einseitigen 95% Konfidenzintervall berechnen. Die Werte für die Kontrolle ergeben keinen biologischen Sinn und sind ein mathematisches Artefakt. Wir kriegen halt immer irgendwelche Zahlen raus.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mite_res_tbl <span class="ot">&lt;-</span> mite_wg_gemetric_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">delta_geometric =</span> (prod<span class="sc">/</span>prod[<span class="dv">9</span>])<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>n_group),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">WG_geometric =</span> <span class="fu">get_q</span>(delta_geometric),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">a =</span> <span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">/</span>n_group) <span class="sc">*</span> residual_tbl<span class="sc">$</span>sigma <span class="sc">*</span> t_quantile <span class="sc">+</span> <span class="fu">log</span>(delta_geometric),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">upper =</span> <span class="fu">get_q</span>(<span class="fu">exp</span>(a)))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>mite_res_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 x 6
  sorte       prod delta_geometric WG_geometric      a  upper
  &lt;fct&gt;      &lt;dbl&gt;           &lt;dbl&gt;        &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 1            198          0.0638         93.6 -1.72    82.1
2 2     2576106000          1.69          -69.0  1.56  -374. 
3 3       10108800          0.558          44.2  0.447  -56.4
4 4      497624400          1.22          -21.7  1.23  -241. 
5 5      916413472          1.37          -37.5  1.35  -285. 
6 6      673639344          1.29          -29.3  1.29  -262. 
7 7           3672          0.114          88.6 -1.14    67.9
8 8             20          0.0404         96.0 -2.18    88.7
9 ctrl   186729543          1               0    1.03  -180. </code></pre>
</div>
</div>
<p>Wir räumen nochmal die Ausgabe auf und konzentrieren uns auf die Spalten und runden einmal die Ergebnisse.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>mite_res_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sorte, WG_geometric, upper) <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">round</span>(.x, <span class="dv">2</span>))) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 x 3
  sorte WG_geometric  upper
  &lt;fct&gt;        &lt;dbl&gt;  &lt;dbl&gt;
1 1             93.6   82.1
2 2            -69.0 -374. 
3 3             44.2  -56.4
4 4            -21.7 -241. 
5 5            -37.5 -285. 
6 6            -29.2 -262. 
7 7             88.6   67.9
8 8             96.0   88.7
9 ctrl           0   -180. </code></pre>
</div>
</div>
<p>Wir können wir jetzt das einseitige 95% Konfidenzintervall interpretieren? In der Sorte 1 erhalten wir einen Wirkungsgrad von 93.6% und mit 95% Sicherheit mindestens einen Wirkungsgrad von 82.1%. Damit haben wir auch eine untere Schranke für unseren Wirkungsgradschätzer. Wir berichten für die Sorte 1 einen Wirkungsgrad von 93.6% [<span class="math inline">\(-\infty\)</span>; 82.1%].</p>
<p>Genauso können wir aber auch den Wirkungsgrad nach <span class="citation" data-cites="abbott1925method">Abbott u.&nbsp;a. (<a href="#ref-abbott1925method" role="doc-biblioref">1925</a>)</span> nochmal auf den Daten berechnen. Dafür müssen wir nur eine Poissonregression auf der Anzahl der Raubmilben rechnen. Die angepassten Werte können wir dann verwenden um den <span class="math inline">\(WG_{abbott}\)</span> zu schätzen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(count <span class="sc">~</span> sorte <span class="sc">+</span> block, <span class="at">data =</span> mite_tbl, <span class="at">family =</span> poisson)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir nutzen hier dann die Funktion <code>emmeans()</code> um die mittlere Anzahl an Raubmilben über alle Blöcke zu ermitteln. Dann können wir auch schon den <span class="math inline">\(WG_{abbott}\)</span> berechnen. Wichtig ist hier, dass die Referenzkategorie mit der Kontrolle an der neunten Stelle bzw. Zeile steht. Deshalb müssen wir auch hier durch <code>prod[9]</code> teilen. Achtung, die <span class="math inline">\(p\)</span>-Werte haben hier keine tiefere Bedeutung im Bezug auf den Wirkungsgrad und deshalb schauen wir uns diese Werte auch gar nicht tiefer an.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>res_mite_tbl <span class="ot">&lt;-</span> fit <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(<span class="sc">~</span>sorte, <span class="at">type =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">WG_abbott =</span> (rate[<span class="dv">9</span>] <span class="sc">-</span> rate)<span class="sc">/</span>rate[<span class="dv">9</span>],</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">WG_abbott_per =</span> <span class="fu">percent</span>(WG_abbott)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sorte, WG_abbott, WG_abbott_per, rate)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>res_mite_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 x 4
  sorte WG_abbott WG_abbott_per  rate
  &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
1 1         0.900 90.0%          4.49
2 2        -1.18  -118.4%       98.0 
3 3         0.216 21.6%         35.2 
4 4        -0.308 -30.8%        58.7 
5 5        -0.376 -37.6%        61.7 
6 6        -0.904 -90.4%        85.4 
7 7         0.880 88.0%          5.38
8 8         0.976 97.6%          1.08
9 ctrl      0     0.0%          44.9 </code></pre>
</div>
</div>
<p>Wenn du verwirrt bist über die negativen Wirkungsgrade, dann musst du dir klar werden, dass wir immer den Wirkungsgrad im Verhältnis zur Kontrolle berechnen. Wenn du also negative Wirkungsgrade siehst, dann sind die Anzahlen in den Sorten <em>höher</em> als in der Kontrolle. Je nach Fragestellung macht dieses Ergebnis mehr oder weniger Sinn.</p>
<p>Auch hier können wir noch schnell einen statistischen Test rechnen und die Sorten zu der Kontrolle <code>ref = 9</code> vergleichen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans</span>(trt.vs.ctrlk <span class="sc">~</span> sorte, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">ref =</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pluck</span>(<span class="st">"contrasts"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast ratio      SE  df null z.ratio p.value
 1 / ctrl 0.100 0.02098 Inf    1 -10.977  &lt;.0001
 2 / ctrl 2.184 0.16678 Inf    1  10.229  &lt;.0001
 3 / ctrl 0.784 0.07480 Inf    1  -2.551  0.0686
 4 / ctrl 1.308 0.10989 Inf    1   3.196  0.0101
 5 / ctrl 1.376 0.11436 Inf    1   3.841  0.0009
 6 / ctrl 1.904 0.14872 Inf    1   8.244  &lt;.0001
 7 / ctrl 0.120 0.02319 Inf    1 -10.973  &lt;.0001
 8 / ctrl 0.024 0.00991 Inf    1  -9.028  &lt;.0001

Results are averaged over the levels of: block 
P value adjustment: dunnettx method for 8 tests 
Tests are performed on the log scale </code></pre>
</div>
</div>
<p>Wir wir sehen, sind alle Varianten signifikant unterschiedlich zu der Kontrolle bis auf die Sorte 3.</p>
<p>Auch hier können wir die Wirkungsgrade miteinander vergleichen. Aber Achtung, wir können nur Wirkungsgrade zwischen 0 und 1 miteinander sinnvoll vergleichen. Deshalb fliegen bei uns einige an Sorten raus. Darüber hinaus musst du jetzt auch einmal schauen, welche Sorte sich hinter der numerischen ID aus dem <code>pairwise.prop.test()</code> verbirgt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>res_mite_tbl <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(WG_abbott <span class="sc">&lt;</span> <span class="dv">1</span> <span class="sc">&amp;</span> WG_abbott <span class="sc">&gt;=</span> <span class="dv">0</span>) <span class="sc">%$%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairwise.prop.test</span>(<span class="at">x =</span> WG_abbott <span class="sc">*</span> <span class="dv">100</span>, </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n =</span> <span class="fu">rep</span>(<span class="dv">100</span>, <span class="dv">5</span>),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">p.adjust.method =</span> <span class="st">"none"</span>) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Pairwise comparison of proportions 

data:  WG_abbott * 100 out of rep(100, 5) 

  1       2       3       4      
2 &lt; 2e-16 -       -       -      
3 0.821   &lt; 2e-16 -       -      
4 0.053   &lt; 2e-16 0.019   -      
5 &lt; 2e-16 2.7e-06 &lt; 2e-16 &lt; 2e-16

P value adjustment method: none </code></pre>
</div>
</div>
<p>Das letzte Beispiel zeigt nochmal schön, dass wir uns immer überlegen müssen, was wir mit den Wirkungsgraden eigentlich zeigen wollen und welche Wirkungsgrade noch eine biologisch sinnvolle Bedeutung haben.</p>
</section>
<section id="sec-effect-ss" class="level3" data-number="21.4.3">
<h3 data-number="21.4.3" class="anchored" data-anchor-id="sec-effect-ss"><span class="header-section-number">21.4.3</span> Wirkungsgrad nach Sun-Shepard</h3>
<p>Der Wirkungsgrad nach Sun-Shepard bezieht sich auf die Mortalität [%] in unserem Versuch. Wir können müssen hier auch vor der Applikation und nach der Applikation in unserer Kontrolle die Mortalität bestimmen, sonst können wir nicht das <span class="math inline">\(C_{\Delta}\)</span> in der Kontrolle berechnen. Auf der <a href="https://www.ehabsoft.com/ldpline/onlinecontrol.htm">Webseite von Ehab Bakr</a>, auf die sich irgendwie in einem Zirkelschluss alle meine gefundenen Quellen beziehen, steht dann zwar <span class="math inline">\(\pm\)</span> aber ich denke, dass hier ausgesagt werden soll, dass <span class="math inline">\(C_{\Delta}\)</span> negativ oder positiv sein kann. Dann können wir auch auch besser nur Plus schreiben und damit ist dann die Formel auch in sich konsistent. Das passt dann auch zu der Durchführung und dem Beispiel auf der Webseite.</p>
<p><span class="math display">\[
WG_{SS} = \left(\cfrac{T + C_{\Delta}}{1 + C_{\Delta}}\right)
\]</span></p>
<p>und</p>
<p><span class="math display">\[
C_{\Delta} = \left(\cfrac{C_a - C_b}{C_b}\right)
\]</span></p>
<p>mit</p>
<ul>
<li><span class="math inline">\(T\)</span> Sterberate in der Behandlung</li>
<li><span class="math inline">\(C_b\)</span> Anzahl lebend in der Kontrolle <em>nach</em> Applikation (eng. <em>after</em>)</li>
<li><span class="math inline">\(C_a\)</span> Anzahl lebend in der Kontrolle <em>vor</em> Applikation (eng. <em>before</em>)</li>
</ul>
</section>
<section id="sec-effect-so" class="level3" data-number="21.4.4">
<h3 data-number="21.4.4" class="anchored" data-anchor-id="sec-effect-so"><span class="header-section-number">21.4.4</span> Wirkungsgrad nach Schneider-Orelli</h3>
<p>Der Wirkungsgrad nach Schneider-Orelli betrachtet nur die Mortalität nach dem Versuch und ist somit mit dem Wirkungsgrad nach Abbott zu vergleichen. Die Formel ist dabei sehr simpel</p>
<p><span class="math display">\[
WG_{SO} = \left(\cfrac{T_a - C_a}{1 - C_a}\right)
\]</span></p>
<p>mit</p>
<ul>
<li><span class="math inline">\(T_a\)</span> Sterberate in der Behandlung <em>nach</em> Applikation (eng. <em>after</em>)</li>
<li><span class="math inline">\(C_a\)</span> Sterberate in der Kontrolle <em>nach</em> Applikation (eng. <em>after</em>)</li>
</ul>
</section>
</section>
<section id="sec-effect-interrater" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="sec-effect-interrater"><span class="header-section-number">21.5</span> Interrater Reliabilität</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/caution.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Der Grad an Übereinstimmung einer Messung, wenn diese unter identischen Bedingungen jedoch von unterschiedlichen Bewertern wiederholt wird. Hinweis: Anhand der Interrater-Reliabilität wird es möglich, den Grad zu ermitteln, in dem sich die erhaltenen Ergebnisse wiederholen lassen.</p>
<p><span class="citation" data-cites="maclure1987misinterpretation">Maclure und Willett (<a href="#ref-maclure1987misinterpretation" role="doc-biblioref">1987</a>)</span> <a href="https://citeseerx.ist.psu.edu/document?repid=rep1&amp;type=pdf&amp;doi=63e3fc4cf928bc0a12f6c62cace8d94aee34db62">Misinterpretation and misuse of the kappa statistic</a> kappa statistik</p>
<p><a href="https://rdrr.io/cran/irr/man/relInterIntra.html">Funktion <code>relInterIntra()</code></a></p>
<p><a href="http://dwoll.de/rexrepos/posts/interRaterICC.html">Inter-rater-reliability and Intra-class-correlation</a></p>
<p><a href="https://www.andywills.info/rminr/irr.html">Inter-rater reliability</a></p>
<p><a href="https://www.datanovia.com/en/lessons/inter-rater-agreement-chart-in-r/">Inter-Rater Agreement Chart in R</a></p>
<p><a href="https://cran.r-project.org/web/packages/irr/irr.pdf">R Paket <code>{irr}</code></a></p>
<p><a href="https://www.datanovia.com/en/lessons/cohens-kappa-in-r-for-two-categorical-variables/">Cohen’s Kappa in R: For Two Categorical Variables</a></p>
<p><span class="math display">\[
\kappa = \cfrac{p_0 - p_e}{1 - p_e}
\]</span></p>
<p>mit</p>
<ul>
<li><span class="math inline">\(p_0\)</span> Anteil der beobachteten Übereinstimmung</li>
<li><span class="math inline">\(p_e\)</span> Anteil der veränderten Übereinstimmung</li>
</ul>
<dl>
<dt>Cohen’s Kappa <span class="math inline">\(\kappa\)</span></dt>
<dd>
<p>Cohen’s Kappa kann von -1 (keine Übereinstimmung) bis +1 (perfekte Übereinstimmung) reichen. Wenn <span class="math inline">\(\kappa = 0\)</span> ist, ist die Übereinstimmung nicht besser als das, was durch Zufall erreicht werden würde. Wenn <span class="math inline">\(\kappa\)</span> negativ ist, ist die Übereinstimmung geringer als die zufällig erwartete Übereinstimmung. Wenn <span class="math inline">\(\kappa\)</span> positiv ist, übersteigt die Übereinstimmung der Bewerter die zufällige Übereinstimmung.</p>
</dd>
</dl>
<p>Text dazwischen</p>
<div id="tbl-2x2-kappa" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2-kappa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;21.8— Eine 2x2 Tabelle als Beispiel.
</figcaption>
<div aria-describedby="tbl-2x2-kappa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Bewerter 1</strong></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>ja</em></td>
<td style="text-align: center;"><em>nein</em></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Bewerter 2</strong></td>
<td style="text-align: center;"><em>ja (1)</em></td>
<td style="text-align: center;"><span class="math inline">\(25_{\;\Large a}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(10_{\;\Large b}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><em>nein (0)</em></td>
<td style="text-align: center;"><span class="math inline">\(15_{\;\Large c}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(20_{\;\Large d}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math display">\[
p_0 = \cfrac{a + d}{N} = \cfrac{25 + 20}{70} = 0.643
\]</span></p>
<p><span class="math display">\[
p_e^{yes} = \cfrac{a + b}{N} \cdot \cfrac{a + c}{N} = \cfrac{25+10}{70} \cdot \cfrac{25+15}{70} = 0.5 \cdot 0.57 = 0.285
\]</span></p>
<p><span class="math display">\[
p_e^{no} = \cfrac{c + d}{N} \cdot \cfrac{b + d}{N} = \cfrac{15+20}{70} \cdot \cfrac{10+20}{70} = 0.5 \cdot 0.428 = 0.214
\]</span></p>
<p><span class="math display">\[
p_e = 0.285 +0.214 = 0.499
\]</span></p>
<p><span class="math display">\[
\kappa = \cfrac{0.643 - 0.499}{1 - 0.499} = 0.28
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contingency table</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>xtab <span class="ot">&lt;-</span> <span class="fu">as.table</span>(<span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">10</span>), <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">20</span>)))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive statistics</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>diagonal.counts <span class="ot">&lt;-</span> <span class="fu">diag</span>(xtab)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">sum</span>(xtab)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>row.marginal.props <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(xtab)<span class="sc">/</span>N</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>col.marginal.props <span class="ot">&lt;-</span> <span class="fu">colSums</span>(xtab)<span class="sc">/</span>N</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute kappa (k)</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>Po <span class="ot">&lt;-</span> <span class="fu">sum</span>(diagonal.counts)<span class="sc">/</span>N</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>Pe <span class="ot">&lt;-</span> <span class="fu">sum</span>(row.marginal.props<span class="sc">*</span>col.marginal.props)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> (Po <span class="sc">-</span> Pe)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> Pe)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>k</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2857143</code></pre>
</div>
</div>
<p><a href="https://bjoernwalther.com/cohens-kappa-in-r-berechnen/">Cohens Kappa</a></p>
<p><a href="https://www.datanovia.com/en/lessons/intraclass-correlation-coefficient-in-r/">Intraclass Correlation Coefficient in R</a></p>
</section>
<section id="referenzen" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-abbott1925method" class="csl-entry" role="listitem">
Abbott WS, others. 1925. A method of computing the effectiveness of an insecticide. J. econ. Entomol 18: 265–267.
</div>
<div id="ref-finner1989berechnung" class="csl-entry" role="listitem">
Finner H, Kunert J, Sonnemann E. 1989. <span>Ü</span>ber die Berechnung des Wirkungsgrades von Pflanzenschutzmitteln. Nachrichtenblatt des Deutschen Pflanzenschutzdienstes (Braunschweig) 41: 145–149.
</div>
<div id="ref-george2020s" class="csl-entry" role="listitem">
George A, Stead TS, Ganti L. 2020. What’s the risk: differentiating risk ratios, odds ratios, and hazard ratios? Cureus 12.
</div>
<div id="ref-grant2014converting" class="csl-entry" role="listitem">
Grant RL. 2014. Converting an odds ratio to a range of plausible relative risks for better communication of research findings. Bmj 348.
</div>
<div id="ref-henderson1955tests" class="csl-entry" role="listitem">
Henderson CF, Tilton EW. 1955. Tests with acaricides against the brown wheat mite. Journal of economic entomology 48: 157–161.
</div>
<div id="ref-maclure1987misinterpretation" class="csl-entry" role="listitem">
Maclure M, Willett WC. 1987. Misinterpretation and misuse of the kappa statistic. American journal of epidemiology 126: 161–169.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./stat-tests-theorie.html" class="pagination-link" aria-label="Die Testtheorie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-tests-pretest.html" class="pagination-link" aria-label="Der Pre-Test oder Vortest">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Pre-Test oder Vortest</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Bio Data Science wurde von Jochen Kruppa-Scheetz geschrieben.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jkruppa/jkruppa.github.io/edit/master/stat-tests-effect.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/blob/master/stat-tests-effect.qmd" class="toc-action"><i class="bi empty"></i>Quellcode anzeigen</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Dieses Openbook wurde mit <a href="https://quarto.org/">Quarto</a> erstellt.</p>
</div>
  </div>
</footer>




</body></html>