<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 42&nbsp; Multinomiale / Ordinale logistische Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-logistic.html" rel="next">
<link href="./stat-modeling-poisson.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><link href="site_libs/tabwid-1.1.2/tabwid.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen und Hunden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen, Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes-site.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren in Habitaten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Von Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Friedman Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">Klassifikation oder maschinelles Lernen</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Random Forest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Support vector machines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Neural networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-deep-learning.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Deep learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-bewertungsbogen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Bewertungsbogen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Modulbeschreibung</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#annahmen-an-die-daten" id="toc-annahmen-an-die-daten" class="nav-link active" data-scroll-target="#annahmen-an-die-daten"> <span class="header-section-number">42.1</span> Annahmen an die Daten</a></li>
  <li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"> <span class="header-section-number">42.2</span> Genutzte R Pakete für das Kapitel</a></li>
  <li><a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"> <span class="header-section-number">42.3</span> Daten</a></li>
  <li><a href="#sec-ordinal" id="toc-sec-ordinal" class="nav-link" data-scroll-target="#sec-ordinal"> <span class="header-section-number">42.4</span> Ordinale logistische Regression</a></li>
  <li><a href="#cumulative-link-models-clm-f%C3%BCr-ordinale-daten" id="toc-cumulative-link-models-clm-für-ordinale-daten" class="nav-link" data-scroll-target="#cumulative-link-models-clm-f%C3%BCr-ordinale-daten"> <span class="header-section-number">42.5</span> Cumulative Link Models (CLM) für ordinale Daten</a></li>
  <li><a href="#sec-multinom" id="toc-sec-multinom" class="nav-link" data-scroll-target="#sec-multinom"> <span class="header-section-number">42.6</span> Multinomiale logistische Regression</a></li>
  <li><a href="#logistische-regression-als-ausweg" id="toc-logistische-regression-als-ausweg" class="nav-link" data-scroll-target="#logistische-regression-als-ausweg"> <span class="header-section-number">42.7</span> Logistische Regression als Ausweg</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-multinom-ordinal" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell">

</div>
<p><em>Version vom November 14, 2022 um 13:49:02</em></p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Einführung in die Multinomiale / Ordinale logistische Regression per Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/CQQEXiYASUk">Multinomiale / Ordinale logistische Regression</a> als Video Reihe. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>
<p>Was machen wir wenn wir ein Outcome haben mit mehr als zwei Kategorien. Wenn wir nur zwei Kategorien hätten, dann würden wir eine logistische Regression rechnen. Wenn wir mehr als zwei Kategorien haben, dann sind wir in dem Fall der multinomialen / ordinalen logistischen Regression. Wir rechnen eine multinomialen Regression, wenn wir keine Ordnung in den Kategorien in dem Outcome haben. Wenn wir eine Ordnung vorliegen haben, dann nutzen wir die ordinale Regression. Wir werden uns erstmal eine ordinale Regression anschauen mit nur drei geordenten Stufen. Dann schauen wir uns einmal wie wir eine ordinale Regression auf Boniturnoten in der Likert-Skala rechnen. Wir machen das getrennt, denn wir sind bei wenigen geordneten Kategorien meistens noch am Effekt zwischen den Kategorien interessiert. Im Gegensatz wollen wir bei einem Outcome mit Boniturnoten einen Gruppenvergleich rechnen. Dann interessiert uns der Unterschied und die Effekte zwischen den Boniturnoten nicht. Deshalb trennen wir das hier etwas auf.</p>
<p>Im zweiten Teil wollen wir uns dann noch eine multinominale Regression auf ungeordneten Kategorien eines Outcomes anschauen. Korrelterweise tuen wir nur so, als wäre unser vorher geordnetes Outcome dann eben ungeordnet. Das macht dann aber bei deiner Anwendung dann keinen großen Unterschied. Als eine Alternative zur multinationalen Regression stelle ich dann noch die logistsiche Regression vor. Wir können nämlich einfach unsere Daten nach dem Outcome jeweils in kleinere Datensätze mit nur jeweils zwei der Kategorien aufspalten. Das ist zwar nicht schön, aber auch eine Möglichkeit mit einem Problem umzugehen.</p>
<p>Ich gehe hier nicht auf die Theorie hinter der multinomialen / ordinalen logistischen Regression ein. Wenn dich dazu mehr interessiert findest du in den jeweiligen Abschnitten dann noch eine passende Referenz. Da kannst du dann schauen, welche Informationen du noch zusätzlich findest.</p>
<section id="annahmen-an-die-daten" class="level2 page-columns page-full" data-number="42.1"><h2 data-number="42.1" class="anchored" data-anchor-id="annahmen-an-die-daten">
<span class="header-section-number">42.1</span> Annahmen an die Daten</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Unser gemessenes Outcome <span class="math inline">\(y\)</span> folgt einer Multinomialverteilung.</span></div></div>
<p>Im folgenden Kapitel zu der multinomialen / ordinalen logistischen linearen Regression gehen wir davon aus, dass die Daten in der vorliegenden Form <em>ideal</em> sind. Das heißt wir haben weder fehlende Werte vorliegen, noch haben wir mögliche Ausreißer in den Daten. Auch wollen wir keine Variablen selektieren. Wir nehmen alles was wir haben mit ins Modell. Sollte eine oder mehre Bedingungen nicht zutreffen, dann schaue dir einfach die folgenden Kapitel an.</p>
<ul>
<li>Wenn du fehlende Werte in deinen Daten vorliegen hast, dann schaue bitte nochmal in das <a href="stat-modeling-missing.html"><span>Kapitel&nbsp;38</span></a> zu Imputation von fehlenden Werten.</li>
<li>Wenn du denkst, dass du Ausreißer oder auffälige Werte in deinen Daten hast, dann schaue doch bitte nochmal in das <a href="stat-modeling-outlier.html"><span>Kapitel&nbsp;36</span></a> zu Ausreißer in den Daten.</li>
<li>Wenn du denkst, dass du zu viele Variablen in deinem Modell hast, dann hilft dir das <a href="stat-modeling-variable-selection.html"><span>Kapitel&nbsp;36</span></a> bei der Variablenselektion.</li>
</ul>
<p>Daher sieht unser Modell wie folgt aus. Wir haben ein <span class="math inline">\(y\)</span> und <span class="math inline">\(p\)</span>-mal <span class="math inline">\(x\)</span>. Wobei <span class="math inline">\(p\)</span> für die Anzahl an Variablen auf der rechten Seite des Modells steht. Im Weiteren folgt unser <span class="math inline">\(y\)</span> einer Multinomialverteilung. Damit finden wir im Outcome im Falle der multinomialen logistischen linearen Regression <em>ungeordnete</em> Kategorien und im Falle der ordinalen logistischen linearen Regression <em>geordnete</em> Kategorien.</p>
<p><span class="math display">\[
y \sim x_1 + x_2 + ... + x_p
\]</span></p>
<p>Wir können in dem Modell auch Faktoren <span class="math inline">\(f\)</span> haben, aber es geht hier nicht um einen Gruppenvergleich. Das ist ganz wichtig. Wenn du einen Gruppenvergleich rechnen willst, dann musst du in <a href="stat-tests-posthoc.html"><span>Kapitel&nbsp;31</span></a> nochmal nachlesen.</p>
</section><section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="42.2"><h2 data-number="42.2" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">42.2</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">conflicted</span>, <span class="va">broom</span>,
               <span class="va">parameters</span>, <span class="va">performance</span>, <span class="va">gtsummary</span>,
               <span class="va">ordinal</span>, <span class="va">janitor</span>, <span class="va">MASS</span>, <span class="va">nnet</span>, <span class="va">flextable</span>,
               <span class="va">emmeans</span>, <span class="va">multcomp</span>, <span class="va">ordinal</span>, <span class="va">see</span>, <span class="va">scales</span>,
               <span class="va">janitor</span><span class="op">)</span>
<span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span>
<span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span>
<span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"mutate"</span>, <span class="st">"dplyr"</span><span class="op">)</span>
<span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"extract"</span>, <span class="st">"magrittr"</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2 page-columns page-full" data-number="42.3"><h2 data-number="42.3" class="anchored" data-anchor-id="daten">
<span class="header-section-number">42.3</span> Daten</h2>
<p>Im Folgenden wollen wir uns die Daten von den infizierten Ferkeln noch einmal anschauen. Wir nehmen als Outcome die Spalte <code>frailty</code> und damit die Gebrechlichkeit der Ferkel. Die Spalte ordnen wir einmal nach <em>robust</em>, <em>pre-frail</em> und <em>frail</em>. Wobei <em>robust</em> ein gesundes Ferkel beschreibt und <em>frail</em> ein gebrechliches Ferkel. Damit wir später die Richtung des Effekts richtig interpretieren können, müssen wir von <em>gut</em> nach <em>schlecht</em> sortieren. Das brauchen wir nicht, wenn wir Boniturnoten haben, dazu mehr in einem eigenen Abschnitt. Wir bauen uns dann noch einen Faktor mit ebenfalls der Spalte <code>frailty</code> in der wir so tun, als gebe es diese Ordnung nicht. Wir werden dann die ordinale Regression mit dem Outcome <code>frailty_ord</code> rechnen und die multinominale Regression dann mit dem Outcome <code>frailty_fac</code> durchführen.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/infected_pigs.xlsx"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>frailty_ord <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">ordered</a></span><span class="op">(</span><span class="va">frailty</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"robust"</span>, <span class="st">"pre-frail"</span>, <span class="st">"frail"</span><span class="op">)</span><span class="op">)</span>,
         frailty_fac <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">frailty</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">infected</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Schauen wir uns nochmal einen Ausschnitt der Daten in der <a href="#tbl-multinom-pigs">Tabelle&nbsp;<span>42.1</span></a> an.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display column-page">
<div id="tbl-multinom-pigs" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 42.1— Auszug aus dem Daten zu den kranken Ferkeln.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">age</th>
<th style="text-align: center;">sex</th>
<th style="text-align: center;">location</th>
<th style="text-align: center;">activity</th>
<th style="text-align: center;">crp</th>
<th style="text-align: center;">frailty</th>
<th style="text-align: center;">bloodpressure</th>
<th style="text-align: center;">weight</th>
<th style="text-align: center;">creatinin</th>
<th style="text-align: center;">frailty_ord</th>
<th style="text-align: center;">frailty_fac</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">61</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">15.31</td>
<td style="text-align: center;">22.38</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">49.88</td>
<td style="text-align: center;">16.94</td>
<td style="text-align: center;">3.07</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="even">
<td style="text-align: center;">53</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">13.01</td>
<td style="text-align: center;">18.64</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">58.2</td>
<td style="text-align: center;">17.95</td>
<td style="text-align: center;">4.88</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="odd">
<td style="text-align: center;">66</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">northeast</td>
<td style="text-align: center;">11.31</td>
<td style="text-align: center;">18.76</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">56.8</td>
<td style="text-align: center;">19.02</td>
<td style="text-align: center;">3.98</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="even">
<td style="text-align: center;">59</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">13.33</td>
<td style="text-align: center;">19.37</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">56.47</td>
<td style="text-align: center;">18.98</td>
<td style="text-align: center;">5.18</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="odd">
<td style="text-align: center;">63</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">14.71</td>
<td style="text-align: center;">21.57</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">59.85</td>
<td style="text-align: center;">16.57</td>
<td style="text-align: center;">6.71</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="even">
<td style="text-align: center;">55</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">15.81</td>
<td style="text-align: center;">21.45</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">58.1</td>
<td style="text-align: center;">18.22</td>
<td style="text-align: center;">5.43</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">54</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">11.82</td>
<td style="text-align: center;">21.5</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">57.05</td>
<td style="text-align: center;">17.95</td>
<td style="text-align: center;">6.16</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="odd">
<td style="text-align: center;">56</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">west</td>
<td style="text-align: center;">13.91</td>
<td style="text-align: center;">20.8</td>
<td style="text-align: center;">pre-frail</td>
<td style="text-align: center;">50.84</td>
<td style="text-align: center;">18.02</td>
<td style="text-align: center;">6.52</td>
<td style="text-align: center;">pre-frail</td>
<td style="text-align: center;">pre-frail</td>
</tr>
<tr class="even">
<td style="text-align: center;">57</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">12.49</td>
<td style="text-align: center;">21.95</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">55.51</td>
<td style="text-align: center;">17.73</td>
<td style="text-align: center;">3.94</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="odd">
<td style="text-align: center;">61</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">northwest</td>
<td style="text-align: center;">15.26</td>
<td style="text-align: center;">23.1</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">58.5</td>
<td style="text-align: center;">18.23</td>
<td style="text-align: center;">2.73</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
<tr class="even">
<td style="text-align: center;">59</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">13.13</td>
<td style="text-align: center;">20.23</td>
<td style="text-align: center;">pre-frail</td>
<td style="text-align: center;">57.33</td>
<td style="text-align: center;">17.21</td>
<td style="text-align: center;">5.42</td>
<td style="text-align: center;">pre-frail</td>
<td style="text-align: center;">pre-frail</td>
</tr>
<tr class="odd">
<td style="text-align: center;">63</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">north</td>
<td style="text-align: center;">10.01</td>
<td style="text-align: center;">19.89</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">55.85</td>
<td style="text-align: center;">17.76</td>
<td style="text-align: center;">6.18</td>
<td style="text-align: center;">robust</td>
<td style="text-align: center;">robust</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Das wären dann die Daten, die wir für unsere Modelle dann brauchen. Schauen wir mal was wir jetzt bei der ordinalen Regression herausbekommen.</p>
</section><section id="sec-ordinal" class="level2 page-columns page-full" data-number="42.4"><h2 data-number="42.4" class="anchored" data-anchor-id="sec-ordinal">
<span class="header-section-number">42.4</span> Ordinale logistische Regression</h2>
<p>Es gibt sicherlich einiges an Paketen in R um eine ordinale Regression durchzuführen. Ich nutze gerne die Funktion <code>polr</code> aus dem R Paket <code>MASS</code>. Daneben gibt es auch noch das R Paket <code>ordinal</code> mit der Funktion <code>clm()</code>, die wir dann noch im Anschluss besprechen werden. Ich nutze jetzt erstmal die Funktion <code>polr</code>, da wir hier noch eine externe Referenz haben, die uns noch detailliertere Informationen liefern kann.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Ich verweise gerne hier auf das tolle Tutorium <a href="https://stats.oarc.ucla.edu/r/dae/ordinal-logistic-regression/">Ordinal Logistic Regression | R Data Analysis Examples</a>. Hier erfährst du noch mehr über die Analyse der ordinalen logistischen Regression.</p>
</div></div><p>Wir schon erwähnt sparen wir usn die mathematischen Details und utzen gleich die Funktion <code>polr</code> auf unserem Outcome <code>frailty</code>. Wir müssen keine Verteilungsfamilie extra angeben, dass haben wir schon mit der Auswahl der Funktion getan. Die Funktion <code>polr</code> kann nur eine ordinale Regression rechnen und wird einen Fehler ausgeben, wenn das Outcome <span class="math inline">\(y\)</span> nicht passt.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">ologit_fit</span> <span class="op">&lt;-</span> <span class="fu">polr</span><span class="op">(</span><span class="va">frailty_ord</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> 
                     <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>, 
                   data <span class="op">=</span> <span class="va">pig_tbl</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Schauen wir uns einmal die Ausgabe des Modellfits der ordinalen Regression mit der Funktion <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> an. Wir sehen eine Menge Zahlen und das wichtigste für uns ist ja, dass wir zum einen Wissen, dass wir auch die ordinale Regression auf der <span class="math inline">\(link\)</span>-Funktion rechnen. Wir erhalten also wieder eine Transformation des Zusammenhangs zurück, wie wir es schon bei der Poisson Regression sowie bei der logistischen Regression hatten.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Hier gibt es nur die Kurzfassung der <em>link</em>-Funktion. <span class="citation" data-cites="dormann2013parametrische">Dormann (<a href="#ref-dormann2013parametrische" role="doc-biblioref">2013</a>)</span> liefert hierzu in Kapitel 7.1.3 nochmal ein Einführung in das Thema.</span></div></div>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">ologit_fit</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = frailty_ord ~ age + sex + location + activity + 
    crp + bloodpressure + weight + creatinin, data = pig_tbl)

Coefficients:
                      Value Std. Error t value
age                0.005199    0.02171  0.2395
sexmale            0.500202    0.28214  1.7729
locationnortheast -0.315377    0.27927 -1.1293
locationnorthwest -0.469579    0.25166 -1.8659
locationwest      -0.046641    0.27381 -0.1703
activity          -0.130300    0.07409 -1.7587
crp               -0.133107    0.06857 -1.9412
bloodpressure      0.016181    0.03083  0.5249
weight             0.047346    0.07080  0.6687
creatinin         -0.022933    0.07097 -0.3231

Intercepts:
                 Value   Std. Error t value
robust|pre-frail -2.1188  3.0707    -0.6900
pre-frail|frail  -0.3625  3.0694    -0.1181

Residual Deviance: 776.36 
AIC: 800.36 </code></pre>
</div>
</div>
<p>Unsere Ausgabe teilt sich in zwei Teile auf. In dem oberen Teil sehen wir die Koeffizienten des Modells zusammen mit dem Fehler und der Teststatistik. Was wir nicht sehen, ist ein <span class="math inline">\(p\)</span>-Wert. Die Funktion rechnet uns keinen Signifikanztest aus. Das können wir aber gleich selber machen. In dem Abschnitt <code>Intercepts</code> finden wir die Werte für die Gruppeneinteilung auf der <em>link</em>-Funktion wieder. Wir transformieren ja unsere drei Outcomekategorien in einen kontinuierliche Zahlenzusammenhang. Trotzdem müssen ja die drei Gruppen auch wieder auftauchen. In dem Abschnitt <code>Intercepts</code> finden wir die Grenzen für die drei Gruppen auf der <em>link</em>-Funktion.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir gibt auch ein Tutorial für <a href="https://stats.oarc.ucla.edu/r/faq/ologit-coefficients/">How do I interpret the coefficients in an ordinal logistic regression in R?</a></p>
</div></div><p>Berechnen wir jetzt einmal die <span class="math inline">\(p\)</span>-Werte per Hand. Dafür brauchen wir die absoluten Werte aus der <code>t value</code> Spalte aus der <code>summary</code> des Modellobjekts. Leider ist die Spalte nicht schön formatiert und so müssen wir uns etwas strecken um die Koeffizienten sauber aufzuarbeiten. Wir erhalten dann das Objekt <code>coef_tbl</code> wieder.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">coef_tbl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ologit_fit</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="va">coef</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span>rownames <span class="op">=</span> <span class="st">"term"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">clean_names</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>t_value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">t_value</span><span class="op">)</span><span class="op">)</span>

<span class="va">coef_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 x 4
   term                 value std_error t_value
   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 age                0.00520    0.0217   0.239
 2 sexmale            0.500      0.282    1.77 
 3 locationnortheast -0.315      0.279    1.13 
 4 locationnorthwest -0.470      0.252    1.87 
 5 locationwest      -0.0466     0.274    0.170
 6 activity          -0.130      0.0741   1.76 
 7 crp               -0.133      0.0686   1.94 
 8 bloodpressure      0.0162     0.0308   0.525
 9 weight             0.0473     0.0708   0.669
10 creatinin         -0.0229     0.0710   0.323
11 robust|pre-frail  -2.12       3.07     0.690
12 pre-frail|frail   -0.363      3.07     0.118</code></pre>
</div>
</div>
<p>Um die Fläche rechts von dem <span class="math inline">\(t\)</span>-Wert zu berechnen, können wir zwei Funktionen nutzen. Die Funktion <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> nimmt eine Standradnormalverteilung an und die Funktion <code><a href="https://rdrr.io/r/stats/TDist.html">pt()</a></code> vergleicht zu einer <span class="math inline">\(t\)</span>-Verteilung. Wenn wir <em>rechts</em> von der Verteilung schauen wollen, dann müssen wir die Option <code>lower.tail = FALSE</code> wählen. Da wir auch zweiseitig statistisch Testen, müssen wir den ausgerechneten <span class="math inline">\(p\)</span>-Wert mal zwei nehmen. Hier einmal als Beispiel für den <span class="math inline">\(t\)</span>-Wert von <span class="math inline">\(1.96\)</span>. Mit <code>pnorm(1.96, lower.tail = FALSE) * 2</code> erhalten wir <span class="math inline">\(0.05\)</span> als Ausgabe. Das ist unser <span class="math inline">\(p\)</span>-Wert. Was uns ja nicht weiter überrascht. Denn rechts neben dem Wert von <span class="math inline">\(1.96\)</span> in einer Standardnormalverteilung ist ja <span class="math inline">\(0.05\)</span>. Wenn wir einen <span class="math inline">\(t\)</span>-Test rechnen würden, dann müssten wir noch die Freiheitsgrade <code>df</code> mit angeben. Mit steigendem <span class="math inline">\(n\)</span> nähert sich die <span class="math inline">\(t\)</span>-Verteilung der Standardnormalverteilung an. Wir haben mehr als <span class="math inline">\(n = 400\)</span> Beobachtungen, daher können wir auch <code>df = 400</code> setzen. Da kommt es auf eine Zahl nicht an. Wir erhalten mit <code>pt(1.96, lower.tail = FALSE, df = 400) * 2</code> dann eine Ausgabe von <span class="math inline">\(0.0507\)</span>. Also <em>fast</em> den gleichen <span class="math inline">\(p\)</span>-Wert.</p>
<p>Im Folgenden setzte ich die Freiheitsgrade <code>df = 3</code> dammit wir was sehen. Bei so hohen Fallzahlen wir in unserem beispiel würden wir sonst keine Unterschiede sehen.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">coef_tbl</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>p_n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">t_value</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">*</span> <span class="fl">2</span>,
         p_t <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="va">t_value</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span>, df <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">*</span> <span class="fl">2</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">round</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 x 6
   term               value std_error t_value   p_n   p_t
   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 age                0.005     0.022   0.239 0.811 0.826
 2 sexmale            0.5       0.282   1.77  0.076 0.174
 3 locationnortheast -0.315     0.279   1.13  0.259 0.341
 4 locationnorthwest -0.47      0.252   1.87  0.062 0.159
 5 locationwest      -0.047     0.274   0.17  0.865 0.876
 6 activity          -0.13      0.074   1.76  0.079 0.177
 7 crp               -0.133     0.069   1.94  0.052 0.148
 8 bloodpressure      0.016     0.031   0.525 0.6   0.636
 9 weight             0.047     0.071   0.669 0.504 0.552
10 creatinin         -0.023     0.071   0.323 0.747 0.768
11 robust|pre-frail  -2.12      3.07    0.69  0.49  0.54 
12 pre-frail|frail   -0.363     3.07    0.118 0.906 0.913</code></pre>
</div>
</div>
<p>Damit haben wir einmal händisch uns die <span class="math inline">\(p\)</span>-Werte ausgerechnet. Jetzt könnte man sagen, dass ist ja etwas mühselig. Gibt es da nicht auch einen einfacheren Weg? Ja wir können zum einen die Funktion <code>tidy()</code> nutzen um die 95% Konfidenzintervalle und die exponierten Effektschätzer aus der ordinalen Regresssion zu erhalten. Wir erhalten aber wieder keine <span class="math inline">\(p\)</span>-Werte sondern müssten uns diese <span class="math inline">\(p\)</span>- Werte dann wieder selber berechnen.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">ologit_fit</span> <span class="op">%&gt;%</span> 
  <span class="fu">tidy</span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span>, exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">coef.type</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 x 6
   term              estimate std.error statistic conf.low conf.high
   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 age                  1.01     0.0217     0.239    0.963      1.05
 2 sexmale              1.65     0.282      1.77     0.952      2.88
 3 locationnortheast    0.730    0.279     -1.13     0.420      1.26
 4 locationnorthwest    0.625    0.252     -1.87     0.381      1.02
 5 locationwest         0.954    0.274     -0.170    0.557      1.63
 6 activity             0.878    0.0741    -1.76     0.758      1.01
 7 crp                  0.875    0.0686    -1.94     0.765      1.00
 8 bloodpressure        1.02     0.0308     0.525    0.957      1.08
 9 weight               1.05     0.0708     0.669    0.913      1.21
10 creatinin            0.977    0.0710    -0.323    0.850      1.12
11 robust|pre-frail     0.120    3.07      -0.690   NA         NA   
12 pre-frail|frail      0.696    3.07      -0.118   NA         NA   </code></pre>
</div>
</div>
<p>Um all dieses Berechnen zu umgehen, können wir dann auch die Funktion <code>model_parameters()</code> nutzen. Hier berechnen wir dann die <span class="math inline">\(p\)</span>-Wert mit <span class="math inline">\(df = 400\)</span> aus einer <span class="math inline">\(t\)</span>-Verteilung. Damit umgehen wir das Problem, dass unser Modellfit keine <span class="math inline">\(p\)</span>-Werte liefert.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">ologit_fit</span> <span class="op">%&gt;%</span> 
  <span class="fu">model_parameters</span><span class="op">(</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># alpha

Parameter        | Log-Odds |   SE |        95% CI | t(400) |     p
-------------------------------------------------------------------
robust|pre-frail |    -2.12 | 3.07 | [-8.16, 3.92] |  -0.69 | 0.491
pre-frail|frail  |    -0.36 | 3.07 | [-6.40, 5.67] |  -0.12 | 0.906

# beta

Parameter            | Log-Odds |   SE |        95% CI | t(400) |     p
-----------------------------------------------------------------------
age                  | 5.20e-03 | 0.02 | [-0.04, 0.05] |   0.24 | 0.811
sex [male]           |     0.50 | 0.28 | [-0.05, 1.06] |   1.77 | 0.077
location [northeast] |    -0.32 | 0.28 | [-0.87, 0.23] |  -1.13 | 0.259
location [northwest] |    -0.47 | 0.25 | [-0.97, 0.02] |  -1.87 | 0.063
location [west]      |    -0.05 | 0.27 | [-0.59, 0.49] |  -0.17 | 0.865
activity             |    -0.13 | 0.07 | [-0.28, 0.01] |  -1.76 | 0.079
crp                  |    -0.13 | 0.07 | [-0.27, 0.00] |  -1.94 | 0.053
bloodpressure        |     0.02 | 0.03 | [-0.04, 0.08] |   0.52 | 0.600
weight               |     0.05 | 0.07 | [-0.09, 0.19] |   0.67 | 0.504
creatinin            |    -0.02 | 0.07 | [-0.16, 0.12] |  -0.32 | 0.747</code></pre>
</div>
</div>
<p>In <a href="#tbl-regression-ordinal">Tabelle&nbsp;<span>42.2</span></a> sehen wir nochmal die Ergebnisse der ordinalen Regression einmal anders aufgearbeitet. Wir aber schon bei der Funktion <code>tidy()</code> fehlen in der Tabelle die <span class="math inline">\(p\)</span>-Werte. Wir können aber natürlich auch eine Entscheidung über die 95% Konfidenzintervalle treffen. Wenn die 1 mit im 95% Konfidenzintervall ist, dann können wir die Nullhypothese nicht ablehnen.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">ologit_fit</span> <span class="op">%&gt;%</span> 
  <span class="fu">tbl_regression</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_flex_table</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-regression-ordinal" class="anchored">

<div class="tabwid">
<style>.cl-bb86a97e{}.cl-bb7e2222{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-bb7e222c{font-family:'Arial';font-size:6.6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;bottom:3.3pt;}.cl-bb818c82{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bb818c8c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bb818c8d{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bb818c96{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bb818c97{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:15pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bb818c98{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bb81a2b2{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2bc{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2c6{width:0.965in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2c7{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2d0{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2d1{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2d2{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2da{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2db{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2e4{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2e5{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2e6{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2ee{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2ef{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2f8{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2f9{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a2fa{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a302{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a303{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a30c{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a30d{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a30e{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a316{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a317{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a318{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a320{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bb81a321{width:0.965in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-bb86a97e">
<caption>Tabelle 42.2—  Tabelle der Ergebnisse der ordinalen Regression. </caption>
<thead><tr style="overflow-wrap:break-word;">
<th class="cl-bb81a2b2"><p class="cl-bb818c82"><span class="cl-bb7e2222">Characteristic</span></p></th>
<th class="cl-bb81a2bc"><p class="cl-bb818c8c"><span class="cl-bb7e2222">OR</span><span class="cl-bb7e222c">1</span></p></th>
<th class="cl-bb81a2c6"><p class="cl-bb818c8c"><span class="cl-bb7e2222">95% CI</span><span class="cl-bb7e222c">1</span></p></th>
</tr></thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2c7"><p class="cl-bb818c8d"><span class="cl-bb7e2222">age</span></p></td>
<td class="cl-bb81a2d0"><p class="cl-bb818c96"><span class="cl-bb7e2222">1.01</span></p></td>
<td class="cl-bb81a2d1"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.96, 1.05</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2d2"><p class="cl-bb818c8d"><span class="cl-bb7e2222">sex</span></p></td>
<td class="cl-bb81a2da"><p class="cl-bb818c96"><span class="cl-bb7e2222"></span></p></td>
<td class="cl-bb81a2db"><p class="cl-bb818c96"><span class="cl-bb7e2222"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2e4"><p class="cl-bb818c97"><span class="cl-bb7e2222">female</span></p></td>
<td class="cl-bb81a2e5"><p class="cl-bb818c96"><span class="cl-bb7e2222">—</span></p></td>
<td class="cl-bb81a2e6"><p class="cl-bb818c96"><span class="cl-bb7e2222">—</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2c7"><p class="cl-bb818c97"><span class="cl-bb7e2222">male</span></p></td>
<td class="cl-bb81a2d0"><p class="cl-bb818c96"><span class="cl-bb7e2222">1.65</span></p></td>
<td class="cl-bb81a2d1"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.95, 2.88</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2ee"><p class="cl-bb818c8d"><span class="cl-bb7e2222">location</span></p></td>
<td class="cl-bb81a2ef"><p class="cl-bb818c96"><span class="cl-bb7e2222"></span></p></td>
<td class="cl-bb81a2f8"><p class="cl-bb818c96"><span class="cl-bb7e2222"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2ee"><p class="cl-bb818c97"><span class="cl-bb7e2222">north</span></p></td>
<td class="cl-bb81a2ef"><p class="cl-bb818c96"><span class="cl-bb7e2222">—</span></p></td>
<td class="cl-bb81a2f8"><p class="cl-bb818c96"><span class="cl-bb7e2222">—</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2c7"><p class="cl-bb818c97"><span class="cl-bb7e2222">northeast</span></p></td>
<td class="cl-bb81a2d0"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.73</span></p></td>
<td class="cl-bb81a2d1"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.42, 1.26</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2c7"><p class="cl-bb818c97"><span class="cl-bb7e2222">northwest</span></p></td>
<td class="cl-bb81a2d0"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.63</span></p></td>
<td class="cl-bb81a2d1"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.38, 1.02</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2c7"><p class="cl-bb818c97"><span class="cl-bb7e2222">west</span></p></td>
<td class="cl-bb81a2d0"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.95</span></p></td>
<td class="cl-bb81a2d1"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.56, 1.63</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2f9"><p class="cl-bb818c8d"><span class="cl-bb7e2222">activity</span></p></td>
<td class="cl-bb81a2fa"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.88</span></p></td>
<td class="cl-bb81a302"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.76, 1.01</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2c7"><p class="cl-bb818c8d"><span class="cl-bb7e2222">crp</span></p></td>
<td class="cl-bb81a2d0"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.88</span></p></td>
<td class="cl-bb81a2d1"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.76, 1.00</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a303"><p class="cl-bb818c8d"><span class="cl-bb7e2222">bloodpressure</span></p></td>
<td class="cl-bb81a30c"><p class="cl-bb818c96"><span class="cl-bb7e2222">1.02</span></p></td>
<td class="cl-bb81a30d"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.96, 1.08</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a2f9"><p class="cl-bb818c8d"><span class="cl-bb7e2222">weight</span></p></td>
<td class="cl-bb81a2fa"><p class="cl-bb818c96"><span class="cl-bb7e2222">1.05</span></p></td>
<td class="cl-bb81a302"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.91, 1.21</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bb81a30e"><p class="cl-bb818c8d"><span class="cl-bb7e2222">creatinin</span></p></td>
<td class="cl-bb81a316"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.98</span></p></td>
<td class="cl-bb81a317"><p class="cl-bb818c96"><span class="cl-bb7e2222">0.85, 1.12</span></p></td>
</tr>
</tbody>
<tfoot><tr style="overflow-wrap:break-word;"><td colspan="3" class="cl-bb81a318"><p class="cl-bb818c98"><span class="cl-bb7e222c">1</span><span class="cl-bb7e2222">OR = Odds Ratio, CI = Confidence Interval</span></p></td></tr></tfoot>
</table>
</div>
</div>
</div>
</div>
<p>Wi es im gazen Kapitel schon durchscheint, die Interpreation der <span class="math inline">\(OR\)</span> aus einer ordinalen Regression ist nicht einfach, geschweige den intuitiv. Was wir haben ist der Trend. Wir haben unser Outcome von <em>robust</em> zu <em>frail</em> sortiert und damit von <em>gut</em> nach <em>schlecht</em>. Wir können so die Richtung der Variablen in unserem Modell interpretieren. Das heißt, dass männliche Ferkel eher von einer Gebrechlichkeit betroffen sind als weibliche Ferkel. Oder wir sagen, dass ein ansteigender CRP Wert führt zu weniger Gebrechlichkeit. Auf diesem Niveau lassen sich die <span class="math inline">\(OR\)</span> einer ordinalen Regression gut interpretieren.</p>
</section><section id="cumulative-link-models-clm-für-ordinale-daten" class="level2 page-columns page-full" data-number="42.5"><h2 data-number="42.5" class="anchored" data-anchor-id="cumulative-link-models-clm-für-ordinale-daten">
<span class="header-section-number">42.5</span> Cumulative Link Models (CLM) für ordinale Daten</h2>
<p>Jetzt kommen wir nochmal zu dem Fall, dass wir Boniturdaten vorliegen habe. Das heißt, wir bauen uns flux wieder einen Datensatz mit drei Blöcken mit jeweils drei Wiederholungen. Wir haben Weizen angepflanzt und bonitieren die Weizenpflanzen nach der Likert Skala. Dabei bedeutet dann eine 1 ein schlechte Note und eine 9 die best mögliche Note. Wir hätten natürlich hier auch einen Kurskal-Wallis-Test rechnen können und dann im Anschluss einen paarweisen Wilcoxon Test. Nun modellieren wir hier aber die Boniturnoten mal mit einer ordinalen Regression und rechnen den anschließenden Gruppenvergleich dann mit dem R Paket <code>emmeans</code>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir finden auch ein Tutorial zu <a href="https://rcompanion.org/handbook/G_01.html">Introduction to Cumulative Link Models (CLM) for Ordinal Data</a>.</p>
</div></div><p>Unser Datensatz <code>grade_tbl</code> enthält den Faktor <code>block</code> mit drei Levels sowie den Faktor <code>variety</code> mit fünf Leveln. Jedes Level repränsentiert dabei eine Weizensorte.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">grade_tbl</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>block <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"I"</span>, <span class="st">"II"</span>, <span class="st">"III"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>,
                    A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">4</span>,<span class="fl">3</span>,<span class="fl">3</span>,<span class="fl">2</span>,<span class="fl">4</span>,<span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span>,
                    B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>,<span class="fl">9</span>,<span class="fl">8</span>,<span class="fl">9</span>,<span class="fl">7</span>,<span class="fl">8</span>,<span class="fl">9</span>,<span class="fl">6</span>,<span class="fl">7</span><span class="op">)</span>,
                    C <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6</span>,<span class="fl">5</span>,<span class="fl">5</span>,<span class="fl">7</span>,<span class="fl">5</span>,<span class="fl">6</span>,<span class="fl">4</span>,<span class="fl">7</span>,<span class="fl">6</span><span class="op">)</span>,
                    D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span>,
                    E <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">3</span>,<span class="fl">7</span>,<span class="fl">5</span>,<span class="fl">6</span>,<span class="fl">4</span>,<span class="fl">5</span>,<span class="fl">7</span>,<span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">gather</span><span class="op">(</span>key <span class="op">=</span> <span class="va">variety</span>, value <span class="op">=</span> <span class="va">grade</span>, <span class="va">A</span><span class="op">:</span><span class="va">E</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>grade_ord <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">ordered</a></span><span class="op">(</span><span class="va">grade</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir schauen uns nochmal den Datensatz an und sehen, dass wir einmal die Spalte <code>grade</code> als numerische Spalte vorliegen haben udn einmal als geordneten Faktor. Wir brauchen die numerische Spalte um die Daten besser in <code>ggplot()</code> darstellen zu können.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">grade_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 45 x 4
   block variety grade grade_ord
   &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;ord&gt;    
 1 I     A           2 2        
 2 I     A           3 3        
 3 I     A           4 4        
 4 II    A           3 3        
 5 II    A           3 3        
 6 II    A           2 2        
 7 III   A           4 4        
 8 III   A           2 2        
 9 III   A           1 1        
10 I     B           7 7        
# ... with 35 more rows</code></pre>
</div>
</div>
<p>In <a href="#fig-clm-dot">Abbildung&nbsp;<span>42.1</span></a> sehen wir einmal die Daten als Dotplot dargestellt. Auf der x-Achse sind die Weizensorten und auf der y-Achse die Boniturnoten. Ich habe noch die zusätzlichen Linien für jede einzelne Note mit eingezeichnet.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">grade_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">variety</span>, <span class="va">grade</span>, fill <span class="op">=</span> <span class="va">block</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_dotplot</span><span class="op">(</span>binaxis <span class="op">=</span> <span class="st">"y"</span>, stackdir<span class="op">=</span><span class="st">'center'</span>, 
               position<span class="op">=</span><span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.6</span><span class="op">)</span>, dotsize <span class="op">=</span> <span class="fl">0.75</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_y_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">9</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_fill_okabeito</span><span class="op">(</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-clm-dot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-multinom_files/figure-html/fig-clm-dot-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 42.1— Dotplot des Datenbeispiels für die Bonitur von fünf Weizensorten.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Jetzt können wir schon die Funktion <code>clm()</code> aus dem R Paket <code>ordinal</code> verwenden um die ordinale Regression zu rechnen. Wir haben in dem Paket <code>ordinal</code> noch weitere Modelle zu Verfügung mit denen wir auch komplexere Designs bis hin zu linearen gemischten Modellen für eine ordinale Regresssion rechnen können. Da wir mit Boniturnoten als Outcome arbeiten setzen wir auch die Option <code>threshold = "symmetric"</code>. Damit teilen wir der Funktion <code>clm()</code> mit, dass wir es mit einer symmetrischen Notenskala zu tun haben. Wenn du das nicht hast, dass kannst du die Option auch of <code>"flexible"</code> stellen. Dann wird eine nicht symmetrische Verteilung des Outcomes angenommen.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">clm_fit</span> <span class="op">&lt;-</span> <span class="fu">clm</span><span class="op">(</span><span class="va">grade_ord</span> <span class="op">~</span> <span class="va">variety</span> <span class="op">+</span> <span class="va">block</span>, data <span class="op">=</span> <span class="va">grade_tbl</span>,
               threshold <span class="op">=</span> <span class="st">"symmetric"</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir können uns dann den Fit des Modells wieder in der Funktion <code>model_parameters()</code> einmal anschauen. Wir <em>brauchen</em> aber die Ausgabe nicht weiter. Wir werden Koeffizienten des Modells jetzt verwenden um die Gruppenvergleiche zu rechnen. Ich habe hier einmal die <span class="math inline">\(OR\)</span> über die Option <code>exponentiate = TRUE</code> mir ausgeben lassen. Leider sind die <span class="math inline">\(OR\)</span> so alleine nicht zu interpretieren.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">clm_fit</span> <span class="op">%&gt;%</span> 
  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Intercept

Parameter | Odds Ratio |     SE |          95% CI |    z |      p
-----------------------------------------------------------------
central 1 |      22.02 |  20.78 | [ 3.47, 139.98] | 3.28 | 0.001 
central 2 |     101.42 | 109.71 | [12.17, 845.18] | 4.27 | &lt; .001
spacing 1 |       4.30 |   1.89 | [ 1.82,  10.16] | 3.33 | &lt; .001
spacing 2 |      35.04 |  25.42 | [ 8.46, 145.23] | 4.90 | &lt; .001
spacing 3 |     169.31 | 142.84 | [32.40, 884.76] | 6.08 | &lt; .001

# Location Parameters

Parameter   | Odds Ratio |      SE |             95% CI |     z |      p
------------------------------------------------------------------------
variety [B] |    5917.41 | 9556.45 | [249.73, 1.40e+05] |  5.38 | &lt; .001
variety [C] |     137.83 |  161.11 | [ 13.94,  1362.41] |  4.21 | &lt; .001
variety [D] |       0.14 |    0.13 | [  0.02,     0.87] | -2.11 | 0.035 
variety [E] |      57.06 |   62.60 | [  6.64,   490.03] |  3.69 | &lt; .001
block [II]  |       0.95 |    0.64 | [  0.26,     3.52] | -0.07 | 0.942 
block [III] |       0.89 |    0.63 | [  0.22,     3.56] | -0.17 | 0.865 </code></pre>
</div>
</div>
<p>Es ist auch möglich auf dem Modellfit eine ANOVA zu rechnen. Wir machen das hier einmal, aber wir erwaten natürlich einen signifikanten Effekt von der Sorte. Die Signifikanz konnten wir ja schon oben im Dortplot sehen.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">clm_fit</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type I Analysis of Deviance Table with Wald chi-square tests

        Df   Chisq Pr(&gt;Chisq)    
variety  4 37.9927  1.124e-07 ***
block    2  0.0292     0.9855    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Ich hatte ja eben geschrieben, dass wir die Effektschätzer nicht nutzen. Wir können mit den <span class="math inline">\(OR\)</span> aus dem Modell nichts anfangen. Stattdessen nutzen wir die Schätzer der <em>link</em>-Funktion, also die Log Odds, um den paarweisen Gruppenvergleich zu rechnen. Wir nutzen dafür die Funktion <code>emmeans()</code> und lassen uns das <em>compact letter display</em> über die Funktion <code>cld()</code> wiedergeben. Ich habe dann noch die Ausgabe einmal nach den Sorten sortiert und nicht nach dem <em>compact letter display</em>. Dadurch lassen sich die Buchstaben besser zum Dotplot vergleichen.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">clm_fit</span> <span class="op">%&gt;%</span> 
  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">variety</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">cld</span><span class="op">(</span>Letters <span class="op">=</span> <span class="va">letters</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">arrange</span><span class="op">(</span><span class="va">variety</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> variety emmean    SE  df asymp.LCL asymp.UCL .group
 A       -3.912 0.887 Inf    -5.650     -2.17  a    
 B        4.774 0.966 Inf     2.881      6.67    c  
 C        1.014 0.623 Inf    -0.206      2.23   b   
 D       -5.848 1.010 Inf    -7.828     -3.87  a    
 E        0.132 0.639 Inf    -1.120      1.38   b   

Results are averaged over the levels of: block 
Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 5 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping letter,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Wir erinnern uns, gleiche Buchstaben heißen <em>kein</em> Unterschied zwischen den Weizensorten. Damit ist die Weizensorte A gleich der Weizensorte D. Die Weizensorte C ist gleich der Weizensorte E. Am Ende unterscheidet sich die Weizensorte B von allen anderen Sorten. Wir können aber die Werte in der Spalte <code>emmean</code> nicht als Notenunterschied interpretieren. Dafür müssen wir dann den Median für die Gruppen berechnen. Wir können dann das <em>compact letter display</em> händisch ergänzen.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">grade_tbl</span> <span class="op">%&gt;%</span> 
  <span class="fu">group_by</span><span class="op">(</span><span class="va">variety</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">summarise</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">grade</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>cld <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"a"</span>, <span class="st">"  c"</span>, <span class="st">" b "</span>, <span class="st">"a  "</span>, <span class="st">" b "</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 3
  variety `median(grade)` cld  
  &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;
1 A                     3 "a"  
2 B                     8 "  c"
3 C                     6 " b "
4 D                     2 "a  "
5 E                     5 " b "</code></pre>
</div>
</div>
<p>Du könntest dir auch die Buchstaben des <em>compact letter display</em> aus einem Objekt ziehen und nicht händisch übertragen. Ich habe mir hier aber einen Schritt gespart.</p>
</section><section id="sec-multinom" class="level2 page-columns page-full" data-number="42.6"><h2 data-number="42.6" class="anchored" data-anchor-id="sec-multinom">
<span class="header-section-number">42.6</span> Multinomiale logistische Regression</h2>
<p>Was machen wir in eine multinomialen logistische Regression? Im Gegensatz zu der ordinalen Regression haben wir in der multinominalen Regression keine Ordnung in unserem Outcome. Das macht die Sache dann schon eine Nummer komplizierter. Und wir lösen dieses Problem indem wir ein Level des Outcomes oder eben eine Kategorie des Outcomes als <em>Referenz</em> definieren. Dann haben wir wieder unsere Ordnung drin. Und die Definition der Referenz ist auch manchmal das schwerste Unterfangen. Wenn ich keine Ordnung in meinem Outcome habe, wie soll ich dann die Referenz bestimmen? Aber das ist dann immer eine Frage an den konkreten Datensatz. Hier basteln wir uns ja die Fragestellung so hin, dass es passt.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Ich verweise gerne hier auf das tolle Tutorium <a href="https://stats.oarc.ucla.edu/r/dae/multinomial-logistic-regression/">Multinomial Logistic Regression | R Data Analysis Examples</a>. Hier erfährst du noch mehr über die Analyse der multinominale logistischen Regression.</p>
</div></div><p>Um eine Referenz in dem Outcome zu definieren nutzen wir die Funktion <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> und setzen als unsere Referenz das Level <code>frail</code> aus unserem Outcome <code>frailty</code>. Wir hätten auch jedes andere Level als Referenz nehmen können. Zu dieser Referenz werden wir jetzt unser Modell anpassen. Ich nehme immer als Referenz das <em>schlechteste</em> im Sinne von <em>nicht gut</em>. In unserem Fall ist das eben das Level <code>frail</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span> <span class="op">&lt;-</span> <span class="va">pig_tbl</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate</span><span class="op">(</span>frailty_fac <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">frailty_fac</span>, ref <span class="op">=</span> <span class="st">"frail"</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nachdem wir unsere Referenz definiert haben, können wir wieder recht einfach mit der Funktion <code>multinom()</code> aus dem Paket <code>nnet</code> die multinominalen Regression rechnen. Ich mache keinen Hehl daraus. Ich mag die Funktion nicht, da die Ausgabe der Funktion sehr unsortiert ist und uns nicht gerade die Arbeit erleichtert. Auch schweigt die Funktion nicht, sondern muss immer eine Ausgabe wiedergeben. Finde ich sehr unschön.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">multinom_fit</span> <span class="op">&lt;-</span> <span class="fu">multinom</span><span class="op">(</span><span class="va">frailty_fac</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>, 
                         data <span class="op">=</span> <span class="va">pig_tbl</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  36 (22 variable)
initial  value 452.628263 
iter  10 value 401.130508
iter  20 value 381.498488
iter  30 value 380.694398
final  value 380.689300 
converged</code></pre>
</div>
</div>
<p>Die Standardausgabe von <code>multinom()</code> hat wiederum keine <span class="math inline">\(p\)</span>-Werte und wir könnten uns über die Funktion <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> wiederum aus den <span class="math inline">\(t\)</span>-Werten unsere <span class="math inline">\(p\)</span>-Werte berechnen. Leider erspart sich <code>multinom()</code> selbst den Schritt die <span class="math inline">\(t\)</span>-Werte zu berechnen, so dass wir die <span class="math inline">\(t\)</span>-Werte selber berechnen müssen. Nicht das es ein Problem wäre, aber schön ist das alles nicht. Im Folgenden siehst du dann einmal die Berechnung der <span class="math inline">\(p\)</span>-Werte über die Berechnung der Teststatistik.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">z_mat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">multinom_fit</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">multinom_fit</span><span class="op">)</span><span class="op">$</span><span class="va">standard.errors</span>
<span class="va">p_n</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">z_mat</span><span class="op">)</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="fl">2</span>
<span class="va">p_n</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          (Intercept)        age   sexmale locationnortheast locationnorthwest
robust      0.4775726 0.34659718 0.1394380         0.4904806         0.1320405
pre-frail   0.5263984 0.05534541 0.6300418         0.7989195         0.6659467
          locationwest  activity        crp bloodpressure    weight  creatinin
robust       0.8648791 0.4539323 0.03667107     0.2398979 0.9118323 0.12787728
pre-frail    0.9714730 0.4295601 0.20119551     0.1570281 0.5565101 0.02860694</code></pre>
</div>
</div>
<p>Jetzt müssten wir diese <span class="math inline">\(pp\)</span>-Werte aus der Matrix noch mit unseren Koeffizienten verbauen und da hört es dann bei mir auf. Insbesondere da wir ja mit <code>model_parameters()</code> eine Funktion haben, die uns in diesem Fall wirklich gut helfen kann. Wir nehmen hier zwar die <span class="math inline">\(t\)</span>-Verteilung an und haben damit leicht höre <span class="math inline">\(p\)</span>-Werte, aber da wir eine so große Anzahl an Beobachtungen haben, fällt dieser Unterschied nicht ins Gewicht.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">multinom_fit</span> <span class="op">%&gt;%</span> <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Response level: robust

Parameter            | Odds Ratio |   SE |         95% CI | t(390) |     p
--------------------------------------------------------------------------
(Intercept)          |       0.03 | 0.16 | [0.00, 433.73] |  -0.71 | 0.478
age                  |       1.03 | 0.04 | [0.96,   1.11] |   0.94 | 0.347
sex [male]           |       0.50 | 0.23 | [0.20,   1.25] |  -1.48 | 0.140
location [northeast] |       1.35 | 0.59 | [0.57,   3.18] |   0.69 | 0.491
location [northwest] |       1.88 | 0.79 | [0.82,   4.27] |   1.51 | 0.133
location [west]      |       1.08 | 0.46 | [0.46,   2.51] |   0.17 | 0.865
activity             |       1.09 | 0.13 | [0.86,   1.39] |   0.75 | 0.454
crp                  |       1.26 | 0.14 | [1.01,   1.56] |   2.09 | 0.037
bloodpressure        |       0.94 | 0.05 | [0.86,   1.04] |  -1.18 | 0.241
weight               |       0.99 | 0.11 | [0.79,   1.23] |  -0.11 | 0.912
creatinin            |       1.20 | 0.14 | [0.95,   1.50] |   1.52 | 0.129

# Response level: pre-frail

Parameter            | Odds Ratio |   SE |         95% CI | t(390) |     p
--------------------------------------------------------------------------
(Intercept)          |       0.04 | 0.20 | [0.00, 945.94] |  -0.63 | 0.527
age                  |       1.07 | 0.04 | [1.00,   1.16] |   1.92 | 0.056
sex [male]           |       0.79 | 0.39 | [0.30,   2.08] |  -0.48 | 0.630
location [northeast] |       0.89 | 0.42 | [0.35,   2.24] |  -0.25 | 0.799
location [northwest] |       1.21 | 0.54 | [0.51,   2.90] |   0.43 | 0.666
location [west]      |       1.02 | 0.46 | [0.42,   2.48] |   0.04 | 0.971
activity             |       0.90 | 0.12 | [0.70,   1.16] |  -0.79 | 0.430
crp                  |       1.16 | 0.14 | [0.92,   1.46] |   1.28 | 0.202
bloodpressure        |       0.93 | 0.05 | [0.84,   1.03] |  -1.42 | 0.158
weight               |       1.07 | 0.13 | [0.85,   1.36] |   0.59 | 0.557
creatinin            |       1.31 | 0.16 | [1.03,   1.68] |   2.19 | 0.029</code></pre>
</div>
</div>
<p>Was sehen wir? Zuerst haben wir etwas Glück. Den unsere Referenzlevel macht dann doch Sinn. Wir vergleichen ja das Outcomelevel <code>robust</code> zu <code>frail</code> und das Outcomelevel <code>pre-frail</code> zu <code>frail</code>. Dann haben wir noch das Glück, dass durch unsere Ordnung dann auch <code>frail</code> das schlechtere Outcome ist, so dass wir die <span class="math inline">\(OR\)</span> als Risiko oder als protektiv interpretieren können. Nehmen wir als Beispiel einmal die Variable <code>crp</code>. Der CRP Wert höht das Risiko für <code>frail</code>. Das macht schonmal so Sinn. Und zum anderen ist der Effekt bei dem Vergleich von <code>pre-frail</code> zu <code>frail</code> mit <span class="math inline">\(1.16\)</span> nicht so große wie bei <code>robust</code> zu <code>frail</code> mit <span class="math inline">\(1.26\)</span>. Das macht auch Sinn. Deshalb passt es hier einigermaßen.</p>
<p>In <a href="#tbl-tbl-regression-multinom">Tabelle&nbsp;<span>42.3</span></a> sehen wir nochmal die Ausgabe von einer multinominalen Regression durch die Funktion <code>tbl_regression()</code> aufgearbeitet.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">multinom_fit</span> <span class="op">%&gt;%</span> 
  <span class="fu">tbl_regression</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_flex_table</span><span class="op">(</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-tbl-regression-multinom" class="anchored">

<div class="tabwid">
<style>.cl-bd9625f0{}.cl-bd8d6fbe{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-bd8d6fc8{font-family:'Arial';font-size:6.6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;bottom:3.3pt;}.cl-bd90b0a2{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd90b0ac{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd90b0b6{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd90b0b7{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd90b0b8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:15pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd90b0c0{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd90c4d4{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4d5{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4de{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4e8{width:0.965in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4f2{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4f3{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4fc{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c4fd{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c506{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c507{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c510{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c511{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c512{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c51a{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c51b{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c51c{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c51d{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c524{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c525{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c52e{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c538{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c539{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c53a{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c542{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c543{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c544{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c54c{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c54d{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c556{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c557{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c558{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c560{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c561{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c56a{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c56b{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c56c{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c574{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c575{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c57e{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c57f{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c588{width:0.905in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c589{width:1.253in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c58a{width:0.583in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c592{width:0.965in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c593{width:0.786in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c594{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c59c{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c59d{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c59e{width:0.965in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd90c5a6{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-bd9625f0">
<caption>Tabelle 42.3—  Tabelle der Ergebnisse der multinominalen Regression. </caption>
<thead><tr style="overflow-wrap:break-word;">
<th class="cl-bd90c4d4"><p class="cl-bd90b0a2"><span class="cl-bd8d6fbe">Outcome</span></p></th>
<th class="cl-bd90c4d5"><p class="cl-bd90b0a2"><span class="cl-bd8d6fbe">Characteristic</span></p></th>
<th class="cl-bd90c4de"><p class="cl-bd90b0ac"><span class="cl-bd8d6fbe">OR</span><span class="cl-bd8d6fc8">1</span></p></th>
<th class="cl-bd90c4e8"><p class="cl-bd90b0ac"><span class="cl-bd8d6fbe">95% CI</span><span class="cl-bd8d6fc8">1</span></p></th>
<th class="cl-bd90c4f2"><p class="cl-bd90b0ac"><span class="cl-bd8d6fbe">p-value</span></p></th>
</tr></thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">robust</span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">age</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.03</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.96, 1.11</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.3</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c510"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c511"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">sex</span></p></td>
<td class="cl-bd90c512"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c51a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c51b"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c51c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c51d"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">female</span></p></td>
<td class="cl-bd90c524"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c525"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c52e"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">male</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.50</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.20, 1.25</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.14</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c538"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c539"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">location</span></p></td>
<td class="cl-bd90c53a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c542"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c543"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c538"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c539"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">north</span></p></td>
<td class="cl-bd90c53a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c542"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c543"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">northeast</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.35</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.58, 3.17</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.5</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">northwest</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.88</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.83, 4.26</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.13</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">west</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.08</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.46, 2.51</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.9</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c544"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c54c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">activity</span></p></td>
<td class="cl-bd90c54d"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.09</span></p></td>
<td class="cl-bd90c556"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.86, 1.39</span></p></td>
<td class="cl-bd90c557"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.5</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">crp</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.26</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.01, 1.56</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.037</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c558"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c560"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">bloodpressure</span></p></td>
<td class="cl-bd90c561"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.94</span></p></td>
<td class="cl-bd90c56a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.86, 1.04</span></p></td>
<td class="cl-bd90c56b"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.2</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c544"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c54c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">weight</span></p></td>
<td class="cl-bd90c54d"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.99</span></p></td>
<td class="cl-bd90c556"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.79, 1.23</span></p></td>
<td class="cl-bd90c557"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">&gt;0.9</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">creatinin</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.20</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.95, 1.50</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.13</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c56c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">pre-frail</span></p></td>
<td class="cl-bd90c574"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">age</span></p></td>
<td class="cl-bd90c575"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.07</span></p></td>
<td class="cl-bd90c57e"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.00, 1.16</span></p></td>
<td class="cl-bd90c57f"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.055</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c510"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c511"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">sex</span></p></td>
<td class="cl-bd90c512"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c51a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c51b"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c51c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c51d"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">female</span></p></td>
<td class="cl-bd90c524"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c525"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c52e"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">male</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.79</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.30, 2.07</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.6</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c538"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c539"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">location</span></p></td>
<td class="cl-bd90c53a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c542"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c543"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c538"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c539"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">north</span></p></td>
<td class="cl-bd90c53a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c542"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">—</span></p></td>
<td class="cl-bd90c543"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">northeast</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.89</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.35, 2.23</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.8</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">northwest</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.21</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.51, 2.90</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.7</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b8"><span class="cl-bd8d6fbe">west</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.02</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.42, 2.47</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">&gt;0.9</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c544"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c54c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">activity</span></p></td>
<td class="cl-bd90c54d"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.90</span></p></td>
<td class="cl-bd90c556"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.70, 1.16</span></p></td>
<td class="cl-bd90c557"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.4</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c4f3"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c4fc"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">crp</span></p></td>
<td class="cl-bd90c4fd"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.16</span></p></td>
<td class="cl-bd90c506"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.92, 1.46</span></p></td>
<td class="cl-bd90c507"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.2</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c558"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c560"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">bloodpressure</span></p></td>
<td class="cl-bd90c561"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.93</span></p></td>
<td class="cl-bd90c56a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.84, 1.03</span></p></td>
<td class="cl-bd90c56b"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.2</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c544"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c54c"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">weight</span></p></td>
<td class="cl-bd90c54d"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.07</span></p></td>
<td class="cl-bd90c556"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.85, 1.36</span></p></td>
<td class="cl-bd90c557"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.6</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-bd90c588"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe"></span></p></td>
<td class="cl-bd90c589"><p class="cl-bd90b0b6"><span class="cl-bd8d6fbe">creatinin</span></p></td>
<td class="cl-bd90c58a"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.31</span></p></td>
<td class="cl-bd90c592"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">1.03, 1.68</span></p></td>
<td class="cl-bd90c593"><p class="cl-bd90b0b7"><span class="cl-bd8d6fbe">0.029</span></p></td>
</tr>
</tbody>
<tfoot><tr style="overflow-wrap:break-word;"><td colspan="5" class="cl-bd90c594"><p class="cl-bd90b0c0"><span class="cl-bd8d6fc8">1</span><span class="cl-bd8d6fbe">OR = Odds Ratio, CI = Confidence Interval</span></p></td></tr></tfoot>
</table>
</div>
</div>
</div>
</div>
<p>Leider wird die Sache mit einer multinominalen Regression sehr unangenehm, wenn wir wirklich nicht sortierbare Level im Outcome haben. Dann haben wir aber noch ein Möglichkeit der multinominalen Regression zu entkommen. Wir rechnen einfach separate logistische Regressionen. Die logistischen Regressionen können wir dann ja separat gut interpretieren.</p>
</section><section id="logistische-regression-als-ausweg" class="level2 page-columns page-full" data-number="42.7"><h2 data-number="42.7" class="anchored" data-anchor-id="logistische-regression-als-ausweg">
<span class="header-section-number">42.7</span> Logistische Regression als Ausweg</h2>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Bitte Beachten bei der Berechung über separate logistische Regressionen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Durch die Verwendung von separaten logistischen Regressionen vermindern wir die Fallzahl je gerechneter Regression, so dass wir <em>größere</em> <span class="math inline">\(p\)</span>-Werte erhalten werden als in einer multinominalen Regression. Oder andersherum, durch die verminderte Fallzahl in den separaten logistischen Regressionen haben wir eine geringere Power einen signifikanten Unterschied nachzuweisen.</p>
</div>
</div>
<p>Es gibt den einen Ring um sich zu knechten. Und das ist die logistische Regression. Gut die logistische Regression hilft jetzt nicht, wenn es mit Boniturnoten zu tun hast, aber wenn wir wenige Level im Outcome haben. In unserem Fall haben wir ja drei Level vorliegen, da können wir dann jeweils ein Level rausschmeißen und haben dann nur noch ein binäres Outcome. Das ist auch die zentrale Idee. Wir entfernen immer alle Level bis wir nur noch zwei Level in unserem Outcome haben und rechnen für diese beiden Level dann eine logistische Regression.</p>
<p>Schauen wir uns erstmal an, wie sich die Daten über die drei Kategorien in unserem Outcome verteilen. Wenn wir eine Kategorie im Outcome kaum vorliegen haben, könnten wir diese Daten vielleicht mit einer anderen Kategorie zusammenlegen oder aber müssen von unserer Idee hier Abstand nehmen.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span><span class="op">$</span><span class="va">frailty_fac</span> <span class="op">%&gt;%</span> <span class="va">tabyl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         .   n   percent
     frail  53 0.1286408
    robust 226 0.5485437
 pre-frail 133 0.3228155</code></pre>
</div>
</div>
<p>Wir haben nicht so viele Beobachtungen in der Kategorie <code>frail</code>. Wir könnten also auch die beiden Faktorlevel <code>pre-frail</code> und <code>frail</code> zusammenlegen.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Das R Paket <code>forcats</code> liefert sehr viele Funktion, die dir helfen Faktoren zu kodieren und zu ändern</span></div></div>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_tbl</span><span class="op">$</span><span class="va">frailty_fac</span> <span class="op">%&gt;%</span> 
  <span class="fu">fct_recode</span><span class="op">(</span>frail_pre_frail <span class="op">=</span> <span class="st">"frail"</span>, frail_pre_frail <span class="op">=</span> <span class="st">"pre-frail"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="va">tabyl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               .   n   percent
 frail_pre_frail 186 0.4514563
          robust 226 0.5485437</code></pre>
</div>
</div>
<p>Das ist jetzt aber nur eine Demonstration für die Zusammenlegung. Wir wollen jetzt trotzdem unsere drei logistischen Regressionen rechnen. Warum drei? Wir haben ja drei Level in unserem Outcome und wir werden jetzt uns drei Datensätze so bauen, dass in jdem Datensatz unser Outcome immer nur zwei Level hat. Die einzelnen Datensätze speichern wir dann in einer Liste.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_lst</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>robust_prefrail <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">pig_tbl</span>, <span class="va">frailty_fac</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"robust"</span>, <span class="st">"pre-frail"</span><span class="op">)</span><span class="op">)</span>,
                robust_frail <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">pig_tbl</span>, <span class="va">frailty_fac</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"robust"</span>, <span class="st">"frail"</span><span class="op">)</span><span class="op">)</span>,
                prefrail_frail <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">pig_tbl</span>, <span class="va">frailty_fac</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"pre-frail"</span>, <span class="st">"frail"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir können das auch fancy. Und das demonstriere ich dann mal hier. Wenn wir die Funktion <code><a href="https://rdrr.io/r/utils/combn.html">combn()</a></code> nutzen erhalten wir eine Liste mit allen zweier Kombinationen wieder. Diese Liste können wir dann in die Funktion <code>map()</code> stecken, die dann über die Liste unserer Kombinationen iteriert. Pro Liste filtern <code>map()</code> dann den Datensatz für uns heraus. Ja, ist ein wenig <em>over the top</em>, aber ich wollte das mal für mich mit <code>map()</code> ausprobieren und es passte hier so schön.</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_fancy_lst</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/combn.html">combn</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"robust"</span>, <span class="st">"pre-frail"</span>, <span class="st">"frail"</span><span class="op">)</span>, <span class="fl">2</span>, simplify <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">map</span><span class="op">(</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">pig_tbl</span>, <span class="va">frailty_fac</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">.x</span><span class="op">)</span><span class="op">)</span> </code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Egal wie du auf die Liste gekommen bist, wir müssen noch die überflüssigen Level <em>droppen</em>. Keine Ahnung was das deutsche Wort ist. Vermutlich ist das deutsche Wort dann entfernen. Dann können wir für jeden der Listeneinträge die logistische Regression rechnen. Am Ende lassen wir uns noch die exponierten Modellfits ausgeben. In der letzten Zeile entferne ich noch den Intercept von der Ausgabe des Modells. Den Intercept brauchen wir nun wirklich nicht.</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pig_lst</span> <span class="op">%&gt;%</span> 
  <span class="fu">map</span><span class="op">(</span><span class="op">~</span><span class="fu">mutate</span><span class="op">(</span><span class="va">.x</span>, frailty_fac <span class="op">=</span> <span class="fu">fct_drop</span><span class="op">(</span><span class="va">frailty_fac</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">map</span><span class="op">(</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">frailty_fac</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">location</span> <span class="op">+</span> <span class="va">activity</span> <span class="op">+</span> <span class="va">crp</span> <span class="op">+</span> <span class="va">bloodpressure</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">creatinin</span>, 
           data <span class="op">=</span> <span class="va">.x</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">map</span><span class="op">(</span><span class="va">model_parameters</span>, exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">map</span><span class="op">(</span><span class="va">extract</span>, <span class="op">-</span><span class="fl">1</span>, <span class="op">)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$robust_prefrail
Parameter            | Odds Ratio |   SE |       95% CI |     z |     p
-----------------------------------------------------------------------
age                  |       1.04 | 0.03 | [0.99, 1.09] |  1.52 | 0.127
sex [male]           |       1.58 | 0.51 | [0.85, 3.00] |  1.44 | 0.151
location [northeast] |       0.66 | 0.22 | [0.35, 1.25] | -1.26 | 0.209
location [northwest] |       0.65 | 0.19 | [0.36, 1.14] | -1.51 | 0.132
location [west]      |       0.96 | 0.31 | [0.51, 1.80] | -0.13 | 0.895
activity             |       0.83 | 0.07 | [0.70, 0.98] | -2.19 | 0.028
crp                  |       0.93 | 0.07 | [0.79, 1.08] | -0.95 | 0.342
bloodpressure        |       0.98 | 0.03 | [0.92, 1.06] | -0.44 | 0.657
weight               |       1.09 | 0.09 | [0.93, 1.28] |  1.05 | 0.295
creatinin            |       1.11 | 0.09 | [0.94, 1.31] |  1.23 | 0.220

$robust_frail
Parameter            | Odds Ratio |   SE |       95% CI |     z |     p
-----------------------------------------------------------------------
age                  |       1.04 | 0.04 | [0.97, 1.12] |  1.09 | 0.275
sex [male]           |       0.52 | 0.23 | [0.21, 1.24] | -1.46 | 0.144
location [northeast] |       1.26 | 0.55 | [0.54, 3.05] |  0.52 | 0.603
location [northwest] |       1.94 | 0.82 | [0.86, 4.52] |  1.57 | 0.116
location [west]      |       1.06 | 0.46 | [0.45, 2.53] |  0.13 | 0.900
activity             |       1.06 | 0.13 | [0.84, 1.34] |  0.47 | 0.638
crp                  |       1.28 | 0.14 | [1.03, 1.60] |  2.17 | 0.030
bloodpressure        |       0.94 | 0.05 | [0.85, 1.04] | -1.22 | 0.223
weight               |       1.00 | 0.11 | [0.81, 1.24] |  0.01 | 0.992
creatinin            |       1.22 | 0.15 | [0.96, 1.55] |  1.64 | 0.100

$prefrail_frail
Parameter            | Odds Ratio |   SE |       95% CI |     z |     p
-----------------------------------------------------------------------
age                  |       1.06 | 0.04 | [0.99, 1.14] |  1.61 | 0.108
sex [male]           |       0.77 | 0.41 | [0.27, 2.19] | -0.48 | 0.632
location [northeast] |       1.04 | 0.50 | [0.41, 2.71] |  0.08 | 0.938
location [northwest] |       1.23 | 0.57 | [0.49, 3.10] |  0.44 | 0.660
location [west]      |       1.08 | 0.51 | [0.44, 2.75] |  0.17 | 0.866
activity             |       0.95 | 0.13 | [0.73, 1.23] | -0.39 | 0.695
crp                  |       1.15 | 0.13 | [0.91, 1.45] |  1.18 | 0.240
bloodpressure        |       0.93 | 0.05 | [0.82, 1.04] | -1.34 | 0.182
weight               |       1.05 | 0.13 | [0.82, 1.36] |  0.42 | 0.673
creatinin            |       1.26 | 0.16 | [1.00, 1.63] |  1.87 | 0.061</code></pre>
</div>
</div>
<p>Eine Sache ist super wichtig zu wissen. Wie oben schon geschrieben, durch die Verwendung von separaten logistischen Regressionen vermindern wir die Fallzahl je Regression, so dass wir größere <span class="math inline">\(p\)</span>-Werte erhalten werden, als in einer multinominalen Regression. Das ist der Preis, den wir dafür bezahlen müssen, dass wir besser zu interpretierende Koeffizienten erhalten. Und das ist auch vollkommen in Ordnung. Ich selber habe lieber Koeffizienten, die ich interpretieren kann, als unklare Effekte mit niedrigen <span class="math inline">\(p\)</span>-Werten.</p>
<p>Schauen wir einmal auf unseren Goldstandard, der Variable für den CRP-Wert. Die Variable haben wir ja jetzt immer mal wieder in diesem Kapitel interpretiert und uns angeschaut. Die Variable <code>crp</code> passt von dem Effekt jedenfalls gut in den Kontext mit rein. Die Effekte sind ähnlich wie in der multinominalen Regression. Wir haben eben nur größere <span class="math inline">\(p\)</span>-Werte. Jetzt müssen wir entscheiden, wir können vermutlich die getrennten logistischen Regressionen besser beschreiben und interpretieren. Das ist <em>besonders</em> der Fall, wenn wir wirklich Probleme haben eine Referenz in der multinominalen Regression festzulegen. Dann würde ich immer zu den getrennten logistischen Regressionen greifen als eine schief interpretierte multinominale Regression.</p>
</section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-dormann2013parametrische" class="csl-entry" role="doc-biblioentry">
Dormann, Carsten F. 2013. <em>Parametrische Statistik</em>. Springer.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-modeling-poisson.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-logistic.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>