<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 49&nbsp; Überlebenszeitanalysen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-modeling-noninferiority.html" rel="next">
<link href="./stat-modeling-robust-quantile.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-modeling-preface.html">Statistisches Modellieren</a></li><li class="breadcrumb-item"><a href="./stat-modeling-survival.html"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frequentistische Hypothesentests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen der linearen Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Permutationstest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Einfache experimentelle Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Fortgeschrittene experimentelle Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Anhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spielecke</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link active" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"><span class="header-section-number">49.1</span> Genutzte R Pakete für das Kapitel</a></li>
  <li>
<a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"><span class="header-section-number">49.2</span> Daten</a>
  <ul class="collapse">
<li><a href="#%C3%BCberleben-von-dodos" id="toc-überleben-von-dodos" class="nav-link" data-scroll-target="#%C3%BCberleben-von-dodos"><span class="header-section-number">49.2.1</span> Überleben von Dodos</a></li>
  <li><a href="#%C3%BCberleben-von-fruchtfliegen" id="toc-überleben-von-fruchtfliegen" class="nav-link" data-scroll-target="#%C3%BCberleben-von-fruchtfliegen"><span class="header-section-number">49.2.2</span> Überleben von Fruchtfliegen</a></li>
  <li><a href="#%C3%BCberleben-von-lungenkrebs" id="toc-überleben-von-lungenkrebs" class="nav-link" data-scroll-target="#%C3%BCberleben-von-lungenkrebs"><span class="header-section-number">49.2.3</span> Überleben von Lungenkrebs</a></li>
  </ul>
</li>
  <li><a href="#die-surv-funktion" id="toc-die-surv-funktion" class="nav-link" data-scroll-target="#die-surv-funktion"><span class="header-section-number">49.3</span> Die <code>Surv()</code> Funktion</a></li>
  <li>
<a href="#visualisierung-%C3%BCber-kaplan-meier-kurven" id="toc-visualisierung-über-kaplan-meier-kurven" class="nav-link" data-scroll-target="#visualisierung-%C3%BCber-kaplan-meier-kurven"><span class="header-section-number">49.4</span> Visualisierung über Kaplan Meier Kurven</a>
  <ul class="collapse">
<li><a href="#dodos" id="toc-dodos" class="nav-link" data-scroll-target="#dodos"><span class="header-section-number">49.4.1</span> Dodos</a></li>
  <li><a href="#fruchtfliegen" id="toc-fruchtfliegen" class="nav-link" data-scroll-target="#fruchtfliegen"><span class="header-section-number">49.4.2</span> Fruchtfliegen</a></li>
  <li><a href="#lungenkrebs" id="toc-lungenkrebs" class="nav-link" data-scroll-target="#lungenkrebs"><span class="header-section-number">49.4.3</span> Lungenkrebs</a></li>
  </ul>
</li>
  <li><a href="#cox-proportional-hazards-modell" id="toc-cox-proportional-hazards-modell" class="nav-link" data-scroll-target="#cox-proportional-hazards-modell"><span class="header-section-number">49.5</span> Cox Proportional-Hazards Modell</a></li>
  <li><a href="#logistische-regression" id="toc-logistische-regression" class="nav-link" data-scroll-target="#logistische-regression"><span class="header-section-number">49.6</span> Logistische Regression</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-survival" class="quarto-section-identifier"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><em>Version vom August 10, 2023 um 21:44:28</em></p>
<p>In diesem Kapitel wollen wir uns nochmal mit der Zeit beschäftigen. Wir haben hier aber keine zeitlichen Messwiederholungen an dem gleichen Subjekt, Tier oder Pflanze vorliegen sondern wir schauen uns an, wie lange es dauert bis ein Ereignis eintritt. Deshalb nennen wir diese Analysen algemein Ereigniszeitanalysen. Häufig schauen wir uns aber die zeit an, die es braucht, bis das Ereignis “tot” für eine Beobachtung eintritt. Daher heißt das Kapitel auch Überlebenszeitanalysen (eng. <em>survival analysis</em>).</p>
<p>Überlebenszeitanalysen sind in den Humanwissenschaften und inbesondere in der Onkologie <em>das</em> Thema schlechthin. Wir beantworten hier die Fragen nach <em>3 Monatsmortalität</em> und wollen wissen, wie viele patienten nach einer Behandlung mit einem Krebsmedikament nach drei Monaten noch leben. Du kanst dir vorstellen, dass es hier eine Menge an Annahmen und Modellen gibt. Wir wollen uns hier in dem Kapitel die Grundlagen anschauen. Da vieles in der Wissenschaft meist in englischer Sprache abläuft, kann ich hier sehr den das Buch von <span class="citation" data-cites="david2012survival">David und Mitchel (<a href="#ref-david2012survival" role="doc-biblioref">2012</a>)</span> empfehlen. Insbesondere die Einführungskapitel sind sehr gut geschrieben. Diese Detailtiefe wie bei <span class="citation" data-cites="david2012survival">David und Mitchel (<a href="#ref-david2012survival" role="doc-biblioref">2012</a>)</span> werde ich in diesem Abschnitt nicht erreichen. In den Agrarwissenschaften ist alles ein wenig anders als in den Humanwissenschaften.</p>
<p>Wie bereits erwähnt, konzentriert sich die Überlebensanalyse auf die erwartete Zeitdauer bis zum Auftreten eines Ereignisses von Interesse. Das Ereignis von Interesse ist dann meist ein Rückfall (eng. <em>relapse</em>) oder eben tot (eng. <em>death</em>). Es kann jedoch sein, dass das Ereignis bei einigen Personen innerhalb des Untersuchungszeitraums nicht beobachtet wird, was zu sogenannten zensierten Beobachtungen führt. Die Zensierung kann auf folgende Weise erfolgen:</p>
<ul>
<li>Ein Patient hat das interessierende Ereignis, wie Rückfall oder Tod, innerhalb des Studienzeitraums (noch) nicht erlebt;</li>
<li>ein Patient wird während des Studienzeitraums nicht weiter beobachtet;</li>
<li>bei einem Patienten tritt ein anderes Ereignis ein, das eine weitere Beobachtung unmöglich macht.</li>
</ul>
<p>Diese Art der Zensierung, die als rechte Zensierung (eng. <em>right censoring</em>) bezeichnet wird, wird in der Überlebensanalyse in diesem Kapitel behandelt.</p>
<p>Am Ende muss ich dann nochmal auf die <em>proportional hazards assumption</em> hinweisen. Wir gehen davon aus, dass die Risiken im Zeitverlauf proportional sind, was bedeutet, dass die Wirkung eines Risikofaktors im Zeitverlauf konstant ist. Das ist jetzt etwas umständlich ausgedrückt, aber wir sagen, dass die Wahrscheinlichkeit zu Sterben über die ganze Studie immer konstant ist. Männer fangen also nicht nach <span class="math inline">\(t\)</span> Tagen an zügiger zu Versterben als Frauen. Wenn wir eine Verletzung der <em>proportional hazards assumption</em> vorliegen haben, dann müssen wir nochmal tiefer in das Thema einsteigen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir immer gibt es eine gute Auswahl an aktuellen Tutorien <a href="http://www.sthda.com/english/wiki/survival-analysis-basics">Survival Analysis Basics</a>, die hier auch aufgegrifen werden. Ein umfangreicheres Tutorium in R findet sich unter <a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Survival Analysis in R</a>.</p>
</div></div><section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="49.1"><h2 data-number="49.1" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">49.1</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">conflicted</span>, <span class="va">broom</span>,</span>
<span>               <span class="va">survminer</span>, <span class="va">survival</span>, <span class="va">parameters</span>,</span>
<span>               <span class="va">gtsummary</span>, <span class="va">janitor</span>, <span class="va">ranger</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"mutate"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="va">cbbPalette</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#000000"</span>, <span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, </span>
<span>                <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2" data-number="49.2"><h2 data-number="49.2" class="anchored" data-anchor-id="daten">
<span class="header-section-number">49.2</span> Daten</h2>
<p>Insgesamt schauen wir uns in diesem Kapitel dann drei Datensätze an. Einmal einen Datensatz der sehr simple ist und nochmal erklärt wie die Datenstruktur in R aussehen muss. Dafür nutzen wir das Überleben von Dodos. Dann einen Datensatz, der etwas komplizierter ist. Wir betrachten hier das Überleben von Fruchtfliegen. Den Abschluss bildet ein Datensatz zu einer klinischen Studie von Lungenkrebs. Der Datensatz wird viel in Beispielen genutzt, so dass ich den Datensatz auch hier nochmal vorstellen möchte.</p>
<section id="überleben-von-dodos" class="level3" data-number="49.2.1"><h3 data-number="49.2.1" class="anchored" data-anchor-id="überleben-von-dodos">
<span class="header-section-number">49.2.1</span> Überleben von Dodos</h3>
<p>Wir schauen uns hier das Überleben von Dodos mit oder ohne Schnabelstutzen an. Wir schauen dann an jedem Lebenstag, wie viele Dodos verstorben sind. Da wir es hier mit sehr schnell wachsenden Dodos zu tun haben, ist der Datensatz nicht so lang was die Zeit angeht. Wir beobachten nur die ersten 55 Lebenstage (eng. <em>days of life</em>, abk. <em>dol</em>) bevor die Dodos dann geschlachtet werden. In der <a href="#tbl-surv-dodo-1">Tabelle&nbsp;<span>49.1</span></a> sehen wir die rohen Daten, die wir in der Form nicht analysieren können. Wir müssen uns hier etwas strecken, damit das Format der Daten für die Überlebenszeitanalyse passt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-surv-dodo-1" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;49.1— Rohe Datentabelle mit den jeweiligen Lebenstagen (abk. <em>dol</em>) und der Anzahl an lebenden sowie toten Dodos an den entsprechenden Tagen.</caption>
<thead><tr class="header">
<th style="text-align: center;">trt</th>
<th style="text-align: center;">dol</th>
<th style="text-align: center;">count</th>
<th style="text-align: center;">death</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">245</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">clipped</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">179</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">clipped</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">177</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">clipped</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">176</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">clipped</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">173</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">clipped</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">clipped</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">163</td>
<td style="text-align: center;">7</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Unsere Daten zu den Dodos beinhalten die folgenden Spalten mit den entsprechenden Bedeutungen.</p>
<ul>
<li>
<strong>trt</strong>, die Behandlung der Schnäbel mit <code>none</code> und <code>clipped</code>
</li>
<li>
<strong>dol</strong>, der <em>day of life</em> also der Lebenstag der Dodos</li>
<li>
<strong>count</strong>, die Anzahl an lebenden Dodos an dem entprechenden <em>day of life</em>
</li>
<li>
<strong>death</strong>, die Anzahl an tot aufgefundenen Dodos an dem entpsrechenden <em>day of life</em>
</li>
</ul>
<p>Wir haben somit <span class="math inline">\(n = 500\)</span> beobachtete Dodos mit jeweils 250 für jede der beiden Schnabelbehandlungen. Jetzt brauchen wir aber wie immer einen Datansatz in dem jede Zeile einen beobachteten Dodo entspricht. In der <a href="#tbl-surv-dodo-2-example">Tabelle&nbsp;<span>49.2</span></a> sehen wir welche Art von Tabelle wir bauen müssen.</p>
<div id="tbl-surv-dodo-2-example" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;49.2— Beispielhafte Datentabelle für die Analyse der Dododaten. Jede Zeile entspricht einem beobachteten Dodo und dem entsprechenden Informationen zur Lebensdauer und Schnabelbehandlung.</caption>
<thead><tr class="header">
<th>dodo_id</th>
<th>trt</th>
<th>dol</th>
<th>death</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>none</td>
<td>6</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>none</td>
<td>6</td>
<td>1</td>
</tr>
<tr class="odd">
<td>3</td>
<td>none</td>
<td>7</td>
<td>1</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>249</td>
<td>none</td>
<td>55</td>
<td>0</td>
</tr>
<tr class="even">
<td>250</td>
<td>none</td>
<td>55</td>
<td>0</td>
</tr>
<tr class="odd">
<td>251</td>
<td>clipped</td>
<td>6</td>
<td>1</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>500</td>
<td>clipped</td>
<td>55</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
<p>Fangen wir also mit der Information an, die wir haben. Wir wissen wie viele Dodos jeweils zu einem bestimmten Lebenstag gestorben sind. Daher können wir anhand der Spalte <code>death</code> die Anzahl an Zeilen entsprechend vervielfältigen. Sind an einem Lebenstag drei Dodos gestorben, dann brauchen wir dreimal eine Zeile mit der Information des Lebenstages und dass an diesem Tag ein Dodo gestorben ist. Wir nutzen dazu die Funktion <code>uncount()</code>. Dann erschaffen wir noch eine Spalte <code>death</code> in der einfach immer eine <code>1</code> steht, da ja an diesem Lebenstag ein Dodo verstorben ist.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">death_tbl</span> <span class="op">&lt;-</span> <span class="va">dodo_raw_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">uncount</span><span class="op">(</span><span class="va">death</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>death <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">.</span><span class="op">$</span><span class="va">dol</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Im nächsten Schritt müssen wir die lebenden Dodos <em>separat für jede Behandlung</em> ergänzen. Daher spalten wir uns die Daten in eine Liste auf und ergänzen dann die Informationen zu den fehlenden, lebenden Dodos. Alle lebenden Dodos haben die maximale Lebenszeit, sind nicht gestorben und damit bleibt die Anzahl auch konstant.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alive_tbl</span> <span class="op">&lt;-</span> <span class="va">death_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/split.html">split</a></span><span class="op">(</span><span class="va">.</span><span class="op">$</span><span class="va">trt</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">map</span><span class="op">(</span><span class="op">~</span><span class="fu">tibble</span><span class="op">(</span>dol <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">dol</span><span class="op">)</span>,</span>
<span>              death <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fu">last</span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">count</span><span class="op">)</span><span class="op">)</span>,</span>
<span>              count <span class="op">=</span> <span class="fu">last</span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">bind_rows</span><span class="op">(</span>.id <span class="op">=</span> <span class="st">"trt"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wenn wir die Informationen zu toten und den noch lebenden Dodos gebaut haben, können wir uns dann einen finalen Datensatz zusammenkleben.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dodo_tbl</span> <span class="op">&lt;-</span> <span class="fu">bind_rows</span><span class="op">(</span><span class="va">death_tbl</span>, <span class="va">alive_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#tbl-surv-dodo-2">Tabelle&nbsp;<span>49.3</span></a> sehen wir den finalen Dododatensatz, den wir uns aus den Informationen zusammengebaut haben. Wir haben hier einmal die Struktur eines Überlebenszeitdatensatzes gelernt und das wir manchmal uns ganz schön strecken müssen um die Daten dann auch gut umzubauen. Wir werden am Ende nur die Informationen in der Spalte <code>dol</code>, <code>death</code> und <code>trt</code> nutzen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-surv-dodo-2" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;49.3— Finaler Dododatensatz für die Überlebenszeitanalysen.</caption>
<thead><tr class="header">
<th style="text-align: center;">trt</th>
<th style="text-align: center;">dol</th>
<th style="text-align: center;">count</th>
<th style="text-align: center;">death</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">245</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">245</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">245</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">245</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">245</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">241</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">none</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">none</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section><section id="überleben-von-fruchtfliegen" class="level3" data-number="49.2.2"><h3 data-number="49.2.2" class="anchored" data-anchor-id="überleben-von-fruchtfliegen">
<span class="header-section-number">49.2.2</span> Überleben von Fruchtfliegen</h3>
<p>Im folgenden Beispiel in <a href="#tbl-surv-2">Tabelle&nbsp;<span>49.4</span></a> beobachten wir Fruchtfliegen bis fast alle Insekten verstorben sind. Das ist natürlich das andere Extrem zu den Dododatensatz. Wir testen hier ein Insektizid und am Ende haben wir dann keine lebenden Fruchtfliegen mehr. Das würdest du mit Dodos oder Schweinen nicht machen, denn so lange möchtest du die Tiere ja auch nicht beobachten, bis alle gestorben sind. Bei Fruchtfliegen dauert es eben nicht so lange bis alle Fliegen verstorben sind.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-surv-2" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;49.4— Fruchtfliegendatensatz mit verschiedenen Covariaten zu der Behandlung, der Zeit und dem Status der Fruchtfliegen.</caption>
<thead><tr class="header">
<th style="text-align: center;">trt</th>
<th style="text-align: center;">time</th>
<th style="text-align: center;">status</th>
<th style="text-align: center;">sex</th>
<th style="text-align: center;">weight</th>
<th style="text-align: center;">weight_bin</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">fruitflyEx</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">8.13</td>
<td style="text-align: center;">low</td>
</tr>
<tr class="even">
<td style="text-align: center;">fruitflyEx</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">7.75</td>
<td style="text-align: center;">low</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fruitflyEx</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">9.86</td>
<td style="text-align: center;">low</td>
</tr>
<tr class="even">
<td style="text-align: center;">fruitflyEx</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">6.36</td>
<td style="text-align: center;">low</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">control</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">21.02</td>
<td style="text-align: center;">high</td>
</tr>
<tr class="odd">
<td style="text-align: center;">control</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">16.45</td>
<td style="text-align: center;">high</td>
</tr>
<tr class="even">
<td style="text-align: center;">control</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">14.17</td>
<td style="text-align: center;">low</td>
</tr>
<tr class="odd">
<td style="text-align: center;">control</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">17.73</td>
<td style="text-align: center;">high</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Unsere Daten zu den Fruchtfliegen beinhalten die folgenden Spalten mit den entsprechenden Bedeutungen.</p>
<ul>
<li>
<strong>trt</strong>, als die Behandlung mit den beiden Leveln <code>fruitflyEx</code> und <code>control</code>
</li>
<li>
<strong>time</strong>, den Zeitpunkt des Todes der entsprechenden Fruchfliege</li>
<li>
<strong>status</strong>, den Status der Fruchtfliege zu dem Zeitpunkt <code>time</code>. Hier meist <code>1</code> und damit tot, aber ein paar Fruchtfliegen sind bei der Überprüfung entkommen und haben dann eine <code>0</code>.</li>
<li>
<strong>sex</strong>, das Geschlecht der entsprechenden Fruchtfliege</li>
<li>
<strong>weight</strong>, das Gewicht der entsprechenden Fruchtfliege in <span class="math inline">\(\mu g\)</span>.</li>
<li>
<strong>weight_bin</strong> das Gewicht der entsprechenden Fruchtfliege aufgeteilt in zwei Gruppen nach dem Cutpoint von <span class="math inline">\(15 \mu g\)</span>.</li>
</ul></section><section id="überleben-von-lungenkrebs" class="level3" data-number="49.2.3"><h3 data-number="49.2.3" class="anchored" data-anchor-id="überleben-von-lungenkrebs">
<span class="header-section-number">49.2.3</span> Überleben von Lungenkrebs</h3>
<p>Zum Abschluss möchte ich noch den Datensatz <code>lung</code> in der <a href="#tbl-surv-3">Tabelle&nbsp;<span>49.5</span></a> aus dem R Paket <code>survival</code> vorstellen. Das hat vor allem den Grund, dass es sich hier um einen klassischen Datensatz zur Überlebenszeitanalyse handelt und ich auch dieses Teilgebiet einmal mit abdecken möchte. Wie schon weiter oben gesagt, Überlebenszeitanalysen kommen eher in dem Humanbereich vor. Darüber hinaus bedienen sich fast alle anderen Tutorien im Internet diesem Datensatz, so dass du dann einfacher die englischen Texte nachvollziehen kannst.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-surv-3" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;49.5— Der Datensatz <code>lung</code> über eine Beobachtungsstudiue Studie zu Lungenkrebs.</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 11%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">inst</th>
<th style="text-align: center;">time</th>
<th style="text-align: center;">status</th>
<th style="text-align: center;">age</th>
<th style="text-align: center;">sex</th>
<th style="text-align: center;">ph.ecog</th>
<th style="text-align: center;">ph.karno</th>
<th style="text-align: center;">pat.karno</th>
<th style="text-align: center;">meal.cal</th>
<th style="text-align: center;">wt.loss</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">306</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">74</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">1175</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">455</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">68</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">1225</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">1010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">1150</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">13</td>
<td style="text-align: center;">191</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">2350</td>
<td style="text-align: center;">-5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">32</td>
<td style="text-align: center;">105</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">1025</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">174</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">66</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">1075</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">22</td>
<td style="text-align: center;">177</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">1060</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li>
<strong>inst</strong> Institution code</li>
<li>
<strong>time</strong> Survival time in days</li>
<li>
<strong>status</strong> censoring status 1=censored, 2=dead</li>
<li>
<strong>age</strong> Age in years</li>
<li>
<strong>sex</strong> Male=1 Female=2</li>
<li>
<strong>ph.ecog</strong> ECOG performance score (0=good 5=dead)</li>
<li>
<strong>ph.karno</strong> Karnofsky performance score (bad=0-good=100) rated by physician</li>
<li>
<strong>pat.karno</strong> Karnofsky performance score as rated by patient</li>
<li>
<strong>meal.cal</strong> Calories consumed at meals</li>
<li>
<strong>wt.loss</strong> Weight loss in last six months</li>
</ul>
<p>Trotz seiner Prominenz hat der Datensatz einen Fehler. Wir wollen den Status nicht auf 1/2 kodiert haben sondern auf 0/1. Ebenso wollen wir die Spalte <code>inst</code> nicht, da wir die Informationen nicht brauchen. Dann sind noch die Namen der Spalten hässlich, so dass wir da die Funktion <code>clean_names()</code> nutzen um einmal aufzuräumen.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lung_tbl</span> <span class="op">&lt;-</span> <span class="va">lung</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>status <span class="op">=</span> <span class="fu">recode</span><span class="op">(</span><span class="va">status</span>, `1` <span class="op">=</span> <span class="fl">0</span>, `2` <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">clean_names</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">inst</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="die-surv-funktion" class="level2" data-number="49.3"><h2 data-number="49.3" class="anchored" data-anchor-id="die-surv-funktion">
<span class="header-section-number">49.3</span> Die <code>Surv()</code> Funktion</h2>
<p>Als <em>die</em> Besonderheit bei der Bearbeitung von Überlebenszeitanalysen ist die Andersartigkeit von unserem <span class="math inline">\(y\)</span>. Wir haben ja <em>zwei</em> Spalten, die das Outcome beschreiben. Zum einen die Dauer oder Zeit bis zum Ereignis und dann die Spalte, die beschreibt, ob das Ereignis überhaupt eingetreten ist. In R lösen wir dieses Problem in dem wir zwei Spalten in dem Objekt <code>Surv()</code> zusammenführen. Alle Analysen in R gehen nur mit dem <code>Surv()</code> Objekt.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">death</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In dem Objekt <code>Surv()</code> haben wir erst die Spalte für die Zeit und dann die Spalte für das Ereignis. Für den Dododatensatz haben wir dann folgende Zusammenhänge.</p>
<ul>
<li>
<code>dol</code> in den Daten <code>dodo_tbl</code> ist gleich <code>time</code> in dem <code>Surv()</code> Objekt</li>
<li>
<code>death</code> in den Daten <code>dodo_tbl</code> ist gleich <code>death</code> in dem <code>Surv()</code> Objekt</li>
</ul>
<p>Bei dem Fruchfliegendatensatz sieht die Sachlage dann so aus.</p>
<ul>
<li>
<code>time</code> in den Daten <code>fruitfly_tbl</code> ist gleich <code>time</code> in dem <code>Surv()</code> Objekt</li>
<li>
<code>status</code> in den Daten <code>fruitfly_tbl</code> ist gleich <code>death</code> in dem <code>Surv()</code> Objekt</li>
</ul>
<p>Für den Lungenkrebsdatensatz haben wir dann folgende Zuordnung.</p>
<ul>
<li>
<code>time</code> in den Daten <code>lung_tbl</code> ist gleich <code>time</code> in dem <code>Surv()</code> Objekt</li>
<li>
<code>status</code> in den Daten <code>lung_tbl</code> ist gleich <code>death</code> in dem <code>Surv()</code> Objekt</li>
</ul>
<p>Im Folgenden haben wir dann immer auf der linken Seite vom <code>~</code> ein <code>Surv()</code> Objekt stehen. Daran muss man sich immer etwas gewöhnen, sonst kommt sowas ja nicht in den Analysen vor.</p>
</section><section id="visualisierung-über-kaplan-meier-kurven" class="level2 page-columns page-full" data-number="49.4"><h2 data-number="49.4" class="anchored" data-anchor-id="visualisierung-über-kaplan-meier-kurven">
<span class="header-section-number">49.4</span> Visualisierung über Kaplan Meier Kurven</h2>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nur kategoriale Variablen in einer Kaplan Meier Kurve
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wir können nur kategoriale Variablen in einer Kaplan Meier Kurve darstellen. Das heißt, wir müssen alle unsere <span class="math inline">\(x\)</span>, die kontinuierlich sind in eine kategoriale Variable umwandeln.</p>
</div>
</div>
<p>Wir können nur kategoriale Variablen in einer Kaplan Meier Kurve darstellen. Das heißt, wir müssen alle unser <span class="math inline">\(X\)</span>, die wir haben, in Variablen mit Kategorien umwandeln. Wenn du also in deinen Daten eine Spalte für das Gewicht in kg hast, dann musst du dir überlegen, wie du diese Werte in Kategorien änderst. Eine beliebte Variante ist, dass du zwei Gruppen bildest. Einmal die Patienten, die schwerer sind als der Median des Körpergewichts und einmal eine Gruppe für die Patienten, die leichter sind als der Median des Körpergewichts. Die Kategorisierung von Variablen ist faktisch ein eigenes Problem und lässt sich ohne den biologischen Hintergrund eigentlich nicht sauber durchführen. Daher werden in klinischen Studien oder Experimenten die Daten gleich in Kategorien erhoben. Daher gibt es vorab klare Kriterien in welcher Gewichtsklasse oder Altersklasse ein Patient landen wird. Das Gleiche gilt dann auch für andere kontinuierlichen Variablen.</p>
<p>Ein häufiger Fehler bei der Betrachtung der Kaplan Meier Kurve ist diese als die simple lineare Regression der Überlebenszeitanalyse anzusehen. Wir können zwar mit der Kaplan Meier Kurve immer nur <em>ein</em> <span class="math inline">\(X\)</span> betrachten aber der Algorithmus basiert auf dem <span class="math inline">\(\mathcal{X}^2\)</span>-Test und hat nichts mit einer Regression zu tun. Daher <em>kann</em> es sein, dass du unterschiedliche Ergebnisse in der Visualisierung mit Kaplan Meier Kurven und dann der Analyse mit dem Cox Proportional-Hazards Modell erhälst.</p>
<p>In R nutzen wir das Paket <code>survminer</code> und die Funktion <code>ggsurvplot()</code> für die Visualisierung der Kaplan Meier Kurven.</p>
<section id="dodos" class="level3" data-number="49.4.1"><h3 data-number="49.4.1" class="anchored" data-anchor-id="dodos">
<span class="header-section-number">49.4.1</span> Dodos</h3>
<p>Um eine Kaplan Meier Kurve zeichnen zu können, brauchen wie als erstes die Funktion <code>survfit()</code>. Mit der Funktion <code>survfit()</code> können wir zum einen das mediane Überleben berechnen und alle Informationen erhalten, die wir brauchen um die Kaplan Meier Kurve zu plotten.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trt_fit</span> <span class="op">&lt;-</span> <span class="fu">survfit</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">dol</span>, <span class="va">death</span><span class="op">)</span> <span class="op">~</span> <span class="va">trt</span>, data <span class="op">=</span> <span class="va">dodo_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir können einmal das Objekt <code>trt_fit</code> uns anschauen.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trt_fit</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(dol, death) ~ trt, data = dodo_tbl)

              n events median 0.95LCL 0.95UCL
trt=clipped 250     87     NA      NA      NA
trt=none    250    165   44.5      40      49</code></pre>
</div>
</div>
<p>Zum einen fallen uns die <code>NA</code>’s in der Wiedergabe des Fits der Überlebenszeit auf. Wenn wir uns die <a href="#fig-surv-1">Abbildung&nbsp;<span>49.1</span></a> einmal anschauen, dann wird das Problem etwas klarer. Wir sehen nämlich, dass wir bei den geklippten Tieren gar nicht so weit runter kommen mit den toten Tieren, dass wir das mediane Überleben berechnen könnten. Nicht immer können wir auch alle statistischen Methoden auf alle Fragestellungen anwenden. Insbesondere wenn nicht genug Ereignisse wie in diesem Beispiel auftreten.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggsurvplot</span><span class="op">(</span><span class="va">trt_fit</span>, </span>
<span>           data <span class="op">=</span> <span class="va">dodo_tbl</span>, </span>
<span>           risk.table <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>,</span>
<span>           ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>,</span>
<span>           palette <span class="op">=</span> <span class="va">cbbPalette</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surv-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-survival_files/figure-html/fig-surv-1-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.1— Kaplan Meier Kurven für unsere geklippten Dodos. Wir sehen, dass die geklippten Tiere in der Zeit der Versuchsdurchführung garnicht zur Hälfte versterben.</figcaption></figure>
</div>
</div>
</div>
</section><section id="fruchtfliegen" class="level3" data-number="49.4.2"><h3 data-number="49.4.2" class="anchored" data-anchor-id="fruchtfliegen">
<span class="header-section-number">49.4.2</span> Fruchtfliegen</h3>
<p>Gehen wir einen Schritt weiter und schauen uns das Modell für die Fruchtfliegen an. Hier haben wir eine Behandlung mit zwei Leveln also Gruppen vorliegen. Wir nutzen wieder die Funktion <code>survfit()</code> um einaml unser Modell der Überlebenszeiten zu fitten.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trt_fit</span> <span class="op">&lt;-</span> <span class="fu">survfit</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">trt</span>, data <span class="op">=</span> <span class="va">fruitfly_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir erhalten dann folgende Ausgabe des Modells.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trt_fit</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ trt, data = fruitfly_tbl)

                n events median 0.95LCL 0.95UCL
trt=fruitflyEx 50     44     12      10      14
trt=control    50     49     15      13      17</code></pre>
</div>
</div>
<p>In der <a href="#fig-surv-2">Abbildung&nbsp;<span>49.2</span></a> sehen wir die Visualisierung des Modells als Kaplan Meier Kurve. In diesem Experiment sterben fast alle Fruchtfliegen im Laufe der Untersuchung. Wir können also einfach das mediane Überleben für beide Gruppen berechnen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggsurvplot</span><span class="op">(</span><span class="va">trt_fit</span>, </span>
<span>           data <span class="op">=</span> <span class="va">fruitfly_tbl</span>, </span>
<span>           risk.table <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>,</span>
<span>           ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>,</span>
<span>           palette <span class="op">=</span> <span class="va">cbbPalette</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surv-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-survival_files/figure-html/fig-surv-2-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.2— Kaplan Meier Kurven für die Fruchtfliegen nach der Behandlung mit einem Pestizid und einer Kontrolle.</figcaption></figure>
</div>
</div>
</div>
<p>Nachdem wir die Kaplan Meier Kurven einmal für die Behandlung durchgeführt haben, können wir uns auch anschauen, ob das Überleben der Fruchtfliegen etwas mit dem Gewicht der Fruchtfliegen zu tun hat. Hier können wir <em>nicht</em> auf das Gewicht in der Spalte <code>weight</code> zurückgreifen sondern müssen die Variable <code>weight_bin</code> mit zwei Klassen nehmen.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">weight_fit</span> <span class="op">&lt;-</span> <span class="fu">survfit</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">weight_bin</span>, data <span class="op">=</span> <span class="va">fruitfly_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir erhalten dann die Kaplan Meier Kurven in der <a href="#fig-surv-3">Abbildung&nbsp;<span>49.3</span></a> zurück. Hier ist es wichtig sich nochmal klar zu machen, dass wir eben nur kategoriale Variablen in einer Kaplan Meier Kurve darstellen können.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggsurvplot</span><span class="op">(</span><span class="va">weight_fit</span>, </span>
<span>           data <span class="op">=</span> <span class="va">fruitfly_tbl</span>, </span>
<span>           risk.table <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>,</span>
<span>           ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>,</span>
<span>           palette <span class="op">=</span> <span class="va">cbbPalette</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surv-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-survival_files/figure-html/fig-surv-3-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.3— Kaplan Meier Kurven für die Fruchtfliegen nach der Behandlung mit einem Pestizid und einer Kontrolle.</figcaption></figure>
</div>
</div>
</div>
</section><section id="lungenkrebs" class="level3 page-columns page-full" data-number="49.4.3"><h3 data-number="49.4.3" class="anchored" data-anchor-id="lungenkrebs">
<span class="header-section-number">49.4.3</span> Lungenkrebs</h3>
<p>Als letztes Beispiel wollen wir uns nochmal den Datensatz <code>lung_tbl</code> anschauen. Zwar ist Lungenkrebs jetzt nichts was Tiere und Pflanzen als eine wichtige Erkrankung haben können, aber der Datensatz wird viel als Beispiel genutzt, so dass ich den Datensatz hier auch nochmal vorstellen möchte. Auch sind teilweise gewisse Schritte von Interesse, die eventuell auch in deiner Tier- oder Mäusestudie von Interesse sein könnten.</p>
<p>Beginnen wir einmal mit dem Nullmodell. Das heißt, wir schauen uns den Verlauf des gesamten Überlebens einmal an. Wir wollen wissen, wie das mediane Überleben in unseren Daten ausschaut ohne das wir uns irgendeien Variable anschauen.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">null_fit</span> <span class="op">&lt;-</span> <span class="fu">survfit</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">lung_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Im Folgenden einmal die Ausgabe des Fits.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">null_fit</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = lung_tbl)

       n events median 0.95LCL 0.95UCL
[1,] 228    165    310     285     363</code></pre>
</div>
</div>
<p>Wir sehen, dass wir ein medianes Überleben von <span class="math inline">\(310\)</span> Tagen haben. Es gibt insgesamt <span class="math inline">\(165\)</span> Ereignisse zu beobachten von insgesamt <span class="math inline">\(228\)</span> in die Studie eingeschlossenen Patienten. Wir können uns auch für bestimmte Zeitpunkte das Überleben wiedergeben lassen. Wir schauen uns hier einmal das Überleben nach einem Jahr bzw. <span class="math inline">\(365.25\)</span> Tagen an.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">null_fit</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span>times <span class="op">=</span> <span class="fl">365.25</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = lung_tbl)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
  365     65     121    0.409  0.0358        0.345        0.486</code></pre>
</div>
</div>
<p>Hier sehen wir, dass <span class="math inline">\(40.9\%\)</span> das eine Jahr überlebt haben. Achtung, immer auf die Kodierung achten. Nur wenn du <code>death = 1</code> kodiert hast, kannst du hier die Ausgaben der Funktionen in diesem Sinne interpretieren. Gerne kannst du hier auch das 3 Monatsüberleben bestimmen. Das kommt ganz darauf an, was deine Fragestellung ist. In der <a href="#fig-surv-4">Abbildung&nbsp;<span>49.4</span></a> siehst du nochmal die Kaplan Meyer Kurve für das Nullmodell.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggsurvplot</span><span class="op">(</span><span class="va">null_fit</span>, </span>
<span>           data <span class="op">=</span> <span class="va">lung_tbl</span>, </span>
<span>           risk.table <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>,</span>
<span>           ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>,</span>
<span>           palette <span class="op">=</span> <span class="va">cbbPalette</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surv-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-survival_files/figure-html/fig-surv-4-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.4— Kaplan Meier Kurven für das Nullmodell des Lungenkrebsdatensatzes.</figcaption></figure>
</div>
</div>
</div>
<p>Schauen wir uns auch einmal Kaplan Meier Kurven für die Variable <code>ph_ecog</code> an. Hier haben wir das Problem, dass die Kategorie <code>3</code> kaum mit Patienten belegt ist. Daher filtern wir die Kategorie <code>3</code> einmal aus unseren Daten raus.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lung_tbl</span> <span class="op">%&lt;&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">ph_ecog</span> <span class="op">!=</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir können dann das Modell der Überlebenszeit einmal fitten.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lung_fit</span> <span class="op">&lt;-</span> <span class="fu">survfit</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">ph_ecog</span>, data <span class="op">=</span> <span class="va">lung_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#fig-surv-5">Abbildung&nbsp;<span>49.5</span></a> sehen wir dann die Kaplan Meier Kurve für die Variable <code>ph_ecog</code>. Du kannst hier schön sehen, dass wenn wir mehrere Kategorien in der Variable haben auch mehrere Graphen erhalten. Wichtig hierbei ist nochmal, dass sich die Graphen nicht überschneiden oder aber in der Mitte kreuzen. Dann haben wir ein Problem und könnten die Daten nicht auswerten.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Konkret geht es hier um die <em>proportional hazards assumption</em>, die besagt, dass Überlebenszeitkurven für verschiedene Gruppen Hazardfunktionen haben müssen, die über die Zeit <span class="math inline">\(t\)</span> proportional sind. Daher dürfen sich die Kurven nicht schneiden.</p>
</div></div><div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggsurvplot</span><span class="op">(</span><span class="va">lung_fit</span>, </span>
<span>           data <span class="op">=</span> <span class="va">lung_tbl</span>, </span>
<span>           risk.table <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>           surv.median.line <span class="op">=</span> <span class="st">"hv"</span>,</span>
<span>           ggtheme <span class="op">=</span> <span class="fu">theme_light</span><span class="op">(</span><span class="op">)</span>,</span>
<span>           palette <span class="op">=</span> <span class="va">cbbPalette</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surv-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-survival_files/figure-html/fig-surv-5-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.5— Kaplan Meier Kurve für die Variable <code>ph_ecog</code> des Lungenkrebsdatensatzes.</figcaption></figure>
</div>
</div>
</div>
<p>Ganz zum Schluss dann noch die Frage, ob wir einen <em>signifikanten</em> Unterschied zwischen den beiden Kurven sehen. Dafür können wir dann die Funktion <code>survdiff()</code> nutzen. Die Funktion <code>survdiff()</code> gibt uns dann einen p-Wert wieder, ob sich die Kurven unterscheiden. Da es sich hier um einen globalen p-Wert handelt, erfahren wir nur, dass sich die Kurven unterscheiden, aber nicht welche. Dafür müssten wir dann die Kurven paarweise getrennt betrachten. Eigentlich ist nur der p-Wert von Interesse, die anderen Informationen haben eigentlich keinen biologischen Mehrwert.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">survdiff</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">ph_ecog</span>, data <span class="op">=</span> <span class="va">lung_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(time, status) ~ ph_ecog, data = lung_tbl)

            N Observed Expected (O-E)^2/E (O-E)^2/V
ph_ecog=0  63       37     53.9    5.3014    8.0181
ph_ecog=1 113       82     83.1    0.0144    0.0295
ph_ecog=2  50       44     26.0   12.4571   14.9754

 Chisq= 18  on 2 degrees of freedom, p= 1e-04 </code></pre>
</div>
</div>
</section></section><section id="cox-proportional-hazards-modell" class="level2 page-columns page-full" data-number="49.5"><h2 data-number="49.5" class="anchored" data-anchor-id="cox-proportional-hazards-modell">
<span class="header-section-number">49.5</span> Cox Proportional-Hazards Modell</h2>
<p>Wenn die Kaplan Meyer Kurven sowas wie die simple lineare Regression sind, dann ist das Cox Proportional-Hazards Modell die multiple Regression in den Ereigniszeitanalysen. Damit haben wir natürlich wieder einen statistischen Engel überfahren. Das Cox Proportional-Hazards Modell ist natürlich etwas anders und lässt sich so einfach auch nicht mit einer multiplen Regression vergleichen, aber die Anwendung ist ähnlich. Wo wir bei den Kaplan Meier Kurven nur ein <span class="math inline">\(X\)</span> in das Modell nehmen können, so können wir beim Cox Proportional-Hazards Modell beliebig viele <span class="math inline">\(X\)</span> mit ins Modell nehmen. Theoretisch müssen die Variablen in einem Cox Proportional-Hazards Modell auch nicht mehr kategorial sein. Da wir aber meist alles schon in Kategorien visualisiert haben, bleiben wir dann meist im Cox Proportional-Hazards Modell auch bei den Kategorien in den Variablen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Auch im Fall des Cox Proportional-Hazards Modells kann ich hier nur eine Übersicht geben. Es findet sich natürlich auch ein Tutorium zum <a href="http://www.sthda.com/english/wiki/cox-proportional-hazards-model">Cox Proportional-Hazards Model Tools</a>. Für das Überprüfen der Modellannahmen empfiehlt sich auch das Tutorium zu <a href="http://www.sthda.com/english/wiki/cox-model-assumptions">Cox Model Assumptions</a>.</p>
</div></div><p>In R nutzen wir die Funktion <code>coxph()</code> um ein Cox Proportional-Hazards Modell anzupassen. Die Anwendung ist eigentlich ziemlich einfach und lässt sich schnell durchführen.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1</span> <span class="op">&lt;-</span> <span class="fu">coxph</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">trt</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">weight</span>, data <span class="op">=</span> <span class="va">fruitfly_tbl</span><span class="op">)</span> </span>
<span><span class="va">fit_1</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter     | Coefficient |   SE |       95% CI |     z |      p
------------------------------------------------------------------
trt [control] |        0.24 | 0.09 | [0.12, 0.49] | -4.00 | &lt; .001
sex [female]  |        0.14 | 0.04 | [0.09, 0.24] | -7.32 | &lt; .001
weight        |        1.02 | 0.04 | [0.95, 1.10] |  0.60 | 0.549 </code></pre>
</div>
</div>
<p>Als Koeffizienten erhalten wir das <em>Hazard ratio</em> (abk. <em>HR</em>) wieder. Wie schon bei der logistischen Regression müssen wir auch hier die Koeffizienten exponieren, damit wir die Link-scale verlassen. Wir können das HR wie ein Risk ratio (abk. <em>RR</em>) interpretieren. Es handelt sich also mehr um eine Sterbe<em>wahrscheinlichkeit</em>. Ganz richtig ist die Interpretation nicht, da wir hier noch eine Zeitkomponente mit drin haben, aber für den umgangssprachlichen Gebrauch reicht die Interpretation.</p>
<p>Wenn wir ein <span class="math inline">\(HR &gt; 1\)</span> vorliegen haben, so steigert die Variable das Risiko zu sterben. Daher haben wir eine protektive Variable vorliegen, wenn dass <span class="math inline">\(HR &lt; 1\)</span> ist. Häufig wollen wir ein <span class="math inline">\(HR &lt; 0.8\)</span> oder <span class="math inline">\(HR &lt; 0.85\)</span> haben, wenn wir von einem relevanten Effekt sprechen wollen. Sonst reicht uns die Risikoreduktion nicht, um wirklich diese Variable zukünftig zu berücksichtigen. Aber wie immer hängt die Schwelle sehr von deiner Fragestellung ab.</p>
<p>Ich habe nochmal als Vergleich die Variable <code>weight</code> in das Modell genommen und damit den <code>fit_1</code> angepasst sowie die Variable <code>weight</code> in zwei Gruppen zu <code>weight_bin</code> aufgeteilt. Hier siehst du sehr schön, dass der Effekt der Dichotomisierung nicht zu unterschätzen ist. Im <code>fit_1</code> ist die kontinuierliche Variable <code>weight</code> eine Risikovariable, daher wir erwarten mehr tote Fruchtfliegen mit einem steigenden Gewicht. In dem <code>fit_2</code> haben wir die dichotomisierte Variable <code>weight_bin</code> vorliegen und schon haben wir eine protektive Variable. Wenn das Gewicht steigt, dann sterben weniger Fruchtfliegen. Zwar ist in beiden Fällen die Variable nicht signifikant, aber du solltest eine Dichotomisierung immer überprüfen.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">&lt;-</span> <span class="fu">coxph</span><span class="op">(</span><span class="fu">Surv</span><span class="op">(</span><span class="va">time</span>, <span class="va">status</span><span class="op">)</span> <span class="op">~</span> <span class="va">trt</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">weight_bin</span>, data <span class="op">=</span> <span class="va">fruitfly_tbl</span><span class="op">)</span> </span>
<span><span class="va">fit_2</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter        | Coefficient |   SE |       95% CI |     z |      p
---------------------------------------------------------------------
trt [control]    |        0.20 | 0.07 | [0.10, 0.39] | -4.65 | &lt; .001
sex [female]     |        0.14 | 0.04 | [0.08, 0.23] | -7.50 | &lt; .001
weight bin [low] |        0.62 | 0.20 | [0.33, 1.16] | -1.48 | 0.138 </code></pre>
</div>
</div>
<p>Nachdem wir ein Cox Proportional-Hazards Modell angepasst haben, wollen wir nochmal überprüfen, ob die Modellannahmen auch passen. Insbesondere müssen wir überprüfen, ob das Risiko über die ganze Laufzeit der Studie gleich bleibt oder sich ändert. Wir testen also die <em>proportional hazards assumption</em>. Dafür können wir in R die Funktion <code>cox.zph()</code> nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_ph</span> <span class="op">&lt;-</span> <span class="fu">cox.zph</span><span class="op">(</span><span class="va">fit_2</span><span class="op">)</span></span>
<span><span class="va">test_ph</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              chisq df     p
trt        0.000866  1 0.977
sex        3.400374  1 0.065
weight_bin 0.185700  1 0.667
GLOBAL     3.971563  3 0.265</code></pre>
</div>
</div>
<p>Wir lesen die Ausgabe von unten nach oben. Zuerst könne wir die <em>proportional hazards assumption</em> nicht ablehnen. Unser globaler p-Wert ist mit <span class="math inline">\(0.265\)</span> größer als das Signifikanzniveau <span class="math inline">\(\alpha\)</span> gleich <span class="math inline">\(5\%\)</span>. Betrachten wir die einzelnen Variablen, dann können wir auch hier die <em>proportional hazards assumption</em> nicht ablehnen. In der <a href="#fig-surv-6">Abbildung&nbsp;<span>49.6</span></a> ist der Test auf die <em>proportional hazards assumption</em> nochmal visualisiert. Wenn die durchgezogene Linie innerhalb der gestrichelten Linien, als Bereich von <span class="math inline">\(\pm 2\)</span> Standardfehlern, bleibt, dann ist soweit alles in Orndung. Bei einem Verstoß gegen die <em>proportional hazards assumption</em> kannst du folgende Maßnahmen ausprobieren:</p>
<ul>
<li>Hinzufügen von einer Kovariate*Zeit-Interaktion in das Cox Proportional-Hazards Modell</li>
<li>Stratifizierung der Daten nach der Kovariaten, die der <em>proportional hazards assumption</em> nicht folgt</li>
</ul>
<p>Auch hier musst du dann mal tiefer in die Materie einsteigen und einmal in den verlinkten Tutorien schauen, ob da was passendes für dein spezifisches Problem vorliegt.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggcoxzph</span><span class="op">(</span><span class="va">test_ph</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-surv-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-modeling-survival_files/figure-html/fig-surv-6-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Abbildung&nbsp;49.6— Visualisierung der Überprüfung der Proportional-Hazards-Annahme.</figcaption></figure>
</div>
</div>
</div>
</section><section id="logistische-regression" class="level2 page-columns page-full" data-number="49.6"><h2 data-number="49.6" class="anchored" data-anchor-id="logistische-regression">
<span class="header-section-number">49.6</span> Logistische Regression</h2>
<p>Was schon wieder die logistische Regression? Ja, schon wieder die logistische Regression. Wenn du dich nicht mit der Ereigniszeitanalyse rumschlagen willst oder denkst, dass die Ereigniszeitanalyse nicht passt, dann hast du immer noch die Möglichkeit eine logistische Regression zu rechnen. Dafür müssen wir dann nur ein wenig an den Daten rumbasteln. Wir müssen dann nämlich eine neue Variable erschaffen. Wir schauen einfach zu einem Zeitpunkt <span class="math inline">\(t\)</span>, ob die Beobachtung noch lebt. Dadurch bauen wir uns dann eine Spalte mit <span class="math inline">\(0/1\)</span> Werten. Dann kann es auch schon losgehen mit der logistischen Regression.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Tja, <a href="https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us"><em>All your base are belong to us</em></a> kann man da nur sagen…</p>
</div></div><p>Im ersten Schritt bauen wir uns eine neue Variable <code>died_3_m</code> für den Lingenkrebsdatensatz. Da in einer logistsichen Regression das <em>Schlechte</em> immer 1 ist, fragen wir, wer nach 90 Tagen verstorben ist. Also eine Lebenszeit unter 90 Tagen hatte. Diese Beobachtungen kriegen dann eine 1 und die anderen Beobachtungen eine 0.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lung_logreg_tbl</span> <span class="op">&lt;-</span> <span class="va">lung_tbl</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>died_3_m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">time</span> <span class="op">&lt;</span> <span class="fl">90</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nachdem wir uns recht schnell eine neue Variable gebaut haben, können wir dann einfach die logistische Regression rechnen. Bitte beachte, dass du die Effekte nur auf der log-Scale wiedergegeben kriegst, du musst dann die Ausgabe noch exponieren. Das machen wir hier in der Funktion <code>model_parameters()</code> gleich mit.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">died_3_m</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">ph_ecog</span>, data <span class="op">=</span> <span class="va">lung_logreg_tbl</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">model_parameters</span><span class="op">(</span>exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   | Odds Ratio |       SE |       95% CI |     z |     p
------------------------------------------------------------------
(Intercept) |   4.94e-03 | 9.59e-03 | [0.00, 0.18] | -2.74 | 0.006
age         |       1.06 |     0.03 | [1.01, 1.13] |  2.29 | 0.022
sex         |       0.45 |     0.23 | [0.16, 1.14] | -1.59 | 0.111
ph ecog     |       1.34 |     0.41 | [0.74, 2.47] |  0.96 | 0.335</code></pre>
</div>
</div>
<p>Was sind die Unterschiede? Eine logistische Regression liefert Odds Ratios, also ein Chancenverhältnis. Aus einer Ereigniszeitanalyse erhalten wir Hazard Ratios, was eher ein Risk Ratio ist und somit eine Wahrscheinlichkeit. Deshalb lassen sich die Ergebnisse an der Stelle nur bedingt vergleichen. Im Falle der logistischen Regression fallen auch Zensierungen weg. Wir betrachten eben nur <em>einen einzigen</em> Zeitpunkt. In der Ereigniszeitanalyse betrachten wir hingegen den gesamten Verlauf. Wir immer musst du überlegen, was ist deine Fragestellung und was möchtest du berichten. Wenn es dir wirklich nur um den Zeitpunkt <span class="math inline">\(t\)</span> geht und dir die Progression dahin oder danach egal ist, dann mag die logistische Regression auch eine Möglichkeit der Auswertung sein.</p>
</section><section id="referenzen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-david2012survival" class="csl-entry" role="listitem">
David, G Kleinbaum, und Klein Mitchel. 2012. <em>Survival analysis: a Self-Learning text</em>. Spinger.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-modeling-robust-quantile.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-modeling-noninferiority.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>