<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 18&nbsp; Die Testentscheidung</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-tests-theorie.html" rel="next">
<link href="./stat-tests-preface.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen und Hunden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen, Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes-site.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren in Habitaten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Gummibärchen</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Von Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Gausian lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimentel-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimentel-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-lectures-semester.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Logbuch</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#sec-hypothesen" id="toc-sec-hypothesen" class="nav-link active" data-scroll-target="#sec-hypothesen"> <span class="header-section-number">18.1</span> Die Hypothesen</a></li>
  <li>
<a href="#die-testentscheidung" id="toc-die-testentscheidung" class="nav-link" data-scroll-target="#die-testentscheidung"> <span class="header-section-number">18.2</span> Die Testentscheidung…</a>
  <ul class="collapse">
<li><a href="#sec-teststatistik" id="toc-sec-teststatistik" class="nav-link" data-scroll-target="#sec-teststatistik"> <span class="header-section-number">18.2.1</span> … anhand der Teststatistik</a></li>
  <li><a href="#sec-pwert" id="toc-sec-pwert" class="nav-link" data-scroll-target="#sec-pwert"> <span class="header-section-number">18.2.2</span> … anhand dem p-Wert</a></li>
  <li><a href="#sec-ki" id="toc-sec-ki" class="nav-link" data-scroll-target="#sec-ki"> <span class="header-section-number">18.2.3</span> … anhand des 95% Konfidenzintervall</a></li>
  </ul>
</li>
  <li><a href="#sec-delta-n-s" id="toc-sec-delta-n-s" class="nav-link" data-scroll-target="#sec-delta-n-s"> <span class="header-section-number">18.3</span> Auswirkung des Effektes, der Streuung und der Fallzahl</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-stat-entscheidung" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><p><em>Version vom October 12, 2022 um 18:19:14</em></p>
<div class="cell">

</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Forschung basiert auf dem Falsifikationsprinzip. Wir können <strong>nur ablehnen</strong> und behalten das weniger schlechte Modell bei.</span></div></div>
<p>Du erfährst im diesem Kapitel mehr zur Testentscheidung und welche Konzepte wir dort nutzen:</p>
<ul>
<li>Wir verstehen die statistischen Testentscheidung nutzen wir das Konzept der Teststatistik <span class="math inline">\(T\)</span> (siehe <a href="#sec-teststatistik"><span>Kapitel&nbsp;18.2.1</span></a>)</li>
<li>Wir können die statistischen Testentscheidung anwenden, da wir das Konzept des p-Wertes <span class="math inline">\(Pr(T|H_0)\)</span> (siehe <a href="#sec-pwert"><span>Kapitel&nbsp;18.2.2</span></a>) und das Konzept der 95% Konfidenzintervalle verstanden haben (siehe <a href="#sec-ki"><span>Kapitel&nbsp;18.2.3</span></a>)</li>
</ul>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Ein Wort zur Klausur
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Abhängig von der Lernstufe - daher welche <a href="organisation.html#sec-vorlesungen-hs">Veranstaltung</a> du gerade bei mir besuchst - kommt nicht <em>alles</em> aus diesem Kapitel dran in der Klausur. Bitte gleiche die Inhalte, die ich in der aktuellen Vorlesung unterrichte, mit dem Material hier ab. Als Faustregel gilt, je höher die Lernstufe desto mehr musst du von dem statistischen Testen Wissen und Verstehen. Beachte auch die Probeklausur in deiner Veranstaltung und die <a href="https://github.com/jkruppa/teaching/tree/main/Klausur">gesammelten Klausurfragen auf GitHub</a>.</p>
</div>
</div>
</div>
<section id="sec-hypothesen" class="level2 page-columns page-full" data-number="18.1"><h2 data-number="18.1" class="anchored" data-anchor-id="sec-hypothesen">
<span class="header-section-number">18.1</span> Die Hypothesen</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p>Im <a href="app-example-analysis.html">Anhang&nbsp;<span>A</span></a> findest du verschiedene Beispiele zu Auswertungen von Datenbeispielen.</p>
</div></div><p>Wir können auf allen Daten einen statistischen Test rechnen und erhalten statistische Maßzahlen wie eine Teststatistik oder einen p-Wert. Nur leider können wir mit diesen statistischen Maßzahlen nicht viel anfangen ohne die Hypothesen zu kennen. Jeder statistische Test testet eine Nullhypothese. Ob diese Hypothese dem Anwender nun bekannt ist oder nicht, ein statistischer Test testet eine Nullhypothese. Daher müssen wir uns immer klar sein, was die entsprechende Nullhypothese zu unserer Fragestellung ist. Wenn du hier stockst, ist das ganz normal. Eine Fragestellung mit einer statistischen Hypothese zu verbinden ist nicht immer so einfach gemacht.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Die Nullhypothese <span class="math inline">\(H_0\)</span> und die Alternativehypothese <span class="math inline">\(H_A\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die Nullhypothese <span class="math inline">\(H_0\)</span> nennen wir auch die Null oder Gleichheitshypothese. Die Nullhypothese sagt aus, dass zwei Gruppen gleich sind oder aber kein Effekt zu beobachten ist.</p>
<p><span class="math display">\[
H_0: \bar{y}_{1} = \bar{y}_{2}
\]</span></p>
<p>Die Alternativehypothese <span class="math inline">\(H_A\)</span> oder <span class="math inline">\(H_1\)</span> auch Alternative genannt nennen wir auch Unterschiedshypothese. Die Alternativehypothese besagt, dass ein Unterschied vorliegt oder aber ein Effekt vorhanden ist.</p>
<p><span class="math display">\[
H_A: \bar{y}_{1} \neq \bar{y}_{2}
\]</span></p>
</div>
</div>
<p>Als Veranschaulichung nehmen wir das Beispiel aus der unterschiedlichen Sprungweiten in [cm] für Hunde- und Katzenflöhe. Wir formulieren als erstes die Fragestellung. Eine Fragestellung endet mit einem Fragezeichen.</p>
<p><em>Liegt ein Unterschied zwischen den Sprungweiten von Hunde- und Katzenflöhen vor?</em></p>
<p>Wir können die Frage auch anders formulieren.</p>
<p><em>Springen Hunde- und Katzenflöhe unterschiedlich weit?</em></p>
<p>Wichtig ist, dass wir eine primäre Fragestellung formulieren. Wir können auch mehrere Fragen an einen Datensatz haben. Das ist auch vollkommen normal. Nur hat <em>jede</em> Fragestellung ein eigenes Hypothesenpaar. Wir bleiben aber bei dem simplen Beispiel.</p>
<p>Wie sieht nun die statistische Hypothese in diesem Beispiel aus? Wir wollen uns die Sprungweite in [cm] anschauen. In diesem Fall wollen wir die <em>mittlere</em> Sprungweite der Hundeflöhe <span class="math inline">\(\bar{y}_{dog}\)</span> mit der <em>mittleren</em> Sprungweite der Katzenflöhe <span class="math inline">\(\bar{y}_{cat}\)</span> vergleichen. Es ergibt sich folgendes Hypothesenpaar.</p>
<p><span class="math display">\[
\begin{aligned}
H_0: \bar{y}_{dog} &amp;= \bar{y}_{cat} \\  
H_A: \bar{y}_{dog} &amp;\neq \bar{y}_{cat} \\   
\end{aligned}
\]</span></p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Das <strong>Falisifkationsprinzip</strong> - wir können nur Ablehnen - kommt hier zusammen mit der <strong>frequentistischen Statistik</strong> in der wir nur eine Wahrscheinlichkeitsaussage über das Auftreten der Daten <span class="math inline">\(D\)</span> - unter der Annahme <span class="math inline">\(H_0\)</span> gilt - treffen können.</span></div></div>
<p>Es ist wichtig sich in Erinnerung zu rufen, dass wir nur und ausschließlich Aussagen über die Nullhypothese treffen werden. Das <em>frequentistische</em> Hypothesentesten kann nichts anders. Wir kriegen keine Aussage über die Alternativhypothese sondern nur eine Abschätzung der Wahrscheinlichkeit des Auftretens der Daten im durchgeführten Experiment, wenn die Nullhypothese wahr wäre.</p>
</section><section id="die-testentscheidung" class="level2 page-columns page-full" data-number="18.2"><h2 data-number="18.2" class="anchored" data-anchor-id="die-testentscheidung">
<span class="header-section-number">18.2</span> Die Testentscheidung…</h2>
<p>In den folgenden Kapiteln werden wir verschiedene statistische Tests kennenlernen. Alle statistischen Tests haben gemein, dass ein Test eine Teststatistik <span class="math inline">\(T_{calc}\)</span> berechnet. Darüber hinaus liefert jeder Test auch einen p-Wert (eng. <em>p-value</em>). Manche statistischen Test geben auch ein 95% Konfidenzintervall wieder. Eine Testentscheidung gegen die Nullhypothese <span class="math inline">\(H_0\)</span> kann mit jedem der drei statistischen Maßzahlen durchgeführt werden. Die Regel für die Entscheidung, ob die Nullhypothese <span class="math inline">\(H_0\)</span> abgelehnt werden kann, ist nur jeweils anders. In <a href="#tbl-comp-t-p-ki">Tabelle&nbsp;<span>18.1</span></a> sind die Entscheidungsregeln einmal zusammengefasst.</p>
<div class="column-page">
<div id="tbl-comp-t-p-ki" class="anchored">
<table class="table">
<caption>Tabelle 18.1— Zusammenfassung der statistischen Testentscheidung unter der Nutzung der Teststatistik, dem p-Wert und dem 95% Konfidenzintervall. Die Entscheidung nach der Teststatistik ist veraltet und dient nur dem konzeptionellen Verständnisses. In der Forschung angewandt wird der p-Wert und das 95% Konfidenzintervall. Im Fall des 95% Konfidenzintervalls müssen wir noch unterschieden, ob wir einen Mittelwertsunterschied <span class="math inline">\(\Delta_{A-B}\)</span> oder aber einen Anteilsunterschied <span class="math inline">\(\Delta_{A/B}\)</span> betrachten.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 24%">
<col style="width: 26%">
<col style="width: 37%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><strong>Teststatistik</strong></th>
<th style="text-align: center;"><strong>p-Wert</strong></th>
<th style="text-align: center;"><strong>95% Konfidenzintervall</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\boldsymbol{T_{calc}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\boldsymbol{Pr(\geq T_{calc}|H_0)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\boldsymbol{KI_{1-\alpha}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">H<span class="math inline">\(_0\)</span> ablehnen</td>
<td style="text-align: center;"><span class="math inline">\(T_{calc} \geq T_{\alpha = 5\%}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Pr(\geq T_{calc}| H_0) \leq \alpha\)</span></td>
<td style="text-align: center;">
<span class="math inline">\(\Delta_{A-B}\)</span>: enthält <u><em>nicht</em></u> <strong>0</strong>
</td>
</tr>
<tr class="odd">
<td style="text-align: center;">H<span class="math inline">\(_0\)</span> ablehnen</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">
<span class="math inline">\(\Delta_{A/B}\)</span>: enthält <u><em>nicht</em></u> <strong>1</strong>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Wir wollen in den folgenden Abschnitten die jeweiligen Entscheidungsregeln eines statistisches Tests einmal durchgehen.</p>
<ul>
<li>Die Testentscheidung gegen die Nullhypothese anhand der Teststatistik in <a href="#sec-teststatistik"><span>Kapitel&nbsp;18.2.1</span></a>
</li>
<li>Die Testentscheidung gegen die Nullhypothese anhand dem p-Wert in <a href="#sec-pwert"><span>Kapitel&nbsp;18.2.2</span></a>
</li>
<li>Die Testentscheidung gegen die Nullhypothese anhand des 95% Konfidenzintervall in <a href="#sec-ki"><span>Kapitel&nbsp;18.2.3</span></a>
</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Streng genommen gilt die Regel <span class="math inline">\(T_{calc} \geq T_{\alpha = 5\%}\)</span> nur für eine Auswahl an statistischen Tests siehe dazu auch <a href="#sec-teststatistik"><span>Kapitel&nbsp;18.2.1</span></a>. Bei manchen statistischen Tests ist die Entscheidung gedreht. Hier lassen wir das aber mal so stehen…</p>
</div></div><section id="sec-teststatistik" class="level3 page-columns page-full" data-number="18.2.1"><h3 data-number="18.2.1" class="anchored" data-anchor-id="sec-teststatistik">
<span class="header-section-number">18.2.1</span> … anhand der Teststatistik</h3>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Prinzip des statistischen Testens I - Die Teststatistik
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/28QjGfR_SPQ">Prinzip des statistischen Testens I - Die Teststatistik</a> als Video. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>
<p>Wir wollen uns dem frequentistischen Hypothesentesten über die Idee der Teststatistik annähern. Im folgenden sehen wir die Formel für den t-Test. Den t-Test werden wir im <a href="stat-tests-ttest.html"><span>Kapitel&nbsp;21</span></a> uns nochmal detaillierter anschauen. Hier nutzen wir die vereinfachte Formel um das Konzept zu verstehen.</p>
<p><span class="math display">\[
T_{calc}=\cfrac{\bar{y}_1-\bar{y}_2}{s_{p} \cdot \sqrt{2/n_g}}
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(\bar{y}_1\)</span> dem Mittelwert für die erste Gruppe.</li>
<li>
<span class="math inline">\(\bar{y}_2\)</span> dem Mittelwert für die zweite Gruppe.</li>
<li>
<span class="math inline">\(s_{p}\)</span> der gepoolten Standardabweichung mit <span class="math inline">\(s_p = \tfrac{s_A + s_B}{2}\)</span>.</li>
<li>
<span class="math inline">\(n_g\)</span> der Gruppengröße der gruppen. Wir nehmen an beide Gruppen sind gleich groß.</li>
</ul>
<p>Wir benötigen also zwei Mittelwerte <span class="math inline">\(\bar{y}_1\)</span> und <span class="math inline">\(\bar{y}_2\)</span> und deren gepoolte Standardabweichung <span class="math inline">\(s_p\)</span> sowie die Anzahl der Beobachtungen je Gruppe <span class="math inline">\(n_g\)</span>. Wenden wir die Formel des t-Tests einmal auf den folgenden Beispieldatensatz an. In <a href="#tbl-dog-cat-small">Tabelle&nbsp;<span>18.2</span></a> ist eine Datenbeispiel gegeben.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-dog-cat-small" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 18.2— Beispiel für die Berechnung von einem Mittelwertseffekt an der Sprunglänge [cm] von Hunde und Katzenflöhen.</caption>
<thead><tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">jump_length</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">8.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">9.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">8.9</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">9.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.4</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir berechnen nun die Mittelwerte und die Standardabweichungen aus der obigen Datentabelle. Die Werte setzen wir dann in die Formel ein.</p>
<p><span class="math display">\[
T_{calc}=\cfrac{9.2 - 7.8}{\cfrac{(0.6 + 0.5)}{2} \cdot \sqrt{2/4}} = 3.6
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(\bar{y}_{cat} = 9.2\)</span> dem Mittelwert für die Gruppe <em>cat</em>.</li>
<li>
<span class="math inline">\(\bar{y}_{dog} = 7.8\)</span> dem Mittelwert für die Gruppe <em>dog</em>.</li>
<li>
<span class="math inline">\(s_p = 0.55\)</span> der gepoolten Standardabweichung mit <span class="math inline">\(s_p = \tfrac{0.6 + 0.5}{2}\)</span>.</li>
<li>
<span class="math inline">\(n_g = 4\)</span> der Gruppengröße der Gruppe A und B. Wir nehmen an beide Gruppen sind gleich groß.</li>
</ul>
<p>Wir haben nun die Teststatistik <span class="math inline">\(T_{calc} = 3.6\)</span> berechnet. In der ganzen Rechnererei verliert man manchmal den Überblick. Erinnern wir uns, was wir eigentlich wollten. Die Frage war, ob sich die mittleren Sprungweiten der Hunde- und Katzenflöhe unterschieden. Wenn die <span class="math inline">\(H_0\)</span> wahr wäre, dann wäre der Unterschied <span class="math inline">\(\Delta\)</span> der beiden Mittelwerte der Hunde- und Katzenflöhe gleich null. Oder nochmal in der Analogie der t-Test Formel, dann wäre im Zähler <span class="math inline">\(\Delta = \bar{y}_{cat} - \bar{y}_{dog} = 0\)</span>. Wenn die Mittelwerte der Sprungweite [cm] der Hunde- und Katzenflöhe gleich wäre, dann wäre die berechnete Teststatistik <span class="math inline">\(T_{calc} = 0\)</span>, da im Zähler Null stehen würde. Die Differenz von zwei gleichen Zahlen ist Null.</p>
<p>Je größer die berechnete Teststatistik <span class="math inline">\(T_{calc}\)</span> wird, desto unwahrscheinlicher ist es, dass die beiden Mittelwerte per Zufall gleich sind. Wie groß muss nun die berechnete Teststatistik <span class="math inline">\(T_{calc}\)</span> werden damit wir die Nullhypothese ablehnen können?</p>
<div class="column-page">
<div id="fig-teststatistik-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/t-verteilung_01.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.1— Die t-Verteilung aller möglichen <span class="math inline">\(T_{calc}\)</span> wenn die Nullhypothese wahr ist. Der Mittelwert der t-Verteilun ist <span class="math inline">\(T=0\)</span>. Wenn wir keinen Effekt erwarten würden dann wären die beiden Mittelwerte <span class="math inline">\(\bar{y}_1\)</span> und <span class="math inline">\(\bar{y}_2\)</span> gleich groß. Die Differenz wäre 0. Je größer der <span class="math inline">\(T_{calc}\)</span> wird desto weniger können wir davon ausgehen, dass die beiden Mittelwerte gleich sind. Liegt der <span class="math inline">\(T_{calc}\)</span> über dem kritischen Wert von <span class="math inline">\(T_{\alpha = 5\%}\)</span> dann wir die Nullhypothese abgelehnt.</figcaption><p></p>
</figure>
</div>
</div>
<p>In <a href="#fig-teststatistik-01">Abbildung&nbsp;<span>18.1</span></a> ist die Verteilung aller möglichen <span class="math inline">\(T_{calc}\)</span> Werte unter der Annahme, dass die Nullhypothese wahr ist, dargestellt. Wir sehen, dass die t-Verteilung am höchsten bei <span class="math inline">\(T_{calc} = 0\)</span> ist und niedrigeren Werte mit steigenden t-Werten annimmt. Wenn <span class="math inline">\(T = 0\)</span> dann sind auch die Mittelwerte gleich. Je größer unsere berechnete Teststatistik <span class="math inline">\(T_{calc}\)</span> wird, desto unwahrscheinlicher ist es, dass die Nullhypothese gilt. Die t-Verteilug ist so gebaut, dass die Fläche <span class="math inline">\(A\)</span> unter der Kurve gleich <span class="math inline">\(A=1\)</span> ist. Wir können nun den kritschen Wert <span class="math inline">\(T_{\alpha = 5\%}\)</span> berechnen an dem rechts von dem Wert eine Fläche von 0.05 oder 5% liegt. Sommit liegt dann links von dem kritischen Wert die Fläche von 0.95 oder 95%. Den kritischen Wert <span class="math inline">\(T_{\alpha = 5\%}\)</span> können wir statistischen Tabellen entnehmen. Oder wir berechnen den kritischen Wert direkt in R mit <span class="math inline">\(T_{\alpha = 5\%} = 2.78\)</span>.</p>
<p>Kommen wir zurück zu unserem Beispiel. Wir haben in unserem Datenbeispiel für den Vergleich von der Sprungweite in [cm] von Hunde- und Katzenflöhen eine Teststatistik von <span class="math inline">\(T_{calc} = 3.6\)</span> berechnet. Der kritische Wert um die Nullhypothese abzulehnen liegt bei <span class="math inline">\(T_{\alpha = 5\%} = 2.78\)</span>. Wenn <span class="math inline">\(T_{calc} \geq T_{\alpha = 5\%}\)</span> wird die Nullhypothese (H<span class="math inline">\(_0\)</span>) abgelehnt. In unserem Fall ist <span class="math inline">\(3.6 \geq 2.78\)</span>. Wir können die Nullhypothese ablehnen. Es gibt einen Unterschied zwischen der mittleren Sprungweite von Hunde- und Katzenflöhen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p><em>Es gibt einen Unterschied zwischen der mittleren Sprungweite von Hunde- und Katzenflöhen.</em> Die Aussage ist <strong>statistisch</strong> falsch. Wir können im frequentistischen Hypothesentesten keine Aussage über die <span class="math inline">\(H_A\)</span> treffen. Im Sinne der Anwendbarkeit soll es hier so stehen bleiben.</p>
</div></div><p>Nun ist es leider so, dass jeder statistische Test seine eigene Teststatistik <span class="math inline">\(T\)</span> hat. Daher ist es etwas mühselig sich immer neue und andere kritische Werte für jeden Test zu merken. Es hat sich daher eingebürgert, sich nicht die Teststatistik für die Testentscheidung gegen die Nullhypothese zu nutzen sondern den p-Wert. Den p-Wert wollen wir uns in dem folgenden Abschnitt anschauen.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Entscheidung mit der berechneten Teststatistik
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bei der Entscheidung mit der Teststatistik müssen wir zwei Fälle unterschieden.</p>
<ol type="1">
<li><p>Bei einem t-Test und einem <span class="math inline">\(\mathcal{X}^2\)</span>-Test gilt, wenn <span class="math inline">\(T_{calc} \geq T_{\alpha = 5\%}\)</span> wird die Nullhypothese (H<span class="math inline">\(_0\)</span>) abgelehnt.</p></li>
<li><p>Bei einem Wilcoxon-Mann-Whitney-Test gilt, wenn <span class="math inline">\(T_{calc} &lt; T_{\alpha = 5\%}\)</span> wird die Nullhypothese (H<span class="math inline">\(_0\)</span>) abgelehnt.</p></li>
</ol>
<p><strong>Achtung –</strong> Wir nutzen die Entscheidung mit der Teststatistik <em>nur und ausschließlich</em> in der Klausur. In der praktischen Anwendung hat die Betrachtung der berechneten Teststatistik <em>keine</em> Verwendung mehr.</p>
</div>
</div>
</section><section id="sec-pwert" class="level3 page-columns page-full" data-number="18.2.2"><h3 data-number="18.2.2" class="anchored" data-anchor-id="sec-pwert">
<span class="header-section-number">18.2.2</span> … anhand dem p-Wert</h3>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Prinzip des statistischen Testens II - Der p-Wert
</div>
</div>
<div class="callout-body-container callout-body">
<p>Du findest auf YouTube <a href="https://youtu.be/Zr8gdWZrSPc">Prinzip des statistischen Testens II - Der p-Wert</a> als Video Reihe. Ich werde zwar alles nochmal hier als Text aufschreiben, aber manchmal ist das Sehen und Hören dann einfacher.</p>
</div>
</div>
<p>In dem vorherigen Abschnitt haben wir gelernt, wie wir zu einer Entscheidung gegen die Nullhypothese anhand der Teststatistik kommen. Wir haben einen kritischen Wert <span class="math inline">\(T_{\alpha = 5\%}\)</span> definiert bei dem rechts von dem Wert 5% der Werte liegen. Anstatt nun den berechneten Wert <span class="math inline">\(T_{calc}\)</span> mit dem kritischen Wert <span class="math inline">\(T_{\alpha = 5\%}\)</span> zu vergleichen, vergleichen wir jetzt die Flächen rechts von den jeweiligen Werten.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Wir schreiben <span class="math inline">\(\boldsymbol{Pr}\)</span> und meinen damit eine Wahrscheinlichkeit (eng. <em>probability</em>). Häufig wird auch nur das <span class="math inline">\(P\)</span> verwendet, aber dann kommen wir wieder mit anderen Konzepten in die Quere.</span></div></div>
<p>In <a href="#fig-teststatistik-01">Abbildung&nbsp;<span>18.1</span></a> sind die Flächen auch eingetragen. Da die gesamte Fläche unter der t-Verteilung mit <span class="math inline">\(A = 1\)</span> ist, können wir die Flächen auch als Wahrscheinlichkeiten lesen. Die Fläche rechts von der berechneten Teststatistik <span class="math inline">\(T_{calc}\)</span> wird <span class="math inline">\(Pr(T_{calc}|H_0)\)</span> oder <span class="math inline">\(p\)</span>-Wert genannt. Die <em>gesamte</em> Fläche rechts von dem kritischen Wert <span class="math inline">\(T_{\alpha = 5\%}\)</span> wird <span class="math inline">\(\alpha\)</span> genannt und liegt bei 5%. Wir können also die Teststatistiken oder den p-Wert mit dem <span class="math inline">\(\alpha\)</span>-Niveau von 5% vergleichen.</p>
<div id="tbl-t-und-A" class="anchored">
<table class="table">
<caption>Tabelle 18.3— Zusammenhang zwischen der Teststatistik <span class="math inline">\(T\)</span> und der Fläche <span class="math inline">\(A\)</span> rechts von der Teststatistik. Die Fläche rechts von der berechneten Teststatistik <span class="math inline">\(T_{calc}\)</span> wird <span class="math inline">\(Pr(T|H_0)\)</span> oder <span class="math inline">\(p\)</span>-Wert genannt. Die Fläche rechts von dem kritischen Wert <span class="math inline">\(T_{\alpha = 5\%}\)</span> wird <span class="math inline">\(\alpha\)</span> genannt und liegt bei 5%.</caption>
<thead><tr class="header">
<th style="text-align: center;">Teststatistik <span class="math inline">\(T\)</span>
</th>
<th style="text-align: center;">Fläche <span class="math inline">\(A\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_{calc}\)</span></td>
<td style="text-align: center;">
<span class="math inline">\(Pr(T_{calc}|H_0)\)</span> oder <span class="math inline">\(p\)</span>-Wert</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(T_{\alpha = 5\%}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\alpha\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Der p-Wert oder <span class="math inline">\(Pr(T|H_0)\)</span> ist eine Wahrscheinlichkeit. Eine Wahrscheinlichkeit kann die Zahlen von 0 bis 1 annehmen. Dabei sind die Grenzen einfach zu definieren. Eine Wahrscheinlichkeit von <span class="math inline">\(Pr(A) = 0\)</span> bedeutet, dass das Ereignis A nicht auftritt; eine Wahrscheinlichkeit von <span class="math inline">\(Pr(A) = 1\)</span> bedeutet, dass das Ereignis A eintritt. Der Zahlenraum dazwischen stellt jeden von uns schon vor große Herausforderungen. Der Unterschied zwischen 40% und 60% für den Eintritt des Ereignisses A sind nicht so klar zu definieren, wie du auf den ersten Blick meinen magst.</p>
<p>Ein frequentistischer Hypothesentest beantwortet die Frage, mit welcher Wahrscheinlichkeit <span class="math inline">\(Pr\)</span> die Teststatistik <span class="math inline">\(T\)</span> aus dem Experiment mit den Daten <span class="math inline">\(D\)</span> zu beobachten wären, wenn es keinen Effekt gäbe (<span class="math inline">\(H_0\)</span> ist wahr).</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Likelihood</strong> heißt Plausibilität und <strong>Probability</strong> heißt Wahrscheinlichkeit.</span></div></div>
<p>Im Englischen gibt es die Begrifflichkeiten einer <em>Likelihood</em> und einer <em>Probability</em> in der Statistik. Meist wird beides ins Deutsche ungenau mit Wahrscheinlichkeit übersetzt oder wir nutzen einfach <em>Likelihood</em>. Was aber auch nicht so recht weiterhilft. Es handelt sich hierbei aber um zwei unterschiedliche Konzepte. Deshalb Übersetzen wir <em>Likelihood</em> mit Plausibilität und <em>Probability</em> mit Wahrscheinlichkeit.</p>
<p>Im Folgenden berechnen wir den <span class="math inline">\(p\)</span>-Wert in R mit der Funktion <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>. Mehr dazu im <a href="stat-tests-ttest.html"><span>Kapitel&nbsp;21</span></a>, wo wir den t-Test und deren Anwendung im Detail besprechen.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  statistic p.value
      &lt;dbl&gt;   &lt;dbl&gt;
1      2.81  0.0309</code></pre>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Wir sagen, dass wir ein <strong>signifikantes</strong> Ergebnis haben, wenn der <span class="math inline">\(p\)</span>-Wert kleiner ist als die Signifikanzschwelle <span class="math inline">\(\alpha\)</span> von 5%.</span></div></div>
<p>Wir erhalten einen <span class="math inline">\(p\)</span>-Wert von 0.031 und vergleichen diesen Wert zu einem <span class="math inline">\(\alpha\)</span> von 5%. Ist der <span class="math inline">\(p\)</span>-Wert kleiner als der <span class="math inline">\(\alpha\)</span>-Wert von 5%, dann können wir die Nullhypothese ablehnen. Da 0.031 kleiner ist als 0.05 können wir die Nullhypothese und damit die Gleichheit der mittleren Sprungweiten in [cm] ablehnen. Wir sagen, dass wir ein signifikantes Ergebnis vorliegen haben.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Entscheidung mit dem p-Wert
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn der p-Wert <span class="math inline">\(\leq \alpha\)</span> dann wird die Nullhypothese (H<span class="math inline">\(_0\)</span>) abgelehnt. Das Signifikanzniveau <span class="math inline">\(\alpha\)</span> wird als Kulturkonstante auf 5% oder 0.05 gesetzt. Die Nullhypothese (H<span class="math inline">\(_0\)</span>) kann auch Gleichheitshypothese gesehen werden. Wenn die H<span class="math inline">\(_0\)</span> gilt, liegt kein Unterschied zwischen z.B. den Behandlungen vor.</p>
</div>
</div>
</section><section id="sec-ki" class="level3 page-columns page-full" data-number="18.2.3"><h3 data-number="18.2.3" class="anchored" data-anchor-id="sec-ki">
<span class="header-section-number">18.2.3</span> … anhand des 95% Konfidenzintervall</h3>
<p>Ein statistischer Test der eine Teststatistik <span class="math inline">\(T\)</span> berechnet liefert auch immer einen <span class="math inline">\(p\)</span>-Wert. Nicht alle statistischen Tests ermöglichen es ein 95% Konfidenzintervall zu berechnen. <a href="#fig-ki-00">Abbildung&nbsp;<span>18.2</span></a> zeigt ein 95% konfidenzintervall.</p>
<div id="fig-ki-00" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/ci-00.png" class="img-fluid figure-img" style="width:70.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.2— Ein 95% Konfidenzintervall. Der Punkt in der Mitte entspricht dem Unterschied oder Effekt <span class="math inline">\(\Delta\)</span>.</figcaption><p></p>
</figure>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Mit <strong>p-Werten</strong> haben wir Wahrscheinlichkeitsaussagen und damit über die <strong>Signifikanz</strong>. Damit haben wir noch keine Aussage über die <strong>Relevanz</strong> des beobachtenten Effekts.</span></div></div>
<p>Mit der Teststatistik <span class="math inline">\(T\)</span> und dem damit verbundenen <span class="math inline">\(p\)</span>-Wert haben wir uns <em>Wahrscheinlichkeiten</em> angeschaut und erhalten eine <em>Wahrscheinlichkeitsaussage</em>. Eine Wahrscheinlichkeitsaussage sagt aber nichts über den Effekt <span class="math inline">\(\Delta\)</span> aus. Also wie groß ist der mittlere Sprung<em>unterschied</em> zwischen Hunde- und Katzenflöhen.</p>
<p>Die Idee von 95% Kondifenzintervallen ist es jetzt den Effekt mit der Wahrscheinlichkeitsaussage zusammenzubringen und beides in einer <em>Visualisierung</em> zu kombinieren. Im Folgenden sehen wir die vereinfachte Formel für das 95% Konfidenzintervall eines t-Tests.</p>
<p><span class="math display">\[
\left[
(\bar{y}_1-\bar{y}_2) -
T_{\alpha = 5\%} \cdot \frac {s_p}{\sqrt{n}}; \;
(\bar{y}_1-\bar{y}_2) +
T_{\alpha = 5\%} \cdot \frac {s_p}{\sqrt{n}};
\right]
\]</span></p>
<p>Die Formel ist ein wenig komplex, aber im Prinzip einfach. Der linke und der rechte Teil neben dem Semikolon sind fast gleich, bis auf das Plus- und Minuszeichen. <a href="#fig-ki-01">Abbildung&nbsp;<span>18.3</span></a> visualisert die Formel einmal. Wir sehen Folgendes in der Formel und dann in der entsprechenden Abbildung:</p>
<ul>
<li>
<span class="math inline">\((\bar{y}_{1}-\bar{y}_{2})\)</span> ist der Effekt <span class="math inline">\(\Delta\)</span>. In diesem Fall der Mittelwertsunterschied. Wir finden den Effekt als Punkt in der Mitte des Intervals.</li>
<li>
<span class="math inline">\(T_{\alpha = 5\%} \cdot \frac {s}{\sqrt{n}}\)</span> ist der Wert, der die Arme des Intervals bildet. Wir vereinfachen die Formel mit <span class="math inline">\(s_p\)</span> für die gepoolte Standardabweichung und <span class="math inline">\(n_g\)</span> für die Fallzahl der beiden Gruppen. Wir nehmen an das beide Gruppen die gleiche Fallzahl <span class="math inline">\(n_1 = n_2\)</span> haben.</li>
</ul>
<div id="fig-ki-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/ci-01.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.3— Zusammenhang zwischen der vereinfachten Formel für das 95% Konfidenzintervall und der Visualisierung des 95% Konfidenzintervalls. Der Effektschätzer wird als Punkt in der Mitte des Intervalls dargestellt. Der Effektschäter <span class="math inline">\(\Delta\)</span> kann entweder ein Mittelwertsunterschied sein oder ein Anteilsunterschied. Bei einem Mittelwertsunterschied kann die Nullhypothese abgelehnt werden, wenn die 0 nicht im Konfidenzintervall ist; bei einem Anteilsunterschied wenn die 1 nicht im Konfidenzintervall ist. Die Arme werden länger oder kürzer je nachdem wie sich die statistischen Maßzahlen <span class="math inline">\(s\)</span> und <span class="math inline">\(n\)</span> verändern.</figcaption><p></p>
</figure>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Die Funktion <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> in R erlaubt es dir die Level eines Faktors zu sortieren und so festzulegen ob Level <code>cat</code> minus Level <code>dog</code> oder umgekehrt von R gerechnet wird.</span></div></div>
<p>Wir können eine biologische Relevanz definieren, dadurch das ein 95% Konfidenzintervall die Wahrscheinlichkeitsaussage über die Signifkanz, daher ob die Nullhypothese abgelehnt werden kann, mit dem Effekt zusammenbringt. Wo die Signifikanzschwelle klar definiert ist, hängt die Relevanzschwelle von der wissenschaftlichen Fragestellung und weiteren externen Faktoren ab. Die Signifikanzschwelle liegt bei 0, wenn wir Mittelwerte miteinander vergleichen und bei 1, wenn wir Anteile vergleichen. <a href="#fig-relevanz">Abbildung&nbsp;<span>18.4</span></a> zeigt fünf 95% Konfidenzintervalle (a-e), die sich anhand der Signifikanz und Relevanz unterscheiden. Bei der Relevanz ist es wichtig zu wissen in welche <em>Richtung</em> der Effekt gehen soll. Erwarten wir einen positiven Effekt wenn wir die Differenz der beiden Gruppen bilden oder einen negativen Effekt?</p>
<div id="fig-relevanz" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/ci-02.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 18.4— Verschiedene signifikante und relevante Konfidenzintervalle: (a) nicht signifikant und nicht relevant; (b) signifikant und nicht relevant; (c) signifikant und relevant; (d) signifikant und nicht relevant, der Effekt ist zu klein; (e) signifikant und potenziell relevant, Effekt zeigt in eine unerwartete Richtung gegeben der Relevanzschwelle.</figcaption><p></p>
</figure>
</div>
<p>Wir wollen uns nun einmal anschauen, wie sich ein 95% Konfidenzintervall berechnet. Wir nehmen dafür die vereinfachte Formel und setzen die berechneten statistischen Maßzahlen ein. In der Anwendung werden wir die Konfidenzintervalle nicht selber berechnen. Wenn ein statistisches Verfahren konfidenzintervalle berechnen kann, dann liefert die entsprechende Funktion in R das Konfidenzintervall.</p>
<p>Es ergibt sich Folgende ausgefüllte, vereinfachte Formel für das 95% Konfidenzintervalls eines t-Tests für das Beispiel des Sprungweitenunterschieds [cm] zwischen Hunde- und Katzenflöhen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/angel_01.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Wir nutzen hier eine <strong>vereinfachte Formel</strong> für das Konfidenzintervall um das Konzept zu verstehen. Später berechnen wir das Konfidenzintervall in R.</p>
</div></div><p><span class="math display">\[
\left[
(9.2-7.8) -
2.78 \cdot \frac {0.55}{\sqrt{4}}; \;
(9.2-7.8) +
2.78 \cdot \frac {0.55}{\sqrt{4}};
\right]
\]</span></p>
<p>mit</p>
<ul>
<li>
<span class="math inline">\(\bar{y}_{cat} = 9.2\)</span> dem Mittelwert für die Gruppe <em>cat</em>.</li>
<li>
<span class="math inline">\(\bar{y}_{dog} = 7.8\)</span> dem Mittelwert für die Gruppe <em>dog</em>.</li>
<li>
<span class="math inline">\(T_{\alpha = 5\%} = 2.78\)</span> dem kritischen Wert.</li>
<li>
<span class="math inline">\(s_p = 0.55\)</span> der gepoolten Standardabweichung mit <span class="math inline">\(s_p = \tfrac{0.6 + 0.5}{2}\)</span>.</li>
<li>
<span class="math inline">\(n_g = 4\)</span> der Gruppengröße der Gruppe A und B. Wir nehmen an beide Gruppen sind gleich groß.</li>
</ul>
<p>Lösen wir die Formel auf, so ergibt sich folgendes 95% Konfidenzintervall des Mittelwertsunterschiedes der Hunde- und Katzenflöhe.</p>
<p><span class="math display">\[[0.39; 2.20]\]</span></p>
<p>Wir können sagen, dass mit 95% Wahrscheinlichkeit das Konfidenzintervall den wahren Effektunterschied <span class="math inline">\(\Delta\)</span> überdeckt. Oder etwas mehr in Prosa, dass wir eine Sprungweiten<em>unterschied</em> von 0.39 cm bis 2.20 cm zwischen Hunde- und Katzenflöhen erwarten würden.</p>
<p>Die Entscheidung gegen die Nullhypothese bei einem Mittelwertsunterschied erfolgt bei einem 95% Konfidenzintervall danach ob die Null mit im Konfidenzintervall liegt oder nicht. In dem Interval <span class="math inline">\([0.39; 2.20]\)</span> ist die Null nicht enthalten, also können wir die Nullhypothese ablehnen. Es ist mit einem Unterschied zwischen den mittleren Sprungweiten von Hunde- und Katzenflöhen auszugehen.</p>
<p>In unserem Beispiel, könnten wir die Relevanzschwelle für den mittleren Sprungweitenunterschied zwischen Hund- und Katzenflöhen auf 2 cm setzen. In dem Fall würden wir entscheiden, dass der mittlere Sprungweitenunterschied nicht relevant ist, da die 2 cm im Konfidenzintervall enthalten sind. Was wäre wenn wir die Relevanzschwelle auf 4 cm setzen? Dann wäre zwar die Relevanzschwelle nicht mehr im Konfidenzintervall, aber wir hätten Fall (d) in der <a href="#fig-relevanz">Abbildung&nbsp;<span>18.4</span></a> vorliegen. Der Effekt ist einfach zu klein, dass der Effekt relevant sein könnte.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Entscheidung mit dem 95% Konfidenzintervall
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bei der Entscheidung mit dem 95% Konfidenzinterval müssen wir zwei Fälle unterscheiden.</p>
<ol type="1">
<li><p>Entweder schauen wir uns einen Mittelwertsunterschied (<span class="math inline">\(\Delta_{y_1-y_2}\)</span>) an, dann können wir die Nullhypothese (H<span class="math inline">\(_0\)</span>) <em>nicht</em> ablehnen, wenn die <strong>0</strong> im 95% Konfidenzinterval ist.</p></li>
<li><p>Oder wir schauen uns einen Anteilsunterschied (<span class="math inline">\(\Delta_{y_1/y_2}\)</span>) an, dann können wir die Nullhypothese (H<span class="math inline">\(_0\)</span>) <em>nicht</em> ablehnen, wenn die <strong>1</strong> im 95% Konfidenzinterval ist.</p></li>
</ol>
</div>
</div>
</section></section><section id="sec-delta-n-s" class="level2 page-columns page-full" data-number="18.3"><h2 data-number="18.3" class="anchored" data-anchor-id="sec-delta-n-s">
<span class="header-section-number">18.3</span> Auswirkung des Effektes, der Streuung und der Fallzahl</h2>
<p>Wir wollen einmal den Zusammenhang zwischen dem Effekt <span class="math inline">\(\Delta\)</span>, der Streuung als Standardabweichung <span class="math inline">\(s\)</span> und Fallzahl <span class="math inline">\(n\)</span> uns näher anschauen. Wir können die Formel des t-Tests wie folgt vereinfachen.</p>
<p><span class="math display">\[
T_{calc}=\cfrac{\bar{y}_1-\bar{y}_1}{s_{p} \cdot \sqrt{2/n_g}}
\]</span></p>
<p>Für die Betrachtung der Zusammenhänge wandeln wir <span class="math inline">\(\sqrt{2/n_g}\)</span> in <span class="math inline">\(1/n\)</span> um. Dadurch wandert die Fallzahl <span class="math inline">\(n\)</span> in den Zähler. Die Standardabweichung verallgemeinern wir zu <span class="math inline">\(s\)</span> und damit allgemein zur Streuung. Abschließend betrachten wir <span class="math inline">\(\bar{y}_A-\bar{y}_B\)</span> als den Effekt <span class="math inline">\(\Delta\)</span>. Es ergibt sich folgende vereinfachte Formel.</p>
<p><span class="math display">\[
T_{calc} = \cfrac{\Delta \cdot n}{s}
\]</span></p>
<p>Wir können uns nun die Frage stellen, wie ändert sich die Teststatistik <span class="math inline">\(T_{calc}\)</span> in Abhängigkeit vom Effekt <span class="math inline">\(\Delta\)</span>, der Fallzahl <span class="math inline">\(n\)</span> und der Streuung <span class="math inline">\(s\)</span> in den Daten. Die <a href="#tbl-t-und-p">Tabelle&nbsp;<span>18.4</span></a> zeigt die Zusammenhänge auf. Die Aussagen in der Tabelle lassen sich generalisieren. So bedeutet eine steigende Fallzahl meist mehr signifikante Ergebnisse. Eine stiegende Streuung reduziert die Signifikanz eines Vergleichs. Ein Ansteigen des Effektes führt zu mehr signifikanten Ergebnissen. Ebenso verschiebt eine Veränderung des Effekt das Konfidenzintervall, eine Erhöhung der Streuung macht das konfidenzintervall breiter, eine sinkende Streeung macht das konfidenzintervall schmaller. bei der Fallzahl verhält es sich umgekehrt. Eine Erhöhung der Fallzahl macht das Konfidenzintervall schmaller und eine sinkende Fallzahl das Konfidenzintervall breiter.</p>
<div class="column-page">
<div id="tbl-t-und-p" class="anchored">
<table class="table">
<caption>Tabelle 18.4— Zusammenhang von der Teststatistik <span class="math inline">\(T_{calc}\)</span> und dem p-Wert <span class="math inline">\(Pr(\geq T_{calc}|H_0)\)</span> sowie dem <span class="math inline">\(KI_{1-\alpha}\)</span> in Abhängigkeit vom Effekt <span class="math inline">\(\Delta\)</span>, der Fallzahl <span class="math inline">\(n\)</span> und der Streuung <span class="math inline">\(s\)</span>.</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{T_{calc}}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{Pr(\geq T_{calc}|H_0)}\)</span></th>
<th><span class="math inline">\(KI_{1-\alpha}\)</span></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{T_{calc}}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\boldsymbol{Pr(\geq T_{calc}|H_0)}\)</span></th>
<th><span class="math inline">\(KI_{1-\alpha}\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\Delta \uparrow\)</span></td>
<td style="text-align: center;">steigt</td>
<td style="text-align: center;">sinkt</td>
<td>verschoben</td>
<td style="text-align: center;"><span class="math inline">\(\Delta \downarrow\)</span></td>
<td style="text-align: center;">sinkt</td>
<td style="text-align: center;">steigt</td>
<td>verschoben</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(s \uparrow\)</span></td>
<td style="text-align: center;">sinkt</td>
<td style="text-align: center;">steigt</td>
<td>breiter</td>
<td style="text-align: center;"><span class="math inline">\(s \downarrow\)</span></td>
<td style="text-align: center;">steigt</td>
<td style="text-align: center;">sinkt</td>
<td>schmaller</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(n \uparrow\)</span></td>
<td style="text-align: center;">steigt</td>
<td style="text-align: center;">sinkt</td>
<td>schmaller</td>
<td style="text-align: center;"><span class="math inline">\(n \downarrow\)</span></td>
<td style="text-align: center;">sinkt</td>
<td style="text-align: center;">steigt</td>
<td>breiter</td>
</tr>
</tbody>
</table>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-tests-preface.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Frequentistische Hypothesentests</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-tests-theorie.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>