<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 26&nbsp; Multiple Vergleiche oder Post-hoc Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-linear-reg-preface.html" rel="next">
<link href="./stat-tests-diagnostic.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen und Hunden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen, Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes-site.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren in Habitaten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Gummibärchen</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Von Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Gaussian lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Lineare gemische Modelle</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimentel-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimentel-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./bayes-preface.html" class="sidebar-item-text sidebar-link">Bayesianische Statistik</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Grundlagen der Bayesianischen Statistik</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link active" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"> <span class="header-section-number">26.1</span> Genutzte R Pakete für das Kapitel</a></li>
  <li>
<a href="#daten" id="toc-daten" class="nav-link" data-scroll-target="#daten"> <span class="header-section-number">26.2</span> Daten</a>
  <ul class="collapse">
<li><a href="#hypothesen-f%C3%BCr-multiple-vergleiche" id="toc-hypothesen-für-multiple-vergleiche" class="nav-link" data-scroll-target="#hypothesen-f%C3%BCr-multiple-vergleiche"> <span class="header-section-number">26.2.1</span> Hypothesen für multiple Vergleiche</a></li>
  </ul>
</li>
  <li>
<a href="#sec-posthoc-pairwise" id="toc-sec-posthoc-pairwise" class="nav-link" data-scroll-target="#sec-posthoc-pairwise"> <span class="header-section-number">26.3</span> Gruppenvergleiche mit <code>pairwise.*.test()</code></a>
  <ul class="collapse">
<li><a href="#paarweiser-t-test" id="toc-paarweiser-t-test" class="nav-link" data-scroll-target="#paarweiser-t-test"> <span class="header-section-number">26.3.1</span> Paarweiser t Test</a></li>
  <li><a href="#paarweiser-wilcoxon-test" id="toc-paarweiser-wilcoxon-test" class="nav-link" data-scroll-target="#paarweiser-wilcoxon-test"> <span class="header-section-number">26.3.2</span> Paarweiser Wilcoxon Test</a></li>
  </ul>
</li>
  <li>
<a href="#sec-posthoc-multcomp" id="toc-sec-posthoc-multcomp" class="nav-link" data-scroll-target="#sec-posthoc-multcomp"> <span class="header-section-number">26.4</span> Gruppenvergleich mit dem <code>multcomp</code> Paket</a>
  <ul class="collapse">
<li><a href="#gruppenvergleiche-mit-multcomp-in-r" id="toc-gruppenvergleiche-mit-multcomp-in-r" class="nav-link" data-scroll-target="#gruppenvergleiche-mit-multcomp-in-r"> <span class="header-section-number">26.4.1</span> Gruppenvergleiche mit <code>multcomp</code> in R</a></li>
  </ul>
</li>
  <li>
<a href="#sec-posthoc-emmeans" id="toc-sec-posthoc-emmeans" class="nav-link" data-scroll-target="#sec-posthoc-emmeans"> <span class="header-section-number">26.5</span> Gruppenvergleich mit der <code>emmeans</code> Paket</a>
  <ul class="collapse">
<li><a href="#gruppenvergleiche-mit-emmeans-in-r" id="toc-gruppenvergleiche-mit-emmeans-in-r" class="nav-link" data-scroll-target="#gruppenvergleiche-mit-emmeans-in-r"> <span class="header-section-number">26.5.1</span> Gruppenvergleiche mit <code>emmeans</code> in R</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-posthoc" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell">

</div>
<p><em>Version vom September 05, 2022 um 09:21:00</em></p>
<p>In diesem Kapitel wollen wir uns mit den multipen Vergleichen beschäftigen. Das heißt, wir wollen statistisch Testen, ob sich die Level eines Faktors voneinander unterscheiden. Eventuell hast du schon eine einfaktorielle ANOVA gerechnet, wie in <a href="stat-tests-anova.html#sec-fac1"><span>Kapitel&nbsp;21.2</span></a> beschrieben. Oder aber du hast eine mehrfaktorielle ANOVA gerechnet wie in <a href="stat-tests-anova.html#sec-fac2"><span>Kapitel&nbsp;21.3</span></a> gezeigt. In beiden Fällen hast du jetzt einen signifikanten Faktor, der mehr als zwei Level hat. Du willst nun wissen, <em>welche</em> der Gruppenmittelwerte der Level sich signifikant unterscheiden. Hierfür können wir verschiedene Ansätze wählen.</p>
<ol type="1">
<li>Wir haben eine einfaktorielle ANOVA gerechnet und nutzen nun paarweise Vergleiche um herauszufinden welche Gruppenmittelwerte sich unterscheiden (siehe <a href="#sec-posthoc-pairwise"><span>Kapitel&nbsp;26.3</span></a>)</li>
<li>Wir haben eine mehrfaktorielle ANOVA gerechnet und haben daher mehrere Faktoren. Wir nutzen nun entweder das R Paket <code>multcomp</code> (siehe <a href="#sec-posthoc-multcomp"><span>Kapitel&nbsp;26.4</span></a>) oder das R Paket <code>emmeans</code> (siehe <a href="#sec-posthoc-emmeans"><span>Kapitel&nbsp;26.5</span></a>) um herauszufinden welche Gruppenmittelwerte sich unterscheiden.</li>
</ol>
<p>Wenn wir multiple Mittelwertsvergleiche rechnen, dann tritt das Problem des multipen Testens auf. Im <a href="stat-tests-theorie.html#sec-statistisches-testen-alpha-adjust"><span>Kapitel&nbsp;19.3</span></a> kannst du mehr über die Problematik erfahren und wie wir mit der <span class="math inline">\(\alpha\)</span> Inflation umgehen. Hier in diesem Kapitel gehe ich jetzt davon aus, dass dir die <span class="math inline">\(\alpha\)</span> Adjustierung ein Begriff ist.</p>
<section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="26.1"><h2 data-number="26.1" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">26.1</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, <span class="va">conflicted</span>, <span class="va">broom</span>,</span>
<span>               <span class="va">multcomp</span>, <span class="va">emmeans</span>, <span class="va">ggpubr</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"select"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"filter"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span>
<span><span class="fu">conflict_prefer</span><span class="op">(</span><span class="st">"mutate"</span>, <span class="st">"dplyr"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="daten" class="level2" data-number="26.2"><h2 data-number="26.2" class="anchored" data-anchor-id="daten">
<span class="header-section-number">26.2</span> Daten</h2>
<p>Wir nutzen in diesem Kapitel den Datensatz aus dem Beispiel in <a href="example-fleas-dogs-cats-foxes.html"><span>Kapitel&nbsp;6</span></a>. Wir haben als Outcome die Sprunglänge in [cm] von Flöhen. Die Sprunglänge haben wir an Flöhen von Hunde, Katzen und Füchsen gemessen. Der Datensatz ist also recht übeerschaubar. Wir haben ein normalverteiltes <span class="math inline">\(y\)</span> mit <code>jump_length</code> sowie einen multinomialverteiltes <span class="math inline">\(y\)</span> mit <code>grade</code> und einen Faktor <code>animal</code> mit drei Leveln.</p>
<p>Du kannst dir komplexere Auswertungen im <a href="app-example-analysis.html"><span>Kapitel&nbsp;A</span></a> anschauen. Dort sammelt sich mit der Zeit Auswertungen vom Fachbereich an. Daher finden sich dort auch Beispiele für multiple Vergleiche.</p>
<p>Im Folgenden laden wir den Datensatz <code>flea_dog_cat_fox.csv</code> und selektieren mit der Funktion <code>select()</code> die benötigten Spalten. Abschließend müssen wir die Spalte <code>animal</code>noch in einen Faktor umwandeln. Damit ist unsere Vorbereitung des Datensatzes abgeschlossen.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fac1_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_csv2</span><span class="op">(</span><span class="st">"data/flea_dog_cat_fox.csv"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">animal</span>, <span class="va">jump_length</span>, <span class="va">grade</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>animal <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">animal</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#tbl-data-posthoc-1">Tabelle&nbsp;<span>26.1</span></a> ist der Datensatz <code>fac1_tbl</code> nochmal dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-posthoc-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 26.1— Selektierter Datensatz mit einer normalverteilten Variable <code>jump_length</code> sowie der multinominalverteilten Variable <code>grade</code> und einem Faktor <code>animal</code> mit drei Leveln.</caption>
<thead><tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">jump_length</th>
<th style="text-align: center;">grade</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.9</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">11.8</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">9.1</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">dog</td>
<td style="text-align: center;">7.6</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">3.2</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">4.1</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">7.7</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">8.1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">9.1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">9.7</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">10.6</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">8.6</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">10.3</td>
<td style="text-align: center;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir werden nun den Datensatz <code>fac1_tbl</code> in den folgenden Abschnitten immer wieder nutzen.</p>
<section id="hypothesen-für-multiple-vergleiche" class="level3" data-number="26.2.1"><h3 data-number="26.2.1" class="anchored" data-anchor-id="hypothesen-für-multiple-vergleiche">
<span class="header-section-number">26.2.1</span> Hypothesen für multiple Vergleiche</h3>
<p>Als wir eine ANOVA gerechnet hatten, hatten wir nur eine Nullhypothese und eine Alternativehypothese. Wenn wir Nullhypothese abgelehnt hatten, wussten wir nur, dass sich mindestens ein paarweiser Vergleich unterschiedet. Multiple Vergleich lösen nun dieses Problem und führen ein Hypothesen<em>paar</em> für jeden paarweisen Vergleich ein. Zum einen rechnen wir damit <span class="math inline">\(k\)</span> Tests und haben damit auch <span class="math inline">\(k\)</span> Hypothesenpaare (siehe auch <a href="stat-tests-theorie.html#sec-statistisches-testen-alpha-adjust"><span>Kapitel&nbsp;19.3</span></a> zur Problematik des wiederholten Testens).</p>
<p>Wenn wir zum Beispiel alle Level des Faktors <code>animal</code> miteinander Vergleichen wollen, dann rechnen wir <span class="math inline">\(k=3\)</span> paarweise Vergleiche. Im Folgenden sind alle drei Hypothesenpaare dargestellt.</p>
<span class="math display">\[\begin{align*}
H_{01}: &amp;\; \bar{y}_{cat} = \bar{y}_{dog}\\
H_{A1}: &amp;\; \bar{y}_{cat} \ne \bar{y}_{dog}\\
\end{align*}\]</span>
<span class="math display">\[\begin{align*}
H_{02}: &amp;\; \bar{y}_{cat} = \bar{y}_{fox}\\
H_{A2}: &amp;\; \bar{y}_{cat} \ne \bar{y}_{fox}\\
\end{align*}\]</span>
<span class="math display">\[\begin{align*}
H_{03}: &amp;\; \bar{y}_{dog} = \bar{y}_{fox}\\
H_{A3}: &amp;\; \bar{y}_{dog} \ne \bar{y}_{fox}\\
\end{align*}\]</span>
<p>Wenn wir drei Vergleiche rechnen, dann haben wir eine <span class="math inline">\(\alpha\)</span> Inflation vorliegen. Wir sagen, dass wir für das multiple Testen adjustieren müssen. In R gibt es eine Reihe von Adjustierungsverfahren. Wir nehmen meist Bonferroni oder das Verfahren, was in der jeweiligen Funktion als Standard (eng. <em>default</em>) gesetzt ist.</p>
<p>Wir adjustieren grundsätzlich die <span class="math inline">\(p\)</span>-Werte und erhalten adjustierte <span class="math inline">\(p\)</span>-Werte aus den jeweiligen Funktionen in R. Die adjustierten p-Werte können wir dann mit dem Signifikanzniveau von <span class="math inline">\(\alpha\)</span> gleich 5% vergleichen.</p>
</section></section><section id="sec-posthoc-pairwise" class="level2 page-columns page-full" data-number="26.3"><h2 data-number="26.3" class="anchored" data-anchor-id="sec-posthoc-pairwise">
<span class="header-section-number">26.3</span> Gruppenvergleiche mit <code>pairwise.*.test()</code>
</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Die Funktion <code>pairwise.*.test()</code> ist <em>veraltet</em>, wir nutzen das R Paket <code>emmeans</code>oder das R Paket <code>multcomp</code>.</span></div></div>
<p>Wenn wir nur einen Faktor mit mehr als zwei Leveln vorliegen haben, dann können wir die Funktion <code>pairwise.*.test()</code> nutzen. Der Stern <code>*</code> steht entweder als Platzhalter für <code>t</code> für den t-Test oder aber für <code>wilcox</code> für den Wilcoxon Test. Die Funktion ist relativ einfach zu nutzen und liefert auch sofort die entsprechenden p-Werte.</p>
<p>Die Funktion <code>pairwise.*.test()</code> ist in dem Sinne <em>veraltet</em>, da wir keine 95% Konfidenzintervalle generieren können. Da die Funktion aber immer mal wieder angefragt wird, ist die Funktion hier nochmal aufgeführt.</p>
<section id="paarweiser-t-test" class="level3 page-columns page-full" data-number="26.3.1"><h3 data-number="26.3.1" class="anchored" data-anchor-id="paarweiser-t-test">
<span class="header-section-number">26.3.1</span> Paarweiser t Test</h3>
<p>Wir nutzen den paarweisen t-Test,</p>
<ul>
<li>wenn wir ein normalverteiltes <span class="math inline">\(y\)</span> vorliegen haben, wie <code>jump_length</code>.</li>
<li>wenn wir <em>nur</em> einen Faktor mit mehr als zwei Leveln vorliegen haben, wie <code>animal</code>.</li>
</ul>
<p>Die Funktion <code>pairwise.t.test</code> kann nicht mit Datensätzen arbeiten sondern nur mit Vektoren. Daher können wir der Funktion auch keine <code>formula</code> übergeben sondern müssen die Vektoren aus dem Datensatz mit <code>fac1_tbl$jump_length</code> für das Outcome und mit <code>fac1_tbl$animal</code> für die Gruppierende Variable benennen. Das ist umständlich und dhaer auch fehleranfällig.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Mehr zu <code>mutate_if()</code> erfährst du auf der <a href="https://dplyr.tidyverse.org/reference/mutate_all.html">Hilfeseite von mutate()</a></p>
</div></div><p>Als Adjustierungsmethode für den <span class="math inline">\(\alpha\)</span> Fehler wählen wir die Bonferroni-Methode mit <code>p.adjust.method = "bonferroni"</code> aus. Da wir eine etwas unübersichtliche Ausgabe in R erhalten nutzen wir die Funktion <code>tidy()</code>um die Ausgabe in ein saubers <code>tibble</code> zu verwandeln. Abschließend runden wir noch alle numerischen Spalten mit der Funktion <code>round</code> auf drei Stellen hinter dem Komma.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span><span class="va">fac1_tbl</span><span class="op">$</span><span class="va">jump_length</span>, <span class="va">fac1_tbl</span><span class="op">$</span><span class="va">animal</span>,</span>
<span>                p.adjust.method <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">tidy</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate_if</span><span class="op">(</span><span class="va">is.numeric</span>, <span class="va">round</span>, <span class="fl">3</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  group1 group2 p.value
  &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;
1 cat    dog      0.007
2 fox    dog      0.876
3 fox    cat      0.001</code></pre>
</div>
</div>
<p>Wir erhalten in einem Tibble die adujstierten p-Werte nach Bonferroni. Wir können daher die adjustierten p-Werte ganz normal mit dem Signifikanzniveau <span class="math inline">\(\alpha\)</span> von 5% vergleichen. Wir sehen, dass der Gruppenvergleich <code>cat - dog</code> signifikant ist, der Gruppenvergleich <code>fox - dog</code> nicht signifkant ist und der Gruppenvergleich <code>fox - cat</code> wiederum signifkant ist.</p>
<p>Leider können wir uns keine Konfidenzintervalle wiedergeben lassen, so dass die Funktion nicht dem Stand der Wissenschaft und deren Ansprüchen genügt.</p>
<p>Im Folgenden wollen wir uns nochmal die Visualisierung mit dem R Paket <code>ggpubr</code> anschauen. Die <a href="https://rpkgs.datanovia.com/ggpubr/index.html">Hilfeseite des R Pakets <code>ggpubr</code></a> liefert noch eine Menge weitere Beispiele für den simplen Fall eines Modells <span class="math inline">\(y ~ x\)</span>, also von einem <span class="math inline">\(y\)</span> und einem Faktor <span class="math inline">\(x\)</span>.</p>
<p>Um die <a href="#fig-ggpubr-1">Abbildung&nbsp;<span>26.1</span></a> zu erstellen müssen wir als erstes die Funktion <code>compare_mean()</code> nutzen um mit der <code>formula</code> Syntax einen t-Test zu rechnen. wir adjustieren die p-Werte nach Bonferroni. Anschließend erstellen wir einen Boxplot mit der Funktion <code>ggboxplot()</code> und speichern die Ausgabe in dem Objekt <code>p</code>. Wie in <code>ggplot</code> üblich können wir jetzt auf das Layer <code>p</code> über das <code>+</code>-Zeichen noch weitere Layer ergänzen. Wir nutzen die Funktion <code>stat_pvalue_manual()</code> um die asjustierten p-Werte aus dem Objekt <code>stat_test_obj</code> zu ergänzen. Abschließend wollen wir noch den p-Wert einer einfaktoriellen ANOVA als globalen Test ergänzen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stat_test_obj</span> <span class="op">&lt;-</span> <span class="fu">compare_means</span><span class="op">(</span></span>
<span> <span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span>, data <span class="op">=</span> <span class="va">fac1_tbl</span>,</span>
<span> method <span class="op">=</span> <span class="st">"t.test"</span>,</span>
<span> p.adjust.method <span class="op">=</span> <span class="st">"bonferroni"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu">ggboxplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">fac1_tbl</span>, x <span class="op">=</span> <span class="st">"animal"</span>, y <span class="op">=</span> <span class="st">"jump_length"</span>,</span>
<span>               color <span class="op">=</span> <span class="st">"animal"</span>, palette <span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span><span class="op">)</span>,</span>
<span>               add <span class="op">=</span> <span class="st">"jitter"</span>, shape <span class="op">=</span> <span class="st">"animal"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">+</span> <span class="fu">stat_pvalue_manual</span><span class="op">(</span><span class="va">stat_test_obj</span>, label <span class="op">=</span> <span class="st">"p.adj"</span>, y.position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">13</span>, <span class="fl">16</span>, <span class="fl">19</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_compare_means</span><span class="op">(</span>label.y <span class="op">=</span> <span class="fl">20</span>, method <span class="op">=</span> <span class="st">"anova"</span><span class="op">)</span>    </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ggpubr-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-posthoc_files/figure-html/fig-ggpubr-1-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 26.1— Boxplot der Sprungweiten [cm] von Hunden und Katzen ergänzt um den paarweisen Vergleich mit dem t-Test und den Bonferroni adjustierten p-Werten.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="paarweiser-wilcoxon-test" class="level3 page-columns page-full" data-number="26.3.2"><h3 data-number="26.3.2" class="anchored" data-anchor-id="paarweiser-wilcoxon-test">
<span class="header-section-number">26.3.2</span> Paarweiser Wilcoxon Test</h3>
<p>Wir nutzen den paarweisen Wilxocon Test,</p>
<ul>
<li>wenn wir ein <em>nicht</em>-normalverteiltes <span class="math inline">\(y\)</span> vorliegen haben, wie <code>grade</code>.</li>
<li>wenn wir <em>nur</em> einen Faktor mit mehr als zwei Leveln vorliegen haben, wie <code>animal</code>.</li>
</ul>
<p>Die Funktion <code>pairwise.wilcox.test</code> kann nicht mit Datensätzen arbeiten sondern nur mit Vektoren. Daher können wir der Funktion auch keine <code>formula</code> übergeben sondern müssen die Vektoren aus dem Datensatz mit <code>fac1_tbl$jump_length</code> für das Outcome und mit <code>fac1_tbl$animal</code> für die Gruppierende Variable benennen. Das ist umständlich und dhaer auch fehleranfällig.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Mehr zu <code>mutate_if()</code> erfährst du auf der <a href="https://dplyr.tidyverse.org/reference/mutate_all.html">Hilfeseite von mutate()</a></p>
</div></div><p>Als Adjustierungsmethode für den <span class="math inline">\(\alpha\)</span> Fehler wählen wir die Bonferroni-Methode mit <code>p.adjust.method = "bonferroni"</code> aus. Da wir eine etwas unübersichtliche Ausgabe in R erhalten nutzen wir die Funktion <code>tidy()</code>um die Ausgabe in ein saubers <code>tibble</code> zu verwandeln. Abschließend runden wir noch alle numerischen Spalten mit der Funktion <code>round</code> auf drei Stellen hinter dem Komma.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.wilcox.test.html">pairwise.wilcox.test</a></span><span class="op">(</span><span class="va">fac1_tbl</span><span class="op">$</span><span class="va">grade</span>, <span class="va">fac1_tbl</span><span class="op">$</span><span class="va">animal</span>,</span>
<span>                     p.adjust.method <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">tidy</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate_if</span><span class="op">(</span><span class="va">is.numeric</span>, <span class="va">round</span>, <span class="fl">3</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  group1 group2 p.value
  &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;
1 cat    dog      0.045
2 fox    dog      0.005
3 fox    cat      0.011</code></pre>
</div>
</div>
<p>Wir erhalten in einem Tibble die adujstierten p-Werte nach Bonferroni. Wir können daher die adjustierten p-Werte ganz normal mit dem Signifikanzniveau <span class="math inline">\(\alpha\)</span> von 5% vergleichen. Wir sehen, dass der Gruppenvergleich <code>cat - dog</code> knapp signifikant ist, der Gruppenvergleich <code>fox - dog</code> ebenfalls signifkant ist und der Gruppenvergleich <code>fox - cat</code> auch signifkant ist.</p>
<p>Leider können wir uns keine Konfidenzintervalle wiedergeben lassen, so dass die Funktion nicht dem Stand der Wissenschaft und deren Ansprüchen genügt.</p>
<p>Im Folgenden wollen wir uns nochmal die Visualisierung mit dem R Paket <code>ggpubr</code> anschauen. Die <a href="https://rpkgs.datanovia.com/ggpubr/index.html">Hilfeseite des R Pakets <code>ggpubr</code></a> liefert noch eine Menge weitere Beispiele für den simplen Fall eines Modells <span class="math inline">\(y ~ x\)</span>, also von einem <span class="math inline">\(y\)</span> und einem Faktor <span class="math inline">\(x\)</span>.</p>
<p>Um die <a href="#fig-ggpubr-2">Abbildung&nbsp;<span>26.2</span></a> zu erstellen müssen wir als erstes die Funktion <code>compare_mean()</code> nutzen um mit der <code>formula</code> Syntax einen Wilcoxon Test zu rechnen. wir adjustieren die p-Werte nach Bonferroni. Anschließend erstellen wir einen Boxplot mit der Funktion <code>ggboxplot()</code> und speichern die Ausgabe in dem Objekt <code>p</code>. Wie in <code>ggplot</code> üblich können wir jetzt auf das Layer <code>p</code> über das <code>+</code>-Zeichen noch weitere Layer ergänzen. Wir nutzen die Funktion <code>stat_pvalue_manual()</code> um die asjustierten p-Werte aus dem Objekt <code>stat_test_obj</code> zu ergänzen. Abschließend wollen wir noch den p-Wert eines Kruskal Wallis als globalen Test ergänzen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stat_test_obj</span> <span class="op">&lt;-</span> <span class="fu">compare_means</span><span class="op">(</span></span>
<span> <span class="va">grade</span> <span class="op">~</span> <span class="va">animal</span>, data <span class="op">=</span> <span class="va">fac1_tbl</span>,</span>
<span> method <span class="op">=</span> <span class="st">"wilcox.test"</span>,</span>
<span> p.adjust.method <span class="op">=</span> <span class="st">"bonferroni"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu">ggboxplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">fac1_tbl</span>, x <span class="op">=</span> <span class="st">"animal"</span>, y <span class="op">=</span> <span class="st">"grade"</span>,</span>
<span>               color <span class="op">=</span> <span class="st">"animal"</span>, palette <span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span><span class="op">)</span>,</span>
<span>               add <span class="op">=</span> <span class="st">"jitter"</span>, shape <span class="op">=</span> <span class="st">"animal"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">+</span> <span class="fu">stat_pvalue_manual</span><span class="op">(</span><span class="va">stat_test_obj</span>, label <span class="op">=</span> <span class="st">"p.adj"</span>, y.position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="fl">13</span>, <span class="fl">16</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_compare_means</span><span class="op">(</span>label.y <span class="op">=</span> <span class="fl">20</span>, method <span class="op">=</span> <span class="st">"kruskal.test"</span><span class="op">)</span>    </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ggpubr-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-posthoc_files/figure-html/fig-ggpubr-2-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 26.2— Boxplot der Sprungweiten [cm] von Hunden und Katzen ergänzt um den paarweisen Vergleich mit dem Wilcoxon Test und den Bonferroni adjustierten p-Werten.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section></section><section id="sec-posthoc-multcomp" class="level2 page-columns page-full" data-number="26.4"><h2 data-number="26.4" class="anchored" data-anchor-id="sec-posthoc-multcomp">
<span class="header-section-number">26.4</span> Gruppenvergleich mit dem <code>multcomp</code> Paket</h2>
<p>Wir drehen hier einmal die Erklärung um. Wir machen erst die Anwendung in R und sollte dich dann noch mehr über die statistischen Hintergründe der Funktionen interessieren, folgt ein Abschnitt noch zur Theorie. Du wirst die Funktionen aus <code>multcomp</code> vermutlich in deiner Abschlussarbeit brauchen. Häufig werden multiple Gruppenvergleiche in Abschlussarbeiten gerechnet.</p>
<section id="gruppenvergleiche-mit-multcomp-in-r" class="level3 page-columns page-full" data-number="26.4.1"><h3 data-number="26.4.1" class="anchored" data-anchor-id="gruppenvergleiche-mit-multcomp-in-r">
<span class="header-section-number">26.4.1</span> Gruppenvergleiche mit <code>multcomp</code> in R</h3>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die Ausgabe von <code>multcomp</code> können über die Funktion <code>tidy()</code> aufgeräumt werden. Mehr dazu unter der <a href="https://broom.tidymodels.org/reference/tidy.glht.html">Hilfeseite von <code>tidy</code>() zu multcomp</a>.</p>
</div></div><p>Als erstes brauchen wir ein lineares Modell für die Verwendung von <code>multcomp</code>. Normalerweise verenden wir das gleiche Modell, was wir schon in der ANOVA verwendet haben. Wir nutzen hier ein simples lineares Modell mit nur einem Faktor. Im Prinzip kann das Modell auch größer sein. Du findest immer Beispiel im <a href="app-example-analysis.html"><span>Kapitel&nbsp;A</span></a>, die dir eventuell dann nochmal zeigen, wie du deine Daten nutzen musst.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span>, data <span class="op">=</span> <span class="va">fac1_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir haben das Objeckt <code>fit_1</code> mit der Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> erstellt. Im Modell sind jetzt alle Mittelwerte und die entsprechenden Varianzen geschätzt worden. Mit <code>summary(fit_1)</code> kannst du dir gerne das Modell auch nochmal anschauen.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wenn wir keinen <em>all-pair</em> Vergleich rechnen wollen, dann können wir auch einen <em>many-to-one</em> Vergleich mit dem <code>Dunnett</code> Kontrast rechnen.</p>
</div></div><p>Im Anschluß nutzen wir die Funktion <code>glht()</code> um den multiplen vergleich zu rechnen. Als erstes musst du wissen, dass wenn wir <em>alle</em> Vergleiche rechnen wollen, wir einen <em>all-pair</em> Vergleich rechnen. In der Statistik heißt dieser Typ von Vergleich <code>Tukey</code>. Wir wollen jetzt als für den Faktor <code>animal</code> einen multiplen <code>Tukey</code>-Vergleich rechnen. Nichts anders sagt <code>mcp(animal = "Tukey")</code> aus, dabei steht <code>mcp</code> für <em>multiple comparison procedure</em>. Mit dem hinteren Teil der Funktion weiß jetzt die Funktion <code>glht()</code> was gerechnet werden soll. Wir müssen jetzt der Funktion nur noch mitgeben auf was der multiple vergleich gerehcnet werden soll, mit dem Objekt <code>fit_1</code>. Wir speichern die Ausgabe der Funktion in <code>comp_1_obj</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">comp_1_obj</span> <span class="op">&lt;-</span> <span class="fu">glht</span><span class="op">(</span><span class="va">fit_1</span>, linfct <span class="op">=</span> <span class="fu">mcp</span><span class="op">(</span>animal <span class="op">=</span> <span class="st">"Tukey"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mit dem Objekt <code>comp_1_fit</code> können wir noch nicht soviel anfangen. Der Inhalt ist etwas durcheinander und wir wollen noch die Konfidenzintervalle haben. Daher pipen wir <code>comp_1_fit</code> erstmal in die Funktion <code>tidy()</code> und alssen mit der Option <code>conf.int = TRUE</code> die simultanen 95% Konfidenzintervalle berechnen. Dann nutzen wir die Funktion <code>select()</code> um die wichtigen Spalten zu selektieren. Abschließend mutieren wir noch alle numerischen Spalten in dem wir auf die dritte Kommastelle runden. Wir speichern alles in das Objekt <code>res_1_obj</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_1_obj</span> <span class="op">&lt;-</span> <span class="va">comp_1_obj</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">contrast</span>, <span class="va">estimate</span>, <span class="va">adj.p.value</span>, </span>
<span>         <span class="va">conf.low</span>, <span class="va">conf.high</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate_if</span><span class="op">(</span><span class="va">is.numeric</span>, <span class="va">round</span>, <span class="fl">3</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir lassen uns dann den Inhalt von dem Objekt <code>res_1_obj</code> ausgeben.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_1_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  contrast  estimate adj.p.value conf.low conf.high
  &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 cat - dog    -3.39       0.006    -5.80     -0.97
2 fox - dog     1.03       0.535    -1.39      3.44
3 fox - cat     4.41       0.001     2.00      6.83</code></pre>
</div>
</div>
<p>Wir erhalten ein <code>tibble()</code> mit fünf Spalten. Zum einen den <code>contrast</code>, der den Vergleich widerspiegelt. Wir vergleichen im ersten Kontrast die Katzen- mit den Hundeflöhen, wobei wir <code>cat - dog</code> rechnen. Also wirklich der Mittelwert der Sprungweite der Katzenflöhe <em>minus</em> den Mittelwert der Sprungweite der Hundeflöhe rechnen. In der Spalte <code>estimate</code> sehen wir den Mittelwertsunterschied. Der Mittelwertsunterschied ist in der <em>Richtung</em> nicht ohne den Kontrast zu interpretieren. Danach erhalten wir die adjustierten <span class="math inline">\(p\)</span>-Wert sowie die simultanen 95% Konfidenzintervalle.</p>
<p>Wir können die Nullhypothese ablehnen für den Vergleiche<code>cat - dog</code> mit einem p-Wert von <span class="math inline">\(0.006\)</span> sowie für den Vergleich <span class="math inline">\(fox - cat\)</span> mit einem p-Wert von <span class="math inline">\(0.001\)</span>. Beide p-Werte liegen unter dem Signifikanzniveau von <span class="math inline">\(\alpha\)</span> gleich 5%.</p>
<p>In <a href="#fig-multcomp-1">Abbildung&nbsp;<span>26.3</span></a> sind die simultanen 95% Konfidenzintervalle nochmal in einem <code>ggplot</code> visualisiert. Die Kontraste und die Position hängen von dem Faktorlevel ab. Mit der Funktion <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> kannst du die Sortierung der Level einem Faktor ändern und somit auch Position auf den Achsen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span>  <span class="fu">ggplot</span><span class="op">(</span><span class="va">res_1_obj</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">contrast</span>, y<span class="op">=</span><span class="va">estimate</span>, </span>
<span>                        ymin<span class="op">=</span><span class="va">conf.low</span>, ymax<span class="op">=</span><span class="va">conf.high</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span>, linetype<span class="op">=</span><span class="st">"11"</span>, colour<span class="op">=</span><span class="st">"grey60"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_errorbar</span><span class="op">(</span>width<span class="op">=</span><span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-multcomp-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-posthoc_files/figure-html/fig-multcomp-1-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 26.3— Simultane 95% Konfidenzintervalle für den paarweisen Vergleich der Sprungweiten in [cm] der Hunde-, Katzen- und Fuchsflöhe.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Die Entscheidung gegen die Nullhypothese anhand der simultanen 95% Konfidenzintervalle ist inhaltlich gleich, wie die Entscheidung anhand der p-Werte. Wir entscheiden gegen die Nullhypothese, wenn die 0 nicht mit im Konfindenzintervall enthalten ist. Wir wählen hier die 0 zur Entscheidung gegen die Nullhypothese, weil wir einen Mittelwertsvergleich rechnen.</p>
<p>Für den Vergleich <code>fox -dog</code> ist die 0 im 95% Konfidenzintervall, wir können daher die Nullhypothese nicht ablehnen. Das 95% Konfidenzintervall ist nicht signifikant. Bei dem Vergleich <code>fox - cat</code> sowie dem Vergleich <code>cat - dog</code> ist jeweils die 0 nicht im 95% Konfidenzintervall enthalten. Beide 95% Konfidenzintervalle sind signifikant, wir können die Nullhypothese ablehnen.</p>
</section></section><section id="sec-posthoc-emmeans" class="level2 page-columns page-full" data-number="26.5"><h2 data-number="26.5" class="anchored" data-anchor-id="sec-posthoc-emmeans">
<span class="header-section-number">26.5</span> Gruppenvergleich mit der <code>emmeans</code> Paket</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p>Wir können hier nicht alles erklären und im Detail durchgehen. Hier gibt es noch ein aufwendiges Tutorium zu <code>emmeans</code>: <a href="https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/">Getting started with emmeans</a>.</p>
<p>Daneben gibt es auch noch die <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html#contents">Einführung mit Theorie auf der Seite des R Paktes</a></p>
</div></div><p>Im Folgenden wollen wir uns mit einem anderen R Paket beschäftigen was auch multiple Vergleiche rechnen kann. In diesem Kapitel nutzen wir das R Paket <code>emmeans</code>. Im Prinzip kann <code>emmeans</code> das Gleiche wir das R Paket <code>multcomp</code>. Beide Pakete rechnen dir einen multipen Vergleich. Das Paket <code>emmeans</code> kann noch mit <em>nested comparisons</em> umgehen. Deshlb hier nochmal die Vorstellung von <code>emmeans</code>. Du kannst aber für eine simple Auswertung mit nur einem Faktor beide Pakete verwenden.</p>
<section id="gruppenvergleiche-mit-emmeans-in-r" class="level3 page-columns page-full" data-number="26.5.1"><h3 data-number="26.5.1" class="anchored" data-anchor-id="gruppenvergleiche-mit-emmeans-in-r">
<span class="header-section-number">26.5.1</span> Gruppenvergleiche mit <code>emmeans</code> in R</h3>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die Ausgabe von <code>emmeans</code> können über die Funktion <code>tidy()</code> aufgeräumt werden. Mehr dazu unter der <a href="https://broom.tidymodels.org/reference/tidy.emmGrid.html">Hilfeseite von <code>tidy</code>() zu emmeans</a>.</p>
</div></div><p>Um den multiplen Vergleich in <code>emmeans</code> durchführen zu können brauchen wir zuerst ein lineares Modell, was uns die notwenidgen Parameter wie Mittelwerte und Standardabweichungen liefert. Wir nutzen in unserem simplen Beispiel ein lineares Modell mit einer Einflussvariable <span class="math inline">\(x\)</span> und nehmen an, dass unser Outcome <span class="math inline">\(y\)</span> normalverteilt ist. Achtung, hier muss natürlich das <span class="math inline">\(x\)</span> ein Faktor sein. Dann können wir ganz einfach die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> nutzen. Im Folgenden fitten wir das Modell <code>fit_2</code> was wir dann auch weiter nutzen werden.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span>, data <span class="op">=</span> <span class="va">fac1_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Der multiple Vergleich in <code>emmeans</code> ist mehrschrittig. Wir pipen unser Modell aus <code>fit_2</code> in die Funktion <code>emmeans()</code>. Wir geben mit <code>~ animal</code> an, dass wir über die Level des Faktors <code>animal</code> einen Vergleich rechnen wollen. Wir adjustieren die <span class="math inline">\(p\)</span>-Werte nach Bonferroni. Danach pipen wir weiter in die Funktion <code>contrast()</code> wo der eigentliche Vergleich festgelegt wird. In unserem Fall wollen wir einen <em>many-to-one</em> Vergleich rechnen. Alle Gruppen zu der Gruppe <code>fox</code>. Du kannst mit <code>ref =</code> auch ein anderes Level deines Faktors wählen.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">comp_2_obj</span> <span class="op">&lt;-</span> <span class="va">fit_2</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">animal</span>, adjust <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">contrast</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"trt.vs.ctrl"</span>, ref <span class="op">=</span> <span class="st">"fox"</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">comp_2_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast  estimate    SE df t.ratio p.value
 dog - fox    -1.03 0.947 18  -1.086  0.4682
 cat - fox    -4.41 0.947 18  -4.660  0.0004

P value adjustment: dunnettx method for 2 tests </code></pre>
</div>
</div>
<p>Wir können auch einen anderen Kontrast wählen. Wir überschreiben jetzt das Objekt <code>comp_2_obj</code> mit dem Kontrast <em>all-pair</em>, der alle möglichen Vergleiche rechnet. In <code>emmeans</code> heißt der <em>all-pair</em> Kontrast <em>pairwise</em>.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">comp_2_obj</span> <span class="op">&lt;-</span> <span class="va">fit_2</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">animal</span>, adjust <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">contrast</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"pairwise"</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">comp_2_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast  estimate    SE df t.ratio p.value
 dog - cat     3.39 0.947 18   3.574  0.0058
 dog - fox    -1.03 0.947 18  -1.086  0.5347
 cat - fox    -4.41 0.947 18  -4.660  0.0005

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>Wir können das Ergebnis auch noch mit der Funktion <code>tidy()</code> weiter aufräumen und dann die Spalten selektieren, die wir brauchen. Häufig benötigen wir nicht alle Spalten, die eine Funktion wiedergibt.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_2_obj</span> <span class="op">&lt;-</span> <span class="va">comp_2_obj</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">tidy</span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">contrast</span>, <span class="va">estimate</span>, <span class="va">adj.p.value</span>, <span class="va">conf.low</span>, <span class="va">conf.high</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">round</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">res_2_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  contrast  estimate adj.p.value conf.low conf.high
  &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 dog - cat     3.39      0.0058    0.968      5.80
2 dog - fox    -1.03      0.535    -3.45       1.39
3 cat - fox    -4.41      0.0005   -6.83      -2.00</code></pre>
</div>
</div>
<p>Abschließend wollen wir noch die 95% Konfidenzintervalle in <a href="#fig-emmeans-1">Abbildung&nbsp;<span>26.4</span></a> abbilden. Hier ist es bei <code>emmeans</code> genauso wie bei <code>multcomp</code>. Wir können das Objekt <code>res_2_obj</code> direkt in <code>ggplot()</code> weiterverwenden und uns die 95% Konfidenzintervalle einmal plotten.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span>  <span class="fu">ggplot</span><span class="op">(</span><span class="va">res_2_obj</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">contrast</span>, y<span class="op">=</span><span class="va">estimate</span>, ymin<span class="op">=</span><span class="va">conf.low</span>, ymax<span class="op">=</span><span class="va">conf.high</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span>, linetype<span class="op">=</span><span class="st">"11"</span>, colour<span class="op">=</span><span class="st">"grey60"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_errorbar</span><span class="op">(</span>width<span class="op">=</span><span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-emmeans-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-posthoc_files/figure-html/fig-emmeans-1-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 26.4— Die 95% Konfidenzintervalle für den <em>allpair</em>-Vergleich des simplen Datensatzes.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Wir wollen uns noch einen etwas komplizierteren Fall anschauen, indem sich <code>emmeans</code> von <code>multcomp</code> in der Anwendung unterscheidet. Wir laden den Datensatz <code>flea_dog_cat_fox_site.csv</code> in dem wir <em>zwei</em> Faktoren haben. Damit können wir dann ein Modell mit einem Interaktionsterm bauen. Wir erinnern uns, dass wir in der zweifaktoriellen ANOAV eine signifikante Interaktion zwischen den beiden Faktoren <code>animal</code> und <code>site</code> festgestelt hatten.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fac2_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_csv2</span><span class="op">(</span><span class="st">"data/flea_dog_cat_fox_site.csv"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">animal</span>, <span class="va">site</span>, <span class="va">jump_length</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>animal <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">animal</span><span class="op">)</span>,</span>
<span>         site <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">site</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir erhalten das Objekt <code>fac2_tbl</code> mit dem Datensatz in <a href="#tbl-data-emmeans-1">Tabelle&nbsp;<span>26.2</span></a> nochmal dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-emmeans-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 26.2— Selektierter Datensatz mit einer normalverteilten Variable <code>jump_length</code> und einem Faktor <code>animal</code> mit drei Leveln sowie dem Faktor <code>site</code> mit vier Leveln.</caption>
<thead><tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">site</th>
<th style="text-align: center;">jump_length</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">12.04</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">11.98</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">16.1</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">13.42</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">12.37</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">city</td>
<td style="text-align: center;">16.36</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">field</td>
<td style="text-align: center;">16.38</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">field</td>
<td style="text-align: center;">14.59</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">field</td>
<td style="text-align: center;">14.03</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">field</td>
<td style="text-align: center;">13.63</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">field</td>
<td style="text-align: center;">14.09</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">field</td>
<td style="text-align: center;">15.52</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#fig-boxplot-emmeans-1">Abbildung&nbsp;<span>26.5</span></a> sehen wir nochmal die Daten visualisiert. Wichtig ist hier, dass wir <em>zwei</em> Faktoren vorliegen haben. Den Faktor <code>animal</code> und den Faktor <code>site</code>. Dabei ist der Faktor <code>animal</code> in dem Faktor <code>site</code> genested. Wir messen jedes Level des Faktors <code>animal</code> jeweils in jedem Level des Faktors <code>site</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot-emmeans-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-posthoc_files/figure-html/fig-boxplot-emmeans-1-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 26.5— Boxplot der Sprungweiten [cm] von Hunden und Katzen gemessen an verschiedenen Orten.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Wir rechnen ein multiples lineares Modell mit einem Interaktionsterm. Daher packen wir beide Faktoren in das Modell sowie die Intraktion zwischen den beiden Faktoren. Wir erhalten nach dem fitten des Modells das Objekt <code>fit_3</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">jump_length</span> <span class="op">~</span> <span class="va">animal</span> <span class="op">+</span> <span class="va">site</span> <span class="op">+</span> <span class="va">animal</span><span class="op">:</span><span class="va">site</span>, data <span class="op">=</span> <span class="va">fac2_tbl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Der Unterschied zu unserem vorherigen multiplen Vergleich ist nun, dass wir auch einen multiplen Vergleich für <em>animal nested in site</em> rechnen können. Dafür müssen wir den Vergleich in der Form <code>animal | site</code> schreiben. Wir erhalten dann die Vergleiche der Level des faktors <code>animal</code> <em>getrennt</em> für die Level es Faktors <code>site</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">comp_3_obj</span> <span class="op">&lt;-</span> <span class="va">fit_3</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">emmeans</span><span class="op">(</span><span class="op">~</span> <span class="va">animal</span> <span class="op">|</span> <span class="va">site</span>, adjust <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">contrast</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"pairwise"</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">comp_3_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>site = city:
 contrast  estimate    SE  df t.ratio p.value
 cat - dog   -3.101 0.771 108  -4.022  0.0003
 cat - fox   -6.538 0.771 108  -8.479  &lt;.0001
 dog - fox   -3.437 0.771 108  -4.457  0.0001

site = smalltown:
 contrast  estimate    SE  df t.ratio p.value
 cat - dog   -4.308 0.771 108  -5.587  &lt;.0001
 cat - fox   -4.064 0.771 108  -5.271  &lt;.0001
 dog - fox    0.244 0.771 108   0.316  0.9463

site = village:
 contrast  estimate    SE  df t.ratio p.value
 cat - dog   -1.316 0.771 108  -1.707  0.2073
 cat - fox   -1.729 0.771 108  -2.242  0.0687
 dog - fox   -0.413 0.771 108  -0.536  0.8540

site = field:
 contrast  estimate    SE  df t.ratio p.value
 cat - dog   -0.982 0.771 108  -1.274  0.4131
 cat - fox    1.366 0.771 108   1.772  0.1840
 dog - fox    2.348 0.771 108   3.045  0.0082

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>Wir können uns das Ergebnis auch etwas schöner ausgeben lassen. Wir nutzen hier noch die Funktion <code><a href="https://rdrr.io/r/base/format.pval.html">format.pval()</a></code> um die <span class="math inline">\(p\)</span>-Werte besser zu formatieren. Die <span class="math inline">\(p\)</span>-Wert, die kleiner sind als 0.001 werden als <code>&lt;0.001</code> ausgegeben und die anderen <span class="math inline">\(p\)</span>-Werte auf zwei Nachstellen nach dem Komma gerundet.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">comp_3_obj</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">summary</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="va">as_tibble</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">contrast</span>, <span class="va">site</span>, <span class="va">p.value</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>p.value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/format.pval.html">format.pval</a></span><span class="op">(</span><span class="va">p.value</span>, eps <span class="op">=</span> <span class="fl">0.001</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   contrast  site      p.value
   &lt;fct&gt;     &lt;fct&gt;     &lt;chr&gt;  
 1 cat - dog city      &lt;0.001 
 2 cat - fox city      &lt;0.001 
 3 dog - fox city      &lt;0.001 
 4 cat - dog smalltown &lt;0.001 
 5 cat - fox smalltown &lt;0.001 
 6 dog - fox smalltown 0.95   
 7 cat - dog village   0.21   
 8 cat - fox village   0.07   
 9 dog - fox village   0.85   
10 cat - dog field     0.41   
11 cat - fox field     0.18   
12 dog - fox field     0.01   </code></pre>
</div>
</div>
<p>In der Ausgabe können wir erkennen, dass die Vergleich in der Stadt alle signifkant sind. Jedoch erkennen wir keine signifikanten Ergebnisse mehr in dem Dorf und im Feld ist nur der Vergleich <code>dog - fox</code> signifkant. Hier solltest du nochmal beachten, warum wir die Analyse getrennt machen. In der zweifaktoriellen ANOVA haben wir gesehen, dass ein signifkanter Interaktionsterm zwischen den beiden Faktoren <code>animal</code> und <code>site</code> vorliegt.</p>
<p>Wir wollen uns noch über die Funktion <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> die 95% Konfidenzintervalle wiedergeben lassen.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_3_obj</span> <span class="op">&lt;-</span> <span class="va">comp_3_obj</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">contrast</span>, <span class="va">site</span>, <span class="va">estimate</span>, conf.low <span class="op">=</span> <span class="va">lower.CL</span>, conf.high <span class="op">=</span> <span class="va">upper.CL</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">res_3_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
   contrast  site      estimate conf.low conf.high
   &lt;fct&gt;     &lt;fct&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 cat - dog city        -3.10    -4.93     -1.27 
 2 cat - fox city        -6.54    -8.37     -4.71 
 3 dog - fox city        -3.44    -5.27     -1.60 
 4 cat - dog smalltown   -4.31    -6.14     -2.48 
 5 cat - fox smalltown   -4.06    -5.90     -2.23 
 6 dog - fox smalltown    0.244   -1.59      2.08 
 7 cat - dog village     -1.32    -3.15      0.516
 8 cat - fox village     -1.73    -3.56      0.103
 9 dog - fox village     -0.413   -2.25      1.42 
10 cat - dog field       -0.982   -2.81      0.850
11 cat - fox field        1.37    -0.466     3.20 
12 dog - fox field        2.35     0.516     4.18 </code></pre>
</div>
</div>
<p>Besonders mit den 95% Konfiendezintervallen sehen wir nochmal den Interaktionseffekt zwischen den beiden Faktoren <code>animal</code> und <code>site</code>. So dreht sich der Effekt von zum Beispiel <code>dog - fox</code> von <span class="math inline">\(-3.44\)</span> in dem Level <code>city</code> zu <span class="math inline">\(+2.35\)</span> in dem Level <code>field</code>. Wir haben eine Interaktion vorliegen und deshalb die Analyse getrennt für jeden Level des Faktors <code>site</code> durchgeführt.</p>
<p><a href="#fig-emmeans-2">Abbildung&nbsp;<span>26.6</span></a> zeigt die entsprechenden 95% Konfidenzintervalle. Wir müssen hier etwas mit der <code>position</code> spielen, so dass die Punkte und der <code>geom_errorbar</code> richtig liegen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span>  <span class="fu">ggplot</span><span class="op">(</span><span class="va">res_3_obj</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">contrast</span>, y<span class="op">=</span><span class="va">estimate</span>, ymin<span class="op">=</span><span class="va">conf.low</span>, ymax<span class="op">=</span><span class="va">conf.high</span>,</span>
<span>                        color <span class="op">=</span> <span class="va">site</span>, group <span class="op">=</span> <span class="va">site</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span>, linetype<span class="op">=</span><span class="st">"11"</span>, colour<span class="op">=</span><span class="st">"grey60"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_errorbar</span><span class="op">(</span>width<span class="op">=</span><span class="fl">0.1</span>, position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu">geom_point</span><span class="op">(</span>position <span class="op">=</span> <span class="fu">position_dodge</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-emmeans-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-posthoc_files/figure-html/fig-emmeans-2-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 26.6— Die 95% Konfidenzintervalle für den <em>allpair</em>-Vergleich des Models mit Interaktionseffekt.</figcaption><p></p>
</figure>
</div>
</div>
</div>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-tests-diagnostic.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-linear-reg-preface.html" class="pagination-link">
        <span class="nav-page-text">Grundlagen der linearen Regression</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>