<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Ein Kochbuch mit Rezepten aus der Bio Data Science, Biostatistik, Biometrie und Statistik">

<title>Bio Data Science - 39&nbsp; Multiple lineare Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-linear-reg-quality.html" rel="next">
<link href="./stat-linear-reg-basic.html" rel="prev">
<link href="./cover2024_favi.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Bio Data Science - 39&nbsp; Multiple lineare Regression">
<meta property="og:description" content="Ein Kochbuch mit Rezepten der Bio Data Science, Biostatistik, Biometrie und Statistik">
<meta property="og:image" content="https://github.com/jkruppa/jkruppa.github.io/raw/master/cover2024.png">
<meta property="og:site_name" content="Bio Data Science">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-linear-reg-preface.html">Grundlagen des Modellierens</a></li><li class="breadcrumb-item"><a href="./stat-modeling-basic.html"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bio Data Science</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/jkruppa/jkruppa.github.io/" title="Quellcode" class="quarto-navigation-tool px-1" aria-label="Quellcode"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Dunkelmodus umschalten"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bibliothek</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./forschungsprozess.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forschungsprozess</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abschlussarbeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Abschlussarbeit</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./example-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datenbeispiele</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programmieren in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Buchstaben und Zahlen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Daten einlesen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Reguläre Ausdrücke</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-purrr-furrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Ein <code>purrr</code> Cookbook</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-quarto-shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Quarto und Shiny App</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explorative Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Testen von Hypothesen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der Pre-Test oder Vortest</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./experimental-design-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelle Designs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Versuchsplanung in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Einfache Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Fortgeschrittene Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental-design-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Fallzahlplanung</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-tests-preface-app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistische Gruppenvergleiche</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Testen in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Die ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-friedman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Der Friedman Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Multiple Vergleiche &amp; Post-hoc Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-permutationstest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Permutationstest &amp; Bootstraping</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grundlagen des Modellierens</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Modelgüte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Ausreißer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Variablenselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Fehlende Werte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Sensitivitätsanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisches Modellieren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Modellieren in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Gaussian Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-beta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Beta Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-multinom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Multinomiale / Ordinale Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-prob-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Linear Probability Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-robust-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Robuste und Quantilesregression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Überlebenszeitanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-noninferiority.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Äquivalenz oder Nichtunterlegenheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Metaanalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Clusteranalysen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Multivariate Verfahren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-survey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Fragebogenanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./time-space-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zeitliche und räumliche Analysen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-pseudo-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Pseudo Zeitreihen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Zeitreihen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-space-spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Räumliche Daten</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classification-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassifikation oder maschinelles Lernen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Grundlagen der Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Data splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-pre-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-model-compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Vergleich von Algorithmen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title"><span class="math inline">\(k\)</span> nearest neighbor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Decision trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Support vector machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Neural networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./abspann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abspann</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-spielecke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Spielecke</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#genutzte-r-pakete" id="toc-genutzte-r-pakete" class="nav-link active" data-scroll-target="#genutzte-r-pakete"><span class="header-section-number">39.1</span> Genutzte R Pakete</a></li>
  <li><a href="#sec-modell-matrix" id="toc-sec-modell-matrix" class="nav-link" data-scroll-target="#sec-modell-matrix"><span class="header-section-number">39.2</span> Die Modellmatrix in R</a>
  <ul class="collapse">
  <li><a href="#kontinuierliches-x" id="toc-kontinuierliches-x" class="nav-link" data-scroll-target="#kontinuierliches-x"><span class="header-section-number">39.2.1</span> Kontinuierliches <span class="math inline">\(x\)</span></a></li>
  <li><a href="#kategorielles-x-mit-2-leveln" id="toc-kategorielles-x-mit-2-leveln" class="nav-link" data-scroll-target="#kategorielles-x-mit-2-leveln"><span class="header-section-number">39.2.2</span> Kategorielles <span class="math inline">\(x\)</span> mit 2 Leveln</a></li>
  <li><a href="#kategorielles-x-mit-2-leveln-1" id="toc-kategorielles-x-mit-2-leveln-1" class="nav-link" data-scroll-target="#kategorielles-x-mit-2-leveln-1"><span class="header-section-number">39.2.3</span> Kategorielles <span class="math inline">\(x\)</span> mit &gt;2 Leveln</a></li>
  <li><a href="#das-volle-modell" id="toc-das-volle-modell" class="nav-link" data-scroll-target="#das-volle-modell"><span class="header-section-number">39.2.4</span> Das volle Modell</a></li>
  </ul></li>
  <li><a href="#sec-interpret-x" id="toc-sec-interpret-x" class="nav-link" data-scroll-target="#sec-interpret-x"><span class="header-section-number">39.3</span> Interpretation von <span class="math inline">\(x\)</span></a>
  <ul class="collapse">
  <li><a href="#sec-interpret-x-cont" id="toc-sec-interpret-x-cont" class="nav-link" data-scroll-target="#sec-interpret-x-cont"><span class="header-section-number">39.3.1</span> Kontinuierliches <span class="math inline">\(x\)</span></a></li>
  <li><a href="#sec-interpret-x-cat2" id="toc-sec-interpret-x-cat2" class="nav-link" data-scroll-target="#sec-interpret-x-cat2"><span class="header-section-number">39.3.2</span> Kategorielles <span class="math inline">\(x\)</span> mit 2 Leveln</a></li>
  <li><a href="#sec-interpret-x-cat3" id="toc-sec-interpret-x-cat3" class="nav-link" data-scroll-target="#sec-interpret-x-cat3"><span class="header-section-number">39.3.3</span> Kategorielles <span class="math inline">\(x\)</span> mit &gt;2 Leveln</a></li>
  </ul></li>
  <li><a href="#sec-confounder" id="toc-sec-confounder" class="nav-link" data-scroll-target="#sec-confounder"><span class="header-section-number">39.4</span> Adjustierung für Confounder</a></li>
  <li><a href="#sec-vif" id="toc-sec-vif" class="nav-link" data-scroll-target="#sec-vif"><span class="header-section-number">39.5</span> Variance inflation factor (VIF)</a></li>
  <li><a href="#sec-model-basic-compare" id="toc-sec-model-basic-compare" class="nav-link" data-scroll-target="#sec-model-basic-compare"><span class="header-section-number">39.6</span> Vergleich von Modellen</a></li>
  <li><a href="#referenzen" id="toc-referenzen" class="nav-link" data-scroll-target="#referenzen">Referenzen</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jkruppa/jkruppa.github.io/edit/master/stat-modeling-basic.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/blob/master/stat-modeling-basic.qmd" class="toc-action"><i class="bi empty"></i>Quellcode anzeigen</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./stat-linear-reg-preface.html">Grundlagen des Modellierens</a></li><li class="breadcrumb-item"><a href="./stat-modeling-basic.html"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-mult-reg-basic" class="quarto-section-identifier"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Letzte Änderung am 25. March 2024 um 18:23:15</em></p>
<blockquote class="blockquote">
<p><em>“All models are approximations. Essentially, all models are wrong, but some are useful. However, the approximate nature of the model must always be borne in mind.” — George E. P. Box</em></p>
</blockquote>
<p>In dem vorherigen Kapitel haben wir uns mit der simplen linearen Regression beschäftigt. In diesem Kapitel wollen wir uns nun mit den Grundlagen der <em>multiplen</em> linearen Regression beschäftigen. Sagen, dass wir ein multiples lineares Modell vorliegen haben, wenn wir mehrere Einflussvariable <span class="math inline">\(x_1\)</span> bis <span class="math inline">\(x_p\)</span> vorliegen haben. Bei dem Outcome <span class="math inline">\(y\)</span>, was einer Verteilung folgt, ändert sich erstmal nichts. Wir wollen jetzt herausfinden, welchen Einfluss oder Effekt die Variablen <span class="math inline">\(x_1, ..., x_p\)</span> auf das Outcome <span class="math inline">\(y\)</span> hat. Sehr simple gesprochen legen wir eine Gerade durch eine <em>mehrdimensionale</em> Punktewolke. Wir konzentrieren uns hier in diesem Kapitel auf nur normalverteilte Outcomes. Später kannst du dann aber auch andere Verteilungsfamilien modellieren.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[15,85]">
<div class="quarto-layout-row quarto-layout-valign-center">
<div class="quarto-layout-cell" style="flex-basis: 15.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/angel_01.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="images/angel_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 85.0%;justify-content: flex-start;">
<blockquote class="blockquote">
<p>Wenn du jetzt denkst ‘Hä? Was soll denn mehrdimensional bedeuten?’, dann besuche doch einmal die fantastische Seite <a href="https://setosa.io/ev/ordinary-least-squares-regression/">Explained Visually | Ordinary Least Squares Regression</a> um selber zu erfahren, was eine multiple lineare Regression macht. Auf der Seite findest du interaktive Abbildungen, die dir das Konzept der linearen Regression sehr anschaulich nachvollziehen lassen.</p>
</blockquote>
</div>
</div>
</div>
<p>Wir erinnern und nochmal, das ein <em>simples</em> lineares Modell nur ein <span class="math inline">\(x_1\)</span> hat:</p>
<p><span class="math display">\[
y \sim x_1
\]</span></p>
<p>Ein <em>multiples</em> lineares Modell hat von <span class="math inline">\(x_1\)</span> bis <span class="math inline">\(x_p\)</span> Einflussvariablen:</p>
<p><span class="math display">\[
y \sim x_1 + x_2 + ... + x_p
\]</span></p>
<p>Wir brauchen viele der Konzepte aus den vorherigen Kapiteln zur Modellgüte sowie Konfidenzintervallen. Vieles fällt hier zusammen. Schau dir ruhig nochmal die vorherigen Kapitel an, wenn dir etwas unklar ist. Häufig wollen wir auch etwas spezifischer sein. Wir schreiben daher einen Faktor mit einem <span class="math inline">\(f\)</span> wie folgt.</p>
<p><span class="math display">\[
y \sim f_1
\]</span></p>
<p>Wenn wir dann noch einen Block mit hinzunehmen, dann erweitern wir das Modell um einen Blockfaktor mit einem <span class="math inline">\(b\)</span> wie folgt.</p>
<p><span class="math display">\[
y \sim f_1 + b_1
\]</span></p>
<p>Es kann auch sein, dass wir noch einen zufälligen Effekt (eng. <em>random effect</em>) mit in das Modell nehmen wollen. Wir bezeichnen einen zufälligen Effekt mit einem <span class="math inline">\(z\)</span> wie folgt.</p>
<p><span class="math display">\[
y \sim f_1 + z_1
\]</span></p>
<p>Oder konkreter können wir sagen, dass <code>jump_length</code> von <code>animal</code>, <code>sex</code> und <code>weight</code> abhängt und wir diesen Zusammenhang modellieren wollen.</p>
<p><span class="math display">\[
jump\_length \sim animal + sex + weight
\]</span></p>
<p>Das hilft uns jetzt nur bedingt, denn wir wollen ja aus einer Modellierung in R die Koeffizienten der Regression wiederbekommen. Dafür müssen wir uns nochmal klar werden, was die Koeffizienten einer Regression sind. Das sind zum einen der y-Achsenabschnitt <span class="math inline">\(\beta_0\)</span> und die Steigung der einzelnen Variablen mit <span class="math inline">\(\beta_1\)</span> bis <span class="math inline">\(\beta_p\)</span>. Wir erhalten auch bei einem multiplen Regressionsmodell nur einen Vektor mit den Residuen wieder.</p>
<p><span class="math display">\[
y \sim \beta_0 + \beta_1 x_1 + \beta_2 x_2 + ... + \beta_p x_p + \epsilon
\]</span></p>
<p>Dennoch sind die Residuen <span class="math inline">\(\epsilon\)</span> normalverteilt. Wir haben im Mittel einen Abstand der <span class="math inline">\(\epsilon\)</span>’s zur geraden von 0 und eine Streuung von <span class="math inline">\(s^2_{\epsilon}\)</span>.</p>
<p><span class="math display">\[
\epsilon \sim \mathcal{N}(0, s^2_{\epsilon})
\]</span></p>
<p>Wir zeichen im Prinzip eine Gerade durch den <span class="math inline">\(p\)</span>-dimensionellen Raum.</p>
<p>In diesem Kapitel wollen wir uns nun folgende Aspekte einmal genauer anschauen. Wir gehen hier nicht so sehr auf den theoretischen Hintergrund ein, wollen aber verstehen wie wir die Statistik nutzen und anwenden können.</p>
<ul>
<li>Wir besprechen die Modellmatrix in <a href="#sec-modell-matrix" class="quarto-xref"><span>Kapitel 39.2</span></a>. Wir wollen uns Fragen, wie R eigentlich zu den Koeffizienten der Regressionsgleichung kommt.</li>
<li>Wir besprechen die Interpretation der Koeffizienten der linearen Regression in <a href="#sec-interpret-x" class="quarto-xref"><span>Kapitel 39.3</span></a>.</li>
<li>Wir fragen uns, was sind eigentlich Confounder (deu. <em>Verwechsler</em>) im <a href="#sec-confounder" class="quarto-xref"><span>Kapitel 39.4</span></a>.</li>
<li>Wir fragen uns, was ist eigentlich ein Variance Inflation Factor (VIF) für kontinuierliche <span class="math inline">\(x\)</span> in <a href="#sec-vif" class="quarto-xref"><span>Kapitel 39.5</span></a>.</li>
<li>Wir besprechen, wie wir verschiedene Modelle miteinander vergleichen können in <a href="#sec-model-basic-compare" class="quarto-xref"><span>Kapitel 39.6</span></a>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Weitere Tutorien für die multiple lineare Regression
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wir immer geht natürlich mehr als ich hier Vorstellen kann. Du findest im Folgenden Tutorien, die mich hier in dem Kapitel inspiriert haben. Ich habe mich ja in diesem Kapitel auf die Durchführbarkeit in R und die allgemeine Verständlichkeit konzentriert. Es geht aber natürlich wie immer auch mathematischer…</p>
<ul>
<li>Wir funktioniert nun so eine lineare Regression und was sind den jetzt eigentlich die Koeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> eigentlich? Hier gibt es die fantastische Seite <a href="https://setosa.io/ev/ordinary-least-squares-regression/">Explained Visually | Ordinary Least Squares Regression</a>, die dir nochmal erlaubt selbe mit Punkten in einem Scatterplot zu spielen und zu sehen wie sich dann die Regressionsgleichung ändert.</li>
<li>Das Buch <a href="https://www.tmwr.org/">Tidy Modeling with R</a> gibt nochmal einen tieferen Einblick in das Modellieren in R. Wir immer, es ist ein Vorschlag aber kein Muss.</li>
</ul>
</div>
</div>
<section id="genutzte-r-pakete" class="level2" data-number="39.1">
<h2 data-number="39.1" class="anchored" data-anchor-id="genutzte-r-pakete"><span class="header-section-number">39.1</span> Genutzte R Pakete</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, magrittr, broom,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               see, performance, car, parameters,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               conflicted)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conflicts_prefer</span>(magrittr<span class="sc">::</span>set_names)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>cbbPalette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#000000"</span>, <span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An der Seite des Kapitels findest du den Link <em>Quellcode anzeigen</em>, über den du Zugang zum gesamten R-Code dieses Kapitels erhältst.</p>
</section>
<section id="sec-modell-matrix" class="level2" data-number="39.2">
<h2 data-number="39.2" class="anchored" data-anchor-id="sec-modell-matrix"><span class="header-section-number">39.2</span> Die Modellmatrix in R</h2>
<p>Als erstes wollen wir verstehen, wie ein Modell <em>in</em> R aussieht. Dann können wir auch besser verstehen, wie die eigentlichen Koeffizienten aus dem Modell entstehen. Wozu brauche ich das? Eine gute Frage. Du brauchst das Verständnis der Modellmatrix, wenn du verstehen willst <em>wie</em> R in einer linearen Regression zu den Koeffizienten kommt. Wir bauen uns dafür ein sehr simplen Datensatz. Wir bauen uns einen Datensatz mit Schlangen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>snake_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">svl =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">45</span>, <span class="dv">39</span>, <span class="dv">51</span>, <span class="dv">52</span>, <span class="dv">57</span>, <span class="dv">58</span>, <span class="dv">49</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mass =</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">10</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">region =</span> <span class="fu">as_factor</span>(<span class="fu">c</span>(<span class="st">"west"</span>,<span class="st">"west"</span>, <span class="st">"west"</span>, <span class="st">"nord"</span>,<span class="st">"nord"</span>,<span class="st">"nord"</span>,<span class="st">"nord"</span>,<span class="st">"nord"</span>)),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="fu">as_factor</span>(<span class="fu">c</span>(<span class="st">"schwarz"</span>, <span class="st">"schwarz"</span>, <span class="st">"rot"</span>, <span class="st">"rot"</span>, <span class="st">"rot"</span>, <span class="st">"blau"</span>, <span class="st">"blau"</span>, <span class="st">"blau"</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#tbl-snakes" class="quarto-xref">Tabelle&nbsp;<span>39.1</span></a> ist der Datensatz <code>snake_tbl</code> nochmal dargestellt. Wir haben die Schlangenlänge <code>svl</code> als Outcome <span class="math inline">\(y\)</span> sowie das Gewicht der Schlangen <code>mass</code>, die Sammelregion <code>region</code> und die Farbe der Schlangen <code>color</code>. Dabei ist <code>mass</code> eine kontinuierliche Variable, <code>region</code> eine kategorielle Variable als Faktor mit zwei Leveln und <code>color</code> eine kategorielle Variable als Faktor mit drei Leveln.</p>
<div class="cell">
<div id="tbl-snakes" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-snakes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;39.1— Datensatz zu Schlangen ist entlehnt und modifiiert nach Kéry <span class="citation" data-cites="kery2010introduction">(<a href="#ref-kery2010introduction" role="doc-biblioref">2010</a>, p.&nbsp;77)</span>
</figcaption>
<div aria-describedby="tbl-snakes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">svl</th>
<th style="text-align: center;">mass</th>
<th style="text-align: center;">region</th>
<th style="text-align: center;">color</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">west</td>
<td style="text-align: center;">schwarz</td>
</tr>
<tr class="even">
<td style="text-align: center;">45</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">west</td>
<td style="text-align: center;">schwarz</td>
</tr>
<tr class="odd">
<td style="text-align: center;">39</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">west</td>
<td style="text-align: center;">rot</td>
</tr>
<tr class="even">
<td style="text-align: center;">51</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">nord</td>
<td style="text-align: center;">rot</td>
</tr>
<tr class="odd">
<td style="text-align: center;">52</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">nord</td>
<td style="text-align: center;">rot</td>
</tr>
<tr class="even">
<td style="text-align: center;">57</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">nord</td>
<td style="text-align: center;">blau</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">nord</td>
<td style="text-align: center;">blau</td>
</tr>
<tr class="even">
<td style="text-align: center;">49</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">nord</td>
<td style="text-align: center;">blau</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Wir wollen uns nun einmal anschauen, wie ein Modell in R sich zusammensetzt. Je nachdem welche Spalte <span class="math inline">\(x\)</span> wir verwenden um den Zusammenhang zum <span class="math inline">\(y\)</span> aufzuzeigen.</p>
<section id="kontinuierliches-x" class="level3" data-number="39.2.1">
<h3 data-number="39.2.1" class="anchored" data-anchor-id="kontinuierliches-x"><span class="header-section-number">39.2.1</span> Kontinuierliches <span class="math inline">\(x\)</span></h3>
<p>Im ersten Schritt wollen wir uns einmal das Modell mit einem kontinuierlichen <span class="math inline">\(x\)</span> anschauen. Daher bauen wir uns ein lineares Modell mit der Variable <code>mass</code>. Wir erinnern uns, dass <code>mass</code> eine kontinuierliche Variable ist, da wir hier nur Zahlen in der Spalte finden. Die Funktion <code>model.matrix()</code> gibt uns die Modellmatrix wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(svl <span class="sc">~</span> mass, <span class="at">data =</span> snake_tbl) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  `(Intercept)`  mass
          &lt;dbl&gt; &lt;dbl&gt;
1             1     6
2             1     8
3             1     5
4             1     7
5             1     9
6             1    11
7             1    12
8             1    10</code></pre>
</div>
</div>
<p>In der ersten Spalte ist der Intercept angegeben, danach folgt dann die Spalte <code>mass</code> als kontinuierliche Variable.</p>
<p>Wir können die Modellmatrix auch mathematisch schreiben und die <span class="math inline">\(y\)</span> Spalte für das Outcome <code>svl</code> ergänzen. Eben so ergänzen wir die <span class="math inline">\(\beta\)</span>-Werte als mögliche Koeefizienten aus der linearen Regression sowie die Residuen als Abweichung von der gefitteten Gerade.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  1 &amp; 6 \\
  1 &amp; 8 \\
  1 &amp; 5 \\
  1 &amp; 7 \\
  1 &amp; 9 \\
  1 &amp; 11\\
  1 &amp; 12\\
  1 &amp; 10\\
\end{pmatrix}
\times
  \begin{pmatrix}
  \beta_0 \\
  \beta_{mass}
\end{pmatrix} +
  \begin{pmatrix}
  \epsilon_1 \\
  \epsilon_2 \\
  \epsilon_3 \\
  \epsilon_4 \\
  \epsilon_5 \\
  \epsilon_6 \\
  \epsilon_7 \\
  \epsilon_8 \\
\end{pmatrix}
\]</span></p>
<p>Jetzt brauche wir die Koeffizienten aus dem linearen Modell, welches wir wie folgt mit der Funktion <code>lm()</code> fitten. Wir nutzen dann die Funktion <code>coef()</code> um uns die Koeffizienten aus dem Objekt <code>fit_1</code> wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(svl <span class="sc">~</span> mass, <span class="at">data =</span> snake_tbl) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        mass 
      26.71        2.61 </code></pre>
</div>
</div>
<p>Die Funktion <code>residuals()</code> gibt uns die Residuen der Geraden aus dem Objekt <code>fit_1</code> wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5     6     7     8 
-2.36 -2.57 -0.75  6.04  1.82  1.61  0.00 -3.79 </code></pre>
</div>
</div>
<p>Wir können jetzt die Koeffizienten in die Modellmatrix ergänzen. Wir haben den Intercept mit <span class="math inline">\(\beta_0 = 26.71\)</span> geschätzt. Weiter ergänzen wir die Koeffizienten aus dem linearen Modell für <code>mass</code> mit <span class="math inline">\(\beta_{mass}=2.61\)</span>. Ebenfalls setzen wir Werte für die Residuen für jede der Beobachtungen in die Gleichung ein. Wir erhalten dann folgende ausgefüllte Gleichung mit den Matrixen.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  26.71 &amp; \phantom{0}6 \cdot 2.61\\
  26.71 &amp; \phantom{0}8 \cdot 2.61\\
  26.71 &amp; \phantom{0}5 \cdot 2.61\\
  26.71 &amp; \phantom{0}7 \cdot 2.61\\
  26.71 &amp; \phantom{0}9 \cdot 2.61\\
  26.71 &amp; 11\cdot 2.61\\
  26.71 &amp; 12\cdot 2.61\\
  26.71 &amp; 10\cdot 2.61\\
\end{pmatrix}
  +
  \begin{pmatrix}
  -2.36\\
  -2.57\\
  -0.75 \\
  +6.04\\
  +1.82\\
  +1.61\\
  \phantom{+}0.00\\
  -3.79\\
\end{pmatrix}
\]</span></p>
<p>Wir können jetzt diese gewaltige Sammlung an Matrixen einmal auflösen. Steht denn nun wirklich rechts das Gleiche wie links von der Gleichung? Wir bauen uns die Zahlen von der rechten Seite der Gleichung einmal in R nach und schauen auf das Ergebnis. Wie du siehst ergänzen wir hier noch eine Reihe von <span class="math inline">\(+\)</span> um den Intercept mit der Steigung zu verbinden. Steht ja auch so in der Gleichung des linearen Modells drin, alles wird mit einem <span class="math inline">\(+\)</span> miteinander verbunden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fl">26.71</span> <span class="sc">+</span>  <span class="dv">6</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">-</span> <span class="fl">2.36</span>,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span>  <span class="dv">8</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">-</span> <span class="fl">2.57</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span>  <span class="dv">5</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">-</span> <span class="fl">0.75</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span>  <span class="dv">7</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">+</span> <span class="fl">6.04</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span>  <span class="dv">9</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">+</span> <span class="fl">1.82</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span> <span class="dv">11</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">+</span> <span class="fl">1.61</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span> <span class="dv">12</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">+</span> <span class="fl">0.00</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fl">26.71</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">*</span><span class="fl">2.61</span> <span class="sc">-</span> <span class="fl">3.79</span>) <span class="sc">|&gt;</span> <span class="fu">round</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40 45 39 51 52 57 58 49</code></pre>
</div>
</div>
<p>Oh ha! Die Zahlen, die wir rauskriegen, sind die gleichen Werte die unser Outcome <span class="math inline">\(y\)</span> hat. Das heißt, die ganze Sache hat funktioniert.</p>
</section>
<section id="kategorielles-x-mit-2-leveln" class="level3" data-number="39.2.2">
<h3 data-number="39.2.2" class="anchored" data-anchor-id="kategorielles-x-mit-2-leveln"><span class="header-section-number">39.2.2</span> Kategorielles <span class="math inline">\(x\)</span> mit 2 Leveln</h3>
<p>Im diesem Schritt wollen wir uns einmal das Modell mit einem kategoriellen <span class="math inline">\(x\)</span> mit 2 Leveln anschauen. Wir bauen uns ein Modell mit der Variable <code>region``. Die Funktion</code>model.matrix()` gibt uns die Modelmatrix wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(svl <span class="sc">~</span> region, <span class="at">data =</span> snake_tbl) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  `(Intercept)` regionnord
          &lt;dbl&gt;      &lt;dbl&gt;
1             1          0
2             1          0
3             1          0
4             1          1
5             1          1
6             1          1
7             1          1
8             1          1</code></pre>
</div>
</div>
<p>In der ersten Spalte ist der Intercept angegeben, danach folgt dann die Spalte <code>regionnord</code>. In dieser Spalte steht die Dummykodierung für die Variable <code>region</code>. Die ersten drei Schlangen kommen nicht aus der Region <code>nord</code> und werden deshalb mit einen Wert von 0 versehen. Die nächsten vier Schlangen kommen aus der Region <code>nord</code> und erhalten daher eine 1 in der Spalte.</p>
<p>Wir können die Modellmatrix auch mathematisch schreiben und die <span class="math inline">\(y\)</span> Spalte für das Outcome <code>svl</code> ergänzen. Eben so ergänzen wir die <span class="math inline">\(\beta\)</span>-Werte als mögliche Koeefizienten aus der linearen Regression sowie die Residuen als Abweichung von der gefitteten Gerade.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  1 &amp;  0  \\
  1 &amp;  0 \\
  1 &amp;  0\\
  1 &amp;  1\\
  1 &amp;  1 \\
  1 &amp;  1 \\
  1 &amp;  1 \\
  1 &amp;  1 \\
\end{pmatrix}
\times
  \begin{pmatrix}
  \beta_0 \\
  \beta^{region}_{nord} \\
\end{pmatrix} +
  \begin{pmatrix}
  \epsilon_1 \\
  \epsilon_2 \\
  \epsilon_3 \\
  \epsilon_4 \\
  \epsilon_5 \\
  \epsilon_6 \\
  \epsilon_7 \\
  \epsilon_8 \\
\end{pmatrix}
\]</span></p>
<p>Jetzt brauche wir die Koeffizienten aus dem linearen Modell, welches wir wie folgt fitten. Wir nutzen dann die Funktion <code>coef()</code> um uns die Koeffizienten wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(svl <span class="sc">~</span> region, <span class="at">data =</span> snake_tbl) </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)  regionnord 
      41.33       12.07 </code></pre>
</div>
</div>
<p>Die Funktion <code>residuals()</code> gibt uns die Residuen der Geraden aus dem Objekt <code>fit_2</code> wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5     6     7     8 
-1.33  3.67 -2.33 -2.40 -1.40  3.60  4.60 -4.40 </code></pre>
</div>
</div>
<p>Wir können jetzt die Koeffizienten ergänzen mit <span class="math inline">\(\beta_0 = 41.33\)</span> für den Intercept. Weiter ergänzen wir die Koeffizienten für die Region und das Level <code>nord</code> mit <span class="math inline">\(\beta^{region}_{nord} = 12.07\)</span>. Ebenfalls setzen wir Werte für die Residuen für jede der Beobachtungen in die Gleichung ein.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  41.33 &amp; 0 \cdot 12.07  \\
  41.33 &amp; 0 \cdot 12.07  \\
  41.33 &amp; 0 \cdot 12.07  \\
  41.33 &amp; 1 \cdot 12.07  \\
  41.33 &amp; 1 \cdot 12.07  \\
  41.33 &amp; 1 \cdot 12.07  \\
  41.33 &amp; 1 \cdot 12.07  \\
  41.33 &amp; 1 \cdot 12.07  \\
\end{pmatrix} +
  \begin{pmatrix}
  -1.33\\
  +3.67 \\
  -2.33 \\
  -2.40 \\
  -1.40 \\
  +3.60 \\
  +4.60 \\
  -4.40 \\
\end{pmatrix}
\]</span></p>
<p>Wir können jetzt diese gewaltige Sammlung an Matrixen einmal auflösen. Steht denn nun wirklich rechts das Gleiche wie links von der Gleichung? Wir bauen uns die Zahlen von der rechten Seite der Gleichung einmal in R nach und schauen auf das Ergebnis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">-</span> <span class="fl">1.33</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">+</span> <span class="fl">3.67</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">-</span> <span class="fl">2.33</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">-</span> <span class="fl">2.40</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">-</span> <span class="fl">1.40</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">+</span> <span class="fl">3.60</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">+</span> <span class="fl">4.60</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fl">41.33</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">12.07</span> <span class="sc">-</span> <span class="fl">4.40</span>) <span class="sc">|&gt;</span> <span class="fu">round</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40 45 39 51 52 57 58 49</code></pre>
</div>
</div>
<p>Die Zahlen, die wir rauskriegen, sind die gleichen Werte die unser Outcome <span class="math inline">\(y\)</span> hat.</p>
</section>
<section id="kategorielles-x-mit-2-leveln-1" class="level3" data-number="39.2.3">
<h3 data-number="39.2.3" class="anchored" data-anchor-id="kategorielles-x-mit-2-leveln-1"><span class="header-section-number">39.2.3</span> Kategorielles <span class="math inline">\(x\)</span> mit &gt;2 Leveln</h3>
<p>Im diesem Schritt wollen wir uns einmal das Modell mit einem kategoriellen <span class="math inline">\(x\)</span> mit &gt;2 Leveln anschauen. Wir bauen uns ein Modell mit der Variable <code>color</code>. Die Funktion <code>model.matrix()</code> gibt uns die Modelmatrix wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(svl <span class="sc">~</span> color, <span class="at">data =</span> snake_tbl) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  `(Intercept)` colorrot colorblau
          &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1             1        0         0
2             1        0         0
3             1        1         0
4             1        1         0
5             1        1         0
6             1        0         1
7             1        0         1
8             1        0         1</code></pre>
</div>
</div>
<p>In der ersten Spalte ist der Intercept angegeben, danach folgt dann die Spalten für <code>color</code>. Die Spalten <code>colorrot</code> und <code>colorblau</code> geben jeweils an, ob die Schlange das Level <code>rot</code> hat oder <code>blau</code> oder keins von beiden. Wenn die Schlange weder rot noch blau ist, dann sind beide Spalten mit einer 0 versehen. Dann ist die Schlange schwarz.</p>
<p>Wir können die Modellmatrix auch mathematisch schreiben und die <span class="math inline">\(y\)</span> Spalte für das Outcome <code>svl</code> ergänzen. Eben so ergänzen wir die <span class="math inline">\(\beta\)</span>-Werte als mögliche Koeefizienten aus der linearen Regression sowie die Residuen als Abweichung von der gefitteten Gerade.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  1 &amp; 0 &amp; 0 \\
  1 &amp; 0 &amp; 0\\
  1 &amp; 1 &amp; 0\\
  1 &amp; 1 &amp; 0\\
  1 &amp; 1 &amp; 0\\
  1 &amp; 0 &amp; 1\\
  1 &amp; 0 &amp; 1\\
  1 &amp; 0 &amp; 1\\
\end{pmatrix}
\times
  \begin{pmatrix}
  \beta_0 \\
  \beta^{color}_{rot} \\
  \beta^{color}_{blau} \\
\end{pmatrix} +
  \begin{pmatrix}
  \epsilon_1 \\
  \epsilon_2 \\
  \epsilon_3 \\
  \epsilon_4 \\
  \epsilon_5 \\
  \epsilon_6 \\
  \epsilon_7 \\
  \epsilon_8 \\
\end{pmatrix}
\]</span></p>
<p>Jetzt brauche wir die Koeffizienten aus dem linearen Modell, welches wir wie folgt fitten. Wir nutzen dann die Funktion <code>coef()</code> um uns die Koeffizienten wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fit_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(svl <span class="sc">~</span> color, <span class="at">data =</span> snake_tbl) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>fit_3 <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)    colorrot   colorblau 
      42.50        4.83       12.17 </code></pre>
</div>
</div>
<p>Die Funktion <code>residuals()</code> gibt uns die Residuen der Geraden aus dem Objekt <code>fit_3</code> wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fit_3 <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5     6     7     8 
-2.50  2.50 -8.33  3.67  4.67  2.33  3.33 -5.67 </code></pre>
</div>
</div>
<p>Wir können jetzt die Koeffizienten ergänzen mit <span class="math inline">\(\beta_0 = 25\)</span> für den Intercept. Weiter ergänzen wir die Koeffizienten für die Farbe und das Level <code>rot</code> mit <span class="math inline">\(\beta^{color}_{rot} = 4.83\)</span> und für die Farbe und das Level <code>blau</code> mit <span class="math inline">\(\beta^{color}_{blau} = 12.17\)</span>. Ebenfalls setzen wir Werte für die Residuen für jede der Beobachtungen in die Gleichung ein.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  42.50 &amp; 0 \cdot 4.83&amp; 0 \cdot 12.17 \\
  42.50 &amp; 0 \cdot 4.83&amp; 0 \cdot 12.17\\
  42.50 &amp; 1 \cdot 4.83&amp; 0 \cdot 12.17\\
  42.50 &amp; 1 \cdot 4.83&amp; 0 \cdot 12.17\\
  42.50 &amp; 1 \cdot 4.83&amp; 0 \cdot 12.17\\
  42.50 &amp; 0 \cdot 4.83&amp; 1 \cdot 12.17\\
  42.50 &amp; 0 \cdot 4.83&amp; 1 \cdot 12.17\\
  42.50 &amp; 0 \cdot 4.83&amp; 1 \cdot 12.17\\
\end{pmatrix} +
  \begin{pmatrix}
  -2.50 \\
  +2.50 \\
  -8.33 \\
  +3.67 \\
  +4.67 \\
  +2.33 \\
  +3.33 \\
  -5.67 \\
\end{pmatrix}
\]</span></p>
<p>Wir können jetzt diese gewaltige Sammlung an Matrixen einmal auflösen. Steht denn nun wirklich rechts das Gleiche wie links von der Gleichung? Wir bauen uns die Zahlen von der rechten Seite der Gleichung einmal in R nach und schauen auf das Ergebnis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">-</span> <span class="fl">2.50</span>,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">+</span> <span class="fl">2.50</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">-</span> <span class="fl">8.33</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">+</span> <span class="fl">3.67</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">+</span> <span class="fl">4.67</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">+</span> <span class="fl">2.33</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">+</span> <span class="fl">3.33</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fl">42.50</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">4.83</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*-</span><span class="fl">12.17</span> <span class="sc">-</span> <span class="fl">5.67</span>) <span class="sc">|&gt;</span> <span class="fu">round</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40 45 39 51 52 33 34 25</code></pre>
</div>
</div>
<p>Die Zahlen, die wir rauskriegen, sind die gleichen Werte die unser Outcome <span class="math inline">\(y\)</span> hat.</p>
</section>
<section id="das-volle-modell" class="level3" data-number="39.2.4">
<h3 data-number="39.2.4" class="anchored" data-anchor-id="das-volle-modell"><span class="header-section-number">39.2.4</span> Das volle Modell</h3>
<p>Im letzten Schritt wollen wir uns einmal das volle Modell anschauen. Wir bauen uns ein Modell mit allen Variablen in dem Datensatz <code>snake_tbl</code>. Die Funktion <code>model.matrix()</code> gibt uns die Modelmatrix wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(svl <span class="sc">~</span> mass <span class="sc">+</span> region <span class="sc">+</span> color, <span class="at">data =</span> snake_tbl) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>() </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  `(Intercept)`  mass regionnord colorrot colorblau
          &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1             1     6          0        0         0
2             1     8          0        0         0
3             1     5          0        1         0
4             1     7          1        1         0
5             1     9          1        1         0
6             1    11          1        0         1
7             1    12          1        0         1
8             1    10          1        0         1</code></pre>
</div>
</div>
<p>In der ersten Spalte ist der Intercept angegeben, danach folgt dann die Spalte <code>mass</code> als kontenuierliche Variable. In der Spalte <code>regionnord</code> steht die Dummykodierung für die Variable <code>region</code>. Die ersten drei Schlangen kommen nicht aus der Region <code>nord</code> und werden deshalb mit einen Wert von 0 versehen. Die nächsten vier Schlangen kommen aus der Region <code>nord</code> und erhalten daher eine 1 in der Spalte. Die nächsten beiden Spalten sind etwas komplizierter. Die Spalten <code>colorrot</code> und <code>colorblau</code> geben jeweils an, ob die Schlange das Level <code>rot</code> hat oder <code>blau</code> oder keins von beiden. Wenn die Schlange weder rot noch blau ist, dann sind beide Spalten mit einer 0 versehen. Dann ist die Schlange schwarz.</p>
<p>Wir können die Modellmatrix auch mathematisch schreiben und die <span class="math inline">\(y\)</span> Spalte für das Outcome <code>svl</code> ergänzen. Eben so ergänzen wir die <span class="math inline">\(\beta\)</span>-Werte als mögliche Koeefizienten aus der linearen Regression sowie die Residuen als Abweichung von der gefitteten Gerade.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  1 &amp; 6 &amp; 0 &amp; 0 &amp; 0 \\
  1 &amp; 8 &amp; 0 &amp; 0 &amp; 0\\
  1 &amp; 5 &amp; 0 &amp; 1 &amp; 0\\
  1 &amp; 7 &amp; 1 &amp; 1 &amp; 0\\
  1 &amp; 9 &amp; 1 &amp; 1 &amp; 0\\
  1 &amp; 11&amp; 1 &amp; 0 &amp; 1\\
  1 &amp; 12&amp; 1 &amp; 0 &amp; 1\\
  1 &amp; 10&amp; 1 &amp; 0 &amp; 1\\
\end{pmatrix}
\times
  \begin{pmatrix}
  \beta_0 \\
  \beta_{mass} \\
  \beta^{region}_{nord} \\
  \beta^{color}_{rot} \\
  \beta^{color}_{blau} \\
\end{pmatrix} +
  \begin{pmatrix}
  \epsilon_1 \\
  \epsilon_2 \\
  \epsilon_3 \\
  \epsilon_4 \\
  \epsilon_5 \\
  \epsilon_6 \\
  \epsilon_7 \\
  \epsilon_8 \\
\end{pmatrix}
\]</span></p>
<p>Jetzt brauche wir die Koeffizienten aus dem linearen Modell, welches wir wie folgt fitten. Wir nutzen dann die Funktion <code>coef()</code> um uns die Koeffizienten wiedergeben zu lassen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>fit_4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(svl <span class="sc">~</span> mass <span class="sc">+</span> region <span class="sc">+</span> color, <span class="at">data =</span> snake_tbl) </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>fit_4 <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        mass  regionnord    colorrot   colorblau 
      25.00        2.50        5.00        1.50       -2.83 </code></pre>
</div>
</div>
<p>Die Funktion <code>residuals()</code> gibt uns die Residuen der Geraden aus dem Objekt <code>fit_4</code> wieder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit_4 <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5     6     7     8 
 0.00  0.00  0.00  2.00 -2.00  2.33  0.83 -3.17 </code></pre>
</div>
</div>
<p>Wir können jetzt die Koeffizienten ergänzen mit <span class="math inline">\(\beta_0 = 25\)</span> für den Intercept. Weiter ergänzen wir die Koeffizienten für <code>mass</code> mit <span class="math inline">\(\beta_{mass}=2.5\)</span>, für Region und das Level <code>nord</code> mit <span class="math inline">\(\beta^{region}_{nord} = 5\)</span>, für die Farbe und das Level <code>rot</code> mit <span class="math inline">\(\beta^{color}_{rot} = 1.5\)</span> und für die Farbe und das Level <code>blau</code> mit <span class="math inline">\(\beta^{color}_{blau} = -2.83\)</span>. Ebenfalls setzen wir Werte für die Residuen für jede der Beobachtungen in die Gleichung ein.</p>
<p><span class="math display">\[
\begin{pmatrix}
  40 \\
  45 \\
  39 \\
  50 \\
  52 \\
  57 \\
  58 \\
  59 \\
\end{pmatrix}
=
  \begin{pmatrix}
  25 &amp; \phantom{0}6 \cdot 2.5 &amp; 0 \cdot 5 &amp; 0 \cdot 1.5&amp; 0 \cdot -2.83 \\
  25 &amp; \phantom{0}8 \cdot 2.5 &amp; 0 \cdot 5 &amp; 0 \cdot 1.5&amp; 0 \cdot -2.83\\
  25 &amp; \phantom{0}5 \cdot 2.5 &amp; 0 \cdot 5 &amp; 1 \cdot 1.5&amp; 0 \cdot -2.83\\
  25 &amp; \phantom{0}7 \cdot 2.5 &amp; 1 \cdot 5 &amp; 1 \cdot 1.5&amp; 0 \cdot -2.83\\
  25 &amp; \phantom{0}9 \cdot 2.5 &amp; 1 \cdot 5 &amp; 1 \cdot 1.5&amp; 0 \cdot -2.83\\
  25 &amp; 11\cdot 2.5 &amp; 1 \cdot 5 &amp; 0 \cdot 1.5&amp; 1 \cdot -2.83\\
  25 &amp; 12\cdot 2.5 &amp; 1 \cdot 5 &amp; 0 \cdot 1.5&amp; 1 \cdot -2.83\\
  25 &amp; 10\cdot 2.5 &amp; 1 \cdot 5 &amp; 0 \cdot 1.5&amp; 1 \cdot -2.83\\
\end{pmatrix} +
  \begin{pmatrix}
  \phantom{+}0.00 \\
  \phantom{+}0.00 \\
  \phantom{+}0.00 \\
  +2.00 \\
  -2.00 \\
  +2.33 \\
  +0.83 \\
  -3.17 \\
\end{pmatrix}
\]</span></p>
<p>Wir können jetzt diese gewaltige Sammlung an Matrixen einmal auflösen. Steht denn nun wirklich rechts das Gleiche wie links von der Gleichung? Wir bauen uns die Zahlen von der rechten Seite der Gleichung einmal in R nach und schauen auf das Ergebnis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">25</span> <span class="sc">+</span>  <span class="dv">6</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">+</span> <span class="fl">0.00</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span>  <span class="dv">8</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">+</span> <span class="fl">0.00</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span>  <span class="dv">5</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">+</span> <span class="fl">0.00</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span>  <span class="dv">7</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">+</span> <span class="fl">2.00</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span>  <span class="dv">9</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">-</span> <span class="fl">2.00</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span> <span class="dv">11</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">+</span> <span class="fl">2.33</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span> <span class="dv">12</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">+</span> <span class="fl">0.83</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">*</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*-</span><span class="fl">2.83</span> <span class="sc">-</span> <span class="fl">3.17</span>) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40 45 39 51 52 57 58 49</code></pre>
</div>
</div>
<p>Die Zahlen, die wir rauskriegen, sind die gleichen Werte die unser Outcome <span class="math inline">\(y\)</span> hat. Was haben wir gelernt?</p>
<ul>
<li>In einem Modell gibt es immer ein Faktorlevel weniger als ein Faktor Level hat. Die Information des <em>alphanumerisch</em> ersten Levels steckt dann mit in dem Intercept.</li>
<li>In einem Modell geht eine kontinuierliche Variable als eine Spalte mit ein.</li>
<li>In einem Modell gibt es immer nur eine Spalte für die Residuen und damit nur eine Residue für jede Beobachtung, egal wie viele Variablen ein Modell hat.</li>
</ul>
</section>
</section>
<section id="sec-interpret-x" class="level2" data-number="39.3">
<h2 data-number="39.3" class="anchored" data-anchor-id="sec-interpret-x"><span class="header-section-number">39.3</span> Interpretation von <span class="math inline">\(x\)</span></h2>
<p>Wi interpretiee wir nun das Ergebnis einer linearen Regression? Zum einen nutzen wir häufig das Modell nur um das Modell dann weiter in einem multiplen Vergleich zu nutzen. Hier wollen wir uns jetzt aber wirklich die Koeffizienten aus einer multiplen linearen Regression anschauen udn diese Zahlen einmal interpretieren. Wichtig ist, dass wir ein normalverteiltes <span class="math inline">\(y\)</span> vorliegen haben und uns verschiedene Formen des <span class="math inline">\(x\)</span> anschauen. Wir betrachten ein kontinuierliches <span class="math inline">\(x\)</span>, ein kategorielles <span class="math inline">\(x\)</span> mit zwei Leveln und ein kategorielles <span class="math inline">\(x\)</span> mit drei oder mehr Leveln.</p>
<section id="sec-interpret-x-cont" class="level3" data-number="39.3.1">
<h3 data-number="39.3.1" class="anchored" data-anchor-id="sec-interpret-x-cont"><span class="header-section-number">39.3.1</span> Kontinuierliches <span class="math inline">\(x\)</span></h3>
<p>Bauen wir uns also einmal einen Datensatz mit einem kontinuierlichen <span class="math inline">\(x\)</span> und einem normalverteilten <span class="math inline">\(y\)</span>. Unser <span class="math inline">\(x\)</span> soll von 1 bis 7 laufen. Wir erschaffen uns das <span class="math inline">\(y\)</span> indem wir das <span class="math inline">\(x\)</span> mit 1.5 multiplizieren, den <span class="math inline">\(y\)</span>-Achsenabschnitt von 5 addieren und einen zufälligen Fehler aus einer Normalverteilung mit <span class="math inline">\(\mathcal{N}(0, 1)\)</span> aufaddieren. Wir haben also eine klassische Regressionsgleichung mit <span class="math inline">\(y = 5 + 1.5 \cdot x\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20137937</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>cont_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">7</span>, <span class="at">by =</span> <span class="dv">1</span>),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> <span class="dv">5</span> <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(x), <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>cont_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
      x     y
  &lt;dbl&gt; &lt;dbl&gt;
1     1  5.93
2     2  8.06
3     3  8.95
4     4 12.1 
5     5 11.9 
6     6 14.9 
7     7 16.3 </code></pre>
</div>
</div>
<p>Wenn wir keinen Fehler addieren würden, dann hätten wir auch eine Linie von Punkten wie an einer Perlschnur aufgereiht. Dann wäre das <span class="math inline">\(R^2 = 1\)</span> und wir hätten keine Varianz in den Daten. Das ist aber in einem biologischen Setting nicht realistisch, dass unser <span class="math inline">\(y\)</span> vollständig von <span class="math inline">\(x\)</span> erklärt wird.</p>
<p>Schauen wir uns nochmal die Modellmatrix an. Hier erwartet uns aber keine Überraschung. Wir schätzen den Intercept und dann kommt der Wert für jedes <span class="math inline">\(x\)</span> in der zweiten Spalte.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(y <span class="sc">~</span> x, <span class="at">data =</span> cont_tbl)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) x
1           1 1
2           1 2
3           1 3
4           1 4
5           1 5
6           1 6
7           1 7
attr(,"assign")
[1] 0 1</code></pre>
</div>
</div>
<p>Im Folgenden schätzen wir jetzt das lineare Modell um die Koeffizienten der Geraden zu erhalten. Wir nutzen die Funktion <code>model_parameter()</code> aus dem R Paket <code>{parameters}</code> für die Ausgabe der Koeffizienten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> cont_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Parameter, Coefficient)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   | Coefficient
-------------------------
(Intercept) |        4.32
x           |        1.71</code></pre>
</div>
</div>
<p>Wir erhalten einen Intercept von <span class="math inline">\(4.32\)</span> und eine Steigung von <span class="math inline">\(x\)</span> mit <span class="math inline">\(1.71\)</span>. Wichtig nochmal, wir haben uns hier zufällige Zahlen erstellen lassen. Wenn du oben den Fehler rausnimmst, dann erhälst du auch die exakten Zahlen für den Intercept und die Steigung von <span class="math inline">\(x\)</span> wieder. Wir sehen also, wenn wir ein kontinuierliches <span class="math inline">\(x\)</span> haben, dann können wir das <span class="math inline">\(x\)</span> in dem Sinne einr Steigung interpretieren. Steigt das <span class="math inline">\(x\)</span> um 1 Einheit an, so erhöht sich das <span class="math inline">\(y\)</span> um den Wert der Steigung von <span class="math inline">\(x\)</span>.</p>
<p>In <a href="#fig-stat-modeling-basic-00" class="quarto-xref">Abbildung&nbsp;<span>39.1</span></a> sehen wir den Zusammenhang nochmal graphisch dargestellt. Wir sehen, dass wir die voreingestellten Parameter von <span class="math inline">\(\beta_0 = 5\)</span> und <span class="math inline">\(\beta_1 = 1.5\)</span> fast treffen.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-stat-modeling-basic-00" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-modeling-basic-00-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-basic-00-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-basic-00-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-modeling-basic-00-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;39.1— Graphische Darstellung der Interpretation von einem kontinuierlichen <span class="math inline">\(x\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-interpret-x-cat2" class="level3" data-number="39.3.2">
<h3 data-number="39.3.2" class="anchored" data-anchor-id="sec-interpret-x-cat2"><span class="header-section-number">39.3.2</span> Kategorielles <span class="math inline">\(x\)</span> mit 2 Leveln</h3>
<p>Etwas anders wird der Fall wenn wir ein kategorielles <span class="math inline">\(x\)</span> mit 2 Leveln vorliegen haben. Wir bauen faktisch zwei Punktetürme an zwei <span class="math inline">\(x\)</span> Positionen auf. Dennoch können wir durch diese Punkte eine Gerade zeichnen. Bauen wir uns erst die Daten mit der Funktion <code>rnorm()</code>. Wir haben zwei Gruppen vorliegen, die Gruppe A hat sieben Beobachtungen und einen Mittelwert von 10. Die Gruppe B hat ebenfalls sieben Beobchatungen und einen Mittelwert von 15. Der Effekt zwischen den beiden Gruppen A und B ist die Mittelwertsdifferenz <span class="math inline">\(\Delta_{A-B}\)</span> ist somit 5. Wir erhlalten dann folgenden Datensatz wobei die Werte der Gruppe A um die 10 streuen und die Werte der Gruppe B um die 15 streuen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20339537</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>cat_two_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">A =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">7</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">B =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">7</span>, <span class="at">mean =</span> <span class="dv">15</span>, <span class="at">sd =</span> <span class="dv">1</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(<span class="at">key =</span> x, <span class="at">value =</span> y) <span class="sc">|&gt;</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">as_factor</span>(x))</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>cat_two_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 2
   x         y
   &lt;fct&gt; &lt;dbl&gt;
 1 A     10.0 
 2 A     10.8 
 3 A     10.7 
 4 A     11.0 
 5 A      9.25
 6 A      8.98
 7 A      9.71
 8 B     15.1 
 9 B     16.0 
10 B     14.5 
11 B     15.1 
12 B     14.2 
13 B     16.8 
14 B     15.6 </code></pre>
</div>
</div>
<p>Wir wollen uns wieder die Modellmatrix einmal anschauen. Wir sehen hier schon einen Unterschied. Zum einen sehen wir, dass der Intercept für alle Beobachtungen geschätzt wird und in der zweiten Spalte nur <code>xB</code> steht. Somit werden in der zweiten Spalte nur die Beobachtungen in der Gruppe B berücksichtigt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(y <span class="sc">~</span> x, <span class="at">data =</span> cat_two_tbl)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) xB
1            1  0
2            1  0
3            1  0
4            1  0
5            1  0
6            1  0
7            1  0
8            1  1
9            1  1
10           1  1
11           1  1
12           1  1
13           1  1
14           1  1
attr(,"assign")
[1] 0 1
attr(,"contrasts")
attr(,"contrasts")$x
[1] "contr.treatment"</code></pre>
</div>
</div>
<p>Wir rechnen einmal das lineare Modell und lassen uns überraschen was als Ergebnis herauskommt. Wir nutzen die Funktion <code>model_parameter()</code> aus dem R Paket <code>{parameters}</code> für die Ausgabe der Koeffizienten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> cat_two_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Parameter, Coefficient)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   | Coefficient
-------------------------
(Intercept) |       10.07
xB          |        5.27</code></pre>
</div>
</div>
<p>Nun erhalten wir als den Intercept 10.07 und die Steigung <code>xB</code> mit 5.27 zurück. Wir sehen, der Intercept ist der Mittelwert der Gruppe A und die das <code>xB</code> ist die Änderung von dem Mittelwert A zu dem Mittelwert B. Wir erhalten die Mittelwertsdifferenz <span class="math inline">\(\Delta_{A-B}\)</span> von 5.27 zurück. In <a href="#tbl-cat-2" class="quarto-xref">Tabelle&nbsp;<span>39.2</span></a> siehst du den Zusammenhang von den Faktorleveln A und B, den jeweiligen Mittelwerte der Level sowie die Differenz zum Mittel von dem ersten Level A.</p>
<div class="cell">
<div id="tbl-cat-2" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cat-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;39.2— Zusammenhang von den Mittelwerten der Level des Faktores <span class="math inline">\(x\)</span> und deren Differenz zu Level A.
</figcaption>
<div aria-describedby="tbl-cat-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Factor x</th>
<th style="text-align: center;">Mean of level</th>
<th style="text-align: center;">Difference to level A</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">10.07</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">15.33</td>
<td style="text-align: center;">5.27</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In <a href="#fig-stat-modeling-basic-01" class="quarto-xref">Abbildung&nbsp;<span>39.2</span></a> kannst du nochmal den visuellen Zusammenhang zwischen den einzelnen Beobachtungen und der sich ergebenen Geraden sehen. Die Gerade geht durch die beiden Mittelwerte der Gruppe A und B. Daher ist die Steigung der Mittlwertsunterschied zwischen der Gruppe A und der Gruppe B. Steigt das <span class="math inline">\(x\)</span> um 1 Einheit an, also springt von Gruppe A zu Gruppe B, so erhöht sich das <span class="math inline">\(y\)</span> um den Mittelwertsunterschied <span class="math inline">\(\Delta_{A-B}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-stat-modeling-basic-01" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-modeling-basic-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-basic-01-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-basic-01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-modeling-basic-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;39.2— Graphische Darstellung der Interpretation von einem kategoriellen <span class="math inline">\(x\)</span> mit 2 Leveln.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-interpret-x-cat3" class="level3" data-number="39.3.3">
<h3 data-number="39.3.3" class="anchored" data-anchor-id="sec-interpret-x-cat3"><span class="header-section-number">39.3.3</span> Kategorielles <span class="math inline">\(x\)</span> mit &gt;2 Leveln</h3>
<p>Nachdem wir das Problem der Interpretation von einem kategoriellen <span class="math inline">\(x\)</span> mit zwei Leveln verstanden haben, werden wir uns jetzt den Fall für ein kategoriellen <span class="math inline">\(x\)</span> mit drei oder mehr Leveln anschauen. Wir nutzen hier nur drei Level, da es für vier oder fünf Level gleich abläuft. Du kannst das Datenbeispiel gerne auch noch um eine vierte Gruppe erweitern und schauen was sich da ändert.</p>
<p>Unser Datensatz besteht aus drei Gruppen A, B und C mit den Mittelwerten von 10, 15 und 3. Hierbei ist wichtig, dass wir in der Gruppe C nur einen Mittelwert von 3 haben. Also wir haben <em>keinen</em> linearen Anstieg über die drei Gruppen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20339537</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>cat_three_tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">A =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">7</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">B =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">7</span>, <span class="at">mean =</span> <span class="dv">15</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">C =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">7</span>, <span class="at">mean =</span> <span class="dv">3</span>, <span class="at">sd =</span> <span class="dv">1</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(<span class="at">key =</span> x, <span class="at">value =</span> y) <span class="sc">|&gt;</span> </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">as_factor</span>(x))</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>cat_three_tbl</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
   x         y
   &lt;fct&gt; &lt;dbl&gt;
 1 A     10.0 
 2 A     10.8 
 3 A     10.7 
 4 A     11.0 
 5 A      9.25
 6 A      8.98
 7 A      9.71
 8 B     15.1 
 9 B     16.0 
10 B     14.5 
# ℹ 11 more rows</code></pre>
</div>
</div>
<p>Schauen wir uns einmal die Modellmatrix an. Wir sehen wieder, dass der Intercept über alle Gruppen geschätzt wird und wir Koeffizienten für die Gruppen B und C erhalten. Mit der Modellmatrix wird dann auch das lineare Modell geschätzt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(y <span class="sc">~</span> x, <span class="at">data =</span> cat_three_tbl)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) xB xC
1            1  0  0
2            1  0  0
3            1  0  0
4            1  0  0
5            1  0  0
6            1  0  0
7            1  0  0
8            1  1  0
9            1  1  0
10           1  1  0
11           1  1  0
12           1  1  0
13           1  1  0
14           1  1  0
15           1  0  1
16           1  0  1
17           1  0  1
18           1  0  1
19           1  0  1
20           1  0  1
21           1  0  1
attr(,"assign")
[1] 0 1 1
attr(,"contrasts")
attr(,"contrasts")$x
[1] "contr.treatment"</code></pre>
</div>
</div>
<p>Wir rechnen wieder das Modell mit der Funktion <code>lm()</code>. Wir nutzen die Funktion <code>model_parameter()</code> aus dem R Paket <code>{parameters}</code> für die Ausgabe der Koeffizienten zu erhalten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> cat_three_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Parameter, Coefficient)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   | Coefficient
-------------------------
(Intercept) |       10.07
xB          |        5.27
xC          |       -7.41</code></pre>
</div>
</div>
<p>Wir sehen wieder, dass der Intercept der Mittelwert der Gruppe A ist. Wir hatten einen Mittelwert von 10 für die Gruppe A eingestellt und wir erhalten diesen Wert wieder. Die anderen Koeffizienten sind die Änderung zum Mittelwert von der Gruppe A. In <a href="#tbl-cat-3" class="quarto-xref">Tabelle&nbsp;<span>39.3</span></a> ist der Zusammenhang nochmal für alle Level des Faktors <span class="math inline">\(x\)</span> dargestellt. Wir haben für die Gruppe B einen Mittelwert von 15 und für die Gruppe C einen Mittelwert von 3 eingestellt. Wir erhalten diese Mittelwerte wieder, wenn wir die Differenzen zu dem Intercept bilden.</p>
<div class="cell">
<div id="tbl-cat-3" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cat-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;39.3— Zusammenhang von den Mittelwerten der Level des Faktores <span class="math inline">\(x\)</span> und deren Differenz zu Level A.
</figcaption>
<div aria-describedby="tbl-cat-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Factor x</th>
<th style="text-align: center;">Mean of level</th>
<th style="text-align: center;">Difference to level A</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">10.07</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">15.33</td>
<td style="text-align: center;">5.27</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">2.66</td>
<td style="text-align: center;">-7.41</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Wir sehen den Zusammenhang nochmal in der <a href="#fig-stat-modeling-basic-02" class="quarto-xref">Abbildung&nbsp;<span>39.3</span></a> visualisiert. Wir sehen die Änderung on der Gruppe A zu der Gruppe B sowie die Änderung von der Gruppe A zu der Gruppe C. Die Abbildung ist etwas <em>verwirrend</em> da wir <em>nicht</em> das <span class="math inline">\(x\)</span> um 2 Einheiten erhöhen um auf den Mittelwert von C zu kommen. Wir rechnen sozusagen ausgehend von A die Änderung zu B und C aus. Dabei nehmen wir jedesmal an, dass die Gruppe B und die Gruppe C nur eine Einheit von <span class="math inline">\(x\)</span> von A entfernt ist.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_segment(aes(x = 1, y = 10.1, xend = 2, yend = 10.1 + 5.27), : All aesthetics have length 1, but the data has 21 rows.
ℹ Please consider using `annotate()` or provide this layer with data containing
  a single row.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_segment(aes(x = 1, y = 10.1, xend = 3, yend = 10.1 - 7.41), : All aesthetics have length 1, but the data has 21 rows.
ℹ Please consider using `annotate()` or provide this layer with data containing
  a single row.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-stat-modeling-basic-02" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-modeling-basic-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-basic-02-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="quarto-lightbox-gallery-4"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-basic-02-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-modeling-basic-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;39.3— Graphische Darstellung der Interpretation von einem kategoriellen <span class="math inline">\(x\)</span> mit 3 Leveln.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-confounder" class="level2 page-columns page-full" data-number="39.4">
<h2 data-number="39.4" class="anchored" data-anchor-id="sec-confounder"><span class="header-section-number">39.4</span> Adjustierung für Confounder</h2>
<p>Im folgenden Abschnitt wollen wir einmal auf Confounder eingehen. Was sind Confounder? Zum einen gibt es kein gutes deutsches Wort für Confounder. Du könntest Confounder in etwa mit <em>Verzerrer</em> oder <em>Störfakor</em> übersetzen. Zum Anderen können Confounder nur zuammen mit anderen Vriabln in einer multiplen Regression auftreten. Das heißt, wir brauchen mindestens zwei Variablen in einer Regression. Ein Confounder verursacht einen Effekt, den wir eigentlich nicht so erwartet hätten. Wir wollen eigentlich einen Effekt schätzen, aber der Effekt ist viel größer oder kleiner, da der Effekt eigentlich von einder anderen Variable verursacht oder aber verdeckt wird. Wir können einen Confounder in beide Richtungen haben. Wichtig ist hierbei, das wir eigentlich <em>nicht</em> an dem Effekt des Confounders interessiert sind. Wir wollen uns zum Beispiel den Effekt einer Düngung auf das Trockengewicht anschauen, aber der Effekt den wir beobachten wird durch die unterschiedlichen Pflanzorte verursacht.</p>
<p>Schauen wir uns das ganze mal für das Beispiel des Zusammenhangs von dem Flohgewicht mit der Sprungweite an. Dafür benötigen wir den Datensatz <code>flea_dog_cat_length_weight.csv</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>model_tbl <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">"data/flea_dog_cat_length_weight.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(animal, sex, weight, jump_length) <span class="sc">|&gt;</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal =</span> <span class="fu">as_factor</span>(animal),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex =</span> <span class="fu">as_factor</span>(sex))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In der <a href="#tbl-model-confounder" class="quarto-xref">Tabelle&nbsp;<span>39.4</span></a> ist der Datensatz <code>model_tbl</code> nochmal dargestellt.</p>
<div class="cell">
<div id="tbl-model-confounder" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-confounder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;39.4— Datensatz für die Confounder Adjustierung. Die Variable <code>jump_length</code> ist das <span class="math inline">\(y\)</span> und die Variable <code>weight</code> das <span class="math inline">\(x\)</span> von Interesse.
</figcaption>
<div aria-describedby="tbl-model-confounder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">animal</th>
<th style="text-align: center;">sex</th>
<th style="text-align: center;">weight</th>
<th style="text-align: center;">jump_length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">6.02</td>
<td style="text-align: center;">15.79</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">5.99</td>
<td style="text-align: center;">18.33</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">8.05</td>
<td style="text-align: center;">17.58</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">6.71</td>
<td style="text-align: center;">14.09</td>
</tr>
<tr class="odd">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">6.19</td>
<td style="text-align: center;">18.22</td>
</tr>
<tr class="even">
<td style="text-align: center;">cat</td>
<td style="text-align: center;">male</td>
<td style="text-align: center;">8.18</td>
<td style="text-align: center;">13.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">8.04</td>
<td style="text-align: center;">27.81</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">9.03</td>
<td style="text-align: center;">24.02</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">7.42</td>
<td style="text-align: center;">24.53</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">9.26</td>
<td style="text-align: center;">24.35</td>
</tr>
<tr class="even">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">8.85</td>
<td style="text-align: center;">24.36</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fox</td>
<td style="text-align: center;">female</td>
<td style="text-align: center;">7.89</td>
<td style="text-align: center;">22.13</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Wir können uns jetzt drei verschiedene Modelle anschauen.</p>
<ol type="1">
<li>Das Modell <code>jump_length ~ weight</code>. Wir modellieren die Abhängigkeit von der Sprungweite von dem Gewicht der Flöhe <em>über alle</em> anderen Variablen hinweg.</li>
<li>Das Modell <code>jump_length ~ weight + animal</code>. Wir modellieren die Abhängigkeit von der Sprungweite von dem Gewicht der Flöhe und berücksichtigen die Tierart des Flohes. Ignorieren aber das Geschlecht des Flohes.</li>
<li>Das Modell <code>jump_length ~ weight + animal + sex</code>. Wir modellieren die Abhängigkeit von der Sprungweite von dem Gewicht der Flöhe und berücksichtigen <em>alle</em> Variablen, die wir gemessen haben.</li>
</ol>
<p>Hierbei ist wichtig, dass es natürlich auch Confounder geben kann, die wir gar nicht in den Daten erhoben haben. Also, dass sich Gruppen finden lassen, die wir gar nicht als Variable mit in den Daten erfasst haben. Hier könnte eine Hauptkomponentenanalyse helfen.</p>
<div class="cell page-columns page-full" data-layout-nrow="1" data-layout-align="center">
<div id="fig-stat-modeling-mult-01" class="quarto-layout-panel page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-stat-modeling-mult-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<div class="quarto-layout-row page-full">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-stat-modeling-mult-01" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-stat-modeling-mult-01-1" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-stat-modeling-mult-01-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-mult-01-1.png" class="lightbox page-columns page-full" data-glightbox="description: .lightbox-desc-5" data-gallery="fig-stat-modeling-mult-01"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-mult-01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-stat-modeling-mult-01" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-stat-modeling-mult-01-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) jump_length ~ weight
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-stat-modeling-mult-01" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-stat-modeling-mult-01-2" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-stat-modeling-mult-01-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-mult-01-2.png" class="lightbox page-columns page-full" data-glightbox="description: .lightbox-desc-6" data-gallery="fig-stat-modeling-mult-01"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-mult-01-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-stat-modeling-mult-01" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-stat-modeling-mult-01-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) jump_length ~ weight + animal
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell page-columns page-full" data-ref-parent="fig-stat-modeling-mult-01" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-stat-modeling-mult-01-3" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure page-columns page-full">
<div aria-describedby="fig-stat-modeling-mult-01-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-mult-01-3.png" class="lightbox page-columns page-full" data-glightbox="description: .lightbox-desc-7" data-gallery="fig-stat-modeling-mult-01"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-mult-01-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" data-ref-parent="fig-stat-modeling-mult-01" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-stat-modeling-mult-01-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) jump_length ~ weight + animal + sex
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-modeling-mult-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;39.4— Darstellung des <em>counfounder</em> Effekts anhand des Zusammenhangs der Sprungweite in [cm] und dem Gewicht von Flöhen [mg].
</figcaption>
</figure>
</div>
</div>
<p>In <a href="#fig-stat-modeling-mult-01-1" class="quarto-xref">Abbildung&nbsp;<span>39.4 (a)</span></a> sehen wir die blaue Linie als die Ausgabe von dem Modell <code>jump_length ~ weight</code>. Wir sehen, dass mit dem Anstieg des Gewichtes der Flöhe auch die Sprungweite sich erhöht. Wir würden annehmen, dass wir hier einen signifikanten Unterschied vorliegen haben. Schauen wir uns die Koeffizienten des Modells aus dem <code>lm()</code> einmal an.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(jump_length <span class="sc">~</span> weight, <span class="at">data =</span> model_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter   | Coefficient |   SE |        95% CI | t(598) |      p
------------------------------------------------------------------
(Intercept) |        9.79 | 0.77 | [8.28, 11.30] |  12.73 | &lt; .001
weight      |        1.34 | 0.09 | [1.16,  1.53] |  14.16 | &lt; .001</code></pre>
</div>
</div>
<p>Wir sehen, dass wir einen Effekt des Gewichts auf die Sprungweite von <span class="math inline">\(1.34\)</span> vorliegen haben. Auch ist der Effekt und damit die Steigung signifikant.</p>
<p>Erweitern wir nun das Modell um die Tierart und erhalten die <a href="#fig-stat-modeling-mult-01-2" class="quarto-xref">Abbildung&nbsp;<span>39.4 (b)</span></a>. Zum einen sehen wir, dass der globale Effekt nicht so ganz stimmen kann. Die Tierarten haben alle einen unterschiedlichen starken Effekt von dem Gewicht auf die Sprungweite. Auch hier fitten wir einmal das lineare Modell und schauen uns die Koeffizienten an.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(jump_length <span class="sc">~</span> weight <span class="sc">+</span> animal, <span class="at">data =</span> model_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter    | Coefficient |   SE |       95% CI | t(596) |      p
------------------------------------------------------------------
(Intercept)  |        7.82 | 0.62 | [6.60, 9.03] |  12.64 | &lt; .001
weight       |        1.27 | 0.07 | [1.13, 1.42] |  17.08 | &lt; .001
animal [dog] |        2.62 | 0.26 | [2.12, 3.13] |  10.23 | &lt; .001
animal [fox] |        4.97 | 0.26 | [4.47, 5.48] |  19.38 | &lt; .001</code></pre>
</div>
</div>
<p>Der Effekt des Gewichtes ist hier in etwa gleich geblieben. Wir sehen aber auch, dass die Sprungweite anscheinend bei Hunden und Füchsen höher ist. Daher haben wir hier einen Effekt on der Tierart. Wir adjustieren für den Confoundereffekt durch die Tierart und erhalten einen besseren Effektschätzer für das Gewicht.</p>
<p>In der letzten <a href="#fig-stat-modeling-mult-01-3" class="quarto-xref">Abbildung&nbsp;<span>39.4 (c)</span></a> wollen wir nochmal das Geschlecht der Flöhe mit in das Modell nehmen. Wir sehen, dass in diesem Fall, das Gewicht gar keinen Einfluss mehr auf die Sprungweite hat. Den Effekt des Gewichtes war nur der Effekt des unterschiedlichen Gewichtes der weiblichen und männlichen Flöhe. Schauen wir auch hier nochmal in des Modell.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(jump_length <span class="sc">~</span> weight <span class="sc">+</span> animal <span class="sc">+</span> sex, <span class="at">data =</span> model_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Coefficient =</span> <span class="fu">round</span>(Coefficient, <span class="dv">2</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   | Coefficient |   SE |         95% CI | t(595) |      p
-------------------------------------------------------------------
(Intercept) |       15.42 | 0.59 | [14.27, 16.58] |  26.23 | &lt; .001
weight      |        0.01 | 0.08 | [-0.16,  0.17] |   0.07 | 0.942 
animaldog   |        2.61 | 0.19 | [ 2.23,  2.99] |  13.50 | &lt; .001
animalfox   |        5.19 | 0.19 | [ 4.81,  5.57] |  26.75 | &lt; .001
sexfemale   |        4.89 | 0.23 | [ 4.44,  5.34] |  21.25 | &lt; .001</code></pre>
</div>
</div>
<p>Nun können wir sehen, dass von unserem ursprünglichen Effekt von dem Gewicht auf die Sprungweite nichts mehr übrigbleibt. Wir haben gar keinen Effekt von dem Gewicht auf die Sprungweite vorliegen. Was wir gesehen haben, war der Effekt des Gewichtes der unterschiedlichen Geschlechter. Wenn wir unser Modell für die Confounder <code>animal</code> und <code>sex</code> adjustieren, haben wir einen unverzerrten Schätzer für <code>weight</code>. Wichtig ist nochmal, dafür müssen wir natürlich auch alle variablen erhoben haben. Hätten wir das Geschlecht der Flöhe nicht bestimt, hätten wir hier eventuell einen falschen Schluß getroffen.</p>
</section>
<section id="sec-vif" class="level2" data-number="39.5">
<h2 data-number="39.5" class="anchored" data-anchor-id="sec-vif"><span class="header-section-number">39.5</span> Variance inflation factor (VIF)</h2>
<p>Wenn wir sehr viele Daten erheben, dann kann es sein, dass die Variablen stark miteinander korrelieren. Wir können aber stark mieinander korrelierte Variablen nicht zusammen in ein Modell nehmen. Die Effekte der beiden Variablen würden sich gegenseitig aufheben. Wir hätten eigentlich zwei getrennt signifikante Variablen. Nehmen wir aber beide Variablen mit ins Modell, sind beide Variablen nicht mehr signifikant.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[15,85]">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 15.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/angel_01.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="images/angel_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 85.0%;justify-content: flex-start;">
<blockquote class="blockquote">
<p>Wir kürzen hier stark ab. Wenn du mehr über Variablen in einem Modell wissen willst, gibt es dann in den Kapitel zur Variablen Selektion mehr Informationen. Wenn du nur Outcomes und Blöcke vorliegen hast, dann ist das VIF für dich uninteressant.</p>
</blockquote>
</div>
</div>
</div>
<p>Um Variablen zu finden, die sich sehr ähnlich verhalten, können wir den Variance inflation factor (VIF) nutzen. Wir können den VIF jedoch <em>nicht</em> für kategoriale Daten verwenden. Statistisch gesehen würde es keinen Sinn machen. Die Anwendung ist recht einfach. Wir fitten als erstes unser Modell und dann können wir die Funktion <code>vif()</code> aus dem R Paket <code>{car}</code> verwenden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>gummi_tbl <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/gummibears.xlsx"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> semester <span class="sc">+</span> age <span class="sc">+</span> count_color <span class="sc">+</span> count_bears, <span class="at">data =</span> gummi_tbl)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir sehen im Folgenden das Eregbnis der Funktion <code>vif()</code>. Wenn der berechnete Wert für den VIF größer als 5 ist, dann liegt mit der Variable <em>ein Problem</em> vor. Wir vermuten dann, dass eine andere variable sehr stark mit dieser Variable korreliert. Wir sehen an den Werten keine Aufälligkeiten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   semester         age count_color count_bears 
   1.039437    1.030421    1.095417    1.140199 </code></pre>
</div>
</div>
<p>Wir können uns mit der Funcktion <code>check_model()</code> aus dem R Paket <code>{performance}</code> auch die Unsicherheit mit angeben lassen. In unserem Beispiel hieft dies gerade nicht sehr viel weiter. Wir bleiben bei den geschätzen Werten und ignorieren das Intervall.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-stat-modeling-vif" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-modeling-vif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-vif-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-9" data-gallery="quarto-lightbox-gallery-9"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-vif-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-modeling-vif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;39.5— Graphische Darstellung des VIF mit der Funktion <code>check_model()</code>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-stat-modeling-vif" class="quarto-xref">Abbildung&nbsp;<span>39.5</span></a> sehen wir nochmal die Visualisierung. Wie immer, manchmal helfen solche Abbildungen, manchmal verwirren die Abbildungen mehr. Wir konzentrieren uns hier auf die Werte des VIF’s und ignorieren die Streuung.</p>
</section>
<section id="sec-model-basic-compare" class="level2" data-number="39.6">
<h2 data-number="39.6" class="anchored" data-anchor-id="sec-model-basic-compare"><span class="header-section-number">39.6</span> Vergleich von Modellen</h2>
<p>Im Folgenden wollen wir einmal verschiedene Modelle miteinander Vergleichen und uns statistisch wiedergeben lassen, was das beste Modell ist. Und hier holen wir auch einmal kurz Luft, denn wir entschieden <em>nur</em> was das statistisch beste Modell ist. Es kann sein, dass ein Modell biologisch mehr Sinn macht und nicht auf Platz 1 der statistischen Maßzahlen steht. Das ist vollkommen in Ordnung. Du musst abweägen, was für sich das beste Modell ist. Im Zweifel komme ruhig nochmal in meine statistische Beratung oder schreibe mir eine Mail.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[15,85]">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 15.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/angel_01.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="images/angel_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 85.0%;justify-content: flex-start;">
<blockquote class="blockquote">
<p>Wir kürzen hier stark ab bzw. gehen nicht im Detail auf jedes Gütekriterium ein. Wichtig ist, dass du Modelle <em>statistisch</em> vergleichen kannst. Bedenke immmer, dass die <em>statistische</em> Bewertung nicht immer ausreicht! Auch was die Biologie über das Modell sagt ist wichtig.</p>
</blockquote>
</div>
</div>
</div>
<p>Wir bauchen uns jetzt fünf Modelle von <code>fit_1</code> bis <code>fit_5</code>. Jedes dieser Modelle hat andere <span class="math inline">\(x\)</span> aber häufig das gleiche Outcome <code>y</code>. In dem Beispiel am Ende des Kapitels nutzen wir auch verschiedene <span class="math inline">\(y\)</span> dafür aber dann gleiche <span class="math inline">\(x\)</span> in dem Modell. Im Weiteren sortieren wir die Modelle von einfach nach komplex. Ich versuche immmer das einfachste Modell <code>fit_1</code> zu nennen bzw. eher die niedrige Nummer zu geben. Im Idealfall benennst du die Modellobjekte nach den Modellen, die in en Objekten gespeichert sind. Oft sind die Modelle aber sehr groß und die Objekte der Fits haben dann sehr lange Namen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jump_length <span class="sc">~</span> animal, <span class="at">data =</span> model_tbl)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jump_length <span class="sc">~</span> animal <span class="sc">+</span> sex, <span class="at">data =</span> model_tbl)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>fit_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jump_length <span class="sc">~</span> animal <span class="sc">+</span> sex <span class="sc">+</span> weight, <span class="at">data =</span> model_tbl)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>fit_4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(jump_length <span class="sc">~</span> animal <span class="sc">+</span> sex <span class="sc">+</span> sex<span class="sc">:</span>weight, <span class="at">data =</span> model_tbl)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>fit_5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(jump_length) <span class="sc">~</span> animal <span class="sc">+</span> sex, <span class="at">data =</span> model_tbl)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Als Ergänzung zum Bestimmtheitsmaß <span class="math inline">\(R^2\)</span> wollen wir uns noch das <em>Akaike information criterion</em> (abk. <span class="math inline">\(AIC\)</span>) anschauen. Du kannst auch das <span class="math inline">\(R^2\)</span> bzw. das <span class="math inline">\(R^2_{adj}\)</span> für die Modellauswahl nehmen. Das <span class="math inline">\(AIC\)</span> ist neuer und auch für komplexere Modelle geeignet. Es gilt hierbei, je kleiner das <span class="math inline">\(AIC\)</span> ist, desto besser ist das <span class="math inline">\(AIC\)</span>. Wir wollen also Modelle haben, die ein kleines <span class="math inline">\(AIC\)</span> haben. Wir gehen jetzt nicht auf die Berechnung der <span class="math inline">\(AIC\)</span>’s für jedes Modell ein. Wir erhalten nur ein <span class="math inline">\(AIC\)</span> für jedes Modell. Die einzelnen Werte des <span class="math inline">\(AIC\)</span>’s sagen <em>nichts</em> aus. Ein <span class="math inline">\(AIC\)</span> ist ein mathematisches Konstrukt. Wir können aber verwandte Modelle mit dem <span class="math inline">\(AIC\)</span> untereinander vergleichen. Daher berechnen wir ein <span class="math inline">\(\Delta\)</span> über die <span class="math inline">\(AIC\)</span>. Dafür nehmen wir das Modell mit dem niedrigsten <span class="math inline">\(AIC\)</span> und berechnen die jeweiligen Differenzen zu den anderen <span class="math inline">\(i\)</span> Modellen. In unserem Beispiel ist <span class="math inline">\(i\)</span> dann gleich fünf, da wir fünf Modelle haben.</p>
<p><span class="math display">\[
\Delta_i = AIC_i - AIC_{min}
\]</span></p>
<ul>
<li>wenn <span class="math inline">\(\Delta_i &lt; 2\)</span>, gibt es keinen Unterschied zwischen den Modellen. Das <span class="math inline">\(i\)</span>-te Modell ist genauso gut wie das Modell mit dem <span class="math inline">\(AIC_{min}\)</span>.</li>
<li>wenn <span class="math inline">\(2 &lt; \Delta_i &lt; 4\)</span>, dann gibt es eine starke Unterstützung für das <span class="math inline">\(i\)</span>-te Modell. Das <span class="math inline">\(i\)</span>-te Modell ist immer noch ähnlich gut wie das <span class="math inline">\(AIC_{min}\)</span>.</li>
<li>wenn <span class="math inline">\(4 &lt; \Delta_i &lt; 7\)</span>, dann gibt es deutlich weniger Unterstützung für das <span class="math inline">\(i\)</span>-te Modell;</li>
<li>Modelle mit <span class="math inline">\(\Delta_i &gt; 10\)</span> sind im Vergleich zu dem <em>besten</em> <span class="math inline">\(AIC\)</span> Modell nicht zu verwenden.</li>
</ul>
<p>Nehmen wir ein <span class="math inline">\(AIC_1 = AIC_{min} = 100\)</span> und <span class="math inline">\(AIC_2\)</span> ist <span class="math inline">\(100,7\)</span> an. Dann ist <span class="math inline">\(\Delta_2=0,7&lt;2\)</span>, so dass es keinen wesentlichen Unterschied zwischen den Modellen gibt. Wir können uns entscheiden, welches der beiden Modelle wir nehmen. Hier ist dann wichtig, was auch die Biologie sagt oder eben andere Kriterien, wie Kosten und Nutzen. Wenn wir ein <span class="math inline">\(AIC_1 = AIC_{min} = 100000\)</span> und <span class="math inline">\(AIC_2\)</span> ist <span class="math inline">\(100700\)</span> vorliegen haben, dann ist <span class="math inline">\(\Delta_2 = 700 \gg 10\)</span>, also gibt es keinen Grund für das <span class="math inline">\(2\)</span>-te Modell. Das <span class="math inline">\(2\)</span>-te Modell ist substantiell schlechter als das erste Modell. Mehr dazu kannst du unter <a href="https://faculty.washington.edu/skalski/classes/QERM597/papers_xtra/Burnham%20and%20Anderson.pdf">Multimodel Inference: Understanding AIC and BIC in Model Selection</a> nachlesen.</p>
<p>Wir können das <span class="math inline">\(\Delta_i\)</span> auch in eine Wahrscheinlichkeit umrechnen. Wir können <span class="math inline">\(p_i\)</span> berechnen und damit die relative (im Vergleich zu <span class="math inline">\(AIC_{min}\)</span>) Wahrscheinlichkeit, dass das <span class="math inline">\(i\)</span>-te Modell den AIC minimiert.</p>
<p><span class="math display">\[
p_i = \exp\left(\cfrac{-\Delta_i}{2}\right)
\]</span></p>
<p>Zum Beispiel entspricht <span class="math inline">\(\Delta_i = 1.5\)</span> einem <span class="math inline">\(p_i\)</span> von <span class="math inline">\(0.47\)</span> (ziemlich hoch) und ein <span class="math inline">\(\Delta_i = 15\)</span> entspricht einem <span class="math inline">\(p_i =0.0005\)</span> (ziemlich niedrig). Im ersten Fall besteht eine Wahrscheinlichkeit von 47%, dass das <span class="math inline">\(i\)</span>-te Modell tatsächlich eine bessere Beschreibung ist als das Modell, das <span class="math inline">\(AIC_{min}\)</span> ergibt, und im zweiten Fall beträgt diese Wahrscheinlichkeit nur 0,05%. Wir können so einmal nachrechnen, ob sich eine Entscheidung für ein anderes Modell lohnen würde. Neben dem <span class="math inline">\(AIC\)</span> gibt es auch das Bayesian information criterion (<span class="math inline">\(BIC\)</span>). Auch beim <span class="math inline">\(BIC\)</span> gilt, je kleiner das BIC ist, desto besser ist das BIC.</p>
<p>Du siehst schon, es gibt eine Reihe von Möglichkeiten sich mit der Güte oder Qualität eines Modells zu beschäftigen. Wir nutzen die Funktion <code>model_performance()</code> um uns die Informationen über die Güte eines Modells wiedergeben zu lassen. Im folgenden Codeblock habe ich mich nur auf das <span class="math inline">\(AIC\)</span> und das <span class="math inline">\(BIC\)</span> konzentriert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_performance</span>(fit_1) <span class="sc">|&gt;</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(AIC, BIC)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
    AIC   BIC
  &lt;dbl&gt; &lt;dbl&gt;
1 3076. 3093.</code></pre>
</div>
</div>
<p>Gut soweit. Du kannst jetzt für jedes der Modelle das <span class="math inline">\(AIC\)</span> berechnen und dann dir die Modelle entsprechend ordnen. Wir müssen das aber nicht tun. Wir können uns auch die Funktion <code>compare_performance()</code> zu nutze machen. Die Funktion gibt uns die <span class="math inline">\(R^2\)</span>-Werte wieder wie auch die <span class="math inline">\(AIC\)</span> sowie die <span class="math inline">\(s^2_{\epsilon}\)</span> als <code>sigma</code> wieder. Wir haben also alles zusammen was wir brauchen. Darüber hinaus kann die Funktion auch die Modelle rangieren. Das nutzen wir natürlich gerne.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>comp_res <span class="ot">&lt;-</span> <span class="fu">compare_performance</span>(fit_1, fit_2, fit_3, fit_4, fit_5, <span class="at">rank =</span> <span class="cn">TRUE</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>comp_res</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name  | Model |    R2 | R2 (adj.) |  RMSE | Sigma | AIC weights | AICc weights | BIC weights | Performance-Score
----------------------------------------------------------------------------------------------------------------
fit_2 |    lm | 0.739 |     0.738 | 1.926 | 1.933 |       0.644 |        0.650 |       0.959 |            82.69%
fit_5 |    lm | 0.731 |     0.729 | 0.099 | 0.099 |    2.58e-09 |     2.61e-09 |    3.84e-09 |            56.58%
fit_3 |    lm | 0.739 |     0.737 | 1.926 | 1.935 |       0.237 |        0.235 |       0.039 |            50.83%
fit_4 |    lm | 0.739 |     0.737 | 1.925 | 1.935 |       0.119 |        0.115 |       0.002 |            45.01%
fit_1 |    lm | 0.316 |     0.314 | 3.118 | 3.126 |   5.42e-126 |    5.57e-126 |   7.27e-125 |             0.00%</code></pre>
</div>
</div>
<p>Anhand der Ausgabe der Funktion <code>compare_performance()</code> sehen wir, dass unser Modell <code>fit_2</code> das beste Modell ist. Zwar ist die Streuung der Residuen nicht die Kleinste aller Modelle (<code>Sigma</code> = 1.933) aber wir haben ein hohes <span class="math inline">\(R^2_{adj}\)</span> und auch ein kleines <span class="math inline">\(AIC\)</span>. Wir würden damit sagen, dass das Modell <code>fit_2</code> mit den Variablen <code>animal</code> und <code>sex</code> für <span class="math inline">\(x\)</span> das Outcome <code>jump_length</code> am besten statistisch beschreibt.</p>
<p>In <a href="#fig-stat-modeling-compare" class="quarto-xref">Abbildung&nbsp;<span>39.6</span></a> sehen wir die Ausgabe der Funktion <code>compare_performance()</code> nochmal visualisiert. Wir können dann die einzelnen Modelle nochmal besser vergleichen. Auch siehst du hier, ob ein Modell in einem Bereich sehr schlecht ist oder aber nur in einem Bereich sehr gut.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-stat-modeling-compare" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-modeling-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="stat-modeling-basic_files/figure-html/fig-stat-modeling-compare-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-11" data-gallery="quarto-lightbox-gallery-11"><img src="stat-modeling-basic_files/figure-html/fig-stat-modeling-compare-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-modeling-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;39.6— Graphische Darstellung der Funktion <code>compare_performance()</code> Wir sehen hier die einzelnen Gütekriterien in einer Übersicht dargestellt.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Zum Ende stellt sich die Frage nach dem statistischen Test. Können wir auch statistisch Testen, ob das Modell <code>fit_1</code> signifikant unterschiedlich ist? Ja wir können die Funktion <code>test_vuong()</code> nutzen um ein Model zu den anderen Modellen zu vergleichen. Wenn du mehrere Modell miteinander vergleichen möchtest, dann muss du die Funktion mehrfach ausführen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_vuong</span>(fit_1, fit_2, fit_3, fit_4, fit_5)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Name  | Model | Omega2 | p (Omega2) |      LR | p (LR)
------------------------------------------------------
fit_1 |    lm |        |            |         |       
fit_2 |    lm |   0.41 |     &lt; .001 |  -18.46 | &lt; .001
fit_3 |    lm |   0.41 |     &lt; .001 |  -18.45 | &lt; .001
fit_4 |    lm |   0.41 |     &lt; .001 |  -18.48 | &lt; .001
fit_5 |    lm |   0.47 |     &lt; .001 | -123.94 | &lt; .001
Each model is compared to fit_1.</code></pre>
</div>
</div>
<p>Nutzen wir die Modellselektion auch einmal an einem konkreten Beispiel. War die Transformation sinnvoll? Wir haben also ein Outcome <span class="math inline">\(y\)</span> vorliegen und wollen wissen, ob wir nicht lieber das Modell mit einem <span class="math inline">\(y\)</span> mit einer <span class="math inline">\(log\)</span>-Transformation rechnen sollten. Wir nutzen dazu den Datensatz mit den Hunde- und Katzenflöhen und die Schlüpfdauer als Outcome. Also wie lange brauchen die Flöhe bis die Flöhe aus den Eiern geschlüpft sind.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>model_tbl <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">"data/flea_dog_cat_length_weight.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_hatch_time =</span> <span class="fu">round</span>(<span class="fu">log</span>(hatch_time), <span class="dv">2</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir bauen uns jetzt zwei Modelle. Zum einen das Modell <code>fit_raw</code> mit der <code>hatch_time</code> und den Variablen <code>ainmal</code> und <code>sex</code>. Das zweite Modell enthält die <code>log(hatch_time)</code> also das Outcome <span class="math inline">\(y\)</span> als <span class="math inline">\(log\)</span>-Transformation. Wiederum sind die <span class="math inline">\(x\)</span> variablen die gleichen wie im untransformierten Modell. Wir fitten beide Modelle und speichern die Objekte entsprechend ab.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>fit_raw <span class="ot">&lt;-</span> <span class="fu">lm</span>(hatch_time <span class="sc">~</span> animal <span class="sc">+</span> sex, <span class="at">data =</span> model_tbl)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>fit_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_hatch_time <span class="sc">~</span> animal <span class="sc">+</span> sex, <span class="at">data =</span> model_tbl)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die Funktion <code>compare_performance()</code> erlaubt uns wieder die beiden Modelle <code>fit_raw</code> und <code>fit_log</code> miteinander zu vergleichen. Wir erhalten die folgende Ausgabe der Funktion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>comp_res <span class="ot">&lt;-</span> <span class="fu">compare_performance</span>(fit_raw, fit_log, <span class="at">rank =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>comp_res</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name    | Model |    R2 | R2 (adj.) |    RMSE |   Sigma | AIC weights | AICc weights | BIC weights | Performance-Score
----------------------------------------------------------------------------------------------------------------------
fit_log |    lm | 0.006 |     0.001 |   0.992 |   0.995 |        1.00 |         1.00 |        1.00 |            71.43%
fit_raw |    lm | 0.008 |     0.003 | 789.441 | 792.086 |    0.00e+00 |     0.00e+00 |    0.00e+00 |            28.57%</code></pre>
</div>
</div>
<p>In diesem Beispiel wäre das <span class="math inline">\(log\)</span>-transformierte Modell das bessere statistische Modell. Wir müssen jetzt überlegen, ob wir den Preis dafür bezahlen wollen. Wenn wir nämlich alles mit der <span class="math inline">\(log\)</span>-Transformation rechnen, dann erhalten wir auch alle Koeffizienten auf der <span class="math inline">\(log\)</span>-Skala (eng. <em>log scale</em>). Hier kannst du nur von Fall zu Fall entscheiden.</p>
</section>
<section id="referenzen" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referenzen">Referenzen</h2>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-2">Abbildung&nbsp;39.1— Graphische Darstellung der Interpretation von einem kontinuierlichen <span class="math inline">\(x\)</span>.</span>
<span class="glightbox-desc lightbox-desc-3">Abbildung&nbsp;39.2— Graphische Darstellung der Interpretation von einem kategoriellen <span class="math inline">\(x\)</span> mit 2 Leveln.</span>
<span class="glightbox-desc lightbox-desc-4">Abbildung&nbsp;39.3— Graphische Darstellung der Interpretation von einem kategoriellen <span class="math inline">\(x\)</span> mit 3 Leveln.</span>
<span class="glightbox-desc lightbox-desc-5">Abbildung&nbsp;39.4&nbsp;(a)— jump_length ~ weight</span>
<span class="glightbox-desc lightbox-desc-6">Abbildung&nbsp;39.4&nbsp;(b)— jump_length ~ weight + animal</span>
<span class="glightbox-desc lightbox-desc-7">Abbildung&nbsp;39.4&nbsp;(c)— jump_length ~ weight + animal + sex</span>
<span class="glightbox-desc lightbox-desc-9">Abbildung&nbsp;39.5— Graphische Darstellung des VIF mit der Funktion <code>check_model()</code>.</span>
<span class="glightbox-desc lightbox-desc-11">Abbildung&nbsp;39.6— Graphische Darstellung der Funktion <code>compare_performance()</code> Wir sehen hier die einzelnen Gütekriterien in einer Übersicht dargestellt.</span>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-kery2010introduction" class="csl-entry" role="listitem">
Kéry M. 2010. Introduction to WinBUGS for ecologists: Bayesian approach to regression, ANOVA, mixed models and related analyses. Academic Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./stat-linear-reg-basic.html" class="pagination-link" aria-label="Simple lineare Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-linear-reg-quality.html" class="pagination-link" aria-label="Modelgüte">
        <span class="nav-page-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Modelgüte</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Bio Data Science wurde von <a href="https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/">Jochen Kruppa-Scheetz</a> geschrieben.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jkruppa/jkruppa.github.io/edit/master/stat-modeling-basic.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li><li><a href="https://github.com/jkruppa/jkruppa.github.io/blob/master/stat-modeling-basic.qmd" class="toc-action"><i class="bi empty"></i>Quellcode anzeigen</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Dieses Openbook wurde mit <a href="https://quarto.org/">Quarto</a> erstellt.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"openEffect":"zoom","closeEffect":"zoom","loop":false,"descPosition":"bottom","selector":".lightbox"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>