<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.629">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Skript Bio Data Science - 28&nbsp; Der diagnostische Test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stat-tests-pretest.html" rel="next">
<link href="./stat-tests-chi-test.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skript Bio Data Science</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./literature.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literatur</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einführung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./example-preface.html" class="sidebar-item-text sidebar-link">Datenbeispiele</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Von Flöhen und Hunden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Von Flöhen, Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-foxes-site.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Von Flöhen auf Tieren in Habitaten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-fleas-dogs-cats-length-weight.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Von vielen Flöhen auf Hunden und Katzen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-gummi-bears.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Von Gummibärchen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example-complex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Von komplexeren Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./programing-preface.html" class="sidebar-item-text sidebar-link">Programmieren in R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-letters-numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Von Buchstaben und Zahlen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Operatoren, Funktionen und Pakete</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daten einlesen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programing-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Daten bearbeiten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./eda-preface.html" class="sidebar-item-text sidebar-link">Explorative Datenanalyse</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualisierung von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Transformieren von Daten</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Verteilung von Daten</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-tests-preface.html" class="sidebar-item-text sidebar-link">Frequentistische Hypothesentests</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Die Testentscheidung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-theorie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Die Testtheorie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-effect.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Der Effektschätzer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ttest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Der t-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Die ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-ancova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Die ANCOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-utest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Der Wilcoxon-Mann-Whitney-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-kruskal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Der Kruskal-Wallis-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-chi-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-diagnostic.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-pretest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tests-posthoc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Multiple Vergleiche oder Post-hoc Tests</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-linear-reg-preface.html" class="sidebar-item-text sidebar-link">Grundlagen der linearen Regression</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-quality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Maßzahlen der Modelgüte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-linear-reg-corr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Korrelation</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./stat-modeling-preface.html" class="sidebar-item-text sidebar-link">Statistisches Modellieren</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-variable-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Variablenselektion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-outlier.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Ausreißer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-missing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Imputation fehlender Werte</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-gaussian.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Gaussian lineare Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Logistische Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-poisson.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Poisson Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Lineare gemischte Modelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-modeling-non-linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Nicht lineare Regression</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./experimentel-design-preface.html" class="sidebar-item-text sidebar-link">Experimentelles Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimentel-design-basic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Grundlagen der Versuchsplanung</span></a>
  </div>
</li>
    </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Anhang</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-example-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Beispielhafte Auswertungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-r-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tutorium in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-how-to-write.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Writing principles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-lectures-semester.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Logbuch</span></a>
  </div>
</li>
    </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#genutzte-r-pakete-f%C3%BCr-das-kapitel" id="toc-genutzte-r-pakete-für-das-kapitel" class="nav-link active" data-scroll-target="#genutzte-r-pakete-f%C3%BCr-das-kapitel"> <span class="header-section-number">28.1</span> Genutzte R Pakete für das Kapitel</a></li>
  <li><a href="#die-daten-f%C3%BCr-das-diagnostische-testen" id="toc-die-daten-für-das-diagnostische-testen" class="nav-link" data-scroll-target="#die-daten-f%C3%BCr-das-diagnostische-testen"> <span class="header-section-number">28.2</span> Die Daten für das diagnostische Testen</a></li>
  <li><a href="#confusion-matrix-deu.-fehlermatrix" id="toc-confusion-matrix-deu.-fehlermatrix" class="nav-link" data-scroll-target="#confusion-matrix-deu.-fehlermatrix"> <span class="header-section-number">28.3</span> Confusion matrix (deu. <em>Fehlermatrix</em>)</a></li>
  <li>
<a href="#receiver-operating-characteristic-roc" id="toc-receiver-operating-characteristic-roc" class="nav-link" data-scroll-target="#receiver-operating-characteristic-roc"> <span class="header-section-number">28.4</span> Receiver Operating Characteristic (ROC)</a>
  <ul class="collapse">
<li><a href="#daten-f%C3%BCr-die-receiver-operating-characteristic-roc" id="toc-daten-für-die-receiver-operating-characteristic-roc" class="nav-link" data-scroll-target="#daten-f%C3%BCr-die-receiver-operating-characteristic-roc"> <span class="header-section-number">28.4.1</span> Daten für die Receiver Operating Characteristic (ROC)</a></li>
  </ul>
</li>
  <li><a href="#reciever-operator-curve-roc-in-r" id="toc-reciever-operator-curve-roc-in-r" class="nav-link" data-scroll-target="#reciever-operator-curve-roc-in-r"> <span class="header-section-number">28.5</span> Reciever Operator Curve (ROC) in R</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-test-diag" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Der diagnostische Test</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell">

</div>
<p><em>Version vom October 21, 2022 um 15:46:32</em></p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Was macht der diagnostische Test?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ein diagnostischer Test gibt die Güte einer Klassifizierung wieder. Wir gut wurden Kranke als krank und Gesunde als gesund erkannt? Diese und ähnliche Fragen beantwortet das diagnostische Testen.</p>
</div>
</div>
<p>In diesem Kapitel wollen wir uns mit dem diagnostischen Test beschäftigen. Eigentlich würde man meinen, dass Diagnostik nun eher in die Medizin gehört. Hauptsächlich wird das diagnostische Testen auch in der Labordiagnostik oder bei der Herstellung eines neuen medizinischen Testes verwendet. Deshalb gibt es hier auch erstmal (Stand Ende 2022) nur einen Ausschnitt aus dem diagnostischen Testen. Wir brauchen aber die Fachbegriffe, wenn wir uns später einmal mit dem maschinellen Lernen oder dem Klasifizieren beschäftigen wollen. Dann brauchen wir die hier verwendeten Fachbegriffe, wie Spezifität, Sensifität, AUC und auch die ROC Abildung.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Ein Wort zur Klausur
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Bitte schau dir die Aufgaben in den <a href="https://github.com/jkruppa/teaching/tree/main/Klausur">gesammelten Klausurfragen auf GitHub</a> an um eine Idee zu haben, welche Fragen zum Diagnostischen Testen drankommen.</p>
</div>
</div>
</div>
<section id="genutzte-r-pakete-für-das-kapitel" class="level2" data-number="28.1"><h2 data-number="28.1" class="anchored" data-anchor-id="genutzte-r-pakete-für-das-kapitel">
<span class="header-section-number">28.1</span> Genutzte R Pakete für das Kapitel</h2>
<p>Wir wollen folgende R Pakete in diesem Kapitel nutzen.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">magrittr</span>, </span>
<span>               <span class="va">pROC</span>, <span class="va">readxl</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am Ende des Kapitels findest du nochmal den gesamten R Code in einem Rutsch zum selber durchführen oder aber kopieren.</p>
</section><section id="die-daten-für-das-diagnostische-testen" class="level2 page-columns page-full" data-number="28.2"><h2 data-number="28.2" class="anchored" data-anchor-id="die-daten-für-das-diagnostische-testen">
<span class="header-section-number">28.2</span> Die Daten für das diagnostische Testen</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Es ist <strong>unabdingbar</strong>, dass oben links in der 2x2 Kreuztabelle immer die <span class="math inline">\(T^+\)</span> und <span class="math inline">\(K^+\)</span> Werte stehen. Sonst funktionieren alle Formeln in diesem Kapitel nicht.</span></div></div>
<p>Die Datentabelle für das diagnostische Testen basiert wie der <span class="math inline">\(\chi^2\)</span>-Test auf der 2x2 Kreuztabelle oder Verfeldertafel. Es ist dabei <em>unabdingbar</em>, dass oben links in der 2x2 Kreuztabelle immer die <span class="math inline">\(T^+\)</span> und <span class="math inline">\(K^+\)</span> Werte stehen. Sonst funktionieren alle Formeln in diesem Kapitel nicht. Wir schauen usn auch immer <em>das Schlechte an</em>. Daher wollen wir immer wissen, ist der Hund krank? Ist der Hund tot? Ist der Hund weggelaufen? Beide Voraussetzung sind wichtig, damit wir mit der 2x2 Kreuztabelle wie in <a href="#tbl-2x2-table-general">Tabelle&nbsp;<span>28.1</span></a> gezeigt rechnen können.</p>
<div id="tbl-2x2-table-general" class="anchored">
<table class="table">
<caption>Tabelle 28.1— Eine 2x2 Tabelle oder Vierfeldertafel</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 21%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Krank</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">
<span class="math inline">\(K^+\)</span> (1)</td>
<td style="text-align: center;">
<span class="math inline">\(K^-\)</span> (0)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Test</strong></td>
<td style="text-align: center;">
<span class="math inline">\(T^+\)</span> (1)</td>
<td style="text-align: center;"><span class="math inline">\(TP_{\;\Large a}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(FN_{\;\Large b}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{a+b}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">
<span class="math inline">\(T^-\)</span> (0)</td>
<td style="text-align: center;"><span class="math inline">\(FP_{\;\Large c}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(TN_{\;\Large d}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{c+d}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{a+c}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{b+d}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{n}\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Wir wollen die <a href="#tbl-2x2-table-general">Tabelle&nbsp;<span>28.1</span></a> mit einem Beispiel von <em>Tollwut</em> an Hauskatzen in <em>ländlicher</em> Umgebung. Die Katzen haben also Auslauf und können sich auch mit Tollwut infizieren. Wir wollen einen neuen, nicht invasiven Labortesten <em>Tollda</em> darauf überprüfen, wie gut der diagnostische Test Tollwut bei Katzen im Frühstadium erkennt.</p>
<p>Wir haben jetzt folgende Informationen erhalten:</p>
<ul>
<li>Der diagnostische Test <em>TollDa</em> ist positiv <span class="math inline">\(T^+\)</span>, wenn Tollwut vorliegt <span class="math inline">\(K^+\)</span> , in 80% der Fälle.</li>
<li>Der diagnostische Test <em>TollDa</em> ist positiv <span class="math inline">\(T^+\)</span>, wenn <em>keine</em> Tollwut vorliegt <span class="math inline">\(K^-\)</span>, in 9.5% der Fälle.</li>
<li>Abschließend haben noch 2% der Katzen in ländlicher Umgebung Tollwut. Wir haben eine Prävalenz der Erkrankung in der betrachteten Population von 2%.</li>
</ul>
<p>Die Halterin einer Katze möchte nun wissen, wie groß ist dei Wahrscheinlichkeit bei einem positiven Testergebnis, dass meine Katze Tollwut hat. Also die bedingte Wahrscheinlichkeit <span class="math inline">\(Pr(K^+|T^+)\)</span> oder die Wahrscheinlichkeit krank zu sein gegeben eines positiven Tests.</p>
<div class="column-page">
<div id="fig-stat-diag-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/diag_testen_doppel.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.1— Visualisierung der Informationen zur Tollwutdiagnostik in einem Doppelbaum. Gefragt ist nach der Wahrscheinlichkeit <span class="math inline">\(Pr(K^+|T^+)\)</span> oder die Wahrscheinlichkeit krank zu sein gegeben eines positiven Tests.</figcaption><p></p>
</figure>
</div>
</div>
<p><a href="#fig-stat-diag-01">Abbildung&nbsp;<span>28.1</span></a> visualisert unsere Frage in einem Doppelbaum. Wir haben 10000 Katzen vorliegen. Ja wir waren fleißig und wir können damit besser rechnen. Du siehst aber auch, für die Diagnostik brauchen wir eine Menge Beobachtungen.</p>
<p>Von den 10000 Katzen sind 2% also 200 wirklich mit Tollwut infiziert, also haben den Status <span class="math inline">\(K^+\)</span>. Damit sind 9800 Katzen gesund oder nicht krank und haben den Status <span class="math inline">\(K^-\)</span>. Wir wissen jetzt, dass 80% der <span class="math inline">\(K^+\)</span> Katzen als postitiv vom Test erkannt werden. Damit werden <span class="math inline">\(200 \cdot 0.8 = 160\)</span> Katzen <span class="math inline">\(T^+\)</span>. Im Umkehrschluss sind die anderen 40 Katzen dann <span class="math inline">\(T^-\)</span>. Von den 9800 gesunden Katzen werden 9.5% fälsch als krank erkannt, also <span class="math inline">\(9800 \cdot 0.095 = 931\)</span> Katzen. Wiederum im Umkehrschluss sind dann 8869 richtig als gesunde Tiere erkannt.</p>
<p>Wir können nun den Doppelbaum nach unten ergänzen. Wir haben damit <span class="math inline">\(1091 = 160 + 931\)</span> positiv getestete Katzen <span class="math inline">\(T^+\)</span> sowie <span class="math inline">\(819 = 40 + 8869\)</span> negativ getestete Katzen <span class="math inline">\(T^-\)</span>.</p>
<p>Wie groß ist nun die Wahrscheinlichkeit <span class="math inline">\(Pr(K^+|T^+)\)</span> oder die Wahrscheinlichkeit krank zu sein gegeben eines positiven Tests? Wir können die Wahrscheinlichkeit <span class="math inline">\(Pr(K^+|T^+)\)</span> direkt im Baum ablesen. Wir haben 160 kranke und positive Tier. Insgesamt sind 1091 Tiere positiv getestet. Daher Wahrscheinlichkeit krank zu sein gegeben eines positiven Tests <span class="math inline">\(\tfrac{160}{1091} = 0.147\)</span> oder nur 14%.</p>
<p>Sammeln wir unsere Informationen um die <a href="#tbl-2x2-table-general">Tabelle&nbsp;<span>28.1</span></a> zu füllen. Wir haben insgesamt <span class="math inline">\(n = 10000\)</span> Katzen untersucht. In <a href="#tbl-2x2-table-example">Tabelle&nbsp;<span>28.2</span></a> sehen wir die Ergebnisse unseres Tests auf Tollwut zusammengefasst. Wir haben <span class="math inline">\(160\)</span> Katzen die Tollwut haben und vom Test als krank erkannt wurden. Dann haben wir <span class="math inline">\(931\)</span> Katzen, die keine Tollwut hatten und vom Test als positiv erkannt wurden. Darüber hinaus haben wir <span class="math inline">\(40\)</span> Katzen, die Tollwut haben, aber ein negatives Testergebnis. Sowie <span class="math inline">\(8869\)</span> gesunde Katzen mit einem negativen Testergebnis.</p>
<div id="tbl-2x2-table-example" class="anchored">
<table class="table">
<caption>Tabelle 28.2— Eine 2x2 Tabelle oder Vierfeldertafel gefüllt mit dem Beispiel aus dem Doppelbaum.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 24%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Krank</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">
<span class="math inline">\(K^+\)</span> (1)</td>
<td style="text-align: center;">
<span class="math inline">\(K^-\)</span> (0)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Test</strong></td>
<td style="text-align: center;">
<span class="math inline">\(T^+\)</span> (1)</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">931</td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{a+b} = 1091\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">
<span class="math inline">\(T^-\)</span> (0)</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">8869</td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{c+d} = 8109\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{a+c} = 200\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{b+d} = 9800\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathbf{n} = 10000\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Wie du sehen kannst ist die mittlere Reihe des Doppelbaums nichts anderes als die ausgefüllte 2x2 Kreuztabelle. In <a href="#fig-stat-diag-00">Abbildung&nbsp;<span>28.2</span></a> sehen wir die letzte Visualisierung des Zusammenhangs von Testscore auf der x-Achse und der Verteilung der tollwütigen Katzen <span class="math inline">\(K^+\)</span> und der gesunden Katzen <span class="math inline">\(K^-\)</span>. Links und rechts von der Testenstscheidung werden Katzen falsch klassifiziert. Das heißt, die Katzen werden als krank oder gesund von dem Test erkannt, obwohl die Katzen diesen Status nicht haben. Ein idelr Test würde zwei Verteilungen der kranken und gesunden Tiere hrvorbringen, die sich perfekt separieren lassen. Es gibt anhand des Testscores keine Überlappung der beiden Verteilungen</p>
<div class="column-page">
<div id="fig-stat-diag-00" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/diag_testen_dist.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.2— Visualisierung des Zusammenhangs zwischen Testscore und den Verteilungen der kranken und gesunden Katzen sowie der Testenstscheidung. Links und rechts von der Testenstscheidung werden Katzen falsch klassifiziert.</figcaption><p></p>
</figure>
</div>
</div>
</section><section id="confusion-matrix-deu.-fehlermatrix" class="level2 page-columns page-full" data-number="28.3"><h2 data-number="28.3" class="anchored" data-anchor-id="confusion-matrix-deu.-fehlermatrix">
<span class="header-section-number">28.3</span> Confusion matrix (deu. <em>Fehlermatrix</em>)</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p>Die 2x2 Kreuztabelle wird als <a href="https://en.wikipedia.org/wiki/Confusion_matrix">Confusion matrix</a> viel auch in der Klassifikation im machinellen Lernen genutzt. Im maschinellen Lernen heißt es dann meist nur anders…</p>
</div></div><p>In der Statistik beziehungsweise der Epidemiologie gibt es eine Vielzahl an statistischen Maßzahlen für die 2x2 Kreuztabelle. In der Fachsprache wird die 2x2 Kreuztabelle auch <a href="https://en.wikipedia.org/wiki/Confusion_matrix">Confusion matrix</a> genannt. Auf der Confusion Matrix können viele Maßzahlen berechnet werden wir konzentrieren uns hier erstmal auf die zwei wichtigsten Maßzahlen, nämlich der Spezifität und der Sensitivität.</p>
<p>In der wissenschaftlichen Fachsprache hat ein diagnostischer Test oder eine Methode, die erkrankte Personen sehr zuverlässig als krank (<span class="math inline">\(K^+\)</span>) erkennt, eine hohe Sensitivität. Das heißt, sie übersieht kaum erkrankte Personen. Ein Test, der gesunde Personen zuverlässig als gesund (<span class="math inline">\(K^-\)</span>) einstuft, hat eine hohe Spezifität. Wir können die Spezifität und die Sensitivität auf der 2x2 Kreuztabelle wir folgt berechnen.</p>
<p><span class="math display">\[
\mbox{Sensitivität} = \mbox{sens} = \cfrac{TP}{TP + FN} = \cfrac{160}{160 + 931} = 0.147
\]</span></p>
<p><span class="math display">\[
\mbox{Spezifität} = \mbox{spec} = \cfrac{TN}{TN + FP} = \cfrac{8869}{8869 + 40} = 0.995
\]</span></p>
<p>Beide statistischen Maßzahlen benötigen wir im Besonderen bei der Erstellung der Reciever Operator Curve (ROC) im folgenden Abschnitt.</p>
</section><section id="receiver-operating-characteristic-roc" class="level2 page-columns page-full" data-number="28.4"><h2 data-number="28.4" class="anchored" data-anchor-id="receiver-operating-characteristic-roc">
<span class="header-section-number">28.4</span> Receiver Operating Characteristic (ROC)</h2>
<p>Die <a href="https://en.wikipedia.org/wiki/Receiver_operating_characteristic">Reciever Operator Curve (ROC)</a> ist <em>die</em> Abbildung wenn es darum geht darzustellen wie gut eine Klassifikation funktioniert hat. Wir werden die Abbildung später im maschinellen Lernen und der Klssifikation wiedertreffen. Da die ROC Kurve aber ursprünglich zum diagnostischen Testen gehört, kommt die ROC Kurve hier auch rein.</p>
<section id="daten-für-die-receiver-operating-characteristic-roc" class="level3 page-columns page-full" data-number="28.4.1"><h3 data-number="28.4.1" class="anchored" data-anchor-id="daten-für-die-receiver-operating-characteristic-roc">
<span class="header-section-number">28.4.1</span> Daten für die Receiver Operating Characteristic (ROC)</h3>
<p>Schauen wir uns erstmal ein Beispiel für die ROC Kurve an. In <a href="#tbl-data-roc-1">Tabelle&nbsp;<span>28.3</span></a> sehen wir Beispieldaten von vierzehn Hunden. Von den vierzehn Hunden haben sieben eine verdeckte Flohinfektion im Anfangsstadium und sieben Hunde sind flohfrei und gesund. Daher haben wir sieben kranke Hunde (<span class="math inline">\(K^+\)</span> oder Infektionsstatus ist <span class="math inline">\(1\)</span>) und sieben gesunde Hunde (<span class="math inline">\(K^-\)</span> oder Infektionsstatus ist <span class="math inline">\(0\)</span>). Wir <em>testen</em> jeden der Hunde mit dem Flohindikatormittel <em>FleaDa</em>. Das Flohindikatormittel gibt einen Farbwert als <code>test_score</code> zwischen <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span> wieder. Wir wollen nun herausfinden, ob wir mit dem <code>test_score</code> die vierzehn Hunde korrekt nach ihrem Krankheitszustand klassifizieren können.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-roc-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 28.3— Datensatz für vierzehn Hunde mit Flohinfektion und keiner Flohinfektion sowie dem Testscore des Flohindikatormittels <em>fleaDa</em>.</caption>
<thead><tr class="header">
<th style="text-align: center;">infected</th>
<th style="text-align: center;">test_score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.100</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.250</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.300</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.400</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.500</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.600</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.350</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.425</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.470</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.550</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.700</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.800</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.820</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir sehen die Daten visualisiert in <a href="#fig-labels-roc1">Abbildung&nbsp;<span>28.3</span></a>. Auf der <span class="math inline">\(y\)</span>-Achse ist der binäre Endpunkt <span class="math inline">\(infected\)</span> und auf der <span class="math inline">\(x\)</span>-Achse der Testscore des Flohindikators <em>FleaDa</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-labels-roc1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-diagnostic_files/figure-html/fig-labels-roc1-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.3— Aufteilung der kranken und gesunden Hunde nach Infektionsstatus und dem Testscore.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">

</div>
<p>Die Idee der ROC Kurve ist nun für jeden möglichen Wert des Testscores die Spezifität und Sensitivität zu berechnen. Wir müssen das aber nicht für alle Werte des Testscores machen, sondern nur für die Wert bei denen sich der Status einer Beobachtung anhand des Testscores ändern würde. Klingt ein wenig schräg, schauen wir es uns einmal an. Zuerst brauchen wir jeweils die Grenzen an denen wir für den Testscore eine Klassifikation machen. In <a href="#fig-labels-roc3">Abbildung&nbsp;<span>28.4</span></a> sehen wir die Grenzen als gelbe Linie.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-labels-roc3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-diagnostic_files/figure-html/fig-labels-roc3-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.4— Aufteilung der kranken und gesunden Hunde nach Infektionsstatus und dem Testscore.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Wir können jetzt für jede gelbe Linie als Threshold des Testscore die Spezifität und die Sensitivität berechen. berechnen <a href="#tbl-data-roc-2">Tabelle&nbsp;<span>28.4</span></a> sind die Werte von Spezifität und Sensitivität für jede gelbe Linie ausgegeben. Wenn wir als Entscheidungsgrenze einen Testscore von 0.12 nehmen würden, dann würden wir 1 Hund als krank und 13 als gesund klassifizieren. Wir hätten 7 TN, 1 TP, 6 FN und 0 FP. Aus diesen Zahlen, die eine 2x2 Kreuztabelle entsprechen, können wir dann die Spezifität und die Sensitivität berechnen. Wir berechnen dann die Spezifität und die Sensitivität für jeden Threshold.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-data-roc-2" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabelle 28.4— Die Spezifität und die Sensitivität berechnet für jeden Threshold.</caption>
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">threshold</th>
<th style="text-align: center;">specificity</th>
<th style="text-align: center;">sensitivity</th>
<th style="text-align: center;">tn</th>
<th style="text-align: center;">tp</th>
<th style="text-align: center;">fn</th>
<th style="text-align: center;">fp</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: center;">0.28</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: center;">0.32</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.57</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center;">0.86</td>
<td style="text-align: center;">0.57</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: center;">0.41</td>
<td style="text-align: center;">0.86</td>
<td style="text-align: center;">0.71</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: center;">0.45</td>
<td style="text-align: center;">0.71</td>
<td style="text-align: center;">0.71</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: center;">0.48</td>
<td style="text-align: center;">0.57</td>
<td style="text-align: center;">0.71</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: center;">0.52</td>
<td style="text-align: center;">0.57</td>
<td style="text-align: center;">0.86</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">0.86</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir können jetzt für jeden Threshold und damit jedes verbundene Spezifität und Sensitivität Paar einen Punkt in einen Plot einzeichnen. Wir lassen damit Stück für Stück die ROC Kurve wachsen.</p>
<p>In der <a href="#fig-roc-drawn-1">Abbildung&nbsp;<span>28.5</span></a> sehen wir die ROC Kurve mit dem Threshold von 0.32 vorliegen. Wir haben damit 7 TN, 4 TP, 3 FN und 0 FP klassifizierte Beobchtungen. Darauf ergibt sich eine Spezifität von 1 und eine Sensitivität von 0.57. In der ROC Kurve tragen wir auf die <span class="math inline">\(x\)</span>-Achse die 1 - Spezifitätswerte auf. Damit haben wir eine schön ansteigende Kurve.</p>
<div class="column-page">
<div id="fig-roc-drawn-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/diag-roc-01.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.5— Visualisierung des Anwachsen der ROC Kurve mit einem Threshold von 0.32 und damit 7 TN, 4 TP, 3 FN und 0 FP.</figcaption><p></p>
</figure>
</div>
</div>
<p>In der <a href="#fig-roc-drawn-2">Abbildung&nbsp;<span>28.6</span></a> istr die ROC Kurve schon nach rechts gewachsen, da wir die ersten falsch positiv (FP) klassifizierten Beobachtungen bei einem Threshold von 0.48 erhalten.</p>
<div class="column-page">
<div id="fig-roc-drawn-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/diag-roc-02.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.6— Visualisierung des Anwachsen der ROC Kurve mit einem Threshold von 0.48 und damit 4 TN, 5 TP, 2 FN und 3 FP.</figcaption><p></p>
</figure>
</div>
</div>
<p>In <a href="#fig-roc-drawn-3">Abbildung&nbsp;<span>28.7</span></a> sind wir mit einem Threshold von 0.65 schon fast am rechten Rand der Verteilung des Testscores angekommen. Wir haben nur noch 3 richtig negative (TN) Beobachtungen, die jetzt mit steigenden Threshold alle zu falsch positiven (FP) klassifiziert werden.</p>
<div class="column-page">
<div id="fig-roc-drawn-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/diag-roc-03.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.7— Visualisierung des Anwachsen der ROC Kurve mit einem Threshold von 0.65 und damit 3 TN, 7 TP, 0 FN und 4 FP.</figcaption><p></p>
</figure>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Ein AUC von 1 bedeutet eine perfekte Trennung der beiden Gruppen durch den Testscore. Ein AUC von 0.5 bedeutet keine Trennung der beiden Gruppen durch den Testscore.</span></div></div>
<p>Die ROC Kurve endet dann oben rechts in der Abbidlung und startet immer unten links. Wir können noch die Fläche unter der ROC Kurve berechnen. Wir nennen diese Fläche unter der Kurve AUC (eng. <em>area under the curce</em>) und wir brauchen diese Maßzahl, wenn wir verschiedene Testscores und die entsprechenden ROC Kurven miteinander vergleichen wollen. Eine AUC von 0.5 bedeutet, dass unser Testscore nicht in der Lage war die kranken von den gesunden Hunden zu trennen.</p>
</section></section><section id="reciever-operator-curve-roc-in-r" class="level2" data-number="28.5"><h2 data-number="28.5" class="anchored" data-anchor-id="reciever-operator-curve-roc-in-r">
<span class="header-section-number">28.5</span> Reciever Operator Curve (ROC) in R</h2>
<p>Wir berechnen die ROC Kurve nicht per Hand. Das wäre eine sehr große Fleißarbeit für jeden Threshold zwischen den Beobachtungen die jeweilige Spezifität und Sensitivität Paare zu berechnen. Wir nutzen daher das R Paket <code>pROC</code>. Das Pakt erlaubt es uns später auch recht einfach ROC Kurven miteinander zu vergleichen und einen statistischen Test zu rechnen.</p>
<p>Die Daten von den obigen Beispiel sind in der Datei <code>roc_data.xlsx</code> gespeichert und können dann einfach verwendet werden. Die Funktion <code>roc()</code> akzeptiert ein binäres <span class="math inline">\(y\)</span> wo bei die <span class="math inline">\(1\)</span> das Schlechte bedeutet und die <span class="math inline">\(0\)</span> die Abwesenheit von dem Schlechten. Also eben krank oder gesund wie oben beschrieben. Wir wollen dann noch die AUC und die 95% Konfidenzintervalle für das AUC wiedergegeben haben.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">roc_tbl</span> <span class="op">&lt;-</span> <span class="fu">read_excel</span><span class="op">(</span><span class="st">"data/roc_data.xlsx"</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">roc_obj</span> <span class="op">&lt;-</span> <span class="fu">roc</span><span class="op">(</span><span class="va">infected</span> <span class="op">~</span> <span class="va">test_score</span>, <span class="va">roc_tbl</span>, auc <span class="op">=</span> <span class="cn">TRUE</span>, ci <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">roc_obj</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
roc.formula(formula = infected ~ test_score, data = roc_tbl,     auc = TRUE, ci = TRUE)

Data: test_score in 7 controls (infected 0) &gt; 7 cases (infected 1).
Area under the curve: 0.83673
95% CI: 0.61765-1 (DeLong)</code></pre>
</div>
</div>
<p>Wir sehen, dass wir eine AUC von 0.837 haben, was auf eine gute Trennschärfe des Tests hindeutet. Wäre die AUC näher an 0.5 dann würden wir sagen, dass der Test die kranken Hunde nicht von den gesunden Hunden unterscheiden kann.</p>
<p>Im nächsten Schritt extrahieren wir noch alle wichtigen Informationen aus dem Objekt <code>roc_obj</code> damit wir die ROC Kurve in <code>ggplot</code> zeichnen können. Das Paket pROC hat auch eine eigne Plotfunktion. Es gibt eine Reihe on <a href="https://web.expasy.org/pROC/screenshots.html">Screenshots vom pROC Paket</a>, wo du noch andere Möglichkeiten siehst. Einfach mal ausprobieren.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">roc_res_tbl</span> <span class="op">&lt;-</span> <span class="va">roc_obj</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">coords</span><span class="op">(</span>ret <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">specificity</span>, <span class="va">sensitivity</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das Objekt <code>roc_obj</code> nutzen wir jetzt um die ROC Kurve einmal darzustellen. Achte drauf, dass auf der <span class="math inline">\(x\)</span>-Achse die 1-Spezifität Werte stehen. Wir erhalten die ROC Kurve wie in <a href="#fig-labels-roc2">Abbildung&nbsp;<span>28.8</span></a> dargestellt. Wie zeichnen noch die Diagonale ein. Wenn die ROC nahe an der Diagonalen verläuft, dann ist der Testscore nicht in der Lage die Kranken von den Gesunden zu trennen. Eine perfekte ROC Kurve läuft senkrecht nach oben und dann waagerecht nach rechts und es ergebit sich eine AUC von 1.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">roc_res_tbl</span>, <span class="fu">aes</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">specificity</span>, <span class="va">sensitivity</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_path</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_abline</span><span class="op">(</span>intercept <span class="op">=</span> <span class="fl">0</span>, slope <span class="op">=</span> <span class="fl">1</span>, alpha <span class="op">=</span> <span class="fl">0.75</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"1 - Spezifität"</span>, y <span class="op">=</span> <span class="st">"Sensitivität"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-labels-roc2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="stat-tests-diagnostic_files/figure-html/fig-labels-roc2-1.png" class="img-fluid figure-img" width="480"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Abbildung 28.8— Abbildung der ROC Kurve.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In späteren Kapiteln zur Klassifikation werden wir auch verschiedene ROC Kurven zusammen darstellen und miteinander Vergleichen. Dazu nutzen wir dann auch die ROC Kurve und die Möglichkeit auch einen <code>roc.test()</code> zu rechnen. Mehr dazu gibt es soweit erstmal auf der Hilfeseite des R Paketes <code>pROC</code> mit vielen <a href="https://web.expasy.org/pROC/screenshots.html">Screenshots vom pROC Paket</a>. Für dieses Kapitel soll die Darstellung einer ROC Kurve genügen.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./stat-tests-chi-test.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Der <span class="math inline">\(\mathcal{X}^2\)</span>-Test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stat-tests-pretest.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Pre-Tests oder Vortest</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>