```{r}
#| echo: true
#| message: false
#| warning: false

cutting_raw_tbl <- read_excel("data/cutting_data.xlsx") %>% 
  clean_names()
```

```{r}
#| echo: true
#| message: false
#| warning: false

cutting_tbl <- cutting_raw_tbl %>% 
  pivot_longer(cols = shoot_1:fruit_8, 
               names_to = c("outcome", "week"), 
               names_sep = "_",
               values_to = "rsp") %>% 
  arrange(outcome, week, trt, block, rsp) %>% 
  mutate(block = as_factor(block),
         trt = as_factor(trt),
         outcome = as_factor(outcome),
         week = as.numeric(week))
```

```{r}
#| echo: true
#| message: false
#| warning: false
#| label: fig-app-exp-cutting-01
#| fig-align: center
#| fig-height: 12
#| fig-width: 12
#| fig-cap: "Abbildung der vier Outcomes über die acht Messtermine mit den vier Behandlungen und den zwei Blöcken.."
#| column: page

cutting_plot_tbl <- cutting_tbl %>% 
  mutate(outcome = recode(outcome, 
                          shoot = "Trieblänge", 
                          flower = "Blütenanzahl", 
                          leaf = "Blätteranzahl", 
                          fruit = "Fruchtanzahl"))

cutting_plot_tbl %>% 
  ggplot(aes(week, rsp, color = trt, linetype = block)) +
  theme_minimal() +
  facet_wrap(~ outcome, scales = "free_y") +
  geom_point() +
  stat_smooth(se = FALSE) +
  scale_color_okabeito()
```

[Correlation plot in R](https://r-coder.com/correlation-plot-r/)

```{r}
cutting_cor_tbl <- cutting_tbl %>% 
  filter(week %in% c(6, 7, 8)) %>% 
  pivot_wider(names_from = outcome, values_from = rsp) %>% 
  unnest()
```

```{r}
#| echo: true
#| message: false
#| warning: false
#| label: fig-app-exp-cutting-02
#| fig-align: center
#| fig-height: 5
#| fig-width: 5
#| fig-cap: "Abbildung der Scatterplots, Histogramme und Korrelation zwischen den vier Outcomes."

cutting_cor_tbl %>% 
  select(flower:shoot) %>% 
  pairs.panels(smooth = TRUE, density = TRUE, method = "kendall", lm = FALSE, 
               cor = TRUE, ellipses = FALSE, stars = TRUE)    
```

### Trieblänge

```{r}
shoot_length_tbl <- cutting_tbl %>% 
  filter(outcome == "shoot" & week == 8)
```

```{r}
shoot_length_fit <- lm(rsp ~ trt + block, data = shoot_length_tbl)
```

```{r}
shoot_length_fit %>% 
  anova() %>% 
  model_parameters()
```

```{r}
shoot_emm_obj <- shoot_length_fit %>% 
  emmeans(specs = ~ trt) 
```

```{r}
shoot_emm_obj %>% 
  contrast(method = "pairwise", adjust = "bonferroni")
```

```{r}
shoot_emm_obj %>%
  cld(Letters = letters, adjust = "bonferroni") 
```

### Blütenanzahl

```{r}
flowers_tbl <- cutting_tbl %>% 
  filter(outcome == "flower" & week == 8)
```

```{r}
flowers_fit <- glm(rsp ~ trt + block, data = flowers_tbl, family = quasipoisson())

```

```{r}
flowers_fit %>% 
  car::Anova() %>% 
  model_parameters()
```

```{r}
flowers_emm_obj <- flowers_fit %>% 
  emmeans(specs = ~ trt) 
```

```{r}
flowers_emm_obj %>% 
  contrast(method = "pairwise", adjust = "bonferroni") 

```

```{r}
flowers_emm_obj %>%
  cld(Letters = letters, adjust = "bonferroni") 
```

### Blätteranzahl

```{r}
leaf_tbl <- cutting_tbl %>% 
  filter(outcome == "leaf" & week == 8)
```

```{r}
leaf_fit <- lm(rsp ~ trt + block, data = leaf_tbl)
```

```{r}
leaf_fit %>% anova()
```

```{r}
leaf_emm_obj <- leaf_fit %>% 
  emmeans(specs = ~ trt)
```

```{r}
leaf_emm_obj %>% 
  contrast(method = "pairwise", adjust = "bonferroni") 
```

```{r}
leaf_emm_obj %>%
  cld(Letters = letters, adjust = "bonferroni") 
```

### Fruchtanzahl

```{r}
fruit_tbl <- cutting_tbl %>% 
  filter(outcome == "fruit" & week == 8)
```

```{r}
fruit_fit <- glm(rsp ~ trt + block, data = fruit_tbl, family = quasipoisson())
```

```{r}
fruit_fit %>% 
  car::Anova() %>% 
  model_parameters()
```

```{r}
fruit_emm_obj <- fruit_fit %>% 
  emmeans(specs = ~ trt) 
```

```{r}
fruit_emm_obj %>%  
  contrast(method = "pairwise", adjust = "bonferroni") 
```

```{r}
fruit_emm_obj %>%  
  cld(Letters = letters, adjust = "bonferroni") 
```
