::: callout-important
## Worte und Bedeutungen im statistischen Modellieren

> *"Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt." --- Ludwig Wittgenstein*

Hier kommt einmal die Tabelle mit den wichtigsten Begriffen im statistischen Modellieren und wie ich die Worte benutzen werde. Damit wir uns verstehen und du was lernen kannst. In anderen Büchern und Quellen findest du teilweise die Worte in einem anderen Sinnzusammenhang. Das ist gut so dort. Bei mir ist es anders.

|   | Symbol | Deutsch | Englisch |
|----|:--:|----|----|
| *LHS* | $Y$ / $y$ | **Messwert** / Endpunkt | Response / outcome / endpoint |
| *RHS* | $X$ / $x$ | **Einflussvariable** / Erklärende Variable / Fester Effekt | risk factor / explanatory / fixed effect |
| *RHS* | $Z$ / $z$ | **Zufälliger Effekt** | Random effect |
| $X$ ist kontinuierlich | $c_1$ | **Kovariate** 1 | Covariate 1 |
| $X$ ist kategorial | $f_A$ | **Faktor** $A$ mit Level $A.1$ bis $A.j$ | Factor $A$ with levels $A.1$ to $A.j$ |

: Zusammenfassende Tabelle des Sprachgebrauchs in meinem statistischen Modellieren. Die *fett* hervorgehobenen Bezeichnungen werden hier genutzt. {#tbl-namen-regression tbl-colwidths="$$14, 10, 38, 38$$"}
:::
